### ISSUE TITLE
crash with methane

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#100]
### Mod Name

methane

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/methane

### Describe the bug

crash at start

### Steps to reproduce

1. have ffapi, connector, methane
2. run
3. see

### Logs

https://pastebin.com/xMhZXFQW

**Comment by coco875** [comment]
strange with cloth config it work so i don't know if it's stay an issue or not

**Comment by coco875** [comment]
by with cloth config I mean by enable cloth config it work

**Comment by Su5eD** [comment]
I checked the mod jar, and it doesn't declare a dependency on cloth config despite requiring it. This should be reported to the mod author.
