### ISSUE TITLE
Crashes upon chunk generation

### ISSUE THREAD

**Issue by Insan1tz** [Sinytra/Connector#1000]
### Mod Name

Terralith

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/terralith

### Minecraft version

1.20.1

### Describe the bug

It appears that the Terralith (forge) mod is somehow incompatible with Sinytra Connector. As soon as Terralith is removed the game does not crash upon initialization.

### Steps to reproduce

1. Install
2. Run create a new world
3. Crash

### Logs

https://pastebin.com/pfjAbewx

**Comment by RoomAlex68** [comment]
The Fabric version of Terralith should work with Connector

**Comment by Insan1tz** [comment]
Still crashes with Fabric ver

**Comment by Su5eD** [comment]
The Forge version of Terralith works perfectly fine. Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
