### ISSUE TITLE
Continuity no longer connects textures with Blueprint and and latest Forgified Fabric API 

### ISSUE THREAD

**Issue by silverbull14** [Sinytra/Connector#1001]
### Mod Name

Continuity

### Mod Homepage

https://modrinth.com/mod/continuity

### Minecraft version

1.20.1

### Describe the bug

Continuity no longer connects textures even if Lazurite and built-in resource packs have been included

### Steps to reproduce

1. Install the following mods:
    - fabric-api-0.92.1+1.11.5+1.20.1
    - Connector-1.0.0-beta.41+1.20.1
    - ConnectorExtras-1.10.0+1.20.1
    - continuity-3.0.0-beta.4+1.20.2
    - lazurite-1.0.4+mc1.20.1
    - embeddium-0.3.12+mc1.20.1
    - blueprint-1.20.1-7.0.3
2. Include built-in connected textures resource pack of Continuity.

### Logs

None

### Additional context

![Minecraft Forge_ 1 20 1 2024_4_12 下午 11_19_58](https://github.com/Sinytra/Connector/assets/147660659/53543511-3ab1-41dc-8267-4a7d021b470e)
![Minecraft Forge_ 1 20 1 2024_4_12 下午 11_19_49](https://github.com/Sinytra/Connector/assets/147660659/143c3798-dc3b-42b3-a8e5-b20b6bb8179e)

**Comment by Tapacywka** [comment]
I can confirm that. If you remove Blueprint from the mod list, everything works fine.
P.S: Also tested on the latest beta version of Connector (b42 build #613).
![image](https://github.com/Sinytra/Connector/assets/71761232/aa50d853-8f5b-4591-9212-3e4dfecaa0c7)

**Comment by RoomAlex68** [comment]
May I ask you, what's the mod that shows the arrow pouch and the little backpack icon?

**Comment by Ezoteric** [comment]
> May I ask you, what's the mod that shows the arrow pouch and the little backpack icon?

This is the mod that shows all that stuff

https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge

**Comment by Pnaabnloo** [comment]
> I can confirm that. If you remove Blueprint from the mod list, everything works fine. P.S: Also tested on the latest beta version of Connector (b42 build #613). ![image](https://private-user-images.githubusercontent.com/71761232/322055176-aa50d853-8f5b-4591-9212-3e4dfecaa0c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyOTMzMzMsIm5iZiI6MTcxMzI5MzAzMywicGF0aCI6Ii83MTc2MTIzMi8zMjIwNTUxNzYtYWE1MGQ4NTMtOGY1Yi00NTkxLTkyMTItM2U0ZGZlY2FhMGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE4NDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNzBkNDQyNTdlOTdjNmVjNGFhMzEwNzQ2MzRmYjZlMDgzZDQ2MmI3MGI2NWQwMTEwZDhiY2NmZjRlODNiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ogf7kWk-6uuROV7VgfhDFHZJhmuiCfKCqM4Bdkq53N4)

What texture pack adds the grass overlay?

**Comment by RoomAlex68** [comment]
Continuity

**Comment by silverbull14** [comment]
> This appears to be a conflict between the two mods. if I recall correctly, blueprint replaces minecraft's resource manager with its own, as well as making several other changes to the model system, which eventually cause continuity to stop working. Unfortunately, this cannot be fixed on our side.

I see,thank you for responding.

**Comment by QianFuv** [comment]
https://www.curseforge.com/minecraft/mc-mods/blueprint-texture-issue-fix
fix mod here
