### ISSUE TITLE
Mythic upgrades doesn't work with connector

### ISSUE THREAD

**Issue by MikroChris** [Sinytra/Connector#1005]
### Mod Name

Mythic upgrades

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mythic-upgrades

### Minecraft version

1.20.1

### Describe the bug

The mod Mythic upgrades on versions above 2.3.2 don't work with the connector anymore

### Logs

https://gist.github.com/MikroChris/18f7017de16c7488e7d4976cd568394f

### Additional context

The connector only works with the 2.3.2 version, but after that version it stopped working, I installed only the mod and the connector but nothing changed, doesn't even give me a crash report, only Error code 1

**Comment by RoomAlex68** [comment]
It also crashes with it's dependency mod "TriQue" on later versions due to it being outdated for older Fabric 1.20.1 versions
