### ISSUE TITLE
[Incompat] Tierify does not work

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#1007]
### Mod Name

Tierify

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/tierify

### Minecraft version

1.20.1

### Describe the bug

Crash on start-up

### Steps to reproduce

1. Install Tierify
2. Install Necronomicon API (dependency)
3. Launch

### Logs

https://gist.github.com/Cixon/9b95e62bec2238a5d0e2c64f5681c5bc

### Additional context

Using Connector-1.0.0-beta.41+1.20.1

Neoforge - 47.1.99

**Comment by Cixon** [comment]
Extra context:

dependency works just fine alone // Tierify seems to be the issue
https://legacy.curseforge.com/minecraft/mc-mods/necronomicon

**Comment by Su5eD** [comment]
Moved to #1044, which better describes the issue
