### ISSUE TITLE
Kibe incompatibility

### ISSUE THREAD

**Issue by linaraincalzando** [Sinytra/Connector#1009]
### Mod Name

Kibe

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/kibe

### Minecraft version

1.20.1

### Describe the bug

Kibe compatibility

### Steps to reproduce

1.Use Kibe and needed library with Sinytra connector
2. 
3.
...

### Logs

https://paste.atlauncher.com/view/4d89b981-b163-47b1-b755-79cd7cd34644

### Additional context

I did find a Git Issue with the same error with Kibe with https://github.com/lucaargolo/kibe/issues/12#issuecomment-690353809
and a corresponding issue on immersive portals https://github.com/iPortalTeam/ImmersivePortalsMod/issues/424

**Comment by Flexico** [comment]
Ah, good! Glad the devs are aware of this.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
