### ISSUE TITLE
[Bug] Fabric Version format Incompatable with Forge

### ISSUE THREAD

**Issue by SaltSouls** [Sinytra/Connector#1011]
### Mod Name

Frights Delight

### Mod Homepage

https://modrinth.com/mod/frights-delight

### Minecraft version

1.20.1

### Describe the bug

Fabric mods that contain non-numeric characters in their version cause the game to crash upon starting due to forge not accepting any non-numeric characters in their version semantic formatting.

### Steps to reproduce

1. Install connector
2. Install a fabric mod that uses non-numeric characters in the version
3. Launch the game
4. Crash
5. ???
6. Profit
...

### Logs

https://gist.github.com/SaltSouls/822de341e1ac5574cdc812a15d5e0bac

**Comment by RoomAlex68** [comment]
This also happens with Brewin and Chewin, Farmer's Respite, Cultural Delight, Farmer's Knives [Fabric], Ube's Delight [Fabric] and Expanded Delight [Fabric]

**Comment by SaltSouls** [comment]
> This also happens with Brewin and Chewin, Farmer's Respite, Cultural Delight, Farmer's Knives [Fabric], Ube's Delight [Fabric] and Expanded Delight [Fabric]

Yup, it is just a general error, not specifically farmers delight related. Any mod that has something like `fabric-1.0.1` as the version will run into this issue.

**Comment by RoomAlex68** [comment]
Yeah, this happens with Mythic Upgrades dependency mod "TriQue"

**Comment by Su5eD** [comment]
This has already been taken care of. If a mod's version does not match the expected format, we let FML assign it a default version number.

https://github.com/Sinytra/Connector/blob/5bbe56f2a51c7ef69e876202525ae0e1ebb3210c/src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorModMetadataParser.java#L55-L60

![image](https://github.com/Sinytra/Connector/assets/51261569/cae0f349-c484-46b7-b963-e15cacea3d6d)
