### ISSUE TITLE
Ecologics Fabric crahes on Beta 42, doesnt on Beta 41

### ISSUE THREAD

**Issue by 3ncanis** [Sinytra/Connector#1014]
### Mod Name

Ecologics

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/ecologics

### Minecraft version

1.20.1

### Describe the bug

Crash to desktop when trying to start game when using Ecologics Fabric 1.20.1. Didn't happen on Beta 41. 

### Steps to reproduce

1. Install Sinytra Connector Beta 42/Forgified Fabric API 0.92.1+1.11.7
2. Install Ecologics
3. Launch game
...

### Logs

https://mclo.gs/aTksTkU

### Additional context

Didn't generate a crash log so I just uploaded the log that generates when I attempt to launch the game

**Comment by RoomAlex68** [comment]
Ecologics Forge works on Connector Beta 42

**Comment by 3ncanis** [comment]
Yeah, the fabric version has a better config file with more options though, specifically options to disable certain features of the mod I prefer disabled
