### ISSUE TITLE
Meal API Server Incompatiblity

### ISSUE THREAD

**Issue by aking4125** [Sinytra/Connector#1016]
### Mod Name

Meal API

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/meal-api

### Minecraft version

1.20.1

### Describe the bug

Crash on Server. Works on Client.

### Steps to reproduce

[crash-2024-04-17_10.15.25-fml.txt](https://github.com/Sinytra/Connector/files/15012405/crash-2024-04-17_10.15.25-fml.txt)

### Logs

https://gist.github.com/aking4125/49545242c9babbee46c90bb35e563b7d

**Comment by Su5eD** [comment]
> Failure message: Some of your mods are incompatible with the game or each other!
		A potential solution has been determined, this may resolve your problem:
		   - Install botanytrees, version 9.0.0 or later.
		More details:
		   - mod Bewitchment Tree Pots (bewitchment_tree_pots) 1.0 requires version 9.0.0 or later of botanytrees, which is missing!

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by aking4125** [comment]
[debug.log](https://github.com/Sinytra/Connector/files/15015266/debug.log)

[latest.log](https://github.com/Sinytra/Connector/files/15015268/latest.log)

Re-done with just: 

Forge 47.1.3 
Connector-1.0.0-beta.42+1.20.1
ConnectorExtras-1.10.0+1.20.1
fabric-api-0.92.1+1.11.7+1.20.1
mealapi-0.3.2+1.20
