### ISSUE TITLE
Hybrid Aquatic Crash on Startup

### ISSUE THREAD

**Issue by cal1407** [Sinytra/Connector#1017]
### Mod Name

Hybrid Aquatic

### Mod Homepage

https://modrinth.com/mod/hybrid-aquatic

### Minecraft version

1.20.1

### Describe the bug

Game crash on startup

### Steps to reproduce

1. Launch the game with only Connector (and its requirements) and Hybrid Aquatic
2. .Game would crash on the loading screen
...

### Logs

https://pastebin.com/P1j7tJvf

### Additional context

Crash log: https://pastebin.com/kW3NpLvC

**Comment by Su5eD** [comment]
Duplicate of #231
