### ISSUE TITLE
Hexed crashes during launch

### ISSUE THREAD

**Issue by platonicnymph** [Sinytra/Connector#1020]
### Mod Name

Hexed

### Mod Homepage

https://modrinth.com/mod/hexed

### Minecraft version

1.20.1

### Describe the bug

The Hexed fabric mod crashes during launch with Sinytra Connector.

### Steps to reproduce

1. Install these versions of the following mods in a fresh **Forge 1.20.1** profile:
 - Connector-1.0.0-beta.42+1.20.1.jar (https://modrinth.com/mod/connector/versions)
 - fabric-api-0.91.0+1.20.1.jar (https://modrinth.com/mod/fabric-api/versions)
 - fabric-api-0.92.1+1.11.7+1.20.1.jar (https://modrinth.com/mod/forgified-fabric-api/versions)
 - fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar (https://modrinth.com/mod/fabric-language-kotlin/versions)
 - hexed-0.8.1H.jar (https://modrinth.com/mod/hexed/versions)

![image](https://github.com/Sinytra/Connector/assets/118676268/c551458f-8f0b-4466-ad6f-380b75689b78)

2. Run the profile and obtain the following error logs:
 - Latest.log (https://mclo.gs/8kRgAMW)
 - Debug.log (https://mclo.gs/mfDtLky)

![image](https://github.com/Sinytra/Connector/assets/118676268/e7b64490-065d-4606-b74a-a75722f37f86)

### Logs

https://mclo.gs/8kRgAMW https://mclo.gs/mfDtLky

**Comment by MrRain139** [comment]
У меня он нормально работает

**Comment by MrRain139** [comment]
I'm hexed, it works.

**Comment by platonicnymph** [comment]
Should be noted that this error apparently only occurs in forge versions after ~47.1.28ish.
