### ISSUE TITLE
Iris and sodium compat crash

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#1027]
### Mod Name

iris and sodium 

### Mod Homepage

https://modrinth.com/mod/sodium                     https://modrinth.com/mod/iris

### Minecraft version

1.20.1

### Describe the bug

crashes when i launch a instance

### Steps to reproduce

1. add connector to your a curseforge profile 
2. then add iris and sodium latest 1.20.1 version 
3. click play then it will have a error during mod loading.
...

### Logs

https://gist.github.com/Thunderrock424242/830592c47c7acfbf14a4d2c00eff8056

### Additional context

![Screenshot 2024-04-22 144431](https://github.com/Sinytra/Connector/assets/119463825/04c0c09b-e84f-433d-9f62-33d3a5324dcb)
forge 47.2.0
mc 1.20.1

**Comment by Thunderrock424242** [comment]
Oculus doesn't do full ports of iris tho

**Comment by RoomAlex68** [comment]
Connector does not support Iris and Sodium
