### ISSUE TITLE
Bewitchment Crashes on Start

### ISSUE THREAD

**Issue by qoolguy** [Sinytra/Connector#1034]
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Minecraft version

1.20.1

### Describe the bug

Bewitchment crashes on startup with Sinytra Connector and Forgified Fabric API.

### Logs

https://mclo.gs/tK8EjSp

**Comment by Su5eD** [comment]
Confirmed to work on both beta 42 and the latest dev build

**Comment by EndangeredNayla** [comment]
Wrong it ONLY works on 47.1.3
