### ISSUE TITLE
When I log into minecraft, a warning about outdated connector_global_mod_aliases appears a configuration file in json format was found

### ISSUE THREAD

**Issue by Trojankill** [Sinytra/Connector#1036]
### Minecraft version

1.20.1

### Describe the bug

Writes that the connector config is outdated

### Steps to reproduce

1.
2.
3.
...

### Additional context

![Java-runtime-gamma Screenshot 2024 04 24 - 13 20 14 42](https://github.com/Sinytra/Connector/assets/165274601/3d7f1e0b-7448-4461-8575-783c3d71ddb7)
Who knows how to disabling notification?

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin

**Comment by coco875** [comment]
![image](https://github.com/Sinytra/Connector/assets/59367621/784378ce-f660-4380-b078-637d0b2b2baf)
the llink: https://sinytra.org/docs/connector/configuration
