### ISSUE TITLE
Astrocraft mixin conflicts with Citadel

### ISSUE THREAD

**Issue by platonicnymph** [Sinytra/Connector#1039]
### Mod Name

Astrocraft

### Mod Homepage

https://modrinth.com/mod/astrocraft

### Minecraft version

1.20.1

### Describe the bug

Running Astrocraft with Connector creates a mixin conflict with Citadel

### Steps to reproduce

1. Create the following **Forge 1.20.1 47.2.17** profile: 
 - https://modrinth.com/mod/astrocraft
 - https://modrinth.com/mod/citadel
 - https://modrinth.com/mod/cloth-config
 - https://modrinth.com/mod/forgified-fabric-api
 - https://modrinth.com/mod/connector

![image](https://github.com/Sinytra/Connector/assets/118676268/dfc9a420-0f49-4ac3-a48e-91ad29a10ba8)

2. Run the profile and obtain the following error log:
![image](https://github.com/Sinytra/Connector/assets/118676268/8e278d12-93e8-4b7b-b253-95778dcfa8fb)

Latest.log: https://mclo.gs/pijNzW9
Debug.log: https://mclo.gs/pjirtUC

### Logs

https://mclo.gs/pijNzW9 https://mclo.gs/pjirtUC

**Comment by Su5eD** [comment]
This is a conflict between the 2 mods that we cannot fix on your side. I recommend asking the astrocraft or citadel devs about considering alternative approaches to the mixin injector that would allow using these mods together.
