### ISSUE TITLE
Minecraft crashes on startup with FREX

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#104]
### Mod Name

FREX

### Mod Homepage

https://modrinth.com/mod/frex/versions

### Describe the bug

Minecraft crashes on startup with FREX

### Logs

https://mclo.gs/ZFD13c6

**Comment by Su5eD** [comment]
I've looked at the conflicting mixin, and it appears to be redirecting a forge render method call to its own system, which is going to break mods that rely on it. Unfortunately, frex can not be made compatible without a dedicated port.
