### ISSUE TITLE
Meal API doesnt work in singleplayer and crashes on server (?)

### ISSUE THREAD

**Issue by milkev** [Sinytra/Connector#1048]
### Mod Name

Meal API

### Mod Homepage

https://modrinth.com/mod/mealapi

### Minecraft version

1.20.1

### Describe the bug

In singleplayer, the game loads but meal api does not seem to work. When attempted to load on a server, it crashes.

### Steps to reproduce

Singleplayer;
1. Load into game with meal api and a mod which utilizes it (in this case i am using [Meal Api Addon](https://modrinth.com/mod/meal-api-addon))
2. attempt to gain fullness (meal api's additional food meter). in this case with meal api addon i attempted this using the saturation effect, which in a fabric only environment quickly fills up the fullness meter
3. observe fullness meter does not fill at all

Server;
Saw in #1016 that it crashes on the server, but was unable to replicate as i couldnt get the forge server installed ,-, this issue was closed due to being invalid but was quickly responded to with a valid entry however has remained closed for 2 weeks hence why im posting this slightly different issue here instead of in that issue.

### Logs

https://pastebin.com/jZ1f6gcP - singleplayer

### Additional context

Singleplayer used the following mods;
Forge 47.1.3
Sinytra 1.0.0-Beta43
Forgified Fabric Api 0.92.1+1.11.7
Meal Api 0.3.2
Meal Api Addon 1.0.1

**Comment by milkev** [comment]
id like to know why it posted as i closed google chrome to restart my pc but ok

**Comment by milkev** [comment]
should be good now

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
