### ISSUE TITLE
Fabric Version of Backported Wolves Causes the Game to Crash

### ISSUE THREAD

**Issue by Daralexen05** [Sinytra/Connector#1049]
### Mod Name

Backported Wolves

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/backported-wolves

### Minecraft version

1.20.1

### Describe the bug

The game crashes upon startup

### Steps to reproduce

1. Install the required mods with Forge as the client
2. Run the game only to see it crash

### Logs

https://gist.github.com/Daralexen05/42c05eeafda677438d026d4b13a40178#file-gistfile1-txt

### Additional context

My modlist:
Alex's Mobs
Backported Wolves
Architectury
Citadel
Citreswen
Cloth Config
Synta Connector
Console Sounds
Entity Model Features
Entity Texture Features
Essential
Fabric API
Fireflies
Friends & Foes
JEI
Modern Beta
Nostalgic Tweaks
Occulus
Old Potions
Paper Doll
Player Animation
Puzzles Lib
Raised
Rubidium
Sodium
What Are You Voting For 2023
Xaeros Minimap
Xaeros Woldmap

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by Daralexen05** [comment]
> Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.
> 
> > Before reporting, please ensure that:
> > 
> > * You've installed a **minimal set of mods** required to reproduce the issue.
> >   Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
> >   Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
> >   If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
> >   repeatedly until the faulty mod is found.

Can I attempt this again with just Syntra and Fabric version of Backported Wolves? The Forge version of Backported Wolves does not cause a crash.

**Comment by WittgensteinChoso** [comment]
It also happens in Forge, When taming a wolf closes the game I tried it several times
