### ISSUE TITLE
Fabric Language Kotlin and mods that require it

### ISSUE THREAD

**Issue by awesomebossdj7** [Sinytra/Connector#1050]
### Mod Name

Fabric Language Kotlin

### Mod Homepage

https://modrinth.com/mod/fabric-language-kotlin/version/1.10.19+kotlin.1.9.23

### Minecraft version

1.20.1

### Describe the bug

connector has kotlin for forge built in, some mods require Fabric Language Kotlin, if you dont install fabric language kotlin it wont launch.

### Steps to reproduce

1. Install fabric Language kotlin (and mod that needs it if you want to)
2. launch game with connector
3. crash

### Logs

https://gist.github.com/awesomebossdj7/128070a92dd980bea97bc7ad812e88f9

### Additional context

you MIGHT be able to make those mods not require it just by jar editing, which should be simple for connector to do (since it literally modifies fabric mods)

**Comment by awesomebossdj7** [comment]
well i dont have kotlin for forge installed, and i saw in the logs connector talking about kotlin, and i remove connectorextras to make sure it wasnt that.

**Comment by awesomebossdj7** [comment]
also what i meant by jar editing is turning file into zip and removing kotlin dependecy, which did not work, for industrial revolution

**Comment by Su5eD** [comment]
> connector has kotlin for forge built in

Pretty sure it doesn't? Fabric Language Kotlin works perfectly fine on forge. Please list what mods you're using as given in the issue template.

**Comment by awesomebossdj7** [comment]
oh my bad, one of the mods has kotlin for forge built in im guessing

let me send a list hold on

**Comment by awesomebossdj7** [comment]
AdvancedReborn-1.20.1-1.2.8
architectury-9.2.14-forge
artifacts-forge-9.5.0
cc-tweaked-1.20.1-forge-1.110.3
cloth-config-11.1.118-forge
cofh_core-1.20.1-11.0.0.51
Connector-1.0.0-beta.42+1.20.1
ConnectorExtras-1.10.1+1.20.1
Controlling-forge-1.20.1-12.0.2
curios-forge-5.9.0+1.20.1
emi-1.1.4+1.20.1+forge
EnderIO-1.20.1-6.0.25-alpha
EnhancedQuarries-1.4.5
essential_1-3-1-1_forge_1-20-1
expandability-9.0.3
fabric-api-0.92.1+1.11.8+1.20.1 (forgified fabric)
fabric-language-kotlin-1.10.19+kotlin.1.9.23
f-tech_robots-1.0-rc.7
FTechCore-1.0-rc.9
indrez-1.16.5-BETA-Hotfix
industrial-foregoing-1.20.1-3.5.16
inmis-2.7.2-1.20.1
mcpitanlib-2.2.4-1.20.1-fabric
MouseTweaks-forge-mc1.20-2.25
Nameless Trinkets-1.20.1-1.7.8
Patchouli-1.20.1-84-FABRIC
RebornCore-5.8.7
Scout-2.0.4+1.20.1
Searchables-forge-1.20.1-1.0.3
sophisticatedbackpacks-1.20.1-3.20.5.1044
sophisticatedcore-1.20.1-0.6.21.609
TechReborn-5.8.7
thermal_cultivation-1.20.1-11.0.0.22
thermal_dynamics-1.20.1-11.0.0.21
thermal_expansion-1.20.1-11.0.0.27
thermal_foundation-1.20.1-11.0.2.64
thermal_innovation-1.20.1-11.0.0.21
thermal_locomotion-1.20.1-11.0.0.17
titanium-1.20.1-3.8.27
trinkets-3.7.2
xp_storage-1.5.7+1.20.1

**Comment by awesomebossdj7** [comment]
ill send full log too, so we can both look over
https://paste.atlauncher.com/view/01c7d7ce-c2fe-44b3-9f1d-0a9cb24a4e4c

**Comment by awesomebossdj7** [comment]
[log.txt](https://github.com/Sinytra/Connector/files/15148470/log.txt)
lemme upload log

(i censored my user)

**Comment by awesomebossdj7** [comment]
ah, it was essential mod, should i make a new issue?
https://www.curseforge.com/minecraft/mc-mods/essential-mod

**Comment by awesomebossdj7** [comment]
its compatible with connector (if u download forge) but if you try to use it with a fabric language kotlin, it doesnt like it

essential does have fabric version however

**Comment by Su5eD** [comment]
After looking at the layout of essential's jar file, it appears that they're using a custom mechanism to load KFF at runtime, since bundling KFF as a regular jar would result in a crash as described in MinecraftForge/MinecraftForge#8878.

Unfortunately, due to Essential's closed source nature, I'm not able to further determine the exact cause of the issue. However, it is apparent that this is a result of the custom KFF loader, as KFF itself works normally alongside Fabric Language Kotlin when loaded from the top level (mod folder file).
