### ISSUE TITLE
Mod "Bewitchment" crashes with exit code 1

### ISSUE THREAD

**Issue by nyancatkitty** [Sinytra/Connector#1058]
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Minecraft version

1.20.1

### Describe the bug

Every time Bewitchment is on the game will crash during the "Minecraft: forge loading" part and goes to launcher with exit code 1 

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/nyancatkitty/2cd02bbde6ab850f8cf77b6f9823d136

### Additional context

I am using the latest bewitchment version (bewitchment-1.20-8.jar) and minecraft version 1.20.1 with forge 47.1.3, It is only when I have bewitchment on is when the game crashes, The mods that is needed for bewitchment works perfectly fine when bewitchment isn't on, I did try on a spare modpack with the same forge version to see if it would work but it is still the same it crashed when bewitchment is on, I have seen a issue already for this type of thing but I didn't see anything on how to fix it
(Also with the logs, I am not exactly sure if I did it correctly, I am new with the uploading log stuff)

**Comment by nyancatkitty** [comment]
bit of an edit: I tried using beta 42 that was said that it works and it is still the same for me

**Comment by nyancatkitty** [comment]
Another edit: I added "connecter extras" and it seems to work now

**Comment by jaesunn** [comment]
How did you get it to work? this is my modlist and havent managed to get it working. Also on Forge 47.1.3
![modlist](https://github.com/Sinytra/Connector/assets/44533899/b2201cfd-715e-460d-9ebc-db68bf810e8d)

**Comment by LLjo** [comment]
I wonder too

**Comment by JarodNms** [comment]
> I wonder too

You Have to use  forge 47.1.3 :).

**Comment by lunaberryyyy** [comment]
> Another edit: I added "connecter extras" and it seems to work now

does it still work for you i cant get it working forge 47.1.3 
![image](https://github.com/Sinytra/Connector/assets/137470430/40b84d8e-a562-433f-bba0-e0e46c03d236)

**Comment by KultidGames** [comment]
@lunaberryyyy @JarodNms @jaesunn @nyancatkitty
Replicated using:
- **Forge 47.1.30**
- Bewitchment- 1.20-7
- Cloth Config 11.1.118-forge
- Connector-1.0.0-beta43
- **ConnectorExtras-1.10.1**
- FabricAPI 0.92.2+1.11.8
- Patchouli-1.20.1-84-Forge
- Pehkui-3.8.0+1.20.1-forge
- trinkets-3.7.1

Unable to launch, returned with Exit Code: 1

However, I am able to launch using the aforementioned versions and NeoForge- 47.1.30. In this version, you are able to progress through the mods without much interference— save for vampirism, which will crash your game due with an "InGameHudMixin is invalid" error.
