### ISSUE TITLE
[Forge] Incompatible with Rubidium 0.6.5

### ISSUE THREAD

**Issue by Sooperfish** [Sinytra/Connector#106]
### Mod Name

Rubidium

### Mod Homepage

https://modrinth.com/mod/rubidium

### Describe the bug

Crash with Rubidium 0.6.5

### Steps to reproduce

1. Install Rubidium 0.6.5
2. Install Forgified and Connector
(on 1.20.1 with Forge 47.1.3)
3. Attempt to run

### Logs

https://mclo.gs/3fHygCi

### Additional context

Seems to be fixed by updating Rubidium, but ≥0.7.0 is incompatible with Oculus for the moment

**Comment by Lolothepro** [comment]
Duplicate of https://github.com/Sinytra/Connector/issues/39

**Comment by Sooperfish** [comment]
Ah, mb
