### ISSUE TITLE
Rendering issue with Catwalks LLC

### ISSUE THREAD

**Issue by Derpacito** [Sinytra/Connector#1061]
### Mod Name

Catwalks LLC

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/catwalks-llc

### Minecraft version

1.20.1

### Describe the bug

Rendering error when trying to launch minecraft

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/nDZ9aJm

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
