### ISSUE TITLE
Incompatible with Marium's Soulslike Weaponry Mod

### ISSUE THREAD

**Issue by assomed00011** [Sinytra/Connector#1064]
### Mod Name

Marium's Soulslike Weaponry

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry

### Minecraft version

1.20.1

### Describe the bug

Crash while loading mod.

### Steps to reproduce

After installing Marium's Soulslike Weaponry Mod and its pre mods, crashes when loading mods.
Confirmed to be unrelated to the fabric version of the geckolib mod (this is a prerequisite mod for Marium's Soulslike Weaponry Mod, and there are no issues running this mod separately).

### Logs

https://gist.github.com/assomed00011/ab1a54c5d77d478cdcb4219da56a66d3

**Comment by RoomAlex68** [comment]
Marium’s Soulslike Weaponery works for me on Connector Beta 43

**Comment by Su5eD** [comment]
You need to use the Fabric version of Geckolib to run Soulslike Weaponry, see #231 for details.
