### ISSUE TITLE
aeroblender + regions unexplored + sinytra causes the game to hang at common setup phase

### ISSUE THREAD

**Issue by RexkUr** [Sinytra/Connector#1067]
### Mod Name

aeroblender and regions unexplored

### Mod Homepage

https://modrinth.com/mod/regions-unexplored and https://www.curseforge.com/minecraft/mc-mods/aeroblender

### Minecraft version

1.20.1

### Describe the bug

you boot the game with the mods and its dependencies installed and it will sometimes hang at common setup phase

### Steps to reproduce

1. download aeroblender + sinytra + regions unexplored with all its dependencies
2. boot game 
3.  game hangs at common setup 
...

### Logs

no output for logs since not considered a crash

### Additional context

sometimes will not hang other times will will have to repeat if it doesnt hang the first time 
i have confirmed it only happens with sinytra installed (no fabric mods loaded)

**Comment by Su5eD** [comment]
I tested this but was unable to reproduce the issue. Please provide your debug log.

**Comment by RexkUr** [comment]
https://mclo.gs/c71tOCP
this is the logs where i had to kill minecraft because it hanged

**Comment by Su5eD** [comment]
Are you sure this is the debug log? It only contains INFO lines. Also, I see you're on Forge 47.2.+ - try using 47.1.3 instead

**Comment by RexkUr** [comment]
how do i get the debug log?

**Comment by RexkUr** [comment]
how do i enable the debug log?

**Comment by RexkUr** [comment]
https://mclo.gs/GERzZlU figured it out, for some reason atlauncher doesnt output logs ,
i also downgraded forge like you asked and same results

**Comment by RexkUr** [comment]
to add to this it mainly breaks on forge i havent had the same issue happen in neoforge

**Comment by Xplodin** [comment]
that is odd, I have a 600+ mod modpack, and havent seen this issue, with those mentioned mods definitely in there.
Are you using fabric RU and aeroblender or forge?
Im using forge for both

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
