### ISSUE TITLE
Enchancements disallowed enchantments not working

### ISSUE THREAD

**Issue by Specimen-420** [Sinytra/Connector#1070]
### Mod Name

Enchancement

### Mod Homepage

https://modrinth.com/mod/enchancement

### Minecraft version

1.20.1

### Describe the bug

disbaled enchantments stilll show up

### Steps to reproduce

1. put an item in the enchantment table
2. You see disallowed enchantments in there
3. as well as enchantment books on the creative menu

### Logs

https://mclo.gs/suQDLKC

**Comment by Su5eD** [comment]
Duplicate of #745
