### ISSUE TITLE
Gravity Mod Incompatibility

### ISSUE THREAD

**Issue by EpicGageMAGEmc** [Sinytra/Connector#1072]
### Mod Name

Amethyst Gravity: Reattracted, and Gravity Changer (quoteall fork)

### Mod Homepage

https://modrinth.com/mod/gravity-api-fork, https://modrinth.com/mod/amethyst-gravity-reattracted

### Minecraft version

1.20.1

### Describe the bug

The game crashes on startup when only using these mods and the dependencies.

### Steps to reproduce

1. Install the mods
2. Launch the game
3. Crash

### Logs

https://mclo.gs/HpX1hQQ

**Comment by EpicGageMAGEmc** [comment]
for reference, the exact same mods, exact same versions work fine on fabric

**Comment by Liamgrayskull** [comment]
Can replicate this, although I think it's a duplicate

**Comment by Su5eD** [comment]
Duplicate of #135
