### ISSUE TITLE
Continuity does not work with Blueprint 

### ISSUE THREAD

**Issue by lovekoishi514** [Sinytra/Connector#1075]
### Minecraft version

1.20.1

### Describe the bug

Continuity does not work with Blueprint 

### Steps to reproduce

1.Install Embeddium Lazurite continuity and [blueprint](https://www.curseforge.com/minecraft/mc-mods/blueprint)
2.Start the game
3.continuity doesnt work though built-in resourcepacks are enabled
...

**Comment by Su5eD** [comment]
Duplicate of #1001
