### ISSUE TITLE
Crash with Clutter

### ISSUE THREAD

**Issue by chadzar** [Sinytra/Connector#108]
### Mod Name

Clutter

### Mod Homepage

https://modrinth.com/mod/clutter

### Describe the bug

Everthing in the mod works just fine but when the item Small Lily Pads appears on screen the game crashes

### Steps to reproduce

1. - Join or create a world with Clutter, Geckolib (Fabric), Forgified Fabric API and Sinytra Connector
2. - Open the inventory and go to the Clutter items tab in creative mode
3. - Go all the way down and the game instantly crashes.

### Logs

https://pastebin.com/nPjzAeC8

**Comment by Abbie5** [comment]
does it still crash if you use the forge version of geckolib?

**Comment by chadzar** [comment]
> does it still crash if you use the forge version of geckolib?

Yeah the game also crash with the forge version of geckolib
