### ISSUE TITLE
Irons Spells and Spellbooks (forge mod) possibly not seeing Gecko Lib (fabric mod)

### ISSUE THREAD

**Issue by sodanger** [Sinytra/Connector#1081]
### Mod Name

Irons Spells and Spellbooks

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

### Minecraft version

1.20.1

### Describe the bug

The bug seems to occur at any moment that you try to render the equipped armor from Irons Spells and Spellbooks.

### Steps to reproduce

1. Equip any Irons Spells and Spellbooks armor
2. See your character inside your inventory or go into 3rd person
3. Minecraft explodes

### Logs

https://gist.github.com/sodanger/a7a26e0b3dbfbee32162dcbe4d8bb9c9

### Additional context

Mods Installed:

Fabric:
Geckolib
AttributeFix
Marium's Soulslike Weaponry

Forge:
Connector
Connector Extras
Forgified Fabric API
Irons Spells and Spellbooks
Player Animator Lib
Curios
Caelus

Medal Clip of me recreating the crash:
https://medal.tv/games/minecraft/clips/2czkJAQt2Lxf6r/d1337Un9fmvl?invite=cr-MSxDa3MsODk1OTQ1MCw

**Comment by sodanger** [comment]
It actually seems like it does see Geckolib, but Geckolib no worky for some reason

**Comment by RoomAlex68** [comment]
Refer to issue to 231#

**Comment by sodanger** [comment]
> Refer to issue to #231

Ah yup thank you
