### ISSUE TITLE
Crash with Oculus

### ISSUE THREAD

**Issue by quackkky** [Sinytra/Connector#1083]
### Mod Name

Oculus

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/oculus

### Minecraft version

1.20.1

### Describe the bug

When starting the game with Oculus and the connector the game crashes.

### Steps to reproduce

1. Download Connector
2. Download Oculus
3. Put both in mod folder
4. Start the game
5. Crash

(I switched to the correct forge version, but the issue was still there

### Logs

https://gist.github.com/quackkky/af1b63e1a69f092b73821d2e739267f2

**Comment by Su5eD** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[`@At`("INVOKE")] on net/minecraft/client/renderer/LevelRenderer::iris$beginClouds with priority 1000 cannot inject into net/minecraft/client/renderer/LevelRenderer::m_253054_(Lcom/mojang/blaze3d/vertex/PoseStack;Lorg/joml/Matrix4f;FDDD)V merged by me.jellysquid.mods.sodium.mixin.features.render.world.clouds.WorldRendererMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.oculus.json:MixinLevelRenderer -> Prepare Injections ->  -> handler$bah000$iris$beginClouds(Lcom/mojang/blaze3d/vertex/PoseStack;Lorg/joml/Matrix4f;FDDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]

This doesn't seem related to Connector. You're also using multiple mods in addition to Oculus that are not mentioned in the issue description. Please verify that the issue occurs with only Connector and Oculus installed.

**Comment by quackkky** [comment]
hm, when I just started the Connector with Oculus/Embeddium and the Fabric mods, the game loaded fine. When i added all the other mods back, the game still started fine. Maybe the problem was me having a wrong version of either the connector or oculus, since I downloaded a new version before trying this. Thanks for the help!
