### ISSUE TITLE
Mindful Eating-Fabric crash w/ Farmer's Delight

### ISSUE THREAD

**Issue by Liamgrayskull** [Sinytra/Connector#1084]
### Mod Name

mindfuleating

### Mod Homepage

https://modrinth.com/mod/mindful-eating-fabric

### Minecraft version

1.20.1

### Describe the bug

Crash on worldload in survival

### Steps to reproduce

1. Load Sinytra Connector, FFAPI, Farmer's Delight, Diet API Fabric & Mindful Eating - Fabric 
2. Loads game successfully, regardless of 1.20.1 forge version
3. Game crashes with crash report on worldload due to a gui rendering error
4. "java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/registry/EffectsRegistry
	at com.minecraftabnormals.mindful_eating.client.HungerOverlay.drawHungerIcons(HungerOverlay.java:96) ~[mindful_eating-1.1.0_mapped_srg_1.20.1.jar%23327!/:?] {re:mixin,re:classloading}"
...
Crash report:
https://gist.github.com/Liamgrayskull/24e10fbf7680fbf2b684594613ce80f5

Debug.log:
https://gist.github.com/Liamgrayskull/3cf0a5d513c9eb47e28dedf1c6f56ddf
Latest.log:
https://gist.github.com/Liamgrayskull/a2cf510ba7371bdcd456c0917d95e312

### Logs

https://gist.github.com/Liamgrayskull/3cf0a5d513c9eb47e28dedf1c6f56ddf

### Additional context

occurs regardless of connector extra's presence, and using the forge version of Diet API causes an instantaneous crash

**Comment by Su5eD** [comment]
Mindful eating fabric is not compatible with Farmer's Delight for Forge. You should be able to disable this integration by hiding FD's presence using Connector's [hidden mods](https://sinytra.org/docs/connector/configuration#hiding-forge-mods-presence) config option. The modid for Farmer's Delight is `farmersdelight`.
