### ISSUE TITLE
minecells 1.8.0 crash

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#1085]
### Mod Name

Minecells

### Mod Homepage

https://modrinth.com/mod/minecells/version/1.8.0

### Minecraft version

1.20.1

### Describe the bug

crash on startup

### Steps to reproduce

doesn't crash with version 1.7.3, but with 1.8.0 it does. 

### Logs

https://gist.github.com/oof100200/a0bc60b478b1f0d6a6c3971154f3e2c3

**Comment by mim1q** [comment]
Found the culprit - MixinExtras' `@ModifyExpressionValue` mixins seem to crash Connector, while they work just fine on Fabric.
Got two of those in Mine Cells: [here](https://github.com/mim1q/MineCells/blob/479dfd7b629fce6cb73cd026e8afc886a8ad84e8/src/main/java/com/github/mim1q/minecells/mixin/client/PlayerEntityRendererMixin.java) and [here](https://github.com/mim1q/MineCells/blob/479dfd7b629fce6cb73cd026e8afc886a8ad84e8/src/main/java/com/github/mim1q/minecells/mixin/client/HeldItemRendererMixin.java). Disabling these Mixins and recompiling the mod allows the game to launch.

**Comment by oof100200** [comment]
> 找到罪魁祸首 - MixinExtras 的`@ModifyExpressionValue`mixins 似乎使 Connector 崩溃，而它们在 Fabric 上工作得很好。 在 Mine Cells 中找到了其中的两个：[这里](https://github.com/mim1q/MineCells/blob/479dfd7b629fce6cb73cd026e8afc886a8ad84e8/src/main/java/com/github/mim1q/minecells/mixin/client/PlayerEntityRendererMixin.java)和[这里](https://github.com/mim1q/MineCells/blob/479dfd7b629fce6cb73cd026e8afc886a8ad84e8/src/main/java/com/github/mim1q/minecells/mixin/client/HeldItemRendererMixin.java)。取消这些 Mixins 并重新编译 mod 即可启动游戏。

thanks.

**Comment by Willem07** [comment]
How do disable the mixing and recompile mod?

**Comment by mim1q** [comment]
> How do disable the mixing and recompile mod?

You shouldn't try to do that, it'll break a few things in the mod. I was just saying that I definitely know these mixins are the problematic thing here.
