### ISSUE TITLE
Modern industrialization crash on startup

### ISSUE THREAD

**Issue by Mark-The-Lark** [Sinytra/Connector#1088]
### Mod Name

Modern Industrialization + Applied Energistics 2

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

### Minecraft version

1.20.1

### Describe the bug

Client crash during loading the game

### Steps to reproduce

1.Install latest AE2, MI, ClothConfig, Connector and FF-API, and also latest forge
2. Simply start the game
3. Get the error

### Logs

https://gist.github.com/Mark-The-Lark/49fb0a5d1848eb205623c52d541fe776

### Additional context

I get such crash-report
https://gist.github.com/Mark-The-Lark/9a6fe21fa4587938758dcd3ccc55f04c
P.S. it seems the same the same with forge 47.1.3

**Comment by Mark-The-Lark** [comment]
Idk how, but some time spend trying to fix via config tweaking helped, but can't tell exactly what i did

**Comment by Lancet-crow** [comment]
> Idk how, but some time spend trying to fix via config tweaking helped, but can't tell exactly what i did

Please tell me, what exactly you fixed? I am also trying to solve this issue now. @Mark-The-Lark

**Comment by dima-dencep** [comment]
#404
