### ISSUE TITLE
Modern Industralization - Invisible Blocks 

### ISSUE THREAD

**Issue by KaelaSavia** [Sinytra/Connector#1093]
### Mod Name

Modern Industralization 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization/files/all?page=1&pageSize=20

### Minecraft version

1.20.1

### Describe the bug

Boiler/Bronze Furnace blocks are invisible/transparent. You can touch them and interact with them but they are invisible

### Steps to reproduce

1. Run modern industralization
2. Place boiler/bronze furnace
3. Its invisible
...

### Logs

Nothing in logs related to the issue

### Additional context

embeddium-0.3.18+mc1.20.1-all/sodium is installed, i am unsure if its related to issue or not

**Comment by Su5eD** [comment]
> embeddium-0.3.18+mc1.20.1-all/sodium is installed, i am unsure if its related to issue or not

Have you also installed [Lazurite](https://modrinth.com/mod/lazurite)?

**Comment by KaelaSavia** [comment]
Oh, that fixed it. Apologies for unnecessary report!
