### ISSUE TITLE
Connecter might have an issue with BcLib

### ISSUE THREAD

**Issue by BabaFisi** [Sinytra/Connector#1095]
### Mod Name

BcLib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bclib

### Minecraft version

1.20.1

### Describe the bug

The game immediately crashes THE MOMENT it finishes loading, not even getting to the title screen.

### Steps to reproduce

1. Open the game, it will crash right before it loads the title screen
2.
3.
...

### Logs

https://gist.github.com/BabaFisi/efcaf789ca266d5a5562d24cf139f074 and https://gist.github.com/BabaFisi/1d13b9c00291ddf6dc7af695c8d5968f

### Additional content ###
-Please, I don't even know if this is a problem relating to the connecter, but I really need this to be solved. The modpack was working just fine yesterday, and now it won't load.-

**Comment by liangmoe** [comment]
Well, aether redux 2.0.14 has incompat issue with geckolib currently, its better to not report issue like this

**Comment by BabaFisi** [comment]
So... do I have to downgrade geckolib or aether redux to fix the issue then?

**Comment by BabaFisi** [comment]
Nope! It's definitly BcLib that's causing the problem. Just downgraded Aether Redux, and it told me that BcLib is the thing causing problems. Is this an error with the Forgified Fabric API? The Connector? Or something else, because it certainly isn't Aether Redux

**Comment by liangmoe** [comment]
Downgrade redux to 2.0.13, and i mean modpack issue should not report on github, unless you have confirmed that sinytra is having issue with the specific mod

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.

**Comment by EndangeredNayla** [comment]
It seems to be curios / trinkets related. It crashed for me the second i added Accessories to the modpack.
