### ISSUE TITLE
Sudden crash at game launch presumably caused by BetterNether. (possibly unrelated)

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#1099]
### Mod Name

BetterNether

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betternether

### Minecraft version

1.20.1

### Describe the bug

Crash at game launch

### Steps to reproduce

Launch game.

I updated a few mods that have nothing to do with Connector, so perhaps one of these mods causes the crash/conflicts with BetterNether in some way. I was unable to find the corresponding mod in the log, as I don't know where to look :/

### Logs

Log: https://mclo.gs/dH9oWkm Crash Report: https://mclo.gs/jYrT6IQ

### Additional context

The game crashed whilst initializing game
Error: net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'betternether'!

Exit Code: -1

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by Wanderer70** [comment]
Right, sorry.
