### ISSUE TITLE
Industrial Revolution items not loading properly 

### ISSUE THREAD

**Issue by Pupseal115** [Sinytra/Connector#1106]
### Mod Name

Industrial Revolution 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/industrial-revolution

### Minecraft version

1.20.1

### Describe the bug

Some amount of items do not load properly, particularly items that are only used for crafting, tools and armor. They will not load in JEI or in the creative menu, but will appear in JEI in the recipes of items that do load, such as machines and otherwise. The items will have some of their crafting recipes once loaded, for instance, Bronze Plates show their decrafter recipe but not others. This also applies, however, when in a pack with just Sinytra, Indrev and JEI. The recipes do still work, even if they do not appear. 

### Steps to reproduce

Put Sinytra Connector, Industrial Revolution and JEI in a pack together

Search "Bronze Plate" in JEI or the Creative menu

### Logs

N/A

**Comment by Su5eD** [comment]
Fabric and Forge show the same behavior regarding items in creative search. As for recipes, Indrev only integrated with [REI](https://github.com/GabrielOlvH/Industrial-Revolution/tree/master/src/main/kotlin/me/steven/indrev/compat) and not JEI, so you'll have to switch in order for them to work. You'll also need to install [Connector Extras](https://modrinth.com/mod/connector-extras) to load REI plugins from Fabric mods.

### Fabric

| ![image](https://github.com/Sinytra/Connector/assets/51261569/3c84b7f4-ab9c-4340-aa76-64e76b298903) | ![image](https://github.com/Sinytra/Connector/assets/51261569/1ebb5d59-ad67-4d97-9b00-014d94831c77) |
|--------|--------|

### Forge

| ![image](https://github.com/Sinytra/Connector/assets/51261569/f5751463-21f4-47a5-934b-63f679311245) | ![image](https://github.com/Sinytra/Connector/assets/51261569/9e256816-d220-4ff1-a363-d90cf256a92c) |
|--------|--------|

**Comment by RoomAlex68** [comment]
You could whatsoever try EMI
