### ISSUE TITLE
Blueprint causes continuity connected textures to stop working

### ISSUE THREAD

**Issue by Nicodemus111** [Sinytra/Connector#1107]
### Mod Name

blueprint, continuity

### Mod Homepage

https://modrinth.com/mod/blueprint https://modrinth.com/mod/continuity

### Minecraft version

1.20.1

### Describe the bug

When blueprint and continuity are installed continuity connected textures stop working.

### Steps to reproduce

1. Install sinytra, continuity, blueprint, ctm resource pack [https://www.curseforge.com/minecraft/texture-packs/clear-glass-pack](url) as an example
2. Place 2 glass blocks
3. They don't connect

### Logs

Logs are unnecessary for this issue but it will not let me submit without filling out this field.

### Additional context

This has been previously reported to team abnormals
[https://github.com/team-abnormals/blueprint/issues/240](url)

**Comment by Su5eD** [comment]
Duplicate of #1001
