### ISSUE TITLE
Crash when using Optfine with Sinytra 

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#111]

**Comment by Fiz-Victor** [comment]
Optifine is known to cause a lot of issues with mods, also it is closed source.
You can use rubidium instead.

**Comment by Su5eD** [comment]
Yeah, optifine is known to cause incompatibilities with many mods. At this point, it should be avoided completely. We have viable alternatives that are much more stable and open source. Like Fiz stated, you can try rubidium instead. Optifine support is not planned for Connector / FFAPI.
