### ISSUE TITLE
Crash upon entering the end with BetterEnd

### ISSUE THREAD

**Issue by kiitkatt** [Sinytra/Connector#1110]
### Mod Name

BetterEnd

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1

### Describe the bug

Entering the end dimension in any way causes it to crash. 

### Steps to reproduce

1. have BetterEnd along with it's dependents, and sinytra connector
2. enter the end via natural end portals or simply spawning one in
3. It loads, but crashes immediately after
...

### Logs

https://gist.github.com/kiitkatt/b33a84d4974382d2460cd8941648c823

### Additional context

The only mods I had were 
better-end-4.0.11
bclib-3.0.14
Connector-1.0.0-beta.43+1.20.1
fabric-api-0.92.1+1.11.8+1.20.1
cloth-config-11.1.118-forge
----
I typically use a bunch of other mods which led me to discover this crash, but even with removing all of them i still experience it.
Here's the list of the mods I use if you want them: https://gist.github.com/kiitkatt/5765037abf12b749238c0eca7d863a41

**Comment by liangmoe** [comment]
Can you try forge 47.1.3 and reproduce again? because betterend works fine with me

**Comment by DeshiDesu** [comment]
> Can you try forge 47.1.3 and reproduce again? because betterend works fine with me

Worked fine for me as well on Forge 47.2.32

**Comment by kiitkatt** [comment]
I tried using forge 47.1.3 and it still crashes once i reach the end. heres the log: https://gist.github.com/kiitkatt/9227dcd4cbbf26df77d2ac31df93342a

**Comment by Su5eD** [comment]
Confirmed to work on Forge 47.1.3
