### ISSUE TITLE
PlayerEx: Directors Cut + Data Attributes: Directors Cut, crash

### ISSUE THREAD

**Issue by esstoma** [Sinytra/Connector#1111]
### Mod Name

PlayerEx: Directors Cut + Data Attributes: Directors Cut

### Mod Homepage

https://github.com/BareMinimumStudios/playerex

### Minecraft version

1.20.1

### Describe the bug

When trying to create a world, the game crashes

### Steps to reproduce

Minecraft launches, but when you click the "Singleplayer" button, it crashes out

### Logs

https://gist.github.com/AvaloriaSinytra/ae0bd0a8328f89fd5161ec9f0b48689d

**Comment by Su5eD** [comment]
Duplicate of #699
