### ISSUE TITLE
Nature's Spirit startup crash

### ISSUE THREAD

**Issue by wiisafetymanual** [Sinytra/Connector#1113]
### Mod Name

Nature's Spirit

### Mod Homepage

https://modrinth.com/mod/natures-spirit

### Minecraft version

1.20.1

### Describe the bug

The profile crashes on startup if Nature's Spirit is installed

### Steps to reproduce

1. Install Nature's Spirit
2. Start the game

### Logs

https://gist.github.com/wiisafetymanual/0e71dfcfcf91072c31bc7ffa951486bd

### Additional context

Aside from sinytra, forgified api, and nature's spirit, I also had falling leaves, geoliphic reforged, better trees, embeddium, tectonic, and luki's grand capitals

**Comment by RoomAlex68** [comment]
Nature Spirits works on Connector 43
Your just missing TerraBlender(Fabric)
But the Forge version of TerraBlender works
