### ISSUE TITLE
Allow configurable timeout for Jar Remapping ?

### ISSUE THREAD

**Issue by Yldales** [Sinytra/Connector#1114]
Hi,

The [JarTransformer.class](https://github.com/Sinytra/Connector/blob/master/src/main/java/dev/su5ed/sinytra/connector/transformer/jar/JarTransformer.java) class has a hardcoded timeout value of 60 seconds for the awaitTermination method. This can be problematic in environments where large mods (like [Conquest Reforged](https://legacy.curseforge.com/minecraft/mc-mods/conquest-reforged)) require more time to be remapped. To enhance flexibility and address issues #275, #424 and #880, could you consider making the timeout value configurable ? 👉👈 

https://github.com/Sinytra/Connector/blob/31aa8e640f53f64184eb24a323d7670eee645e02/src/main/java/dev/su5ed/sinytra/connector/transformer/jar/JarTransformer.java#L152-L154

Thank you in advance for your consideration.

**Comment by Su5eD** [comment]
I "removed" the delay by setting it to one hour (a timeout duration is always required by Java's thread executor), which should suffice. I don't expect transformation to actually freeze up, and all reported cases so far seem related to available system resources, so hopefully no issues arise after this change either.
