### ISSUE TITLE
Incompatibility with Treasure2 with Better Nether

### ISSUE THREAD

**Issue by cal1407** [Sinytra/Connector#1116]
### Mod Name

Treasure2

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/treasure2

### Minecraft version

1.20.1

### Describe the bug

I apologize for not narrowing down the mods causing the crash earlier. After narrowing them down, it seems that having Better Nether and Treasure2 installed together would cause the game to crash on startup.

### Steps to reproduce

1. Install Connector, Connector Extra and Forgified Fabric API.
2. Install Better Nether and BCLib
3. Install Treasure2 and Gottschcore
4. Game would crash on startup
...

### Logs

https://pastebin.com/ue84Kehy

**Comment by Su5eD** [comment]
> Caused by: java.lang.ClassNotFoundException: mod.gottsch.forge.gottschcore.config.AbstractConfig

This is a missing class error. Please make sure you've installed the correct version of gottschcore. The game runs fine for me.

![2024-05-30_14 59 51](https://github.com/Sinytra/Connector/assets/51261569/ac8b43bd-42f4-4159-aa22-e3da7736a485)

![image](https://github.com/Sinytra/Connector/assets/51261569/cab3ac1b-810f-48c4-a61d-582a61960b23)
