### ISSUE TITLE
Redirect Soulbound conflict with Sortilege & Galosphere

### ISSUE THREAD

**Issue by Liamgrayskull** [Sinytra/Connector#1121]
### Mod Name

Sortilege

### Mod Homepage

https://modrinth.com/mod/sortilege

### Minecraft version

1.20.1

### Describe the bug

Crash when both sortilege and galosphere are loaded

### Steps to reproduce

1. Install FFAPI, Connector, Extras & Sortilege
2. Game runs fine
3. Install Galosphere
4. Game crashes before startup with log below

### Logs

https://gist.github.com/Liamgrayskull/c154b9308cbd7733128b916c8c943040

**Comment by Su5eD** [comment]
This is a conflict between the two mods and cannot be fixed on our side.
