### ISSUE TITLE
Mods require fabric loader above 1.15.0

### ISSUE THREAD

**Issue by Axon-waxby** [Sinytra/Connector#1129]
### Minecraft version

1.20.1

### Describe the bug

Many mods require a version of fabric loader higher than version 1.15.0, but sinytra connector only supports 1.15.0.

### Steps to reproduce

1.Launch an unsupported mod. For example, Language reload mod
2.Then get an error

### Logs

https://pastebin.com/6SZRyZRD

### Additional context

:(

**Comment by Su5eD** [comment]
> Sinytra Connector: 1.0.0-beta.33+1.20.1+dev-00000000

Please update your version of Connector to the latest one, where this issue no longer occurs
