### ISSUE TITLE
Incompatibility with new version of "Minecells mod" 1.80+

### ISSUE THREAD

**Issue by TheKekas-YT** [Sinytra/Connector#1130]
### Mod Name

Mine Cells

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/minecells

### Minecraft version

1.20.1

### Describe the bug

If i try to use the version 1.80 or above the game crash, with version 1.70 this doesn't happen

### Steps to reproduce

![imagen_2024-06-06_095924331](https://github.com/Sinytra/Connector/assets/171953504/1e314f9a-db04-4b64-b259-f76fc5976e57)
The game just crash after i add that version of the mod to my game (1.8.0 or above ), but if i use 1.7.4 the game run well

![image](https://github.com/Sinytra/Connector/assets/171953504/24214bd6-d217-4e3a-a18d-4d22c12401f1)

### Logs

The game crashed whilst initializing game Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### Additional context

Thats all, anucase other mods work well, thank you vere much for doing this awesome comtability mods

**Comment by RoomAlex68** [comment]
1058#
