### ISSUE TITLE
map atlases mod crashing

### ISSUE THREAD

**Issue by E064** [Sinytra/Connector#1134]
### Mod Name

Map Atlases

### Mod Homepage

https://modrinth.com/mod/map-atlases

### Minecraft version

1.20.1

### Describe the bug

minecraft crashing on the forge ( connector ) screen

### Steps to reproduce

1. start minecraft
2. wait
3. here is a crash!

### Logs

https://gist.github.com/E064/ecb8d782f029f81c8b9415528ddf62fc

**Comment by Su5eD** [comment]
> java.lang.ClassNotFoundException: dev.emi.trinkets.api.TrinketItem

You're missing trinkets

**Comment by Tapacywka** [comment]
Install all dependencies normally. Instead of Trinkets and Curios, use Accessories and its Compatibility Layers.

**Comment by Su5eD** [comment]
A forge version is available too btw https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge
