### ISSUE TITLE
jewerly crash

### ISSUE THREAD

**Issue by E064** [Sinytra/Connector#1135]
### Mod Name

Jewelry (RPG Series)

### Mod Homepage

https://modrinth.com/mod/jewelry

### Minecraft version

1.20.1

### Describe the bug

just crashing on the forge screen

### Steps to reproduce

1. start minecraft
2. wait for connector converting jar screen ( It may happen sooner )
3. minecraft crashing

### Logs

https://gist.github.com/E064/c2c06d4ea5f56d5905fb8eb65126ccd7

**Comment by Tapacywka** [comment]
Install all dependencies normally. Instead of Trinkets and Curios, use Accessories and its Compatibility Layers.

**Comment by Su5eD** [comment]
Confirmed to work on beta 43

![2024-06-08_19 36 37](https://github.com/Sinytra/Connector/assets/51261569/327a0051-d72d-4e5e-bf08-b5404fdd153c)
