### ISSUE TITLE
Shallow Swimming incompatiblity

### ISSUE THREAD

**Issue by AS184** [Sinytra/Connector#1136]
### Mod Name

Shallow Swimming

### Mod Homepage

https://modrinth.com/mod/shallowswimming

### Minecraft version

1.20.1

### Describe the bug

Game crashes during startup whenever the Shallow Swimming mod is installed.

### Steps to reproduce

1. Have Sinytra connector, Forgified Fabric API, and Connector Extras (optional) installed.
2. Have Shallow Swimming mod installed.
3. Launch it.
4. Wait a few seconds.
5. Receive game crash while the game tried to load.

### Logs

https://gist.github.com/AS184/2c941b32ba96f15236f598adb1f80c51

### Additional context

No other mods besides Sinytra connector, Forgified Fabric API, and Connector Extras and Shallow Swimming were installed. Shallow Swimming doesn't have any external mods it relies on (no library mods it utilizes). Opening the mod file, it has two mixins that make up the functionality of the mod, EntityMixin and ClientPlayerEntityMixin. Both seem to internally call for mixinextras which seems to be the problem as the last processes the log shows happening before the game crashes seems to reference it. Mixinextras is stored as a separate jar file if you were to open the mod through a program like I had. The specific file the log mentions, MixinExtrasServiceImpl, can be found by opening the mixinextras.jar file if you check under the services folder inside it, but due to technical issues on my end, I couldn't go beyond that and actually explore the code myself to figure out the issue.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
