### ISSUE TITLE
Crash when opening chest

### ISSUE THREAD

**Issue by 7-pv-7** [Sinytra/Connector#1137]
### Mod Name

BetterEnd, I guess...

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1

### Describe the bug

I'm playing in a server with multiple mods, and found a structure with a chest inside, when I tried to open the chest, the server crashed. I don't really know if the problem is related about BetterEnd or Sinytra, but in the log the name "BetterEnd" and "connector" appear some times.

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/7-pv-7/c8c8faf88903c16979dd0313608525a8

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)

This looks like an issue with allocated resources. Try increasing the memory allocated to your server.
