### ISSUE TITLE
Icompatible mod [oceansdelight] and forge update required

### ISSUE THREAD

**Issue by ErythroCraft** [Sinytra/Connector#1138]
### Mod Name

oceansdelight

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/oceans-delight -- https://www.curseforge.com/members/scouter567/projects

### Minecraft version

1.20.1

### Describe the bug

Please watch the crash file I uploaded

### Steps to reproduce

Normal installing the mod and starting minecraft instance 1.20.1 - 47.3.0

Using last recommended forge version.

Maybe you can fix this bug and creating an update to the latest recommended forge version 1.20.1 - 47.3.0 ?

### Logs

https://gist.github.com/ErythroCraft/c5a1d56418807465a7885f2f05a23d15

### Additional context

[latest.log](https://github.com/user-attachments/files/15750790/latest.log)
[debug.log](https://github.com/user-attachments/files/15750791/debug.log)

**Comment by Su5eD** [comment]
> Suppressed: java.lang.NoSuchFieldError: COMFORT
		at cn.foggyhillside.ends_delight.item.FoodList.<clinit>(FoodList.java:21) ~[ends_delight-refabricated-1.20.1-alpha-1.0_mapped_srg_1.20.1.jar%23970!/:?] {re:classloading}

The version of Farmer's delight you're running is not compatible with the addon do you differences in their code. You'll need to use a version the addon was built for, e.g. Forge addons with the official Forge version of FD.
