### ISSUE TITLE
Axiom-Embeddium incompatibility

### ISSUE THREAD

**Issue by Jakub-Wilk** [Sinytra/Connector#1140]
### Mod Name

Axiom

### Mod Homepage

https://axiom.moulberry.com

### Minecraft version

1.20.1

### Describe the bug

Using Axiom 3.0.0 and Embeddium 0.3.20, the game launches correctly, but crashes on entering a world. That happens regardless of the json files from #399 being in `/config` or not.

### Steps to reproduce

1. Install Connector 1.0.0 beta 43, Axiom 3.0.0, Embeddium 0.3.20 on Forge 47.1.3
2. Add the two config files from #399
3. Launch the game and create a world
4. Upon joining the world, the game immediately crashes

### Logs

Crash and debug logs: https://gist.github.com/Jakub-Wilk/e92386bc3a07a0e8b73faf90748f1a74

**Comment by Dokman** [comment]
My log https://gist.github.com/Dokman/8550e6cc58e45fc90644b225a8e4b528

**Comment by coco875** [comment]
Use embeddium 0.3.18

**Comment by Su5eD** [comment]
This is a conflict between Embeddium and Axiom, thus it cannot be fixed on our side.

**Comment by Jakub-Wilk** [comment]
> Use embeddium 0.3.18

Thank you, it indeed works with 0.3.18
