### ISSUE TITLE
GeckoLib both version issue

### ISSUE THREAD

**Issue by GooGirlCyra** [Sinytra/Connector#1141]
### Mod Name

GeckoLib, Hybrid Aquatic, Critters and Companions

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/geckolib || https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic || https://www.curseforge.com/minecraft/mc-mods/critters-and-companions 

### Minecraft version

1.20.1

### Describe the bug

Process crashed with exit code -1073740791 (updated windows, disabled recording software and checked for driver updates)

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/htdR5GXb

### Additional context

Unable to use Hybrid Aquatic (Fabric) with Critters and Companions (forge) due to needing both GeckoLib versions

**Comment by RoomAlex68** [comment]
231#
