### ISSUE TITLE
Bren incompatibility

### ISSUE THREAD

**Issue by ghost** [Sinytra/Connector#1142]
### Mod Name

Bren

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bren

### Minecraft version

1.20.1

### Describe the bug

Weapons don't shoot

### Steps to reproduce

1. Use latest version of Connector and Bren mod
2. Open any world
3. Grab shotgun and shells (or any other weapons)
4. load it with "r" button
5. shoot it with right click. It will deplete shells, but not shoot
...

### Logs

https://gist.github.com/Axi0L/b7517bc41c89a7ac3b797171bf4083b6

**Comment by ThePiekar** [comment]
To add to this it seems like a server/client sync issue.
I am fairly certain of it (don't take me too seriously though, i only glanced at the code and tested the behaviour).

Shooting seeming consumes ammo and plays the animation of the held item.
Yet, when removing ammo from weapon/unloading the weapon item and reloading it.
The weapon seems to not have lost any ammo from shooting.
So my bet is the packet sent to server to signify weapon being shot doesn't quite accomplish its task, everything that happens seems to be happening purely client side.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by F-708** [comment]
Maybe it can be fixed at next 1.20.1 update?
I mean
Do not update sinytra just for bren
When sinytra be updated (in order to fix critical bugs) bren compatibility may be added too!
