### ISSUE TITLE
Ultracraft crash on beta 44 dev

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#1144]
### Mod Name

Ultracraft

### Mod Homepage

https://modrinth.com/mod/absolute-ultracraft/version/1.20.1-2.1.pride2

### Minecraft version

1.20.1

### Describe the bug

game crashed 

### Steps to reproduce

i've tested this on beta44 dev and this time the crash reason has nothing to do with flywheel, can you please check it?

### Logs

https://pastebin.com/cfFuXEyC

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by oof100200** [comment]
> Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.
> 
> > Before reporting, please ensure that:
> > 
> > * You've installed a **minimal set of mods** required to reproduce the issue.
> >   Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
> >   Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
> >   If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
> >   repeatedly until the faulty mod is found.

this mod crashes because embeddium's Render, and in （https://github.com/embeddedt/embeddium/issues/310）this issue, embddededt gaved me a solution, how do i edit connector.json？
