### ISSUE TITLE
daily shop crash

### ISSUE THREAD

**Issue by redgamer229** [Sinytra/Connector#1145]
### Mod Name

daily shop 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/daily-shop

### Minecraft version

1.20.1

### Describe the bug

When launching the game letting it start up it produces this msg when it crashs before it finishs loading the game The game crashed whilst initializing game Error: net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'dailyshop'!

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/SnDVDv6n

**Comment by Su5eD** [comment]
You need to install Architectury. The mod works fine for me on Connector Beta 43
