### ISSUE TITLE
daily shop crash mk2 i added Architectury still not working

### ISSUE THREAD

**Issue by redgamer229** [Sinytra/Connector#1147]
### Mod Name

daily shop

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/daily-shop

### Minecraft version

1.20.1

### Describe the bug

When launching the game it trys to launch and crashes with no crash log

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/Fn2yR84Y

### Additional context

someone said on my github issue to install Architectury, but i tried the latest fabric and forge version the forge version produces the same crash without Architectury and the fabric version crashes the game with no crash log

**Comment by Su5eD** [comment]
Please provide more information, namely:
- a crash report / crash log / anything that contains a stack trace
- installed mods and versions

**Comment by redgamer229** [comment]
Architectury 9.2.14-fabric.jar
DailyShop-mc1.20.1-v1.0.8-fabric.jar
Forgified Fabric API 0.92.2+1.11.8+1.20.1.jar
Sinytra Connector 1.0.0-beta.43+1.20.1.jar
it produces no crash log when it crashes

**Comment by Su5eD** [comment]
> Architectury 9.2.14-fabric.jar

Use the forge version of Architectury and install Connector Extras

**Comment by redgamer229** [comment]
that works thank you

**Comment by redgamer229** [comment]
now that i loaded it up and checked the "daily shop block" is not in the game

**Comment by Su5eD** [comment]
![image](https://github.com/Sinytra/Connector/assets/51261569/390c4740-c3f5-4db7-b63d-baca4d214a96)

Have you checked if this is not indeed the expected behaviour? I launched the mod on Fabric and there are no new blocks in the creative menu either. Use the /give command to obtain the block
