### ISSUE TITLE
Mod Compatibility Thread

### ISSUE THREAD

**Issue by DaDiGui** [Sinytra/Connector#1148]
|:------:|:------:|:------:|:------:|

| MiniMOTD | [Modrinth](https://modrinth.com/plugin/minimotd) | ⚠️ | The mod loads without errors and the configuration is created correctly in .config but when I enter the client the server appears with the message “can't connect to server” and the red X appears above the ping icon. HOWEVER I CAN access the server.<br/> 
Log: https://mclo.gs/n2ghAsp

**Comment by Su5eD** [comment]
Please use the appropriate issue template
