### ISSUE TITLE
[MCT] MiniMOTD

### ISSUE THREAD

**Issue by DaDiGui** [Sinytra/Connector#1149]
LOG: https://mclo.gs/n2ghAsp
<div type='discussions-op-text'>

| 📦 Name | 🔗 Link | ❓ Status | 🗒️ Notes |
|:------:|:------:|:------:|:------:|
| MiniMOTD | [Modrinth](https://modrinth.com/plugin/minimotd) | ⚠️ | The mod loads without errors and the configuration is created correctly in .config but when I enter the client the server appears with the message “can't connect to server” and the red X appears above the ping icon.<br/> HOWEVER I CAN access the server |

**Comment by Su5eD** [comment]
Please follow the issue template
