### ISSUE TITLE
cardinal components crast at the start

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#115]
### Mod Name

Cardinal Components

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/cardinal-components

### Describe the bug

crash at start

### Steps to reproduce

1. have ffapi, connector, cardinal components
2. start
3. see

### Logs

https://pastebin.com/VTddsJWL

**Comment by Su5eD** [comment]
Fixed in c4e4c1721695e2bbb3d8757b87e85c052be4a3ba
