### ISSUE TITLE
[1.20.1] Crash with Biolith and Deep Dark Regrowth

### ISSUE THREAD

**Issue by Reshy** [Sinytra/Connector#1153]
### Mod Name

Deep Dark Regrowth & Biolith/Cinderscapes

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/deep-dark-regrowth https://www.curseforge.com/minecraft/mc-mods/biolith/files/4850274 https://www.curseforge.com/minecraft/mc-mods/cinderscapes

### Minecraft version

1.20.1

### Describe the bug

The two mods cause a conflict upon world generation causing a hang into crash.

### Steps to reproduce

1.  Install Connector
2.  Install Deep Dark Regrowth & it's dependencies
3.  Install Cinderscapes & it's dependencies
4.  Generate a world
5. ???
6. Crash.

### Logs

https://pastebin.com/5Sve3MjZ

### Additional context

![image](https://github.com/Sinytra/Connector/assets/2096384/fcc3ad10-fe05-4fb8-b359-a5898b63e5af)

**Comment by Su5eD** [comment]
Same issue as https://github.com/Sinytra/Connector/issues/857

**Comment by Reshy** [comment]
Still getting the crashing, is there anything that can be done to fix it?
