### ISSUE TITLE
UltraCraft crash with Embeddium

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#1154]
### Mod Name

ULTRACRAFT Embeddium

### Mod Homepage

https://modrinth.com/mod/absolute-ultracraft/version/1.20.1-2.1.pride2

### Minecraft version

1.20.1

### Describe the bug

crash with embeddium

### Steps to reproduce

this mod crashes because embeddium's Render, and in （https://github.com/embeddedt/embeddium/issues/310 this issue, embeddedt gaved me a solution, how do i edit connector.json？

### Logs

https://pastebin.com/3CYbruvR

**Comment by Su5eD** [comment]
Please read the documentation at https://sinytra.org/docs/connector/configuration
