### ISSUE TITLE
Crash on statup

### ISSUE THREAD

**Issue by Fingernailsss** [Sinytra/Connector#1158]
### Mod Name

N/A

### Mod Homepage

N/A

### Minecraft version

1.20.1

### Describe the bug

crashes on startup. i have tried disabling everything but the fabric mods, then disabling all the fabric mods then disabling everything except for connecter and it's dependencies. issue only goes away when i remove connecter

### Steps to reproduce

N/A

### Logs

https://pastebin.com/rptkW7dg

**Comment by liangmoe** [comment]
Read line 93 from your log, you are missing some dependencies mod from another mods, not even related to sinytra

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
