### ISSUE TITLE
[mod conflict] Architectury API [forge] crashes when loaded with Regions Unexplored [fabric]

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#116]
### Mod Name

Regions Unexplored

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/regions-unexplored

### Describe the bug

Crash at startup

### Steps to reproduce

1. Install fabric terrablender (works fine alone)
2. Install regions unexplored fabric version
3. Launch game

poopfart

### Logs

https://gist.github.com/Cixon/6670284a01959737bb9427dbe2ae314b

### Additional context

Even though there is a forge version, there is and will be more mods that have support for the fabric version such wood-type support for furniture or chests for example.

**Comment by Su5eD** [comment]
Kind reminder: in the future, please use a paste site for uploading logs, as suggested in the issue template. In this form, they obstruct the description and the text wrap makes the actual error hard to find. Thanks!

**Comment by Su5eD** [comment]
@Cixon is there any reason you're using the Fabric version over the Forge one?

**Comment by Cixon** [comment]
> Kind reminder: in the future, please use a paste site for uploading logs, as suggested in the issue template. In this form, they obstruct the description and the text wrap makes the actual error hard to find. Thanks!

forgor 💀
https://gist.github.com/Cixon/6670284a01959737bb9427dbe2ae314b

**Comment by Cixon** [comment]
> @Cixon is there any reason you're using the Fabric version over the Forge one?

Mods like this:
https://legacy.curseforge.com/minecraft/mc-mods/variant-bookshelves-fabric

Support the fabric version's woodtypes, not forge

**Comment by Cixon** [comment]
@Su5eD

**Comment by Su5eD** [comment]
I tried running the following mods and they all work as expected:
- Connector beta 9
- Forgified Fabric API 0.87.0+1.9.6+1.20.1
- Regions Unexplored Fabric 0.5.1_02+1.20.1
- TerraBlender fabric 1.20.1-3.0.0.169

**Comment by Cixon** [comment]
> I tried running the following mods and they all work as expected:
> 
> * Connector beta 9
> * Forgified Fabric API 0.87.0+1.9.6+1.20.1
> * Regions Unexplored Fabric 0.5.1_02+1.20.1
> * TerraBlender fabric 1.20.1-3.0.0.169


Regions Unexplored [fabric] is incompat with Architectury API [forge].

**Comment by Cixon** [comment]
Possibly unrelated to Sinytra. Labeled won't fix ?
