### ISSUE TITLE
I'm crashing and I don't know what to do

### ISSUE THREAD

**Issue by neaxy0** [Sinytra/Connector#1162]
### Minecraft version

1.20.1

### Describe the bug

when I try to join the server it crashes and gives this error

### Steps to reproduce

1. I opened the game
2. Tried to join to server
3. Crash

### Logs

https://gist.github.com/neaxy0/81b2d9e39f45ce99e9278f2a6c5dd55c

### Additional context

game gives this error when it crashes

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_21023_(net.minecraft.world.effect.MobEffect)" because "this.f_109876_.f_91074_" is null

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
