### ISSUE TITLE
Immersive Portals with Embeddium makes nothing render

### ISSUE THREAD

**Issue by CalebHaleDev** [Sinytra/Connector#1163]
### Mod Name

Immersive Portals + Embeddium

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod
https://www.curseforge.com/minecraft/mc-mods/embeddium

### Minecraft version

1.20.1

### Describe the bug

No blocks or entities render, but clouds and particles do

### Steps to reproduce

As soon as you enter the world, nothing renders

### Logs

I don't see a debug.log in the logs directory

### Additional context

TL;DR; I tested combinations of mods and found Immersive Portals breaks rendering when combined with Embeddium

Thanks for all your great work!

I was going to make a modpack for personal use, so some other mods were installed. Playing with immersive portals disabled everything worked fine, so the issue is not solely within any other mods. I had several mods from someaddon but tried disabling all of them, which didn't fix the issue. I also tried disabling all the "content" mods and left only Immersive Portals, Connector, Connector Extras, Citadel, Balm, Embeddium, Cupboard, FerriteCore, spark, ModernFix, and Redirector[Modern]. This did not fix the issue. Using only Su5eD's mods, FerriteCore, and immersive portals finally worked. So, one of the following mods is the issue: Citadel, Balm, Embeddium, Cupboard, spark, ModernFix, or Redirector[Modern]. Adding Embeddium and ModernFix caused the issue. Disabling Embeddium removes the issue. I then tried running only Su5eD mods and Embeddium and everything worked fine, so Embeddium and Immersive Portals were both definitely the issue, but only together.

**Comment by vinnyg0621** [comment]
i'm having the same problem.

**Comment by Su5eD** [comment]
Please refer to #665
