### ISSUE TITLE
Effective not working

### ISSUE THREAD

**Issue by Aulberon** [Sinytra/Connector#1165]
### Mod Name

Effective

### Mod Homepage

https://modrinth.com/mod/effective

### Minecraft version

1.20.1

### Describe the bug

Effective is being ignored when loading

### Steps to reproduce

Simply loading the mod.

### Logs

https://gist.github.com/Aulberon/cdb258889ea55da5f6cd6c37e82b36f6

### Additional context

[16:46:12] [main/INFO]: Fabric mod metadata not found in jar effective._1._20._1, ignoring

**Comment by coco875** [comment]
it's normal it's a quilt mod to a fabric mod there is a forge port here https://github.com/hlysine/Effective-Forge-/tree/1.20.1

**Comment by Aulberon** [comment]
I have no idea how to turn that into a usable mod file.

**Comment by Su5eD** [comment]
Connector does not support running Quilt mods

**Comment by Aulberon** [comment]
> Use this: https://modrinth.com/mod/particular it works fine with sinytra

OMG! Thank you! This mod is awesome!
