### ISSUE TITLE
Creeper Healing mod crash on start

### ISSUE THREAD

**Issue by cococops** [Sinytra/Connector#1166]
### Mod Name

creeper healing

### Mod Homepage

https://modrinth.com/mod/creeper-healing

### Minecraft version

1.20.1

### Describe the bug

Crash on start

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/cococops/16aa82d93d2f620ecb99743830b87dcf

### Additional context

Tried it without any other mod, it just crashes on start with code exit: 1

**Comment by neonjuno** [comment]
It still does not work on 1.20.1
