### ISSUE TITLE
Not Enough Enchantments

### ISSUE THREAD

**Issue by nguyentd01** [Sinytra/Connector#1168]
### Mod Name

Not Enough Enchantments and Additional Entity Attributes

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/not-enough-enchantments

### Minecraft version

1.20.1

### Describe the bug

It seems like Additional Entity Attributes and Not Enough Enchantments mod conflicted.(I dont know where the mod Additional Entity Attributes comes from)

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/6c6WXzpz

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
