### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AmNexio** [Sinytra/Connector#1169]
### Mod Name

watermedia/waterframes

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5440341/dependencies

### Minecraft version

1.20.1

### Describe the bug

I'm not sure, the game just crashes on launch when I have those two installed

### Steps to reproduce

1. Install Better MC BMC4
2.Watermedia and waterframes
3. **Crash**
...

### Logs

https://gist.github.com/AmNexio/b7496ac4e56c05a2aace4853369748cc

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
