### ISSUE TITLE
Minecells

### ISSUE THREAD

**Issue by OminousDiscovery** [Sinytra/Connector#1170]
### Mod Name

Minecells

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/minecells

### Minecraft version

1.20.1

### Describe the bug

the game crashes

### Steps to reproduce

1. open launcher with minecells, sinytra, and owo (library needed for sinytra)
2. press play
3. game crashes
...

### Logs

https://pastebin.com/BjUTTUg0

**Comment by kakashi1464** [comment]
duplicate of #1085
