### ISSUE TITLE
clientcommands mod command not working

### ISSUE THREAD

**Issue by tayseerla101** [Sinytra/Connector#1172]
### Minecraft version

1.20.1

### Describe the bug

clientcommands mod cenchant command not working

### Steps to reproduce

1.log into a world
2.run /ccrack
3.run /ccenchant <item> with <enchants> <level>
...

### Logs

https://gist.github.com/tayseerla101/828f8d0ca71468d9e774d4a085fcaac6.js

### Additional context

after those steps the following message is output
An unexpected error occurred trying to execute that command

I tried the mod on fabric with the latest fabric api and it worked normally

**Comment by Su5eD** [comment]
Duplicate of #441
