### ISSUE TITLE
beta-44 crashed with architectury, update connector extra also does not fix it

### ISSUE THREAD

**Issue by liangmoe** [Sinytra/Connector#1177]
### Mod Name

 Architectury

### Mod Homepage

https://modrinth.com/mod/architectury-api

### Minecraft version

1.20.1

### Describe the bug

crashed with architectury

### Steps to reproduce

1. update sinytra fron beta 43 to beta 44
2. launch the game alongside with architectury
3. crash
...

### Logs

crash report: https://mclo.gs/Z6Vwreq, latest.log: https://mclo.gs/YrlKKMy

**Comment by Su5eD** [comment]
This belongs in ConnectorExtras
