### ISSUE TITLE
Ultracraft crash on startup

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#1179]
### Mod Name

ULTRACRAFT 1.20.1-2.1.3

### Mod Homepage

https://modrinth.com/mod/absolute-ultracraft/version/1.20.1-2.1.3

### Minecraft version

1.20.1

### Describe the bug

crash on startup

### Steps to reproduce

crash on startup

### Logs

https://pastebin.com/r2tjeGsf

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by oof100200** [comment]
> Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.
> 
> > Before reporting, please ensure that:
> > 
> > * You've installed a **minimal set of mods** required to reproduce the issue.
> >   Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
> >   Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
> >   If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
> >   repeatedly until the faulty mod is found.

Classic
