### ISSUE TITLE
Embeddium and Create crash 

### ISSUE THREAD

**Issue by lotusdrive** [Sinytra/Connector#1180]
### Mod Name

Embeddium / Create

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/create https://www.curseforge.com/minecraft/mc-mods/embeddium

### Minecraft version

1.20.1

### Describe the bug

A rare bug that causes the game to crash when dealing with create's doors while using embeddium and sinytra and rarely menu crashes with create items

### Steps to reproduce

1. run game with all three mods 
2. use creates doors or use menus
3. wait it may take a while 

(this doesnt happen with embeddium and create by themselves ive tested for 8+ hours only when sinytra is present even with out fabric mods it will crash every 2hrs or so)

### Logs

java.lang.NullPointerException: Cannot invoke "com.simibubi.create.foundation.utility.Couple.get(boolean)" because "partials" is null at com.simibubi.create.content.decoration.slidingDoor.SlidingDoorRenderer.renderSafe(SlidingDoorRenderer.java:58) ~[create-1.20.1-0.5.1.f.jar%23282!/:0.5.1.f] {re:classloading}

**Comment by Su5eD** [comment]
> only when sinytra is present

Is this about connector or FFAPI?

**Comment by lotusdrive** [comment]
> > only when sinytra is present
> 
> Is this about connector or FFAPI?

Connector id imagine unless I'm some how wrong

**Comment by lotusdrive** [comment]
i misclicked and closed this issue sorry bout that

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
