### ISSUE TITLE
Latest Continuity Release (3.0.0-beta.5+1.20.1) will not startup

### ISSUE THREAD

**Issue by BoardAnims** [Sinytra/Connector#1185]
### Mod Name

Continuity

### Mod Homepage

https://modrinth.com/mod/continuity/version/3.0.0-beta.5+1.20.1

### Minecraft version

1.20.1

### Describe the bug

Game crashes on startup

### Steps to reproduce

1. Install Sinytra Connector (including Forgified Fabric API and Connector Extras)
2. Install continuity-3.0.0-beta.5+1.20.1.jar
3. Launch Minecraft

### Logs

https://gist.github.com/BoardAnims/8c118bd243db9005f1893a12d019de6e

### Additional context

Downgrading Continuity to  "3.0.0-beta.4+1.20.1" will make the mod function as normal.

Though I would like to bring up #1001, which has yet to be resolved. There has been more than two issues [#243](https://github.com/team-abnormals/blueprint/issues/243) opened on both Blueprint and Connector, both sides saying that it is the other mod's fault. 

Sorry if it's a duplicate, this could also be a problem on Continuity's side... Or even something to do with Embeddium and/or Lazurite.

**Comment by ArteriusDayne** [comment]
I get the same issue.  not the biggest deal as downgrading continuity still works, but an issue nevertheless.

**Comment by Xplodin** [comment]
![image](https://github.com/Sinytra/Connector/assets/13007677/e75a343b-fdc8-4382-8fbd-62f8b2f73c77)
works for me

**Comment by Tapacywka** [comment]
> ![image](https://private-user-images.githubusercontent.com/13007677/344501684-e75a343b-fdc8-4382-8fbd-62f8b2f73c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjE5ODksIm5iZiI6MTcxOTkyMTY4OSwicGF0aCI6Ii8xMzAwNzY3Ny8zNDQ1MDE2ODQtZTc1YTM0M2ItZmRjOC00MzgyLThmYmQtNjJmOGIyZjczYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEyMDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjMxZmEwZDVlMjg1MjQ0YmYzMzEyY2JhYzE0MmNjZWRmZDA0MzM5MWFkYWRmMDIwNWRjY2ZlNzJkY2RmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJ2C0eM2yWiRX2L17afl2OzjQuzk3QC6KyIUKtBhqbo) works for me

It's coz latest Connector Extras fixes that crash

**Comment by Xplodin** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13007677/344501684-e75a343b-fdc8-4382-8fbd-62f8b2f73c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjE5ODksIm5iZiI6MTcxOTkyMTY4OSwicGF0aCI6Ii8xMzAwNzY3Ny8zNDQ1MDE2ODQtZTc1YTM0M2ItZmRjOC00MzgyLThmYmQtNjJmOGIyZjczYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEyMDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjMxZmEwZDVlMjg1MjQ0YmYzMzEyY2JhYzE0MmNjZWRmZDA0MzM5MWFkYWRmMDIwNWRjY2ZlNzJkY2RmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJ2C0eM2yWiRX2L17afl2OzjQuzk3QC6KyIUKtBhqbo) works for me
> 
> It's coz latest Connector Extras fixes that crash

also worked before updating connector extras, on continuity beta 4

**Comment by BoardAnims** [comment]
Latest version of Connector Extras does indeed seem to fix this. It also seems to have fixed the Blueprint incompatibility Might need to re-check that though...

**Comment by Nicodemus111** [comment]
Continuity connected textures still do not work with blueprint installed.

**Comment by BoardAnims** [comment]
> Continuity connected textures still do not work with blueprint installed.

You're right, It no longer seems to crash the game now, but the continuity mod itself seems to not work at all when Blueprint is installed alongside it... Someone really needs to fix this..

**Comment by lSherozl** [comment]
Connector conflicts with Blueprint and connectivity, causing crashes when creating a world for me

**Comment by PenumbraStar** [comment]
Heres hoping someone finds a workaround soon
