### ISSUE TITLE
adventureZ doesnt work (no crash)

### ISSUE THREAD

**Issue by Fla-mme** [Sinytra/Connector#1187]
### Minecraft version

1.20.1

### Describe the bug

doesnt crash but the mod doesnt work, items and mobs are accesable in the creative menu but does not spawn in chests or terrain. (all mods are up to date according to modrinth)

### Steps to reproduce

1.create a forge 47.1.3 instance
2. install sinytra connector, connector extras and forgified fabric API 
3. install adventureZ and its dependencies cloth config API (either the forge version or fabric results in the same issue)
4. go to the end and see that none of the mobs that are supposed to spawn around spawns (easiest way) even tho it happens in the overworld nether and chest as well
...

### Additional context

well adventureZ suppose to have some unique mobs spawn in the overworld end and nether with some items from chests around the world but the items never appear in chests, the mobs don't spawn yet you can get and spawn everything with commands and the creative menu
https://modrinth.com/mod/adventurez

I wanna add I think voidZ (dependent on adventureZ) will not work either but haven't checked it, additionZ works btw

**Comment by RoomAlex68** [comment]
AdventureZ seems to work for me when using Connector Beta 44

**Comment by Fla-mme** [comment]
i wanna add, i tried without and with nullscape, with nullscape, I found only 1 whale after searching through thosends of blocks, and no endwarthogs, without nullscape, I found 4 whales and 4 endwarthogs

**Comment by Su5eD** [comment]
Moving to #1343
