### ISSUE TITLE
TieredZ doesnt work (no crash)

### ISSUE THREAD

**Issue by Fla-mme** [Sinytra/Connector#1188]
### Minecraft version

1.20.1

### Describe the bug

when trying to craft an item it doesnt give it the unique attributes as it should, and reforging item doesnt work either (same issue as adventureZ, mod doesnt crash, but doesnt work, both from the same author but on same dependencies)

### Steps to reproduce

1. create a forge 47.1.3 instance
2. install sinytra connector, connector extras and forgified fabric API
3. install tieredZ and its dependencies cloth config API, auto tag and libz (all fabric)
4. try to craft an item and see it doesn't give it the unique attributes it should give, and reforging an item in the anvil doesn't work either

...

### Additional context

nothin to add

**Comment by RoomAlex68** [comment]
TieredZ work for me when using Connector Beta 44

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
