### ISSUE TITLE
Inject in Fabric BowItem.onStoppedUsing does not inject in Forge BowItem.releaseUsing

### ISSUE THREAD

**Issue by Galysso** [Sinytra/Connector#1190]
### Mod Name

simple quiver

### Mod Homepage

https://modrinth.com/mod/simple-quiver

### Minecraft version

1.20.1

### Describe the bug

Arrows are not removed from the quiver after shooting

### Steps to reproduce

Even though I probably located the issue, here is a minimal example using a very simple mod (simple quiver) for you to test easily:

1. give yourself a bow
2. give yourself one or more arrow
3. give yourself a quiver from the mod
4. left click on the quiver, then with the quiver use right click on the arrows to fill it with arrows
5. place the quivers on your chest slot
6. in survival mode, shoot an arrow

The result is that your arrows in the quiver will not be removed (and you even can loot the arrows on the ground).

### Logs

Logs are probably irrelevant here

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
