### ISSUE TITLE
[1.20.1] Create: Railways Navigator + Seamless Loading Screen -> YACL mixin inject failure and startup crash

### ISSUE THREAD

**Issue by Alexander3847575** [Sinytra/Connector#1191]
### Mod Name

Create: Railways Navigator (mcdragonlib), Seamless Loading Screen

### Mod Homepage

https://github.com/MisterJulsen/MC-DragonLib2/

### Minecraft version

1.20.1

### Describe the bug

When attempting to boot with Create Railways Navigator, Seamless Loading Screen and Sinytra Connector, the mixin from YACL on `ContainerEventHandler` fails to apply and crashes pre-modload.

### Steps to reproduce

When the following mods are installed, the game crashes on startup.

### Mods used to replicate:
- Sinytra Connector 1.0.0 beta 44
- Forgified Fabric API 0.9.22+1.11.8+1.20.1
- Create 0.5.1f
- Create Railways Navigator 1.20.1-0.5.4
- Seamless Loading Screen 2.0.3

`.connector/` folder was cleared before verification.

### Logs

https://mclo.gs/rPueP6C

### Additional context

⚠️ **This issue ONLY occurs when ALL mods are present. No Fabric mods or YACL need to be installed for this to occur.**
Tested combinations of:
- RailNav + Seamless
- Seamless XOR RailNav + Sinytra
- Seamless + Create only + Sinytra

all booted properly.

### Environment details:
- Forge 47.3.1 - 1.20.1

Please let me know if any further information or other action is required, and if I should post this to the relevant mod repos.

**Comment by Su5eD** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: `@At`("INVOKE") on net/minecraft/client/gui/components/events/ContainerEventHandler::modifyFocusCandidates with priority 1000 cannot inject into net/minecraft/client/gui/components/events/ContainerEventHandler::m_264486_(Lnet/minecraft/client/gui/navigation/ScreenRectangle;Lnet/minecraft/client/gui/navigation/ScreenDirection;Lnet/minecraft/client/gui/components/events/GuiEventListener;Lnet/minecraft/client/gui/navigation/FocusNavigationEvent;)Lnet/minecraft/client/gui/ComponentPath; merged by de.mrjulsen.mcdragonlib.mixin.ContainerEventHandlerMixin with priority 1000 [ -> redirect$zkh000$yet_another_config_lib_v3$modifyFocusCandidates(Lnet/minecraft/client/gui/components/events/ContainerEventHandler;Lnet/minecraft/client/gui/navigation/ScreenRectangle;Lnet/minecraft/client/gui/navigation/ScreenDirection;Lnet/minecraft/client/gui/components/events/GuiEventListener;Lnet/minecraft/client/gui/navigation/FocusNavigationEvent;)Ljava/util/List; -> Prepare]

Does this occur without Connector installed? According to the log, a conflict occurs between mods YACL and mcdragonlib.

**Comment by Alexander3847575** [comment]
It does not, weirdly enough. `mcdragonlib` is an internal library in Railways Navigator, and I'm not sure where YACL is coming from. You can see my tested mod combinations under the Additional Context section; all done in the provided environment.

**Comment by Su5eD** [comment]
This was now fixed in [createrailwaysnavigator-forge-1.20.1-0.5.5](https://www.curseforge.com/minecraft/mc-mods/create-railways-navigator/files/5528569)
