### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by showyxxx** [Sinytra/Connector#1192]
### Mod Name

sinytra connector

### Mod Homepage

https://modrinth.com/mod/connector

### Minecraft version

1.20.1

### Describe the bug

minecraft crashes when launched with the sinytra connector mod. when I turn it off, everything is fine

### Steps to reproduce

1. installing other mods
2. installing sinytra
3. minecraft crash
4. turn off mod and launch minecraft
...

### Logs

https://gist.github.com/showyxxx/2003ade1c94490d12388fa248b3e9414

**Comment by showyxxx** [comment]
my mods:
![image](https://github.com/Sinytra/Connector/assets/174203118/2e16212b-5736-49d0-b390-f6c69b497542)
![image](https://github.com/Sinytra/Connector/assets/174203118/1ee659bf-e5b7-4404-b2a5-f4511046d056)

**Comment by showyxxx** [comment]
I solved the problem on my own. incompatibility with optifine

**Comment by showyxxx** [comment]
closed

**Comment by RoomAlex68** [comment]
Iris isn't compatible with Connector 
Use Ocules as an alternative
