### ISSUE TITLE
The Reactive Music mod does not work

### ISSUE THREAD

**Issue by OneWorldStudio** [Sinytra/Connector#1193]
### Minecraft version

1.20.1

### Describe the bug

I don't know

### Steps to reproduce

1.
2.
3.
...

### Logs

https://paste.ubuntu.com/p/Sp666sKXb8/

### Additional context

Hello, fix plz

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin

**Comment by MasterCakeX5** [comment]
I have the same problem in 1.21.1

Reactive Music 1.0.3 for 1.21.1 crashes the game at startup with this message:
The game crashed: rendering overlay
Error: java.lang.ExceptionInInitializerError: null
Exit-Code:-1
When I disable the mod it starts normally.

It would be wonderful to have this mod working.
Thanks!
