### ISSUE TITLE
Single server tick took 60 seconds

### ISSUE THREAD

**Issue by qeqeee** [Sinytra/Connector#1194]
### Mod Name

BMC4

### Mod Homepage

https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4

### Minecraft version

1.20.1

### Describe the bug

Whenever someone moves close to something the server crashes and everyone on the server gets timed out

### Steps to reproduce

1.
2.
3.
...
[crash-2024-06-29_11.29.32-server.txt](https://github.com/user-attachments/files/16042075/crash-2024-06-29_11.29.32-server.txt)

### Logs

<script src="https://gist.github.com/qeqeee/9fbae63898d3598a49d56afb645a44b2.js"></script>

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
