### ISSUE TITLE
Parzi's Star Wars Mod/Embeddium/Connector crash

### ISSUE THREAD

**Issue by pesesta** [Sinytra/Connector#1195]
### Mod Name

Embeddium/Galaxies: Parzi's Star Wars Mod

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/embeddium and https://www.curseforge.com/minecraft/mc-mods/pswg

### Minecraft version

1.20.1

### Describe the bug

Galaxies: Parzi's Star Wars Mod crashes when used with Connector and Embeddium

### Steps to reproduce

1. Load Minecraft 1.20.1 with:

- Embeddium (_embeddium-0.3.21+mc1.20.1.jar_)
- Forgified Fabric API (_fabric-api-0.92.2+1.11.8+1.20.1.jar_)
- Connector (_Connector-1.0.0-beta.44+1.20.1.jar_)
- Connector Extras (_ConnectorExtras-1.11.1+1.20.1.jar_)
- Galaxies: Parzi's Star Wars Mod (_pswg-0.0.109+1.20.1.jar_)

### Logs

https://gist.github.com/pesesta/8683d9f49fd5a6ab45166e5cc2f3cc5f

### Additional context

This isn't a Sinytra issue (PSWG and Sinytra run fine together without Embeddium), and it's definitely not Sinytra's problem. However Embeddium is a commonly used performance mod for Forge, and enough bugs have been raised here about theoretical PSWG incompatibility with Sinytra that I thought I'd log this for others like me who come here trying to work out why their PSWG/Connector build results in a crash.

**Comment by embeddedt** [comment]
The next version of Embeddium (beta: https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip) tweaks the entity renderer optimization to allow for better mod compatibility, and will likely fix this issue.

**Comment by pesesta** [comment]
Thank you (for this specifically, and your work on Embeddium in general). I can confirm that loading PSWG with Sinytra and this new Embeddium beta file has fixed my crashing at start-up issue.
