### ISSUE TITLE
Crash with Music Moods

### ISSUE THREAD

**Issue by sherpascott** [Sinytra/Connector#1196]
### Mod Name

Music Moods

### Mod Homepage

Link to Music Moods: https://modrinth.com/mod/music-moods

### Minecraft version

1.20.1

### Describe the bug

Hey so the dev for music moods just added some support for forge through sinytra connector, but I get this issue when adding it to my modpack. I'm assuming it's a conflict with another mod, but idk which. I tried it with v43 and v44 of connector.

### Steps to reproduce

1. Add Music Moods
2. Launch Minecraft
3. Crash
...

### Logs

https://gist.github.com/AvaloriaSinytra/1afdc64c9942fdbb56fe1609c19ff57c

### Additional context

I'm not using connector extras because of incompatability with valkyrian skies idk if that's the issue

**Comment by Su5eD** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: `@At`("STORE" ordinal=-1 index=-1) on net/minecraft/client/sounds/MusicManager::injected with priority 1000 cannot inject into net/minecraft/client/sounds/MusicManager::m_120183_()V merged by gay.ampflower.musicmoods.mixin.MixinMusicManager with priority 1000 [PREINJECT Applicator Phase -> cumulus_menus.mixins.json:client.MusicManagerMixin from mod cumulus_menus -> Prepare Injections ->  -> localvar$bkd000$cumulus_menus$injected(Lnet/minecraft/sounds/Music;)Lnet/minecraft/sounds/Music; -> Prepare]

The mod you're looking for is `cumulus_menus`
