### ISSUE TITLE
Game crash when running world with Gallant's Gauntlets mod

### ISSUE THREAD

**Issue by Hoa78DaMastermind** [Sinytra/Connector#1198]
### Mod Name

Gallant's Gauntlets

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/gauntlets

### Minecraft version

1.20.1

### Describe the bug

Everything is fine until I play the world. Terrain loaded, joinning world text pop up and then the game crashed

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/Hoa78DaMastermind/c5d7a787422c895bd97add799f7f2540

**Comment by Su5eD** [comment]
I am getting the same error on Fabric https://mclo.gs/q0fnQTy. Please report this to the mod author.
