### ISSUE TITLE
modpack crash

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#120]
### Describe the bug

crashes when i launch my modpack

### Steps to reproduce

1. launch modpack then it will crash
2.
3.
...

### Additional context

[latest.log](https://github.com/Sinytra/Connector/files/12447101/latest.log)
[debug.log](https://github.com/Sinytra/Connector/files/12447103/debug.log)

link to modpack mods: https://legacy.curseforge.com/minecraft/modpacks/wilderness-odyssey/relations/dependencies

**Comment by Su5eD** [comment]
The log doesn't contain any information related to a crash or exception. Do you perhaps have a crash report? Also, the modpack you linked doesn't list connector in its dependencies. Please try to identify the problematic mod / mods.

**Comment by Thunderrock424242** [comment]
It's fabric mods that are causing it to crash

**Comment by Su5eD** [comment]
Can you give an exact list of (Fabric) mods in the modpack? Do these mods work on their own? At this moment there is not enough information to determine the cause of the issue.
