### ISSUE TITLE
Particular (sushi_bar lib) crashes on startup neoforge 1.20.1

### ISSUE THREAD

**Issue by OlehooLE** [Sinytra/Connector#1201]
### Mod Name

Particular / Sushi Bar

### Mod Homepage

https://modrinth.com/mod/particular/version/1.1.0 https://modrinth.com/mod/sushi-bar/version/0.1.0

### Minecraft version

1.20.1

### Describe the bug

Crash on startup with particular + sushi bar installed

### Steps to reproduce

1. Install Sinytra connector, forgified fabric api (last version)
2. Install sushi bar (fabric) and Particular (fabric)
3. Launch Minecraft, get a crash
...

### Logs

https://pastebin.com/XNVktbNT https://gist.github.com/OlehooLE/e67e7568bf26d1cda6e99a1ea61f044d

**Comment by Su5eD** [comment]
> Caused by: java.lang.ClassNotFoundException: io.wispforest.owo.config.ConfigWrapper

You are missing [owolib](https://modrinth.com/mod/owo-lib/versions).
