### ISSUE TITLE
Incompatible with Adventures in Time mod

### ISSUE THREAD

**Issue by Emberdeath** [Sinytra/Connector#1202]
### Mod Name

Adventures in Time

### Mod Homepage

https://modrinth.com/mod/ait

### Minecraft version

1.20.1

### Describe the bug

Crashes upon server loading world

### Steps to reproduce

1. Download Connector and AIT and owo lib and have them in server's mod folder.
2. Launch server
3. Immediately as it finishes generating world it will crash.
...

### Logs

N/A

### Additional context

Doesn't seem to happen on single player world's, just when the server tries to start the mod.

**Comment by Su5eD** [comment]
Confirmed to work on beta 43
