### ISSUE TITLE
Many mods not working

### ISSUE THREAD

**Issue by G3DX** [Sinytra/Connector#1207]
### Minecraft version

1.20.1

### Describe the bug

Apparently some mods aren´t working with the connector, i got a new computer, and i´m installing the mods again, but i don´t understand why it is not working properly

### Steps to reproduce

1. I installed the mods DynamicSurroundings, friendsandfoes, entity texture features, entity model features
2. Then i installed the Synitra Connector
3. The Launcher told me to put some extra mods that the othe mods need so i install them: gml, ash api, puzzle lib, midnight lib and mod menu
4. When i loaded it the game crashed

Crash Report:
![Captura de pantalla 2024-07-02 150511](https://github.com/Sinytra/Connector/assets/174533413/1cc9e60f-68e8-4e65-977c-2a3838dcd584)

**Comment by coco875** [comment]
if you go on the discord we can help you fix this it's a easy solution

**Comment by G3DX** [comment]
> if you go on the discord we can help you fix this it's a easy solution

Thank you i´m going
