### ISSUE TITLE
Backport to older minecraft versions?

### ISSUE THREAD

**Issue by DonFlymoor** [Sinytra/Connector#121]
### Describe the bug

It would be great if this could support older minecraft versions such as 1.19.2, 1.18, and possibly further back

### Steps to reproduce

1. Search for a version below 1.20.1

**Comment by Su5eD** [comment]
Backports of Connector are not planned, sorry. It would require backporting all of FFAPI, FFLoader, and also double the maintenance costs. Our focus is on future versions where running Connector will become easier over time.
