### ISSUE TITLE
Incompatible with Dark loading screen

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1211]
### Mod Name

Dark loading screen

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen

### Minecraft version

1.20.1

### Describe the bug

doesn't start with dark loading screen mod for fabric.

### Steps to reproduce

1. add "dark-loading-screen-1.6.14.jar" into the mods folder
2. launch Minecraft
3. the game will crash with exit code -1

### Logs

https://gist.github.com/vinnyg0621/f35215bc590b18b14b5f63cf328d552d

**Comment by Su5eD** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector postWindowCreated()Lorg/lwjgl/opengl/GLCapabilities; in **embeddium.mixins.json**:workarounds.context_creation.WindowMixin from mod embeddium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap **embeddium**-refmap.json

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
