### ISSUE TITLE
Continuity textures not connecting w/ embeddium 0.3.23 (mc1.20.1)

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1212]
### Mod Name

Continuity

### Mod Homepage

https://modrinth.com/mod/continuity

### Minecraft version

1.20.1

### Describe the bug

textures do not connect with optifine's ctm feature

### Steps to reproduce

1. Enable the default connected textures resourcepack
2. 
3.
...

### Logs

https://gist.github.com/vinnyg0621/a94941a276aaf6ba58274efa072c9804

### Additional context

even when the built-in resource packs are enabled, the textures don't connect. they don't even connect with lazurite, which is now deprecated and should be removed. I removed it and they are still not connecting. I'm also using the clean glass from vanilla tweaks. it's still not connecting. but the connected lapis and bookshelves are working from vanilla tweaks. how can I get connected textures now?
![Screenshot 2024-07-04 121333](https://github.com/Sinytra/Connector/assets/57818441/2917781c-4fc7-41bf-99b8-b9b444ffbe9e)
![2024-07-04_12 02 35](https://github.com/Sinytra/Connector/assets/57818441/22c7bedd-72e3-49dc-b9e8-133afb863585)
![2024-07-04_12 16 58](https://github.com/Sinytra/Connector/assets/57818441/b4fc0ca5-6c4b-4665-bcab-b717de30986f)

**Comment by liangmoe** [comment]
You have blue print
