### ISSUE TITLE
Incompatible with Marium's Soulslike weaponry and Celestisynth

### ISSUE THREAD

**Issue by N3WtrAllX** [Sinytra/Connector#1214]
### Mod Name

Marium's Soulslike weaponry & Celestisynth 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry

### Minecraft version

1.20.1

### Describe the bug

Using both of these mods (Celestisynth & Marium's Soulslike weaponry) at the same time the game crashes. Using these mods separately they work

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/5kG1NvNh

### Additional context

Celestisynth mod homepage: https://www.curseforge.com/minecraft/mc-mods/celestisynth

**Comment by Su5eD** [comment]
Duplicate of #231
