### ISSUE TITLE
why is this not working?

### ISSUE THREAD

**Issue by temginson** [Sinytra/Connector#1216]
### Minecraft version

1.20.1

### Describe the bug

it says that i need to instal fabric any versioin even tho i have fabric installed

### Steps to reproduce

1.start minecraft with inventory management mod 1.3.1
2.
3.
...

### Logs

 temginson/gist:763fe67b86c6f3d67718278fc30023fb

### Additional context

![image](https://github.com/Sinytra/Connector/assets/132342905/8ef3b79d-d1da-41e4-a8b5-296ed9f47f7d)

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
