### ISSUE TITLE
Client crash when respawning in the overworld after I died in the nether. 

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1217]
### Mod Name

OpenBlocks Elevator

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator

### Minecraft version

1.20.1

### Describe the bug

the game crashes when I change any dimension with this mod

### Steps to reproduce

1. go into a Nether portal when your spawnpoint is in overworld
2. die in survival mode
3. the world exits and saves

### Logs

https://gist.github.com/vinnyg0621/4e5fcc4dbfa3dc3e3e620bcbe9e0cc6a

### Additional context

in one of my other maps, the same thing happens when I change any dimension, but the game just closes completely, and the log says "Stopping!", but it doesn't give me any exit code.

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
