### ISSUE TITLE
Incompatibility with CreativeCore/AmbientSounds5 (Forge)

### ISSUE THREAD

**Issue by tharrmeehan** [Sinytra/Connector#122]
### Mod Name

Incompatibility with CreativeCore/AmbientSounds5

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/ambientsounds

### Describe the bug

Adding AmbientSounds5 + CreativeCore, which are Forge mods instantly crashes the game upon loading. Using Connector Beta 9 and the latest fabric API

### Steps to reproduce

1. Download CreativeCore and AmbientSounds5
2. Start Game
3. Instant Crash

### Logs

https://gist.github.com/tharrmeehan/aecf97980e1c5dbdbb5513bc05745897

**Comment by BigBull-H3RO** [comment]
Same problem with [CreativeCore](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/4690991) and [ItemPhysic Full](https://www.curseforge.com/minecraft/mc-mods/itemphysic/files/4719251). With CreativeCore the game crashes immediately on startup. I don't see any clues in the log file what the problem could be.

https://gist.github.com/BigBull-H3RO/c23e2a008a88cef1dcc1ad6aa034367d
