### ISSUE TITLE
Plethora (for Fabric) and Kotlin do not work together

### ISSUE THREAD

**Issue by lisiyglobus2015** [Sinytra/Connector#1222]
### Mod Name

Plethora

### Mod Homepage

https://modrinth.com/mod/plethora-peripherals

### Minecraft version

1.20.1

### Describe the bug

when you start the game crashes

### Steps to reproduce

1. Download CC: Tweaked (for Forge), Connector, Connector Extra, Kotlin for Fabric, Plethora for Fabric, Trinkets for Fabric and API Forgified Fabric .
2. Start the game

### Logs

https://pastebin.com/CPPaTb6R

### Additional context

everything starts without Plethora

**Comment by Su5eD** [comment]
> Caused by: java.lang.IllegalStateException: ComputerCraft has not initialised yet?

This is a conflict between Plethora and ComputerCraft. You can try disabling the integration using Connector's "hidden mods" feature. https://sinytra.org/docs/connector/configuration#hiding-forge-mods-presence
