### ISSUE TITLE
Crashed on mouseClicked event handler from configured

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1225]
### Mod Name

Configured

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/configured

### Minecraft version

1.20.1

### Describe the bug

game crashed when clicking on an option in the configured menu.

### Steps to reproduce

1. Open the mod list
2. Click on "config"
3. Click on an option in the configured menu
...

### Logs

https://gist.github.com/vinnyg0621/e107eccf04add469e7616de455ffd492

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
