### ISSUE TITLE
Astrocraft and Citadel do not startup together

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1228]
### Mod Name

Astrocraft

### Mod Homepage

https://modrinth.com/mod/astrocraft

### Minecraft version

1.20.1

### Describe the bug

when installing citadel with astrocraft, the game crashes when initializing game.

### Steps to reproduce

1. add astrocraft for fabric in the mods folder
2. add citadel for forge in the mods folder
3. start the game
...

### Logs

https://gist.github.com/vinnyg0621/735e5d3188c9b396314519330a7ada8a

### Additional context

i have alex's mobs and caves in my mods folder too, which that mod is required for

**Comment by Su5eD** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector modifyTwilightColor(Lnet/minecraft/client/multiplayer/ClientLevel;F)F in astrocraft.mixins.json:MixinWorldRenderer from mod astrocraft failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap astrocraft-refmap.json

This is a redirect conflict between the two mods, and is outside our control. I suggest asking the mod's devs if it's possible to use a chainable injector instead, such as `ModifyExpressionValue` or `WrapOperation`.
