### ISSUE TITLE
[1.20.1] Immersive Portals (Fabric) and Scannable (Forge)

### ISSUE THREAD

**Issue by Cephelo** [Sinytra/Connector#1229]
### Mod Name

Immersive Portals + Scannable

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/scannable/files/4763070

### Minecraft version

1.20.1

### Describe the bug

Crash to desktop when Immersive Portals (fabric) and Scannable (forge) are loaded together due to a shader bug.

### Steps to reproduce

1. Install both mods and their dependencies
2. Launch the game.
3. Voila, crashlog.

All mods were downloaded directly via the Curseforge launcher, save for Immersive Portals.

Exact versions used:
Forge - 47.3.0
Forgified Fabric API ([fabric-api-0.92.2+1.118.1.20.1.jar](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/files/5387432))
Sinytra Connector ([Connector-1.0.0-beta44+1.20.1.jar](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/files/5453446))
Immersive Portals ([immersive-portals-3.3.9-mc1.20.1-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod/files/5028868))
Architechtury API ([architechtury-9.2.14-forge.jar](https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/5137938))
Scannable ([scannable-MC1.20.1-forge-1.7.12+18ccb75.jar](https://www.curseforge.com/minecraft/mc-mods/scannable/files/4763070))

### Logs

Crash log: https://pastebin.com/y9qNcuCD
debug.log: https://paste.ee/p/pO9DE

### Additional context

Let me know if there's any way I can help.  Thank you for such an amazing tool!

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
