### ISSUE TITLE
Incompatibility regarding Mariums Soulslike Weaponry in conjunction with other mods

### ISSUE THREAD

**Issue by tharrmeehan** [Sinytra/Connector#123]
### Mod Name

Mariums Soulslike Weaponry/Iron's Spells 'n Spellbooks

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks /  https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry

### Describe the bug

Using the forementioned mods together, which both depend on GeckoLib, triggers a crash while loading. I think there was a similar issue, which had been fixed before.

### Steps to reproduce

1. Download both Mods and their dependencies
2. Launch the game
3. Crash

### Logs

https://gist.github.com/tharrmeehan/23506f0ec2c19c03313e0d8befba243b

**Comment by Su5eD** [comment]
The error is caused by Geckolib Forge being initialized earlier than it expects by one of the Fabric mods. Can you try using the Fabric version of Geckolib instead?

**Comment by tharrmeehan** [comment]
Using Geckolib fabric causes a similar error. 

https://gist.github.com/tharrmeehan/33155cd106c7bd269169ec195fc3adee

I have to add that isolating the mods does make it work (with iron spells for example), but it seems that a specific mod (which i am trying to find out which one) is causing this crash to happen without being mentioned in the logs.

**Comment by tharrmeehan** [comment]
I did actually update to the latest Connector and Fabric API, but to no avail. I'm not getting smarter by skimming through the logs either, but I will try to remove mods one by one and see if that solves the problem.

**Comment by tharrmeehan** [comment]
and the game crashes due to incompatibility with a iron's spells.

https://gist.github.com/tharrmeehan/f233a1b2c4a54355fa9c64cf88232505

**Comment by Su5eD** [comment]
Sounds like an incompatibility between Forge and Fabric geckolib. Unfortunately, there isn't much that can be done about it as the two versions contain different code. And two mods with identical mod IDs can't be run together.

**Comment by tharrmeehan** [comment]
Alright, thanks for the reply. I'm closing this issue.
