### ISSUE TITLE
Plethora Peripherals (fabric) and CC:Tweaked (forge)

### ISSUE THREAD

**Issue by Cube-Killer** [Sinytra/Connector#1231]
### Mod Name

Plethora Peripherals (fabric) + CC:Tweaked (forge)

### Mod Homepage

https://modrinth.com/mod/plethora-peripherals

### Minecraft version

1.20.1

### Describe the bug

Crash when Plethora + CC:Tweaked loaded together due to "ComputerCraft has not initialised yet?"

### Steps to reproduce

1.Install mods and their dependencies
2.Launch game
3.Game crashes
...

### Logs

https://gist.github.com/Cube-Killer/2c5a7fa57ca446cc819692187bbccb96

### Additional context

cc-tweaked-1.20.1-forge-1.111.0
Connector-1.0.0-beta.44+1.20.1
ConnectorExtras-1.11.1+1.20.1
fabric-api-0.92.2+1.11.8+1.20.1
fabric-language-kotlin-1.11.0+kotlin.2.0.0
Plethora-Fabric-1.11.7
trinkets-3.7.2

**Comment by Su5eD** [comment]
The mod was built for the Fabric version of CC Tweaked and is not compatible with the Forge one. Please see our [FAQ](https://sinytra.org/docs/connector/faq#%EF%B8%8F-can-i-use-a-forge-mod-with-its-fabric-addons-and-vice-versa) for more information.

**Comment by minecraftbossdj** [comment]
what about now? cctweaked updated a lot, and its actually not that far anymore, they separated the libraries that fabric only had, and those libraries are now included in the 1.116.1 port of plethora (re:plethora)

also cc fabric and most cc addons work via kilt, hell all cc addon mods do, just some dont load for other reasons.

really you would just need to write a tiny bit of cc compat which is asking a lot already, but just saying more plausible now
