### ISSUE TITLE
In-Game Switch Account Incompatible?

### ISSUE THREAD

**Issue by DiscFragment** [Sinytra/Connector#1232]
### Mod Name

In-Game Account Switcher

### Mod Homepage

https://modrinth.com/mod/in-game-account-switcher

### Minecraft version

1.20.1

### Describe the bug

```
Failed to load correctly,
https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues
	Exception message: java.lang.NoSuchFieldError: IGNORE_ALL_VERSION 
``` 

### Steps to reproduce

- Download the Mod
- Attach the Connector to the Modpack
- Just Open the game.

### Logs

https://mclo.gs/XO0n4Gw

### Additional context

# Crash Report

```
Download
``` 

[crash-2024-07-13_17.07.06-fml.txt](https://github.com/user-attachments/files/16202434/crash-2024-07-13_17.07.06-fml.txt)

**Comment by Su5eD** [comment]
Seems like the mod is not compatible with the Forge version you're using. I'd suggest asking the mod author, as the issue isn't related to connector.
