### ISSUE TITLE
[Crash - Incompatibility] Ranged Weapon API and UnionLib

### ISSUE THREAD

**Issue by ShinryuAspect** [Sinytra/Connector#1236]
### Mod Name

UnionLib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/unionlib

### Minecraft version

1.20.1

### Describe the bug

The game crashes when trying to open the inventory or shoot an arrow (doesn't matter the weapon used, be it a Vanilla bow or one from Archers)) and complais about "Can't find attribute ranged_weapon:haste"

### Steps to reproduce

1. Create an instance of Minecraft 1.20.1 (I'm using latest Forge by this time 47.3.5)
2. Load the set of mods from the RPG series (I simply downloaded any of daedelus_dev's and its dependecies) along Sinytra Connector and Extras
3. Add UnionLib to the mix
4. Once in-game, try to open the inventory or shoot an arrow (doesn't matter if it's vanilla weapon or one from Archers)
5. Watch the world burn and Minecraft crash

### Logs

https://gist.github.com/AvaloriaSinytra/3a95bf3f2219733fe0959188f3959575

### Additional context

The link to the other source mod: https://www.curseforge.com/minecraft/mc-mods/ranged-weapon-api

I'm attaching here a link to the support ticket I opened on the Discord in which I also talked about this issue and some steps I followed: https://discord.com/channels/1141048834177388746/1262403339904090225

**Comment by Su5eD** [comment]
This is caused by unionlib, which mixins into createLivingAttributes and outright cancels it, preventing RangedWeaponAPI from providing its own attributes. I recommend forwarding this issue to unionlib's author.
