### ISSUE TITLE
1.16.5 support for players with old hardware (OpenGL 2.0 hardware)

### ISSUE THREAD

**Issue by NightLighter423** [Sinytra/Connector#1237]
It would be nice if players with old hardware(OpenGL 2.0 hardware) can also play, if there is a version of this mod worked for 1.16.5 then players like me could play as well!

**Comment by coco875** [comment]
Su5ed mention in [FAQ](https://sinytra.org/docs/connector/faq) no backport are planned (and opengl 2.0 are very old already 19 years)
