### ISSUE TITLE
Unable to start with luckperms

### ISSUE THREAD

**Issue by Ax3dGaming** [Sinytra/Connector#1243]
### Mod Name

Luckperms

### Mod Homepage

https://luckperms.net

### Minecraft version

1.20.1

### Describe the bug

The server doesn't start

### Steps to reproduce

1. Put the fabric version of luckperms in the mod folder
2. Start the server

### Logs

https://pastebin.com/zWrK2d7p

**Comment by Su5eD** [comment]
The native Forge version of LuckPerms works as intended, please use that instead.
