### ISSUE TITLE
Progressive archery is incompatible

### ISSUE THREAD

**Issue by RaptorZeraora** [Sinytra/Connector#1247]
### Mod Name

Progressive archery

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/progressive-archery

### Minecraft version

1.20.1

### Describe the bug

Compatibility issue

### Steps to reproduce

1. Install the correct mods
2. Launch the game
3. Game crashes with exit code: 1

### Logs

https://gist.github.com/RaptorZeraora/bb7850d5112710d447aa73e94e987089

### Additional context

Installed mods:
Connector-1.0.0-beta.44+1.20.1
fabric-api-0.92.2+1.11.8+1.20.1
progressivearchery-1.1.3.a-1.20.1

**Comment by Su5eD** [comment]
Duplicate of #1157

**Comment by RaptorZeraora** [comment]
Oh, I was not aware of that
