### ISSUE TITLE
Create fails to load correctly after installing automobility

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1248]
### Mod Name

Automobility

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/automobility

### Minecraft version

1.20.1

### Describe the bug

it says during startup: "Create has failed to load correctly".

### Steps to reproduce

1. Add create mod
2. Add automobility into the mods folder
3. Start up the game
...

### Logs

https://paste.gg/p/anonymous/d2d412ffc76e412095aea60ca01266ed

### Additional context

crash log:
[crash-2024-07-19_20.00.52-fml.txt](https://github.com/user-attachments/files/16318643/crash-2024-07-19_20.00.52-fml.txt)

**Comment by Su5eD** [comment]
Connector, FFAPI, Create and Automobility run fine together.
![image](https://github.com/user-attachments/assets/49d84411-3293-450a-ba7e-8392c8869c2a)

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
