### ISSUE TITLE
ViaFabric/ViaFabricPlus

### ISSUE THREAD

**Issue by jgrnot** [Sinytra/Connector#1254]
### Mod Name

ViaFabric/ViaFabricPlus

### Mod Homepage

https://modrinth.com/mod/viafabricplus

### Minecraft version

1.20.1

### Describe the bug

After installing ViaFabricPlus and launching minecraft, everything freezes on the "launching bootstrap resources" screen

### Steps to reproduce

1. Download sinytra connector and its dependencies on forge 47.1.30
2. Download ViaFabricPlus
3. Launching minecraft
4. That's the error
![javaw_u4x3oyUzrr](https://github.com/user-attachments/assets/7cbc9f28-89b7-4c87-ab20-2530320008dc)

### Logs

https://gist.github.com/jgrnot/4e67a4c0cb9f33b2219a0faef32cc854

**Comment by Hoshino-Yumetsuki** [comment]
same as https://github.com/Sinytra/Connector/issues/1209
