### ISSUE TITLE
Server crash on startup: `ClassNotFoundException: (...).mod.DummyTarget`

### ISSUE THREAD

**Issue by minisbett** [Sinytra/Connector#1255]
### Minecraft version

1.20.1

### Describe the bug

The server crashes on start, with the exception mentioned in the title

### Steps to reproduce

1. Install the BetterMC server-pack (https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4)
2. Start the server

### Logs

debug.log: https://gist.github.com/minisbett/2bf7f532a6bafdabb3b4049549b0a1ea

**Comment by minisbett** [comment]
Apparently this was related to a forge mod using the wrong version (targetting 1.21). Not sure why it leads to this error.

**Comment by Su5eD** [comment]
I suppose forge refused to load any mods once it detected a loading error, yet connector still tried to load the mod class
