### ISSUE TITLE
[Incompatible] Sounds not working on modded inventories (such as Sophisticated Backpats and probably Storate too)

### ISSUE THREAD

**Issue by ShinryuAspect** [Sinytra/Connector#1257]
### Mod Name

Sounds

### Mod Homepage

https://modrinth.com/mod/sound

### Minecraft version

1.20.1

### Describe the bug

Sounds provides custom sounds for certain actions (such as inventory scrolling, moving between slots, etc.). It seems those sounds are being reproduced when using certain modded inventories (I've experienced this with Sophisticated backpacks)

### Steps to reproduce

1. Launch Minecraft with Sophisticated Backpacks and Sounds.
2. Perform any invetory related action (dragging, droping, etc.) on bothe Minecrat's Inventory and a Backpack's and hear the first reproducing the sounds, while the modded stays silent.

### Logs

Don't think it's necessary (hit me up if needed and I'll atach it)

### Additional context

It seems it's not literally any modded inventory, as I can hear the sounds when, for example, moving items from and to Curios slots.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
