### ISSUE TITLE
not sure whats causing this crash and was unsure but i am guessing connector has something to do with it

### ISSUE THREAD

**Issue by Aabyiswack** [Sinytra/Connector#1258]
### Mod Name

Not sure

### Mod Homepage

not found yet

### Minecraft version

1.20.1

### Describe the bug

Whenever i open a screen where i have to select items it crashes, for example: advanced xray block select screen and heracles quest book block icon select screen

### Steps to reproduce

1. open a screen where you have to select blocks or items
2.
3.
...

### Logs

https://gist.githubusercontent.com/Aabyiswack/c25f5f0cd155d0844940285aff51409f/raw/22c729bd1246c642a8be94d43cea28d68053577f/crash-2024-07-22_12.49.39-client.txt

### Additional context

i will conduct a binary search when im sure sinytra is not exactly the one causing it, just need a confirmation so i can be sure b4 i start

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
