### ISSUE TITLE
adventureZ make a crash at the generation

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#126]
### Mod Name

AdventureZ

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/adventurez

### Describe the bug

crash at the world generation

### Steps to reproduce

1. have ffapi, connector, adventureZ and it's dependencies
2. Run
3. See

### Logs

https://pastebin.com/UXZ6CNaz

**Comment by Su5eD** [comment]
Duplicate of #16
