### ISSUE TITLE
SoulForge 

### ISSUE THREAD

**Issue by HATRED9** [Sinytra/Connector#1261]
### Mod Name

SoulForge 2.2.5

### Mod Homepage

https://modrinth.com/mod/soulforge/version/2.2.5

### Minecraft version

1.20.1

### Describe the bug

.

### Steps to reproduce

start the game - wait for "loading bootstrap resources" - crash

### Logs

https://gist.github.com/fb451a1d9aecf7bafcfbd3cdaaca356a.git

### Additional context

Mod list:
architectury-9.2.14-forge
cardinal-components-api-5.2.2
Connector-1.0.0-beta.44+1.20.1
fabric-api-0.92.2+1.11.8+1.20.1                         (forgified api if anything...)
modmenu-7.2.2
soulforge-2.2.5

**Comment by RoomAlex68** [comment]
ModMenu is incompatible with Connector

**Comment by HATRED9** [comment]
> ModMenu is incompatible with Connector

compatible... the buttons are one to one, but you can change them in the config... In any case, it didn't have any effect if you delete it.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
