### ISSUE TITLE
incompatibility with something

### ISSUE THREAD

**Issue by trykio1** [Sinytra/Connector#1262]
### Mod Name

I assume is between sinystra and another mod

### Mod Homepage

.

### Minecraft version

1.20.1

### Describe the bug

when I join the world it says saving world, and crashes.

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/KrthZiU

### Additional context

it is a custom modpack I am currently working on, when I join my modpack, I get that loading screen it loads into the game where I have to choose singleplayer/multiiplayer/realm/etc.. , I select singeplayer and 1 random world. then after like 1-2 minutes it says saving world and it crashes.

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
