### ISSUE TITLE
Crash mine cells 1 8 3 (1 20 1)

### ISSUE THREAD

**Issue by bro6er** [Sinytra/Connector#1266]
### Minecraft version

1.20.1

### Describe the bug

 Crash mine cells 1 20 1

### Steps to reproduce

1.I can't run the game with the connector and with mine cells (even with older versions)
![Снимок экрана (44)](https://github.com/user-attachments/assets/bc62fed9-8ce2-4edc-aaa9-d5cee133af37)

2.
3.
...

**Comment by RoomAlex68** [comment]
You need owo installed
