### ISSUE TITLE
Description: Initializing game

### ISSUE THREAD

**Issue by JellyBubb1e** [Sinytra/Connector#1268]
### Minecraft version

1.20.1

### Describe the bug

The cilent crashes on start, with the exception mentioned in the title

### Steps to reproduce

1.install [cutetrade](https://modrinth.com/mod/cutetrade) and [cutetranslationapi](https://modrinth.com/mod/cutetranslationapi).
2.Start the server.
3.
...

### Logs

https://mclo.gs/FfGQLYN

**Comment by Su5eD** [comment]
Crash reproduced on Fabric https://mclo.gs/JfOftpb, please report to the mod author
