### ISSUE TITLE
`@Local` application exception.

### ISSUE THREAD

**Issue by melontini** [Sinytra/Connector#127]
### Describe the bug

Sugar from MixinExtras fails validation.

### Steps to reproduce

1. Launch the game.
2. Crash.

### Logs

https://mclo.gs/HYv0kRw

### Additional context

The mixin in question: [[Link]](https://github.com/melontini/andromeda/blob/ea9f207bcc498c97c2287d27cb1693d079964c91/src/main/java/me/melontini/andromeda/mixin/items/infinite_totem/LivingEntityMixin.java#L41).

Locals:
```
Fabric:
    LOCALVARIABLE this Lnet/minecraft/entity/LivingEntity; L0 L25 0
    LOCALVARIABLE source Lnet/minecraft/entity/damage/DamageSource; L0 L25 1
    LOCALVARIABLE itemStack Lnet/minecraft/item/ItemStack; L3 L25 2
    LOCALVARIABLE hand Lnet/minecraft/util/Hand; L6 L8 7
    LOCALVARIABLE itemStack2 Lnet/minecraft/item/ItemStack; L7 L5 3
    LOCALVARIABLE serverPlayerEntity Lnet/minecraft/server/network/ServerPlayerEntity; L16 L14 4

Forge:
    LOCALVARIABLE itemstack1 Lnet/minecraft/world/item/ItemStack; L7 L8 7
    LOCALVARIABLE interactionhand Lnet/minecraft/world/InteractionHand; L6 L8 6
    LOCALVARIABLE serverplayer Lnet/minecraft/server/level/ServerPlayer; L16 L14 3
    LOCALVARIABLE itemstack Lnet/minecraft/world/item/ItemStack; L3 L25 2
    LOCALVARIABLE this Lnet/minecraft/world/entity/LivingEntity; L0 L25 0
    LOCALVARIABLE p_21263_ Lnet/minecraft/world/damagesource/DamageSource; L0 L25 1
```

There's also an issue with [this mixin](https://github.com/melontini/andromeda/blob/ea9f207bcc498c97c2287d27cb1693d079964c91/src/main/java/me/melontini/andromeda/mixin/world/epic_fire/AbstractFireBlockMixin.java#L29C35-L29C36), but this is caused by forge adding new parameters to the method.

**Comment by Su5eD** [comment]
Fixed the fire block mixin as well. Are there are any other failing mixins on connector that need to be fixed?

**Comment by melontini** [comment]
Thank you! 

FireBlock mixin still doesn't apply (https://mclo.gs/1AVegli) and a lambda inject from this [MinecraftClientMixin](https://github.com/melontini/dark-matter/blob/1.19.2-fabric/dark-matter-mirage/src/main/java/me/melontini/dark_matter/impl/mirage/mixin/MinecraftClientMixin.java). I see that you also patched it, but the method should be `m_285666_`. (`lambda$new$1` is a Minecraft supplier for the loading overlay.)

**Comment by melontini** [comment]
Latest CI build broke the mixin back.  The offset is now 4 instead of 7.

**Comment by Su5eD** [comment]
Can you try using the new [latest build](https://github.com/Sinytra/Connector/actions/runs/6039416430) from ea3eef4621982369bcdad55f88e2b03fcb479b41? Andromeda runs on it for me. Also, delete your .connector folder just to be sure.

**Comment by melontini** [comment]
Still crashes. Andromeda force disables features when it detects that it's running on Connector. You need to set `enableFeatureManager` to false and `totemSettings.enableInfiniteTotem` to true in the config.

**Comment by melontini** [comment]
Alright, thank you.
