### ISSUE TITLE
Replay Mod x Sinytra Connector = X

### ISSUE THREAD

**Issue by 50RB3T** [Sinytra/Connector#1270]
### Mod Name

Replay Mod

### Mod Homepage

https://www.replaymod.com/

### Minecraft version

1.20.1

### Describe the bug

error trasforming replaymod-1.20.1-2.6.18.jar

### Steps to reproduce

1. download sinytra connector, forgified fabric api, connector extras and replay mod (all version 1.20.1 and forge loader 47.1.3)
2. install all mods
3. launch game
![error loading mods](https://github.com/user-attachments/assets/c0d96f69-8538-45b0-8a51-55db9cb56044)

### Logs

idk

### Additional context

idk

**Comment by 50RB3T** [comment]
i wanna use my replay mod

**Comment by Su5eD** [comment]
Duplicate of #556

**Comment by 50RB3T** [comment]
i did not know there was one :(
