### ISSUE TITLE
Crash with MCMTFabric

### ISSUE THREAD

**Issue by PeterStrick** [Sinytra/Connector#1272]
### Mod Name

MCMTFabric

### Mod Homepage

https://github.com/himekifee/MCMTFabric

### Minecraft version

1.20.1

### Describe the bug

MCMTFabric crashes when performing it's Mixin Injection check for Method preTick within MinecraftServerMixin

### Steps to reproduce

1. Clone the MCMTFabric repository
2. Run gradlew build
3. Use the built jar file within a fresh installed Forge 47.3.0 Server that only has Connector, Connector Extras, Forgified Fabric API and Cloth Config API

### Logs

Console Output: https://pastebin.com/vft4kn6h, debug.log: https://pastebin.com/QW2zNYGE

### Additional context

Same compiled Jar works fine on Fabric

**Comment by okeanosthedev** [comment]
When do you guys think it will be fixed.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
