### ISSUE TITLE
UU-Matter REI Crash 

### ISSUE THREAD

**Issue by ashi0-a** [Sinytra/Connector#1273]
### Mod Name

Tech Reborn

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/techreborn

### Minecraft version

1.20.1

### Describe the bug

Game crashes when viewing uu-matter recipes in rei

### Steps to reproduce

1. Load in the world
2. Go into inventory
3. Find techreborn:uu_matter
4. Press 'U' on it

### Logs

https://gist.github.com/ashi0-a/60ddc39321ec8c91a1bb39db5afcd8df

### Additional context

Modpack: https://www.transfernow.net/dl/20240801LK0AkkMX

Binary search yielded nothing, the problem was disappearing, maybe multiple mods are conflicting

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
