### ISSUE TITLE
Sinytra Connector crashing launcher on game start when "Special AI" mod is enabled.

### ISSUE THREAD

**Issue by Anakin1773** [Sinytra/Connector#1275]
### Mod Name

Special AI

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/special-ai

### Minecraft version

1.20.1

### Describe the bug

Sintrya Connector crashes with Special AI mod enabled.

### Steps to reproduce

1. Add and enable "Special AI".
2. Add and enable "Sintrya Connector" and "Forgified Fabric API".
3. Launch the game.

### Logs

https://mclo.gs/dH8s47q

### Additional context

Special AI is a native Forge mod.

I only installed Sintrya Connector to acquire "Enhanced Block Entities" and "Concurrent Chunk Management Engine", and as such, the two are my only installed and enabled Fabric mods. 

Most of my mods were disabled for diagnosing this issue, so I implore the case reviewer to ignore all disabled mods if possible. (I can whittle my modlist down to just Sinytra Connector, Forgified Fabric API and Special AI being enabled if my case reviewer requests it).

**Comment by WitherTM** [comment]
could you try again with just connector, ffapi and special ai?

**Comment by Anakin1773** [comment]
I'll try it.

Edit: Still didn't work.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
