### ISSUE TITLE
Bending

### ISSUE THREAD

**Issue by TheBalladeer6thOfTheFatuiHarbingers** [Sinytra/Connector#1276]
### Mod Name

Bending

### Mod Homepage

https://modrinth.com/plugin/bending

### Minecraft version

1.20.1

### Describe the bug

crash

### Steps to reproduce

download mod with syntra

### Logs

none

### Additional context

none

**Comment by OrdinaryCloverOC** [comment]
https://github.com/Sinytra/Connector/issues/727

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
