### ISSUE TITLE
Sinytra Connector crashing launcher on game launch when Bewitchment is enabled

### ISSUE THREAD

**Issue by MrUnicycle** [Sinytra/Connector#1277]
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Minecraft version

1.20.1

### Describe the bug

Connector+Bewitchment=kabloowie

### Steps to reproduce

1. Install Connector and its dependencies
2. Install Bewitchment and its dependencies
3. Launch game
4. Crash

### Logs

[latest.log](https://github.com/user-attachments/files/16484625/latest.log)

### Additional context

When I came across this issue, I expected that rooting through my mods one by one would solve it, but simply using the connector with bewitchment yields a crash.

**Comment by Su5eD** [comment]
Duplicate of #1164
