### ISSUE TITLE
Incompatibility with Simple Animated Guns on 1.20.1

### ISSUE THREAD

**Issue by FranzFischer78** [Sinytra/Connector#1280]
### Mod Name

Simple Animated Guns

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/fabric-simple-animated-guns

### Minecraft version

1.20.1

### Describe the bug

The game pretty much instantly crashes with exit code 1 when launching it. 

### Steps to reproduce

The game crashes instantly on mod loading

The following mods are used:
![grafik](https://github.com/user-attachments/assets/8c6656e0-7590-48b7-b452-e8d23a3b9958)

### Logs

https://gist.github.com/FranzFischer78/8d5922acf91e6b5659b79b2ddce26d2f

### Additional context

Simple Animated Guns uses Azurelib. I tried the forge and the fabric version of Azurelib but got the exact same issue.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
