### ISSUE TITLE
1.20.1 forge version 47.3.0 and 14 fabric mods. Crash

### ISSUE THREAD

**Issue by RxniR** [Sinytra/Connector#1283]
### Mod Name

BClib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bclib

### Minecraft version

1.20.1

### Describe the bug

I started minecraft and it crashed 1 minute in.

### Steps to reproduce

1. CLick on play
2.wait for a minute
3.crash
...

### Logs

https://gist.github.com/RxniR/427f2f94fdc7d7ebbb1518b14a3720a0

### Additional context

I have 269 Mods and 27 datapacks. i am pretty sure that quark is a part of this issue

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
