### ISSUE TITLE
Adding Pick your Poison crashes apon startup

### ISSUE THREAD

**Issue by Specimen-420** [Sinytra/Connector#1284]
### Mod Name

Pick Your Poison

### Mod Homepage

https://modrinth.com/mod/pick-your-poison

### Minecraft version

1.20.1

### Describe the bug

Adding Pick your Poison crashes apon startup

### Steps to reproduce

1. Add pick your poison to the mods list
2. start the instance
3. crash
...

### Logs

https://mclo.gs/P5NsDTC

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
