### ISSUE TITLE
Better MC 4 Server Crash on Startup

### ISSUE THREAD

**Issue by Setting4988** [Sinytra/Connector#1286]
### Mod Name

Better Minecraft 4

### Mod Homepage

https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4

### Minecraft version

1.20.1

### Describe the bug

Server crashed and now crashed on startup.

### Steps to reproduce

1. Start server on Ubuntu
2. 60 seconds pass and the server crashes. Unable to understand crash log.

### Logs

https://pastebin.com/SUNyUwV0

### Additional context

I'm unable to see if this is a connector issue as I'm not very good at reading crash logs. I'm running this server on Ubuntu. The crash logs says "Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker."

**Comment by Su5eD** [comment]
> java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)

Doesn't look like us, try asking in the modpack's discord server
