### ISSUE TITLE
C2ME crashes with Canary

### ISSUE THREAD

**Issue by BoardAnims** [Sinytra/Connector#1289]
### Mod Name

Canary & Concurrent Chunk Management Engine

### Mod Homepage

https://modrinth.com/mod/canary & https://modrinth.com/mod/c2me-fabric

### Minecraft version

1.20.1

### Describe the bug

Game crashes on startup

### Steps to reproduce

1. Make a Forge Instance
2. Install Sinytra Connector (and it's dependencies), Canary and C2ME
3. Launch Minecraft

### Logs

https://gist.github.com/BoardAnims/c65bd5e34566300a1d2d45112fe40d4f

### Additional context

Someone else made this an issue in Canary's repository [#231](https://github.com/AbdElAziz333/Canary/issues/231).

I can confirm that [Radium](https://modrinth.com/mod/radium) does not crash the game. (Nor does it crash on a Fabric instance using [Lithium](https://modrinth.com/mod/lithium))

**Comment by Su5eD** [comment]
As the linked issue states, the crash is a result of a mixin redirect conflict, therefore this cannot be solved on our side.

**Comment by Tapacywka** [comment]
You can use Radium instead of Canary, it's a Lithium fork too, but works pretty well with c2me.
