### ISSUE TITLE
Blue obsidian in  betternether mod can't be poured in regular form

### ISSUE THREAD

**Issue by 7yudinglaopin8** [Sinytra/Connector#1290]
### Minecraft version

1.20.1

### Describe the bug

Blue obsidian can't be poured in regular form

### Steps to reproduce

I'm pouring blue obsidian, but I'm only pouring regular obsidian.  
![3](https://github.com/user-attachments/assets/07ba5b10-a97e-4886-a497-8640cd06917c)
![blueobsidian](https://github.com/user-attachments/assets/43320eab-f87a-4298-bc39-ec25bfef8203)
![1](https://github.com/user-attachments/assets/702313e4-4eb7-4a24-9a5b-9a7805d69884)
![2](https://github.com/user-attachments/assets/5a4a30c3-43cc-4475-99be-1c9d9fe4d58a)

**Comment by 7yudinglaopin8** [comment]
Installing Betternether separately also has this problem.

**Comment by 7yudinglaopin8** [comment]
It seems that interactions between blocks modified by the fabric mod cannot be read.

**Comment by 7yudinglaopin8** [comment]
I want to play this mod on 1.21. but (Unable to Transform betternether）（issue#1338）

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
