### ISSUE TITLE
[1.20.1] Biolith: MultiNoiseBiomeSource crash still occurs on latest version

### ISSUE THREAD

**Issue by Reshy** [Sinytra/Connector#1291]
### Mod Name

Biolith and any MCCreator mod

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/biolith/

### Minecraft version

1.20.1

### Describe the bug

The two mods cause a conflict upon world generation causing a hang into crash.

### Steps to reproduce

1.  Install Biolith
2.  Install MCcreator mod
3.  Load game
4.  Generate world
5. Crash!

### Logs

https://pastebin.com/T9hSmQfn https://pastebin.com/kd5xYf5X

### Additional context

This bug was mentioned to be fixed in #857 but the fix does not function.

**Comment by Su5eD** [comment]
Please specify which mods need to be installed.

**Comment by Reshy** [comment]
Crash:  https://pastebin.com/dZaBsTVy
Log:  https://pastebin.com/mtc4tiGN

Mod List:  
![image](https://github.com/user-attachments/assets/97e4c581-2dbb-4927-8452-521af284032e)

**Comment by Su5eD** [comment]
Ah, I see, Yes, the mod does indeed do the same thing as Dungeons Content. Unfortunately, this is out of our control. I recommend talking to the mod's author instead. This kind of forceful replacement looks like a bad practice, it's probably better to use a library like Biome Squisher, Biolith or Terrablender as the other mods do.

![replacement](https://github.com/user-attachments/assets/907a263c-44f3-4839-8a0e-2e6ad64f5a01)

**Comment by Reshy** [comment]
Happens with MCcreator mods, I dunno how much they can really change within that program.  Is there no way to make a handler for MCcreator mods since they all seem to have the exact same problem?

![image](https://github.com/user-attachments/assets/84d72201-45e6-497d-84db-c42a70964f96)
https://pastebin.com/FwpTHrq5

![image](https://github.com/user-attachments/assets/df0a0bcb-0787-4ce4-9e77-6b48b2cf01db)
https://pastebin.com/av9N3nMe

**Comment by WitherTM** [comment]
> Happens with MCcreator mods, I dunno how much they can really change within that program. Is there no way to make a handler for MCcreator mods since they all seem to have the exact same problem?
> 
> ![image](https://private-user-images.githubusercontent.com/2096384/356764183-84d72201-45e6-497d-84db-c42a70964f96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDIyMjQsIm5iZiI6MTcyMzI0MTkyNCwicGF0aCI6Ii8yMDk2Mzg0LzM1Njc2NDE4My04NGQ3MjIwMS00NWU2LTQ5N2QtODRkYi1jNDJhNzA5NjRmOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMjIxODQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQxZDU2N2EzYTQ2ZWU3ODE3MjY5NWRhOWZjZDAzOTg2M2Q4ZTIwOTFlMThlOGMwNGZiYTA1MzVlYTEyMzRmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aZqcpGRvX3BPzt2h7BFiOFjitVnEbj3RSWiaFC73fi0) https://pastebin.com/FwpTHrq5
> 
> ![image](https://private-user-images.githubusercontent.com/2096384/356764203-df0a0bcb-0787-4ce4-9e77-6b48b2cf01db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDIyMjQsIm5iZiI6MTcyMzI0MTkyNCwicGF0aCI6Ii8yMDk2Mzg0LzM1Njc2NDIwMy1kZjBhMGJjYi0wNzg3LTRjZTQtOWU3Ny02YjQ4YjJjZjAxZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMjIxODQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxMTA3M2ZlNjc4ZDAxY2Q3YWY2N2ZlMzliZDhhZGY4ZDBkZjgxOWFjYjU1ZWMwNWVjOWJjODUyZjhlNDg4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eG0FwL9q-uUYcv1V7tXJOhyRIiYKfKjJEvUG3Ko6_ro) https://pastebin.com/av9N3nMe

or just don't use MCreator mods?

**Comment by Reshy** [comment]
I mean sure?  That's like saying during a bug report "just don't use the mod that crashes lol", yet we report bugs and incompatibilities anyway.
