### ISSUE TITLE
C2ME crash

### ISSUE THREAD

**Issue by kakashi1464** [Sinytra/Connector#1297]
### Mod Name

Concurrent Chunk Management Engine

### Mod Homepage

https://modrinth.com/mod/c2me-fabric

### Minecraft version

1.21.1

### Describe the bug

C2ME causes crash after opening any tab in settings tab

### Steps to reproduce

1. Install C2ME, Connector, FFAPI
2. Open game
3. While in the main menu, open the settings tab
4. Click on any tab

### Logs

[latest.log](https://mclo.gs/ICDLJra)
[crash-report](https://mclo.gs/Za8niXI)
[debug.log](https://mclo.gs/ZjigqOw)

### Additional context

Doesn't crash if you open a tab while in the world

**Comment by Su5eD** [comment]
Fixed in [Forgified Fabric API 0.101.2+2.0.10+1.21](https://modrinth.com/mod/forgified-fabric-api/version/0.101.2+2.0.10+1.21)
