### ISSUE TITLE
betterx and artifacts are incompatible

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#1298]
### Mod Name

BetterNether, Artifacts

### Mod Homepage

https://modrinth.com/mod/betternether , https://modrinth.com/mod/betterend , https://modrinth.com/mod/artifacts

### Minecraft version

1.21.1

### Describe the bug

crash on startup

### Steps to reproduce

1.install artifacts and betternether or end
2.crash

### Logs

https://gist.github.com/xg787/3776070ac4bba4d47ebf98af65de32dc

**Comment by WitherTM** [comment]
Better X works, it just requires [World Weaver](https://modrinth.com/mod/worldweaver/version/21.0.12) now

**Comment by xg787** [comment]
world weaver is installed
