### ISSUE TITLE
The Darkened Storm mod prevents world creation 

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#1299]
### Mod Name

The Darkened Storm Mod

### Mod Homepage

https://cdn.discordapp.com/attachments/1125876556393365528/1270754570062008422/ultimatesword-1.0.0.jar?ex=66b62b6a&is=66b4d9ea&hm=6fff779613e7ba7822f1863451ffaf434d9d552cab97dfd78b6dc14cc335a3eb&

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When attempting to create world with the mod on it would be stuck on the create world screen

### Steps to reproduce

1. Install the Darkened Storm Mod with Connector Beta 44 and Forgified Fabric API 0.92.2+1.11.8+1.20.1
2. Create a new world
3. The game will be stuck on the Create World Screen
...

### Logs

I don't have a crash log 

### Additional context

Can you see if you can replicate this issue 
Note: The ultimatesword file is the Darkened Storm mod
When Removing the mod, the world seems to created

**Comment by WitherTM** [comment]
have you tried with beta 45?

**Comment by RoomAlex68** [comment]
Yes and still tries to attempting to create a world but it's stuck on the creating world screen unless you remove the mod

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
