### ISSUE TITLE
Replay mod replay does not open up

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1300]
### Mod Name

ReplayMod

### Mod Homepage

https://www.replaymod.com

### Minecraft version

1.20.1 (LTS)

### Describe the bug

client crashes when loading a replaymod replay.

### Steps to reproduce

1. Go into replays in replayMod, **not** a singleplayer world.
2. click on one of them

### Logs

https://gist.github.com/vinnyg0621/5396ac7d9d3cc443d176e149ffbcc27d

### Additional context

even after installing ffmpeg is does this!

**Comment by Su5eD** [comment]
Duplicate of #556
