### ISSUE TITLE
CRASH WITH REPLAY MOD 1.21

### ISSUE THREAD

**Issue by TheVirusNVGM** [Sinytra/Connector#1305]
### Mod Name

replaymod

### Mod Homepage

https://modrinth.com/mod/replaymod

### Minecraft version

1.21.1

### Describe the bug

not compatible with SC version 1.21

### Logs

https://gist.github.com/TheVirusNVGM/210739384403c111385d5f25d01c9ed6

```[tasklist]
### Tasks
```

**Comment by Su5eD** [comment]
Duplicate of #556
