### ISSUE TITLE
Better Nether Incompatibility

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Sinytra/Connector#131]
### Mod Name

BetterNether

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betternether/files

### Describe the bug

The biomes and structures this adds to the nether are not present

### Steps to reproduce

1. Go to the nether
2. Search nether. No biomes from mod and almost all structures are gone.

### Logs

https://gist.githubusercontent.com/ChrisLTheNerd/07cbeaee9b73361c35ce39070db7dfb1/raw/b0b50d55a03f0c2e914eecaacb12327ca2fe6e9e/debug-5.log

### Additional context

Mobs and a structure named the Nether City are still spawning. All items and blocks can still be used and placed. Biomes that where generated using normal fabric do stay along with the colored fog and still appear in "Biomes:" in F3.

**Comment by Su5eD** [comment]
Can you try again using the [dev build](https://github.com/Sinytra/Connector/suites/15535889511/artifacts/886706861)? I recently pushed a fix for better end that should help betternether as well.

**Comment by ChrisLTheNerd** [comment]
Good news! It worked! :D

**Comment by Su5eD** [comment]
Cool, I'll close this as resolved then. The new release should arrive in the next couple days.
