### ISSUE TITLE
How to make more than one mod in Hiddenmods in config

### ISSUE THREAD

**Issue by ikkera0** [Sinytra/Connector#1310]
### Mod Name

l

### Mod Homepage

l

### Minecraft version

1.20.1 (LTS)

### Describe the bug

l

### Steps to reproduce

1.
2.
3.
...
![notepad_J1QaDWWPPB](https://github.com/user-attachments/assets/bab8a785-6272-4366-be7c-b8b8c2d0314a)

### Additional context

l

**Comment by Su5eD** [comment]
Yes, that looks correct.

**Comment by ikkera0** [comment]
It doesn't work the game is crashing
