### ISSUE TITLE
Crash with minecell 1.8.3 - minecraft 1.20.1

### ISSUE THREAD

**Issue by PlaIsMe** [Sinytra/Connector#1311]
### Mod Name

Minecells

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/minecells

### Minecraft version

1.21.1

### Describe the bug

Crashes with latest minecells 

### Steps to reproduce

Crashes on startup

### Logs
crash-reports:
https://pastebin.com/zSkCDXhd

latest log:
https://pastebin.com/Q5edDPfY

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
