### ISSUE TITLE
Mod shows missing fabric-api

### ISSUE THREAD

**Issue by Markoiv2C08** [Sinytra/Connector#1312]
### Minecraft version

1.20.1

### Describe the bug

After I installed the mod and the fabric mods, The game shows that its missing fabric-api, even that I installed the forgified farbic-api its still not working, I've tried to put normal fabric-api, it still doenst work. Im using Particualr mod (the one on modrinth). (first time i open i use the forgified farbic api, second time i use normal fabric api)

### Steps to reproduce

1.Installed the connector ,forgified fabric-api and fabric mods
2.open the game
3.bug triggered
...

https://github.com/user-attachments/assets/f3ce283f-9ea3-4ddd-bae8-55813cd3f5ec

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by Lolothepro** [comment]
Buy Minecraft

**Comment by Su5eD** [comment]
Custom server APIs (such as Mohist, Magma, Arclight) are not supported. This also applies to launchers for mobile platforms (Pojav, FoldCraft) and pirated launchers.

Such platforms provide unpredictable environments in which mods might not function as expected, and therefore we can't provide support for them. Ensuring mod compatibility is the platform's duty, just like Connector tries its best to achieve parity when running Fabric mods on Forge.

This is explained in our [FAQ](https://github.com/Sinytra/Connector/discussions/689).
