### ISSUE TITLE
Unable to configure Enhanced Block Entities via NeoForge's "Mods" menu

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#1318]
### Mod Name

Enhanced Block Entities

### Mod Homepage

https://github.com/FoundationGames/EnhancedBlockEntities

### Minecraft version

1.21.1

### Describe the bug

Unable to configure Enhanced Block Entities via NeoForge's "Mods" menu

### Logs

https://mclo.gs/8nHXdJM

### Additional context

[latest.log](https://github.com/user-attachments/files/16573158/latest.log)

**Comment by Su5eD** [comment]
Do you have Connector Extras installed?

**Comment by Lolothepro** [comment]
> Do you have Connector Extras installed?

Oh, I forgot to install it.
