### ISSUE TITLE
1.21 Pickaxe, Axe, and Shear harvesting are gone when Sinytra Connector and Dramatic Doors are present

### ISSUE THREAD

**Issue by Inonedn** [Sinytra/Connector#1321]
### Minecraft version

1.21.1

### Describe the bug

Harvesting Pickaxe, Axe, and Shears are all impossible when the mod is present

### Steps to reproduce

N/A

### Logs

https://pastebin.com/MyyPqD35

**Comment by Su5eD** [comment]
Please provide reproduction steps as described in the issue template

**Comment by Inonedn** [comment]
This bug has no known reproduction steps, as whenever I remove or add mods, it doesn't seem to work

**Comment by Inonedn** [comment]
I found the issue, it seems to be Dramatic Doors when added with Sinytra Connector

**Comment by ghost** [comment]
is this gonna be fixed?

**Comment by Su5eD** [comment]
Moving to #1389 which provides a better description of the issue
