### ISSUE TITLE
Player Statistics produces exceptions on queries when Kotlin For Forge is present

### ISSUE THREAD

**Issue by virtualonno** [Sinytra/Connector#1323]
### Mod Name

Player Statistics

### Mod Homepage

https://modrinth.com/mod/playerstatistics

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When using Player Statistics (and its Fabric Language Kotlin & SQLite JDBC dependencies) through Connector, if Kotlin For Forge is also installed, that takes precedence over Fabric Language Kotlin, producing an exception whenever a Player Statistics database query is invoked. Without KFF present, the mod functions normally.

### Steps to reproduce

Use any query command, e.g. `/stats top` of Player Statistics whilst having Kotlin For Forge installed. 

### Logs

https://gist.github.com/virtualonno/2f32a77bd2e36d77d9e199ec9e66eeb8

### Additional context

I have already attempted to hide KFF's presence in the Connector config, to no avail.
The mod only functions in a dedicated server environment (ergo, not singleplayer).

**Comment by virtualonno** [comment]
I've also tried to replicate this on 1.21 (and 1.21.1) but here, Fabric Language Kotlin does not seem to load with Connector at all and crashes early into startup. This is solely with Connector, FFAPI, and Fabric Language Kotlin: https://gist.github.com/virtualonno/901bdee5ab44ec8ac9236c50493ec764

(Including KFF in addition resulted in the same crash; my bad on closing the issue, my finger slipped)

**Comment by sisby-folk** [comment]
Also experiencing issues related to FLK not loading on connector (in my case, [teabridge](https://modrinth.com/mod/teabridge)) - the dependent mods also seem to not load, and silently, which is odd.

**Comment by sisby-folk** [comment]
(Going to be annoying and @Su5eD because i'm unsure how to get this moved out of the triage done column)

**Comment by Su5eD** [comment]
> the dependent mods also seem to not load, and silently, which is odd.

Could it be https://github.com/FabricMC/fabric-loader/issues/868? It affects our forge port as well, since the dependency resolver code remains unchanged.

**Comment by sisby-folk** [comment]
unsure! in this case I was explicitly adding both teabridge and flk to the mods folder

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
