### ISSUE TITLE
Verticality mod displays GUI incorrectly

### ISSUE THREAD

**Issue by efficient-efi** [Sinytra/Connector#1325]
### Mod Name

Verticality

### Mod Homepage

https://modrinth.com/mod/verticality

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Health bar not moving

### Steps to reproduce

1.Enter a world
2.Press esc and set the GUI placement as these (these screecshots were taken in fabric loader)
![image](https://github.com/user-attachments/assets/adf2c5be-3e9c-4e42-a822-52e2053aa859)
![image](https://github.com/user-attachments/assets/e4f04b84-1e9f-42c8-9476-9a9b0190983c)
![image](https://github.com/user-attachments/assets/c96e2e85-88d5-4813-9d55-dd367f855bf0)
3.The Health bar does not move when it should and does not disappear when it should
![2024-08-13_12 50 38](https://github.com/user-attachments/assets/e07ed727-1487-4acb-83fe-6ca8cdb7de87)
![2024-08-13_12 50 59](https://github.com/user-attachments/assets/39897322-7599-4112-b905-abc638efba66)
![2024-08-13_12 51 17](https://github.com/user-attachments/assets/3ee8e9b4-a572-486f-a907-8d135e3fd462)
![2024-08-13_12 51 31](https://github.com/user-attachments/assets/ab413379-bab3-46f8-a9dc-dc99133dda15)
...

### Logs

https://gist.github.com/efficient-efi/70c6e51b26efebfa432a052d20796b75

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
