### ISSUE TITLE
[1.20.1] BetterEnd-BetterNether-Textures of elytra are not visible

### ISSUE THREAD

**Issue by TeQTabanca** [Sinytra/Connector#1326]
### Mod Name

better-end-4.0.11-fabric | better-nether-9.0.10-fabric

### Mod Homepage

https://modrinth.com/mod/betterend/version/4.0.11 | https://modrinth.com/mod/betternether/version/9.0.10

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Textures of elytra are not visible

### Steps to reproduce

1.Add mods to the server
2.Start the server
3.Enter the game and take one of the elytras offered by the mods and wear it.
...

### Logs

There is no log because there is a texture problem.

### Additional context

![BetterEnd-BetterNether-Textures of elytra are not visible](https://github.com/user-attachments/assets/1756f4ee-a605-4e47-bd05-3a1a920f3a84)

_No response_

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by TeQTabanca** [comment]
> As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Connector-1.0.0-beta.45+1.20.1 | Connector-ConnectorExtras-1.11.2+1.20.1 | Connector-fabric-api-0.92.2+1.11.8+1.20.1**

All are up to date anyway.
