### ISSUE TITLE
[1.20.1] Critical injection failure: @Inject annotation on onRenderBackground could not find any targets matching

### ISSUE THREAD

**Issue by TeQTabanca** [Sinytra/Connector#1327]
### Mod Name

smoothgui-0.1.0.jar

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/smooth-gui

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Client gives error while loading

### Steps to reproduce

1.Install the mod and run the game

### Logs

https://gist.github.com/TeQTabanca/39975c9d6ab35922aa6f8c52cd74f0c4

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
