### ISSUE TITLE
Windows Defender Quarantining Connector

### ISSUE THREAD

**Issue by myah-mitchell** [Sinytra/Connector#1329]
### Minecraft version

1.20.1

### Describe the bug

Mod flagged as Trojan:Script/Wacatac.B!ml

### Steps to reproduce

1. Install mod via Modrinth
2. Windows Defender may flag JAR and quarantine file.

### Additional context

![Screenshot 2024-08-13 204436](https://github.com/user-attachments/assets/89323dda-55d4-48e8-988a-873bacbedca6)

Version: 1.0.0-beta.45+1.20.1

This only started happening today, I was fine on Sunday when I played MC.

**Comment by myah-mitchell** [comment]
SHA-256 of my file, which was a new download via Modrinth: 82f095b316712587b1fda476c11ec27c1bf663d64c7dfd8ecb5337d8c24ddd14

I'm running Security intelligence version 1.417.101.0 which was created on 8/13/2024 11:07am (I assume this is CDT, but idk).

VirusTotal still shows all clean: https://www.virustotal.com/gui/file/82f095b316712587b1fda476c11ec27c1bf663d64c7dfd8ecb5337d8c24ddd14?nocache=1

To be clear, I don't think the file is infected or malicious, but other users might be getting a false alert as well once they get the virus definition from today.

**Comment by Su5eD** [comment]
This is a false positive. Windows defender is knows to occasionally flag minecraft mods, though as long as the download isn't corrupt, it should be fine.
