### ISSUE TITLE
Incompatibility with Milkevs Essentials

### ISSUE THREAD

**Issue by aking4125** [Sinytra/Connector#133]
### Mod Name

Milkevs Essentials

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/milkevs-essentials

### Describe the bug

Client crashes upon startup

### Steps to reproduce

1. Setup Connector and Forgified Fabric API
2. Install Milkevs Essentials, Trinkets and Cloth Config API (Yes the fabric versions since the mod is still calling for them)
3. Launch and it crashes.

Disabling Milkev Essentials causes the game to load. With both Trinkets and Cloth Config API (Fabirc) still present. 

### Logs

Debug.log: https://pastebin.com/pHNqt3As
Prism Launcher Log: https://pastebin.com/6cd35zpk

### Additional context

https://github.com/milkev/Milkevs-Essentials/issues/5

**Comment by milkev** [comment]
Seems to be due to Sinytra being incompatable with Reach Entity Attributes
https://github.com/Sinytra/Connector/discussions/12#:~:text=Reach%20Entity%20Attributes,Forge%20attribute%20modifiers

Is there any way to have entity attributes work through Sinytra?

**Comment by milkev** [comment]
AttributeFix doesnt do anything to the attributes of reach, so it should not effect this situation

**Comment by Su5eD** [comment]
This has now been fixed via [Connector Extras](https://github.com/Sinytra/ConnectorExtras), which bundles a Forge port of Reach Entity Attributes. Install [Connector Extras](https://legacy.curseforge.com/minecraft/mc-mods/connector-extras) alongside Connector and the mod will work.
