### ISSUE TITLE
it's a question, how to hide the libraries from the mods menu?

### ISSUE THREAD

**Issue by Surepart** [Sinytra/Connector#1330]
the tile is already explain

**Comment by Tapacywka** [comment]
You can't do this right neither from regular NeoForge mods list or even using Catalogue for NeoForge.
This feature is only available for original Fabric ModMenu.

**Comment by Su5eD** [comment]
Which libraries do you mean?

**Comment by ForestWolf99** [comment]
Someone ported Mod Menu to forge and neoforge. You can use this to hide libraries.

https://modrinth.com/mod/better-modlist
