### ISSUE TITLE
[1.20.1] Crash caused by Rubidum when loading into main menu

### ISSUE THREAD

**Issue by Td-Flyy** [Sinytra/Connector#1332]
### Mod Name

Rubidium

### Mod Homepage

https://modrinth.com/mod/rubidium

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When first starting up the game, it loads for a couple seconds, then crashes and sends me back to the launcher

### Steps to reproduce

1. Make sure all mods are for 1.20.1, install NeoForge for 1.20.1
2. Put the S. Connector, Oculus, and Rubidium into the mods folder
3. Launch Minecraft

### Logs

https://gist.github.com/Td-Flyy/fa9086fb3ee5ce6ae0bcff3a2afea17d#file-gistfile1-txt

### Additional context

Works just fine with oculus, as soon as I put rubidium in there, it crashes.

**Comment by liangmoe** [comment]
Dude.. the crash didnt even related to connector, if you remove all of the connector relate mods you will know that

**Comment by kakashi1464** [comment]
Oculus is incompatible with rubidium, use embeddium instead. This issue is not Connector related, as liangmoe said
