### ISSUE TITLE
Minor mod conflict with Terrestria mod

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#1334]
### Mod Name

Terrestria

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/terrestria

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Cannot create a new world if Luminous: Nether is installed.

### Steps to reproduce

1. Download [LUMINOUS: NETHER](https://www.curseforge.com/minecraft/mc-mods/luminous-nether) + dep
2. Download [Terrestria](https://www.curseforge.com/minecraft/mc-mods/terrestria/relations/dependencies)
3. Attempt to make a new world. It will try to load it, then crash.

### Logs

https://gist.github.com/Cixon/d0a7ede406ee4b9db027b8693613a760

### Additional context

here's a hint:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.m_203565_(net.minecraft.resources.ResourceKey)" because the return value of "net.minecraft.world.level.biome.MultiNoiseBiomeSource.biolith$getDimensionType()" is null
```

it's terrestria's biolith engine thingy...

source:
https://github.com/TerraformersMC/Terrestria/tree/1.20

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
