### ISSUE TITLE
Unable to Transform betternether

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#1338]
### Mod Name

BetterNether

### Mod Homepage

https://modrinth.com/mod/betternether

### Minecraft version

1.21.1

### Describe the bug

Unable to Transform betternether

### Steps to reproduce

1.load better nether and dependencies 
2.crash

### Logs

https://gist.github.com/xg787/d599a24780f09c769824a790827d70a7

### Additional context

![sad](https://github.com/user-attachments/assets/893ec6f5-8d45-4b10-af59-8954cf8edb76)

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
