### ISSUE TITLE
Incompatibility with Rubidium

### ISSUE THREAD

**Issue by aking4125** [Sinytra/Connector#134]
### Mod Name

Rubidium

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/rubidium

### Describe the bug

Crash upon startup

### Steps to reproduce

1. Install this mod and Forgied Fabric API
2. Install Rubidium
3. Crash

### Logs

Debug log: https://pastebin.com/YnQrNa0F Prism Log: https://pastebin.com/RaksHnX8

**Comment by Fiz-Victor** [comment]
The mod `supplementaries` requires `moonlight`, and rubidium is fully compatible with connector

**Comment by coco875** [comment]
in your log you have multiple mod I don't know so much prism one with a cross is disable or not ?

**Comment by coco875** [comment]
(and you don't use the lastest version of rubidium)

**Comment by aking4125** [comment]
Copy. 

We used 0.6.5 because Oculus doesn't work correctly with 0.7.0a of Rubidium

**Comment by aking4125** [comment]
> 

All of them with the X are disabled saved for those with the check mark.
