### ISSUE TITLE
Can not run with Carpet

### ISSUE THREAD

**Issue by zlink2010** [Sinytra/Connector#1344]
### Mod Name

Carpet

### Mod Homepage

https://modrinth.com/mod/carpet

### Minecraft version

1.21.1

### Describe the bug

The farbic loader:The mod "carpet" Injection Failed

### Logs

https://gist.github.com/zlink2010/6a88cf7d7be6323521da4e4fd0feb7c9

**Comment by Su5eD** [comment]
Duplicate of #296
