### ISSUE TITLE
1.21.1 | Architectury API Incapable of loading

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#1348]
### Mod Name

Architectury API  ( Fabric Version )

### Mod Homepage

https://modrinth.com/mod/architectury-api/version/13.0.6+fabric

### Minecraft version

1.21.1

### Describe the bug

Start-up crash. Incompatible with connector.

### Steps to reproduce

1. Download Fabric Architectury API.
2. Download Connector 2.0.0-beta.2 (full) + dep.
3. Attempt launch.

![2024-08-19 22_33_37-Greenshot](https://github.com/user-attachments/assets/9b0bdc2e-18b7-4da6-8fdc-2cdbf76d80d8)

### Logs

https://gist.github.com/Cixon/8c5dba5b9f84b2af6534fb03c638068c

**Comment by home-gihub** [comment]
isn't there a neoforged version you can use ❓

**Comment by Cixon** [comment]
> isn't there a neoforged version you can use ❓

true but there are fabric mods that rely on the fabric version.

**Comment by Su5eD** [comment]
Have you tried using the neoforge version to confirm the fabric version is necessary? AFAIK architectury should work fine even without connector extras installed

**Comment by Tenta-dev** [comment]
Up, same error here
![Image](https://github.com/user-attachments/assets/63f3e2ad-4bd2-463d-9216-f6b64e7f68e9)
