### ISSUE TITLE
LegendarySurvivalOverhaul/SinytraConnector break Curio Custom Validation

### ISSUE THREAD

**Issue by wsxiya** [Sinytra/Connector#1349]
### Minecraft version

1.20.1

### Describe the bug

I have a package with nearly 100 mods. I found that the hat cannot be worn in the accessories column. The minimum number of mods that cause the problem is listed below. When you delete Connector-1.0.0-beta.45+1.20.1 or legendarysurvivaloverhaul-1.20.1-1.3.9, the hat can be worn in the accessories column. Note that the game has not crashed.

### Steps to reproduce

https://github.com/fonnymunkey/SimpleHats/issues/82

### Additional context

![1$B52SAGQ_5)Y3XN2X$R0PF](https://github.com/user-attachments/assets/9a120551-c3ce-42ec-a6d4-1d9550ead6a6)
![625ITP0 4 QJ763@020457Q](https://github.com/user-attachments/assets/449e35ad-b038-4934-a26c-8fc9b343e674)

**Comment by fonnymunkey** [comment]
I would recommend re-opening this issue, from reports it is still a bug in latest versions.
