### ISSUE TITLE
Origins Mixing issue 1.21.1

### ISSUE THREAD

**Issue by linaraincalzando** [Sinytra/Connector#1351]
### Mod Name

Origins

### Mod Homepage

https://modrinth.com/mod/origins

### Minecraft version

1.21.1

### Describe the bug

Mixin error

### Steps to reproduce

1.Add origins and sinytra connector with connector extras
2. Load minecraft
3. Get mixin error
...

### Logs

https://paste.atlauncher.com/view/24c9fb84-ffb0-4cfe-b2e4-a3e3b5cf90df

**Comment by Su5eD** [comment]
Duplicate of #890

**Comment by linaraincalzando** [comment]
Sorry, I didn't consider it as a duplicate because its on 1.21.1. Neoforge and Minecraft itself had coding changes that were large enough that the solutions might be different.
