### ISSUE TITLE
unable to transform wilder wilds / frozen lib

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#1352]
### Mod Name

wilder wilds / frozen lib

### Mod Homepage

https://modrinth.com/mod/wilder-wild

### Minecraft version

1.21.1

### Describe the bug

crash on startup

### Steps to reproduce

1.load wilder wilds
2.crash

### Logs

https://gist.github.com/xg787/ba3b085a6a1a644479de8746fd833d76

### Additional context

![cheese](https://github.com/user-attachments/assets/1bb2d5b6-a248-4178-83a0-46e1d04edbbe)

**Comment by Su5eD** [comment]
Duplicate of #1055
