### ISSUE TITLE
[1.21.1] Crash on game launch with the Flashback mod.

### ISSUE THREAD

**Issue by VOLKOUL** [Sinytra/Connector#1353]
### Mod Name

Flashback

### Mod Homepage

https://modrinth.com/mod/flashback

### Minecraft version

1.21.1

### Describe the bug

Crash on game launch.

### Steps to reproduce

Install Connector, Connector Extras, FFAPI.
Install Flashback.
Launch game.

### Logs

Log: https://mclo.gs/fZ1yv8I Crash Report: https://mclo.gs/zGOFZNg

### Additional context

Flashback is a new in-game editor, video and sound recorder for Minecraft.

**Comment by MagicalAlexey** [comment]
The Flashback starts, but there is a conflict with player_variables_sync in replays

**Comment by VOLKOUL** [comment]
Latest Flashback version launches normally, but crashes as soon as you enter a replay.

**Comment by Tapacywka** [comment]
You need to report this issue to the Flashback mod developers.

**Comment by VOLKOUL** [comment]
Crash was caused by an incompatibility with NostalgicTweaks. Flashback appears to be working without any issues.
