### ISSUE TITLE
Incompatible with ChatPlus

### ISSUE THREAD

**Issue by Aroshold** [Sinytra/Connector#1357]
### Mod Name

Chat Plus

### Mod Homepage

https://github.com/ebicep/ChatPlus

### Minecraft version

1.20.1 (LTS)

### Describe the bug

game crashes at the early load without crash report

### Steps to reproduce

1. Install connector and chatplus
2. launch the game

### Logs

Logs stop updating before early game load, no crash reports

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
