### ISSUE TITLE
china edition failed to launch with Sinytra Connector installed

### ISSUE THREAD

**Issue by BredyAK** [Sinytra/Connector#1361]
### Minecraft version

1.20.1

### Describe the bug

china edition failed to launch with Sinytra Connector installed

### Steps to reproduce

1. install Sinytra Connector and Forgified Fabric API in china edition's `mods` folder, then start the game
2. launch the game
3. game failed to launch

### Logs

https://gist.github.com/AvaloriaSinytra/c3675a179b173a1e275d8c7a497923c8

### Additional context

hi there, i'm a Minecraft China Edition player and i find the client will fail to launch if i install Sinytra Connector. currently most players in china are playing with China Edition ([https://minecraft.wiki/w/China_Edition](https://minecraft.wiki/w/China_Edition)). and it forces player to install a mod `netease_official-studio-1.20.jar` when player launch the game, and it is an official mod made by Netease. i can't find an official download link of the official mod (it is auto generated when player launch the game), so what i could do is to upload this jar.

btw, china edition uses a special fork of forge loader. so idk if it is caused by the chinese forge loader or the official mod.

i have upload my latest.log and debug.log. wish they could help you. i didn't find any other vaulable logs that contain crash reports or startup logs.

currently most of chinese players are playing china edition, so many chinese players are having this issue too. this mod is amazing! wish this issue could be reasonably solved.

**Comment by BredyAK** [comment]
[netease_official-studio-1.20.zip](https://github.com/user-attachments/files/16739672/netease_official-studio-1.20.zip)
this is the official mod, you should to unzip it to get the `.jar` file.

Netease does not provide an official way to download the mod, so what i could only do is to upload it manually.

**Comment by Su5eD** [comment]
Hi, the uploaded debug.log does not contain a crash stacktrace. Could you please try uploading a crash report instead?

**Comment by BredyAK** [comment]
> Hi, the uploaded debug.log does not contain a crash stacktrace. Could you please try uploading a crash report instead?

i've edited the title of this post, the game didn't crash, but failed to launch.

there is no crash reports or any other valuable logs, the game is just failed to launch and suddenly shut down.

btw, i could help you to test anytime, wish this issue could be fixed! thank you.

**Comment by wsxiya** [comment]
Terrible NetEase version. I'm Chinese and the Minecraft represented by NetEase in China is the worst version of Minecraft. I hope this mod will never support the NetEase version of Minecraft.

**Comment by wsxiya** [comment]
Terrible NetEase version, I'm Chinese, and the Minecraft represented by NetEase in China is the worst version of Minecraft. The mods of the Minecraft version represented by NetEase are all charged, and many Chinese studios plagiarize most of the popular modules of the Java version (and most of them are not authorized by the author). I hope this mod will never support the NetEase version of Minecraft.

**Comment by BredyAK** [comment]
> Terrible NetEase version, I'm Chinese, and the Minecraft represented by NetEase in China is the worst version of Minecraft. The mods of the Minecraft version represented by NetEase are all charged, and many Chinese studios plagiarize most of the popular modules of the Java version (and most of them are not authorized by the author). I hope this mod will never support the NetEase version of Minecraft.

stop causing hatred please. your are not saying the mod's issue itself, you are expressing your own hatred for the China Edition. you have no right to represent everyone. so please DO NOT post that on GitHub. this is a place we talk about coding issues.
