### ISSUE TITLE
after the initial loading screen minecraft crashes (there are no mods except connector and API)

### ISSUE THREAD

**Issue by bartok1** [Sinytra/Connector#1367]
### Minecraft version

1.20.1

### Describe the bug

after the initial loading screen minecraft crashes with exit code: 1

### Steps to reproduce

1. I'm launching the game
2. it's loading
3. it crashes at the loading stage of "launching minecraft"
...

### Logs

https://gist.github.com/bartok1/89eeaf3e5761164be312c9f2bbd62e45

### Additional context

I have forge version _**47.3.0**_ installed, but the latest available version _**47.3.7**_ has the same issue
I have Sinytra Connector version _**Connector-1.0.0-beta.45+1.20.1**_
I have Forgified Fabric API version _**fabric-api-0.92.2+1.11.8+1.20.1**_
These are the latest versions at the time of writing

This is ALL I have installed, nothing else

I use Tlauncher

**Comment by Su5eD** [comment]
> I use Tlauncher

please read our FAQ
