### ISSUE TITLE
Incompatibility with Invariable Paintings

### ISSUE THREAD

**Issue by Fokke456** [Sinytra/Connector#1370]
### Mod Name

Invariable Paintings

### Mod Homepage

https://modrinth.com/mod/invariable-paintings

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When launching the game with just Connector, Forgified Fabric API, and Invariable Paintings (both with and without Patched), the game crashes.

### Steps to reproduce

1. Add said mods to Minecraft forge 1.20.1 instance.
2. Try to run the game.
3. Crash.

### Logs

[Here](https://gist.github.com/Fokke456/495fbb7acf140ca39b6c4ee528452f48)

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
