### ISSUE TITLE
Connector 1.21.1+beta.2 is incompatible with Axiom 3.2.1

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [Sinytra/Connector#1373]
### Mod Name

Axiom

### Mod Homepage

https://modrinth.com/mod/axiom

### Minecraft version

1.21.1

### Describe the bug

The mod does not allow to run any Minecraft 1.21.1 instance loading both Connector and any of 1.21 build of Axiom throwing random errors on startup or missing `FabricShaderProgram`.

### Steps to reproduce

1. Get Axiom 3.2.1 and patch an MC version to `fabric.mod.json` to support 1.21.1 instead of 1.21. (or you can set `>1.21` if you wish) .
(NOTE: If you launch the Fabric instance of Axiom after this change, everything will work as expected and this change should not do any issues, because 1.21 and 1.21.1 are practically *almost the same*)
2. Get the Connector from the CurseForge/Modrinth page, at the moment of writing it is `2.0.0-beta.2+1.21.1`
3. Start the game and get the crash instantly with the error: `java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram`

### Logs

https://gist.github.com/DenisMasterHerobrine/fa111fc6eddd1f5e1ea2accd9c998bdb

### Additional context

Axiom: `3.2.1-for-MC1.21`
Sinytra Connector: `2.0.0-beta.2+1.21.1-full`
Forgified Fabric API: `0.102.0+2.0.12+1.21.1`

Let me know, if you need more info!

**Comment by Su5eD** [comment]
Moving this to #1414 since I already pinged the mod author in there. Sorry for not caching the duplicate earlier.
