### ISSUE TITLE
Spectrum & Create Incompatibility

### ISSUE THREAD

**Issue by rowanthemodder** [Sinytra/Connector#1379]
### Mod Name

Spectrum, Create

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/spectrum

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crashes to desktop immediately.

### Steps to reproduce

Reproduction is rather easy, just slap the mods inside the log into the mod folder, it's worth noting that you can make this mod combination boot if you disable create compatibility in spectrum's config as such:

```
	// Mod Integration Packs to not load (in case of mod compat errors)
	"IntegrationPacksToSkipLoading": [
		"create"
	]
```
The following log is produced when you do so: 
https://gist.github.com/rowanthemodder/b70473d3ccb42fdafe498e29d34e8319

### Crash Log

https://gist.github.com/rowanthemodder/8aa0ad35e16f4968a91fc8db128395ba

**Comment by ALEILGOD** [comment]
Open the file config for the Spectrum mod called spectrum.json5
Then find the option called IntegrationPacksToSkipLoading and in the brackets add create and it should work

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
