### ISSUE TITLE
Crash in feature placement stage with Better End

### ISSUE THREAD

**Issue by johalun** [Sinytra/Connector#1387]
### Mod Name

BetterEnd

### Mod Homepage

https://modrinth.com/mod/betterend

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Server crashes during terrain generation

### Steps to reproduce

1. Travel around the outer end islands until game crashes. If the bug is biome dependent, some exploring might be required to trigger the bug.

### Logs

https://pastebin.com/zCF3Ca7i

### Additional context

First error message in crash log
> java.lang.ClassCastException: class org.betterx.bclib.api.v2.levelgen.biomes.BCLBiome cannot be cast to class org.betterx.betterend.world.biome.cave.EndCaveBiome (org.betterx.bclib.api.v2.levelgen.biomes.BCLBiome is in module bclib@3.0.14 of loader 'TRANSFORMER' @510e6b93; org.betterx.betterend.world.biome.cave.EndCaveBiome is in module betterend@4.0.11 of loader 'TRANSFORMER' @510e6b93)

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
