### ISSUE TITLE
Crash with Epic Fight's Battle mode

### ISSUE THREAD

**Issue by slendercreeper1010** [Sinytra/Connector#1390]
### Mod Name

Epic Fight

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash then putting any armor piece on 

### Steps to reproduce

1. Enter the world
2. put any armor piece on
3. enter a battle mode (if it isn't on by default)
...
Crash

### Logs

https://pastebin.com/XegFAmrQ

### Additional context

Using Connector to play with BetterEnd and BetterNether

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
