### ISSUE TITLE
Antique Atlas reports Connector Not Available

### ISSUE THREAD

**Issue by NFGman** [Sinytra/Connector#1392]
### Mod Name

Antique Atlas 4

### Mod Homepage

https://modrinth.com/mod/antique-atlas-4

### Minecraft version

1.21.1

### Describe the bug

Connector is installed, but mod reports it's not

### Steps to reproduce

1. Add Antique Atlas and its dependencies (Connector, FFAPI) to mods folder 
2. Run server, get error
3.
...

### Logs

See Additional context

### Additional context

Similar to this Discord conversation: https://discord.com/channels/1141048834177388746/1281143111116128329/1281149382926012447

`net.neoforged.fml.ModLoadingException: Loading errors encountered:`
`        - Mod antique_atlas requires connector any`
`          Currently, connector is not installed`

`[main/ERROR] [loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:`
`        Mod ID: 'connector', Requested by: 'antique_atlas', Expected range: '*', Actual version: '[MISSING]'`
`[main/WARN] [service.ConnectorLoaderService/]: Broken FML mod files found, not adding Connector locator errors`

**Comment by kakashi1464** [comment]
antique atlas is a client side mod

**Comment by NFGman** [comment]
You are correct, I am inattentive.  Thank you.

**Comment by Kiryonn** [comment]
I get the issue for a single player instance

![Image](https://github.com/user-attachments/assets/fd2164ce-46a6-4d1b-8ad3-e29da367fc22)

![Image](https://github.com/user-attachments/assets/93192ab8-9b8d-4006-bf98-dc770f5bc5ee)

![Image](https://github.com/user-attachments/assets/98baedec-dcf9-4c74-8702-2ffce62a67fa)

**Comment by RougeJr** [comment]
I get the same issue
