### ISSUE TITLE
Mixins priority

### ISSUE THREAD

**Issue by srccc74** [Sinytra/Connector#1396]
### Minecraft version

1.20.1

### Describe the bug

Fabric mods doesn't respect mixins priorities.

### Steps to reproduce

I used Modern Industrialization and my custom mod for privates (Such as WorldGuard)
1. Create an Event Handler of _PlayerInteractEvent.LeftClickBlock_, add some logging info for example, cancel the event
2. Place any MI Barrel, and try to get items from it, using MouseLeftClick
### Additional context

I tried to conduct a deeper investigation of this issue, because the private system is critical on a public server - and if fabric mods ignore it, this leads to disastrous consequences

1. After trying to cancel Forge Event, I've tried to mixin in _ServerPlayerGameMode$handleBlockBreakAction_, with a priority 100000, logically, this should have prevented not only the forge event, but also the event factory, which is also initially a mixin. But this. But it didn't give any results.
2. After that, I've forked Modern Industrialization, and just added some info in code of Barrel Attack Block Event
The result, is really weird, fabric mixin runs before my mixin with priority 100000:
![image](https://github.com/user-attachments/assets/13d7363c-104a-44fd-80e5-197afcc672fe)
3. So next, in fork of Modern Industrialization i've tried to not use fabric event, and transfer all the event logic natively to a mixin inside the mod, and force set priority of that mixin to 1.
But the result is same, fabric mixin runs before my forge guard mixin, with priority 100000:
![image](https://github.com/user-attachments/assets/072f2535-c678-4745-835d-2ee04b532d9c)

Looks like all fabric mixins runs before forge mixins, fully ignoring priority system

**Comment by Su5eD** [comment]
Please show your mixin code. I believe the issue is simply an incorrect priority values. Higher priority in injections means you inject first, and lower priority injectors come afterwards. Therefore, the last injector to be applied will always end up being called first.

Try lowering your mixin's priority instead, or try asking for help in the mixin discord.
