### ISSUE TITLE
Connector not detected by several mods (Surveyor, Antique Atlas and others)

### ISSUE THREAD

**Issue by EugeneLeclerc** [Sinytra/Connector#1398]
### Mod Name

Surveyor

### Mod Homepage

https://modrinth.com/mod/surveyor

### Minecraft version

1.21.1

### Describe the bug

It seems several mods from the same developper (at least https://modrinth.com/mod/surveyor and https://modrinth.com/mod/antique-atlas-4) do not detect Connector. Trying to start the server will shows this error: 

```
net.neoforged.fml.ModLoadingException: Loading errors encountered:         
- Mod surveyor requires connector any           Currently, connector is not installed
```

### Steps to reproduce

1. Setup a Neoforge server 
2. Install Connector and FFAPI
3. Install Surveyor
4. Crash at startup!

### Logs

https://github.com/user-attachments/files/16929904/surveyor.log

### Additional context

This only happens on my server, not on my client, even tho the mod list is the same.

**Comment by Tapacywka** [comment]
Antique Atlas is for client only, it does not need to be installed on the server. Perhaps the second mod is also for client only.

**Comment by EugeneLeclerc** [comment]
> Antique Atlas is for client only, it does not need to be installed on the server. Perhaps the second mod is also for client only.

Antique Atlas is indeed for client only, but Surveyor is not. I only included Antique Atlas to show multiple mods from the same dev had the same problem, so they probably have something in common.

**Comment by Tapacywka** [comment]
The problem is that Connector uses the "connectormod" identifier and the developer refers to the "connector" identifier, which is incorrect.

**Comment by Tapacywka** [comment]
But there's also a fun fact in those logs: the server really doesn't see the Connector, because it doesn't show up in the mod list.

**Comment by EugeneLeclerc** [comment]
> But there's also a fun fact in those logs: the server really doesn't see the Connector, because it doesn't show up in the mod list.

Connector seems to correctly show up when I remove surveyor: [latest.log](https://github.com/user-attachments/files/16931834/latest.log). At least that's what I think, I'm new to reading Minecraft logs.

**Comment by EugeneLeclerc** [comment]
> The problem is that Connector uses the "connectormod" identifier and the developer refers to the "connector" identifier, which is incorrect.

Where do you see the "connectormod" identifier? I'm trying to find it to maybe fix it myself manually in the .jar 😄
