### ISSUE TITLE
Crashing when trying to create world with Tectonic (NeoForge 1.21.1)

### ISSUE THREAD

**Issue by 3ncanis** [Sinytra/Connector#1401]
### Mod Name

Tectonic

### Mod Homepage

https://modrinth.com/datapack/tectonic

### Minecraft version

1.21.1

### Describe the bug

When you try to create a new world with Sinytra Connector, Forgified Fabric API and Tectonic, you CTD

### Steps to reproduce

1. Install Sinytra/FFAPI
2. Install Tectonic
3. Try to create new world

### Logs

https://mclo.gs/pgYv2a8

**Comment by Su5eD** [comment]
Duplicate of #1345
