### ISSUE TITLE
Forgified Fabric API crashes with EnlightenedBlockEntities (fork of EnhancedBlockEntities) in 1.20.1

### ISSUE THREAD

**Issue by CapoFantasma97** [Sinytra/Connector#1402]
### Mod Name

EnlightenedBlockEntities

### Mod Homepage

https://github.com/ITsMrToad/EBEReforged

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on startup

### Steps to reproduce

The game crashes on startup

### Logs

https://gist.github.com/AvaloriaSinytra/cc7eaa6af6fd6e3ab78e2b4e5ed023d3

### Additional context

EnlightenedBlockEntities is a Forge/NeoForge fork of the Fabric mod EnhancedBlockEntities

**Comment by CapoFantasma97** [comment]
ITsMrToad/EBEReforged#1

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by ITsMrToad** [comment]
This has been fixed on my end. Update EBE to 0.8.
