### ISSUE TITLE
Fabric Language Kotlin and Essential

### ISSUE THREAD

**Issue by K0rS1z** [Sinytra/Connector#1404]
### Mod Name

Fabric Language Kotlin

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When the Connector is working with the Fabric Language Kotlin mod, Essential does not work.

### Steps to reproduce

1. Remove Essential
2. Starting the game

### Logs

https://gist.github.com/K0rS1z/1b8ce745cb826aebf63c1e33b8aa9404

### Additional context

Forge - 47.3.0
Mods:
Connector-1.0.0-beta.45+1.20.1.jar,
essential_1-3-4-1_forge_1-20-1.jar
fabric-api-0.92.2+1.11.8+1.20.1.jar
fabric-language-kotlin-1.12.1+kotlin.2.0.20.jar

I saw issue #1050 and it had the answer that Essential has closed source code. Isn't there enough information about this here? - https://github.com/EssentialGG/Essential

**Comment by Su5eD** [comment]
This is likely an issue on essential's side, please report it to them instead. Fabric Language Kotlin works fine on its own for me, and is unaffected by forge mods.
