### ISSUE TITLE
[1.20.1] Exordium mixin crash

### ISSUE THREAD

**Issue by Reshy** [Sinytra/Connector#1405]
### Mod Name

Exordium

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/exordium

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on load

### Steps to reproduce

1.  Install Connector
2.  Install Exordium
3.  Boot Minecraft
4. Crash!

### Logs

https://pastebin.com/2GKcScEc

### Additional context

The forge version of the mod crashes as well, so until the mixins are fixed on the fabric version there is **no way to use exordium** in a connector environment.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
