### ISSUE TITLE
BetterEnd 1.20.1 displays an error making the game unplayable

### ISSUE THREAD

**Issue by iDryZe** [Sinytra/Connector#1406]
### Mod Name

BetterEnd Mod

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1 (LTS)

### Describe the bug

I am using the latest version of forge 47.3.10 and am using BetterEnd alongside its necessities like BCLib, Sinytra and the fabric api all on their latest versions as well. The game runs smoothly but after some time on the end traveling the game crashes and just kicks me out of the world for no apparent reason. I have tried searching the web but nothing of the like comes up. It says something about not being able to correctly load the facing of the block. On top of that it doesnt allow the creation of other worlds which completely crashes my game and doesnt even let me open it.

### Steps to reproduce

1.Open MInecraft Launcher withe Just Enough Crashes downloaded 
2.Open up a new world and traverse the end islands not the dragon fight
3.After the game crashes try creating a new world
...

### Logs

https://gist.github.com/iDryZe/398de52a88901d36356c70d29eb82f87

### Additional context

I tried removing a few other mods i have downloaded as performance enhancers and gameplay adding ones but nothing seems to work. I am honestly dumbfounded

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
