### ISSUE TITLE
Error: net.minecraftforge.fml.loading.EarlyLoadingException

### ISSUE THREAD

**Issue by JCHB322** [Sinytra/Connector#1407]
### Mod Name

Better End

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The game crashed whilst initializing game Error: net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'client' due to errors, provided by 'betterend'!

### Steps to reproduce

1. Launch Minecraft from CurseForge.
2. Game crashes.

### Logs

https://gist.github.com/JCHB322/9c3ae399c678a1292122ebf17332a0d7

### Additional context

Everything worked just fine yesterday. Today, I launched the game as usual... and it crashed. Nothing (that I am aware of) has changed from yesterday to now. Everything is up-to-date.

**Comment by Kapil242** [comment]
Was this every resolved? I experience the same crash report except with aaa_particles which I believe to be a dependency of the eldritch end mod

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
