### ISSUE TITLE
Conflict with JEI latest version for Forge 1.20.1

### ISSUE THREAD

**Issue by VsUK** [Sinytra/Connector#1410]
### Mod Name

Connector

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on server start up..

### Steps to reproduce

org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field vanillaKeyMapping was not located in the target class net.minecraft.client.KeyMapping. Using refmap mixins.connectormod.refmap.json

### Logs

n/a

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
