### ISSUE TITLE
[Help Wanted] [Bug] AdventureZ and Moonrise

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#1411]
### Mod Name

Moonrise

### Mod Homepage

https://modrinth.com/mod/moonrise-opt/version/0.1.0-beta.1+98e8a08

### Minecraft version

1.21*

### Describe the bug

Crash on start-up.

### Steps to reproduce

1. Download AdventureZ 
`https://modrinth.com/mod/adventurez`
2. Download Moon Rise 1.21
`https://modrinth.com/mod/moonrise-opt/version/0.1.0-beta.1+98e8a08`
3. Utilize connector and fabricated api
4. Launch

### Crash Report
[crash-2024-09-13_16.47.26-client.txt](https://github.com/user-attachments/files/16999690/crash-2024-09-13_16.47.26-client.txt)

### Logs

https://gist.github.com/Cixon/40045a6c6867ec82ab0acffc9b3a2be3

### Additional context

MC version: 1.21
NeoForge: 21.0.160

**Comment by Cixon** [comment]
`Help wanted` because idk if this is connector related or something Moonrise would need to fix

**Comment by coco875** [comment]
did you try on fabric ? and if yes does it make the same issue ? if it's the case then it's a problem between adventurez and moonrise

**Comment by Cixon** [comment]
> did you try on fabric ? and if yes does it make the same issue ? if it's the case then it's a problem between adventurez and moonrise

Moonrise is a NeoForge mod. AdventureZ is a fabric mod, there's no mod-loader alternative for either or.

**Comment by coco875** [comment]
??? moonrise are also on fabric

**Comment by coco875** [comment]
https://modrinth.com/mod/moonrise-opt/version/Kxy5mXbm I just ask you to try reproduce the crash on fabric

**Comment by Cixon** [comment]
> https://modrinth.com/mod/moonrise-opt/version/Kxy5mXbm I just ask you to try reproduce the crash on fabric

Using fabric mod-loader 1.21.1 - 0.16.5 with both the mod version you provided and Adventure Z, it does not crash. Seems stable with fabric mod-loader.

Trying that same mod version you provided with connector in addition to Adventure Z, crash still persists.

**Comment by coco875** [comment]
ok

**Comment by Su5eD** [comment]
> org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[`@At`("INVOKE_ASSIGN")] on net/minecraft/world/level/Explosion::collectBlocksAndDamageEntitiesMixin with priority 1000 cannot inject into net/minecraft/world/level/Explosion::explode()V merged by ca.spottedleaf.moonrise.mixin.collisions.ExplosionMixin with priority 1000 [PREINJECT Applicator Phase -> adventurez.mixins.json:ExplosionMixin from mod adventurez -> Prepare Injections -> handler$zca000$adventurez$collectBlocksAndDamageEntitiesMixin(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Set;IFIIIIIILjava/util/List;)V -> Prepare ->  -> { target: explode()V }]

A mixin conflict between adventurez and moonrise, it seems. Please report it to them so that they can change their priorities.
