### ISSUE TITLE
Texture problem

### ISSUE THREAD

**Issue by SaskeCat** [Sinytra/Connector#1412]
### Mod Name

More Axolotl Variants Mod

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mavm

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The provided mod adds item icons for axolotl buckets of all the types, vanilla minecraft axolotl AND mav mod axelotl buckets. However with this mod collecting axolotl gives the black and purple checkered texture (except for the pink axolotl) which is awful and looks like the game is broken

### Steps to reproduce

1. Install More Axolotl Variants Mod
2. Install More Axolotl Variants API
3. Install Sinytra Connector
4. Install Forgified Fabric API
5. Run the game
6. Spawn different colored Axolotls
7. Collect Axolotls with water buckets
![image](https://github.com/user-attachments/assets/deb1830d-15f1-4dd4-b4d8-62f5b1504e0a)

### Logs

https://pastebin.com/kAVimbKK

### Additional context

If this bug is too small to be patched is there a way for me to fix this issue by myself?

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
