### ISSUE TITLE
Client side issues with Better End 

### ISSUE THREAD

**Issue by MyDarlingirene** [Sinytra/Connector#1413]
### Minecraft version

1.20.1

### Describe the bug

Upon launching the game through curseforge it loads for a few seconds before crashing. Crash reports say " Could not execute entrypoint stage 'client' due to errors, provided by 'betterend'"

### Steps to reproduce

1. Launch Game
2. Load for a few moments
3. 
...

### Logs

https://mclo.gs/wFW7TIQ

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
