### ISSUE TITLE
Sinytra Connector crashing when using 1.20.1 neoforge 

### ISSUE THREAD

**Issue by gltchii** [Sinytra/Connector#1417]
### Mod Name

Sinytra Connector

### Mod Homepage

https://modrinth.com/mod/connector/

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Exit code 1 when launching NF 1.20.1 with Connector-1.0.0-beta.45+1.20.1.jar

### Steps to reproduce

1. Install neoforge 20.2.73
2. Install Sinytra Connector 1.0 beta 45 to the mods folder
3. Launch game

### Logs

https://gist.github.com/Shiba-Abihs/ae09e8d52453ff466c7a6e68a584fdbc

### Additional context

Mods: 
Connector-1.0.0-beta.45+1.20.1.jar
BCLIB-1.20.1-3.0.14.jar
ConnectorExtras-1.11.2+1.20.1.jar

fabric-api-0.92.2+1.11.8+1.20.1.jar

immersive-portals-3.3.7-mc1.20.1

infinity-1.11.1-1.20.1.jar

Patchouli-1.20.1-84-FORGE.jar

RoughlyEnoughltems-12.1.758-forge.jar

trinkets-3.7.2.jar

**Comment by Tapacywka** [comment]
You need to use Forgified Fabric API with Connector (and Connector Extras for better Fabric mods compatibility).

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by Gaming-tech-cyber** [comment]
forge 47.3.27 breaks fabric api as it refers to: (beginning of report) org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
at net.minecraft.world.entity.npc.VillagerTrades.m_35632_(VillagerTrades.java:65) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.Util.m_137469_(Util.java:359) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading}
at net.minecraft.world.entity.npc.VillagerTrades.<clinit>(VillagerTrades.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
at net.minecraftforge.common.VillagerTradingManager.<clinit>(VillagerTradingManager.java:32) ~[forge-1.20.1-47.3.27-universal.jar%23163!/:?] {re:classloading}
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23138!/:?] {}
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23138!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23138!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23138!/:?] {}
at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:98) ~[forge-1.20.1-47.3.27-universal.jar%23163!/:?] {re:classloading}
at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
-- System Details --
fabric-blockrenderlayer-v1-1.1.41+1d0da21e77.jar |Fabric BlockRenderLayer Regist|fabric_blockrenderlayer_v1 |1.1.41+1d0da21e77 |DONE |Manifest: NOSIGNATURE
fabric-item-api-v1-2.1.28+4d0bbcfa77.jar |Fabric Item API (v1) |fabric_item_api_v1 |2.1.28+4d0bbcfa77 |DONE |Manifest: NOSIGNATURE
fabric-block-api-v1-1.0.11+0e6cb7f777.jar |Fabric Block API (v1) |fabric_block_api_v1 |1.0.11+0e6cb7f777 |DONE |Manifest: NOSIGNATURE
fabric-rendering-fluids-v1-3.0.28+4ac5e37a77.jar |Fabric Rendering Fluids (v1) |fabric_rendering_fluids_v1 |3.0.28+4ac5e37a77 |DONE |Manifest: NOSIGNATURE
fabric-resource-conditions-api-v1-2.3.8+9ad825cd77|Fabric Resource Conditions API|fabric_resource_conditions_api|2.3.8+9ad825cd77 |DONE |Manifest: NOSIGNATURE
fabric-screen-handler-api-v1-1.3.30+561530ec77.jar|Fabric Screen Handler API (v1)|fabric_screen_handler_api_v1 |1.3.30+561530ec77 |DONE |Manifest: NOSIGNATURE
fabric-models-v0-0.4.2+7c3892a477.jar |Fabric Models (v0) |fabric_models_v0 |0.4.2+7c3892a477 |DONE |Manifest: NOSIGNATURE
fabric-resource-loader-v0-0.11.10+bcd08ed377.jar |Fabric Resource Loader (v0) |fabric_resource_loader_v0 |0.11.10+bcd08ed377 |DONE |Manifest: NOSIGNATURE
fabric-rendering-v1-3.0.8+66e9a48f77.jar |Fabric Rendering (v1) |fabric_rendering_v1 |3.0.8+66e9a48f77 |DONE |Manifest: NOSIGNATURE
fabric-renderer-indigo-1.5.2+b5b2da4177.jar |Fabric Renderer - Indigo |fabric_renderer_indigo |1.5.2+b5b2da4177 |DONE |Manifest: NOSIGNATURE
fabric-item-group-api-v1-4.0.12+c9161c2d77.jar |Fabric Item Group API (v1) |fabric_item_group_api_v1 |4.0.12+c9161c2d77 |DONE |Manifest: NOSIGNATURE
fabric-convention-tags-v1-1.5.5+fa3d1c0177.jar |Fabric Convention Tags |fabric_convention_tags_v1 |1.5.5+fa3d1c0177 |DONE |Manifest: NOSIGNATURE
fabric-command-api-v1-1.2.34+f71b366f77.jar |Fabric Command API (v1) |fabric_command_api_v1 |1.2.34+f71b366f77 |DONE |Manifest: NOSIGNATURE
fabric-mining-level-api-v1-2.1.50+561530ec77.jar |Fabric Mining Level API (v1) |fabric_mining_level_api_v1 |2.1.50+561530ec77 |DONE |Manifest: NOSIGNATURE
fabric-block-view-api-v2-1.0.1+0767707077.jar |Fabric BlockView API (v2) |fabric_block_view_api_v2 |1.0.1+0767707077 |DONE |Manifest: NOSIGNATURE
fabric-command-api-v2-2.2.13+561530ec77.jar |Fabric Command API (v2) |fabric_command_api_v2 |2.2.13+561530ec77 |DONE |Manifest: NOSIGNATURE
fabric-data-attachment-api-v1-1.0.0+30ef839e77.jar|Fabric Data Attachment API (v1|fabric_data_attachment_api_v1 |1.0.0+30ef839e77 |DONE |Manifest: NOSIGNATURE
mixinextras-forge-0.3.5.jar |MixinExtras |mixinextras |0.3.5 |DONE |Manifest: NOSIGNATURE
fabric-biome-api-v1-13.0.13+dc36698e77.jar |Fabric Biome API (v1) |fabric_biome_api_v1 |13.0.13+dc36698e77 |DONE |Manifest: NOSIGNATURE
fabric-entity-events-v1-1.6.0+6274ab9d77.jar |Fabric Entity Events (v1) |fabric_entity_events_v1 |1.6.0+6274ab9d77 |DONE |Manifest: NOSIGNATURE
fabric-registry-sync-v0-2.3.3+1c0ea72177.jar |Fabric Registry Sync (v0) |fabric_registry_sync_v0 |2.3.3+1c0ea72177 |DONE |Manifest: NOSIGNATURE
fabric-recipe-api-v1-1.0.21+514a076577.jar |Fabric Recipe API (v1) |fabric_recipe_api_v1 |1.0.21+514a076577 |DONE |Manifest: NOSIGNATURE
fabric-loot-api-v2-1.2.1+eb28f93e77.jar |Fabric Loot API (v2) |fabric_loot_api_v2 |1.2.1+eb28f93e77 |DONE |Manifest: NOSIGNATURE
fabric-object-builder-api-v1-11.1.3+2174fc8477.jar|Fabric Object Builder API (v1)|fabric_object_builder_api_v1 |11.1.3+2174fc8477 |DONE |Manifest: NOSIGNATURE
fabric-screen-api-v1-2.0.8+45a670a577.jar |Fabric Screen API (v1) |fabric_screen_api_v1 |2.0.8+45a670a577 |DONE |Manifest: NOSIGNATURE
fabric-rendering-data-attachment-v1-0.3.37+a6081af|Fabric Rendering Data Attachme|fabric_rendering_data_attachme|0.3.37+a6081afc77 |DONE |Manifest: NOSIGNATURE
fabric-networking-api-v1-1.3.11+503a202477.jar |Fabric Networking API (v1) |fabric_networking_api_v1 |1.3.11+503a202477 |DONE |Manifest: NOSIGNATURE
fabric-sound-api-v1-1.0.13+4f23bd8477.jar |Fabric Sound API (v1) |fabric_sound_api_v1 |1.0.13+4f23bd8477 |DONE |Manifest: NOSIGNATURE
fabric-particles-v1-1.1.2+78e1ecb877.jar |Fabric Particles (v1) |fabric_particles_v1 |1.1.2+78e1ecb877 |DONE |Manifest: NOSIGNATURE
forge-1.20.1-47.3.27-universal.jar |Forge |forge |47.3.27 |DONE |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
fabric-message-api-v1-5.1.9+52cc178c77.jar |Fabric Message API (v1) |fabric_message_api_v1 |5.1.9+52cc178c77 |DONE |Manifest: NOSIGNATURE
fabric-api-0.92.2+1.11.9+1.20.1.jar |Forgified Fabric API |fabric_api |0.92.2+1.11.9+1.20.1|DONE |Manifest: NOSIGNATURE
fabric-content-registries-v0-4.0.11+a670df1e77.jar|Fabric Content Registries (v0)|fabric_content_registries_v0 |4.0.11+a670df1e77 |DONE |Manifest: NOSIGNATURE
fabric-transitive-access-wideners-v1-4.3.1+1880499|Fabric Transitive Access Widen|fabric_transitive_access_widen|4.3.1+1880499877 |DONE |Manifest: NOSIGNATURE
fabric-lifecycle-events-v1-2.2.22+afab492177.jar |Fabric Lifecycle Events (v1) |fabric_lifecycle_events_v1 |2.2.22+afab492177 |DONE |Manifest: NOSIGNATURE
fabric-data-generation-api-v1-12.3.4+369cb3a477.ja|Fabric Data Generation API (v1|fabric_data_generation_api_v1 |12.3.4+369cb3a477 |DONE |Manifest: NOSIGNATURE
fabric-events-interaction-v0-0.6.2+0d0bd5a777.jar |Fabric Events Interaction (v0)|fabric_events_interaction_v0 |0.6.2+0d0bd5a777 |DONE |Manifest: NOSIGNATURE
fabric-key-binding-api-v1-1.0.37+561530ec77.jar |Fabric Key Binding API (v1) |fabric_key_binding_api_v1 |1.0.37+561530ec77 |DONE |Manifest: NOSIGNATURE
fabric-client-tags-api-v1-1.1.2+5d6761b877.jar |Fabric Client Tags |fabric_client_tags_api_v1 |1.1.2+5d6761b877 |DONE |Manifest: NOSIGNATURE
Crash Report UUID: ab6521a4-59f4-433f-969a-3b925d8083c8
FML: 47.3
Forge: net.minecraftforge:47.3.27 (end of report) and you can't even load into a world as it says worldserver2 is null

**Comment by Gaming-tech-cyber** [comment]
this is with nothing but sinytra connector, connector extras, and forgified fabric api, all latest versions just like the forge loader

**Comment by Gaming-tech-cyber** [comment]
had to revert to last version before it (47.3.25) for it to work

**Comment by cassiancc** [comment]
Known issue in FFAPI, will be fixed when https://github.com/Sinytra/ForgifiedFabricAPI/pull/191 is merged.
