### ISSUE TITLE
Crash with BCLib when running on Server

### ISSUE THREAD

**Issue by Li3Fish** [Sinytra/Connector#142]
### Describe the bug

Crash with BCLib when running on Server(Forge 47.1.3),But BCLib works well on client(Forge 47.1.3)

### Steps to reproduce

1.Install a brand-new Forge Server
2.Add Connector(beta10),Forgified FabricAPI(0.87.0+1.9.6+1.20.1) and [BCLib](https://modrinth.com/mod/bclib/version/3.0.13)
3.Start the server
4.Wait for crash

### Logs

https://pastebin.com/af53F6GT

**Comment by Cixon** [comment]
Interesting. I haven’t tested in a server environment but why not use Essential mod?

**Comment by Su5eD** [comment]
How is it related?

**Comment by Su5eD** [comment]
My suspicion here is `@Environment` methods are not being stripped properly on Forge. We'll have to remap them to use Forge's `@OnlyIn` annotation instead.

**Comment by Li3Fish** [comment]
> Interesting. I haven’t tested in a server environment but why not use Essential mod?

Because I want to use connector in my server😭
