### ISSUE TITLE
Oritech incompatibility

### ISSUE THREAD

**Issue by nekonomura** [Sinytra/Connector#1420]
### Mod Name

oritech

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/oritech

### Minecraft version

1.21.1

### Describe the bug

If you start oritech and its dependencies owo-lib, athena, geckolib, lavender together with TechReborn in Connector, it will crash.

### Logs

https://mclo.gs/V8ESwf0

### Additional context

owo-lib
(If you do not install this mod, the game will crash at an earlier stage or for another reason.)
https://www.curseforge.com/minecraft/mc-mods/owo-lib

Even if you don't install these MODs, it will just show that there are no dependencies, but the game will not force a reset.
gecko
https://www.curseforge.com/minecraft/mc-mods/geckolib
athena
https://www.curseforge.com/minecraft/mc-mods/athena
lavender
https://www.curseforge.com/minecraft/mc-mods/lavender

normal fabric+The mods listed here, the mod+Connector above, and the mod+Connector below work properly. Only the combination of Connector + the mods listed here will not work.
TechReborn
https://www.curseforge.com/minecraft/mc-mods/techreborn

**Comment by Su5eD** [comment]
Oritech is now available for NeoForge
