### ISSUE TITLE
1.21.1 Neoforge Leaf Texture bug

### ISSUE THREAD

**Issue by Jafooleryy** [Sinytra/Connector#1421]
### Minecraft version

1.20.1

### Describe the bug

Oak Leaves has its old texture instead of the modern texture.

### Steps to reproduce

1. Install Connector, Connector Extras, and Forgified Fabric API
2. Launch MC World
3. 
![Base Profile Screenshot 2024 09 15 - 18 33 57 12](https://github.com/user-attachments/assets/13771bba-15d5-49f8-abc3-bb8477a910d5)

Other Mods Installed: Sodium and Iris

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
