### ISSUE TITLE
Source Stone in VoidZ can't work.

### ISSUE THREAD

**Issue by CrazyNut-Figures-Out** [Sinytra/Connector#1422]
### Minecraft version

1.20.1

### Describe the bug

The source stone couldn't shoot projectiles or phase through walls when I right-click or shift and right-click.

### Steps to reproduce

1. I was using a forge modpack, so I use Sinytra Connector to launch AdventrueZ and VoidZ.
2. According to the descriptions, the source stone could shoot projectiles if you right click and could phrase the player through walls if you right click with shift.
3. I did what it said above, but nothing happens except there was a cooling animation on the source stone in the inventory(like the animation on shield while hitting by a axe)

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
