### ISSUE TITLE
RedBits crash upon launch

### ISSUE THREAD

**Issue by kokofixcomputers** [Sinytra/Connector#1425]
### Mod Name

RedBits

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/red-bits

### Minecraft version

1.20.1 (LTS)

### Describe the bug

It crashes upon launch of game

### Steps to reproduce

1. Install the mod
2.Launch the game

### Logs

https://pastebin.com/BFXb9Hvx

**Comment by kokofixcomputers** [comment]
Same goes with LED: https://www.curseforge.com/minecraft/mc-mods/led

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
