### ISSUE TITLE
[1.20.1] Effective mod for fabric does not load

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#1426]
### Mod Name

Effective

### Mod Homepage

https://modrinth.com/mod/effective

### Minecraft version

1.20.1 (LTS)

### Describe the bug

when installing effective for both fabric and quilt, the game does not start.

### Steps to reproduce

1. install effective 1.20.1 for both fabric **and** quilt,
2. launch Minecraft forge 1.20.1 - 47.3.10

### Logs

https://gist.github.com/vinnyg0621/46eff0c3e37674ff20edaf538e765870

### also my latest log: 
[latest.log](https://github.com/user-attachments/files/17069161/latest.log)

**Comment by vinnyg0621** [comment]
issue still persists:
![Screenshot 2024-09-22 105735](https://github.com/user-attachments/assets/182e7445-343c-4fcd-90db-3143bc1001ee)
[crash-2024-09-22_10.56.38-fml.txt](https://github.com/user-attachments/files/17090676/crash-2024-09-22_10.56.38-fml.txt)
[latest.log](https://github.com/user-attachments/files/17090677/latest.log)

**Comment by Raiiiden** [comment]
Use Particular for now

**Comment by vinnyg0621** [comment]
actually for now I use the forge version of effective

**Comment by mateus3c** [comment]
> actually for now I use the forge version of effective

it's only for 1.19.2

**Comment by vinnyg0621** [comment]
no, I found the repo of it for 1.20 and I converted it into a jarfile using visual studio code

**Comment by RaptorZeraora** [comment]
I hope this gets fixed

**Comment by RaptorZeraora** [comment]
ALso, vinny what version of effective is it?

**Comment by kakashi1464** [comment]
> ALso, vinny what version of effective is it?

1.3.4

**Comment by WitherTM** [comment]
> 1.3.4

that is not a real version?

**Comment by kakashi1464** [comment]
> > 1.3.4
> 
> that is not a real version?

https://www.curseforge.com/minecraft/mc-mods/effective-forge/files/4017700

**Comment by WitherTM** [comment]
> > > 1.3.4
> > 
> > 
> > that is not a real version?
> 
> https://www.curseforge.com/minecraft/mc-mods/effective-forge/files/4017700

oh you talking about the forge port, gotcha

**Comment by Teanen** [comment]
> no, I found the repo of it for 1.20 and I converted it into a jarfile using visual studio code

do you still have it? 
I cant find it anywhere and Particular also doenst work with the connector

**Comment by mateus3c** [comment]
Particular does work with connector, I'm using it rn

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
