### ISSUE TITLE
Simply Skills: Ascendancy

### ISSUE THREAD

**Issue by Scycisolum** [Sinytra/Connector#1427]
### Mod Name

Simply Skills

### Mod Homepage

https://www.curseforge.com/

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Certain bugs that were present in previous versions of Simply Skills, such as skyward sunder, cleave, and ghostwalk crashing your game is present, and I am supposing it's because this connector is not compatible with the latest version of Simply Skills.

### Steps to reproduce

1. use the command /puffer-skills points add (username) simplyskills:tree 42 (aka, max out the first skill tree)
2. you will get the ascendancy skill tree, and unlock ghostwalk or anything else i listed (can use the same command, just replace simplyskills:tree with simplyskills:ascendancy)
3. use the move while clashing into another entity
...

### Logs

https://gist.github.com/Scycisolum/443bba444a8e7fb1e4f768853a4c9133#file-gistfile1-txt

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
