### ISSUE TITLE
Cannot Swim with Vannila-Degus Mod

### ISSUE THREAD

**Issue by Mugen2411** [Sinytra/Connector#1431]
### Mod Name

Vannila Degus

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/vanilla-degus

### Minecraft version

1.21.1

### Describe the bug

Cannot swim in waterSource.

### Steps to reproduce

1. install [Connector 2.0.0-beta.2+1.21.1]
2. install [forgified-fabric-api-0.102.0+2.0.12+1.21.1]
3. install [vanilla_degus-1.21+-v1.5.2-fabric]
4. start survival game
5. dive to waterSource
6. Cannnot Swim

### Logs

not crash

### Additional context

I can swim in waterMoving.

**Comment by BentoGambin** [comment]
Better nether and Better End mods also cause this.

**Comment by Cixon** [comment]
Yeah there’s a pattern with quite a few mods. Duplicate post. 
https://github.com/Sinytra/Connector/issues/1343#issuecomment-2295574404

**Comment by Mugen2411** [comment]
thx.
I will close this and watch #1343 .


> Yeah there’s a pattern with quite a few mods. Duplicate post. [#1343 (comment)](https://github.com/Sinytra/Connector/issues/1343#issuecomment-2295574404)
