### ISSUE TITLE
Incompatible with anyscale causes crash

### ISSUE THREAD

**Issue by NeoStarWonV** [Sinytra/Connector#1438]
### Mod Name

anyscale appleskin

### Mod Homepage

https://modrinth.com/mod/anyscale/versions

### Minecraft version

1.20.1 (LTS)

### Describe the bug

crashed when started the game

### Steps to reproduce

crashed when started the game

### Logs

https://mclo.gs/aoS7kJn

### Additional context

no

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
