### ISSUE TITLE
Carpet Incompatible

### ISSUE THREAD

**Issue by ghost** [Sinytra/Connector#1440]
### Mod Name

Fabric-Carpet

### Mod Homepage

https://modrinth.com/mod/carpet

### Minecraft version

1.21.1

### Describe the bug

 The server throws an error when I run it with the carpet mod

### Steps to reproduce

1.
2.
3.
...

### Logs

https://paste.ubuntu.com/p/35PHCcyFpV/

**Comment by Su5eD** [comment]
Duplicate of https://github.com/Sinytra/Connector/issues/296
