### ISSUE TITLE
Forge mod item pipes won't connect to Tech Reborn machines.

### ISSUE THREAD

**Issue by furtabs** [Sinytra/Connector#1441]
### Minecraft version

1.20.1

### Describe the bug

Forge mod item pipes won't connect to Tech Reborn machines. seems to pull out laserio cards as well as a side effect when trying different options.

### Steps to reproduce

https://media.discordapp.net/attachments/1288999692499288116/1289005261159268422/2024-09-26_19.png?ex=66f93972&is=66f7e7f2&hm=5d3631713d4b561a006853eb90f59bad8be02e988540e47eaec424f6c13d97fd&

### Additional context

Something is mostjmely wrong with item capabilities

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by furtabs** [comment]
See the issue i made on FFAPI
