### ISSUE TITLE
Update the `gson` version to catch up the version used by fabric platform.

### ISSUE THREAD

**Issue by sakurawald** [Sinytra/Connector#1443]
### Minecraft version

1.21

### Describe the bug

The `gson` used by fabric platform is newer, so mods use the new version will failed to call the new methods, due to `NoSuchMethodError`

### Steps to reproduce

Call the method `JsonObject#isEmpty` added in `gson v2.10.1`
```
  /**
   * Returns true if the number of key/value pairs in the object is zero.
   *
   * @return true if the number of key/value pairs in the object is zero.
   * @since 2.10.1
   */
  public boolean isEmpty() {
    return members.size() == 0;
  }
```

Get the error:
```
[29Sep2024 18:00:53.246] [main/ERROR] [mixin/]: Error loading companion plugin class [io.github.sakurawald.module.mixin.GlobalMixinConfigPlugin] for mixin config [fuji.mixins.json]. The plugin may be out of date: NoSuchMethodError:'boolean com.google.gson.JsonObject.isEmpty()'
java.lang.NoSuchMethodError: 'boolean com.google.gson.JsonObject.isEmpty()'
```

### Logs

https://mclo.gs/qet1h24

### Additional context

none

**Comment by Su5eD** [comment]
I think this will need to be addressed on NeoForge's side, as Connector does not have control over game libraries. It seems like they're already using the correct gson version, but due to a bug in tooling, an older version makes its way into both usersev and production, causing this issue.

**Comment by sakurawald** [comment]
> I think this will need to be addressed on NeoForge's side, as Connector does not have control over game libraries. It seems like they're already using the correct gson version, but due to a bug in tooling, an older version makes its way into both usersev and production, causing this issue.

Okay.
