### ISSUE TITLE
`Oxidized` mod is broken with the latest `Friends & Foes` update

### ISSUE THREAD

**Issue by mpustovoi** [Sinytra/Connector#1444]
### Mod Name

Oxidized

### Mod Homepage

https://modrinth.com/mod/oxidized

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The game crashes on the early loading screen.
Everything was working normally before `F&F` was updated to v3.0.X.

### Steps to reproduce

1. Install `Sinytra Connector` (latest `1.0.0-beta.46+1.20.1`).
2. Install `Oxidized`.
3. Install `Friends & Foes (Forge/NeoForge)`.
4. Launch the game and get a crash on the early loading screen.

### Logs

https://mclo.gs/5c9KEtv

### Additional context

There is nothing in the log about the error, so here is the crash report:
https://mclo.gs/IVqOdaO

The item called `friendsandfoes:copper_button` is still present in `F&F`, the ID hasn't changed.

`Friends & Foes (Forge/NeoForge)` mod's homepage:
https://modrinth.com/mod/friends-and-foes-forge

`Friends & Foes (Fabric/Quilt)` with `Oxidized` worked and are working fine on Fabric 1.20.1 even after `F&F` v3.0.X.

Minimum setup:
![image](https://github.com/user-attachments/assets/c0f81b19-b421-48e9-912c-ce2643c140bc)

**Comment by Su5eD** [comment]
Looks like Oxidized is not compatible with the Forge version of Friends Foes. Try using the Fabric version instead.
