### ISSUE TITLE
minecraft crashing when writing in mods menu with sinytra and dependencies installed

### ISSUE THREAD

**Issue by VaporeonScripts** [Sinytra/Connector#1445]
### Minecraft version

1.20.1

### Describe the bug

1.21.1 neoforge latest version

### Steps to reproduce

install this mod
install mods
open mod list, write something

### Logs

https://mclo.gs/isRT2D5

**Comment by VaporeonScripts** [comment]
and i cant make a world,it crashes

**Comment by Su5eD** [comment]
> 18:21:41] [Render thread/ERROR] [Mod Menu | ModsScreen/]: Error from mod 'bridgingmod'
java.lang.AbstractMethodError: Receiver class me.cg360.mod.bridging.entrypoint.neoforge.BridgingModNeoForge$$Lambda/0x0000718c8f7a2100 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.client.gui.screens.Screen createScreen(net.neoforged.fml.ModContainer, net.minecraft.client.gui.screens.Screen)' of interface net.neoforged.neoforge.client.gui.IConfigScreenFactory.

**Comment by VaporeonScripts** [comment]
> > 18:21:41] [Render thread/ERROR] [Mod Menu | ModsScreen/]: Error from mod 'bridgingmod'
> > java.lang.AbstractMethodError: Receiver class me.cg360.mod.bridging.entrypoint.neoforge.BridgingModNeoForge$$Lambda/0x0000718c8f7a2100 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.client.gui.screens.Screen createScreen(net.neoforged.fml.ModContainer, net.minecraft.client.gui.screens.Screen)' of interface net.neoforged.neoforge.client.gui.IConfigScreenFactory.

what does that have to do with syntra? its a mod menu issue(?)
