### ISSUE TITLE
[1.20.1] Unicopia Crashes when loading world

### ISSUE THREAD

**Issue by Silverfishv9** [Sinytra/Connector#1446]
### Mod Name

Unicopia

### Mod Homepage

https://modrinth.com/mod/unicopia

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on loading into world

### Steps to reproduce

1. Install only lastest version of Sinytra Connector, Fabric API, and Unicopia for 1.20.1, as well as recommended version of Forge
2. Launch game, attempt to load into an unmodded or new world
3. "The game crashed whilst starting integrated server"
...

### Logs

https://gist.github.com/Silverfishv9/0f5c4048489591963a721549578f940d

### Additional context

Crashes were repeated several times to make sure. Mod works fine on fabric alone.

**Comment by yBOBi** [comment]
I have the same crash. Please fix it. Equestria with forge mods is waiting for us

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
