### ISSUE TITLE
1.20.1 Temp Files Cause CurseForge Modpacks to Get Rejected

### ISSUE THREAD

**Issue by MokahTGS** [Sinytra/Connector#1447]
### Minecraft version

1.20.1

### Describe the bug

Temp Files Cause CurseForge Modpacks to Get Rejected

### Steps to reproduce

1. Make Modpack
2. Use Connector and Eldritch End
3.Temp Files Get Left in Mod Folder
4.Curseforge cries because mod files are in the zip
5.rejection

Connector is making copies of the mod files and leaving them in the temp folder causing any modpack that uploads a zip file to get rejected.  These temp files should get cleaned out.

**Comment by Su5eD** [comment]
Files generated by connector inside the `.connector` folder contain remapped mods, which are cached between runs to improve load times and are part of essential connector functionality. Unfortunately, we have no plans to make changes to this functionality. I don't think Connector is the only mods that saves its own helper files into the mods folder either.

I recommend simply deleting the temp folder before submitting your modpack to curseforge.

**Comment by MokahTGS** [comment]
Can I delete everything in the connector folder in the zip file?  Do these files get created automatically when the client runs the game?

**Comment by Su5eD** [comment]
Yes, both are correct
