### ISSUE TITLE
Connector doesn't seem to convert mod's built-in dependencies

### ISSUE THREAD

**Issue by R4llik** [Sinytra/Connector#1448]
I encountered this problem while trying to run minecraft with Eldritch End. Eldritch End requires NecronomiconApi, AzureLib, Connector and AAAparticles to run. While NecronomiconApi and AzureLib need to be downloaded separately, AAAparticles are built into the mod. When you try to run minecraft with Eldritch End and all its dependencies, it crashes while loading and the only way to fix this is to download AAAparticles separately, leading to a situation where you have AAAparticles fabric that is built into Eldritch End and you have a AAAparticles forge that is loaded separately, only then will your minecraft launch.

**Comment by Su5eD** [comment]
Hi, thanks for reporting this bug. To make sure all issues follow the same format, please open a new issue using the Mod Compatibility issue template. Thank you.
