### ISSUE TITLE
Fabric Mod Discovery Failed!

### ISSUE THREAD

**Issue by BedrockBurger** [Sinytra/Connector#1449]
### Minecraft version

1.20.1

### Describe the bug

Duplicated a Modrinth instance to test Sinytra Connector. Most recent versions of connector and its dependancies are in the new pack. Removed any mods that Connector doesnt work with(like Sodium). Fixed issues with compatibility on other mods. Mod list can be provided if needed. Mostly Create and add-ons(just over 100, not sure if theres a cut off for assistance). Would appreciate assistance or direction to another SOLVED issue like this! 

### Steps to reproduce

1. Duplicated perfectly working pack on Modrinth to test Connector. Newest versions and dependencies.
2. Cut non-compatible mods and dependencies of said mods
3. Launch new pack with Sinytra, fix other compatibility issues. Fabric discovery issue.
4. Relaunch post-compatibility fix
5.  Crash. Fabric Mod Discovery error. 

### Logs

---- Minecraft Crash Report ---- // Surprise! Haha. Well, this is awkward.  Time: 2024-10-04 18:54:54 Description: Mod loading error has occurred  java.lang.Exception: Mod Loading has failed 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.106-universal.jar%23365!/:?] {re:classloading} 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.1.106-universal.jar%23365!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:classloading,pl:connector_pre_launch:A} 	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:148) ~[forge-1.20.1-47.1.106-universal.jar%23365!/:?] {re:classloading} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:958) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-47.1.106.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- NO MOD INFO AVAILABLE -- Details: 	Caused by 0: java.io.UncheckedIOException: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions 		at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:138) ~[securejarhandler-2.1.10.jar:?] {} 		at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70) ~[securejarhandler-2.1.10.jar:?] {} 		at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66) ~[securejarhandler-2.1.10.jar:?] {} 		at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58) ~[securejarhandler-2.1.10.jar:?] {} 		at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50) ~[securejarhandler-2.1.10.jar:?] {} 		at org.sinytra.connector.locator.ConnectorLocator.discoverNestedJarsRecursive(ConnectorLocator.java:259) ~[Connector-1.0.0-beta.46+1.20.1.jar%23256!/:1.0.0-beta.46+1.20.1] {} 		at org.sinytra.connector.locator.ConnectorLocator.lambda$discoverNestedJarsRecursive$26(ConnectorLocator.java:270) ~[Connector-1.0.0-beta.46+1.20.1.jar%23256!/:1.0.0-beta.46+1.20.1] {} 		at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {} 		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {} 		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {} 		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?] {} 		at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?] {} 		at org.sinytra.connector.locator.ConnectorLocator.locateFabricMods(ConnectorLocator.java:132) ~[Connector-1.0.0-beta.46+1.20.1.jar%23256!/:1.0.0-beta.46+1.20.1] {} 		at org.sinytra.connector.locator.ConnectorLocator.scanMods(ConnectorLocator.java:77) ~[Connector-1.0.0-beta.46+1.20.1.jar%23256!/:1.0.0-beta.46+1.20.1] {} 		at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:128) ~[loader-47.2.2.jar:47.2] {} 		at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164) ~[loader-47.2.2.jar:47.2] {} 		at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[loader-47.2.2.jar:47.2] {} 		at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-10.0.9.jar:?] {} 		at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-10.0.9.jar:?] {} 		at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {} 		at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {} 		at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {} 		at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?] {} 		at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) ~[modlauncher-10.0.9.jar:?] {} 		at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) ~[modlauncher-10.0.9.jar:?] {} 		at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar:?] {} 		at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}  	Mod File: NO FILE INFO 	Failure message: [Connector] Fabric mod discovery failed 		java.io.UncheckedIOException: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions 	Mod Version: NO MOD INFO AVAILABLE 	Mod Issue URL: NOT PROVIDED 	Exception message: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions  -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.12, Azul Systems, Inc. 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc. 	Memory: 556077424 bytes (530 MiB) / 1157627904 bytes (1104 MiB) up to 32010928128 bytes (30528 MiB) 	CPUs: 12 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 5 3600 6-Core Processor               	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0 	Microarchitecture: Zen 2 	Frequency (GHz): 3.60 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x2489 	Graphics card #0 versionInfo: DriverVersion=32.0.15.6590 	Memory slot #0 capacity (MB): 16384.00 	Memory slot #0 clockSpeed (GHz): 3.00 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 16384.00 	Memory slot #1 clockSpeed (GHz): 3.00 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 48589.36 	Virtual memory used (MB): 12558.20 	Swap memory total (MB): 15872.00 	Swap memory used (MB): 0.00 	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx30528M 	Sinytra Connector: 1.0.0-beta.46+1.20.1 		SINYTRA CONNECTOR IS PRESENT! 		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker. 		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues. 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		loader-47.2.2.jar slf4jfixer PLUGINSERVICE  		loader-47.2.2.jar object_holder_definalize PLUGINSERVICE  		loader-47.2.2.jar runtime_enum_extender PLUGINSERVICE  		loader-47.2.2.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		loader-47.2.2.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE  	FML Language Providers:  		kotlinforforge@4.11.0 		lowcodefml@47.2 		minecraft@47.2 		javafml@47.2 	Mod List:  		fabric-transfer-api-v1-3.3.5+631c9cd677.jar       |Fabric Transfer API (v1)      |fabric_transfer_api_v1        |3.3.5+631c9cd677    |NONE      |Manifest: NOSIGNATURE 		fabric-dimensions-v1-2.1.54+8005d10d77.jar        |Fabric Dimensions API (v1)    |fabric_dimensions_v1          |2.1.54+8005d10d77   |NONE      |Manifest: NOSIGNATURE 		ctov-create-structures-1.0.jar                    |CTOV - Create: Structures     |mr_ctov_createstructures      |1.0                 |NONE      |Manifest: NOSIGNATURE 		fabric-renderer-api-v1-3.2.1+1d29b44577.jar       |Fabric Renderer API (v1)      |fabric_renderer_api_v1        |3.2.1+1d29b44577    |NONE      |Manifest: NOSIGNATURE 		fabric-item-api-v1-2.1.28+4d0bbcfa77.jar          |Fabric Item API (v1)          |fabric_item_api_v1            |2.1.28+4d0bbcfa77   |NONE      |Manifest: NOSIGNATURE 		fabric-model-loading-api-v1-1.0.3+6274ab9d77.jar  |Fabric Model Loading API (v1) |fabric_model_loading_api_v1   |1.0.3+6274ab9d77    |NONE      |Manifest: NOSIGNATURE 		fabric-rendering-fluids-v1-3.0.28+4ac5e37a77.jar  |Fabric Rendering Fluids (v1)  |fabric_rendering_fluids_v1    |3.0.28+4ac5e37a77   |NONE      |Manifest: NOSIGNATURE 		fabric-screen-handler-api-v1-1.3.30+561530ec77.jar|Fabric Screen Handler API (v1)|fabric_screen_handler_api_v1  |1.3.30+561530ec77   |NONE      |Manifest: NOSIGNATURE 		fabric-models-v0-0.4.2+7c3892a477.jar             |Fabric Models (v0)            |fabric_models_v0              |0.4.2+7c3892a477    |NONE      |Manifest: NOSIGNATURE 		fabric-resource-loader-v0-0.11.10+bcd08ed377.jar  |Fabric Resource Loader (v0)   |fabric_resource_loader_v0     |0.11.10+bcd08ed377  |NONE      |Manifest: NOSIGNATURE 		fabric-rendering-v1-3.0.8+66e9a48f77.jar          |Fabric Rendering (v1)         |fabric_rendering_v1           |3.0.8+66e9a48f77    |NONE      |Manifest: NOSIGNATURE 		fabric-renderer-indigo-1.5.2+b5b2da4177.jar       |Fabric Renderer - Indigo      |fabric_renderer_indigo        |1.5.2+b5b2da4177    |NONE      |Manifest: NOSIGNATURE 		fabric-convention-tags-v1-1.5.5+fa3d1c0177.jar    |Fabric Convention Tags        |fabric_convention_tags_v1     |1.5.5+fa3d1c0177    |NONE      |Manifest: NOSIGNATURE 		fabric-mining-level-api-v1-2.1.50+561530ec77.jar  |Fabric Mining Level API (v1)  |fabric_mining_level_api_v1    |2.1.50+561530ec77   |NONE      |Manifest: NOSIGNATURE 		fabric-command-api-v1-1.2.34+f71b366f77.jar       |Fabric Command API (v1)       |fabric_command_api_v1         |1.2.34+f71b366f77   |NONE      |Manifest: NOSIGNATURE 		fabric-block-view-api-v2-1.0.1+0767707077.jar     |Fabric BlockView API (v2)     |fabric_block_view_api_v2      |1.0.1+0767707077    |NONE      |Manifest: NOSIGNATURE 		fabric-command-api-v2-2.2.13+561530ec77.jar       |Fabric Command API (v2)       |fabric_command_api_v2         |2.2.13+561530ec77   |NONE      |Manifest: NOSIGNATURE 		fabric-data-attachment-api-v1-1.0.0+30ef839e77.jar|Fabric Data Attachment API (v1|fabric_data_attachment_api_v1 |1.0.0+30ef839e77    |NONE      |Manifest: NOSIGNATURE 		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |NONE      |Manifest: NOSIGNATURE 		create_trimmed.jar                                |Create: Trimmed               |create_trimmed                |1.0.0               |NONE      |Manifest: NOSIGNATURE 		fabric-screen-api-v1-2.0.8+45a670a577.jar         |Fabric Screen API (v1)        |fabric_screen_api_v1          |2.0.8+45a670a577    |NONE      |Manifest: NOSIGNATURE 		fabric-particles-v1-1.1.2+78e1ecb877.jar          |Fabric Particles (v1)         |fabric_particles_v1           |1.1.2+78e1ecb877    |NONE      |Manifest: NOSIGNATURE 		forge-1.20.1-47.1.106-universal.jar               |NeoForge                      |forge                         |47.1.106            |NONE      |Manifest: NOSIGNATURE 		fabric-api-0.92.2+1.11.8+1.20.1.jar               |Forgified Fabric API          |fabric_api                    |0.92.2+1.11.8+1.20.1|NONE      |Manifest: NOSIGNATURE 		fabric-content-registries-v0-4.0.11+a670df1e77.jar|Fabric Content Registries (v0)|fabric_content_registries_v0  |4.0.11+a670df1e77   |NONE      |Manifest: NOSIGNATURE 		fabric-transitive-access-wideners-v1-4.3.1+1880499|Fabric Transitive Access Widen|fabric_transitive_access_widen|4.3.1+1880499877    |NONE      |Manifest: NOSIGNATURE 		elytratrims-fabric-3.5.3+1.20.1.jar               |Elytra Trims                  |elytratrims                   |3.5.3               |NONE      |Manifest: NOSIGNATURE 		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		fabric-game-rule-api-v1-1.0.40+683d4da877.jar     |Fabric Game Rule API (v1)     |fabric_game_rule_api_v1       |1.0.40+683d4da877   |NONE      |Manifest: NOSIGNATURE 		AmbientSounds_FABRIC_v6.1.1_mc1.20.1.jar          |AmbientSounds                 |ambientsounds                 |6.1.1               |NONE      |Manifest: NOSIGNATURE 		fabric-api-base-0.4.31+ef105b4977.jar             |Fabric API Base               |fabric_api_base               |0.4.31+ef105b4977   |NONE      |Manifest: NOSIGNATURE 		fabric-api-lookup-api-v1-1.6.36+67f9824077.jar    |Fabric API Lookup API (v1)    |fabric_api_lookup_api_v1      |1.6.36+67f9824077   |NONE      |Manifest: NOSIGNATURE 		fabric-blockrenderlayer-v1-1.1.41+1d0da21e77.jar  |Fabric BlockRenderLayer Regist|fabric_blockrenderlayer_v1    |1.1.41+1d0da21e77   |NONE      |Manifest: NOSIGNATURE 		CreativeCore_FORGE_v2.12.17_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.12.17             |NONE      |Manifest: NOSIGNATURE 		create-compat-betterend-betternether-1.1.jar      |Create: Compat BetterEnd & Bet|mr_create_compatbetterendbette|1.1                 |NONE      |Manifest: NOSIGNATURE 		fabric-block-api-v1-1.0.11+0e6cb7f777.jar         |Fabric Block API (v1)         |fabric_block_api_v1           |1.0.11+0e6cb7f777   |NONE      |Manifest: NOSIGNATURE 		supermartijn642corelib-1.1.12a-forge-mc1.20.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.12a             |NONE      |Manifest: NOSIGNATURE 		fabric-resource-conditions-api-v1-2.3.8+9ad825cd77|Fabric Resource Conditions API|fabric_resource_conditions_api|2.3.8+9ad825cd77    |NONE      |Manifest: NOSIGNATURE 		kffmod-4.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.11.0              |NONE      |Manifest: NOSIGNATURE 		flywheel-forge-1.20.1-0.6.11-13.jar               |Flywheel                      |flywheel                      |0.6.11-13           |NONE      |Manifest: NOSIGNATURE 		create-1.20.1-0.5.1.h.jar                         |Create                        |create                        |0.5.1.h             |NONE      |Manifest: NOSIGNATURE 		fabric-item-group-api-v1-4.0.12+c9161c2d77.jar    |Fabric Item Group API (v1)    |fabric_item_group_api_v1      |4.0.12+c9161c2d77   |NONE      |Manifest: NOSIGNATURE 		Connector-1.0.0-beta.46+1.20.1-mod.jar            |Connector                     |connectormod                  |1.0.0-beta.46+1.20.1|NONE      |Manifest: NOSIGNATURE 		fabric-biome-api-v1-13.0.13+dc36698e77.jar        |Fabric Biome API (v1)         |fabric_biome_api_v1           |13.0.13+dc36698e77  |NONE      |Manifest: NOSIGNATURE 		fabric-entity-events-v1-1.6.0+6274ab9d77.jar      |Fabric Entity Events (v1)     |fabric_entity_events_v1       |1.6.0+6274ab9d77    |NONE      |Manifest: NOSIGNATURE 		fabric-registry-sync-v0-2.3.3+1c0ea72177.jar      |Fabric Registry Sync (v0)     |fabric_registry_sync_v0       |2.3.3+1c0ea72177    |NONE      |Manifest: NOSIGNATURE 		fabric-recipe-api-v1-1.0.21+514a076577.jar        |Fabric Recipe API (v1)        |fabric_recipe_api_v1          |1.0.21+514a076577   |NONE      |Manifest: NOSIGNATURE 		fabric-loot-api-v2-1.2.1+eb28f93e77.jar           |Fabric Loot API (v2)          |fabric_loot_api_v2            |1.2.1+eb28f93e77    |NONE      |Manifest: NOSIGNATURE 		fabric-object-builder-api-v1-11.1.3+2174fc8477.jar|Fabric Object Builder API (v1)|fabric_object_builder_api_v1  |11.1.3+2174fc8477   |NONE      |Manifest: NOSIGNATURE 		fabric-rendering-data-attachment-v1-0.3.37+a6081af|Fabric Rendering Data Attachme|fabric_rendering_data_attachme|0.3.37+a6081afc77   |NONE      |Manifest: NOSIGNATURE 		fabric-networking-api-v1-1.3.11+503a202477.jar    |Fabric Networking API (v1)    |fabric_networking_api_v1      |1.3.11+503a202477   |NONE      |Manifest: NOSIGNATURE 		fabric-sound-api-v1-1.0.13+4f23bd8477.jar         |Fabric Sound API (v1)         |fabric_sound_api_v1           |1.0.13+4f23bd8477   |NONE      |Manifest: NOSIGNATURE 		fabric-message-api-v1-5.1.9+52cc178c77.jar        |Fabric Message API (v1)       |fabric_message_api_v1         |5.1.9+52cc178c77    |NONE      |Manifest: NOSIGNATURE 		fabric-lifecycle-events-v1-2.2.22+afab492177.jar  |Fabric Lifecycle Events (v1)  |fabric_lifecycle_events_v1    |2.2.22+afab492177   |NONE      |Manifest: NOSIGNATURE 		fabric-data-generation-api-v1-12.3.4+369cb3a477.ja|Fabric Data Generation API (v1|fabric_data_generation_api_v1 |12.3.4+369cb3a477   |NONE      |Manifest: NOSIGNATURE 		fabric-events-interaction-v0-0.6.2+0d0bd5a777.jar |Fabric Events Interaction (v0)|fabric_events_interaction_v0  |0.6.2+0d0bd5a777    |NONE      |Manifest: NOSIGNATURE 		createaddition-1.20.1-1.2.4e.jar                  |Create Crafts & Additions     |createaddition                |1.20.1-1.2.4e       |NONE      |Manifest: NOSIGNATURE 		fabric-key-binding-api-v1-1.0.37+561530ec77.jar   |Fabric Key Binding API (v1)   |fabric_key_binding_api_v1     |1.0.37+561530ec77   |NONE      |Manifest: NOSIGNATURE 		fabric-client-tags-api-v1-1.1.2+5d6761b877.jar    |Fabric Client Tags            |fabric_client_tags_api_v1     |1.1.2+5d6761b877    |NONE      |Manifest: NOSIGNATURE

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
