### ISSUE TITLE
Connector not working with Styled Player List

### ISSUE THREAD

**Issue by nyaukii** [Sinytra/Connector#1450]
### Mod Name

Styled Player List

### Mod Homepage

https://modrinth.com/mod/styledplayerlist

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Styled player list will not show the code in the player tab correctly when using sinytra.

### Steps to reproduce

1. Open AT Launcher
2. Create a 1.20.1 forge server in the "create pack" tab (make sure to accept the TOS in the files)
3. Install Styled Player List, Sinytra, and Forgified Fabric API into the servers mods folder
4. Go to "Create Pack", create a 1.20.1 neoforge instance (I tried normal forge before this, i had the same issue, so i tried neoforge)
5. Install Styled Player List, Sinytra, and Forgified Fabric API into the mods folder
6. Go to the instances tab and press play
7. Click multiplayer and join the LAN server
8. Push tab, youll see the issue.

![Image](https://github.com/user-attachments/assets/ba9d4f2a-c6c5-499e-be0e-63d164ce867f)
[default.json](https://github.com/user-attachments/files/17264551/default.json) the only config folder I edited to customize the playertab

### Logs

https://gist.github.com/nyaukii/5d8550371ae77962fd9b70b81c0b6943

### Additional context

I was previously using Styled Player List in a normal fabric instance in single player and it worked perfectly fine, but when I tried to use it for forge using sinytra it broke, thought I could fix it by making a server since thats the only way it would let me see the tab, and then the tab was all messed up.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
