### ISSUE TITLE
[Feature Request] API for loading fabric mods for the other mod locators

### ISSUE THREAD

**Issue by SettingDust** [Sinytra/Connector#1451]
Below is targeting 1.20.1 Forge

For now. All the logic is private in https://github.com/Sinytra/Connector/blob/1.20.1/src/main/java/org/sinytra/connector/locator/ConnectorLocator.java
My mod is adding a mod locator that will load mods from the other directory. And provide config GUI for users to disable them by [directory](https://github.com/SettingDust/ModSets/blob/main/forge/mod-locator/src/main/java/settingdust/modsets/forge/service/ModSetsModLocator.java#L45-L50) or mod ID. `connector.additionalModLocations` is lacking the folder information.
Need an API like `ConnectorLocator#addCandidates(Path... paths)` for loading the mods with connector locator.
Since connector's is the last one. It's possible to add the path in any normal mod locator

For now, I have to pass the folders to `connector.additionalModLocations` and copy(or invoking with reflection?) the `ConnectorLocator#filterPaths` and transform the jars to get the directory and mod id 

Or an API that can get original jar path from the mod info?

**Comment by Su5eD** [comment]
> connector.additionalModLocations is lacking the folder information.

What information is this exactly?

**Comment by SettingDust** [comment]
> What information is this exactly?

What's the folder the mod from. All the mods are loaded from `.connector`

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
