### ISSUE TITLE
Geckolib Fabric and Forge won't run under the same environment

### ISSUE THREAD

**Issue by FullMetalMaster** [Sinytra/Connector#1453]
### Mod Name

Geckolib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/geckolib

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Geckolib Fabric and Forge won't run under the same environment

### Steps to reproduce

1. have a geckolib required mod Critters and Companions for forge and Pokeblocks for Fabric (example)
2. load with Sinytra Connector)
3. crash mods cant determine which one to run off of
[latest.log](https://github.com/user-attachments/files/17270772/latest.log)

### Logs

file attached

**Comment by RoomAlex68** [comment]
Duplicate #231

**Comment by Su5eD** [comment]
Duplicate of #231, resolved in 1.21.1
