### ISSUE TITLE
Sinytra Connector doesnt load/convert dependencies that are built into mod

### ISSUE THREAD

**Issue by R4llik** [Sinytra/Connector#1454]
### Mod Name

Eldritch End

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/eldritch-end

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Sinytra Connector isnt loading build into mod dependencies leading to crash

### Steps to reproduce

1. Load these mods: Eldritch End, AzureLib, Necronomicon API, Sinytra Connector, Connector Extras, Forgified Fabric API
2. Launch Minecraft
3. Crash

### Logs

Latest.log: https://gist.github.com/R4llik/9eaad93fbf0f37ce2e8986e2bc777c12 |||| Game Output Log: https://gist.github.com/R4llik/ceca7c7f2402aa25b31b74d10def408d

### Additional context

I encountered this problem while trying to run minecraft with Eldritch End. Eldritch End requires NecronomiconApi, AzureLib, Connector and AAAparticles to run. While NecronomiconApi and AzureLib need to be downloaded separately, AAAparticles are built into the mod. When you try to run minecraft with Eldritch End and all its dependencies, it crashes while loading and the only way to fix this is to download AAAparticles separately, leading to a situation where you have AAAparticles fabric that is built into Eldritch End and you have a AAAparticles forge that is loaded separately, only then will your minecraft launch.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
