### ISSUE TITLE
Weapon from SimplyMore is crashing game when using its ability near mobs

### ISSUE THREAD

**Issue by R4llik** [Sinytra/Connector#1455]
### Mod Name

Simply More

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/simply-more

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When using special ability of weapon named "Stasis" near for example iron golem or any other mob minecraft crashes

### Steps to reproduce

1.![Image](https://github.com/user-attachments/assets/db762ef0-25ea-4342-98ab-52a0415d6138)
    load these mods
2. Start your minecraft
3. Go into your world
4. Get weapon from SimplyMore named "stasis"
5. Use special ability by pressing right mouse button near any mob
6. wait for it to charge and when lightning strikes, the game crashes
...

### Logs

Latest.log: https://gist.github.com/R4llik/45244f09123169e6196fcc32211b5b5b CrashLog: https://gist.github.com/R4llik/da95c18468f576bf591b5f21de085bec

### Additional context

I have not tested any other weapons. I will try to contact the creator of the mod and ask him about this situation, maybe he will know why this is happening.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
