### ISSUE TITLE
MidnightLib Forge crash

### ISSUE THREAD

**Issue by SylisMC** [Sinytra/Connector#1456]
### Mod Name

MidnightLib

### Mod Homepage

https://github.com/TeamMidnightDust/MidnightLib

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on boot with puzzle

### Steps to reproduce

Crash on boot

**Minecraft Ver:** 1.20.1
**Loader:** Forge 47.3.0 & 47.3.5 (likely not relevant, tested on both version) 

puzzle-1.5.2+1.20 ([Modrinth](https://modrinth.com/mod/puzzle))
midnightlib-forge-1.4.2 - midnightlib-fabric-1.4.1.1 ([Modrinth](https://modrinth.com/mod/midnightlib))
fabric-api-0.92.2+1.11.8+1.20.1 (Forgified)
ConnectorExtras-1.11.2+1.20.1
Connector-1.0.0-beta.46+1.20.1

(Disabled all other mods for testing)

Replacing `midnightlib-forge-1.4.2` with `fabric-1.4.1.1`  with the fabric version resolves the crash Not sure if it will be less stable
Edit: I didn't realize the forge/fabic versions were different.. i tested midnightlib-forge-**1.4.1** and it crashed with the same result

### Logs

https://mclo.gs/KSvjyiQ

**Comment by SylisMC** [comment]
It might just be an issue with puzzle not recognizing the forge version of ML as valid. du-know. ill let you do your thing.... thanks for taking on such a huge but overwhelmingly useful project... its like putting two kids on timeout for not playing nice together

**Comment by Su5eD** [comment]
If the fabric version works fine, please use that.
