### ISSUE TITLE
Flashback crash on servers

### ISSUE THREAD

**Issue by MehVahdJukaar** [Sinytra/Connector#1457]
### Mod Name

Flashback

### Mod Homepage

https://modrinth.com/mod/flashback/version/0.11.0

### Minecraft version

1.21.1

### Describe the bug

After recording something with Flashback on a Server, viewing the recording will crash IF ANY mod that adds some packet is there. Error is thrown by forge which (supposedly) believes that such mod does not have a valid channel and thus crashes as soon as flashback tries to play a modded packet.

### Steps to reproduce

Record something on a server when having a mod that has any netowrking
view the recording and it will crash as soon as one of those packets is sent

### Logs

https://gist.github.com/MehVahdJukaar/7f1c02aa3804e3b240e63beba5602f34

**Comment by Su5eD** [comment]
Duplicate of #1452
