### ISSUE TITLE
modpack  crashes on start 

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#146]
### Describe the bug

crashes when i launch my modpack

### Steps to reproduce

1. start the pack 
2. then  it will crash
3.
...

### Additional context

logs:   
[latest.log](https://github.com/Sinytra/Connector/files/12468142/latest.log)
[debug.log](https://github.com/Sinytra/Connector/files/12468144/debug.log)

**Comment by Su5eD** [comment]
Please identify the mod(s) causing the crash. Try removing half of the current mods until you find it.
