### ISSUE TITLE
Spectrum causing crash

### ISSUE THREAD

**Issue by Dawnwhisper213** [Sinytra/Connector#1463]
### Mod Name

Spectrum

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/spectrum

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Game crashes on launch

### Steps to reproduce

1. launch game
2. crash
3. profit?
...

### Logs

[crash-2024-10-10_17.40.37-client.txt](https://github.com/user-attachments/files/17335031/crash-2024-10-10_17.40.37-client.txt)

### Additional context

[crash-2024-10-10_17.40.37-client.txt](https://github.com/user-attachments/files/17335031/crash-2024-10-10_17.40.37-client.txt)

**Comment by Dawnwhisper213** [comment]
I just removed Create, this seemed to fix it. i'd like to have both, if anyone knows the solution here

**Comment by tlitookilakin** [comment]
You **can** have both, but you have to either use the fabric version of create, **or** disable spectrum's create integration in the config.
When spectrum's create integration is enabled, it sees that create is installed, and tries to patch it like it's the fabric version of create, which it isn't, and that causes the crash.
Spectrum has the same issue integrating traveler's backpack. I don't think there's anything Connector can do about this.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
