### ISSUE TITLE
Connector (ver. 1.0.0-beta.46+1.20.1) doesn't seem to work on Linux (!Pop_OS 22.04)

### ISSUE THREAD

**Issue by DabGias** [Sinytra/Connector#1465]
### Minecraft version

1.20.1

### Describe the bug

Connector (ver. 1.0.0-beta.46+1.20.1) doesn't seem to work on Linux (!Pop_OS 22.04 LTS)

### Steps to reproduce

1. Install Steampunk [LPS] - 1.20 Update from CurseForge on !Pop_OS 22.04 LTS using PrismLauncher
2. Launch Steampunk instance

### Logs

https://gist.github.com/DabGias/9333ec0c8faa3538e2343747835cfafd

### Additional context

The game seems to crash after trying to render a mod related to AAAParticles. In my case it crashes and presents these mods: [eldritch_end, aaa_particles, betterend, wunderlib, bclib], as these mods are Fabric mods. After removing the mentioned mods, the game runs without any crashes, but after clicking on "Singleplayer" Minecraft instantly crashes. I tested The Pixelmon Mod 1.16.5-9.1.12 (from CurseForge) and worked fine, so I guess the problem isn't related to my launcher. My friends can run the game with no issues on Windows. I didn't test any other modpack with Connector. After installing the AAAParticles mod the error doesn't pop up anymore, but the game still crashes with other errors.

**Comment by Su5eD** [comment]
Please post the full log

**Comment by DabGias** [comment]
> Please post the full log

just updated the log, after some review it seems like its a problem related to glibc (`version GLIBC_2.38 not found (required by /SteamPunk [LPS] - 1.20 Update!/minecraft/libEffekseerNativeForJava.so)`). After some research it looks like to be a problem with my glibc and OS version, as my distro is a LTS it doesn't have the bleeding edge updates.
