### ISSUE TITLE
Fabric mod discovery failed issue

### ISSUE THREAD

**Issue by ChiefAstronuat** [Sinytra/Connector#1467]
### Mod Name

sodium-fabric-0.5.11+mc1.21.jar

### Mod Homepage

https://modrinth.com/mod/sodium

### Minecraft version

1.21.1

### Describe the bug

Fabric mod discovery failed

### Steps to reproduce

connector-2.0.0-beta.3+1.21.1-full.jar
forgified-fabric-api-0.104.0+2.0.15+1.21.1.jar
ConnectorExtras-1.12.1+1.21.1.jar
sodium-fabric-0.5.11+mc1.21.jar

include this mod and run neoforge

### Logs

https://pastebin.com/RkU3a8Lw

**Comment by kakashi1464** [comment]
sodium is available for neoforge

**Comment by Tapacywka** [comment]
Use Sodium Beta 0.6 for NeoForge instead of using the Fabric one :/

**Comment by ChiefAstronuat** [comment]
It's quite possible, but I can't apply nvidium
In this case, is it faster to talk to nvidium developers?
Is it faster to talk to sodium developers?
or is it faster to talk to this place that has fabric compatible technology?
I know this is greedy
Sorry for writing it here

**Comment by kakashi1464** [comment]
> It's quite possible, but I can't apply nvidium In this case, is it faster to talk to nvidium developers? Is it faster to talk to sodium developers? or is it faster to talk to this place that has fabric compatible technology? I know this is greedy Sorry for writing it here

try embeddium instead of sodium (don't forget to override the dependency for nvidium)
