### ISSUE TITLE
Crash with Forge 1.20.1 version 47.3.0

### ISSUE THREAD

**Issue by SuperStefan97** [Sinytra/Connector#1469]
### Mod Name

BCLib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bclib

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Incompatibility with Forge 47.3.0

### Steps to reproduce

1. Play with Neo version forge-1.20.1-47.1.106
2. Works fine
3. Newer mods or updated ones for Forge (example, Create version 0.5.1.i) need the latest stable Forge version 
4. Install Forge 47.3.0
5. The game that used to work now crashed on start up
...

### Logs

https://gist.github.com/SuperStefan97/3425ffbcac8f4381922ec3612fdbbb13

### Additional context

I know you are moving from 1.20 to 1.21. But 1.20.1 version is still widely played the same as mods like Create and BCLib (with Better Nether/End), so if there can't be a fix on your end, could you tell me what Forge version seems to be the latest to work with Sinytra? Thank you in advance

**Comment by Su5eD** [comment]
I recommend using Forge 47.1.3. Some of its newer versions might work, too.
