### ISSUE TITLE
Enchancement crash on startup

### ISSUE THREAD

**Issue by Nokunami** [Sinytra/Connector#1470]
### Mod Name

Enchancement

### Mod Homepage

https://modrinth.com/mod/enchancement

### Minecraft version

1.21.1

### Describe the bug

Crashes on startup

### Steps to reproduce

1. Install Connector, FFAPI, Connector Extras and Enchancement
2. Launch the game
3. Crashed
...

### Logs

https://mclo.gs/jRMoxda

**Comment by Su5eD** [comment]
Duplicate of #1068
