### ISSUE TITLE
[1.21.1] Jade crashes with the Flashback mod.

### ISSUE THREAD

**Issue by VOLKOUL** [Sinytra/Connector#1472]
### Mod Name

Jade and Flashback

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/jade / https://modrinth.com/mod/flashback

### Minecraft version

1.21.1

### Describe the bug

When entering a replay the game will crash. I was asked by the Jade developer to report this here.

### Steps to reproduce

1. Record a replay.
2. Enter said replay.
3. Crash.
...

### Logs

https://mclo.gs/pJu5nm2 (Go to line 878, ignore resource pack spam plz)

### Additional context

Jade GitHub Report: https://github.com/Snownee/Jade/issues/477

**Comment by Su5eD** [comment]
Merging with #1457
