### ISSUE TITLE
Applied Energistics 2 Forge Version Incompatability

### ISSUE THREAD

**Issue by ghost** [Sinytra/Connector#1473]
### Mod Name

Applied Energistics 2 ( Forge )

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Text becomes squares and not readable.

### Steps to reproduce

1. Download AE2 with Connector, Connector Extras
2.Launch the game

3. Get buggy errors
...

### Logs

https://gist.github.com/N2K2021/0dc06153a007e78dd745ee811000c0b5

**Comment by ghost** [comment]
![Image](https://github.com/user-attachments/assets/b66992c2-5c48-44f1-963b-45b4eb4c86fc)

**Comment by RoomAlex68** [comment]
Dashloader is incompatible with Connector

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
