### ISSUE TITLE
curseforge moderation striking due to fabric mod with sinytra installed

### ISSUE THREAD

**Issue by VaporeonScripts** [Sinytra/Connector#1474]
i get striked due to having a fabric mod (continuity) in my mods folder altough i have sinytra, they told me to ask there
![Image](https://github.com/user-attachments/assets/116a5e4a-4b30-45c5-be9c-8683bba00cff)

**Comment by VaporeonScripts** [comment]
neoforge 1.21.1 .69, latest sinytra

**Comment by coco875** [comment]
curseforge moment where the dev of connector can't do so much to fix it

**Comment by VaporeonScripts** [comment]
so what can i do?

**Comment by Su5eD** [comment]
Unfortunately this is outside our control. I recommend asking in the [CurseForge Dev](https://discord.gg/Q4bB5zE75f) discord.
