### ISSUE TITLE
Crash with Hybrid Aquatic

### ISSUE THREAD

**Issue by Redls07** [Sinytra/Connector#1478]
### Mod Name

Hybrid Aquatic

### Mod Homepage

https://modrinth.com/mod/hybrid-aquatic

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash

### Steps to reproduce

1. Launch the game with the following mods (Forge 47.3.6):
   1) Hybrid Aquatic 1.3.5
   2) geckolib-fabric-1.20.1-4.4.9
   3) Connector-1.0.0-beta.46+1.20.1
   4) fabric-api-0.92.2+1.11.8+1.20.1
   5) fabric-language-kotlin-1.12.3+kotlin.2.0.21
2. Crash

### Logs

https://gist.github.com/Redls07/54031a1f66c7c2821f3c15c9820db6cf

### Additional context

I've seen crashes with this mod from other users who wrote about it here. Changing the forge version of geckolib to the fabric version helped someone, which I did. But it didn't help me.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
