### ISSUE TITLE
Incompatibility with neep meat

### ISSUE THREAD

**Issue by hedkne43rei0pow** [Sinytra/Connector#1479]
### Mod Name

Neep meat

### Mod Homepage

https://modrinth.com/mod/neepmeat

### Minecraft version

1.20.1 (LTS)

### Describe the bug

neep meat crash

### Steps to reproduce

1. install Sinytra Connector and neep meat
2. run
3. crash
...

### Logs

n/a

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
