### ISSUE TITLE
C2ME freezes default worldgen at 0% (does not affect superflat world)

### ISSUE THREAD

**Issue by lzm11111111** [Sinytra/Connector#1480]
### Mod Name

C2ME

### Mod Homepage

https://modrinth.com/mod/c2me-fabric

### Minecraft version

1.21.1

### Describe the bug

When trying to generate a default world the loading progress get stuck at 0%, even if I waited 30 minutes, the world still didn't load, super flat world works fine

### Steps to reproduce

1. Installing connector, FFAPI and latest version of C2ME
2. Try to generate a world
3. Get stuck at 0%

### Logs

There doesn't seen to be any error on log and the game nor crash, the world just simply not load

https://paste.ubuntu.com/p/5n3KymJV3d/

### Additional context

Neoforge version: 21.1.71

Modlist (I only installed 4 mods, no other mods are installed, including sodium): 
c2me-fabric-mc1.21.1-0.3.0+alpha.0.290.jar
connector-2.0.0-beta.3+1.21.1-full.jar
ConnectorExtras-1.12.1+1.21.1.jar
forgified-fabric-api-0.104.0+2.0.15+1.21.1.jar

**Comment by coco875** [comment]
need a log or a crash report to know why and I try connector+c2me on my computer and it work

**Comment by lzm11111111** [comment]
> need a log or a crash report to know why and I try connector+c2me on my computer and it work

There doesn't seen to be any error on log and the game nor crash, the world just simply not load
