### ISSUE TITLE
Spellblades and such

### ISSUE THREAD

**Issue by R4llik** [Sinytra/Connector#1482]
### Mod Name

Spellblades and such

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/spellblade-next

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Spellblades and such in combination with apotheosis crash game on joining world

### Steps to reproduce

1. Load both Spellblades and such and Apotheosis
2. Start joining world
3. crash
...

### Logs

1 - https://gist.github.com/R4llik/3dfffc4512325490db5e19e0b9b0230d 2 - https://gist.github.com/R4llik/6ca6c039310bacd2c18e7531c4bffd14

**Comment by RexkUr** [comment]
bump

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
