### ISSUE TITLE
Data Attributes: Directors Cut crashes during initialization

### ISSUE THREAD

**Issue by Cpt0range** [Sinytra/Connector#1484]
### Mod Name

Data Attributes: Directors Cut

### Mod Homepage

https://modrinth.com/mod/data-attributes-directors-cut

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash during initialization

### Steps to reproduce

1. Install [Connector 1.0.0-beta.46+1.20.1](https://modrinth.com/mod/connector/version/1.0.0-beta.46+1.20.1) and [[1.20.1] Forgified Fabric API 0.92.2+1.11.8+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.92.2+1.11.8+1.20.1)
2. Install [Data Attributes: Directors Cut 2.0.2+1.20.1-fabric](https://modrinth.com/mod/data-attributes-directors-cut/version/2.0.2+1.20.1-fabric) with its Dependencies [Fabric Language Kotlin 1.12.3+kotlin.2.0.21](https://modrinth.com/mod/fabric-language-kotlin/version/1.12.3+kotlin.2.0.21)
3. try to start the game
4. experience the wonders of looking at crash logs

### Logs

https://pastebin.com/3pCwN28E

### Additional context

i know there is another issue(#699 ) where its fixed from the mods end but as evident by crash log its not
btw i tired with the version mentioned in #699 and that also crashes in the exact same way

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
