### ISSUE TITLE
Crashed upon startup

### ISSUE THREAD

**Issue by mas6y6** [Sinytra/Connector#1485]
### Minecraft version

1.20.1

### Describe the bug

Crashes

### Steps to reproduce

1. Just run it
2.
3.
...

### Logs

https://gist.github.com/mas6y6/4950f7df4aa8d38a98022c79707a272b

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
