### ISSUE TITLE
[ 1.21.1 ]  与 Oritech 不兼容 in Arclight

### ISSUE THREAD

**Issue by windy664** [Sinytra/Connector#1486]
### Mod Name

Arclight

### Mod Homepage

https://www.mcmod.cn/class/3060.html

### Minecraft version

1.21.1

### Describe the bug

无法启动

### Steps to reproduce

1.
2.
3.
...

### Logs

https://paste.helpch.at/ubeweyucom.bash

**Comment by windy664** [comment]
好像不是arc不兼容，是装了 https://www.mcmod.cn/class/15500.html 这个mod后跑不了

**Comment by Su5eD** [comment]
Custom server APIs (such as Mohist, Magma, Arclight) are not supported. This also applies to launchers for mobile platforms (Pojav, FoldCraft) and pirated launchers.

Such platforms provide unpredictable environments in which mods might not function as expected, and therefore we can't provide support for them. Ensuring mod compatibility is the platform's duty, just like Connector tries its best to achieve parity when running Fabric mods on Forge.

This is explained in our [FAQ](https://github.com/Sinytra/Connector/discussions/689).
