### ISSUE TITLE
[1.20.1] Can't create singleplayer world

### ISSUE THREAD

**Issue by Kaixon986** [Sinytra/Connector#1487]
### Mod Name

Sinytra Connector

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

### Minecraft version

1.20.1 (LTS)

### Describe the bug

I can't create a singleplayer world

### Steps to reproduce

1. I go on minecraft menu (everything working fine)
2. I click singleplayer
3. It says creating world
4. Then it says saving world and closes minecraft

### Logs

https://pastebin.com/b3XbQWp0

### Additional context

I downloaded the BetterMC modpack from curseforge and haven't changed anything from it

**Comment by kakashi1464** [comment]
Report crash to LunaPixelStudio discord server instead

**Comment by Kaixon986** [comment]
okay
