### ISSUE TITLE
None of the mods that say they are compatible with sinytra work with sinytra.

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [Sinytra/Connector#1489]
I honestly don't know what else to do. I've tried a bunch of mods and nothing worked. Here, I tried with copper rails.

Log:https://pastebin.com/qYvP6hPK

**Comment by liangmoe** [comment]
Your connector is outdated buddy

**Comment by Su5eD** [comment]
Please use our discord for tech support
