### ISSUE TITLE
Terrestria incorrect worldgen

### ISSUE THREAD

**Issue by vos6434** [Sinytra/Connector#149]
### Describe the bug

Desert biomes in Terrestria generate with grass blocks instead of sand.

### Steps to reproduce

Generate a new world and locate a Terrestria desert biome.
![2023-08-30_00 05 24](https://github.com/Sinytra/Connector/assets/21976486/f42d57f9-b7b5-402f-818d-29648d91a14c)

### Additional context

Terrestria is listed as verified compatible mod, should change that until this is resolved.

**Comment by tharrmeehan** [comment]
Which biome are you referring to?

![2023-08-30_19 41 53](https://github.com/Sinytra/Connector/assets/58373200/8f307438-a751-48f0-9826-55065617af6e)

**Comment by Fiz-Victor** [comment]
I've checked the wiki and assume this is not a bug, but a biome called [Outback](https://github.com/TerraformersMC/Terrestria/wiki/Outback)

**Comment by vos6434** [comment]
It bugs with Alex Mobs + Citadel added.
Without
![2023-08-31_07 56 28](https://github.com/Sinytra/Connector/assets/21976486/72e83c0e-830c-43d7-a2d8-88f202bd2025)
With
![2023-08-31_07 52 38](https://github.com/Sinytra/Connector/assets/21976486/0c633a14-a68d-4504-b292-0c07555f7b2c)

**Comment by tharrmeehan** [comment]
My screenshot was actually taken with Alex's Mobs and Citadel. I did not face any issues myself, maybe there's an incompatibility with another mod?

**Comment by Su5eD** [comment]
I managed to track down the issue to an interaction between citadel and biolith, where citadel [modifies](https://github.com/AlexModGuy/Citadel/blob/1.20/src/main/java/com/github/alexthe666/citadel/mixin/NoiseBasedChunkGeneratorMixin.java) the surface rules during worldgen and caches the result. However, later in the process, biolith [changes](https://github.com/TerraformersMC/Biolith/blob/master/src/main/java/com/terraformersmc/biolith/impl/mixin/MixinMinecraftServer.java#L88) the input of this modification, without citadel's cache being invalidated. This leads to minecraft using an outdated set of surface rules when generating terrestria biomes, creating the weird results we can see.
