### ISSUE TITLE
Compatibility issue - player movement does not follow camera with Forkcart installed

### ISSUE THREAD

**Issue by NoaHimesaka1873** [Sinytra/Connector#1492]
### Mod Name

Forkcart

### Mod Homepage

https://github.com/ImplicitSaber/Forkcart

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Player movement does not follow camera

### Steps to reproduce

1. Install the mod
2. Try to move yourself
3. PROFIT!

### Logs

https://mclo.gs/6DPOMF1

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
