### ISSUE TITLE
Game crashes when loading a specific chunk on a forge 1.20.1 moded server.

### ISSUE THREAD

**Issue by Hazenn99** [Sinytra/Connector#1493]
When entering specific area of the map it crashes entire server here is the crash report:
[crash-2024-10-22_16.29.40-server.txt](https://github.com/user-attachments/files/17484689/crash-2024-10-22_16.29.40-server.txt)

**Comment by TeQTabanca** [comment]
> When entering specific area of the map it crashes entire server here is the crash report: [crash-2024-10-22_16.29.40-server.txt](https://github.com/user-attachments/files/17484689/crash-2024-10-22_16.29.40-server.txt)

This reddit [link](https://www.reddit.com/r/admincraft/comments/wp3r87/serverhangwatchdog_detected_that_a_single_server/?rdt=48233) may provide a solution.
