### ISSUE TITLE
Was advised to submit a bug report here.

### ISSUE THREAD

**Issue by AngelOfCreation** [Sinytra/Connector#1496]
### Mod Name

Not sure.

### Mod Homepage

Not sure.

### Minecraft version

1.20.1 (LTS)

### Describe the bug

A crash related to Alex's Mobs Interactions

### Steps to reproduce

1. Exist in a world with Crimson Mosquitos or Whales from Alexs Mobs while having Alexs Mobs Interactions installed.
2. Wait until you crash.
2.
3.
...

### Logs

https://pastebin.com/NPnvh70E, https://pastebin.com/ccWA4A71

### Additional context

Full disclosure, I initially submitted this to https://github.com/CrimsonCrips/AlexsMobsInteraction but was advised that one of the two issues was related to Sinytra. I was not told which one.

Modlist can be seen here: https://github.com/CrimsonCrips/AlexsMobsInteraction/issues/37#issuecomment-2407699659

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
