### ISSUE TITLE
Keybind CFG Mod incompatibility

### ISSUE THREAD

**Issue by NuruddinPlays** [Sinytra/Connector#1497]
### Mod Name

Keybind CFG

### Mod Homepage

https://modrinth.com/mod/keybind-cfg

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The game crashes when both the Connector and Keybind CFG mods are active

### Steps to reproduce

1. Install Connector, Forgified Fabric API, and Keybind CFG
2. Launch the game
3. The game crashes when reaching the "Loading bootstrap resources" step

### Logs

https://gist.github.com/NuruddinPlays/1c2a3029693479aee35f3756af71163a

### Additional context

Forge Version: 47.3.11
Sinytra Version: Beta 46 for MC 1.20.1

**Comment by Mr-Zombii** [comment]
This will be fixed soon on KeybindCFG's side

**Comment by Mr-Zombii** [comment]
Fixed in current 1.20.1 version of KeybindConfig

https://modrinth.com/mod/keybind-cfg/version/VX0U0CHb

**Comment by NuruddinPlays** [comment]
Can confirm that it's now fixed with the 1.0.1 update!
