### ISSUE TITLE
BetterEnd+BetterNether Fabric problem (Can't Swim)

### ISSUE THREAD

**Issue by BateauSD** [Sinytra/Connector#1499]
### Mod Name

BetterEnd

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.21.1

### Describe the bug

When one or both mods installed I cant move in water it all. It stucks completely. 

### Steps to reproduce

1. Install BetterEnd+BetterNether or only one of them.
2. Run on server or in single player and try check water..
3. Results?..
...

### Logs

https://gist.github.com/BateauSD/016bed85e9502a146dd1436e5772f211

### Additional context

Both of mods itself runs completely fine and new world generation works but.. issues with water in normal world ruins everything.

**Comment by BateauSD** [comment]
Video - https://youtu.be/EXEm56rVK9Y

**Comment by DrexHD** [comment]
This is likely related to the [FabricDefaultAttributeRegistry](https://github.com/Sinytra/ForgifiedFabricAPI/blob/1.21.1/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/entity/FabricDefaultAttributeRegistry.java) api (removed the usage of that api in another mod with the same issue and the swimming issue went away, "invoking" `clinit` in modinit seems to be enough to trigger the issue). Would probably be the same for [BetterEnds usage](https://github.com/quiqueck/BetterEnd/blob/35c56c534232ded7bbb2c97b00f9e7fc221dddf4/src/main/java/org/betterx/betterend/registry/EndEntities.java#L150) (not tested).
I tried looking at [Neoforges patches](https://github.com/neoforged/NeoForge/blob/521fcedd531ea2b309e899606380aad044f4f592/patches/net/minecraft/world/entity/ai/attributes/DefaultAttributes.java.patch), [Connectors mixin](https://github.com/Sinytra/Connector/blob/ffe828ad1f79580864bc246acd4d5c9efce8e575/src/mod/java/org/sinytra/connector/mod/mixin/CommonHooksMixin.java#L7) and forgified fabric apis implementation, but couldn't figure out whats wrong.

**Comment by Hammelpilaw** [comment]
I can confirm that this issue also exists with BetterEnd mod.

**Comment by Soforak** [comment]
BetterEnd prevents moving in water
The problem comes from BetterEnd and not its dependencies

**Comment by Su5eD** [comment]
Same issue as #1502

**Comment by horse4lunch** [comment]
I was having this same issue when I updated my server. I was able to fix by running this command "/attribute @s neoforge:swim_speed base set 1"
