### ISSUE TITLE
Immersive Portals Continued isnt compatible

### ISSUE THREAD

**Issue by Elostris** [Sinytra/Connector#1504]
### Mod Name

Immersive Portals Continued 

### Mod Homepage

https://modrinth.com/mod/immersive-portals-continued

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Immersive portals works BUT if i try to add Shaders it doesnt so i installed the continued version of Immersive Portals but that isnt compatible

### Steps to reproduce

1. Get Sinytra Connector and Oculus
2. Install Immersive Portals Continued
3. Launch the game = crash
...

### Logs

https://gist.github.com/Elostris/b41f377a3bc3e7d0d83479a24388fd39

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
