### ISSUE TITLE
error transforming jar file for replay

### ISSUE THREAD

**Issue by topgunstriker** [Sinytra/Connector#1505]
### Mod Name

Replay mod

### Mod Homepage

https://modrinth.com/mod/replaymod

### Minecraft version

1.20.1 (LTS)

### Describe the bug

whenever i load up with replay i get an error that says error transforming jar file

### Steps to reproduce

1.install connector and forgified fabric
2.install replay mod
3.launch game
...

### Logs

https://gist.github.com/topgunstriker/236f6804ef9f026491c7b12967f30523

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by technokerem** [comment]
> As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

Using the latest version but getting the same error, i cant use replay mod on forge and tried every version.
