### ISSUE TITLE
they are not displayed together with shaders, smooth animation does not work

### ISSUE THREAD

**Issue by NoriTeam** [Sinytra/Connector#1506]
### Mod Name

Provi's Health Bars

### Mod Homepage

https://modrinth.com/mod/provis-health-bars

### Minecraft version

1.20.1 (LTS)

### Describe the bug

the health menu is not displayed on top of mobs if shaders are enabled, and smooth menu changes do not work even if it is enabled in the config

### Steps to reproduce

1.
2.
3.
...

### Logs

no

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
