### ISSUE TITLE
Sinytra connector doesn't work with mod menu.

### ISSUE THREAD

**Issue by MiloMiko** [Sinytra/Connector#1507]
The Mod Menu mod doesn't show up in minecraft (1.20.1)

Mod Launcher (Modrinth App):
![Image](https://github.com/user-attachments/assets/8e17fd8e-a654-4cd7-840b-c11c64517c65)
As you see, the mod is turned on.

Minecraft (In-Game):
![Image](https://github.com/user-attachments/assets/d9ee2833-8024-42b3-b662-650a82ffbdab)
The mod can't be found.

**Comment by kakashi1464** [comment]
Use https://modrinth.com/mod/better-modlist instead

**Comment by RoomAlex68** [comment]
Mod Menu is incompatible with connector because it conflicts with forge mod list screen. Your best alternatives would be to use Cataloge and Configured

**Comment by MiloMiko** [comment]
Sorry, Better Modlist doesn't work. I am using a mod called "Liberty's Villagers" which works only with mod menu. I have already messaged the mod author on github, but no response.

**Comment by 1foxy2** [comment]
do you have connector extras?

**Comment by MiloMiko** [comment]
Yes, I do.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
