### ISSUE TITLE
Connector is incompatible with dank storage

### ISSUE THREAD

**Issue by Poolgs** [Sinytra/Connector#1510]
### Mod Name

Dank storage

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/dank-storage

### Minecraft version

1.21.1

### Describe the bug

fml.modloadingissue.incompatiblemod.noreason 

### Steps to reproduce

when installing dank storage with the incompatibility connector it

### Logs

https://pastebin.com/y9CKKUnx

**Comment by Su5eD** [comment]
This error comes from the mod marking itself as incompatoble with connector. In other words, the mod author has prevented it from loading when connector is installed.

Howvever, this doesn't mean the mod would actually crash if this restriction is bypassed. Please try asking the author instead. This is out of our control.

**Comment by Tonywqs** [comment]
Just replace it with the fabric version of dank storage
