### ISSUE TITLE
Alloy Forgery Crash neoforge 1.21.1

### ISSUE THREAD

**Issue by Tidoto** [Sinytra/Connector#1511]
### Mod Name

Alloy Forgery

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/alloy-forgery

### Minecraft version

1.21.1

### Describe the bug

yea it crashes during loading, i thought it was owo lib, owo lib alone runs, once i add alloy forgery it just crashes. if you get it to work with alloy forgery, try adding mythic metals and see if it works with that then too. thx!

### Steps to reproduce

1. add Connector, Add owo lib, Add alloy forgery
2. launch minecraft
3. wait for crash

### Logs

https://gist.github.com/Tidoto/2d1a480489ce3140a25169497ccf7c16

**Comment by tlitookilakin** [comment]
I'm running Connector with Alloy Forgery 2.1.2, owo 0.11.2, and mythic metals 0.19.9 and I am not experiencing startup crashes.

**Comment by Starexify** [comment]
> I'm running Connector with Alloy Forgery 2.1.2, owo 0.11.2, and mythic metals 0.19.9 and I am not experiencing startup crashes.

owo-lib 0.11.2 is for 1.20.1 Fabric not 1.21.1 .-. it shouldnt work. Also Alloy Forgery doesnt work not Mythic Metals, it could be the NeoForge version. I tried on latest 21.1.76 and doesn't work for example and crashes because some Recipe stuff.

**Comment by tlitookilakin** [comment]
Ah yeah, sorry, I misread the title. I'm on 1.20.1 not 1.21.1

**Comment by ghost** [comment]
This is a duplicate of #1340
