### ISSUE TITLE
Oh My Minecraft Client for

### ISSUE THREAD

**Issue by xiyan520** [Sinytra/Connector#1515]
### Mod Name

Oh My Minecraft Client for

### Mod Homepage

https://github.com/Nyan-Work/oh-my-minecraft-client

### Minecraft version

1.20.1 (LTS)

### Describe the bug

R key organizing crash

### Steps to reproduce

1.
2.The game crashes instantly when pressing the R key in the inventory screen
3.
...

### Logs

The game crashes instantly when pressing the R key in the inventory screen

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
