### ISSUE TITLE
doesn`t does his job

### ISSUE THREAD

**Issue by wolchi64** [Sinytra/Connector#1517]
### Mod Name

Forgified Fabric API

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/forgified-fabric-api

### Minecraft version

1.21.1

### Describe the bug

when I try to open a world it sends me a report but when I don`t use the connector all works fine

### Steps to reproduce

[disconnect-2024-11-07_20.03.01-client.txt](https://github.com/user-attachments/files/17667537/disconnect-2024-11-07_20.03.01-client.txt)
1.![Image](https://github.com/user-attachments/assets/05303d53-abea-40cf-9520-1f93fa9178e1)

2.
3.
...

### Logs

---- Minecraft Crash Report ---- // I bet Cylons wouldn't have this problem.  Time: 2024-11-07 19:54:32 Description: Mod loading failures have occurred; consult the issue messages for more details  net.neoforged.neoforge.logging.CrashReportExtender$ModLoadingCrashException: Mod loading has failed   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Mod loading issue -- Details: 	Mod file: <No mod information provided> 	Failure message: Some of your mods are incompatible with the game or each other! 		A potential solution has been determined, this may resolve your problem: 		   - Install fabric, any version. 		More details: 		   - mod Big Globe (bigglobe) 4.5.0 requires any version of fabric, which is missing! 	Mod version: <No mod information provided> 	Mod issues URL: <No issues URL found> 	Exception message: <No associated exception found>  -- System Details -- Details: 	Minecraft Version: 1.21.1 	Minecraft Version ID: 1.21.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 21.0.5, Azul Systems, Inc. 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc. 	Memory: 520279576 bytes (496 MiB) / 1509949440 bytes (1440 MiB) up to 19058917376 bytes (18176 MiB) 	CPUs: 16 	Processor Vendor: GenuineIntel 	Processor Name: 13th Gen Intel(R) Core(TM) i7-13700K 	Identifier: Intel64 Family 6 Model 183 Stepping 1 	Microarchitecture: Raptor Lake 	Frequency (GHz): 3.42 	Number of physical packages: 1 	Number of physical CPUs: 8 	Number of logical CPUs: 16 	Graphics card #0 name: NVIDIA GeForce RTX 4070 	Graphics card #0 vendor: NVIDIA 	Graphics card #0 VRAM (MiB): 12282.00 	Graphics card #0 deviceId: VideoController1 	Graphics card #0 versionInfo: 32.0.15.6590 	Graphics card #1 name: Intel(R) UHD Graphics 770 	Graphics card #1 vendor: Intel Corporation 	Graphics card #1 VRAM (MiB): 1024.00 	Graphics card #1 deviceId: VideoController2 	Graphics card #1 versionInfo: 31.0.101.4577 	Memory slot #0 capacity (MiB): 32768.00 	Memory slot #0 clockSpeed (GHz): 2.67 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MiB): 32768.00 	Memory slot #1 clockSpeed (GHz): 2.67 	Memory slot #1 type: DDR4 	Virtual memory max (MiB): 75034.27 	Virtual memory used (MiB): 17327.23 	Swap memory total (MiB): 9728.00 	Swap memory used (MiB): 0.00 	Space in storage for jna.tmpdir (MiB): available: 360477.91, total: 952892.00 	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 360477.91, total: 952892.00 	Space in storage for io.netty.native.workdir (MiB): available: 360477.91, total: 952892.00 	Space in storage for java.io.tmpdir (MiB): available: 360477.91, total: 952892.00 	Space in storage for workdir (MiB): available: 360477.91, total: 952892.00 	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx18176M 	Loaded Shaderpack: (off) 	ModLauncher: 11.0.4+main.d2e20e43 	ModLauncher launch target: forgeclient 	ModLauncher services:  		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE  		loader-4.0.31.jar slf4jfixer PLUGINSERVICE  		loader-4.0.31.jar runtime_enum_extender PLUGINSERVICE  		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE  		loader-4.0.31.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE  		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE  		modlauncher-11.0.4.jar connector_loader TRANSFORMATIONSERVICE  	FML Language Providers:  		gml@7.0.0 		kotlinforforge@5.6.0 		javafml@4.0 		lowcodefml@4.0 		minecraft@4.0 	Mod List:  		advancednetherite-neoforge-2.1.6-1.21.1.jar       |Advanced Netherite            |advancednetherite             |2.1.6               |Manifest: NOSIGNATURE 		almanac-1.21.x-neoforge-1.0.2.jar                 |Almanac                       |almanac                       |1.0.2               |Manifest: NOSIGNATURE 		appleskin-neoforge-mc1.21-3.0.5.jar               |AppleSkin                     |appleskin                     |3.0.5+mc1.21        |Manifest: NOSIGNATURE 		architectury-13.0.8-neoforge.jar                  |Architectury                  |architectury                  |13.0.8              |Manifest: NOSIGNATURE 		Atlas-Lib-1.21.0-1.1.14.jar                       |Atlas Lib                     |atlaslib                      |1.21.0-1.1.14       |Manifest: NOSIGNATURE 		azurelib-neo-1.21.1-2.3.27.jar                    |AzureLib                      |azurelib                      |2.3.27              |Manifest: NOSIGNATURE 		BetterCopper 1.21 -1.2 - neoforge.jar             |Better Copper                 |bettercopper                  |1.2.1               |Manifest: NOSIGNATURE 		carryon-neoforge-1.21.1-2.2.2.11.jar              |Carry On                      |carryon                       |2.2.2               |Manifest: NOSIGNATURE 		cloth-config-15.0.140-neoforge.jar                |Cloth Config v15 API          |cloth_config                  |15.0.140            |Manifest: NOSIGNATURE 		ColdSweat-2.3.8.jar                               |Cold Sweat                    |cold_sweat                    |2.3.8               |Manifest: NOSIGNATURE 		collective-1.21.1-7.87.jar                        |Collective                    |collective                    |7.87                |Manifest: NOSIGNATURE 		comforts-neoforge-9.0.3+1.21.1.jar                |Comforts                      |comforts                      |9.0.3+1.21.1        |Manifest: NOSIGNATURE 		common-networking-neoforge-1.0.16-1.21.1.jar      |Common Networking             |commonnetworking              |1.0.16-1.21.1       |Manifest: NOSIGNATURE 		cgl-1.21-neoforge-0.5.1.jar                       |CommonGroovyLibrary           |commongroovylibrary           |0.5.1               |Manifest: NOSIGNATURE 		configured-neoforge-1.21.1-2.6.0.jar              |Configured                    |configured                    |2.6.0               |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99 		Controlling-neoforge-1.21.1-19.0.3.jar            |Controlling                   |controlling                   |19.0.3              |Manifest: NOSIGNATURE 		coroutil-neoforge-1.21.0-1.3.8.jar                |CoroUtil                      |coroutil                      |1.21.0-1.3.8        |Manifest: NOSIGNATURE 		corpse-neoforge-1.21.1-1.1.2.jar                  |Corpse                        |corpse                        |1.21.1-1.1.2        |Manifest: NOSIGNATURE 		dynamic-fps-3.7.6+minecraft-1.21.0-neoforge.jar   |Dynamic FPS                   |dynamic_fps                   |3.7.6               |Manifest: NOSIGNATURE 		easy-villagers-neoforge-1.21.1-1.1.23.jar         |Easy Villagers                |easy_villagers                |1.21.1-1.1.23       |Manifest: NOSIGNATURE 		eatinganimation-1.21.0-6.0.1.jar                  |Eating Animation              |eatinganimation               |6.0.1               |Manifest: NOSIGNATURE 		entity_model_features_neoforge_1.21-2.2.6.jar     |Entity Model Features         |entity_model_features         |2.2.6               |Manifest: NOSIGNATURE 		entity_texture_features_neoforge_1.21.1-6.2.7.jar |Entity Texture Features       |entity_texture_features       |6.2.7               |Manifest: NOSIGNATURE 		FallingTree-1.21.1-1.21.1.2.jar                   |FallingTree                   |fallingtree                   |1.21.1.2            |Manifest: NOSIGNATURE 		FarmersDelight-1.21.1-1.2.5.jar                   |Farmer's Delight              |farmersdelight                |1.2.5               |Manifest: NOSIGNATURE 		farsightedmobs-neoforge-2.1.1-1.20.6.jar          |Farsighted Mobs               |farsightedmobs                |2.1.1               |Manifest: NOSIGNATURE 		forgeconfigapiport-neoforge-21.1.0.jar            |Forge Config API Port         |forgeconfigapiport            |21.1.0              |Manifest: NOSIGNATURE 		fabric-api-base-0.4.42+d1308ded19.jar             |Forgified Fabric API Base     |fabric_api_base               |0.4.42+d1308ded19   |Manifest: NOSIGNATURE 		fabric-block-view-api-v2-1.0.10+9afaaf8c19.jar    |Forgified Fabric BlockView API|fabric_block_view_api_v2      |1.0.10+9afaaf8c19   |Manifest: NOSIGNATURE 		fabric-renderer-api-v1-3.4.0+acb05a3919.jar       |Forgified Fabric Renderer API |fabric_renderer_api_v1        |3.4.0+acb05a3919    |Manifest: NOSIGNATURE 		fabric-rendering-data-attachment-v1-0.3.48+73761d2|Forgified Fabric Rendering Dat|fabric_rendering_data_attachme|0.3.48+73761d2e19   |Manifest: NOSIGNATURE 		ftb-library-neoforge-2101.1.5.jar                 |FTB Library                   |ftblibrary                    |2101.1.5            |Manifest: NOSIGNATURE 		ftb-ultimine-neoforge-2101.1.1.jar                |FTB Ultimine                  |ftbultimine                   |2101.1.1            |Manifest: NOSIGNATURE 		geckolib-neoforge-1.21.1-4.7.jar                  |GeckoLib 4                    |geckolib                      |4.7                 |Manifest: NOSIGNATURE 		gml-6.0.1.jar                                     |GroovyModLoader               |gml                           |6.0.1               |Manifest: NOSIGNATURE 		healingcampfire-1.21.1-6.1.jar                    |Healing Campfire              |healingcampfire               |6.1                 |Manifest: NOSIGNATURE 		immersive_aircraft-1.1.4+1.21.1-neoforge.jar      |Immersive Aircraft            |immersive_aircraft            |1.1.4+1.21.1        |Manifest: NOSIGNATURE 		iris-neoforge-1.8.0-beta.7+mc1.21.1.jar           |Iris                          |iris                          |1.8.0-beta.7+mc1.21.|Manifest: NOSIGNATURE 		ironchest-1.21-neoforge-16.0.7.jar                |Iron Chests                   |ironchest                     |1.21-neoforge-16.0.7|Manifest: NOSIGNATURE 		ironfurnaces-neoforge-1.21.1-4.2.6.jar            |Iron Furnaces                 |ironfurnaces                  |4.2.6               |Manifest: NOSIGNATURE 		Jade-1.21.1-NeoForge-15.8.2.jar                   |Jade                          |jade                          |15.8.2+neoforge     |Manifest: NOSIGNATURE 		jei-1.21.1-neoforge-19.21.0.247.jar               |Just Enough Items             |jei                           |19.21.0.247         |Manifest: NOSIGNATURE 		kffmod-5.6.0.jar                                  |Kotlin For Forge              |kotlinforforge                |5.6.0               |Manifest: NOSIGNATURE 		letmedespawn-1.21.x-neoforge-1.4.4.jar            |Let Me Despawn                |letmedespawn                  |1.4.4               |Manifest: NOSIGNATURE 		luggage-1.21-1.6.7.jar                            |Luggage                       |luggage                       |1.21-1.6.7          |Manifest: NOSIGNATURE 		client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		moonlight-1.21-2.15.11-neoforge.jar               |Moonlight Lib                 |moonlight                     |1.21-2.15.10        |Manifest: NOSIGNATURE 		MouseTweaks-neoforge-mc1.21-2.26.1.jar            |Mouse Tweaks                  |mousetweaks                   |2.26.1              |Manifest: NOSIGNATURE 		NaturesCompass-1.21.1-3.0.3-neoforge.jar          |Nature's Compass              |naturescompass                |1.21.1-3.0.2-neoforg|Manifest: NOSIGNATURE 		neoforge-21.1.74-universal.jar                    |NeoForge                      |neoforge                      |21.1.74             |Manifest: NOSIGNATURE 		notenoughanimations-neoforge-1.7.6-mc1.21.jar     |NotEnoughAnimations           |notenoughanimations           |1.7.6               |Manifest: NOSIGNATURE 		pipez-neoforge-1.21.1-1.2.17.jar                  |Pipez                         |pipez                         |1.21.1-1.2.17       |Manifest: NOSIGNATURE 		Powah-6.1.0.jar                                   |Powah                         |powah                         |6.1.0               |Manifest: NOSIGNATURE 		primalwinter-neoforge-1.21.1-6.0.2.jar            |Primal Winter                 |primalwinter                  |6.0.2               |Manifest: NOSIGNATURE 		reeses-sodium-options-neoforge-1.8.0-beta.4+mc1.21|Reese's Sodium Options        |reeses_sodium_options         |1.8.0-beta.4+mc1.21.|Manifest: NOSIGNATURE 		Resourcify (1.21-1.21.1-neoforge)-1.5.1.jar       |Resourcify                    |resourcify                    |1.5.1               |Manifest: NOSIGNATURE 		Searchables-neoforge-1.21.1-1.0.2.jar             |Searchables                   |searchables                   |1.0.2               |Manifest: NOSIGNATURE 		simpleplanes-1.21.1-5.3.4.jar                     |Simple Planes                 |simpleplanes                  |5.3.4               |Manifest: NOSIGNATURE 		simple_guns_reworked-1.0.0-neoforge-1.21.1.jar    |SImple_Guns_Reworked          |simple_guns_reworked          |1.0.0               |Manifest: NOSIGNATURE 		smallships-neoforge-1.21.1-2.0.0-b1.5.jar         |Small Ships                   |smallships                    |2.0.0-b1.5          |Manifest: NOSIGNATURE 		sodium-neoforge-0.6.0-beta.4+mc1.21.1.jar         |Sodium                        |sodium                        |0.6.0-beta.4+mc1.21.|Manifest: NOSIGNATURE 		sodiumdynamiclights-neoforge-1.0.9-1.21.1.jar     |Sodium Dynamic Lights         |sodiumdynamiclights           |1.0.9               |Manifest: NOSIGNATURE 		sodium-extra-neoforge-0.6.0-beta.3+mc1.21.1.jar   |Sodium Extra                  |sodium_extra                  |0.6.0-beta.3+mc1.21.|Manifest: NOSIGNATURE 		sodiumoptionsapi-neoforge-1.0.5-1.21.1.jar        |Sodium Options API            |sodiumoptionsapi              |1.0.5               |Manifest: NOSIGNATURE 		sophisticatedbackpacks-1.21-3.20.19.1124.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.19             |Manifest: NOSIGNATURE 		sophisticatedcore-1.21-0.6.47.728.jar             |Sophisticated Core            |sophisticatedcore             |0.6.47              |Manifest: NOSIGNATURE 		spectrelib-neoforge-0.17.2+1.21.jar               |SpectreLib                    |spectrelib                    |0.17.2+1.21         |Manifest: NOSIGNATURE 		squatgrow-neoforge-21.1.0+mc1.21.1.jar            |Squat Grow                    |squatgrow                     |21.1.0+mc1.21.1     |Manifest: NOSIGNATURE 		Storage Drawers-neoforge-1.21-13.8.2.jar          |Storage Drawers               |storagedrawers                |13.8.2              |Manifest: NOSIGNATURE 		supplementaries-1.21-3.0.8-alpha-neoforge.jar     |Supplementaries               |supplementaries               |1.21-3.0.5-alpha    |Manifest: NOSIGNATURE 		The-Hordes-1.21-1.6.1b.jar                        |The Hordes                    |hordes                        |1.6.1b              |Manifest: NOSIGNATURE 		watut-neoforge-1.21.0-1.1.4.jar                   |What Are They Up To           |watut                         |1.21.0-1.1.4        |Manifest: NOSIGNATURE 		Xaeros_Minimap_24.5.0_NeoForge_1.21.jar           |Xaero's Minimap               |xaerominimap                  |24.5.0              |Manifest: NOSIGNATURE 		XaerosWorldMap_1.39.0_NeoForge_1.21.jar           |Xaero's World Map             |xaeroworldmap                 |1.39.0              |Manifest: NOSIGNATURE 		YetAnotherConfigLib-3.6.1+1.21-neoforge.jar       |YetAnotherConfigLib           |yet_another_config_lib_v3     |3.6.1+1.21-neoforge |Manifest: NOSIGNATURE

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.
