### ISSUE TITLE
[1.20.1] [Origins Mod] | Server crash.

### ISSUE THREAD

**Issue by TeQTabanca** [Sinytra/Connector#1519]
### Mod Name

Origins

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/origins

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Normally, the Origins mod has a forge mod, but Reincarnation Origins: Werewolf mod requires the Origins mod's fabric mod.

### Steps to reproduce

1.Install Reincarnation Origins: Werewolf, Origins and Pehkui mod.
2.Run this server.
3.See errors...

### Logs

https://mclo.gs/V66eono

**Comment by AngelOfCreation** [comment]
Hold on, just to be clear, you were able to fully launch the game with origins fabric without crashing? I wasn't aware that was possible yet.

**Comment by TeQTabanca** [comment]
> Hold on, just to be clear, you were able to fully launch the game with origins fabric without crashing? I wasn't aware that was possible yet.

No, it crashes on the client side too.

[Client Log](https://mclo.gs/CCyAx8Q)

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
