### ISSUE TITLE
Failed to Initializing the Game due to issues relating to Connector unable to initialize MC Dungeons Weapons Mod, MC Dungeons Armors Mod, MC Dungeons: Enchanting Mod, MC Dungeons Artifacts Mod, RangeWeaponsAPI Mod.

### ISSUE THREAD

**Issue by MrG2kO1GitH** [Sinytra/Connector#1521]
### Mod Name

MC Java Forge: MC Dungeons mod's; MC Dungeons Artifacts, MC Dungeons Weapons, MC Dungeons Armors, MC Dungeons: Enchantmenting, RangeWeaponAPI, additional details included.

### Mod Homepage

MC Dungeons Armors:  https://modrinth.com/mod/mcda ;MC Dungeons Weapons: https://www.curseforge.com/minecraft/mc-mods/mcdw ;MC Dungeons: Enchanting: https://www.curseforge.com/minecraft/mc-mods/mc-dungeons-enchanting ;MC Dungeons Artifacts: https://modrinth.com/mod/mcdar ; RangedWeaponsAPI: https://modrinth.com/mod/ranged-weapon-api/versions?g=1.20.1

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The Game Crash were caused by multiple issues relating to certain Fabric Mods that failed to initialize on Connector Mod on the MultiMC MC Java 1.20.1 Windows 10 Home, that couldn't run MC Dungeons Weapons and among other Fabric Mods.

### Steps to reproduce

1. ASUS Vivobook 15 AMD, Windows 10 Home, MC Java 1.20.1, used Latest Forge Mod Loader on MultiMC with Instance => Settings. Turned on Java Installation: C:/Program Files/Java/jdk-23/bin/javaw.exe. 
2. Download list of mods: Architectury by shedaniel ;[Better Combat](https://github.com/ZsoltMolnarrr/BetterCombat) by Daedelus ;betterchunkloading mod by Someaddon ; [Canary](https://www.curseforge.com/minecraft/mc-mods/canary) by AbdElAziz ; [Chunky](https://github.com/pop4959/Chunky) by pop4959 ; clientcrafting mod by Someaddon ; [Cloth Config v10 API](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/) by shedaniel ; [Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps) by Jaredlll08 ; [Connector Extras](https://github.com/Sinytra/ConnectorExtras) by Su5eD ; Connector-1.0.0-beta.46+1.20.1 ; [Cracker's Wither Storm Mod](https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod) by nonamecrackers2, Nazaru ; Cupboard utilities by Someaddon ; Dynamic View Distance Mod: https://github.com/ldtteam/DynView/ ;Embeddium by embeddedt ;EMI by Emi ; Entity Model Features by Traben ;Entity Texture Features by Traben ;[EntityCulling](https://modrinth.com/mod/entityculling) by tr7zw ; [Fabric API](https://fabricmc.net/) by FabricMC ; Ferrite Core by malte0811 ; Forgified Fabric API by FabricMC, Sinytra ; [Friends & Foes](https://github.com/Faboslav/friends-and-foes) by Faboslav ; [GeckoLib 4](http://geckolib.com/) by Gecko, Eliot, AzureDoom, DerToaster, Tslat, Witixin ; [Get It Together, Drops!](http://minecraft.curseforge.com/projects/get-it-together-drops) by bl4ckscor3 ; ImmediatelyFast by RK_01 ; Konkrete by Keksuccino ; Krypton Reforged ;[Ksyxis](https://modrinth.com/mod/ksyxis) by VidTu ; KubeJS by LatvianModder ; [Legacy4J](https://github.com/Wilyicaro/Legacy-Minecraft) by Wilyicaro ; *[MC Dungeons Armors](https://www.curseforge.com/minecraft/mc-mods/mcda) by Chronosacaria, Kluzzio, SeaOfPixels (Art), SattesKrokodil (Art), Patreons (Support) ; *MC Dungeons Artifacts by Chronosacaria, Kluzzio, SeaOfPixels (Art), SattesKrokodil (Art), Patreons (Support) ;*[MC Dungeons Weapons](https://www.curseforge.com/minecraft/mc-mods/mcdw) by Chronosacaria, Kluzzio ;*MC Dungeons: Enchanting by BackupCup, Iamnotagenius ;[Minecraft Dungeons](https://twitter.com/mde_studio) by MDEStudio MDE Official Mod Build Number 1.18 ; [Minecraft Story Mode Mod](https://mcreator.net/) by Brandon, MCreator ; [ModernFix](https://modrinth.com/mod/modernfix) by embeddedt ; [Pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui/) by Virtuoel ; Player Animator by KosmX ; Polytone by MehVahdJukaar ; *RangedWeaponAPI by Daedelus ; Rhino by latvian.dev, Mozilla ; Roughly Enough Items (REI) by shedaniel ; [Soulz New Nether Reactor Core](https://mcreator.net/) by SoulzBerry ; [TerraBlender](https://www.curseforge.com/minecraft/mc-mods/terrablender) by Adubbz ; [Xg's Story Mode Items, Armor and More ](https://mcreator.net/)by Xg787.
3. Forge Mod Loader within MultiMC was: 47.3.12. Up-to-date Forge Mod Loader; Up-to-date API's: Architecture, Fabric API, Forgified Fabric API, RangeWeapons API, KubeJS, GeckoLib 4, Konkrete...
4. No Additional Instance Settings was made; just, Java Installation on JDK version 23 (Latest) 11/08/2024 as of Writing.
...

### Logs

https://gist.github.com/MrG2kO1GitH/a86cc2be8646d27468630c89d63c60b6

### Additional context

Do not worry; you don't necessarily need to download all the other mods listed above, the main highlights were: 

* mcdw-9.0.4$mixinextras-fabric-0.2.0-beta.8_mapped_ | MixinExtras | com_github_llamalad7_mixinextr | 0.2.0-beta.8.
* mcdar-4.0.4_mapped_srg_1.20.1.jar | MC Dungeons Artifacts | mcdar  | 4.0.4
* mcde-1.6.4-1.20$glob-0.9.0_mapped_srg_1.20.1.jar | glob | com_hrakaroo_glob | 0.9.0 
* mcdw-9.0.4_mapped_srg_1.20.1.jar | MC Dungeons Weapons  | mcdw  | 9.0.4
* mcda-5.0.2_mapped_srg_1.20.1.jar | MC Dungeons Armors | mcda   | 5.0.2 
* mcde-1.6.4-1.20_mapped_srg_1.20.1.jar | MC Dungeons: Enchanting | mcde | 1.6.4-1.20
* ranged_weapon_api-1.1.4+1.20.1_mapped_srg_.20.1.j | RangedWeaponAPI  | ranged_weapon_api  | 1.1.41.20.1
* mcde-1.6.4-1.20$jankson-1.2.3_mapped_srg_1.20.1.ja | jankson  | blue_endless_jankson | 1.2.3

**Comment by Orangeboi69** [comment]
Try removing Clumps, I had the same problem and by removing Clumps by jaredlll08 stopped the crash
