### ISSUE TITLE
[1.20.1] Minecraft crashing after installing new mods

### ISSUE THREAD

**Issue by TopOnPC** [Sinytra/Connector#1522]
I recently started a playthrough on the BetterMC modpack and everything was going well until I decided to add some new mods, which then broke things once I started loading chunks that I've already explored before. A lot of blocks started being see through, and chunks were not loading in front of me until the game crashed. I'm really unsure why my game is crashing now with the new mods when it was fine before. There seem to be a few mods that are suspect, those being: 

- Fabric Renderer - Indigo (fabric_renderer_indigo)
- Xenon (xenon)
- Fabric Renderer API (v1) (fabric_renderer_api_v1)
- Continuity (continuity)

**The new mods that I have added are:** 

- [Create](https://www.curseforge.com/minecraft/mc-mods/create) and most of it's sub mods
- [Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts)
- [Axes Are Weapons](https://www.curseforge.com/minecraft/mc-mods/axes-are-weapons)
- [Durability Tooltip](https://www.curseforge.com/minecraft/mc-mods/durability-tooltip)
- [Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
- [Iron Furnaces](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
- [Lootr (Forge & NeoForge)](https://www.curseforge.com/minecraft/mc-mods/lootr)
- [Nyf's Spiders](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders)
- [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
- [Trash Cans](https://www.curseforge.com/minecraft/mc-mods/trash-cans)

If anyone can point me in the right direction I would really appreciate it! Thanks :)

**These are the 2 crash reports:**

- https://mclo.gs/AEVq1Ez
- https://mclo.gs/TWLFFo7

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
