### ISSUE TITLE
Supplementaries + Connector (NeoForge)

### ISSUE THREAD

**Issue by Obe107** [Sinytra/Connector#1523]
### Mod Name

Supplementaries

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/supplementaries

### Minecraft version

1.21.1

### Describe the bug

When using Supplementaries + Moonlight lib + Sinytra Connector + Forgified Fabric API + Connector Extras and trying to load into a world the game crashes.

### Steps to reproduce

1. Install Supplementaries, Moonlight lib, Sinytra Connector, Forgified Fabric API, Connector Extras (NeoForge 1.21.1)
2. Join / Create a world.
3. Crash

![Image](https://github.com/user-attachments/assets/2331142b-e8d2-41e8-8585-3de64e5dce21)

### Logs

https://gist.github.com/Obe107/785301736e9e09952a18f0ad3c9f9867

**Comment by JavierClassDev** [comment]
I confirm the issue, I have the same problem at the moment with the modpack Im building

**Comment by wingedseahorse** [comment]
+1 for same issue

Minecraft 1.21.1
Neoforge 21.1.76
Connector 2.0.0-beta.3
Forgified Fabric API 0.104.0+2.0.18
Moonlight Lib 1.21-2.15.14
Suplementaries 3.0.10-alpha

**Comment by Su5eD** [comment]
Works fine on Connector beta 4
