### ISSUE TITLE
Incompatibilty with Haunted Harvest

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#153]
### Describe the bug

wont load via connector

### Steps to reproduce

Install the mods and run and expect a crash

**Comment by EndangeredNayla** [comment]
not sure how to change the tag

**Comment by Su5eD** [comment]
Sorry, Quilt mods are not supported by Connector.

**Comment by Abbie5** [comment]
haunted harvest is available for both forge and fabric https://www.curseforge.com/minecraft/mc-mods/haunted-harvest/files

**Comment by Su5eD** [comment]
Ah, I looked up the wrong mod on modrinth, sorry. This is why it's good to link the mod in the issue..
