### ISSUE TITLE
Axiom on Connector doesn't properly handle its some of its packets on the client

### ISSUE THREAD

**Issue by afamiliarquiet** [Sinytra/Connector#1531]
### Mod Name

Axiom

### Mod Homepage

https://axiom.moulberry.com/

### Minecraft version

1.21.1

### Describe the bug

Axiom's packets don't seem to get handled properly on the client, it doesn't autodetect Axiom on the server and using /axiomhandshake to force detection results in Axiom features appearing momentarily before being kicked for a DecoderException

### Steps to reproduce

1. Run client and server with Axiom 4.2.0, Connector 2.0.0-beta.4+1.21.1 and FFAPI 0.104.0+2.0.18+1.21.1
2. Connect to your localhost
3. Run /whynoaxiom - It doesn't autodetect anything from the server, so it tells you the server doesn't support Axiom.
4. Run /axiomhandshake to force detection - Axiom features appear momentarily but then it immediately kicks for a Decoder exception created from failing to decode axiom:blueprint_manifest (java.lang.IndexOutOfBoundsException: readerIndex(26) + length(1) exceeds writerIndex(26): PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26))

### Logs

server debug.log: https://mclo.gs/qRASfUA client debug.log: https://mclo.gs/8M7Wipe

**Comment by Moulberry** [comment]
https://github.com/Sinytra/ForgifiedFabricAPI/pull/170

**Comment by afamiliarquiet** [comment]
Seems to be working perfectly with FFAPI 0.104.0+2.0.19+1.21.1, thank you Moulberry!
