### ISSUE TITLE
Game Crashes on Clicking the Mods Button in Menu

### ISSUE THREAD

**Issue by DarkBreaker09** [Sinytra/Connector#1533]
### Minecraft version

1.21.1

### Describe the bug

Game Crashes on Clicking the Mods Button in Menu

### Steps to reproduce

Before i start. I am using Neoforge for Mincraft 1.21.3 but i cant chose it in the drop down Menu.

1. Using Minecraft Launcher or MultiMC
2. Installing Neoforge for Minecraft 1.21.3
3. Installing any Mods
4. Clicking on the Mods Button
...

### Logs

https://pastebin.com/yW7S7mDC

### Additional context

Since i dont have much Time to Play Online and dont wont to lose my Progress i Play on Singelplayer and use just a few Mods.
The Crash happens also when there is no Mod Installed and only Neoforge is Running.
The Mods i am using cant be run in Fabric or not jet Portet for Forge.

Ram total 16GB. Ram for MC 8GB. Runing MC on Win 11. All drivers uptodate. 44 Mods Installed.

Some of the Mods can be Configered in Game as far as i know. That can be done in the Mod Tab wich you reach when clicking on the Mod Button in the Menu. But every Time when i Click the Mod Button the Game Crashes.

Adding a Screenshot and the Crashlogs from MultiMC.

![Image](https://github.com/user-attachments/assets/85087392-0fc7-483a-ba80-bfca1e8155cf)
[crash-2024-11-13_03.23.41-client.txt](https://github.com/user-attachments/files/17725338/crash-2024-11-13_03.23.41-client.txt)
[crash-2024-11-13_03.19.44-fml.txt](https://github.com/user-attachments/files/17725340/crash-2024-11-13_03.19.44-fml.txt)

**Comment by Tapacywka** [comment]
You can't use Connector with 1.21.3 version of MC yet, only 1.21.1 is supported at this time.

**Comment by DarkBreaker09** [comment]
Connector isnt Installed.

Or do you see it in the Log´s?
Or do i need it to fix that?

Sorry but i dont get you answer.

**Comment by Tapacywka** [comment]
Then what does this crash report have to do with the Connector and why did you create a topic here if you don't use it? This is the Connector github, where Connector health reports are accepted.

**Comment by DarkBreaker09** [comment]
Oh that was my mistake sorry.

In my research about Connecteri did end here and figured that it isnt for 1.21.3.

Beside i was looking for the Crash wish another Person told me is an Neoforge Bug.
So i confused where i was when i wrote the Report.

I am realy sorry.
