### ISSUE TITLE
Cinytra Connector Incompatible with Axiom 1.20.1 (Forge)

### ISSUE THREAD

**Issue by HorizonX1** [Sinytra/Connector#1534]
### Mod Name

Axiom

### Mod Homepage

https://modrinth.com/mod/axiom

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When i load my game with Sinytra Connector and FFAPI with Axiom, it crashes at booting the game

### Steps to reproduce

1. Run Axiom 4.1.1 with latest version of Cinytra and FFAPI on 1.20.1 forge
2. Game crashes in booting process
3. crash log opens
...

### Logs

https://gist.github.com/HorizonX1/b6c4851e37d972c7d9ce56daa0eee7f4

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
