### ISSUE TITLE
why does Sinatra Connector download the overloadedarmorbar-fabric mod if I have it on forge and it requires a non-existing mod what should I do

### ISSUE THREAD

**Issue by CyberFIowey** [Sinytra/Connector#1535]
Installed Fabric mods:
		| ================================================== | ============================== | ============================== | ==================== |
		| mod-updater-1.0.0_mapped_srg_1.20.1.jar            | Mod Updater                    | mod_updater                    | 1.0.0                |
		| modmenu-7.2.2_mapped_srg_1.20.1.jar                | Mod Menu                       | modmenu                        | 7.2.2                |
		| overloadedarmorbar-fabric-1.20.1-2$GBfabrictools-1 | GBfabrictools                  | gbfabrictools                  | 1.2.21.16            |
		| Big Globe-4.6.0-MC1.20.1_mapped_srg_1.20.1.jar     | Big Globe                      | bigglobe                       | 4.6.0                |
		| mod-updater-1.0.0$owo-sentinel-0.11.2+1.20_mapped_ | o?o-sentinel                   | owo_sentinel                   | 0.11.21.20           |
		| satin-1.14.0_mapped_srg_1.20.1.jar                 | Satin                          | satin                          | 1.14.0               |
		| Big Globe-4.6.0-MC1.20.1$autocodec-5.0.0_mapped_sr | autocodec                      | builderb0y_autocodec           | 5.0.0                |
		| overloadedarmorbar-fabric-1.20.1-2_mapped_srg_1.20 | Overloaded Armor Bar           | overloadedarmorbar             | 1.20.1-2             |
#@!@# Game crashed! Crash report saved to: #@!@# #path#
[18:46:44] [WARN] [FabricLoader/Resolution]: Warnings were found!
 - §Emod 'Overloaded Armor Bar' (overloadedarmorbar)§r 1.20.1-2 recommends version 1.1.7 or later of §6modupdater§r, which is missing!
	 - You should install version 1.1.7 or later of §6modupdater§r for the optimal experience.

**Comment by Su5eD** [comment]
Connector does not contain any code related to runtime file downloading.
