### ISSUE TITLE
Crashes with modpack

### ISSUE THREAD

**Issue by ikrannn** [Sinytra/Connector#154]
### Describe the bug

Modpack crashes with ONLY Sinytra and Forgified API installed

### Steps to reproduce

1. Install modpack
2. Add Sinytra & Forgified API
3. Launch game
4. Crashes with exit code 1 or something along the lines of "failed to register entity model: husk"

### Logs

https://pastebin.com/UJQXNafF

### Additional context

3dskinlayers-forge-1.5.4-mc1.20.1.jar
AI-Improvements-1.20-0.5.2.jar
alexsmobs-1.22.5.jar
almostunified-forge-1.20.1-0.6.0.jar
AmbientSounds_FORGE_v5.2.22_mc1.20.1.jar
appleskin-forge-mc1.20.1-2.5.0.jar
architectury-9.1.12-forge.jar
artifacts-forge-9.0.5.jar
AttributeFix-Forge-1.20.1-21.0.2.jar
automobility-0.4.2+1.20.1-forge.jar
awesomedungeon-forge-1.20.1-3.2.0.jar
awesomedungeonend-forge-1.20.1-3.1.1.jar
awesomedungeonnether-forge-1.20.1-3.1.1.jar
awesomedungeonocean-forge-1.20.1-3.3.0.jar
balm-forge-1.20-7.0.7.jar
BasicNetherOres-forge-1.20.1-9.1.1.jar
betterchunkloading-1.20.1-2.1.jar
bettercombat-forge-1.7.3+1.20.1.jar
BetterF3-7.0.1-Forge-1.20.1.jar
betterfpsdist-1.20.1-3.8.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
blue_skies-1.20.1-1.3.27.jar
Bookshelf-Forge-1.20.1-20.0.3.jar
caelus-forge-3.1.0+1.20.jar
canary-mc1.20.1-0.2.7.jar
carryon-forge-1.20.1-2.1.0.1.jar
cave_dweller-1.20.1-1.6.1.jar
charmofundying-forge-6.4.2+1.20.1.jar
chat_heads-0.10.20-forge-1.20.jar
Chunk Pregenerator-1.20-4.2.3.jar
chunksending-1.20.1-2.6.jar
citadel-2.4.2-1.20.1.jar
cloth-config-11.1.106-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-6.65.jar
combatroll-forge-1.2.1+1.20.1.jar
connectivity-1.20.1-4.5.jar
CorgiLib-forge-1.20.1-4.0.0.4.jar
corpse-1.20.1-1.0.5.jar
cosmeticarmorreworked-1.20.1-v1a.jar
create-1.20.1-0.5.1.d.jar
create-structures-0.1.1-1.20.1-FORGE.jar
createaddition-1.20.1-1.0.0b.jar
CreativeCore_FORGE_v2.10.34_mc1.20.1.jar
creeperoverhaul-3.0.1-forge.jar
ctov-3.3.3.jar
cupboard-1.20.1-1.8.jar
curios-forge-5.2.0-beta.3+1.20.1.jar
deeperdarker-forge-1.20.1-1.2.0.jar
doapi-1.2.6-forge.jar
doubledoors-1.20.1-5.0.jar
dragonfight-1.20.1-4.0.jar
dragonmounts-1.20.1-1.1.5.b3.jar
DungeonsArise-1.20.1-2.1.56.1-beta.jar
dungeonsenchantments-1.1.0-1.20.1.jar
dynview-1.20.1-3.9.jar
elytraslot-forge-6.3.0+1.20.1.jar
emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.4.jar
enchantmenttransfer-0.0.6-1.20.1.jar
endrem_forge-5.2.3-R-1.20.X.jar
ends_delight-1.20.1-1.0.1.jar
enlightend-5.0.6-1.20.1.jar
entityculling-forge-1.6.2-mc1.20.jar
epicpaladins-0.1.1-1.20.1-forge.jar
explorify-v1.3.0-mc1.20u1.20.1.jar
FarmersDelight-1.20.1-1.2.3.jar
farsight-1.20.1-3.3.jar
FastLeafDecay-31.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
ferritecore-6.0.0-forge.jar
flib-1.20.1-0.0.11.jar
forbidden_arcanus-1.20.1-2.2.0-beta1.jar
framework-forge-1.20.1-0.6.16.jar
friendsandfoes-forge-mc1.20.1-1.9.4.jar
ftb-chunks-forge-2001.2.0.jar
ftb-essentials-forge-2001.1.2.jar
ftb-library-forge-2001.1.3.jar
ftb-teams-forge-2001.1.4.jar
ftb-ultimine-forge-2001.1.2.jar
geckolib-forge-1.20.1-4.2.2.jar
getittogetherdrops-forge-1.20-1.3.jar
gpumemleakfix-1.20.1-1.6.jar
Guide-API-VP-1.20.1-2.2.6-alpha+20230617-1850.jar
IllagerInvasion-v8.0.2-1.20.1-Forge.jar
immersive_paintings-0.6.5+1.20.1-forge.jar
Incendium_1.20.1_v5.3.1.jar
infernalmobs-1.20.1.0.jar
InsaneLib-1.10.2-mc1.20.1.jar
irons_spellbooks-1.20.1-1.2.1.jar
Jade-1.20.1-forge-11.5.1.jar
JadeAddons-1.20.1-forge-5.2.0.jar
jei-1.20.1-forge-15.2.0.27.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
L_Enders_Cataclysm-1.29-1.20.1.jar
l2library-2.4.15.jar
letmedespawn-1.1.1.jar
letsdo-bakery-forge-1.1.2.jar
letsdo-beachparty-forge-1.1.2b.jar
letsdo-candlelight-forge-1.2.4.jar
libraryferret-forge-1.20.1-4.0.0.jar
limitedchunks-1.20.1-3.8.jar
logprot-1.20.1-3.1.jar
lootintegrations-1.20.1-3.2.jar
lootr-1.20-0.7.30.73.jar
majrusz-library-1.20.1-5.0.0.jar
majruszs-accessories-1.20.1-1.2.3.jar
majruszs-difficulty-1.20.1-1.8.0.jar
majruszs-enchantments-1.20.1-1.9.1.jar
mcw-bridges-2.1.1-mc1.20.1forge.jar
mcw-fences-1.0.7-mc1.20.1forge.jar
mes-1.2-1.20-forge.jar
MobCaptains-v2.1.2.jar
modernfix-forge-5.7.1+mc1.20.1.jar
modulargolems-2.4.12.jar
moonlight-1.20-2.8.11-forge.jar
moredragoneggs-4.0.jar
MoreMobGriefingOptions-1.20.1-2.0.4.jar
morevanillapotions-1.20.1-1.8.jar
mvs-4.0-1.20-forge.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
neruina-1.1.1-forge+1.20.jar
nether-s-exoticism-1.20.1-1.2.6.jar
Paraglider-1.20.1-1.9.0.0.jar
Pehkui-3.7.8+1.20.1-forge.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
pmmo_xp_bottles_1.20.1_v3.jar
pmmo-1.20.1-1.1.3.jar
polymorph-forge-0.49.0+1.20.1.jar
puffish_skills-0.8.0-1.20-forge.jar
PuzzlesLib-v8.0.24-1.20.1-Forge.jar
rats-8.0.6-1.20.1.jar
reds-more-structures-1.0.8-common.jar
RegionsUnexploredForge-0.5.1+1.20.1.jar
relics-1.20.1-0.4.8.3.jar
reliquary-1.20.1-2.0.36.1199.jar
repurposed_structures-7.1.3+1.20.1-forge.jar
resourcefulconfig-forge-1.20.1-2.1.0.jar
respawningshulkers-1.20.1-3.5.jar
Rex's-AdditionalStructures-1.20.x-(v.4.1.2).jar
servercore-forge-1.3.7+1.20.1.jar
Simple Weapons 1.4.3 - 1.20.1.jar
simplehats-forge-1.20.1-0.2.1.jar
SimplyHouses-1.1.4-1.20.1-forge.jar
smoothboot-mc1.20.1-0.0.3.jar
smoothchunk-1.20.1-3.1.jar
sophisticatedbackpacks-1.20.1-3.18.56.890.jar
sophisticatedcore-1.20.1-0.5.83.395.jar
sophisticatedstorage-1.20.1-0.8.46.579.jar
soundphysics-forge-1.20.1-1.1.2.jar
spark-1.10.42-forge.jar
Stackable Potions-forge-1.20.1-1.0.0.jar
stackrefill-1.20.1-4.0.jar
stalwart-dungeons-1.20.1-1.2.8.jar
Stellarity-v2-0e.jar
structure_gel-1.20.1-2.13.1.jar
structureessentials-1.20.1-3.0.jar
supplementaries-1.20-2.5.26.jar
tenshilib-1.20.1-1.7.0-forge.jar
TerraBlender-forge-1.20.1-3.0.0.169.jar
The_Undergarden-1.20.1-0.8.8.jar
toofast-1.20-0.4.3.5.jar
toolleveling-forge-1.20.1-2.0.0.jar
TreeChop-1.20.1-forge-0.18.3.jar
twilightforest-1.20.1-4.3.1809-universal.jar
u_team_core-forge-1.20.1-5.1.4.269.jar
valhelsia_core-forge-1.20.1-1.1.0.jar
Vampirism-1.20.1-1.9.1.jar
voicechat-forge-1.20.1-2.4.22.jar
waystones-forge-1.20-14.0.1.jar
Werewolves-1.20.1-1.1.0.1.jar
worldedit-mod-7.2.15.jar
WorldPreGenerator-1.20.1-4.0.0.jar
Xaeros_Minimap_23.6.3_Forge_1.20.jar
XaerosWorldMap_1.33.1_Forge_1.20.jar
xptome-1.20.1-2.1.7.jar
yawp-1.20.1-0.0.2.9-beta3-forge.jar

Also, I've tried removing mods & trying to find the specific problem, but it seems as though most structure mods, ambient sounds, sound physics, etc. are an often cause of the crash. However, I haven't been able to find out what other mods have been causing the crashes (no Optifine, Rubidium, or Oculus installed)

All of these are forge mods, there isn't a single fabric mod installed.

**Comment by Su5eD** [comment]
Can you please upload a crash report and/or the debug.log file?

**Comment by ikrannn** [comment]
There's no crash report, but here's the debug.log file: https://pastebin.com/QZ56vfp6

**Comment by tharrmeehan** [comment]
It's incompatible with CreativeCore, so duplicate of #122

**Comment by ikrannn** [comment]
I tested removing CreativeCore as well, still the same errors

**Comment by ikrannn** [comment]
Actually, I got it to work by trying again and removing CreativeCore, Ambient Sounds, & a couple of other mods (mainly structure mods)! was even able to add betterend and betternether
