### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by BassStarling** [Sinytra/Connector#1540]
### Mod Name

Embeddium

### Mod Homepage

https://modrinth.com/mod/embeddium

### Minecraft version

1.20.1 (LTS)

### Describe the bug

connector issue

### Steps to reproduce

Minecraft Luncher
Minecraft Forge 47.3.12
Version: 1.20.1

Connector usage:
C3ME

Concurrent issues
/Oculus
Embeddium

I'm sorry if this is not useful. If you need any more information, please let me know.

![Image](https://github.com/user-attachments/assets/eebc71ba-9cf4-4315-9161-28e4993984ed)

### Logs

https://gist.github.com/BassStarling/05b8431019b6ea8d1e4795c7cc398b8e

**Comment by liangmoe** [comment]
it is distant horizen with oculus issue, not even related to sinytra or embeddium

**Comment by BassStarling** [comment]
I deleted Distant horizons and it worked. Thanks for pointing this out.'

**Comment by DadamaldaDad** [comment]
You can use Distant Horizons with Oculus or Iris, as long as you have compatible versions. Oculus is currently behind Iris, so you have to downgrade Distant Horizons.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
