### ISSUE TITLE
This is a potential incompatability, feel free to close if its the mod Redirector and Connector is not involed in any way

### ISSUE THREAD

**Issue by lSherozl** [Sinytra/Connector#1542]
### Mod Name

Redirector will Cause a crash in the End when paired with Embeddium and Better End Mod, when going to the End Islands, and of course all of this is possible because Connector allows the fabric mod to be loaded, so I am posting this issue just in case. 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/redirector

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Causes a crash upon going to End Islands please refer to the report I made on their page.

### Steps to reproduce

https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/issues/164

### Logs

All Relevant logs people provided are in the reports above

**Comment by lSherozl** [comment]
https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/issues/164

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
