### ISSUE TITLE
crash client

### ISSUE THREAD

**Issue by blackvccat** [Sinytra/Connector#1543]
### Mod Name

supplementaries, oculus, c2me_client_uncapvd, copycats

### Mod Homepage

https://github.com/Sinytra/Connector/issues.

### Minecraft version

1.20.1 (LTS)

### Describe the bug

crash the game

### Steps to reproduce

1.
2.
3.
...

### Logs

in the files 

### Additional context

[错误报告-2024-11-19_19.17.07.zip](https://github.com/user-attachments/files/17814352/-2024-11-19_19.17.07.zip)

**Comment by blackvccat** [comment]
Additional context have crash report

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
