### ISSUE TITLE
My Minecraft is crashing

### ISSUE THREAD

**Issue by Mishantaaa** [Sinytra/Connector#1544]
### Mod Name

My own mod collections

### Mod Homepage

https://modrinth.com/collection/Px25fKGn

### Minecraft version

1.20.1 (LTS)

### Describe the bug

After launching minecraft, it crashes.

### Steps to reproduce

1. I've uploaded all the necessary mods to the mods folder
2. When launching the game I had some errors, which I immediately fixed (for example, some mods can not work together, such as Astrocraft at version Ad Astra 19). I removed these conflicting mods
3. After startup, minecraft loads and then crashes

[crash-2024-11-20_20.49.40-client.txt](https://github.com/user-attachments/files/17834916/crash-2024-11-20_20.49.40-client.txt)
[tl-logger8867069600650746530.txt](https://github.com/user-attachments/files/17834908/tl-logger8867069600650746530.txt)

### Logs

I uploaded files in description "Steps to reproduce"

**Comment by Bulkog** [comment]
check last lines in your crash report. [20:49:09] [WARN] [FabricLoader/Resolution]: Warnings were found!
 - §Emod 'LambDynamicLights' (lambdynlights)§r 2.3.2+1.20.1 recommends version 0.19.1 or later of §6quilt_loader§r, which is missing!
	 - You should install version 0.19.1 or later of §6quilt_loader§r for the optimal experience.
Literally means that you need LambDynamicLights 0.19.1

**Comment by Mishantaaa** [comment]
> check last lines in your crash report. [20:49:09] [WARN] [FabricLoader/Resolution]: Warnings were found!
> 
> * §Emod 'LambDynamicLights' (lambdynlights)§r 2.3.2+1.20.1 recommends version 0.19.1 or later of §6quilt_loader§r, which is missing!
>   
>   * You should install version 0.19.1 or later of §6quilt_loader§r for the optimal experience.
>     Literally means that you need LambDynamicLights 0.19.1

I deleted this mod and its dependency “mininghelmet”, but the game still keeps crashing. Can you please list all the startup errors that are waiting to be fixed?

**Comment by Mishantaaa** [comment]
I have now removed some mods, and thanks to that, minecraft started up. When creating a world, the game crashed. Here are the listed mods that I removed:
• skinrestorer
• lambydinamiclights
• ad_extenda
• mininghelmet
• astrocraft & astrocraft_compat
• embeddium

As well as the logs:
[crash-2024-11-23_22.04.26-client.txt](https://github.com/user-attachments/files/17882251/crash-2024-11-23_22.04.26-client.txt)
[latest.log](https://github.com/user-attachments/files/17882255/latest.log)

**Comment by Mishantaaa** [comment]
I missclicked ;-;

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
