### ISSUE TITLE
NEEPMeat Milk Crash (INCOMPATIBLE MOD)

### ISSUE THREAD

**Issue by LemoneJamTart** [Sinytra/Connector#1545]
### Mod Name

NEEPMeat

### Mod Homepage

https://modrinth.com/mod/neepmeat

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When attempting to use Sinytra with NEEPMeat and (NeoForge) Geckolib, one of its dependencies, the game crashes. The issue appears to be related to milk, and also occurs with the Fabric version of Geckolib.

### Steps to reproduce

1. Install NeoForge v.47.1.106
2. Install Sinytra Connector v.1.0.0-beta.46+1.20.1
3. Install Forgified Fabric API v.0.92.2+1.11.8
4. Install Geckolib (Forge, Neoforge, and Fabric-- they all have the same result) v.4.4.9
5. Install NEEPMeat v.0.7.2-beta+1.20.1
6. Launch the game
7. Cry

### Logs

https://gist.github.com/LemoneJamTart/64a3fa984a2d04f862520e00090b4eac

### Additional context

No additional context. Little sad it doesn't work with Sinytra though, seems like a cool mod.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
