### ISSUE TITLE
Crash when singleplayer

### ISSUE THREAD

**Issue by pelle-balint** [Sinytra/Connector#1548]
### Minecraft version

1.20.1 (LTS)

### Describe the bug

When I try to make a singleplayer world in steampunk 1.20.1 v8, it crashes after i press the singleplayer button on the main menu of the game

### Steps to reproduce

1.Start the game
2.Main Menu is there
3.Press SinglePlayer button
4.Crash

### Logs

https://gist.github.com/pelle-balint/530d54e1e7b96b40de04f09704c8d07c

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
