### ISSUE TITLE
Spectrum mod crashing when creating new world (MouseClicked Event Handler)

### ISSUE THREAD

**Issue by ALEILGOD** [Sinytra/Connector#1549]
### Mod Name

Spectrum

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/spectrum

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When i try to create a new world with spectrum sinytra connector and extras.. it crashes

### Steps to reproduce

1. Download Connector
2. Download Spectrum and dependencies
3. Run Minecraft
4. Create new world
5. Crash

### Logs

https://gist.github.com/ALEILGOD/9492bba79c49fb9c54b1c75504ab4b1c

### Additional context

I have Cardinal Components API installed and Embeddium

**Comment by ALEILGOD** [comment]
Spectrum version is the latest

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by ALEILGOD** [comment]
Spectrum Is only on 1.20.1, do i Need to ask spectrum team?
