### ISSUE TITLE
Andromeda mod compatibility

### ISSUE THREAD

**Issue by Su5eD** [Sinytra/Connector#155]
### Mod Name

Andromeda

### Mod Homepage

https://modrinth.com/mod/andromeda

### Describe the bug

Various crashes related to mixins

### Steps to reproduce

1. Set `enableFeatureManager` to false and `totemSettings.enableInfiniteTotem` to true in the config.

### Logs

N/A

### Additional context

Continuation of #127

**Comment by melontini** [comment]
Btw, the FireBlockMixin should also be here. It's `quickFire` in the config. https://mclo.gs/1AVegli
