### ISSUE TITLE
BetterEnd crashing 1.20.1 on startup

### ISSUE THREAD

**Issue by axtrough** [Sinytra/Connector#1550]
### Mod Name

BetterEnd

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on startup with BetterEnd.

### Steps to reproduce

1. Get the mods i have.
2. Latest of everything
3. The game crashes
...

### Logs

https://gist.github.com/axtrough/82f61bc4825f0ed326976144eec56d61

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
