### ISSUE TITLE
PolyMC

### ISSUE THREAD

**Issue by Just-ElC** [Sinytra/Connector#1552]
### Mod Name

Polymc dont work

### Mod Homepage

https://github.com/Patbox/polymania/blob/master/pack/mods/PolyMc-5.7.0-rev.188d8ee%2B1.21.1.jar

### Minecraft version

1.21.1

### Describe the bug

When I log into the server it requires the mod installed, when Polymc removes this requirement

### Steps to reproduce

1.
2.
3.
...

### Logs

Nothing is written in the logs

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
