### ISSUE TITLE
Farsight (forge) is not compatible with Antique Atlas 4

### ISSUE THREAD

**Issue by Bruskych** [Sinytra/Connector#1554]
### Mod Name

Antique Atlas 4

### Mod Homepage

https://modrinth.com/mod/antique-atlas-4

### Minecraft version

1.20.1 (LTS)

### Describe the bug

In multiplayer the atlas map does not load

### Steps to reproduce

1. Download mod for atlas, connector and farsight
2. Open the world for friends to come into your world
3. Observe that one player's map loads, but the other does not. The map is simply frozen and the new territory does not load on it![Image](https://github.com/user-attachments/assets/f8cbfa66-30b8-494f-a913-ea84ef4756d2)

### Logs

There are no logs, as this is an in-game bug.

### Additional context

I wrote to the author of the Antique Atlas 4 mod, he said that the problem is in the Farsight mod. I wrote to the author of the Farsight mod, and he said that the problem is in the connector. That's why I'm writing to you!

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
