### ISSUE TITLE
Server Running - Invalid Player Data

### ISSUE THREAD

**Issue by MrJJLand** [Sinytra/Connector#1556]
While loading into a new 1.21.1 Neoforge server, I have tested all my mods throughout the process to work with Sinytra. So far the only mods being used for Fabric are:

- Simplehats
- Trinkets
- Pure Discs - Lofi Edition
- Pure Discs - Tricky Trials
- Pure Discs - Trails & Tales 

This listing was originally using BetterEnd, but was eliminated as a part of troubleshooting.
I have tested with and without the various mods we have implemented, but the major issue is occurring only when attempting to connect to server.

Loading singleplayer is creating no issues currently, and the server is running fine according to console with no conflictions or errors.
This is only occurring when the Sinytra connector is on for Client and Server side to make mods operate.

[disconnect-2024-12-01_19.03.42-client.txt](https://github.com/user-attachments/files/17970855/disconnect-2024-12-01_19.03.42-client.txt)

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
