### ISSUE TITLE
Server Crashing when Entering certain biome

### ISSUE THREAD

**Issue by hydraslayer4285** [Sinytra/Connector#1557]
When I enter a certain biome in my BetterMC Modded server, everyone times out and the server automatically restarts. [crash-2024-12-03_05.36.18-server.txt](https://github.com/user-attachments/files/17988185/crash-2024-12-03_05.36.18-server.txt)

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
