### ISSUE TITLE
why my functional block is gone

### ISSUE THREAD

**Issue by NamelessXiaoJiang** [Sinytra/Connector#1558]
### Minecraft version

1.20.1 (LTS)

### Describe the bug

when i install the Forgified Fabric API my functional block is gone

### Steps to reproduce

1.start game

### Logs

https://gist.github.com/XiaoJiang0208/5cd8d0c60802d8d994ce1f51b04b04e1

### Additional context

![Image](https://github.com/user-attachments/assets/33b8ee76-8c06-4140-949e-3f9e65dd60e8)

**Comment by Xplodin** [comment]
what do you mean by functional block

**Comment by NamelessXiaoJiang** [comment]
All blocks in the Function Blocks category are gone
![IMG_20241204_195810.png](https://github.com/user-attachments/assets/e4656881-444c-4680-8ddc-e90fe10a898a)

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
