### ISSUE TITLE
server crash somehow

### ISSUE THREAD

**Issue by VaporeonScripts** [Sinytra/Connector#1560]
### Mod Name

connector?

### Mod Homepage

not needed

### Minecraft version

1.21.1

### Describe the bug

server crash with chunks

### Steps to reproduce

use the mod ig

### Logs

https://mclo.gs/iUu518l

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin

**Comment by VaporeonScripts** [comment]
My bad,the issue got fixed cuz I was using fabric ver of oceans delight,forge one works correctly
