### ISSUE TITLE
Crash with ExclusionLib1.0.2

### ISSUE THREAD

**Issue by fg1989** [Sinytra/Connector#1562]
### Mod Name

ExclusionLib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/exclusions-lib

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The game crashes in the menu when you try to create a new world

### Logs

https://gist.github.com/fg1989/8aca122dbd0009614c1e9fcb78cfe727

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
