### ISSUE TITLE
Crashing with Enchancement

### ISSUE THREAD

**Issue by shardskye** [Sinytra/Connector#1565]
### Mod Name

Enchancement

### Mod Homepage

https://modrinth.com/mod/enchancement

### Minecraft version

1.20.1 (LTS)

### Describe the bug

It is 

### Steps to reproduce

1. Install latest version of Sinytra Connector, Forgified Fabric API, Connector Extrass, Tooltipfix, and the latest 1.20.1 version of Enchancement
2. Launch the game
3. Crash

### Logs

https://mclo.gs/ka8Ub3y

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
