### ISSUE TITLE
Amarite (broke again)

### ISSUE THREAD

**Issue by Thysi2** [Sinytra/Connector#1567]
### Mod Name

Amarite

### Mod Homepage

https://modrinth.com/mod/amarite

### Minecraft version

1.20.1 (LTS)

### Describe the bug

crash on start

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/3VgMMp9C

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
