### ISSUE TITLE
Pick Your Poison incompatibility

### ISSUE THREAD

**Issue by Thysi2** [Sinytra/Connector#1568]
### Mod Name

Pick Your Poison

### Mod Homepage

https://modrinth.com/mod/pick-your-poison

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on start

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/ryiYXtjV

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
