### ISSUE TITLE
Character Garbling Issue with ATM9 Pack and Sinytra Connector Mod

### ISSUE THREAD

**Issue by H2Opower** [Sinytra/Connector#1569]
![Image](https://github.com/user-attachments/assets/3dcb0feb-0da9-49f7-a3e6-7f3b2ee1b920)
Hello,

I am experiencing a character garbling issue after installing the Sinytra Connector mod alongside the ATM9 pack. The issue results in all in-game characters being displayed as square-shaped gibberish, which severely hampers gameplay. Below are the details of my environment and the steps I took to reproduce the issue:

Environment:

Operating System: [Windows11 proworkstation 24h2]
Minecraft Version: [1.20.1 forge]
ATM9 Pack Version: [0.3.5]
Sinytra Connector Mod Version: [1.0.0 beta.46]
Steps to Reproduce:

Installed the latest version of the ATM9 pack.
Added the Sinytra Connector mod to the mods folder.
Launched the game and observed the character garbling in the user interface.
Expected Behavior:
The game should display characters correctly without any garbling.

Actual Behavior:
All characters are displayed as square-shaped gibberish, making it impossible to read any text in the game.

Attached Mod List:
absentbydesign-1.20.1-1.9.0.jar
Ad-Astra-Giselle-Addon-forge-1.20.1-6.15.jar
AdditionalEnchantedMiner-1.20.1-1201.1.90.jar
additionallanterns-1.1.1a-forge-mc1.20.jar
additional_lights-1.20.1-2.1.7.jar
AdvancedPeripherals-1.20.1-0.7.41r.jar
advgenerators-1.6.0.6-mc1.20.1.jar
ad_astra-forge-1.20.1-1.15.18.jar
AE2-Things-1.2.1.jar
ae2insertexportcard-1.20.1-1.3.0.jar
ae2wtlib-15.2.3-forge.jar
AEAdditions-1.20.1-5.0.6.jar
AEInfinityBooster-1.20.1-1.0.0+21.jar
aether-1.20.1-1.5.1-neoforge.jar
AI-Improvements-1.20-0.5.2.jar
aiotbotania-1.20.1-4.0.5.jar
alchemistry-1.20.1-2.3.4.jar
alchemylib-1.20.1-1.0.30.jar
allthearcanistgear-1.20.1-20.0.0.jar
allthecompressed-1.20.1-3.0.2.jar
alltheleaks-0.0.2-beta+1.20.1-forge.jar
allthemodium-1.20.1-47.1.25-2.5.1.jar
alltheores-1.20.1-47.1.3-2.2.4.jar
allthetweaks-1.20.1-47.2.20-2.3.2.jar
allthewizardgear-1.20.1-1.1.4.jar
almostunified-forge-1.20.1-0.9.4.jar
amendments-1.20-1.2.12.jar
angelring-1.20.1-2.3.1.jar
Apotheosis-1.20.1-7.4.3.jar
ApothicAttributes-1.20.1-1.3.7.jar
appleskin-forge-mc1.20.1-2.5.1.jar
Applied-Botanics-forge-1.5.0.jar
Applied-Mekanistics-1.4.2.jar
appliedenergistics2-forge-15.2.13.jar
AppliedFlux-1.20-1.1.9-forge.jar
Aquaculture-1.20.1-2.5.2.jar
architectury-9.2.14-forge.jar
arseng-1.2.0.jar
ars_creo-1.20.1-4.1.0.jar
ars_elemental-1.20.1-0.6.7.5.jar
ars_nouveau-1.20.1-4.12.6-all.jar
ars_ocultas-1.20.1-1.2.2-all.jar
artifacts-forge-9.5.13.jar
athena-forge-1.20.1-3.1.2.jar
AttributeFix-Forge-1.20.1-21.0.4.jar
balm-forge-1.20.1-7.3.9-all.jar
BambooEverything-forge-3.0.3+mc1.20.1.jar
baubley-heart-canisters-1.20.1-1.0.5.jar
bdlib-1.27.0.8-mc1.20.1.jar
BetterAdvancements-Forge-1.20.1-0.4.2.10.jar
BetterF3-7.0.2-Forge-1.20.1.jar
bettervillage-forge-1.20.1-3.2.0.jar
BiomesOPlenty-forge-1.20.1-19.0.0.91.jar
blockui-1.20.1-1.0.186-beta.jar
bloodmagic-1.20.1-3.3.3-45.jar
blueflame-1.20.0-1.0.3.jar
blue_skies-1.20.1-1.3.31.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
BorderlessWindow-1.20-1.6.0.jar
Botania-1.20.1-446-FORGE.jar
BotanyPots-Forge-1.20.1-13.0.39.jar
BotanyTrees-Forge-1.20.1-9.0.17.jar
botarium-forge-1.20.1-2.3.4.jar
BrandonsCore-1.20.1-3.2.1.302-universal.jar
buildinggadgets2-1.0.7.jar
bwncr-forge-1.20.1-3.17.1.jar
cabletiers-1.20.1-1.2.2.jar
caelus-forge-3.2.0+1.20.1.jar
caupona-1.20.1-0.4.9.jar
cc-tweaked-1.20.1-forge-1.113.1.jar
cfm-forge-1.20.1-7.0.0-pre36.jar
charginggadgets-1.11.0.jar
charmofundying-forge-6.5.0+1.20.1.jar
chemlib-1.20.1-2.0.19.jar
Chimes-v2.0.1-1.20.1.jar
chipped-forge-1.20.1-3.0.7.jar
cleanswing-1.20-1.5.jar
clickadv-1.20.1-3.8.jar
cloth-config-11.1.136-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
CodeChickenLib-1.20.1-4.4.0.516-universal.jar
cofh_core-1.20.1-11.0.2.56.jar
colorfulhearts-forge-1.20.1-4.3.16.jar
comforts-forge-6.4.0+1.20.1.jar
CommonCapabilities-1.20.1-2.9.3.jar
configuration-forge-1.20.1-3.1.0.jar
configured-forge-1.20.1-2.2.3.jar
connectedglass-1.1.12-forge-mc1.20.1.jar
connectivity-1.20.1-5.6.jar
Connector-1.0.0-beta.46+1.20.1.jar
constructionwand-1.20.1-2.11.jar
Controlling-forge-1.20.1-12.0.2.jar
cookingforblockheads-forge-1.20.1-16.0.9.jar
corail_woodcutter-1.20.1-3.0.6.jar
CorgiLib-forge-1.20.1-4.0.1.3.jar
corn_delight-1.1.6-1.20.1.jar
cosmeticarmorreworked-1.20.1-v1a.jar
crafting-on-a-stick-1.20.1-1.1.5.jar
craftingtweaks-forge-1.20.1-18.2.5.jar
crashutilities-8.1.4.jar
create-1.20.1-0.5.1.j.jar
create-confectionery1.20.1_v1.1.0.jar
create-new-age-forge-1.20.1-1.1.2.jar
createaddition-1.20.1-1.2.4e.jar
createoreexcavation-1.20-1.5.3.jar
create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.12.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.d.jar
create_jetpack-forge-4.3.2.jar
creeperoverhaul-3.0.2-forge.jar
cristellib-1.1.6-forge.jar
Croptopia-1.20.1-FORGE-3.0.4.jar
Cucumber-1.20.1-7.0.13.jar
cuisinedelight-1.1.16.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.11.0+1.20.1.jar
CyclopsCore-1.20.1-1.19.5.jar
dankstorage-forge-1.20.1-13.jar
DarkModeEverywhere-1.20.1-1.2.2.jar
DarkPaintings-Forge-1.20.1-17.0.4.jar
DarkUtilities-Forge-1.20.1-17.0.5.jar
deeperdarker-forge-1.20.1-1.3.2.jar
deepresonance-1.20-5.0.4.jar
DefaultSettings-1.20.x-4.0.7-Forge.jar
Delightful-1.20.1-3.6.jar
DimStorage-1.20.1-8.0.1.jar
Ding-1.20.1-Forge-1.4.1.jar
domum_ornamentum-1.20.1-1.0.282-snapshot-universal.jar
Draconic-Evolution-1.20.1-3.1.2.588-universal.jar
Dungeon Crawl-1.20.1-2.3.14.jar
DungeonsArise-1.20.x-2.1.58-release.jar
durabilitytooltip-1.1.5-forge-mc1.20.jar
dyenamics-1.20.1-3.2.0.jar
dyenamicsandfriends-1.20.1-1.9.0.jar
easy-villagers-forge-1.20.1-1.1.23.jar
eccentrictome-1.20.1-1.10.2.jar
EdivadLib-1.20.1-2.0.1.jar
eidolon_repraised-1.20.1-0.3.8.15.jar
elevatorid-1.20.1-lex-1.9.jar
elytraslot-forge-6.4.4+1.20.1.jar
embeddium-0.3.31+mc1.20.1.jar
EnchantingInfuser-v8.0.3-1.20.1-Forge.jar
EnchantmentDescriptions-Forge-1.20.1-17.1.19.jar
enchantmenttransfer-0.0.6-1.20.1.jar
enderchests-forge-1.20.1-1.2.jar
EnderIO-1.20.1-6.2.2-beta-all.jar
endersdelight-1.20.1-1.0.3.jar
endertanks-forge-1.20.1-1.3.jar
ends_delight-1.20.1-2.5.jar
energymeter-forge-1.20.1-1.0.0.jar
ensorcellation-1.20.1-5.0.2.24.jar
entangled-1.3.20-forge-mc1.20.4.jar
entityculling-forge-1.7.1-mc1.20.1.jar
EpheroLib-1.20.1-FORGE-1.2.0.jar
EuphoriaPatcher-1.4.3-r5.3-forge.jar
everythingcopper-1.20.1-2.3.4.jar
EvilCraft-1.20.1-1.2.48.jar
Exchangers-1.20.1-3.5.1.jar
ExtendedAE-1.20-1.2.1-forge.jar
ExtraDisks-1.20.1-3.0.2.jar
ExtraStorage-1.20.1-4.0.7.jar
ExtremeReactors2-1.20.1-2.0.88.jar
ExtremeSoundMuffler-3.48-forge-1.20.1.jar
fabric-api-0.92.2+1.11.8+1.20.1.jar
FarmersDelight-1.20.1-1.2.5.jar
farmingforblockheads-forge-1.20.1-14.0.2.jar
farsight-1.20.1-3.7.jar
FastFurnace-1.20.1-8.0.2.jar
FastLeafDecay-32.jar
FastSuite-1.20.1-5.0.1.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
findme-3.2.1-forge.jar
flavor_immersed_daily-1.0.3-forge-1.20.1.jar
flib-1.20.1-0.0.14.jar
flickerfix-1.20.1-4.0.1.jar
FluxNetworks-1.20.1-7.2.1.15.jar
forbidden_arcanus-1.20.1-2.2.6.jar
FramedBlocks-9.3.1.jar
ftb-chunks-forge-2001.3.2.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.2.5.jar
ftb-quests-forge-2001.4.9.jar
ftb-ranks-forge-2001.1.3.jar
ftb-teams-forge-2001.3.0.jar
ftb-ultimine-forge-2001.1.5.jar
ftb-xmod-compat-forge-2.1.1.jar
fuelgoeshere-1.20.0-1.0.1.jar
functionalstorage-1.20.1-1.2.12.jar
fusion-1.1.1-forge-mc1.20.1.jar
GatewaysToEternity-1.20.1-4.2.6.jar
geckolib-forge-1.20.1-4.4.9.jar
generatorgalore-1.20.1-1.2.4.jar
getittogetherdrops-forge-1.20-1.3.jar
glassential-renewed-forge-1.20.1-2.4.2.jar
GlitchCore-forge-1.20.1-0.0.1.1.jar
Glodium-1.20-1.5-forge.jar
GravitationalModulatingAdditionalUnit-1.20.1-3.2.jar
gtceu-1.20.1-1.4.6.jar
GunpowderLib-1.20.2-2.2.2.jar
handcrafted-forge-1.20.1-3.0.6.jar
harvestwithease-1.20.1-8.0.1.0-forge.jar
HostileNeuralNetworks-1.20.1-5.3.3.jar
hyperbox-1.20.1-4.0.2.0.jar
I18nUpdateMod-3.6.0-all.jar
IMBlocker_4.0.5+1.20.jar
ImmersiveEngineering-1.20.1-10.1.0-171.jar
industrial-foregoing-1.20.1-3.5.19.jar
industrial-foregoing-souls-1.20.1-1.0.9.jar
IntegratedCrafting-1.20.1-1.1.9.jar
IntegratedDynamics-1.20.1-1.23.12.jar
IntegratedTerminals-1.20.1-1.6.2.jar
IntegratedTunnels-1.20.1-1.8.31.jar
inventoryessentials-forge-1.20.1-8.2.6.jar
invtweaks-1.20.1-1.1.0.jar
ironfurnaces-1.20.1-4.1.6.jar
IronJetpacks-1.20.1-7.0.7.jar
irons_spellbooks-1.20.1-3.4.0.4.jar
item-filters-forge-2001.1.0-build.59.jar
itemcollectors-1.1.10-forge-mc1.20.jar
Jade-1.20.1-Forge-11.12.2.jar
JadeAddons-1.20.1-Forge-5.3.1.jar
JCPlugin-1.17.x-1.20.x-4.0.4-Forge.jar
jearchaeology-1.20.1-1.0.4.jar
jecharacters-1.20.1-forge-4.5.11.jar
jei-1.20.1-forge-15.20.0.105.jar
jmi-forge-1.20.1-0.14-48.jar
journeymap-1.20.1-5.10.3-forge.jar
jumpboat-1.20.0-1.0.5.jar
JustEnoughMekanismMultiblocks-1.20.1-4.5.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
justzoom_forge_2.0.0_MC_1.20.1.jar
kitchenkarrot-1.20.1-0.5.4.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.11.0-all.jar
kubejs-forge-2001.6.5-build.16.jar
laserio-1.6.8.jar
ldlib-forge-1.20.1-1.0.32.a.jar
letsdo-bakery-fabric-2.0.3.jar
libraryferret-forge-1.20.1-4.0.0.jar
LibX-1.20.1-5.0.14.jar
lionfishapi-1.9.jar
lionfishapi-2.4-Fix.jar
lithostitched-forge-1.20.1-1.3.4.jar
littlecontraptions-forge-1.20.1.2.jar
littlelogistics-mc1.20.1-v1.20.1.2.jar
logprot-1.20.1-3.4.jar
lootr-forge-1.20-0.7.34.89.jar
lostcities-1.20-7.3.5.jar
lost_aether_content-1.20.1-1.2.3.jar
L_Enders_Cataclysm-2.27_-_1.20.1.jar
macawsbridgesbop-1.20-1.3.jar
macawsroofsbop-1.20-1.1.jar
mahoutsukai-1.20.1-v1.34.78.jar
matc-1.6.0.jar
mcjtylib-1.20-8.0.6.jar
MCMOD-Forge-1.6.0+1.20.1.jar
mcw-bridges-3.0.0-mc1.20.1forge.jar
mcw-doors-1.1.1forge-mc1.20.1.jar
mcw-fences-1.1.2-mc1.20.1forge.jar
mcw-furniture-3.3.0-mc1.20.1forge.jar
mcw-lights-1.1.0-mc1.20.1forge.jar
mcw-paintings-1.0.5-1.20.1forge.jar
mcw-paths-1.0.5-1.20.1forge.jar
mcw-roofs-2.3.1-mc1.20.1forge.jar
mcw-trapdoors-1.1.3-mc1.20.1forge.jar
mcw-windows-2.3.0-mc1.20.1forge.jar
mcwfencesbop-1.20-1.2.jar
Measurements-forge-1.20.1-2.0.0.jar
megacells-forge-2.4.5-1.20.1.jar
Mekanism-1.20.1-10.4.9.61.jar
MekanismGenerators-1.20.1-10.4.9.61.jar
MekanismTools-1.20.1-10.4.9.61.jar
memorysettings-1.20.1-5.5.jar
merequester-forge-1.20.1-1.1.5.jar
minecolonies-1.20.1-1.1.732-snapshot.jar
miners_delight-1.20.1-1.2.3.jar
mininggadgets-1.15.6.jar
MobDespawnTimers-1.20.1-3.0.1.jar
mob_grinding_utils-1.20.1-1.1.0.jar
modelfix-1.15.jar
modernfix-forge-5.19.5+mc1.20.1.jar
modonomicon-1.20.1-forge-1.77.3.jar
modular-routers-12.1.1+mc1.20.1.jar
moonlight-1.20-2.13.25-forge.jar
moredragoneggs-4.0.jar
morejs-forge-1.20.1-0.10.0.jar
moreoverlays-1.22.7-mc1.20.2.jar
morered-1.20.1-4.0.0.4.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
multipiston-1.20-1.2.43-RELEASE.jar
MyServerIsCompatible-1.20-1.0.jar
mysterious_mountain_lib-1.5.17-1.20.1.jar
MysticalAgradditions-1.20.1-7.0.5.jar
MysticalAgriculture-1.20.1-7.0.14.jar
MysticalCustomization-1.20.1-5.0.2.jar
MythicBotany-1.20.1-4.0.3.jar
naturalist-forge-4.0.3-1.20.1.jar
NaturesAura-39.4.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
netherportalfix-forge-1.20-13.0.1.jar
nethersdelight-1.20.1-4.0.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
noflyzone-1.20.1-1.1.0.jar
notrample-1.20.1-1.0.1.jar
novillagerdm-1.20.1-5.0.0.jar
observable-4.4.2.jar
occultism-1.20.1-1.140.1.jar
oceansdelight-1.0.2-1.20.jar
oculus-mc1.20.1-1.7.0.jar
packetfixer-forge-1.4.2-1.19-to-1.20.1.jar
PackingTape-1.20.1-0.14.3.jar
PackMenu-1.20.1-6.1.2.jar
Paraglider-forge-20.1.3.jar
Patchouli-1.20.1-84-FORGE.jar
PigPen-Forge-1.20.1-15.0.2.jar
pipez-forge-1.20.1-1.2.16.jar
Placebo-1.20.1-8.6.2.jar
platforms-forge-1.20.1-1.1.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
pneumaticcraft-repressurized-6.0.17+mc1.20.1.jar
polyeng-forge-0.1.1-1.20.1.jar
polymorph-forge-0.49.5+1.20.1.jar
ponderjs-1.20.1-1.4.0.jar
Potion-Blender-1.20.1-FORGE-3.1.1.1.jar
potionsmaster-1.20.1-47.1.70-0.6.0.jar
Powah-5.0.7.jar
productivebees-1.20.1-12.6.0.jar
productivetrees-1.20.1-0.2.6.jar
PuzzlesLib-v8.1.25-1.20.1-Forge.jar
pylons-1.20.1-4.2.1.jar
Quark-4.0-460.jar
railcraft-reborn-1.20.1-1.1.8.jar
rangedpumps-1.1.0.jar
rebornstorage-1.20.1-5.0.7.jar
rechiseled-1.1.6-forge-mc1.20.jar
rechiseledcreate-1.0.2-forge-mc1.20.jar
redstone_arsenal-1.20.1-8.0.1.24.jar
refinedpolymorph-0.1.1-1.20.1.jar
refinedstorage-1.12.4.jar
refinedstorageaddons-0.10.0.jar
reliquary-1.20.1-2.0.44.1243.jar
repurposed_structures-7.1.15+1.20.1-forge.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.29.jar
rftoolsbase-1.20-5.0.5.jar
rftoolsbuilder-1.20-6.0.8.jar
rftoolscontrol-1.20-7.0.3.jar
rftoolspower-1.20-6.0.2.jar
rftoolsstorage-1.20-5.0.3.jar
rftoolsutility-1.20-6.0.6.jar
rhino-forge-2001.2.3-build.6.jar
RSInfinityBooster-1.20.1-1.0+39.jar
rsinsertexportupgrade-1.20.1-1.4.0.jar
rsrequestify-1.20.1-2.3.3.jar
Runelic-Forge-1.20.1-18.0.2.jar
ScalableCatsForce-3.3.1-build-0-with-library.jar
Searchables-forge-1.20.1-1.0.3.jar
serverconfigupdater-4.0.2.jar
shetiphiancore-forge-1.20.1-1.3.jar
Shrink-1.20.1-1.4.5.jar
silent-gear-1.20.1-3.6.6.jar
silent-lib-1.20.1-8.0.0.jar
SimpleBackups-1.20.1-3.1.8.jar
simplemagnets-1.1.12-forge-mc1.20.1.jar
simplylight-1.20.1-1.4.6-build.50.jar
sliceanddice-forge-3.3.0.jar
SmartBrainLib-forge-1.20.1-1.15.jar
sodiumdynamiclights-forge-1.0.9-1.20.1.jar
sodiumoptionsapi-forge-1.0.5-1.20.1.jar
solcarrot-1.20.1-1.15.1.jar
sophisticatedbackpacks-1.20.1-3.20.12.1126.jar
sophisticatedcore-1.20.1-0.7.2.756.jar
sophisticatedstorage-1.20.1-0.10.48.942.jar
spark-1.10.53-forge.jar
sparsestructuresreforged-1.20.1-1.0.0.jar
Stargate Journey-1.20.1-0.6.33.jar
Steam_Rails-1.6.7+forge-mc1.20.1.jar
Structory_1.20.x_v1.3.5.jar
StructureCompass-1.20.1-2.1.0.jar
structure_gel-1.20.1-2.16.2.jar
structurize-1.20.1-1.0.760-snapshot.jar
stylecolonies-1.10-1.20.1.jar
Super Factory Manager-1.20.1-4.19.0.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar
supplementaries-1.20-3.1.4.jar
sushigocrafting-1.20.1-0.5.3.jar
tacz-1.20.1-1.0.3-all.jar
tempad-forge-1.20.1-2.3.4.jar
TerraBlender-forge-1.20.1-3.0.1.7.jar
Terralith_1.20.x_v2.5.4.jar
ThermalExtra-3.2.0-1.20.1.jar
thermal_cultivation-1.20.1-11.0.1.24.jar
thermal_dynamics-1.20.1-11.0.1.23.jar
thermal_expansion-1.20.1-11.0.1.29.jar
thermal_foundation-1.20.1-11.0.6.70.jar
thermal_innovation-1.20.1-11.0.1.23.jar
thermal_integration-1.20.1-11.0.1.27.jar
thermal_locomotion-1.20.1-11.0.1.19.jar
theurgy-1.20.1-1.23.0.jar
The_Undergarden-1.20.1-0.8.14.jar
time-in-a-bottle-4.0.4-mc1.20.1.jar
tinyredstone-1.20-5.0.3.jar
titanium-1.20.1-3.8.32.jar
ToastControl-1.20.1-8.0.3.jar
tombstone-1.20.1-8.8.4.jar
ToolBelt-1.20.1-1.20.01.jar
torchmaster-20.1.9.jar
totw_modded-forge-1.20.1-1.0.5.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
towntalk-1.20.1-1.1.0.jar
trashcans-1.0.18b-forge-mc1.20.jar
trashslot-forge-1.20-15.1.0.jar
travelersbackpack-forge-1.20.1-9.1.16.jar
Twigs-1.20.1-3.1.0.jar
twilightdelight-2.0.13.jar
twilightforest-1.20.1-4.3.2508-universal.jar
universalgrid-1.20.1-1.1.jar
utilitarian-1.20.1-0.9.1.jar
UtilitiX-1.20.1-0.8.23.jar
valhelsia_core-forge-1.20.1-1.1.2.jar
VanillaCookbook-2.2.2.jar
villagertools-1.20.1-1.0.3.jar
Voidscape-1.20.1-1.5.389.jar
voidtotem-forge-1.20-3.0.1.jar
waystones-forge-1.20-14.1.6.jar
wirelesschargers-1.0.9a-forge-mc1.20.jar
WitherSkeletonTweaks-1.20.1-9.1.0.jar
xnet-1.20-6.1.6.jar
xnetgases-1.20.1-5.1.4.jar
YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar
YungsApi-1.20-Forge-4.0.6.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
ZeroCore2-1.20.1-2.1.47.jar
Zeta-1.0-24.jar
[1.20.1] SecurityCraft v1.9.11.jar
[forge]ctov-3.4.10.jar

Additional Information:

I have confirmed that both the ATM9 pack and Sinytra Connector mod are up to date.
I have checked the game logs for any error messages but found none related to this issue.
This issue does not occur when the Sinytra Connector mod is not installed.
I would appreciate any assistance in resolving this issue. Thank you for your time and attention.

Best regards,

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
