### ISSUE TITLE
Crash when starting game with health regeneration overhaul

### ISSUE THREAD

**Issue by SF-24** [Sinytra/Connector#1570]
### Mod Name

Health Regeneration Overhaul

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/health-regeneration-overhaul/

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Game crashes on startup

### Steps to reproduce

1. Install Synitra connector, Forgified fabric API, Health Regeneration overhaul and (Optionally) Connector Extras
2. Start Game
3. Game Crashes

### Logs

https://pastebin.com/zx47WeYL

### Additional context

Username and other sensitive information has been marked as -R-

**Comment by SF-24** [comment]
If necessary I can post the exact line of code causing the error.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
