### ISSUE TITLE
Already downloaded fabric dependency mod not being found by Sinytra when a mod calls for it, causing crash on startup.

### ISSUE THREAD

**Issue by Tkcool1** [Sinytra/Connector#1571]
### Mod Name

Sinytra Connector 1.0.0-beta.46+1.20.1 & Ratatouille 1.0.7 - 1.20.1 & Defile 1.0.0 - 1.20.1

### Mod Homepage

https://modrinth.com/mod/connector & https://modrinth.com/mod/ratatouille & https://modrinth.com/mod/defile

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When loading Defile with it's library mod, Ratatouille, Sinytra doesn't seem to recognize that Ratatouille is installed and gives an error upon startup saying that Defile requires Ratatouille which is supposedly missing in the log. Disabling Ratatouille lets minecraft boots up, but stops you, at the "error loading mods" screen, needing Ratatouille for Defile. Loading Ratatouille and Defile in fabric does not present this issue.

### Steps to reproduce

1. Have Forgified Fabric API, Sinytra Connector, and Connector Extras installed.
2. Have Ratatouille and Defile installed.
3. Launch Minecraft and experience crash.

### Logs

https://gist.github.com/Tkcool1/4a8000406182cf6da9a0c1d2b30e00c6

### Additional context

Disabling/removing Defile seems to show that Sinytra can at least load Ratatouille (and the few items that come bundled with the library mod) on it's own, appearing in the in-game mod list despite Sinytra not recognizing the mod being there when Defile calls for it.

**Comment by Tkcool1** [comment]
UPDATE: This issue doesn't seem to be exclusive to these mods as I've had it just happen with Enchancement Unbound asking me to install Enchancement as a dependency despite it already being installed (after deleting the necessary mixins to let Enchancement work on Sinytra)

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
