### ISSUE TITLE
Server crash due to enigmatic legacy and connector

### ISSUE THREAD

**Issue by Snortcatt** [Sinytra/Connector#1572]
### Mod Name

Enigmatic Legaсy

### Mod Homepage

https://modrinth.com/mod/enigmatic-legacy/versions

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The player selects storage_crystal (resource storage after death) after which the server freezes and crashes

### Logs

[crash-2024-12-07_18.51.03-server.txt](https://github.com/user-attachments/files/18049137/crash-2024-12-07_18.51.03-server.txt)

### Additional context

I want to point out that everything worked fine for all the other players (including the player with this problem). The server is crashing now, so I think the error is related to the item that is in the crystal

**Comment by Snortcatt** [comment]
A crash occurs when the player picks up a storage_crystal that has a darknest_scroll

**Comment by Snortcatt** [comment]
The crash occurs when the mind_shielding_plate located in storage_crystal.  mind_shielding_plate from the mod Eidolon:Repraised
https://www.curseforge.com/minecraft/mc-mods/eidolon-repraised
https://modrinth.com/mod/eidolonrepraised

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
