### ISSUE TITLE
Connector makes the game crash

### ISSUE THREAD

**Issue by 25h01** [Sinytra/Connector#1573]
### Mod Name

connector mod /forge

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

### Minecraft version

1.20.1 (LTS)

### Describe the bug

when i put connector mod in my mod folder the game crash

### Steps to reproduce

Hello,

So  I do some test and when i don't put connector mod in the folder its says "u need this mod to run the game correctly" but when i put connector mod inside its just crash and on the wiki it says its for neoforge but maybe the is a way to make it works on forge ?

### Logs

---- Minecraft Crash Report ---- // Don't do that.  Time: 2024-12-09 23:33:58 Description: Mod loading error has occurred  java.lang.Exception: Mod Loading has failed 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading} 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:583) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1380) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Suspected Mods: NONE Stacktrace: 	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading} -- MOD antique_atlas -- Details: 	Mod File: /C:/Users/25h01/curseforge/minecraft/Instances/create modpacks/mods/antique-atlas-2.10.0+1.20.jar 	Failure message: Mod antique_atlas requires connectormod any 		Currently, connectormod is not installed 	Mod Version: 2.10.0+1.20 	Mod Issue URL: https://github.com/sisby-folk/antique-atlas/issues 	Exception message: MISSING EXCEPTION MESSAGE Stacktrace: 	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading} 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {} 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:61) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading} 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.Util.m_137521_(Util.java:583) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.0-universal.jar%23311!/:?] {re:classloading} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1380) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- MOD connectorextras_architectury_bridge -- Details: 	Mod File: /C:/Users/25h01/curseforge/minecraft/Instances/create modpacks/mods/ConnectorExtras-1.11.2+1.20.1.jar#240!/META-INF/jarjar/architectury-bridge-1.11.2+1.20.1.jar 	Failure message: Mod connectorextras_architectury_bridge requires connectormod 1.0.0-beta.18 or above 		Currently, connectormod is not installed 	Mod Version: 1.11.2+1.20.1 	Mod Issue URL: https://github.com/Sinytra/ConnectorExtras/issues 	Exception message: MISSING EXCEPTION MESSAGE  -- MOD surveyor -- Details: 	Mod File: /C:/Users/25h01/curseforge/minecraft/Instances/create modpacks/mods/surveyor-0.6.25+1.20.jar 	Failure message: Mod surveyor requires connectormod any 		Currently, connectormod is not installed 	Mod Version: 0.6.25+1.20 	Mod Issue URL: https://github.com/sisby-folk/surveyor/issues 	Exception message: MISSING EXCEPTION MESSAGE  -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 1021090792 bytes (973 MiB) / 1862270976 bytes (1776 MiB) up to 7717519360 bytes (7360 MiB) 	CPUs: 12 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz 	Identifier: Intel64 Family 6 Model 165 Stepping 3 	Microarchitecture: unknown 	Frequency (GHz): 2.90 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x21c4 	Graphics card #0 versionInfo: DriverVersion=32.0.15.6094 	Memory slot #0 capacity (MB): 16384.00 	Memory slot #0 clockSpeed (GHz): 2.67 	Memory slot #0 type: DDR4 	Virtual memory max (MB): 28596.77 	Virtual memory used (MB): 15293.69 	Swap memory total (MB): 12288.00 	Swap memory used (MB): 592.57 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7360m -Xms256m 	OptiFine Version: OptiFine_1.20.1_HD_U_I6 	OptiFine Build: 20231221-120401 	Render Distance Chunks: 12 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: null 	OpenGlVersion: 4.6.0 NVIDIA 560.94 	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 	OpenGlVendor: NVIDIA Corporation 	CpuCount: 12 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.3.0.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.3.0.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.3.0.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.3.0.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.3.0.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		kotlinforforge@4.11.0 		javafml@null 		__fabric_loader_bootstrap@2.6.0+0.15.0+1.20.1 		lowcodefml@null 	Mod List:  		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		forge-1.20.1-47.3.0-universal.jar                 |Forge                         |forge                         |47.3.0              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
