### ISSUE TITLE
incompatibility with epic fight mod

### ISSUE THREAD

**Issue by Sebas2K25** [Sinytra/Connector#1575]
### Minecraft version

1.20.1 (LTS)

### Describe the bug

When I enter my server with the Epic Fight mod, my Minecraft crashes, but testing on another server without Sinytra or its modifications, the Epic Fight works fine and without problems, and this error happens to me in multiplayer in a single player, no

### Steps to reproduce

1.I enter the server
2.Load the world
3.The world closes and says saving, it practically kicks me out and the game [closes]
 [crash-2024-11-30_12.00.13-client.txt](https://github.com/user-attachments/files/18116101/crash-2024-11-30_12.00.13-client.txt)

...

### Additional context

[crash-2024-11-30_12.00.13-client.txt](https://github.com/user-attachments/files/18116131/crash-2024-11-30_12.00.13-client.txt)

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by Sebas2K25** [comment]
In the latest version of sinytra I still have the same error
