### ISSUE TITLE
World Creation Crash

### ISSUE THREAD

**Issue by Siravia** [Sinytra/Connector#1577]
Didn't make one from a template, because I'm not sure _what_ exactly is causing the crash, but as I have Connector installed I thought I'd check here first. If this isn't the appropriate channel to do so, please point me in the right direction.

Simple problem - creating a world causes the game to crash. [Here's](https://pastebin.com/HippFwcU) the crash log. Would appreciate some help in regards to figuring out what's causing the problem. Hopefully it's not just "need more memory" or something silly like that.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
