### ISSUE TITLE
Bren ( fabric gun mod) currently incompatible with Connector and Connector Extras

### ISSUE THREAD

**Issue by MASTOOOO** [Sinytra/Connector#1579]
### Mod Name

bren

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bren

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The ammunition of each weapon dont exist and dont deal any damage when shot. Its like there shooting invisible and harmless bullets. Everything else works just fine. I can provide video clip of the issue if I dont explain it well enough. 

### Steps to reproduce

1.Minecraft Launcher 
2.Forge 47.3.0
3.1.20.1 

### Logs

https://gist.github.com/MASTOOOO/44ec4c95ae5634f6390f88f37cea6576

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
