### ISSUE TITLE
MCHalo 1.20.1 crashes on startup with azurelib(Fabric)


### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#158]

**Comment by RoomAlex68** [comment]
Mods here:

https://www.curseforge.com/minecraft/mc-mods/mchalo/files?version=1.20.1

https://www.curseforge.com/minecraft/mc-mods/azurelib

**Comment by Su5eD** [comment]
Works for me using `azurelib-fabric-1.20.1-1.0.25` and `mchalo-1.20.1-1.1.20` on Connector beta 10. Do you have any other mods installed?

**Comment by RoomAlex68** [comment]
It crashes with and without other mods

**Comment by Su5eD** [comment]
Can you please list exactly what mods you're using and provide a crash log / debug.log?

**Comment by RoomAlex68** [comment]
Is there any other API for MCHalo mod to run?

**Comment by Su5eD** [comment]
What API?
