### ISSUE TITLE
incompatibility with ocean's delight

### ISSUE THREAD

**Issue by VaporeonScripts** [Sinytra/Connector#1580]
### Mod Name

Ocean's delight

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/oceans-delight

### Minecraft version

1.20.1 (LTS)

### Describe the bug

crash

### Steps to reproduce

use connector along the mod

### Logs

https://mclo.gs/okA5xr5

### Additional context

a

**Comment by VaporeonScripts** [comment]
forge

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
