### ISSUE TITLE
Minecraft Game Crash - NullPointerException in LocalPlayer

### ISSUE THREAD

**Issue by WinKing114** [Sinytra/Connector#1581]
### Mod Name

embeddium_extra

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/magnesium-extras

### Minecraft version

1.20.1 (LTS)

### Describe the bug

NullPointerException

### Logs

https://gist.github.com/lXIAOLEl/796f955f221414fd260d2e79f5147d28

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
