### ISSUE TITLE
Hybrid Aquatic Crash

### ISSUE THREAD

**Issue by spiritpoyo** [Sinytra/Connector#1583]
### Mod Name

Hybrid Aquatic

### Mod Homepage

https://github.com/hybridlabs/hybrid-aquatic

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Game instantly crashes with Exit Code 1 on error, crash log is not generated. Tried with a combination of Geckolib Fabric, Geckolib Forge, and Geckolib Fabric + Forge. The Fabric version is the only one and latest one used in this crash trial.

### Steps to reproduce

1. Use Forge Version 47.3.0 on Java 17.0.10 (Prism Launcher is used to retrieve crash log, but similar issue is present on both Minecraft and Prism Launcher)
2. Install Hybrid Aquatic (Latest version), Geckolib Fabric (Latest Version), Sinytra Connector (Latest version), ConnectorExtras (Latest Version), Forgified Fabric API (Latest Version). All above are for version 1.20.1
3. Launch Game...

### Logs

https://mclo.gs/ii3xtaq

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
