### ISSUE TITLE
Better End partal incompatibility

### ISSUE THREAD

**Issue by The-Arcanian** [Sinytra/Connector#1587]
### Mod Name

Better End

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Disabling items/blocks in Better End causes Minecraft to crash

### Steps to reproduce

1. Install Sinytra Connector and Better End.
2. Disable some of Better End's items and blocks in its configs.
3. Start Minecraft.
4. Crash.

### Logs

https://gist.github.com/The-Arcanian/64c211e3217a738bf3a6df419e75e7ab

### Additional context

I don't know if Better End is feature-complete when nothing is disabled, but I am able to load the game and make a world. Unlike in this situation.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by The-Arcanian** [comment]
Well, that is unfortunate. 1.20.1 has many more mods available for pack-making. But at least the record is here for others encountering this.
