### ISSUE TITLE
Alex's Mod detected as reason for server crash.

### ISSUE THREAD

**Issue by articens** [Sinytra/Connector#1588]
### Mod Name

Alex's Mod

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

### Minecraft version

1.20.1 (LTS)

### Describe the bug

From the crash report, I interacted with the entity "sugar gliders" and the mod crashed with "ticking entity".

### Steps to reproduce

The server has crashed and now I cannot get back in without disabling the mod. I haven't had any other issues with the mod. I do not know if the specific entity of sugar glider is the problem or if it is something else. I cannot re-enter my server to try to verify.

### Logs

https://pastebin.com/8AWyfQWS

**Comment by Su5eD** [comment]
Please report to Alex's mod.
