### ISSUE TITLE
Advent of Ascension (Nevermine mod(Forge) 1.20.1 Incompatible with connector 

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#159]
Mod Link here:
https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine

**Comment by Su5eD** [comment]
Do you have a crashlog or any additional details on this? I've tried using the mod on the latest release of Connector and FFAPI. Everything runs fine.

**Comment by RoomAlex68** [comment]
It works fine when I had other forge mods installed but when I put Fabric Mods like Marium’s Soulslike Weaponery, Bosses of Mass Destruction, and Mythic Mounts(Note: Mythic Mounts works now with connector) The only fabric mod that to got work was Presence Footsteps for Fabric

**Comment by RoomAlex68** [comment]
Except Mods that require Forge Geckolib because Bosses of Mass Destruction and Marium’s Soulslike Weaponery require Geckolib Fabric( I think Mythic Mounts also requires Geckolib Fabric?)

**Comment by Su5eD** [comment]
Do the mods you mentioned also crash when AoA is not installed?

**Comment by RoomAlex68** [comment]
Yes.
L_ender's cataclysm(1.20.1)
Mutant Monsters (1.20.1)
Aquamirae (Forge 1.20.1)
Alex Mobs(1.20.1)
CrimsonSteve's more mobs(1.20.1)
Deeper and Darker(1.20.1)
Rats(1.20.1)
Blue Skies(1.20.1)
Ultris: Boss Expansion(1.20.1)
Twilight Forest(1.20.1)

**Comment by RoomAlex68** [comment]
Yeah they don't crash when AOA is not installed

**Comment by tharrmeehan** [comment]
incompatible, see #123

**Comment by rainysux** [comment]
Aoa isnt even really viable in 1.20 survival, none of the dimensions and dimensions mobs have models

**Comment by RoomAlex68** [comment]
Because I need Forge Version of Geckolib to run AoA Because it doesn't work with Fabric version of Geckolib
