### ISSUE TITLE
Incompatible mod on 1.20.1

### ISSUE THREAD

**Issue by Alcryv** [Sinytra/Connector#1590]
### Mod Name

replay mod

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/replay-mod-fabric-and-forge

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When i boot Create mod with Replay mod it gives me an error.

### Steps to reproduce

1.Install Create Mod On Forge
2.Install Replay Mod On Fabric
3.Boot the game

### Logs

https://gist.github.com/Alcryv/b82e4f566e8961dcd361aea41612bdee

**Comment by Alcryv** [comment]
nvm fixed it by changing version of replay mod

**Comment by StormDragon-64** [comment]
For those wondering, the minimum 1.20.1 version of ReplayMod needed for it to work is 2.6.15
