### ISSUE TITLE
Crash on 1.20.1 with Modern Industrialization and others forge mods

### ISSUE THREAD

**Issue by 4ikan** [Sinytra/Connector#1593]
### Mod Name

Not sure

### Mod Homepage

Not sure

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash at the end of mc startup

### Steps to reproduce

1. Make modpack with forge and add some forge mods
2. Add Sinytra Connector
3. Add Modern Instrualization (lastest version)
...

### Logs

https://pastebin.com/7eJnc7KT

### Additional context

My modpack has 141 mod, im not sure which mod makes minecraft crash

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
