### ISSUE TITLE
connector causes crash with kotlin for forge on 1.20.1

### ISSUE THREAD

**Issue by deathstrike126** [Sinytra/Connector#1594]
### Mod Name

kotlin for forge

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge

### Minecraft version

1.20.1 (LTS)

### Describe the bug

mod crashes when dispatching mod constructs

### Steps to reproduce

1.launched game
2.got to mods gathering
3.crashes when dispatching constructs

sry for lack of info

### Logs

https://gist.github.com/deathstrike126/a6cfaf0fa446e99a4fc281d72d61c0f2

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
