### ISSUE TITLE
"Music Control" crashes immediately on startup, even with no other mods present at all

### ISSUE THREAD

**Issue by ComradeKevin** [Sinytra/Connector#1596]
### Mod Name

Music Control

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/music-control

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Immediate crash on Startup

### Logs

https://gist.github.com/ComradeKevin/5c05f8d9edc050d8bd2115de635b039b

### Additional context

The game immediately crashes on startup when trying to run the mod "Music Control". I executed the test on a completely fresh Prism Launcher instance, with no other mods present. Only "Forgified Fabric API", "Sinytra Connector", and "Music Control".

**Comment by ComradeKevin** [comment]
Update 1: I completely forgot to mention the versions I am using. I am using Minecraft Version 1.20.1, with Forge Version 47.3.0, Sinytra Connector Version 1.0.0-beta.46, and Mod Version 1.8.2.

Update 2: Using the older mod version for 1.20.1, Music Control 1.6.2, it does not crash. So something about the update from 1.6.2 to 1.8.2 must have broken the compatibility.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
