### ISSUE TITLE
Got a Weird Access Violation crash when using connector's latest 1.20.1 version

### ISSUE THREAD

**Issue by lSherozl** [Sinytra/Connector#1597]
### Mod Name

Connector

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Game crashes, maybe out of memory but mentions a few mods, just dont know if connector is involved

### Steps to reproduce

[hs_err_pid41528.log](https://github.com/user-attachments/files/18234083/hs_err_pid41528.log)
What log said before crash: https://pastebin.com/DDnQTMnA'
Ill try to reproduce it

### Logs

https://pastebin.com/DDnQTMnA

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
