### ISSUE TITLE
Update fabric to 0.16.5

### ISSUE THREAD

**Issue by souldbminerr** [Sinytra/Connector#1598]
### Mod Name

Fabric mods which use Fabric 0.16+

### Mod Homepage

N/A

### Minecraft version

1.21.1

### Describe the bug

Connector lacks support for mods which

### Steps to reproduce

Install a mod which uses new versions of fabric (I used countered's terrain slabs), then look at the crash
...

### Logs

N/A

**Comment by Su5eD** [comment]
Tested the mod and it works fine on connector beta 4. Not sure what "fabric" refers to here. FFAPI is downloaded separately.
