### ISSUE TITLE
Crash with AdventureZ

### ISSUE THREAD

**Issue by UhCaleb** [Sinytra/Connector#16]
### Describe the bug

Crashes when you load a World

### Steps to reproduce

1. Install AdventureZ
2. Load into the World
3. Crash
...

### Crash Report

https://pastebin.com/EjYEDG1v

### Additional context

Forge Version 47.1.43

Mods:
Connector-1.0.0-beta+1.20.1-full
cloth-config-11.1.106-forge
citadel-2.4.2-1.20.1
fabric-api-0.86.1+1.7.2+1.20.1
L_Enders_Cataclysm-1.29-1.20.1
libz-1.0.1
adventurez-1.4.18

**Comment by Foxering** [comment]
Has this issue been solved? I have the same problem.

**Comment by zeid0ne** [comment]
same problem on latest version

**Comment by RoomAlex68** [comment]
Am surprised he hasn't fixed this one because I don't know if it's to do with a mixin in the mod.

**Comment by RoomAlex68** [comment]
But give him time he will fix this eventually.
