### ISSUE TITLE
[1.20.1] Crash with Dash Loader

### ISSUE THREAD

**Issue by LTCatt** [Sinytra/Connector#1600]
### Mod Name

Dash Loader

### Mod Homepage

https://github.com/alphaqu/DashLoader

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash when launching

### Steps to reproduce

Just launch the game.

### Logs

https://pastebin.com/UStzBdeg  and   https://pastebin.com/jHa58a3a

### Additional context

Mod List:
![Image](https://github.com/user-attachments/assets/b958dc78-253a-490f-ad6f-c1356f9de1b9)

**Comment by LTCatt** [comment]
I know #515 recommends using Modern Fix as an alternative, but they don't really work in the same way.
Dash Loader is mostly about improving launch speed through caching.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
