### ISSUE TITLE
MCDW Incompatibility

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#162]
mod: https://www.curseforge.com/minecraft/mc-mods/mcdw

crashes on launch, sister mod minecraft dungeons armor works fine. 

Minecraft Dungeons Artifacts has a couple of bugs. 

Words from the creator of the mod on compatibility thread: 

MCDW doesn't load because of the compatibility for Reach Entity Attributes. I would imagine that this also means that MixinExtras isn't functioning properly because that code should only be loaded conditionally. It is also possible that it would run into similar issues due to our internal modification of range. See attached log

MCDA appears to work flawlessly, including the set abilities.

MCDAR appears to work, but the rendering of the Enchanted Sheep's wool does not work properly. This might be because the code is specific to Fabric and Forge does it differently. Otherwise, it seems to work well.

MCDE appears to work flawlessly.

As an aside, I am extremely excited to see where this leads. I am glad to see it taken up by such a competent developer :)

**Comment by rainysux** [comment]
Theres no crash report sadly.

**Comment by rainysux** [comment]
any updates on this? :)

**Comment by chronosacaria** [comment]
@rainysux It looks like we may need to make some code for when MCDW is used with Forge; but this is the time of year when Timefall Development prepares for our charity events, so it is kind of a crazy time of year for us right now

**Comment by rainysux** [comment]
@chronosacaria ah, I see, theres truly no rush, thank you for the response, and I'm looking forward to the future!

**Comment by PrismDraco** [comment]
Found this issue as well. Feel free to fix whenever you wish. Have a good one!

**Comment by rainysux** [comment]
@PrismDraco  you need clumps fabric

**Comment by rainysux** [comment]
https://pastebin.com/4FJRFDGi
Crashes with recent update still everything up to date
 Debug: https://pastebin.com/y6V57PMX

**Comment by Su5eD** [comment]
Fixed in b3f5ced8ab24c7e604db8a8a793e64d499e79c4a
