### ISSUE TITLE
Crashes with prominence II pack

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#165]
### Mod Name

Prominence II

### Mod Homepage

https://www.curseforge.com/minecraft/modpacks/prominence-2-forge

### Describe the bug

When pressing start world, immediately crashes, doesnt happen without connector. I disabled creative core, ambiant sounds, and oculus

### Steps to reproduce

1.Load Up minecraft
2.Press Start Game
3.Crashes 
...

### Logs

https://pastebin.com/VdfKcHeV

### Additional context
I updated all the mods too.
_No response_
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by rainysux** [comment]
if you cant find the problem through the crashlog, i'll try to find it one by one!

**Comment by tharrmeehan** [comment]
Create is not compatible with Rubidium 0.7a, downgrade to 0.6.5.

**Comment by rainysux** [comment]
I went down to 0.65 and it just crashes now without a crash log. I then tried how the modpack is originally but just adding connector and forgified, which did the same issue.

**Comment by Su5eD** [comment]
Rubidium 0.6.5 is not compatible with FFAPI due to a split package conflict as explained in #39

**Comment by rainysux** [comment]
That explains why its crashing when I went down right now, but what about the original problem? Or is rubidium all together incompatible? In 0.70a it goes to the main menu and crashes when pressing single player!

**Comment by rainysux** [comment]
If I had to guess, there could be more mods like create that could be incompatible with 0.70a I presume? Its just odd that it allows me to go all the way to the title screen and doesnt crash until i press single player

**Comment by Lolothepro** [comment]
Create is not compatible with Rubidium 0.7.0a

**Comment by rainysux** [comment]
I am 99% sure I attempted to turn off create due to me seeing flywheel in the crash report and it still did the same issue. I'm sure its also the create mods but I think there could be more.

**Comment by kakashi1464** [comment]
https://github.com/embeddedt/embeddium - 
it is a fork of rubidium which is compatible with create and Connector

**Comment by Lolothepro** [comment]
> [embeddedt/embeddium](https://github.com/embeddedt/embeddium) - it is a fork of rubidium which is compatible with create and Connector

No, it isn't

**Comment by kakashi1464** [comment]
oh then sorry for the misinformation

**Comment by rainysux** [comment]
Seems to work now, odd, I did turn off create so you are probably right
