### ISSUE TITLE
Blue Skies incompatibility 

### ISSUE THREAD

**Issue by ikrannn** [Sinytra/Connector#168]
### Mod Name

Blue Skies

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/blue-skies

### Describe the bug

Crash when using any Blue Skies weapon or tool

### Steps to reproduce

1. Launch modpack with Connector, Forgified API, and Blue Skies installed
2. Try to mine or attack something with any Blue Skies weapon/tool
3. Crash

### Logs

https://pastebin.com/ZUSJ4uer

### Additional context

Connector, Forgified API, and Blue Skies are all the latest version

**Comment by Su5eD** [comment]
Seems to be the same error as in #206

**Comment by lSherozl** [comment]
> Seems to be the same error as in #206

Question if this mod was ported to 1.19.2, would this error still happen or does an earlier version of Forge not have this conflict

**Comment by Su5eD** [comment]
Backports are not planned as explained in #33
