### ISSUE TITLE
Error occurs with Excavated Variants

### ISSUE THREAD

**Issue by 1straycat** [Sinytra/Connector#171]
### Mod Name

Excavated Variants

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/excavated-variants

### Describe the bug

When joining or creating a new singleplayer world, an error occurs reading "Failed to connect to the server: Took too long to log in" and prompts you to return to the title screen.

### Steps to reproduce

1. Have Connector beta 11, Forgified Fabric API v0.87.0+1.9.6, Dynamic Asset Generator v4.2.1 (dependency), and Excavated Variants v3.0.5 in mods folder
2. Start Minecraft
3. Attempt to join or create new singleplayer world
4. Wait for error to occur

### Logs

latest.log: https://pastebin.com/UP7ztsyd - debug.log (first half, for file size reasons): https://pastebin.com/xM0Cr8Cb - debug.log (second half): https://pastebin.com/pU2JZN2Z - crash report: https://pastebin.com/eRE7WaDJ

### Additional context

Dynamic Asset Generator is not the cause of the error, as worlds load quickly and correctly with only Connector, FFAPI, and DAG. Worlds also load when only DAG and EV are installed, so I'm fairly certain it's specifically a compatibility issue.

A crash will sometimes (but not always) occur while attempting to load a world instead of just an error, but that only happened when I had several other mods installed. I included a crash report here anyway in case it's helpful somehow, since all those mods still work fine when EV is removed.

**Comment by LostGameDev** [comment]
Doesn't Excavated Variants have dedicated versions for forge?

**Comment by 1straycat** [comment]
@LostGameDev 

Yes, the Forge version is the one that seems incompatible. There aren't any Fabric versions (at least, not that the creator maintains).
