### ISSUE TITLE
ModContainers aren't present early enough, causing crashes

### ISSUE THREAD

**Issue by Patbox** [Sinytra/Connector#18]
### Describe the bug

On fabric, all ModContainer are usable within mixin plugins. This is not the case here

### Steps to reproduce

1. Install mod getting own/other mod containers (for example Polymer)
2. Run it
3. Crash!
...

### Additional context

Technically speaking polymer will crash later down the line. But this is first crash happening

**Comment by Skidamek** [comment]
I will add that ModContainer is usable even in language adapter phrase :)

**Comment by Su5eD** [comment]
Should be fixed with 8d72c2e547dbeb29165fc0def4f3d1faa44b5492. Fabric loader is now initialized on the SERVICE layer rather than GAME, meaning we don't load any game classes which would otherwise lead to initializing mixin plugins.
