### ISSUE TITLE
Imcompability with gigeresque mod 

### ISSUE THREAD

**Issue by ItzBurning2023** [Sinytra/Connector#183]
### Mod Name

Gigeresque

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/gigeresque

### Describe the bug

I loaded the mod by itsself and with his dependecies, it just crashes

### Steps to reproduce

The mods I used: 
![image](https://github.com/Sinytra/Connector/assets/143913105/611f25c5-bfc9-4629-b9e8-1b1813fad763)

Here is the crash log:

[crash-2023-09-04_14.34.31-fml.txt](https://github.com/Sinytra/Connector/files/12515999/crash-2023-09-04_14.34.31-fml.txt)

### Logs

*

### Additional context

*

**Comment by RoomAlex68** [comment]
It crashed when I used MCHalo 1.20.1 with azurelib fabric 1.20.1

**Comment by Su5eD** [comment]
Works fine for me using Azurelib fabric and smartbrainlib forge.
![image](https://github.com/Sinytra/Connector/assets/51261569/f1490b3d-3417-453e-9348-a503f5e1e595)

**Comment by RoomAlex68** [comment]
I think I didn't put smartbrainlib for fabric when using MCHalo and azurelib for fabric

**Comment by Su5eD** [comment]
Confirmed to work with beta 12
