### ISSUE TITLE
Mixin apply crash with immersive portals

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#186]
### Mod Name

Immserive Portals

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod

### Describe the bug

crash during load

### Steps to reproduce

1. install immersive portals + miniscaled to a working modpack (and connector beta 12 + latest api)
2. crash on load due to mixins failing
3. idk what else to put here
...

### Logs

https://gist.github.com/Xplodin/ce3ba31b276b1aa3be12afcb35b93499

### Additional context

idk what changed but it crashes, but not as bad as the first one I put.

**Comment by Su5eD** [comment]
> to a working modpack

Can you please list what other mods you have installed? This could be caused by a mixin conflict with another forge mod

**Comment by Xplodin** [comment]
[list.txt](https://github.com/Sinytra/Connector/files/12528563/list.txt)
mod list

**Comment by Su5eD** [comment]
Try gradually removing to find the one causing the issue. IMMPT works fine on its own for me.

**Comment by Xplodin** [comment]
when im removing mods, should I delete the connector folder?

**Comment by Su5eD** [comment]
It's not necessary.

**Comment by Xplodin** [comment]
hey found the mod finally. Its corails tombstone not working with immersive portals

**Comment by RoomAlex68** [comment]
Immersive Portals also crashed for me

**Comment by Su5eD** [comment]
I've investigated this issue and found out both mods contain a redirector mixin for the same target in `Program#compileShaderInternal` - `Lorg/apache/commons/io/IOUtils;toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;`. This crashes the game as mixin `@Redirect` redirectors can not be chained.

However, both mods also call the original method and then process its return value. There is an alternate injector annotation in mixinextras called [`@ModifyExpressionValue`](https://github.com/LlamaLad7/MixinExtras/wiki/ModifyExpressionValue), which is tailored exactly for this use case, and it can be chained.
> Should be used in favour of `Redirect`s or `ModifyConstant`s when you want to tweak an expression's existing value instead of replacing it entirely, as unlike `Redirect`s and `ModifyConstant`s, this chains when used by multiple people.

If both mods were to switch to using MEV, the issue would be resolved. There is currently nothing that can be done for this on our side, as the conflict comes from the mods themselves, not forge.
