### ISSUE TITLE
Blur works with beta 10 but breaks with beta 11

### ISSUE THREAD

**Issue by MenacingPerson** [Sinytra/Connector#188]
### Mod Name

Blur

### Mod Homepage

https://modrinth.com/mod/blur-fabric

### Describe the bug

Crash on startup

### Steps to reproduce

1. Add Blur (fabric), Connector, FFAPI
2. Launch Minecraft
3. Crashes if connector is beta 11, works if connector is beta 10

### Logs

https://mclo.gs/pohqhNS

**Comment by Su5eD** [comment]
Fixed in upcoming release beta 12
