### ISSUE TITLE
server crashes with BetterEnd errors

### ISSUE THREAD

**Issue by mesacake** [Sinytra/Connector#191]
### Describe the bug

When starting my server, it crashes due to betterend related errors

### Steps to reproduce

1. add the mods in additional context to a server (forge 1.20.1)
2. start the server
3. witness the crash 
...

### Logs

https://pastebin.com/AtcRe4Za

### Additional context

Mod list of my modpack:
	advancednetherite-forge-2.0.2-1.20.1.jar	442.65kB	04/09/2023 22:26:25	
AE2-Things-1.2.1.jar	69.15kB	04/09/2023 22:24:35	
ae2wtlib-15.0.6-beta.jar	208.20kB	04/09/2023 22:25:28	
alchemistry-1.20.1-2.3.3.jar	3.46MB	04/09/2023 22:25:55	
alchemylib-1.20.1-1.0.29.jar	98.86kB	04/09/2023 22:27:16	
alexsmobs-1.22.5.jar	24.60MB	04/09/2023 22:27:06	
allthetrims-3.2.3-forge+1.20.1.jar	202.54kB	04/09/2023 22:24:34	
almostunified-forge-1.20.1-0.6.0.jar	191.61kB	04/09/2023 22:24:59	
AmbientEnvironment-forge-1.20.1-11.0.0.1.jar	7.16kB	04/09/2023 22:25:29	
appliedenergistics2-forge-15.0.9-beta.jar	9.24MB	04/09/2023 22:28:18	
aquamirae-6.API15.jar	16.52MB	04/09/2023 22:24:57	
architectury-9.1.12-forge.jar	554.28kB	04/09/2023 22:27:53	
AttributeFix-Forge-1.20.1-21.0.2.jar	18.96kB	04/09/2023 22:24:28	
auudio_forge_1.0.3_MC_1.19.3.jar	26.91kB	04/09/2023 22:25:48	
balm-forge-1.20-7.0.7.jar	323.47kB	04/09/2023 22:27:19	
BarteringStation-v8.0.0-1.20.1-Forge.jar	114.04kB	04/09/2023 22:27:50	
bclib-3.0.13.jar	2.22MB	04/09/2023 22:18:21	
better-end-4.0.10.jar	88.43MB	04/09/2023 22:20:15	
BetterAdvancements-1.20.1-0.3.2.161.jar	70.21kB	04/09/2023 22:25:46	
BetterCompatibilityChecker-forge-4.0.8+mc1.20.1.jar	25.92kB	04/09/2023 22:25:58	
betterfpsdist-1.20.1-3.8.jar	16.59kB	04/09/2023 22:24:30	
BetterModsButton-v8.0.2-1.20.1-Forge.jar	55.87kB	04/09/2023 22:27:10	
BetterThirdPerson-Forge-1.20-1.9.0.jar	60.08kB	04/09/2023 22:25:37	
bettervillage-forge-1.20.1-3.2.0.jar	1.93MB	04/09/2023 22:24:31	
BHMenu-Forge-1.20.1-2.4.0.jar	151.54kB	04/09/2023 22:28:14	
biomemakeover-FORGE-1.20.1-1.10.3.jar	6.66MB	04/09/2023 22:17:18	
BiomesOPlenty-1.20.1-18.0.0.597.jar	20.79MB	04/09/2023 22:24:27	
blockui-1.20.1-0.0.91-ALPHA.jar	308.00kB	04/09/2023 22:24:23	
blue_skies-1.20.1-1.3.27.jar	79.67MB	04/09/2023 22:20:27	
Boat-Item-View-Forge-1.20.1-0.0.5.jar	26.37kB	04/09/2023 22:26:44	
BoatBreakFix-Universal-1.0.11.jar	6.71kB	04/09/2023 22:26:31	
Bookshelf-Forge-1.20.1-20.0.3.jar	328.18kB	04/09/2023 22:24:26	
botarium-forge-1.20.1-2.2.0.jar	137.26kB	04/09/2023 22:27:29	
caelus-forge-3.1.0+1.20.jar	37.27kB	04/09/2023 22:28:53	
carryon-forge-1.20.1-2.1.0.1.jar	428.81kB	04/09/2023 22:25:04	
cc-tweaked-1.20.1-forge-1.108.0.jar	2.92MB	04/09/2023 22:23:54	
charmofundying-forge-6.4.2+1.20.1.jar	164.06kB	04/09/2023 22:25:37	
chemlib-1.20.1-2.0.17.jar	12.97MB	04/09/2023 22:25:24	
cherishedworlds-forge-6.1.1+1.20.1.jar	57.83kB	04/09/2023 22:25:03	
chunksending-1.20.1-2.6.jar	10.92kB	04/09/2023 22:25:40	
Chunky-1.3.92.jar	320.30kB	04/09/2023 22:29:28	
citadel-2.4.3-1.20.1.jar	2.93MB	04/09/2023 22:24:02	
clickadv-1.20.1-3.1.jar	15.32kB	04/09/2023 22:25:38	
cloth-config-11.1.106-forge.jar	1.11MB	04/09/2023 22:17:16	
Clumps-forge-1.20.1-12.0.0.3.jar	19.82kB	04/09/2023 22:27:59	
collective-1.20.1-6.65.jar	603.89kB	04/09/2023 22:26:07	
comforts-forge-6.3.3+1.20.1.jar	361.73kB	04/09/2023 22:25:07	
connectivity-1.20.1-4.5.jar	61.58kB	04/09/2023 22:23:38	
Connector-1.0.0-beta.11+1.20.1-full.jar	3.93MB	04/09/2023 22:18:35	
Controlling-forge-1.20.1-12.0.2.jar	112.58kB	04/09/2023 22:27:35	
corpse-1.20.1-1.0.5.jar	218.19kB	04/09/2023 22:26:36	
CraterLib-forge-1.20-1.0.2.jar	1.19MB	04/09/2023 22:27:05	
cristellib-1.1.1-forge.jar	418.31kB	04/09/2023 22:26:01	
Croptopia-1.20.1-FORGE-2.3.2.jar	1.93MB	04/09/2023 22:27:40	
ctov-3.3.4.jar	4.25MB	04/09/2023 22:17:39	
ctov-irons-spells-n-spellbooks-compat-1.1.jar	119.27kB	04/09/2023 22:28:21	
cupboard-1.20.1-1.8.jar	17.25kB	04/09/2023 22:23:40	
curios-forge-5.2.0+1.20.1.jar	293.02kB	04/09/2023 22:28:28	
curios-forge-5.2.0-beta.3+1.20.1.jar	285.63kB	04/09/2023 22:26:24	
CustomSkinLoader_ForgeActive-14.17.jar	140.98kB	04/09/2023 22:28:30	
DarkPaintings-Forge-1.20.1-17.0.2.jar	37.00kB	04/09/2023 22:23:36	
defaultoptions-forge-1.20-18.0.1.jar	85.88kB	04/09/2023 22:27:56	
DiagonalFences-v8.0.1-1.20.1-Forge.jar	104.99kB	04/09/2023 22:27:31	
divinerpg-1.10.6.1.jar	21.67MB	04/09/2023 22:29:24	
divinerpg_compat-1.0.1.jar	51.46kB	04/09/2023 22:29:26	
domum_ornamentum-1.20-1.0.126-BETA-universal.jar	942.25kB	04/09/2023 22:23:29	
doubledoors-1.20.1-5.0.jar	50.25kB	04/09/2023 22:27:14	
dragonfight-1.20.1-4.0.jar	30.58kB	04/09/2023 22:28:03	
dragonmounts-1.20.1-1.1.5.b3.jar	524.08kB	04/09/2023 22:29:31	
dummmmmmy-1.20-1.8.3.jar	186.57kB	04/09/2023 22:22:41	
Dungeon Crawl-1.20.1-2.3.14.jar	739.73kB	04/09/2023 22:27:46	
DungeonsArise-1.20.1-2.1.56-beta.jar	7.03MB	04/09/2023 22:17:33	
DungeonsArise-1.20.1-2.1.56.1-beta.jar	7.03MB	04/09/2023 22:26:21	
EasyAnvils-v8.0.1-1.20.1-Forge.jar	137.77kB	04/09/2023 22:25:45	
EasyMagic-v8.0.1-1.20.1-Forge.jar	113.23kB	04/09/2023 22:25:29	
elevatorid-1.20.1-1.8.15.jar	183.70kB	04/09/2023 22:22:25	
elytraslot-forge-6.3.0+1.20.1.jar	55.65kB	04/09/2023 22:27:09	
EnchantmentDescriptions-Forge-1.20.1-17.0.4.jar	61.25kB	04/09/2023 22:23:31	
endrem_forge-5.2.3-R-1.20.X.jar	861.96kB	04/09/2023 22:26:28	
entity_model_features_forge_1.20-0.2.13.jar	471.89kB	04/09/2023 22:27:13	
entity_texture_features_forge_1.20-4.5.1.jar	454.87kB	04/09/2023 22:20:40	
entityculling-forge-1.6.2-mc1.20.jar	59.07kB	04/09/2023 22:27:19	
epicsamurai-0.0.25-1.20.1-forge.jar	1.02MB	04/09/2023 22:23:35	
essential_commands-0.33.2-mc1.20.jar	1.17MB	04/09/2023 22:28:43	
fabric-api-0.83.0+1.20.jar	1.88MB	04/09/2023 22:28:35	
fabric-api-0.87.0+1.9.8+1.20.1.jar	2.52MB	04/09/2023 22:18:41	
Fallingleaves-1.20.1-2.1.0.jar	127.31kB	04/09/2023 22:23:23	
FallingTree-1.20.1-4.3.0.jar	412.36kB	04/09/2023 22:23:17	
FarmersDelight-1.20.1-1.2.3.jar	2.76MB	04/09/2023 22:26:58	
farsight-1.20.1-3.3.jar	9.28kB	04/09/2023 22:23:09	
Fastload-Reforged-mc1.20.1-3.4.0.jar	65.42kB	04/09/2023 22:17:50	
ferritecore-6.0.0-forge.jar	119.91kB	04/09/2023 22:26:03	
flib-1.20.1-0.0.11.jar	279.70kB	04/09/2023 22:23:26	
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar	225.17kB	04/09/2023 22:26:07	
ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar	504.59kB	04/09/2023 22:25:27	
friendsandfoes-beekeeperhut-forge-mc1.20-1.3.0.jar	65.18kB	04/09/2023 22:25:43	
friendsandfoes-forge-mc1.20.1-1.9.4.jar	2.48MB	04/09/2023 22:23:15	
Galosphere-1.20.1-1.3.2-Forge.jar	11.50MB	04/09/2023 22:24:57	
geckolib-forge-1.20.1-4.2.2.jar	1.11MB	04/09/2023 22:23:03	
Grass_Overhaul-Forge-23.06.09_MC1.20.jar	113.20kB	04/09/2023 22:27:53	
guardvillagers-1.20-1.6.1.jar	193.45kB	04/09/2023 22:27:42	
handcrafted-forge-1.20.1-3.0.1.jar	2.66MB	04/09/2023 22:23:08	
heracles-forge-1.20.1-1.0.4.jar	994.53kB	04/09/2023 22:22:58	
icarus-1.16.jar	174.50kB	04/09/2023 22:28:52	
Iceberg-1.20.1-forge-1.1.13.jar	129.83kB	04/09/2023 22:27:18	
Jade-1.20.1-forge-11.5.1.jar	500.36kB	04/09/2023 22:22:55	
jei-1.20.1-forge-15.2.0.27.jar	1.06MB	04/09/2023 22:22:49	
JustEnoughProfessions-forge-1.20.1-3.0.1.jar	24.03kB	04/09/2023 22:25:24	
Kiwi-1.20.1-forge-11.1.1.jar	710.95kB	04/09/2023 22:22:52	
konkrete_forge_1.6.1-2_MC_1.20.jar	609.47kB	04/09/2023 22:25:43	
kotlinforforge-4.4.0-all.jar	7.25MB	04/09/2023 22:20:37	
lazydfu-0.1.3.jar	14.19kB	04/09/2023 22:28:45	
LeavesBeGone-v8.0.0-1.20.1-Forge.jar	48.87kB	04/09/2023 22:27:43	
letmedespawn-1.1.1.jar	75.67kB	04/09/2023 22:29:50	
libraryferret-forge-1.20.1-4.0.0.jar	186.07kB	04/09/2023 22:27:51	
lootintegrations-1.20.1-3.2.jar	21.93kB	04/09/2023 22:22:43	
lootr-1.20-0.7.30.73.jar	268.68kB	04/09/2023 22:25:32	
LuckPerms-Forge-5.4.88.jar	1.33MB	04/09/2023 22:28:49	
MagnumTorch-v8.0.0-1.20.1-Forge.jar	87.89kB	04/09/2023 22:27:58	
midnightlib-fabric-1.4.1.1.jar	55.89kB	04/09/2023 22:29:53	
midnightlib-forge-1.4.1.jar	62.27kB	04/09/2023 22:28:37	
MindfulDarkness-v8.0.2-1.20.1-Forge.jar	98.85kB	04/09/2023 22:22:45	
minecolonies-1.20.1-1.1.125-BETA.jar	71.20MB	04/09/2023 22:24:21	
mining_dimension-1.20.1-1.0.4.jar	148.21kB	04/09/2023 22:24:32	
modernfix-forge-5.7.2+mc1.20.1.jar	613.94kB	04/09/2023 22:22:39	
modonomicon-1.20.1-forge-1.39.0.jar	1.94MB	04/09/2023 22:25:35	
MonsterPlus-Forge1.20.1-v1.1.6.1.jar	250.09kB	04/09/2023 22:27:27	
moonlight-1.20-2.8.13-forge.jar	919.83kB	04/09/2023 22:22:41	
MouseTweaks-forge-mc1.20-2.25.jar	74.36kB	04/09/2023 22:28:18	
multipiston-1.20-1.2.31-ALPHA.jar	37.80kB	04/09/2023 22:27:33	
MutantMonsters-v8.0.3-1.20.1-Forge.jar	1.27MB	04/09/2023 22:22:36	
MyServerIsCompatible-1.20-1.0.jar	3.40kB	04/09/2023 22:27:20	
NaturesCompass-1.20.1-1.11.2-forge.jar	210.08kB	04/09/2023 22:22:38	
NetherChested-v8.0.1-1.20.1-Forge.jar	348.61kB	04/09/2023 22:28:06	
netherportalfix-forge-1.20-13.0.0.jar	212.29kB	04/09/2023 22:27:07	
NoSeeNoTick-2.0.0-1.20.1.jar	150.45kB	04/09/2023 22:25:01	
notenoughanimations-forge-1.6.4-mc1.20.jar	401.40kB	04/09/2023 22:25:12	
obscure_api-15.jar	485.48kB	04/09/2023 22:24:59	
occultism-1.20.1-1.87.0.jar	5.02MB	04/09/2023 22:22:36	
okzoomer-forge-1.20-3.0.1.jar	117.23kB	04/09/2023 22:22:31	
open-parties-and-claims-forge-1.20.1-0.19.3.jar	1.16MB	04/09/2023 22:22:29	
OpenLoader-Forge-1.20.1-19.0.2.jar	16.46kB	04/09/2023 22:22:25	
OverflowingBars-v8.0.0-1.20.1-Forge.jar	71.77kB	04/09/2023 22:25:47	
Patchouli-1.20.1-81-FORGE.jar	622.16kB	04/09/2023 22:27:10	
Philips-Ruins1.20.1-1.9.jar	1.17MB	04/09/2023 22:22:23	
PickUpNotifier-v8.0.0-1.20.1-Forge.jar	99.77kB	04/09/2023 22:28:08	
Placebo-1.20.1-8.3.7.jar	269.38kB	04/09/2023 22:22:24	
polymorph-forge-0.49.0+1.20.1.jar	290.48kB	04/09/2023 22:26:11	
Powah-5.0.2.jar	1.84MB	04/09/2023 22:22:18	
Prism-1.20.1-forge-1.0.5.jar	50.98kB	04/09/2023 22:27:12	
Prominence-Forge-MC1.20-1.1.0-hotfix.jar	2.49MB	04/09/2023 22:26:51	
PuzzlesLib-v8.0.24-1.20.1-Forge.jar	713.68kB	04/09/2023 22:22:21	
rare-ice-0.6.0.jar	42.38kB	04/09/2023 22:25:57	
recruits-1.20.1-1.10.7.1.jar	1.15MB	04/09/2023 22:17:54	
RegionsUnexploredForge-0.5.1+1.20.1.jar	5.42MB	04/09/2023 22:17:25	
relics-1.20.1-0.4.8.3.jar	1.18MB	04/09/2023 22:22:13	
repurposed_structures-7.1.4+1.20.1-forge.jar	8.17MB	04/09/2023 22:22:10	
resourcefullib-forge-1.20.1-2.1.10.jar	362.06kB	04/09/2023 22:22:00	
ResourcePackOverrides-v8.0.1-1.20.1-Forge.jar	80.16kB	04/09/2023 22:20:39	
riverredux-0.3.1.jar	17.89kB	04/09/2023 22:26:04	
Searchables-forge-1.20.1-1.0.1.jar	75.87kB	04/09/2023 22:27:57	
SereneSeasons-1.20.1-9.0.0.43.jar	142.46kB	04/09/2023 22:24:36	
ShoulderSurfing-Forge-1.20.1-2.4.1.jar	138.17kB	04/09/2023 22:27:15	
simple-rpc-forge-1.20-3.2.2.jar	738.66kB	04/09/2023 22:26:43	
SimpleStorageNetwork-1.20.1-1.10.0.jar	460.97kB	04/09/2023 22:27:55	
SimplyHouses-1.1.4-1.20.1-forge.jar	449.60kB	04/09/2023 22:25:41	
simplyswords-forge-1.51.0-1.20.1.jar	11.52MB	04/09/2023 22:22:19	
SkyVillages-1.0.2-1.20.1-forge-release.jar	237.23kB	04/09/2023 22:27:23	
SmartBrainLib-forge-1.20-1.11.jar	309.91kB	04/09/2023 22:27:01	
smoothchunk-1.20.1-3.1.jar	12.02kB	04/09/2023 22:21:57	
snowmancy-1.20-1.1.jar	65.75kB	04/09/2023 22:28:12	
soundphysics-forge-1.20.1-1.2.1.jar	153.20kB	04/09/2023 22:18:26	
spark-1.10.42-forge.jar	2.84MB	04/09/2023 22:26:21	
spellbound-weapons-v4.0.5f.jar	672.63kB	04/09/2023 22:28:26	
starterkit-1.20.1-5.2.jar	60.40kB	04/09/2023 22:26:32	
Stoneworks-v8.0.0-1.20.1-Forge.jar	2.68MB	04/09/2023 22:26:02	
Structory_1.20.1_v1.3.2.jar	1.19MB	04/09/2023 22:25:16	
structure_gel-1.20.1-2.13.1.jar	863.07kB	04/09/2023 22:20:20	
structureessentials-1.20.1-3.0.jar	27.72kB	04/09/2023 22:24:34	
structurize-1.20.1-1.0.631-BETA.jar	980.88kB	04/09/2023 22:21:55	
supplementaries-1.20-2.5.26.jar	13.83MB	04/09/2023 22:21:51	
TerraBlender-forge-1.20.1-3.0.0.169.jar	102.90kB	04/09/2023 22:26:29	
Terralith_1.20.1_v2.4.5.jar	2.61MB	04/09/2023 22:17:41	
The_Graveyard_2.6.2_(FORGE)_for_1.20+.jar	12.94MB	04/09/2023 22:27:42	
The_Undergarden-1.20.1-0.8.8.jar	42.74MB	04/09/2023 22:21:54	
theurgy-1.20.1-1.6.4.jar	2.57MB	04/09/2023 22:21:01	
Towns-and-Towers-1.11-Fabric+Forge.jar	2.54MB	04/09/2023 22:28:02	
TradingPost-v8.0.1-1.20.1-Forge.jar	120.55kB	04/09/2023 22:25:09	
trashslot-forge-1.20-15.0.0.jar	110.83kB	04/09/2023 22:26:09	
TravelersBackpack-1.20.1-9.1.4.jar	827.90kB	04/09/2023 22:28:21	
TreeChop-1.20.1-forge-0.18.3.jar	424.78kB	04/09/2023 22:20:35	
trimeffects-1.0.1-forge.jar	12.41kB	04/09/2023 22:26:22	
trinkets-3.7.1.jar	228.95kB	04/09/2023 22:28:39	
twigs-1.20.1-3.1.0-forge.jar	2.64MB	04/09/2023 22:27:49	
twilightforest-1.20.1-4.3.1809-universal.jar	22.13MB	04/09/2023 22:21:31	
ultris-v5.6.9b.jar	14.02MB	04/09/2023 22:29:48	
veinmining-forge-1.2.0+1.20.1.jar	208.75kB	04/09/2023 22:25:26	
villagernames-1.20.1-5.2.jar	56.76kB	04/09/2023 22:26:27	
VillagersPlus_1.3_(FORGE)_for_1.20.jar	276.12kB	04/09/2023 22:26:30	
visuality-forge-2.0.2.jar	210.69kB	04/09/2023 22:20:42	
VisualWorkbench-v8.0.0-1.20.1-Forge.jar	80.13kB	04/09/2023 22:26:31	
voicechat-forge-1.20.1-2.4.24.jar	7.30MB	04/09/2023 22:17:49	
Xaeros_Minimap_23.6.3_Forge_1.20.jar	1.25MB	04/09/2023 22:20:56	
XaerosWorldMap_1.33.1_Forge_1.20.jar	797.86kB	04/09/2023 22:20:42	
xptome-1.20.1-2.1.7.jar	19.63kB	04/09/2023 22:25:49	
YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar	554.96kB	04/09/2023 22:26:34	
YSNS-Forge-MC1.20-1.0.4.jar	6.40kB	04/09/2023 22:27:43

**Comment by rainysux** [comment]
I personally recommend deleting the connector folder because this is what helped me when I had problems with better end and nether

**Comment by mesacake** [comment]
Thanks, I just did and now I am getting another error 

https://pastebin.com/RtdR9S6w

This is the new log - seems to be errors applying mixins, this was after deleting the connector folder

**Comment by rainysux** [comment]
im assuming youre using prominence or better minecraft?

**Comment by rainysux** [comment]
I also recommend deleting the old jar files since you have multiple of the same, may cause issues im not entirely sure honestly

**Comment by Su5eD** [comment]
I can't reproduce this on Connector beta 11 with only betterend and bclib. Please try further identifying the mod(s) that are causing this issue.

My installed mods used for testing:
- bclib-3.0.13
- better-end-4.0.10
- cloth-config-11.1.106-forge
- Connector-1.0.0-beta.11+1.20.1-full
- fabric-api-0.87.0+1.9.8+1.20.1

**Comment by mesacake** [comment]
I have fixed the issue, but have come to another one when using OWO lib

**Comment by Su5eD** [comment]
Could it be the same as #190 ?

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce
