### ISSUE TITLE
Crash with Customizable Player Models

### ISSUE THREAD

**Issue by Inonedn** [Sinytra/Connector#20]
### Describe the bug

When present, CPM will crash with Error Code 2

### Steps to reproduce

1. Have all required mods downloaded
2. Install CPM
3. Run Game
4. Crash
...

### Logs

https://pastebin.com/hspQBcbk

**Comment by Su5eD** [comment]
I tested the [latest version](https://www.curseforge.com/minecraft/mc-mods/custom-player-models/files/4630290) of the mod on connector beta 5 and it works perfectly. However, I still recommend you use the official Forge version, which is guaranteed to work.
