### ISSUE TITLE
Minecell (1.20.1) Crashes when exiting creative menu 

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#201]
When you exiting the creative menu. It freezes for a bit and crashes. 

Mods Link here: 
https://www.curseforge.com/minecraft/mc-mods/minecells
https://www.curseforge.com/minecraft/mc-mods/owo-lib

**Comment by rainysux** [comment]
I tried it myself, it works perfectly for me

**Comment by Su5eD** [comment]
Missing logs and version information. Please use the mod compat issue template when reporting issues, and make sure to provide all necessary information as requested.
