### ISSUE TITLE
[Buggy] Biome Replacer incapable on Sinytra

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#203]
### Mod Name

Biome Replacer

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/biome-replacer

### Describe the bug

When replacing a modded biome with config, nothing works.

### Steps to reproduce

1. See [this](https://github.com/WerDei/Biome-Replacer/issues/1) report first.
2. Attempt to replace a modded biome yourself.
3. Create new world after fiddling with config.
4. Notice you can still /locate biome

### Logs

N/A

### Additional context

Although this mod is a virgin, I really like the simplicity behind it because as a mod-pack creator, utilizing mods that are overly simplified like this one, is a godsend - it saves me lots and lots of time. 🙌

Anyway, I did some testing on fabric 0.14.22 and had no issues replacing a cinderscapes biome with a vanilla biome which leads me to believe this just might be a Sinytra bug since I was unable to get the same results on forge.

### Config you can test yourself:
cinderscapes:ashy_shoals > minecraft:basalt_deltas

**Comment by Su5eD** [comment]
I tested this as you described and it appears to work just fine. No ashy shoals biome is found, and the rest of cinderscapes' biomes are still present.

![biomes](https://github.com/Sinytra/Connector/assets/51261569/729c64dc-cd99-48db-aa73-265270da13d3)

**Comment by Cixon** [comment]
> I tested this as you described and it appears to work just fine. No ashy shoals biome is found, and the rest of cinderscapes' biomes are still present.
> 
> ![biomes](https://user-images.githubusercontent.com/51261569/265996328-729c64dc-cd99-48db-aa73-265270da13d3.png)

okay I need to diagnosis this better. perhaps one of the mods I use is disrupting everything. i’ll do some more testing

**Comment by Cixon** [comment]
sorry for wasting time - this is a mod conflict with BCLib. ticket has been passed over to biome replacer dev to investigate.
