### ISSUE TITLE
doesn't work on arclight 1.20.1

### ISSUE THREAD

**Issue by sj-hub9796** [Sinytra/Connector#205]
### Describe the bug

forgified fabric api is not working on arclight

### Steps to reproduce

1. install the latest version of forgified fabric api 
2. launch the arclight

### Logs

https://pastebin.com/Jx5v14P9

**Comment by Su5eD** [comment]
What is "arclight"? Your issue does not include a link to the incompatible mod. Please provide it.

**Comment by Su5eD** [comment]
Support for hybrids is not planned, sorry. They break a lot of stuff along the way and there is no possibility to support them properly, much like OptiFine. Both Forge and Arclight all rely on (heavy) modifications to Minecraft's code, and with FFAPI added it just explodes.

I recommend looking around for Forge and Fabric mods to substitute plugins, I believe there exist good replacements for the popular ones.

**Comment by Craftales** [comment]
Arclight is what Epic Paladins names their .jar files. Epic Paladins has both Forge and Fabric versions of the same mod so this is a classic case of incompetence on the OP's part along with their probable inability to speak or understand much English judging by their pastebin content including Korean.

**Comment by sj-hub9796** [comment]
thank you for answer.
