### ISSUE TITLE
Crashes with Yuushya Townscape

### ISSUE THREAD

**Issue by 1straycat** [Sinytra/Connector#206]
### Mod Name

Yuushya Townscape

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/yuushya-townscape

### Describe the bug

Crash occurs when clicking armor slot to equip hats added by Yuushya.

### Steps to reproduce

1. Have Connector beta 13, FFAPI 0.87.0+1.9.9, Architectury API 9.1.12 for Forge (dependency), and Yuushya Townscape 2.0.0 for Forge in mods folder.
2. Start game.
3. Attempt to equip one of the new hats (under Creative tab Yuushya-Misc) by clicking the helmet armor slot or shift-clicking the hat in the inventory.
4. Crash.

### Logs

crash report: https://pastebin.com/1gh64Caf

### Additional context

Hats _can_ be equipped successfully by right-clicking while holding one outside of the inventory. Trying to unequip the hat by clicking the helmet slot causes the same crash. This doesn't occur with other modded armors as far as I can tell.

**Comment by Su5eD** [comment]
This conflict can be easily solved by FFAPI switching to use an interface mixin instead of injecting into `Item`, but that can only be done once (Neo)Forge's mixin allows interface injections. For now, I'm afraid this will have to wait due to the technical limitation imposed by stock Forge mixin.
