### ISSUE TITLE
styled-chat-2.2.2+1.20.1 Crash server

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#208]
### Mod Name

styled-chat-2.2.2+1.20.1.jar

### Mod Homepage

https://modrinth.com/mod/styled-chat/version/2.2.2+1.20.1

### Describe the bug

error for launch server
fabric-api-0.88.1+1.20.1.jar

### Steps to reproduce

Put mod and start server = crash

### Logs

https://gist.github.com/DonorKrovi/626361f7260daa0f9c0f2017f52a21e6

**Comment by Patbox** [comment]
It should now work if you update to 2.2.3

**Comment by DonorKrovi** [comment]
> It should now work if you update to 2.2.3

No, sadly

https://gist.github.com/DonorKrovi/748ddbc6827923a6fbcb904ffa8df305

**Comment by DonorKrovi** [comment]
> It should now work if you update to 2.2.3

work, but i'm use /say and put this error
https://gist.github.com/DonorKrovi/e5b5a5eed2dfbbb5049ae0b501547ebe

**Comment by Su5eD** [comment]
Tested and confirmed to work on Connector beta 14
