### ISSUE TITLE
Chat Tools

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#210]
### Mod Name

Chat Tools 1 3 4

### Mod Homepage

https://modrinth.com/mod/chat-tools/version/1.3.4

### Describe the bug

idk

chattools-1.20.1-1.3.4.jar
186.57 KiB
4 minutes ago
cloth-config-11.1.106-fabric.jar
1.11 MiB
4 minutes ago
Connector-1.0.0-beta.13+1.20.1-full.jar
3.95 MiB
19 minutes ago
fabric-api-0.88.1+1.20.1.jar
1.96 MiB
42 minutes ago

### Steps to reproduce

Start server = crash

### Logs

https://gist.github.com/DonorKrovi/14bc9ca5608c1196e66aa937d2d450e2

**Comment by Su5eD** [comment]
Looks like you've installed the upstream Fabric API instead of the Forgified Fabric API, which should be downloaded instead according to the [installation steps](https://github.com/Sinytra/Connector#players) in Connector's readme.

**Comment by Su5eD** [comment]
> Start server = crash

According to the mod's modrinth page, it is not supported on servers. I tested it on a client and it runs fine otherwise.

>|            |           |
>|--------|--------|
>| Client side | Required |
>| Server side | Unsupported |

**Comment by DonorKrovi** [comment]
> 

Oh, sorry
