### ISSUE TITLE
ChatUtils 1.10.1+1.20.1

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#211]
### Mod Name

ChatUtils 1.10.1+1.20.1

### Mod Homepage

https://modrinth.com/mod/chatutils/version/1.10.1+1.20.1

### Describe the bug

.

### Steps to reproduce

Put and start server

### Logs

https://gist.github.com/DonorKrovi/f9d6a12dc7dd40248a989fbb68a0ac20

**Comment by Su5eD** [comment]
> - §eMod 'Chat Utils Mod' (chat_utils)§r 1.10.1+1.20.1 requires any version of §6fabric§r, which is missing!

Do you have the farbic api installed?

**Comment by DonorKrovi** [comment]
> forgified farbic api

no

**Comment by Su5eD** [comment]
According to the mod's modrinth page, it is not supported on servers. I've tested it on a client as well and it runs fine.

>|            |           |
>|--------|--------|
>| Client side | Required |
>| Server side | Unsupported |
