### ISSUE TITLE
Minecells (1.20.1) crashes when exiting creative menu

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#212]
### Describe the bug

Minecells (1.20.1) crashes when trying to exit creative menu

### Steps to reproduce

1. Connector Beta 13
2. Forgified-fabric-api 1.9.9
3. minecells-1.20.1-1.5.4
4. [1.20.1] oωo - 0.11.1
5. Open creative menu and when trying to exit it. It freezes for a bit and crashes 

...

### Additional context

Mod links here:
https://www.curseforge.com/minecraft/mc-mods/minecells
https://www.curseforge.com/minecraft/mc-mods/owo-lib
For some reason It didn't give me a crash log

**Comment by RoomAlex68** [comment]
Am not sure if it's Minecells mod itself or it could be owo lib

**Comment by RoomAlex68** [comment]
This also happened when I use Alloy Forgey and Owo lib and I opened the creative menu and when grab something or not from the creative menu it's crashes! So I guess there is some Incompatibility with owo-lib.

**Comment by RoomAlex68** [comment]
This also happened when I use Alloy Forgey and Owo lib and I opened the creative menu and when grab something or not from the creative menu it's crashes! So I guess there is some Incompatibility with owo-lib.

**Comment by rainysux** [comment]
show your latest log file atleast when the crash occurs

**Comment by RoomAlex68** [comment]
Here Is the latest log:

![2023-09-08-1.log.gz](https://github.com/Sinytra/Connector/files/12560476/2023-09-08-1.log.gz)

**Comment by Su5eD** [comment]
I tried to reproduce this with the mods you listed, but could not trigger the crash. Your log also indicates there are far more mods installed than you listed in the report. Please try to reproduce the crash with only minecells installed, or identify the mod causing the crash.

**Comment by RoomAlex68** [comment]
Its owo-lib thats causing the crash

**Comment by rainysux** [comment]
Its not owo, I play with owo just fine and it doesnt crash, its probably conflicting with another mod, does it not have a crash report? since you crash during the game

**Comment by RoomAlex68** [comment]
Here is the new log file:

![converted_fileproinfo_latest.txt](https://github.com/Sinytra/Connector/files/12566119/converted_fileproinfo_latest.txt)
