### ISSUE TITLE
game starts but cant load inside world

### ISSUE THREAD

**Issue by forgolotl** [Sinytra/Connector#213]
### Describe the bug

the mods all work fine but cant load in a world (PROBLEM IS RUBIDIUM/SODIUM OCCLUSIN FIX)

### Steps to reproduce

1. load up the game (success)
2. try to load a world
3. it goes to 100% but when the screen says(loading in world) it says "saving world" then crashes
...

### Logs

logs doesnt say anything + the logs are insanely large (CAUSED BY RUBIDIUM/SODIUM OCCLUSION FIX)

### Additional context

https://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWMhttps://pastebin.com/VQemNNWM

**Comment by Su5eD** [comment]
Please identify the mod(s) causing the issue instead of just providing the entire mod list.

**Comment by rainysux** [comment]
try removing exordium

**Comment by forgolotl** [comment]
> try removing exordium

its disabled @rainysux

**Comment by forgolotl** [comment]
update: the issue was caused by rubidium/ sodium occlusion fix

**Comment by coco875** [comment]
> update: the issue was caused by rubidium/ sodium occlusion fix

this mod is inutile since 0.5

**Comment by coco875** [comment]
https://github.com/yezhiyi9670/occlusion-culling-fix-sodium/issues/4
