### ISSUE TITLE
Very Many Players

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#216]
### Mod Name

Very Many Players

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/vmp-fabric

### Describe the bug

Server crash to launch

### Steps to reproduce

Server crash to launch

### Logs

https://gist.github.com/DonorKrovi/8a3a1a63eb853c9a841c001d0fad335d

**Comment by StormDragon-64** [comment]
There is an official [Forge port of VMP](https://modrinth.com/mod/vmp-forge) btw.
