### ISSUE TITLE
Unexpected Crash with Let's Do [Cheese/API]

### ISSUE THREAD

**Issue by Matthysse** [Sinytra/Connector#219]
### Mod Name

[Let's Do] Meadow

### Mod Homepage

https://modrinth.com/mod/lets-do-cheese

### Describe the bug

It's a weird crash, as the mod itself has a forge version, and this mod and Sinytrra Connector alone work together with no problem. But on my main modpack, here is a crash that I have that seem to be related to the connector.

### Steps to reproduce

1. Install Let's Do Meadow (Forge version) on a modpack alongside the connector mod (unidentified incompatibility)
2. See it crashing when launching game

### Logs

https://pastebin.com/s2tQynNE

**Comment by wsxiya** [comment]
I also encountered the same situation, which caused many forge versions of mods to become unusable.

**Comment by rainysux** [comment]
Me as well. It works fine by itself but like you guys said, it causes problems with forge mods even though its a forge mod itself

**Comment by Su5eD** [comment]
> this mod and Sinytrra Connector alone work together with no problem

Have you been able to identify which other mod is causing the incompatibility?

**Comment by rainysux** [comment]
It causes incompatibility with alot of mods, like
[crash-2023-09-08_22.07.43-client.txt](https://github.com/Sinytra/Connector/files/12566777/crash-2023-09-08_22.07.43-client.txt)
[crash-2023-09-08_22.20.00-client.txt](https://github.com/Sinytra/Connector/files/12566778/crash-2023-09-08_22.20.00-client.txt)
[crash-2023-09-08_22.21.18-client.txt](https://github.com/Sinytra/Connector/files/12566779/crash-2023-09-08_22.21.18-client.txt)
[crash-2023-09-08_22.22.49-client.txt](https://github.com/Sinytra/Connector/files/12566780/crash-2023-09-08_22.22.49-client.txt)
[crash-2023-09-08_22.24.53-client.txt](https://github.com/Sinytra/Connector/files/12566781/crash-2023-09-08_22.24.53-client.txt)
[crash-2023-09-08_22.26.08-client.txt](https://github.com/Sinytra/Connector/files/12566782/crash-2023-09-08_22.26.08-client.txt)
[crash-2023-09-08_22.27.39-client.txt](https://github.com/Sinytra/Connector/files/12566783/crash-2023-09-08_22.27.39-client.txt)
[crash-2023-09-08_22.28.57-client.txt](https://github.com/Sinytra/Connector/files/12566785/crash-2023-09-08_22.28.57-client.txt)

**Comment by RoomAlex68** [comment]
Yeah this happened to me too

**Comment by Matthysse** [comment]
Update: on the latest version of the mod (beta 14) it doesn't crash anymore on boot, and doesn't crash at all, but makes the loading of a world completely stucked at 46% :
![image](https://github.com/Sinytra/Connector/assets/32510957/27eff0ae-e458-4517-8fc5-006b34f31af9)
Here are the logs without closing Minecraft, just at the time when the loading is stucked.
https://pastebin.com/cgvyBb8k

**Comment by Matthysse** [comment]
Update : now the loading is successful, but when generating new terrain, sometimes it just stops generating new chunks randomly without any errors in the logs.

**Comment by Matthysse** [comment]
Issue actually not related to the mod, so compatiblity seems resolved as biomes generate without problems.
