### ISSUE TITLE
Crashwhen loading mythic metals

### ISSUE THREAD

**Issue by NULLIFICATED** [Sinytra/Connector#220]
### Mod Name

Mythic Metals

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/mythicmetals

### Describe the bug

Crash while minecraft mod loading

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/qMbW7XGQ

**Comment by Su5eD** [comment]
Duplicate of #46
