### ISSUE TITLE
Crashing with Cloth, Oculus and several other Forge mods

### ISSUE THREAD

**Issue by Gamemassa** [Sinytra/Connector#222]
### Describe the bug

I've been seeing several different crashes when Forge mods are installed alongside Connector. I'm not sure if Connector (or Forgified Fabric, if that's what's causing them) is supposed to be looking for mods that work natively with Forge, but it seems like it is, and then it's getting confused because the mods don't need to be converted the way it would convert Fabric mods.

**Comment by Su5eD** [comment]
No, connector ignores all forge mods and does not attempt loading them.
