### ISSUE TITLE
InvView-1.4.12-1.20+.jar

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#223]
### Mod Name

InvView-1.4.12-1.20+.jar

### Mod Homepage

https://modrinth.com/mod/invview/version/1.4.12

### Describe the bug

.

### Steps to reproduce

Start server = crash

### Logs

https://gist.github.com/DonorKrovi/748ddbc6827923a6fbcb904ffa8df305

**Comment by Su5eD** [comment]
Fixed in Connector beta 14
