### ISSUE TITLE
Carbon mod

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#224]
### Mod Name

Carbon mod

### Mod Homepage

https://modrinth.com/plugin/carbon/version/mWkTUcC4

### Describe the bug

.

### Steps to reproduce

server start = crash

### Logs

https://gist.github.com/DonorKrovi/4c19e5a6edc170633a08e00be3105434

**Comment by Su5eD** [comment]
I tried running the mod on Fabric, but couldn't get it to work there either. Is it possible this is an issue with the mod itself? I got a similar CNFE error despite having luckperms v5.4.102 installed
> Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/model/user/User

**Comment by DonorKrovi** [comment]
> I tried running the mod on Fabric, but couldn't get it to work there either. Is it possible this is an issue with the mod itself? I got a similar CNFE error despite having luckperms v5.4.102 installed
> 
> > Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/model/user/User

Probably need to try running the version below?

**Comment by Su5eD** [comment]
I'm running the version you linked, using Fabric 0.87.0+1.20.1 and Fabric loader 0.14.22

**Comment by DonorKrovi** [comment]
> Я использую версию, которую вы связали, используя Fabric 0.87.0 + 1.20.1 и Fabric loader 0.14.22
