### ISSUE TITLE
LuckyPerms Mod

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#225]
### Mod Name

LuckyPerms

### Mod Homepage

https://modrinth.com/mod/luckperms/version/v5.4.102-fabric

### Describe the bug

Luckyperms server side crash

### Steps to reproduce

Luckyperms server side crash

### Logs

https://gist.github.com/DonorKrovi/8f9be468fe29cc13411628f398d22f8c

**Comment by kakashi1464** [comment]
why don't you use the forge version?

**Comment by DonorKrovi** [comment]
> why don't you use the forge version?

Fabric modes are set up for the fabric version, I suppose

**Comment by Su5eD** [comment]
The Fabric version runs fine for me on Connector beta 13 and FFAPI 0.87.0+1.9.9+1.20.1.

![](https://github.com/Sinytra/Connector/assets/51261569/1cd1f75b-5bfa-4611-b41f-56e3b7af92bf)

**Comment by Su5eD** [comment]
Tested running a server and it indeed crashes there. Interesting.

**Comment by Su5eD** [comment]
The Forge mod works on a server, but if I try to load the class it complains about, it can't be found anyway. So I suspect this is an issue with the mod itself, as the class file is not present in the jar or any nested jars. For now, I recommend using the Forge version.
