### ISSUE TITLE
orderedplayerlist-0.1.2+1.20.1

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#226]
### Mod Name

orderedplayerlist-0.1.2+1.20.1

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/ordered-player-list

### Describe the bug

The launch of the server is successful, but as soon as the player connects to the server, it will immediately crash

### Steps to reproduce

The launch of the server is successful, but as soon as the player connects to the server, it will immediately crash

### Logs

https://gist.github.com/DonorKrovi/a07cf22da6b871ea90a65c6083c17c4b

**Comment by Su5eD** [comment]
I tried to run this mod on Fabric, but it crashes there as well with a similar classnotfoundexception. Therefore, this is an issue on the mod's side.
