### ISSUE TITLE
Minecells(1.20.1) Crashes when trying to exit creative menu.

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#229]
### Describe the bug

This is a issue I had despite being closed multiple times because of trying to reproduce it and logs as well.

### Steps to reproduce

1. Have Connector Beta 13 Installed 
2. Have Forgified Fabric API 1.9.9 Installed 
3. Minecells(1.20.1) 1.5.6
4. owo-lib(1.20.1) owo - 0.11.1
5. Open the creative menu and try to get something 
6.  When trying to leave the creative menu it freezes for a bit and then crashes with no crash log but it does show what happened in the latest log.

### Logs

https://github.com/Sinytra/Connector/files/12566119/converted_fileproinfo_latest.txt

**Comment by RoomAlex68** [comment]
There is no other mods this time or if there is then let me know which ones I have installed.

**Comment by tharrmeehan** [comment]
I can't seem to reproduce this with my modpack, seems to be a Linux specific issue?

**Comment by Su5eD** [comment]
same

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce. If you're able to provide exact reproduction steps, please comment on this issue.
