### ISSUE TITLE
GeckoLib cross-platform compatibility

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#231]
### Mod Name

advent of ascension, boss of mass destruction

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine

### Describe the bug

crash at start

### Steps to reproduce

1. have ffapi, connector, advent of ascension, bomd
2. start
3. see
...

### Logs

https://pastebin.com/uViK60p4

**Comment by tharrmeehan** [comment]
BOMD is not compatible with Geckolib Forge, try the Fabric version.

**Comment by coco875** [comment]
I already use the fabric version of gecko try yourself if you don't trust me

**Comment by tharrmeehan** [comment]
The problem here is probably that one of the mods has got Geckolib Forge included/embedded in it, which makes it crash.

**Comment by coco875** [comment]
ok like said in issue I only use AoA and Bomd with it dependencies os it can be only AoA or Bomd

**Comment by coco875** [comment]
AoA depend of gecko also but I put fabric version of it so it should use it

**Comment by RoomAlex68** [comment]
I tried with the Fabric version of Geckolib with AoA it crashes.

**Comment by Su5eD** [comment]
The problem here comes in 2 parts:
1. AoA bundles Forge Geckolib, which will be preferred over its Fabric version in case you install both. This means Fabric Geckolib will never be loaded.
2. Even if you remove Forge Geckolib from AoA and load Fabric Geckolib instead, you get potential item rendering issues as explained in #198

**Comment by coco875** [comment]
so it's geckolib fabric version who need to make the change

**Comment by coco875** [comment]
or geckolib forge need to update to avoid init to early

**Comment by zeid0ne** [comment]
> The problem here comes in 2 parts:
> 
> 1. AoA bundles Forge Geckolib, which will be preferred over its Fabric version in case you install both. This means Fabric Geckolib will never be loaded.
> 2. Even if you remove Forge Geckolib from AoA and load Fabric Geckolib instead, you get potential item rendering issues as explained in [Using this with fabric Geckolib can make some items turn invisible #198](https://github.com/Sinytra/Connector/issues/198)

How do you remove forge gecko lib from a mod that use it ?
And how do you detect these mods ?
Thanks

**Comment by Jackiecrazy** [comment]
to pitch a bit into the situation, using connector extras allows models to show up but does not solve the game crashing when rendering a forge geckolib item. Most of them seem to be `AbstractMethodError`s.
[crash-2023-11-08_19.35.28-client.txt](https://github.com/Sinytra/Connector/files/13296176/crash-2023-11-08_19.35.28-client.txt)
[crash-2023-11-08_19.27.14-client.txt](https://github.com/Sinytra/Connector/files/13296183/crash-2023-11-08_19.27.14-client.txt)

**Comment by Su5eD** [comment]
Yeah, that happens due to code differences between the two versions of geckolib

**Comment by SuperStefan97** [comment]
In case it solves anything now there is a forge version of Bosses of Mass destruction... https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction-forge

**Comment by coco875** [comment]
yeah but it's not the only fabric mod who use geckolib so can be good to solve this or gecko make parity between forge and fabric

**Comment by MCCrafter247** [comment]
So I posted that issue about Enderman Overhaul not working with the fabric version of Geckolib (logs and all necessary info can be found there for anyone curious). What exactly is the issue it has with fabric Geckolib?

**Comment by aking4125** [comment]
Throwing [NeepMeat](https://github.com/MeatWheeze/NeepMeat) in here as #1010 is a dupe. Works with Geckolib Fabric, doesn't work with the Forge version.

**Comment by hiimrickross** [comment]
Does anyone have other info on what mods forcibly bundle geckolib forge in then?

If Soulslike Weaponry and similar mods that require geckolib fabric, plus mods that require geckolib forge and AREN'T bundled, BUT work fine with connector's geckolib fabric... that's awesome - but how can we tell what mods we have are bundling geckolib forge and preventing things from working? :/

**Comment by Mqony** [comment]
Hello, still having a similar issue. For some reason, using Geckolib Fabric to replace GeckoLib Forge not only causes a crash with Celestisynth, but also the BCLib mod which is necessary for Better End/Better Nether

**Comment by FullMetalMaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/critters-and-companions/files/all?page=1&pageSize=20&gameVersionTypeId=4
https://www.curseforge.com/minecraft/mc-mods/pokeblocks
these mods has the same issue it can't decide between the two and it will crash the game
