### ISSUE TITLE
Game Crashes when using Oculus and Rubidium

### ISSUE THREAD

**Issue by PrelawAverage** [Sinytra/Connector#233]
### Describe the bug

Can't start game

### Steps to reproduce

1. Download and install 
- oculus-mc1.20-1.6.4.jar
- rubidium-0.6.5.jar
- fabric-api-0.87.0+1.9.9+1.20.1.jar
- Connector-1.0.0-beta.13+1.20.1-full.jar
2. Launch game
3. Crash

### Logs

https://pastebin.com/2VnynTYP

**Comment by PrelawAverage** [comment]
Sorry i meant to put this as compat issue

**Comment by Su5eD** [comment]
ATs not being applied means there was an error during mod loading. Can you please provide your debug.log?

**Comment by MarsliZiya** [comment]
> ATs not being applied means there was an error during mod loading. Can you please provide your debug.log?

exact same error. the curious part is it crashed then worked perfectly then crashed again

**Comment by PrelawAverage** [comment]
Yes I can send it when I get home but like the previous person said, it crashed but then worked again

**Comment by Su5eD** [comment]
> Launched Version: forge-47.1.47

It appears you're using the wrong version of Forge. Please downgrade to 47.1.3
