### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by TylerHuddleston** [Sinytra/Connector#234]
### Describe the bug

The game crashed whilst unexpected error Error: java.lang.IllegalStateException: Config property is not linked yet

### Steps to reproduce

1.
2.
3.
...

**Comment by TylerHuddleston** [comment]
I think I'm just stupid. I'm using Forge... I don't remember. But not the latest one because the mods I use get slow on forge 44

**Comment by DonorKrovi** [comment]
> I think I'm just stupid. I'm using Forge... I don't remember. But not the latest one because the mods I use get slow on forge 44

You didn't even send logs, what's the point of creating an issue, are you laid up?
