### ISSUE TITLE
Biomes not generating properly

### ISSUE THREAD

**Issue by Vexonek** [Sinytra/Connector#239]
### Mod Name

Regions Unexplored, Biomes O' Plenty

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored | https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/files

### Describe the bug

All nylium is not generating in nether, prob grass undergroun is not generating properly too(Regions Unexplored) Some of blocks are not spawning correctly, Example:in Withered Abyss biome should be blackstone but instead netherrack spawns(Biomes O' Plenty)

### Steps to reproduce

1.Go to nether and look for glistering meadow
2.Nylium is not spawning, and in the rest of biomes too

### Logs

There is no log

### Additional context

![bug](https://github.com/Sinytra/Connector/assets/142011941/5b289d75-4c64-4e1d-b669-bf30bee967ba)
![bug2](https://github.com/Sinytra/Connector/assets/142011941/071ba1d3-3b6c-4b17-99d2-2bf3e96eaf53)
![bug3](https://github.com/Sinytra/Connector/assets/142011941/ecd075d3-d590-438e-b799-ec58b4e48d57)
![bug4](https://github.com/Sinytra/Connector/assets/142011941/d248e5a8-b56e-42f4-b726-039db46f6f3c)

1 pic: Nylium not generating, rest biomes too
2 pic: brimstone not generating correctly and brimstone fumarole not generating
3 pic: flesh block not generating 
4 pic: blackstone not generating

**Comment by Vexonek** [comment]
And i was testing it with better nether mod

**Comment by Vexonek** [comment]
Update: Removing folder is not helping and i will tell more details about not spawning things. Underground biomes spawns normally,(Photo:1) In Mycotoxic biome Big Yellow Bioshrooms(trees) and mycotoxic moss, grass, daisy are not spawning| In Glistering Meadow Glistering nylium, sprout, spire are not spawning|(Photo:2) In Blackstone Basin Cobalt nylium, roots, earlight, hanging earlight are not spawning.
![bug5](https://github.com/Sinytra/Connector/assets/142011941/b0b2ba79-2073-414c-b7a3-6ca81e2cc6c8)
![bug6](https://github.com/Sinytra/Connector/assets/142011941/e382ad7a-cfa3-4c1c-a7e0-925278d8c137)

**Comment by Vexonek** [comment]
Sniferplus mod is not working properly too, biome Timless grotto
![bug](https://github.com/Sinytra/Connector/assets/142011941/80acc305-3c1a-48ee-9e15-ff111dc9c934)

**Comment by lSherozl** [comment]
Can confirm some of the issues and some new ones which Idk if are the fault of connector like sprouts growing on the roof of the nether? 
<img width="1280" alt="image" src="https://github.com/Sinytra/Connector/assets/65663746/454bf91f-77b8-4085-8e55-78b2d28fbc66">

**Comment by lSherozl** [comment]
> Update: Removing folder is not helping and i will tell more details about not spawning things. Underground biomes spawns normally,(Photo:1) In Mycotoxic biome Big Yellow Bioshrooms(trees) and mycotoxic moss, grass, daisy are not spawning| In Glistering Meadow Glistering nylium, sprout, spire are not spawning|(Photo:2) In Blackstone Basin Cobalt nylium, roots, earlight, hanging earlight are not spawning. ![bug5](https://user-images.githubusercontent.com/142011941/267349889-b0b2ba79-2073-414c-b7a3-6ca81e2cc6c8.png) ![bug6](https://user-images.githubusercontent.com/142011941/267349911-e382ad7a-cfa3-4c1c-a7e0-925278d8c137.png)

Your messages are VERY confusion, please specify for the author which biomes belong to which mod, I can barely figure out which ones are from better nether, regions unexplored or something else

**Comment by lSherozl** [comment]
> And i was testing it with better nether mod

Your messages are confusing, identify which biome belongs to which mod more clearly

**Comment by lSherozl** [comment]
Also can confirm that some trees, plants and flora, as well as some blocks that are supposed to spawn for certain regions are not spawning 
<img width="1280" alt="image" src="https://github.com/Sinytra/Connector/assets/65663746/27c57f98-4318-40ba-b42c-f2795de9027e">

**Comment by lSherozl** [comment]
My glistering biome has all of these spawning, try finding more and see if spawns are fine for you
<img width="1280" alt="image" src="https://github.com/Sinytra/Connector/assets/65663746/e161dc61-5eb1-4eba-a4d6-aa692a309fe5">
Unless you mean the blue vine thingy which yes I'm not spawning that either

**Comment by lSherozl** [comment]
Here is what the biomes are supposed to look like as a reference, many of the blocks are being replaced by default nether blocks, this is weird as regions unexplored is not even a fabric version, its already forge so connector did not have to change anything to help implement it
<img width="913" alt="image" src="https://github.com/Sinytra/Connector/assets/65663746/728cb245-f84a-4762-82db-eb0e5b8d250e">
<img width="912" alt="image" src="https://github.com/Sinytra/Connector/assets/65663746/c8d08d77-3921-4691-ad80-01803e678d1a">

**Comment by Su5eD** [comment]
After some investigation I found out this is an issue with bclib, which was also reported on their repository
- https://github.com/quiqueck/BCLib/issues/75

It appears to be a conflict of bclib/terrablender that occurs when using the `BetterX` world type. I could reproduce the same surface rule bug on fabric by installing regions unexplored and better nether.

![](https://github.com/Sinytra/Connector/assets/51261569/1052c6a5-0dcb-4e73-92f5-407646c5036d)

![](https://github.com/Sinytra/Connector/assets/51261569/e4470ee2-c68d-4750-907f-845d709c60a8)

**Comment by Tomat777** [comment]
So to fix this u need to use fabric terrablender and fabric regions unexplored(also should this issue be pinned so people can find solution to biome problems?)
