### ISSUE TITLE
BOMD Works on It's Own, But Not With Mods Like Ars

### ISSUE THREAD

**Issue by ChrisLTheNerd** [Sinytra/Connector#240]
### Mod Name

Bosses of Mass Destruction & Ars Nouveau

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction  https://www.curseforge.com/minecraft/mc-mods/ars-nouveau

### Describe the bug

I tried to load Bosses of Mass Destruction with Ars Nouveau and it crashes.

### Steps to reproduce

1. Load BOMD with all required mod along with Ars Nouveau
2. It will crash

### Logs

https://gist.github.com/ChrisLTheNerd/5c94d949e5b461e1a67ffdef8c05da45

### Additional context

There's no crashes when BOMD is used along side mods like L_Ender 's Cataclysm [Forge], Alex's Mobs [Forge], Better Villages [Forge], Traverse [Fabric], Terrestria [Fabric], Sandwichable [Fabric], Better Archeology [Fabric], ext. 

Ars uses GeckoLib internally, so I think that's the issue. At the time of this edit I see it might be a similar issue as #231, but I'm reporting it just in case.

Using "Connector-1.0.0-beta.13+1.20.1-full", Forgified Fabric API "resourcefulconfig-fabric-1.20.1-2.1.0", and Forge 47.1.3.

**Comment by Su5eD** [comment]
Same situation as #231 (ars bundling forge geckolib, which crashes when initialized from fabric mods), I'll keep track of it there
