### ISSUE TITLE
Incabable mod-Conjuring

### ISSUE THREAD

**Issue by TheosCreation** [Sinytra/Connector#241]
### Mod Name

Conjuring

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/conjuring

### Describe the bug

Error: java.lang.RuntimeException: Failed to initialized owo shader program

### Steps to reproduce

1.download conjuring mod on forge 47.1.3
2.download the two fabric mods sinytra connector and forge fabric api
3.crashes on launch
...

### Logs

https://pastebin.com/hHS41Rat

**Comment by RoomAlex68** [comment]
Incompatible*

**Comment by RoomAlex68** [comment]
Did install the owo lib?

**Comment by EndangeredNayla** [comment]
This is invalid the mod doesnt crash
