### ISSUE TITLE
Leaves don't drop sticks and grass don't drop fiber

### ISSUE THREAD

**Issue by Iskaa303** [Sinytra/Connector#242]
### Describe the bug

Leaves don't drop sticks and grass don't drop fiber. In no tree punching mod grass should drop fiber and in vanilla minecraft leaves should drop sticks.

### Steps to reproduce

1. Install No Tree Punching mod and Connector
2. Start the game and generate new world
3. Leaves don't drop sticks and grass don't drop fiber
...

### Additional context

I am playing with some other mods.

**Comment by Su5eD** [comment]
Can you see if this occurs only with the listed mods installed?

**Comment by Su5eD** [comment]
Closing as can't reproduce / stale
