### ISSUE TITLE
Incompatibility w/ Plushables

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#243]
### Mod Name

Plushables

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/plushables

### Describe the bug

The mod does not launch

### Steps to reproduce

1. Install Plushables, GeckoLib (forge or fabric), Forgified Fabric and Connector
2. Load the game
3. Crash
...

### Logs

https://crashy.net/68da4bd6-f9b5-4722-adaf-cebbed56cd65

**Comment by Su5eD** [comment]
> 'java.util.function.Supplier software.bernie.geckolib.animatable.GeoItem.makeRenderer(software.bernie.geckolib.animatable.GeoItem)'

Try using the Fabric version of Geckolib

**Comment by Su5eD** [comment]
Tested to work with Geckolib Fabric
