### ISSUE TITLE
Incompatibility with Gelatin and Jello

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#246]
### Mod Name

Crash with Gelatin and Jello

### Mod Homepage

https://curseforge.com/minecraft/mc-mods/gelatin https://www.curseforge.com/minecraft/mc-mods/jello

### Describe the bug

Game crashes with mixin error

### Logs

https://pastebin.com/N83Ch0P5

### Additional context

Crash seems to be coming from Gelatin

**Comment by Su5eD** [comment]
Please provide your debug.log
