### ISSUE TITLE
Incompatibility with Alloy Forgery + Mythic Metals

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#247]
### Mod Name

Mythic Metals

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/alloy-forgery  https://modrinth.com/mod/mythicmetals

### Describe the bug

crash

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/LK1Hz6i

### Additional context

Im not sure if Mythic Metals is causing the crash but i feel like its a dependency

**Comment by Fiz-Victor** [comment]
literally the same as #46 ...

**Comment by RoomAlex68** [comment]
Alloy Forgey works, but when I exit the creative with the mod installed, it frezzes for a bit and crashes. This is an issue I had with minecells (1.20.1). I wonder if it's something to do with owo-lib
See #229
