### ISSUE TITLE
BCLIB (BETTER END & BETTER NETHER) Incompatible

### ISSUE THREAD

**Issue by MarsliZiya** [Sinytra/Connector#248]
### Mod Name

BCLIB, Better End, Better Nether

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Describe the bug

mods grass doesnt generate, incorrect biome generation crashes many times

### Steps to reproduce

1.entering end
2.getting clsoe to an modified biome

### Logs

https://gist.github.com/MarsliZiya/2c37120513ee1f62e227975e93f58dcf

### Additional context

game crashes when you get close to any modified biome. problem can be in the BETTER END mod aswell as in its library Mod BCLIB

**Comment by Su5eD** [comment]
You're using an outdated version of Connector. Please update to the latest version of Connector and FFAPI.

**Comment by MarsliZiya** [comment]
ok will try now
