### ISSUE TITLE
Create (forge) crashes with indium errors when looking up Mixing Item in JEI

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#249]
### Mod Name

Create, Indium

### Mod Homepage

https://github.com/Creators-of-Create/Create/

### Describe the bug

Create (forge) crashes with indium (a fabric mod for the fabric rendering API) errors when looking up Mixing Item in JEI

### Steps to reproduce
Hitting U on a Echo Shard in JEI causes this crash.

### Logs

https://pastebin.com/Wku6ScKP

### Additional context

Sodium or Indium is not installed but that could maybe fix this

**Comment by forgolotl** [comment]
sodium does not work (install embedium or rubidium) and in indium you have to open it on 7 zip and remove the sodium dependency in fabric.mod.json

**Comment by EndangeredNayla** [comment]
I had neither installed. And for indium just use a config override opening jars is stupid and funny at the same time

**Comment by Su5eD** [comment]
Unfortunately, Indium can not be supported due to conflicting with forge's rendering system. I'll add it to the list of incompatible mods.

See #56 and #59

**Comment by EndangeredNayla** [comment]
Thats weird since i have indium loading
