### ISSUE TITLE
Crash with Tech reborn

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#25]
### Mod Name

Tech Reborn

### Mod Homepage

https://github.com/TechReborn/TechReborn

### Describe the bug

It crash a the startup

### Steps to reproduce

1. Run
2. Wait
3. And see

### Logs

https://pastebin.com/yu8wTUMw

### Additional context

I have installed his addon also

**Comment by Su5eD** [comment]
What version of Connector and FFAPI are you using? The crash log lists forge version `47.1.43` which is too new and not compatible with FFAPI. I assume you're using FFAPI 1.8.0 or older, which crashes on this forge version instead of showing the error screen.

**Comment by Su5eD** [comment]
Try launching the game without tech reborn's addon

**Comment by coco875** [comment]
[crash-2023-08-10_21.24.36-client.txt](https://github.com/Sinytra/Connector/files/12316551/crash-2023-08-10_21.24.36-client.txt)
I steel have the same issue

**Comment by Su5eD** [comment]
Works for me with just the following mods:
- Forge `47.1.3`
- Connector `1.0.0-beta.4`
- Forgified Fabric API `0.86.1+1.8.1+1.20.1`
- Tech Reborn `5.8.6`

**Comment by coco875** [comment]
I don't know why but curseforge don't give me the last version of connector

**Comment by coco875** [comment]
[crash-2023-08-12_21.43.30-client.txt](https://github.com/Sinytra/Connector/files/12328163/crash-2023-08-12_21.43.30-client.txt)
I steel get the same error with the same config as you

**Comment by Su5eD** [comment]
Could you please paste your debug.log? I suspect a different error occurs sometime during launch that later causes the crash

**Comment by coco875** [comment]
[debug.zip](https://github.com/Sinytra/Connector/files/12328419/debug.zip)
ok

**Comment by Su5eD** [comment]
> [12Aug2023 21:43:12.739] [main/FATAL] [mixin/]: Mixin prepare for mod (unknown) failed preparing MixinDebugRenderer in reborncore.client.mixins-YmSKJ.json: org.spongepowered.reloc.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'reborncore.client.mixin.MixinDebugRenderer' was not found
org.spongepowered.reloc.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'reborncore.client.mixin.MixinDebugRenderer' was not found

Yup, this must be the actual error, huh. Weird. I'll see if I can figure out what causes this.

**Comment by Su5eD** [comment]
Can you try again using beta 5? Also delete your `mods/.connector` folder just to be extra sure.

**Comment by coco875** [comment]
[crash-2023-08-13_23.43.20-client.txt](https://github.com/Sinytra/Connector/files/12330481/crash-2023-08-13_23.43.20-client.txt)
same error I also like you said remove mods/.connector

**Comment by Su5eD** [comment]
I made some changes in FFAPI that should eliminate the crash, but I suspect there is another error that happens sooner. Can you try again using FFAPI [0.86.1+1.8.3+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.86.1+1.8.3+1.20.1)? If it crashes, please upload your debug.log.

**Comment by coco875** [comment]
and when I click on single player he crash

**Comment by coco875** [comment]
[crash-2023-08-14_17.37.55-client.txt](https://github.com/Sinytra/Connector/files/12336896/crash-2023-08-14_17.37.55-client.txt)
[debug.log](https://github.com/Sinytra/Connector/files/12336898/debug.log)

**Comment by coco875** [comment]
by using the last version of tech reborn and ffapi and sinytra connector he make a crash on the startup
[debug.log](https://github.com/Sinytra/Connector/files/12388489/debug.log)
[crash-2023-08-20_17.09.12-client.txt](https://github.com/Sinytra/Connector/files/12388490/crash-2023-08-20_17.09.12-client.txt)

**Comment by Su5eD** [comment]
Still the same odd mixin error from TR. Unfortunately, I haven't been able to reproduce it so far.

**Comment by coco875** [comment]
I can make something to help ?

**Comment by Su5eD** [comment]
Have you installed RebornCore separately alongside TechReborn?

**Comment by coco875** [comment]
I have a other instance with the two mods fabric and tech reborn I just copy the .jar file into the forge instance

**Comment by coco875** [comment]
so yes I have reborn installer with tech reborn

**Comment by Su5eD** [comment]
Can you try using only the techreborn jar alone, without reborncore? Techreborn already includes all required libraries inside it.

**Comment by coco875** [comment]
oh it's work

**Comment by coco875** [comment]
![image](https://github.com/Sinytra/Connector/assets/59367621/a62fd85a-5fa7-4798-8d02-221f92242600)
it's look like to work perfectly

**Comment by Su5eD** [comment]
Hm, the issue must be caused by the split package merger then...

**Comment by Su5eD** [comment]
Okay, I managed to fix the issue. There was a bug in the locator that loaded both `RebornCore` jars at once and triggered the split package merger when it shouldn't have.
