### ISSUE TITLE
Item alchemy crashes on boot

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#251]
### Mod Name

Item Alchemy

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/item-alchemy-fabric

### Describe the bug

crash on boot

### Steps to reproduce

1. install connector FFAPI and item alchemy
2. boot
3. exit code -1
...

### Logs

https://gist.github.com/Xplodin/fbb980d39b98192cc6396cd9799b14f4

### Additional context

idk what else  to put besides adding this mod borked a pack

**Comment by Su5eD** [comment]
Added a bridge to fix this issue in Connector Extras 1.2.0

**Comment by Xplodin** [comment]
seems this issue came back:

all updated on all connector related stuffs

https://gist.github.com/Xplodin/23889024ac57ac3b3a051c20777f4f34

**Comment by Su5eD** [comment]
This happens to be an issue with item alchemy, and should be reported there. The crash occurs on fabric when using:
- itemalchemy 0.7.3
- mcpitanlibarch 1.7.9-1.20.1-fabric
- architectury 9.1.12
