### ISSUE TITLE
Crash with Skyblock Builder

### ISSUE THREAD

**Issue by BigBull-H3RO** [Sinytra/Connector#253]
### Mod Name

Skyblock Builder

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/skyblock-builder 
https://www.curseforge.com/minecraft/mc-mods/libx

### Describe the bug

Game crashes

### Steps to reproduce

1. Setup Connector and Forgified Fabric API
2. Install [Skyblock Builder](https://www.curseforge.com/minecraft/mc-mods/skyblock-builder/files/4709469) and [LibX](https://www.curseforge.com/minecraft/mc-mods/libx/files/4636994)
3. When creating a Minecraft world in singleplayer, if you change the world type to Skyblock and click Customize to the right, the game crashes.

### Logs

https://gist.github.com/BigBull-H3RO/c03e97f1cc66dba4a3ce53452dba109d

**Comment by Vexonek** [comment]
When i checked up this mod and isues i see that this mod has isue not connector mod, but im not 100% sure

**Comment by BigBull-H3RO** [comment]
If I disable the Connector and Forgified Fabric API mod. The problem is no longer there. So, it must be a problem with the Connector (Forgified Fabric API) mod.

**Comment by Su5eD** [comment]
Fixed in https://github.com/Sinytra/ForgifiedFabricAPI/commit/8ba517a068bf1be75ff03f27a99d4acf56f11d45
