### ISSUE TITLE
Game crashes with Essential Mod installed

### ISSUE THREAD

**Issue by MarsliZiya** [Sinytra/Connector#254]
### Mod Name

Essential Mod

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/essential-mod

### Describe the bug

Game crashes a couple of seconds after loading finished and got into the game menu while having Essential Mod installed

### Steps to reproduce

1.install essential mod
2.wait for game to finish loading
3.CRASH
...

### Logs

[latest.log](https://github.com/Sinytra/Connector/files/12602216/latest.log)

### Additional context

it just says unknown reason after crash

**Comment by ieatbeansbruh** [comment]
essential mod is a forge mod

**Comment by Su5eD** [comment]
Unfortunately, Essential is a closed source and obfuscated mod. Much like in the case of OptiFine, this makes debugging impossible. My best guess is that there's a mixin conflict, but it's hard to tell without additional information. If you're using the mod to expose a local server, [ngrok](https://ngrok.com/) is a great alternative. Here's a [useful list](https://github.com/anderspitman/awesome-tunneling) of other tunneling services for reference.

**Comment by Its-Just-Luci** [comment]
I know the issue is closed, but wanted to add that I've reached out to the essential team to see if they'd be interested in finding and fixing the incompatibilities with FFI/Sinytra and their mod, hoping for the best.

**Comment by SystemlessDev** [comment]
I would recommend reading the log before putting the blame on other mods. This is very obviously a sodium issue @Su5eD
