### ISSUE TITLE
Midnight controls issue

### ISSUE THREAD

**Issue by ieatbeansbruh** [Sinytra/Connector#255]
### Mod Name

Midnight controls

### Mod Homepage

https://modrinth.com/mod/midnightcontrols

### Describe the bug

Controller sometimes give double inputs and config has issues with sensetivity as far as I know.

### Steps to reproduce

1.Download midnight controls and midnight lib
2.Connect your controller
3.Configurate the sensitivity and/or press the menu button on the controller and use the controller to pan around the buttons

### Logs

https://paste.atlauncher.com/view/378beb74-0c03-425f-a494-90254794b25b

**Comment by Lolothepro** [comment]
You're using the wrong version of Forge

**Comment by RoomAlex68** [comment]
Because the other version of Forge 1.20.1 are unstable

**Comment by ieatbeansbruh** [comment]
I am using forge 47.1.3 bozo

**Comment by ieatbeansbruh** [comment]
maybe you should learn to read the entire log

**Comment by ieatbeansbruh** [comment]
> FFAPI requires Forge 47.1.3

i accidentaly gave the entire log, issues occured even after switching

**Comment by Su5eD** [comment]
> [15/09/2023 08:20:30 AM] Using loader version 47.1.47

This clearly says you're using the wrong version of forge. Please downgrade to 47.1.3 as per #42

**Comment by Lolothepro** [comment]
Please resend the log file with Forge 47.1.3

**Comment by ieatbeansbruh** [comment]
> > [15/09/2023 08:20:30 AM] Using loader version 47.1.47
> 
> This clearly says you're using the wrong version of forge. Please downgrade to 47.1.3 as per #42

like i said I accidentally sent the full log, if you scroll further you will see, you could also try to reproduce it yourself

**Comment by Lolothepro** [comment]
> > > [15/09/2023 08:20:30 AM] Using loader version 47.1.47
> > 
> > 
> > This clearly says you're using the wrong version of forge. Please downgrade to 47.1.3 as per #42
> 
> like i said I accidentally sent the full log, if you scroll further you will see, you could also try to reproduce it yourself

Can't you send the useful part of the log file (where you run Forge 47.1.3)?

**Comment by ieatbeansbruh** [comment]
> > > > [15/09/2023 08:20:30 AM] Using loader version 47.1.47
> > > 
> > > 
> > > This clearly says you're using the wrong version of forge. Please downgrade to 47.1.3 as per #42
> > 
> > 
> > like i said I accidentally sent the full log, if you scroll further you will see, you could also try to reproduce it yourself
> 
> Can't you send the useful part of the log file (where you run Forge 47.1.3)?

you can literally scroll down
