### ISSUE TITLE
Rubidium and Modern Beta conflicts 

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#262]
### Describe the bug

Crashing when rubidium and Modern Beta are installed alongside one another 

### Steps to reproduce

Boot up the game with the specified mods installed, game will crash during startup.

### Logs

<script src="https://gist.github.com/Its-Just-Luci/6e297e9a0f164d0d49d8c310a4330e3e.js"></script>

### Additional context

I believe the most important (or at least _an_ important) line in the log is:

`[17Sep2023 03:45:13.925] [main/ERROR] [mixin/]: Mixin config fabric-block-view-api-v2.mixins.json does not specify "minVersion" property`
and
`[17Sep2023 03:45:13.946] [main/ERROR] [mixin/]: Mixin config fabric-rendering-data-attachment-v1.client.mixins.json does not specify "minVersion" property`

I'm on the latest versions of Rubidium, Sinytra and Modern Beta, and my Forge version is 47.1.6

Additionally, Iris/Sodium seem to be incompatible with Sinytra, but I reckon that is both known and low priority as forge equivalents exist. Just thought I'd mention it in case the advice is to use them, I've tried.

**Comment by Su5eD** [comment]
Reproduced. Will be fixed in beta 14
