### ISSUE TITLE
[Mod Incompat] Deep Mob Learning: Refabricated

### ISSUE THREAD

**Issue by Leclowndu93150** [Sinytra/Connector#264]
### Mod Name

Deep Mob Learning: Refabricated

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated

### Describe the bug

Crash

### Steps to reproduce

![image](https://github.com/Sinytra/Connector/assets/73310949/8310d04a-9fff-4447-b263-4c37a51ea850)

### Logs

https://pastebin.com/rjR6ZghB

**Comment by Leclowndu93150** [comment]
Looks like i pasted the wrong log but my issue is easily reproducable

**Comment by Leclowndu93150** [comment]
https://pastebin.com/yYtb1YZ9

**Comment by Leclowndu93150** [comment]
balls

**Comment by Leclowndu93150** [comment]
balls

**Comment by Leclowndu93150** [comment]
Hello

**Comment by Su5eD** [comment]
please don't spam the issue unnecessarily
