### ISSUE TITLE
Rift loader

### ISSUE THREAD

**Issue by FinnT730** [Sinytra/Connector#265]
### Describe the bug

Rift loader should be supported

### Steps to reproduce

No repro.
Just support

### Additional context

![932605815406342174](https://github.com/Sinytra/Connector/assets/7442674/e96cfcae-af88-4da1-858f-2d66e14e111f)

**Comment by Su5eD** [comment]
Thanks finn....

**Comment by WitherTM** [comment]
very funny Finn

**Comment by FinnT730** [comment]
No worries mate!!
