### ISSUE TITLE
Embeddium 0.1.5 crashes the game upon loading a world

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#266]
Mod Link here:
https://www.curseforge.com/minecraft/mc-mods/embeddium

Crash report here:
![crash-2023-09-17_17.47.10-client.txt](https://github.com/Sinytra/Connector/files/12644096/crash-2023-09-17_17.47.10-client.txt)

Latest Log here: ![2023-09-17-7.log.gz](https://github.com/Sinytra/Connector/files/12644098/2023-09-17-7.log.gz)

**Comment by Su5eD** [comment]
Does this also occur without connector installed?

**Comment by RoomAlex68** [comment]
Yes

**Comment by Su5eD** [comment]
In that case it is not an issue with connector
