### ISSUE TITLE
Not all Forge Versions supported (Forge 47.1.3 vs 47.1.47)

### ISSUE THREAD

**Issue by lSherozl** [Sinytra/Connector#267]
### Describe the bug

If I play the better minecraft prominence which has far more mods, because it is on 47.1.3 it loads the world and game fine, but if I play better minecraft 1.20.1 and it has a lot fewer mods, it does not allow you to load giving the below dependency issue. I provided a log and crash too. 

### Steps to reproduce

<img width="708" alt="image" src="https://github.com/Sinytra/Connector/assets/65663746/5182cd1e-d338-48c3-882b-e69e323e6c00">

[crash-2023-09-17_20.10.16-client.txt](https://github.com/Sinytra/Connector/files/12644322/crash-2023-09-17_20.10.16-client.txt)

### Logs

[latest.log](https://github.com/Sinytra/Connector/files/12644320/latest.log)

### Additional context

No other context except the modpacks in question are Prominence 2 vs Better Minecraft Forge 1.20.1

**Comment by lSherozl** [comment]
Updating the modpack to use 47.1.3 does not fix the issue it continues to give this message 
<img width="473" alt="image" src="https://github.com/Sinytra/Connector/assets/65663746/5a61eae5-47bb-4328-9c2c-7b9d4c243f5f">

**Comment by ArrowAced** [comment]
The error when you downgrade is because BMC has other mods that require Forge versions past 47.1.3

**Comment by lSherozl** [comment]
> The error when you downgrade is because BMC has other mods that require Forge versions past 47.1.3

Yeah I realized that, hence why I deleted the message

**Comment by lSherozl** [comment]
> The error when you downgrade is because BMC has other mods that require Forge versions past 47.1.3

I do hope though more forge versions can be incorporated at 1.3 is very early in the Forge versions

**Comment by AzureDoom** [comment]
> > The error when you downgrade is because BMC has other mods that require Forge versions past 47.1.3
> 
> I do hope though more forge versions can be incorporated at 1.3 is very early in the Forge versions

47.1.3 is the last version pushed when Forge had actual maintainers (Now it's basically just Lex doing anything) and is considered the safe version for stability, as Lex merged quite a few breaking and untested PRs after that version when the maintainers left to start [NeoForge](https://neoforged.net/)

One such [patch](https://github.com/MinecraftForge/MinecraftForge/blob/a4bef828366527c93286a7ed7a5a02ebfd6813b2/patches/minecraft/net/minecraft/client/particle/TerrainParticle.java.patch#L7-L8) breaks this [mixin](https://github.com/Sinytra/ForgifiedFabricAPI/blob/65ee7601e7008244249726335fa6076964ccc846/fabric-particles-v1/src/client/java/net/fabricmc/fabric/mixin/client/particle/BlockDustParticleMixin.java#L51) in ForgifiedFabricAPI making incompatible with the newest Forge version as per su5ed.

**Comment by lSherozl** [comment]
> > > The error when you downgrade is because BMC has other mods that require Forge versions past 47.1.3
> > 
> > 
> > I do hope though more forge versions can be incorporated at 1.3 is very early in the Forge versions
> 
> 47.1.3 is the last version pushed when Forge had actual maintainers (Now it's basically just Lex doing anything) and is considered the safe version for stability, as Lex merged quite a few breaking and untested PRs after that version when the maintainers left to start [NeoForge](https://neoforged.net/)
> 
> One such [patch](https://github.com/MinecraftForge/MinecraftForge/blob/a4bef828366527c93286a7ed7a5a02ebfd6813b2/patches/minecraft/net/minecraft/client/particle/TerrainParticle.java.patch#L7-L8) breaks this [mixin](https://github.com/Sinytra/ForgifiedFabricAPI/blob/65ee7601e7008244249726335fa6076964ccc846/fabric-particles-v1/src/client/java/net/fabricmc/fabric/mixin/client/particle/BlockDustParticleMixin.java#L51) in ForgifiedFabricAPI making incompatible with the newest Forge version as per su5ed.

Thank you for the information, I'm sure many people wondering this will have their question answered by your comment

**Comment by lSherozl** [comment]
> > > The error when you downgrade is because BMC has other mods that require Forge versions past 47.1.3
> > 
> > 
> > I do hope though more forge versions can be incorporated at 1.3 is very early in the Forge versions
> 
> 47.1.3 is the last version pushed when Forge had actual maintainers (Now it's basically just Lex doing anything) and is considered the safe version for stability, as Lex merged quite a few breaking and untested PRs after that version when the maintainers left to start [NeoForge](https://neoforged.net/)
> 
> One such [patch](https://github.com/MinecraftForge/MinecraftForge/blob/a4bef828366527c93286a7ed7a5a02ebfd6813b2/patches/minecraft/net/minecraft/client/particle/TerrainParticle.java.patch#L7-L8) breaks this [mixin](https://github.com/Sinytra/ForgifiedFabricAPI/blob/65ee7601e7008244249726335fa6076964ccc846/fabric-particles-v1/src/client/java/net/fabricmc/fabric/mixin/client/particle/BlockDustParticleMixin.java#L51) in ForgifiedFabricAPI making incompatible with the newest Forge version as per su5ed.

I do hope the future forge versions fix this mixin issue, many mods require later forge versions now, so its hard to stay on 1.3

**Comment by coco875** [comment]
> > > > The error when you downgrade is because BMC has other mods that require Forge versions past 47.1.3
> > > 
> > > 
> > > I do hope though more forge versions can be incorporated at 1.3 is very early in the Forge versions
> > 
> > 
> > 47.1.3 is the last version pushed when Forge had actual maintainers (Now it's basically just Lex doing anything) and is considered the safe version for stability, as Lex merged quite a few breaking and untested PRs after that version when the maintainers left to start [NeoForge](https://neoforged.net/)
> > One such [patch](https://github.com/MinecraftForge/MinecraftForge/blob/a4bef828366527c93286a7ed7a5a02ebfd6813b2/patches/minecraft/net/minecraft/client/particle/TerrainParticle.java.patch#L7-L8) breaks this [mixin](https://github.com/Sinytra/ForgifiedFabricAPI/blob/65ee7601e7008244249726335fa6076964ccc846/fabric-particles-v1/src/client/java/net/fabricmc/fabric/mixin/client/particle/BlockDustParticleMixin.java#L51) in ForgifiedFabricAPI making incompatible with the newest Forge version as per su5ed.
> 
> I do hope the future forge versions fix this mixin issue, many mods require later forge versions now, so its hard to stay on 1.3

the next forge will be neoforge with some internal problem and it's here where all forge maintener go, so it's will be more stable

**Comment by Leclowndu93150** [comment]
All my the mods in my pack are compatible with 47.1.3, i hope it stays like that

**Comment by Su5eD** [comment]
Fixed in https://github.com/Sinytra/ForgifiedFabricAPI/commit/076770702cbe999faee0ad87c305f3b99f270a4d. FFAPI can now run on later forge versions, but it is still recommended to stick with 47.1.3 if you can.
