### ISSUE TITLE
Minecells(1.20.1) crashes in creative menu(Video Here)


### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#268]
This is a issue I reported multiple times. However I have a video of it

Mod links here:
Minecells(1.20.1) Mod version (1.5.6)

https://www.curseforge.com/minecraft/mc-mods/minecells

Owo-lib(1.20.1) Mod Version (owo-lib-0.11.2)

https://www.curseforge.com/minecraft/mc-mods/owo-lib

I used Connector Beta 14 and Forgified Fabric API 1.9.11

Video here:
https://github.com/Sinytra/Connector/assets/85209177/58e85990-5ee5-4df3-8519-3bf1a7444fca

Latest Log file here:
![2023-09-17-7.log.gz](https://github.com/Sinytra/Connector/files/12644482/2023-09-17-7.log.gz)

**Comment by RoomAlex68** [comment]
Steps to reproduce:
1. Open the creative menu
2. Grab whatever in the creative menu 
3. Try to exit the creative menu
Frezzes for a bit and then crashes with crash log

Everything else works fine with minecells mod and owo-lib but it's just that exiting the creative menu crashes the game(Well for my experience I had) I wonder it has to do with rendering the items or something that minecells is causing or owo-lib is causing 🤔 
The only way for me to get the items and spawn the mobs and the boss is by using commands

**Comment by Su5eD** [comment]
Does this work for you on fabric?

**Comment by RoomAlex68** [comment]
Yes

**Comment by RoomAlex68** [comment]
No. But I will close this issue because I don't know what is causing the crash.
