### ISSUE TITLE
'Slight' Gui Modifications incompatibility.

### ISSUE THREAD

**Issue by murao-kun** [Sinytra/Connector#269]
### Mod Name

'Slight' Gui Modifications

### Mod Homepage

https://modrinth.com/mod/slight-gui-modifications

### Describe the bug

https://modrinth.com/mod/slight-gui-modifications

### Steps to reproduce

1. Install 'Slight' Gui Modifications, architectury and cloth config.
2. Change fabric mod json file to accept cloth config.
3. Boot the game.

### Logs

https://mclo.gs/teOQ3Pm

**Comment by Su5eD** [comment]
Fixed in Connector beta 15

**Comment by murao-kun** [comment]
Seems like not. https://mclo.gs/RDWpa9d

**Comment by Su5eD** [comment]
Are you sure the mod works with mc 1.20.1? The latest release on modrinth is for 1.19.2

**Comment by murao-kun** [comment]
You right. I was using wrong version. CF one seems to support 1.20.1. I will test it.

**Comment by murao-kun** [comment]
I tested CF version and it is crashing. Tested fabric 1.20.1 and it is working fine there. So I guess after all it is connector issue.
Here newest log using CF version and beta 15. https://mclo.gs/TCzu0G2
