### ISSUE TITLE
Majrusz's Progrssive Difficulty crash (1.20.1)

### ISSUE THREAD

**Issue by Ladocterus** [Sinytra/Connector#270]
### Mod Name

Majrusz's Progressive Difficulty

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty

### Describe the bug

When mobs that spawned from the undead army of the mod get's killed the game crashes.

### Steps to reproduce

1.Starting an undead army event by killing many zombies in an area
2.Even gets triggered
3.Kill the event monsters and game crashes.

### Logs

https://pastebin.com/xq5VnTtg

### Additional context

- I have not enough crashes, when the game crashed I get booted to the mutiplayer server screen instead of title screen
- I tested removing Majrusz's Progressive Difficulty and it stops crashes, I also tested removing Sinytra connector and it also stops the crash. (Tho as of now I'm not super sure if it's these two that are in conflict? or some fabric mod that loaded by sinytra)

**Comment by Su5eD** [comment]
Tested to work with Connector beta 17 and FFAPI 0.89.0+1.9.23+1.20.1
