### ISSUE TITLE
[Startup-Crash] Legacy Reviver

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#271]
### Mod Name

Legacy Reviver

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/legacy-reviver

### Describe the bug

Failed Startup Phase

### Steps to reproduce

Install this mod with the latest Sinytra build - see results after client launch.

### Logs

https://gist.github.com/Cixon/c0ac216ca86b3fa33a6f54901c4aea79

**Comment by Su5eD** [comment]
After patching the problematic mixin I've come across a worse issue - it appears that Legacy Reviver does [registry replacement](https://github.com/Alexandra-Myers/legacy-reviver/blob/5d4446ba60de6d011090504d480b6a4bf74010ac/src/main/java/com/atlas/legacy/legacyreviver/mixin/ItemsMixin.java#L25) for music disc cat using a **hardcoded id**, which crashes forge registry sync.

**Comment by Cixon** [comment]
> After patching the problematic mixin I've come across a worse issue - it appears that Legacy Reviver does [registry replacement](https://github.com/Alexandra-Myers/legacy-reviver/blob/5d4446ba60de6d011090504d480b6a4bf74010ac/src/main/java/com/atlas/legacy/legacyreviver/mixin/ItemsMixin.java#L25) for music disc cat using a **hardcoded id**, which crashes forge registry sync.

I can relay this to Alex. I got their inbox on discord, thanks! :-)

**Comment by Su5eD** [comment]
Opened a PR to fix the problem upstream and improve code quality

**Comment by Cixon** [comment]
thank you so much! can’t wait for next release!
