### ISSUE TITLE
Immersive portals bug

### ISSUE THREAD

**Issue by ieatbeansbruh** [Sinytra/Connector#272]
### Describe the bug

I can't interact with mobs through portals (you normally can)

### Steps to reproduce

1.make a portal with portal helper blocks
2.place a mob through a portal
3.try to hurt or interact with it in any way

**Comment by ieatbeansbruh** [comment]
> logs or modlist would help
the steps to reproduce exist for a reason

**Comment by Su5eD** [comment]
I tried this out on fabric using version [3.4.4](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod/files/4807499), and while I can break blocks through the portal, I can't interact with any entites. Does this work for you on a fabric instance?

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
