### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by litjohn50** [Sinytra/Connector#275]
### Describe the bug

The modpack won't load

### Steps to reproduce

1. Make a fresh profile with inlcuded
Forge 47.1.30
ConnectorExtras-1.1.0+1.20.1
fabric-api-0.88.1+1.9.11+1.20.1
Connector-1.0.0-beta.14+1.20.1-full
TechReborn-5.8.7
2. Try to launch game
3.  crash

### Logs

https://gist.github.com/litjohn50/c0262800168407770e1af8db347a4735

**Comment by litjohn50** [comment]
Ok ignore the above log as I installed the wrong forge v.30 instead of v.3. I do still crash on starting the pack with the correct forge
Forge 47.1.3
Previously mentioned mods
https://gist.github.com/litjohn50/53a87c365ee9e5f2004eeb5e43ded431

Randomly it does load on second launch.

**Comment by Su5eD** [comment]
Please upload your debug.log

**Comment by litjohn50** [comment]
https://gist.github.com/litjohn50/a090d68b90f6cfa43b8efd7b52f8d6e8

**Comment by Su5eD** [comment]
> Forge 47.1.30

Please downgrade Forge to 47.1.3 as later versions are currently not supported. Also, try deleting the mods/.connector folder, it might help refresh jars.

**Comment by litjohn50** [comment]
Ok so I downgraded to forge 47.1.3 removed the mods/.connector folder

This is what I have so far:
forge -47.1.3
ConnectorExtras-1.1.0+1.20.1.jar
fabric-api-0.88.1+1.9.11+1.20.1.jar
Connector-1.0.0-beta.14+1.20.1-full.jar
TechReborn-5.8.7.jar


Crash log: https://gist.github.com/litjohn50/dce5bcfd73d8fd4dc06cc28453e02608
Debug log:  https://gist.github.com/litjohn50/6957d0c9b95e868f6908bc9554f2fd76
Normal log: https://gist.github.com/litjohn50/30e5cdafdf6f20024c2e648b75776103

I am still getting the same timeout jar error

**Comment by Su5eD** [comment]
Does this still occur on the latest version of connector?

**Comment by litjohn50** [comment]
Yes, Sadly, this still occurs. Mainly, once I add a mod/ remove a mod, then it will stop timing out. But it's pretty recurrent.

**Comment by litjohn50** [comment]
https://gist.github.com/litjohn50/3036736a98beab58af4ed1e25d39504c <- latest log with newest connector version

**Comment by DonorKrovi** [comment]
https://mclo.gs/87vPo9N

I uploaded only a few mods, as soon as the error I expected occurred on fabric-automessage-1.0.0+1.20.1.jar, subsequent server runs are already unsuccessful

**Comment by DonorKrovi** [comment]
Report:
https://mclo.gs/JFONOiZ

**Comment by DonorKrovi** [comment]
![image](https://github.com/Sinytra/Connector/assets/60231586/788636ae-3b16-463f-8429-67aab53930ab)

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
