### ISSUE TITLE
Tech Reborn 5.8.7 Incompatibility

### ISSUE THREAD

**Issue by cavy8** [Sinytra/Connector#279]
### Mod Name

Tech Reborn 5.8.7

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/techreborn

### Describe the bug

Crash on startup when using the latest version - downgrading to 5.8.6 fixes the issue

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/quJu5dLQ

### Additional context

No other mods installed

**Comment by Su5eD** [comment]
Tech Reborn works for me. What other mods do you have installed?
