### ISSUE TITLE
sodium 0.5.3 incompatible

### ISSUE THREAD

**Issue by Emil2010** [Sinytra/Connector#281]
### Mod Name

sodium

### Mod Homepage

https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.3

### Describe the bug

crashes game

### Logs

https://gist.github.com/Emil2010/1fbb0515553eb61233a6bf32f37c4c27

**Comment by Lolothepro** [comment]
duplicate of https://github.com/Sinytra/Connector/issues/71

**Comment by Emil2010** [comment]
no, this is newer version of sodium

**Comment by Su5eD** [comment]
Sodium is not compatible, sorry. See the linked issue for details.
