### ISSUE TITLE
Crashes when installing LambdaBetterGrass

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#282]
### Mod Name

LambdaBetterGrass

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass

### Describe the bug

when the game was loading, the mod said that it was moving to quilt.

### Steps to reproduce

1. start Minecraft
2. the quilt message will come up
3. press "close"
4. Minecraft will crash with exit code 1
...

### Logs

https://gist.github.com/vinnyg0621/046869cbced7677474d704ce85b6cddc

### Additional context

I thought this mod would be able to load quilt mods too 😠

**Comment by Su5eD** [comment]
Running quilt-only mods is not supported by connector
