### ISSUE TITLE
Incompatiblity with BetterEnd

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#283]
### Mod Name

BetterEnd

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Describe the bug

Fabric mod discovery failed

### Steps to reproduce

1. start Minecraft
2. once it finishes loading, I'll get this dirt background screen.
3. it won't let me play
...

### Logs

https://gist.github.com/vinnyg0621/d05b3925d22a2434340c2e010de3fc04

### Additional context

I've tried every version
the mod also works for everybody else. it's so not fair that it's only doing this to me

**Comment by Su5eD** [comment]
How much memory have you allocated to minecraft? Do you have any other mods installed?

**Comment by wsxiya** [comment]
I can run it perfectly

**Comment by DonorKrovi** [comment]
this mod work for me

**Comment by wsxiya** [comment]
> 这个模组对我有用
Are there other mods installed? I use the "Forgified Fabric API
"The version is 1.9.11. It seems that the game will crash after entering the world in 1.9.12 and turning the camera.
![Uploading T@(`I{)%@{`7H2
![XQ8P8L%0G(ZZH9XL4HEBP76](https://github.com/Sinytra/Connector/assets/114494454/ea83f9b2-8c81-4a03-86d2-ceb28519889b)
UZ38CX3`L.png…]()

**Comment by lSherozl** [comment]
> ### Mod Name
> BetterEnd
> 
> ### Mod Homepage
> https://www.curseforge.com/minecraft/mc-mods/betterend
> 
> ### Describe the bug
> Fabric mod discovery failed
> 
> ### Steps to reproduce
> 1. start Minecraft
> 2. once it finishes loading, I'll get this dirt background screen.
> 3. it won't let me play
>    ...
> 
> ### Logs
> https://gist.github.com/vinnyg0621/d05b3925d22a2434340c2e010de3fc04
> 
> ### Additional context
> I've tried every version the mod also works for everybody else. it's so not fair that it's only doing this to me

What are your other mods, better end works fine with me

**Comment by vinnyg0621** [comment]
> > ### Mod Name
> > BetterEnd
> > ### Mod Homepage
> > https://www.curseforge.com/minecraft/mc-mods/betterend
> > ### Describe the bug
> > Fabric mod discovery failed
> > ### Steps to reproduce
> > 
> > 1. start Minecraft
> > 2. once it finishes loading, I'll get this dirt background screen.
> > 3. it won't let me play
> >    ...
> > 
> > ### Logs
> > https://gist.github.com/vinnyg0621/d05b3925d22a2434340c2e010de3fc04
> > ### Additional context
> > I've tried every version the mod also works for everybody else. it's so not fair that it's only doing this to me
> 
> What are your other mods, better end works fine with me

bc lib, better Nether, Dragon mounts, geophilic

**Comment by Xplodin** [comment]
> > > ### Mod Name
> > > BetterEnd
> > > ### Mod Homepage
> > > https://www.curseforge.com/minecraft/mc-mods/betterend
> > > ### Describe the bug
> > > Fabric mod discovery failed
> > > ### Steps to reproduce
> > > 
> > > 1. start Minecraft
> > > 2. once it finishes loading, I'll get this dirt background screen.
> > > 3. it won't let me play
> > >    ...
> > > 
> > > ### Logs
> > > https://gist.github.com/vinnyg0621/d05b3925d22a2434340c2e010de3fc04
> > > ### Additional context
> > > I've tried every version the mod also works for everybody else. it's so not fair that it's only doing this to me
> > 
> > 
> > What are your other mods, better end works fine with me
> 
> bc lib, better Nether, Dragon mounts, geophilic

strange, I have those mods and it works for me.
Bclib, better nether (fabric) and dragon mounts geophilic (forge)

**Comment by Su5eD** [comment]
> How much memory have you allocated to minecraft? Do you have any other mods installed?

This still hasn't been addressed

**Comment by Su5eD** [comment]
Closing this in favor of #275 which tracks the same jar transformation timeout issue
