### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by wsxiya** [Sinytra/Connector#286]
### Describe the bug

The game crashes after about 5-10 seconds after entering the game and turning the camera angle.

### Steps to reproduce

1.Forgified Fabric API-0.88.1+1.9.12+1.20.1

2.Sinytra Connector-bate15

3.
...

### Additional context

"Forgified Fabric API-0.88.1+1.9.12+1.20.1" This version will cause a crash, while "Forgified Fabric API-0.88.1+1.9.12+1.20.1" will not crash
[错误报告-2023-9-20_16.25.11.zip](https://github.com/Sinytra/Connector/files/12670822/-2023-9-20_16.25.11.zip)

**Comment by Leclowndu93150** [comment]
forge version ?

**Comment by Leclowndu93150** [comment]
the bug was already reported and will get fixed today

**Comment by wsxiya** [comment]
> 该错误已经报告，并将在今天修复
OK, thanks
