### ISSUE TITLE
Crash with the latest version of Forgified Fabric API 

### ISSUE THREAD

**Issue by BigBull-H3RO** [Sinytra/Connector#287]
### Mod Name

Forgified Fabric API 0.88.1+1.9.12+1.20.1

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector 
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

### Describe the bug

When you join a new world after creating it, Minecraft crashes a few seconds later.

### Steps to reproduce

1. Setup [Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/files/4758210) and [Forgified Fabric API](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/files/4759560)
2. Create a new world and join it
3. Seconds later it crashes

### Logs

https://gist.github.com/BigBull-H3RO/acd37d052d01d3ceecc53e511914c76e

**Comment by Leclowndu93150** [comment]
the issue is being fixed today, you can close your issue
