### ISSUE TITLE
Mod Crash

### ISSUE THREAD

**Issue by FrylixGG** [Sinytra/Connector#288]
### Describe the bug

crashing with curios api/aether

### Steps to reproduce

1. Install Forgified Fabric Api, Connector and The Aether Or Curios API
2. Load up Minecraft
3. Crash!

### Logs

https://gist.github.com/FrylixGG/f86aa0538ef4ed5eee3c69f8ee426386 https://gist.github.com/FrylixGG/ab19c6ad7ba4d2ea0ceda5495181109a

**Comment by Su5eD** [comment]
I've tested the setup with the mods you listed (FFAPI, Connector, Aether and Curios), but could not reproduce the crash. According to your log, it looks like you're using additional mods that you have not listed in the issue. Please determine which mod is causing the problem before reporting issues and make sure it can be reproduced in a clean instance with just those mods.
