### ISSUE TITLE
Access-widening isn't done correctly

### ISSUE THREAD

**Issue by Sollace** [Sinytra/Connector#29]
First off sorry if this isn't the right project to report this with. I wasn't sure if it's something ForgifiedFabricAPI should be doing, or the [Synitra Connector](https://modrinth.com/mod/connector) mod should.

Basically, when I was testing some mods to see if they worked with it, I noticed some of them were crashing due to fields they were trying to access either not being visible, or not existing.

i.e.
```
Caused by: java.lang.NoSuchFieldError: f_79109_
	at ivorius.psychedelicraft.recipe.PSRecipes.lambda$bootstrap$0(PSRecipes.java:39) ~[psychedelicraft-1.6.3+1.20_mapped_srg_1.20.1.jar%23295!/:?] {re:classloading}
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$2(LootTableEvents.java:88) ~[fabric-loot-api-v2-1.1.39+561530ec77.jar%23249!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.storage.loot.LootDataManager.md4967ae$lambda$applyLootTableEvents$1$0(LootDataManager.java:1591) ~[client-1.20.1-20230612.114412-srg.jar%23165!/:?]
```

The code that threw the exception was this line here:
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/6429283/be4122f7-75b6-4d37-976a-98bee8ec2446)

The field in question is an access widened field:
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/6429283/9883840f-308e-4291-abd2-a162103974d0)

So my conclusion is either FFA might not be applying the access wideners fabric-api does normally, or Forge has done something and stripped the fields, in which case a fix might be more involved. I hope it's the former, though, and we can get it fixed so more mods can work with this.

**Comment by Sollace** [comment]
Ah, interesting. So I suppose this isn't something straightforward to fix?

**Comment by Su5eD** [comment]
Oh, in Connector it should be fairly simple. We can run mass asm to find all references to this field and adapt the bytecode to convert the value back to an array before it's consumed. In use cases like you've shown above it would be a little redundant in terms of performance since the value is immediately converted back to a list. So we'd just go list -> array -> list. Unfortunately, such is the const of hacks.

**Comment by Sollace** [comment]
Yeah that's understandable.

It would be nice if Forge didn't make changes like this in the first place, but I suppose that's just how it is.

**Comment by Fox2Code** [comment]
In ASM it's possible to detect if next insn transform back to list, so maybe it would be possible to detect such cases?

Something like `code.replace("list -> array -> list", "list")` would work. (Note: It's pseudo code, not actual ASM)

**Comment by Sollace** [comment]
> In ASM it's possible to detect if next insn transform back to list, so maybe it would be possible to detect such cases?
> 
> Something like `code.replace("list -> array -> list", "list")` would work. (Note: It's pseudo code, not actual ASM)

That is possible, although that would raise the question of do we code in dumb support for just List.of(T[]), or do we have to look for other methods and permitations of the instructions/method invokations as well?

**Comment by Su5eD** [comment]
Added a transformer to fix the field value. I tested it with psychedelicraft and everything works fine.

There's an extra 9 fields that have their types changed, however, I'm not sure if any mods access them:
```
# Implemented transform
Field net/minecraft/world/level/storage/loot/LootTable.f_79109_ changed its type from [Lnet/minecraft/world/level/storage/loot/LootPool; to Ljava/util/List;

# Could also likely be accessed by mods
Field net/minecraft/client/KeyMapping.f_90810_ changed its type from Ljava/util/Map; to Lnet/minecraftforge/client/settings/KeyMappingLookup;

# Internal deserializer, use case unknown
Field net/minecraft/world/level/storage/loot/LootDataType.f_278485_ changed its type from Ljava/util/function/BiFunction; to Lorg/apache/commons/lang3/function/TriFunction;

# Has a public getter with the same type on both platform, direct field access is unnecessary
Field net/minecraft/world/item/HorseArmorItem.f_41362_ changed its type from Ljava/lang/String; to Lnet/minecraft/resources/ResourceLocation;

# Registry methods that should only be called by FAPI
Field net/minecraft/client/color/block/BlockColors.f_92571_ changed its type from Lnet/minecraft/core/IdMapper; to Ljava/util/Map;
Field net/minecraft/client/color/item/ItemColors.f_92674_ changed its type from Lnet/minecraft/core/IdMapper; to Ljava/util/Map;
Field net/minecraft/client/particle/ParticleEngine.f_107293_ changed its type from Lit/unimi/dsi/fastutil/ints/Int2ObjectMap; to Ljava/util/Map;
Field net/minecraft/world/item/alchemy/PotionBrewing$Mix.f_43532_ changed its type from Ljava/lang/Object; to Lnet/minecraft/core/Holder$Reference;
Field net/minecraft/world/item/alchemy/PotionBrewing$Mix.f_43534_ changed its type from Ljava/lang/Object; to Lnet/minecraft/core/Holder$Reference;

# Type broadened to all `Mob` instances by Forge, not sure if there's any way for backwards compat here
Field net/minecraft/world/entity/ai/goal/RangedBowAttackGoal.f_25782_ changed its type from Lnet/minecraft/world/entity/monster/Monster; to Lnet/minecraft/world/entity/Mob;
```

**Comment by Sollace** [comment]
> Added a transformer to fix the field value. I tested it with psychedelicraft and everything works fine.
> 
> There's an extra 9 fields that have their types changed, however, I'm not sure if any mods access them:
> 
> ```
> # Implemented transform
> Field net/minecraft/world/level/storage/loot/LootTable.f_79109_ changed its type from [Lnet/minecraft/world/level/storage/loot/LootPool; to Ljava/util/List;
> 
> # Could also likely be accessed by mods
> Field net/minecraft/client/KeyMapping.f_90810_ changed its type from Ljava/util/Map; to Lnet/minecraftforge/client/settings/KeyMappingLookup;
> 
> # Internal deserializer, use case unknown
> Field net/minecraft/world/level/storage/loot/LootDataType.f_278485_ changed its type from Ljava/util/function/BiFunction; to Lorg/apache/commons/lang3/function/TriFunction;
> 
> # Has a public getter with the same type on both platform, direct field access is unnecessary
> Field net/minecraft/world/item/HorseArmorItem.f_41362_ changed its type from Ljava/lang/String; to Lnet/minecraft/resources/ResourceLocation;
> 
> # Registry methods that should only be called by FAPI
> Field net/minecraft/client/color/block/BlockColors.f_92571_ changed its type from Lnet/minecraft/core/IdMapper; to Ljava/util/Map;
> Field net/minecraft/client/color/item/ItemColors.f_92674_ changed its type from Lnet/minecraft/core/IdMapper; to Ljava/util/Map;
> Field net/minecraft/client/particle/ParticleEngine.f_107293_ changed its type from Lit/unimi/dsi/fastutil/ints/Int2ObjectMap; to Ljava/util/Map;
> Field net/minecraft/world/item/alchemy/PotionBrewing$Mix.f_43532_ changed its type from Ljava/lang/Object; to Lnet/minecraft/core/Holder$Reference;
> Field net/minecraft/world/item/alchemy/PotionBrewing$Mix.f_43534_ changed its type from Ljava/lang/Object; to Lnet/minecraft/core/Holder$Reference;
> 
> # Type broadened to all `Mob` instances by Forge, not sure if there's any way for backwards compat here
> Field net/minecraft/world/entity/ai/goal/RangedBowAttackGoal.f_25782_ changed its type from Lnet/minecraft/world/entity/monster/Monster; to Lnet/minecraft/world/entity/Mob;
> ```

Excellent! Thanks!

It may be a good idea to add transforms for any such changes Forge is making as a preventative measure. It shouldn't affect performance all too much, right?

**Comment by Su5eD** [comment]
Don't think so.

**Comment by Sollace** [comment]
Sorry, I just tried beta-4 and am still seeing the same error. I've added the client log for the new version

https://mclo.gs/V1RT8cu

**Comment by Su5eD** [comment]
Try deleting the `mods/.connector` folder and try again

**Comment by Sollace** [comment]
> Try deleting the `mods/.connector` folder and try again

Ah yep! It works now. Thanks!

**Comment by Su5eD** [comment]
For future reference, I've added a feature in 02d12c7f02cf844b09c18bd9259c4cc6cf2da165 to make sure the cache resets automatically when you update the mod without having to delete the folder
