### ISSUE TITLE
Mythic Metals incompatibility (rendering related)

### ISSUE THREAD

**Issue by SiverDX** [Sinytra/Connector#295]
### Mod Name

Mythic Metals

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mythicmetals

### Describe the bug

Crashes when trying to mine (at least with Celestial Pickaxe)

### Steps to reproduce

Seems like a different issue compared to the entity reach thing?
If not just close I guess

### Logs

https://gist.github.com/SiverDX/4e7c0ff03c677643fcbe082f124ae0b0

**Comment by Su5eD** [comment]
> NeoForge: net.neoforged:47.1.76

Use Forge 47.1.3
