### ISSUE TITLE
Aeroblender

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#299]
### Mod Name

Aeroblender

### Mod Homepage

https://modrinth.com/mod/aeroblender

### Describe the bug

aeroblender causing some sort of conflict w fabric

### Steps to reproduce

Install aether and aeroblender

### Logs

<script src="https://gist.github.com/Its-Just-Luci/f525256697bcf6ce30a3b0c8e70acfc6.js"></script>

**Comment by Xplodin** [comment]
Aeroblender works fine on my end, especially before the update today.
Ive noticed small bugs like world rendering in main menu causing crashes, but thats about it

**Comment by Its-Just-Luci** [comment]
> Aeroblender works fine on my end, especially before the update today. Ive noticed small bugs like world rendering in main menu causing crashes, but thats about it

I retried with all the latest updates to FFI and sinytra and the game still crashed, basically the same log as before.

**Comment by Xplodin** [comment]
> > Aeroblender works fine on my end, especially before the update today. Ive noticed small bugs like world rendering in main menu causing crashes, but thats about it
> 
> I retried with all the latest updates to FFI and sinytra and the game still crashed, basically the same log as before. It looks like I have terrablender fabric installed, reinstalled it w forge and that seemed to have worked

I found that basically no biome mods work with connector that are forge.
Im unsure if this is the same case.
Example: Biomes o plenty just refuses to let the game boot

**Comment by Its-Just-Luci** [comment]
> > > Aeroblender works fine on my end, especially before the update today. Ive noticed small bugs like world rendering in main menu causing crashes, but thats about it
> > 
> > 
> > I retried with all the latest updates to FFI and sinytra and the game still crashed, basically the same log as before. It looks like I have terrablender fabric installed, reinstalled it w forge and that seemed to have worked
> 
> I found that basically no biome mods work with connector that are forge. Im unsure if this is the same case. Example: Biomes o plenty just refuses to let the game boot

The issue is closed, but regions unexplored is running fine for me on forge
