### ISSUE TITLE
Cull Leaves

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#300]
### Mod Name

Cull Leaves

### Mod Homepage

https://modrinth.com/mod/cull-leaves

### Describe the bug

Game crashes at startup

### Steps to reproduce

Install Cull Leaves and midnight lib (its api iirc)

### Logs

<script src="https://gist.github.com/Its-Just-Luci/501ec223c94001eabb182fda60c8bf0d.js"></script>

**Comment by StormDragon-64** [comment]
if you need a cull leaves mod right now, use cull less leaves. It works perfectly fine, and even has compatibility with the sodium/embeddium video settings menu if you have embeddium installed.

**Comment by Su5eD** [comment]
Tested to work with Connector beta 17 using [Cull Leaves 3.2.0 - Forge 1.20+](https://modrinth.com/mod/cull-leaves/version/3.2.0-forge) and [MidnightLib 1.4.1 - Forge 1.20](https://modrinth.com/mod/midnightlib/version/1.4.1-forge).

![image](https://github.com/Sinytra/Connector/assets/51261569/822af26a-42a6-4598-b1de-56f80934e62d)
