### ISSUE TITLE
TexTrue's Rubidium Options

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#301]
### Mod Name

TexTrue's Rubidium Options

### Mod Homepage

https://modrinth.com/mod/textrues-rubidium-options/version/1.0.3+mc1.20.1

### Describe the bug

game crashes on boot

### Steps to reproduce

boot game with mod

### Logs

<script src="https://gist.github.com/Its-Just-Luci/72d110303693cc67667eee8c74df4e5f.js"></script>

**Comment by forgolotl** [comment]
give us logs + forge version + connecter version + ffapi version + other mods  u use that u think are related to rubidium

**Comment by Su5eD** [comment]
Tested to work with Connector beta 15 and FFAPI 0.89.0+1.9.17+1.20.1
