### ISSUE TITLE
Game crash when using Minecells

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#302]
### Describe the bug

L-click on any blocks of minecells will crash my game(it only happens on survival mode, which it won't happens when i'm on creative mode)

### Bug showcase video
https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3YvcyFBdHRfV09jMXBjUEZoUUJDNnZFZHlLZC1zUHZxP2U9MDg3UVpl.mp4

### Logs

https://pastebin.com/zn65C7x3

**Comment by Su5eD** [comment]
NeoForge is not yet supported. Use Forge 47.1.3
