### ISSUE TITLE
Crash with Rubidium 0.7.0a (0.7.1) and rendering problem

### ISSUE THREAD

**Issue by BigBull-H3RO** [Sinytra/Connector#305]
### Mod Name

Rubidium 0.6.5 and 0.7.0a

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/rubidium 
https://www.curseforge.com/minecraft/mc-mods/industrial-revolution 
https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin

### Describe the bug

When placing the blocks of Industrial Revolution, the textures are not rendered. Also, in Rubidium version 0.7.0a, right-clicking on the Industrial Revolution blocks causes the game to crash.

### Steps to reproduce

1. Setup Connector and Forgified Fabric API
2. Install [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/4684247), [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/4742613) and [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files/4719981)
3. To trigger the crash, place a block of Industrial Revolution with a gui and right-click on it.

https://github.com/Sinytra/Connector/assets/132926832/50bc3034-3cfe-4e77-99e3-d29d216402fe

### Logs

https://gist.github.com/BigBull-H3RO/18911ecb53c1202a275cac9f30d71951

**Comment by RoomAlex68** [comment]
This didn't happened to me when I used Rubidium 0.6.5 but 0.7.0a crashed for me. Do you not have Oculus 1.6.4 installed for Rubidium 0.6.5? But I recommend using Embeddium since it fixes Rubidium 0.7.0a's incompatibilities.

**Comment by BigBull-H3RO** [comment]
I do not understand the purpose of your comment. I have written which mods I have used. I have now tried the whole thing again with Rubidium 0.6.5 and in combination with Oculus 1.6.4, as well as with Embeddium. All of them have the same rendering problem. When testing with Rubidium 0.7.0 the game crashes when I try to right click on the invisible block. The crash also happens with Rubidium 0.7.0a as described.

**Comment by RoomAlex68** [comment]
Because Rubidium 0.7.0 and 0.7.0a have many mod Incompatibilities. So use embeddium for better mod compatibility.

**Comment by Asek3** [comment]
Rubidium 0.7.1 now is compatible with Connector

**Comment by BigBull-H3RO** [comment]
I have tested Rubidium 0.7.1 and when I start the game it crashes.
https://gist.github.com/BigBull-H3RO/0c9a99b946d7eb4e7416e271f0d9a691

**Comment by Leclowndu93150** [comment]
Use embeddium

**Comment by BigBull-H3RO** [comment]
> Use embeddium

With embeddium I have the rendering problem

**Comment by RoomAlex68** [comment]
> I have tested Rubidium 0.7.1 and when I start the game it crashes.
> https://gist.github.com/BigBull-H3RO/0c9a99b946d7eb4e7416e271f0d9a691

Did you not have oculus installed?

**Comment by BigBull-H3RO** [comment]
> > I have tested Rubidium 0.7.1 and when I start the game it crashes.
> > https://gist.github.com/BigBull-H3RO/0c9a99b946d7eb4e7416e271f0d9a691
> 
> Did you not have oculus installed?

No, I have now tested it with oculus and embeddium the rendering problem still persists. With Rubidium 0.7.1 and oculus the game still crashes.

**Comment by Su5eD** [comment]
I am getting very similar results on fabric:
- The crash you're getting is a result of industrial revolution bundling an outdated version of [noindium](https://github.com/Luligabi1/NoIndium) for 1.19
- Industrial Revolution experiences rendering issues with sodium when used without indium installed. This applies to forge and Rubidium as well. Currently, there is no available FRAPI compat mod for Rubidium on 1.20.1

**Comment by Su5eD** [comment]
This can now be fixed by installing [Lazurite](https://github.com/Su5eD/Lazurite) alongside Embeddium, which provides FRAPI support for mods that require it.
