### ISSUE TITLE
Essential

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#307]
### Mod Name

Essential

### Mod Homepage

https://essential.gg/en/

### Describe the bug

Game crashes prior to title screen, essential updater appears some times

### Steps to reproduce

1. Install essential
2. ???
3. profit (crash :( )

All versions of essential, FFI and Sinytra are current and updated as of 10:33:10 Eastern Standard time

### Logs

https://gist.github.com/Its-Just-Luci/85a577298267da94e884b21aafb64def

**Comment by Its-Just-Luci** [comment]
> Duplicate of whatever issue it was (i can't remember)

ah, I see. Hate that essential is closed source, total bull lol, closing now

**Comment by SystemlessDev** [comment]
This is not a Essential issue. You're missing a mod dependency. 

`[21Sep2023 10:29:36.739] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod �eaether_redux�r requires �6aeroblender�r �o0 or above�r
�7Currently, �6aeroblender�r�7 is �o�nnot installed`
