### ISSUE TITLE
forge 47.1.46 crash

### ISSUE THREAD

**Issue by ImpulsiveLad** [Sinytra/Connector#309]
### Describe the bug

random mixin crash on 47.1.46

### Steps to reproduce

I got this crash after breaking maybe 40 soul sand with a shovel, probably not from it. Have a look.

### Logs

https://crashy.net/f4781992-dba8-4e55-9d30-f715638aecdb

**Comment by ImpulsiveLad** [comment]
Same sorta crash in 47.1.76,

https://crashy.net/827cd1cc-038d-4408-a925-acf0a5fc4a69

Got it from trying to break a cherry wooden plank

**Comment by Xplodin** [comment]
use forge 47.1.3

**Comment by lSherozl** [comment]
> ### Describe the bug
> random mixin crash on 47.1.46
> 
> ### Steps to reproduce
> I got this crash after breaking maybe 40 soul sand with a shovel, probably not from it. Have a look.
> 
> ### Logs
> https://crashy.net/f4781992-dba8-4e55-9d30-f715638aecdb
> 
> ### Additional context
> _No response_

This mod works best on 47.1.3

**Comment by Su5eD** [comment]
Use Forge 47.1.3 as explained in #42
