### ISSUE TITLE
Feature Request - Mod opt out

### ISSUE THREAD

**Issue by Smartin-b** [Sinytra/Connector#31]
Hey, certain mods might want to disable parts or even the whole mod if loaded by connector due to compat or other reasons.
For Example https://github.com/PacifistMC/Forgix enables the merging of forge and fabric mods into one jar
Those jars shouldnt be loaded by Connector since the mod is already loaded by forge.
i am propising a optinal field in the fabric mod.json to stop connector from loading A mod entirely, so mods can add a opt out to prevent issues.

**Comment by Su5eD** [comment]
The way I'd go about this is ignoring any mods that are already being loaded by FML based on their mod id in the discovery phase. Connector already does this, expect it's being done for nested jars only. By adding an additional simple check, we can ignore any top level jars, too. This would prioritize Forge mods automatically without third-parties having to opt out manually.

**Comment by Smartin-b** [comment]
As far as i can currently see the loading behaviour of Connectors scans all fabric mods and adds them to forge before forge does its scans. So to implement your idea one would have to change that, since one would want to prevent the mod from beeing initialized at all.
Maybe im understanding things wrong though, modloading isnt something i have a lot of experience with.

**Comment by Smartin-b** [comment]
At least in my quick test
```java
    private static boolean shouldLoadFabricMod(JarTransformer.TransformableJar jar){
        if(jar.modPath().metadata().modMetadata().containsCustomElement("loadOnConnector")){
            return jar.modPath().metadata().modMetadata().getCustomValue("loadOnConnector").getAsBoolean();
        }
        if(FMLLoader.getLoadingModList().getModFileById(jar.modPath().metadata().modMetadata().getId()) != null){
            return false;
        }
        if(ConnectorUtil.DISABLED_MODS.contains(jar.modPath().metadata().modMetadata().getId())){
            return false;
        }
        return true;
    }
```
didnt work since FMLLoader doesnt have a modlist setup at this point.

**Comment by Su5eD** [comment]
I implemented a workaround to ensure our locator always runs last, after all jars and even nested jars have been discovered by FML.

https://github.com/Sinytra/Connector/blob/fdfb9ebd3c2d6d7bd8b6c428ada0aae6c3a9e4b7/src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorEarlyLocator.java#L36-L43

We can then build a list of candidate mod IDs in our locator by reading the `loadedMods` iterable provided to us.

https://github.com/Sinytra/Connector/blob/fdfb9ebd3c2d6d7bd8b6c428ada0aae6c3a9e4b7/src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorLocator.java#L60-L63

**Comment by Smartin-b** [comment]
huh, thanks, ill try that real quick

**Comment by Su5eD** [comment]
I tested this with the [More Axolotl Variants](https://www.curseforge.com/minecraft/mc-mods/mavm) mod which uses Forgix to package its jar, and it seems to work fine.
```patch
--- a/src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorLocator.java	(revision fdfb9ebd3c2d6d7bd8b6c428ada0aae6c3a9e4b7)
+++ b/src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorLocator.java	(revision ac2cf683e272792d51928e0002652571b446b4c2)
@@ -67,7 +67,10 @@
             .sorted(Comparator.comparing(path -> StringUtils.toLowerCase(path.getFileName().toString())))
             .filter(ConnectorLocator::locateFabricModJar)
             .map(rethrowFunction(p -> cacheTransformableJar(p.toFile())))
-            .filter(jar -> !ConnectorUtil.DISABLED_MODS.contains(jar.modPath().metadata().modMetadata().getId()))
+            .filter(jar -> {
+                String modid = jar.modPath().metadata().modMetadata().getId();
+                return !ConnectorUtil.DISABLED_MODS.contains(modid) && !loadedModIds.contains(modid);
+            })
             .toList();
         // Discover fabric nested mod jars
         List<JarTransformer.TransformableJar> discoveredNestedJars = discoveredJars.stream()
```

**Comment by Smartin-b** [comment]
yep, worked fine for my mod as well, i still would add the field in the fabric.mod.json just in case some mods have weird issues

**Comment by Su5eD** [comment]
Hmm, what about making use of the existing `breaks` or `conflicts` fields in fabric.mod.json? I could check them earlier for connector's id to stop the mod from loading completely if it lists connector as incompatible.

**Comment by Smartin-b** [comment]
Those are explicitly for warning or crashing in case of incompatibility, fabric doesnt have a native option to stop a mod from loading sadly. but ye, you could missuse the "conflicts" or "breaks" field that way, but im not a fan of missusing the fields personaly, its up to you if/how you want that in Connector

**Comment by Smartin-b** [comment]
I personally think thats exactly what a custom field in a fabric.mod.json is for.

**Comment by Su5eD** [comment]
Okay, but in case we disable a mod by its custom flag, we should also inform the user of incompatible mods via FML's warning screen (`Modloader#addWarning`).

**Comment by Smartin-b** [comment]
Does sound like a good idea, but the Modloader is not initialized during this phase, forge is giving me a
```java
Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraftforge/fml/ModLoader
 
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/dev.su5ed.sinytra.connector.locator.ConnectorLocator.shouldLoadFabricMod(ConnectorLocator.java:108)
 
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/dev.su5ed.sinytra.connector.locator.ConnectorLocator.lambda$scanMods$7(ConnectorLocator.java:73)
 
 ```
 when i try to access it via
 ```java
                 ModLoader.get().addWarning(new ModLoadingWarning(null, ModLoadingStage.CONSTRUCT,jar.modPath().metadata().modMetadata().getId()+ " is not compatible with Connector and was not loaded"));
            }
            ```
so maybe we just add a warning in the logs use StartupNotificationManager.addModMessage

**Comment by Su5eD** [comment]
Yes, it is too early to access fmlcore, which is on the PLUGIN layer. I'll see if I can come up with a solution.

**Comment by Su5eD** [comment]
Leaving my side idea here: The custom flag might be a good way to partially automate the mod compatibility thread via a github app / bot that would gradually search github for mod repos with this flag and add them to the list as incompatible.

**Comment by Su5eD** [comment]
Now that dependency support has been implemented, I think it would be a good idea to reconsider using dependency constraints to declare connector as incompatible. Besides not having to check for additional fields, it also nicely integrates with the mod dependency resolver and the loading error screen. An example incompatibility error would look like this:

![](https://github.com/Sinytra/Connector/assets/51261569/0016127e-722d-4db2-a1f6-2b89384cff33)
