### ISSUE TITLE
Some ModernFix mixins are not loaded

### ISSUE THREAD

**Issue by embeddedt** [Sinytra/Connector#310]
### Describe the bug

Many ModernFix mixins are not loaded at runtime with Connector installed

### Steps to reproduce

1. Install ModernFix 5.7.2 in a 1.20.1 instance.
2. Check the number of mixins loaded in the log message: `[ModernFix/]: Loaded configuration file for ModernFix 5.7.2+mc1.20.1: 63 options available`.
3. Add Connector to the same instance.
4. Check the number of mixins loaded: `[ModernFix/]: Loaded configuration file for ModernFix 5.7.2+mc1.20.1: 20 options available`.

My educated guess is that this is related to the sorcery you use to load Fabric Mixin at runtime.

**Comment by Su5eD** [comment]
I've modified mixintransmog to no longer require renaming mixin classes, which eliminates this and other reflection-related issues.

One thing I'd like to note is that the mixin memory leak fix fails to apply as a result of already being shipped by fabric mixin. Besides logging an error in the console, this should not present a problem.
```
[00:17:12] [main/ERROR] [ModernFix/]: Failed to patch mixin memory leak
java.lang.NoSuchFieldException: NO_GROUP
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?] {}
	at org.embeddedt.modernfix.platform.forge.ModernFixPlatformHooksImpl.injectPlatformSpecificHacks(ModernFixPlatformHooksImpl.java:106) ~[modernfix-forge-5.7.2+mc1.20.1.jar%23166!/:5.7.2+mc1.20.1] {re:classloading}
	at org.embeddedt.modernfix.core.ModernFixMixinPlugin.<init>(ModernFixMixinPlugin.java:71) ~[modernfix-forge-5.7.2+mc1.20.1.jar%23166!/:5.7.2+mc1.20.1] {re:classloading}
```

**Comment by embeddedt** [comment]
> no longer require renaming mixin classes, which eliminates this and other reflection-related issues.

That would definitely explain the problem since I use a relatively unconventional approach to discover mixins at load time.

> One thing I'd like to note is that the mixin memory leak fix fails to apply as a result of already being shipped by fabric mixin. Besides logging an error in the console, this should not present a problem.

Yup, this should be harmless as I designed it to fail fast if the field disappears one day. Glad to see Fabric Mixin being usable on Forge now, cheers. :slightly_smiling_face:
