### ISSUE TITLE
Game Crashes when attempting to break a block

### ISSUE THREAD

**Issue by Swazza810** [Sinytra/Connector#318]
### Describe the bug

Game Crashes when attempting to break a block in survival mode but doesn't crash in creative mode

### Steps to reproduce

1. Start World 
2. Tried to break a block in survival mode
3. Game crashes 
...

### Logs

https://gist.github.com/Swazza810/987e27c3fc11039bcf5ad44e9fdc58cc

### Additional context

I also removed every mod that I had on my pack except the sinytra connector and the forge fabric one and it stills crashes after attempting to break a block in survival

**Comment by Su5eD** [comment]
> Forge: net.minecraftforge:47.1.43

Use Forge 47.1.3 as explained in #42
