### ISSUE TITLE
Crash when using the "Avaritia Fabric" Infinity Hammer (Pickaxe)

### ISSUE THREAD

**Issue by Leclowndu93150** [Sinytra/Connector#319]
### Mod Name

Avaritia Fabric

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/avaritia-fabric

### Describe the bug

crash

### Steps to reproduce

1.take an infinity pickaxe
2. shift right click with it
3.get the hammer
break block in survival
crash
...

### Logs

https://crashy.net/013fbef7-1823-4c26-bd69-a0c9f95e6685

### Additional context

https://bytebin.lucko.me/KUVwikJYLK

**Comment by Su5eD** [comment]
The version of Forge you're using is too new. Please downgrade to 47.1.3 as instructed in the README

**Comment by Leclowndu93150** [comment]
thanks
