### ISSUE TITLE
Crash with FramedBlock when i place Casing block from Create mod

### ISSUE THREAD

**Issue by L1neHypeR** [Sinytra/Connector#321]
### Describe the bug

Conflicting default methods 

### Steps to reproduce

1.Place framed block - https://www.curseforge.com/minecraft/mc-mods/framedblocks
2.Place casing from the create mod near framed block - https://create.fandom.com/wiki/Casing
3.https://user-images.githubusercontent.com/145922134/270176009-82890c4b-1a97-4926-8fc4-f91574060b85.png
...

### Logs

Error: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraftforge/common/extensions/IForgeBlock.getAppearance net/fabricmc/fabric/api/block/v1/FabricBlock.getAppearance xfacthd/framedblocks/api/block/IFramedBlock.getAppearance

**Comment by L1neHypeR** [comment]
![image](https://github.com/Sinytra/Connector/assets/145922134/dbe41e1a-e5f0-4f77-b4fb-8cbe126e5f8c)
response from the creator of the Framed Block mod

**Comment by Su5eD** [comment]
Hi, I've applied some fixes in the meantime. Can you try using FFAPI version [0.89.0+1.9.19+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.89.0+1.9.19+1.20.1) to see if the issue persists?

**Comment by L1neHypeR** [comment]
it didn't work out :
The game crashed whilst batching chunks
Error: java.lang.IncompatibleClassChangeError: Method 'net.minecraft.world.level.block.state.BlockState net.fabricmc.fabric.api.block.v1.FabricBlockState.getAppearance(net.minecraft.world.level.BlockAndTintGetter, net.minecraft.core.BlockPos, net.minecraft.core.Direction, net.minecraft.world.level.block.state.BlockState, net.minecraft.core.BlockPos)' must be InterfaceMethodref constant

**Comment by L1neHypeR** [comment]
https://youtu.be/Nl6UUA1a6Bo - this video may help you

**Comment by Su5eD** [comment]
Fixed in FFAPI [0.89.0+1.9.20+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.89.0+1.9.20+1.20.1).

**Comment by L1neHypeR** [comment]
![image](https://github.com/Sinytra/Connector/assets/145922134/dd4b18c6-cd2f-433c-bc86-7b5c2232244d)
Problem solved, thanks for your help

**Comment by L1neHypeR** [comment]
![image](https://github.com/Sinytra/Connector/assets/145922134/8f67ade4-2a46-4b27-9cb2-37bbb34475db)
Hello again. 
When playing with multiplayer, the ping increases and kicks with this error.

**Comment by L1neHypeR** [comment]
Using new api and connector

**Comment by Su5eD** [comment]
Please open a new issue with reproduction steps and logs
