### ISSUE TITLE
Incompatible with the 1.20 version of firework frenzy

### ISSUE THREAD

**Issue by gitguette** [Sinytra/Connector#324]
### Mod Name

firework frenzy

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/firework-frenzy

### Describe the bug

The game does not launch with the 1.20 version of firework frenzy(unoffical)

### Steps to reproduce

1. Download the 1.20 version of firework frenzy [here](https://github.com/ApoWillow/FireworkFrenzy1.20)
2. Put the mod in your mods folder
3. Run minecraft
4. Crash

### Logs

https://mclo.gs/IQIPhE3

### Additional context

I have confirmed the mod works normally on 1.20.1 fabric.

**Comment by Su5eD** [comment]
You've linked the curseforge page of the mod, which does not, however, contain a 1.20 version of the mod. Where can I download one for testing?

**Comment by RoomAlex68** [comment]
Maybe check modrinth

**Comment by gitguette** [comment]
> You've linked the curseforge page of the mod, which does not, however, contain a 1.20 version of the mod. Where can I download one for testing?

[Github link](https://github.com/ApoWillow/FireworkFrenzy1.20), also provided under "steps to reproduce".

**Comment by Su5eD** [comment]
Oh I missed that, sorry
