### ISSUE TITLE
The biomes in Nature's Spirit can't be generated

### ISSUE THREAD

**Issue by Staticlp** [Sinytra/Connector#326]
### Mod Name

Nature's Spirit

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/natures-spirit

### Describe the bug

The biomes in Nature's Spirit can't be generated

### Steps to reproduce

1.Install TerraBlender-forge-1.20.1-3.0.0.169 and naturespirit-1.0-1.20.1
2.Create New world 
3.Locate any Nature's Spirit biome
4.No biome can be found

### Logs

https://gist.github.com/Staticlp/4e9c230d94c7de514935a4fd1b96ac1c

**Comment by murao-kun** [comment]
Use fabric TerraBlender.
