### ISSUE TITLE
Incompatible with Pehkui (Forge)

### ISSUE THREAD

**Issue by nebulazorua** [Sinytra/Connector#328]
### Mod Name

Pehkui

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/pehkui

### Describe the bug

When you try to run the game with Pehkui, FFAPI and Connector installed, the game crashes

### Steps to reproduce

1. Get Pehkui, FFAPI and Connector
2. Load the game
3. Crash

### Logs

https://mclo.gs/o9X2RoF

### Additional context

I am using the Forge version, not the Fabric version. The Fabric version, however, also doesn't work.

**Comment by nebulazorua** [comment]
Oh 47.1.3 and 47.1.30 isn't the same version
Right

**Comment by LoSilopante** [comment]
The issue persist when using the correct Forge version.
Minecraft crashes when Syntra Connector is loaded with either the Forge or Fabric release of Pehkui and every version of said mod (Pehkui-3.7.6 to 3.7.8).

Tested with:
Forge-47.1.3
Syntra-1.0.0-beta.19
Pehkui (Forge or Fabric)-(each version)
Connector Extras (with and without)

**Comment by Su5eD** [comment]
Tested to work with Connector beta 19, FFAPI 0.90.0+1.9.26+1.20.1 and Pehkui-3.7.8+1.20.1-forge

![pehkui](https://github.com/Sinytra/Connector/assets/51261569/360161dc-3368-4416-a9e7-17c3b65a8726)

**Comment by LoSilopante** [comment]
I see that my testing was flawed and that I've probably launched the game mistaking the Fabric version for the Forge one. Sorry for the inconvenience, although this doesn't change the Fabric release of Pehkui still being incompatible.
