### ISSUE TITLE
Tech reborn crash with create

### ISSUE THREAD

**Issue by tea103130** [Sinytra/Connector#329]
### Describe the bug

Tech reborn crash with create

### Steps to reproduce

Rendering a liquid tank crashes when create is installed with tech reborn
These are the mods I use
Connector-1.0.0-beta.15+1.20.1-full
ConnectorExtras-1.1.0+1.20.1
create-1.20.1-0.5.1.e
fabric-api-0.89.0+1.9.20+1.20.1
FluxNetworks-1.20.1-7.2.0.14
RebornCore-5.8.7
supermartijn642configlib-1.1.8-forge-mc1.20
supermartijn642corelib-1.1.12a-forge-mc1.20
TechReborn-5.8.7

### Logs

https://gist.github.com/tea103130/2fc825e1ebff804ab48a2501625ed7fe

### Additional context

[crash-2023-09-28_02.39.26-client.txt](https://github.com/Sinytra/Connector/files/12742198/crash-2023-09-28_02.39.26-client.txt)
Crash report

**Comment by Su5eD** [comment]
Fixed in [Forgified Fabric API 0.89.0+1.9.21+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.89.0+1.9.21+1.20.1).
