### ISSUE TITLE
Connecter Beta 17 Crashes on loading screen

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#333]
Crash log here:

![crash-2023-09-28_07.41.34-client.txt](https://github.com/Sinytra/Connector/files/12774003/crash-2023-09-28_07.41.34-client.txt)

**Comment by RoomAlex68** [comment]
Everything was working when I had connector beta 15 installed

**Comment by Su5eD** [comment]
Please open a new issue providing all the necessary information according to the mod compat template
