### ISSUE TITLE
Connecter Beta 17 crashes when initializing the game

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#335]
### Describe the bug

Connector Beta 17 crashes on loading screen 

### Steps to reproduce

1. Install connector beta 17 and Forgified Fabric API 1.9.22
2.  Boot up the game
3. Game crashes when Initializing game

Note: Forge 47.1.3 was installed 

### Additional context

This didn't happen when I had Connector Beta 15 installed and everything was working fine on that version.

**Comment by RoomAlex68** [comment]
Here is crash log:
[crash-2023-09-30_07.29.10-client.txt](https://github.com/Sinytra/Connector/files/12774994/crash-2023-09-30_07.29.10-client.txt)

**Comment by Su5eD** [comment]
Please list the mods you're using

**Comment by RoomAlex68** [comment]
![crash-2023-09-30_07.29.10-client.txt](https://github.com/Sinytra/Connector/files/12775001/crash-2023-09-30_07.29.10-client.txt)

**Comment by RoomAlex68** [comment]
It didn't give me a crash log but I have the latest for it

Latest Log here:
![2023-09-30-7.log.gz](https://github.com/Sinytra/Connector/files/12775010/2023-09-30-7.log.gz)

**Comment by RoomAlex68** [comment]
There were no other mods installed but these 2
