### ISSUE TITLE
Crash on Arclight server

### ISSUE THREAD

**Issue by Loopdream123** [Sinytra/Connector#337]
### Mod Name

Arclight(Forge+bukkit) server

### Mod Homepage

https://github.com/IzzelAliz/Arclight

### Describe the bug

Crash on Arclight server

### Steps to reproduce

1.Install Connector-1.0.0-beta.17+1.20.1-full and fabric-api-0.89.0+1.9.22+1.20.1
2.Start server

### Logs

https://gist.github.com/Loopdream123/948e8bb88fb25abed020ebccc505da03

### Additional context

Connector-1.0.0-beta.15+1.20.1-full and fabric-api-0.89.0+1.9.20+1.20.1 can barely run on Arclight light server with very many bugs.

When Connector and ForgifiedFabricAPI get updated to the latest version,The server can't be started.

**Comment by Su5eD** [comment]
Hybrids are not supported, sorry. Please use the vanilla/official server.
