### ISSUE TITLE
Auditory sounds don't work(1.20.1)

### ISSUE THREAD

**Issue by gitguette** [Sinytra/Connector#339]
### Mod Name

Auditory

### Mod Homepage

https://github.com/TheQwerDev/auditory/

### Describe the bug

Block sounds(tested with brick and obsidian) are the same as vanila.

### Steps to reproduce

1. Download mod from github link(unofficial 1.20 port)
2. Use alongside connector
3. Place and destroy an obsidian block 

### Logs

No log

**Comment by Su5eD** [comment]
Tested to work on connector beta 17 and FFAPI 0.89.0+1.9.22+1.20.1
