### ISSUE TITLE
Client Side Crash with Recent Beta 18 Build. Rendering Entity Crash

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#341]
### Describe the bug

Crashes Client SIde

### Steps to reproduce

Join server on recent beta 18 build
Crash 
Crash Report: https://pastebin.com/3CbbFKFm

### Logs

https://pastebin.com/qxDN3qiC

**Comment by rainysux** [comment]
Also have noticed theres alot of "corrected ID mismatch on class...."

**Comment by rainysux** [comment]
I would like to add that everything works in single player

**Comment by Su5eD** [comment]
Can you reproduce this with only connector and minecells installed?

**Comment by rainysux** [comment]
I am not sure if its from minecells, it was just a hunch due to the logs. @Su5eD

**Comment by rainysux** [comment]
All these mods worked perfectly fine before using connector 18, 15 works fine.

**Comment by Su5eD** [comment]
Does beta 17 or 16 work?

**Comment by rainysux** [comment]
would you like me to try 16

**Comment by Su5eD** [comment]
Yes please, that would help

**Comment by rainysux** [comment]
Doesnt seem to crash on 16, however there are ALOT of errors that come up when startinf backup the world in the server

**Comment by rainysux** [comment]
wait i just tried 18 your recnet build and it seems to work

**Comment by rainysux** [comment]
Yea, I just tried more and it works, maybe because of the ffapi update?

**Comment by Su5eD** [comment]
Maybe, it's a possibility

**Comment by rainysux** [comment]
Thank you for your hard work, it seems like its good to go. I will mark this as complete
