### ISSUE TITLE
[1.20.1] Soulslike Weaponry Crash

### ISSUE THREAD

**Issue by HaizUber** [Sinytra/Connector#342]
### Describe the bug

crashes due to soulslike weaponry "Could not execute entrypoint stage 'main' due to errors, provided by 'soulsweapons'!"

### Steps to reproduce

1.Download and install Marium Soulslike Weaponry[SW 0.9.9.7-1.20-fabric] (https://modrinth.com/mod/mariums-soulslike-weaponry/version/0.9.9.7-1.20.1-fabric)
2. Download and install Connector 1.0.0-beta.17+1.20.1
3. Launch
4. Crash
...

### Logs

https://gist.github.com/HaizUber/0189043d94156a1c5e4b23c7a35ab769

### Additional context

Could not execute entrypoint stage 'main' due to errors, provided by 'soulsweapons'!

Forge 47.1.3
Embeddium 0.1.12
Oculus 1.6.9
Forgified Fabric API 0.89.0+1.9.22+1.20.1
Connector 1.0.0-beta.17+1.20.1

can i also ask whats causing this? maybe an incompatibility with a mod?

**Comment by Su5eD** [comment]
> Caused by: dev.booky.stackdeobf.mappings.RemappedThrowable: GeckoLib was initialized too early!

You need to use the fabric version of geckolib. However, that comes with its own issues. Please see #231 for full details on the state of geckolib on connector
