### ISSUE TITLE
Terramine Incompatibility because of architectury fabric required however architectury fabric is Incompatible

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#345]
Mod Links here:
https://www.curseforge.com/minecraft/mc-mods/terramine

https://www.curseforge.com/minecraft/mc-mods/architectury-api

Crash report here:
![crash-2023-10-01_17.34.48-fml.txt](https://github.com/Sinytra/Connector/files/12778646/crash-2023-10-01_17.34.48-fml.txt)

**Comment by Su5eD** [comment]
Pojav launcher is not supported

**Comment by RoomAlex68** [comment]
Am not even using pojavlauncher

**Comment by Su5eD** [comment]
Doesn't matter; FCL and pojav are both non-standard launchers that won't receive support

**Comment by RoomAlex68** [comment]
The Connector mod and Forgified Fabric API work with them.
