### ISSUE TITLE
Immersive Portals crashes when Initializing the game

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#346]
Mod Link here:
https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod

Crash log here:
![crash-2023-10-01_18.04.21-client.txt](https://github.com/Sinytra/Connector/files/12778757/crash-2023-10-01_18.04.21-client.txt)

**Comment by Su5eD** [comment]
Pojav launcher is not supported
