### ISSUE TITLE
[Broken Mod] CIT Resewn

### ISSUE THREAD

**Issue by Leclowndu93150** [Sinytra/Connector#347]
### Describe the bug

The mod loads but it appears that the feature is broken

### Steps to reproduce

```
type=item
items=hostilenetworks:prediction
texture=zombie_pristine.png
nbt.ExtraAttributes.id=hostilenetworks:zombie

```
The path in correct as well as the NBT

### Logs

https://pastebin.com/DVA59Ekw

### Additional context

https://www.curseforge.com/minecraft/mc-mods/cit-resewn

**Comment by Leclowndu93150** [comment]
![Screenshot_2023-10-02-09-03-30-179_dev beefers vendetta-edit](https://github.com/Sinytra/Connector/assets/73310949/9eaa3778-7df9-43da-9eaa-f6df589fbb51)

**Comment by Leclowndu93150** [comment]
assets/minecraft/citresewn/cit

**Comment by Leclowndu93150** [comment]
> > ```
> > type=item
> > items=hostilenetworks:prediction
> > texture=zombie_pristine.png
> > nbt.ExtraAttributes.id=hostilenetworks:zombie
> > ```
> 
> Please provide more exact steps to reproduce. I don't know where to put this text

You have to put it in kubejs/assets
![image.png](https://github.com/Sinytra/Connector/assets/73310949/6e014547-f4d3-48f0-bb82-3ed08c29302e)

**Comment by gitguette** [comment]
found it, [here](https://www.curseforge.com/minecraft/mc-mods/forge-cit/files)

**Comment by Leclowndu93150** [comment]
Bro im not gay but i love you
