### ISSUE TITLE
mod prevents vivecraft from loading completly

### ISSUE THREAD

**Issue by Nathan22211** [Sinytra/Connector#349]
### Mod Name

Vivecraft 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/vivecraft

### Describe the bug

Mod causes vivecraft to not load completly and crash the game

### Steps to reproduce

1.add vivecraft to an instance with sintra connector
2. load the game
3. after crashing, check the logs for a lot of mentions of vivecraft classes
...

### Logs

https://gist.github.com/Nathan22211/78c6a67ccb8b2476e4bd0575744ced92

**Comment by Su5eD** [comment]
> Mod ID: 'forge', Requested by: 'fabric_message_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.47'

Please downgrade forge to 47.1.3
