### ISSUE TITLE
Enhanced Block Entities: ``java.lang.IllegalStateException: Render layers can only be set during client loading! This might ideally be done from FMLClientSetupEvent.``

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#35]
### Mod Name

Enhanced Block Entities

### Mod Homepage

https://modrinth.com/mod/ebe/versions

### Describe the bug

Game crashes when changing EBE settings

### Logs

https://mclo.gs/R0u6aNO

**Comment by Su5eD** [comment]
So apparently mods do register render layers past client setup, too. I'm afraid the best way to prevent this error is to remove the check put in place by Forge. Mods can register render layers for any blocks and not just their own, so there is no way to figure out which mod called the method and let only fabric mods pass.
