### ISSUE TITLE
Terramine Incompatibility 

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#352]
Mod Link here:
https://www.curseforge.com/minecraft/mc-mods/terramine

It gave me a error because of a mixin 

Crash log here:
![crash-2023-10-03_06.15.47-fml.txt](https://github.com/Sinytra/Connector/files/12795163/crash-2023-10-03_06.15.47-fml.txt)

**Comment by Su5eD** [comment]
> com.tungsten.fcl

As I have previously stated, unofficial, android launchers like Pojav or FCL are NOT supported.
