### ISSUE TITLE
Cultural delights fabric

### ISSUE THREAD

**Issue by gitguette** [Sinytra/Connector#355]
### Mod Name

Cultural delights fabric(forge version is 1.19 only)

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/cultural-delights-fabric

### Describe the bug

Game crashes on startup.

### Steps to reproduce

Use cultural delights fabric with beta 18 connector and latest version of ffapi.

### Logs

https://mclo.gs/xI0pObU

**Comment by RoomAlex68** [comment]
Can you send the link beta 18 version of connector

**Comment by gitguette** [comment]
you can find them in the actions tab of github, be sure to use the full jar and not the sources one

**Comment by melontini** [comment]
Farmer's delight [Fabric] add-ons do not work with the Forge version. This is not an issue with Connector.

**Comment by RoomAlex68** [comment]
Yeah you need Farmers Delight(Fabric) to play the addon and tou cannot use Farmers Delight(Forge) addons with it

**Comment by Su5eD** [comment]
> Caused by: java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/block/WildCropBlock

As was said, you need the fabric version farmer's delight. iirc it should be compatible
