### ISSUE TITLE
Bclib Problems with radium/canary?

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#356]
### Mod Name

Radium/Canary

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/radium-reforged

### Describe the bug

Crashes on server start up

### Steps to reproduce

Try Running it on a server
It crashes

### Logs

https://pastebin.com/fWtNSyaA

**Comment by Cixon** [comment]
not trying to bash developers here but they're not optimistic when it comes mod-compatibility. your best bet is using a mod called DoesPotatoTick which effectively doesn't tick entities based on a set radius via config. TPS performance is phenomenal and you can whitelist entities from the list to tick normally.

Source:
https://www.curseforge.com/minecraft/mc-mods/doespotatotick

**Comment by rainysux** [comment]
Are you talking about BCLIB, or the lithium ports about not caring about compatibility? Because bclib works fine with lithium on fabric so I just assumed it was a connector problem maybe

**Comment by dima-dencep** [comment]
> not trying to bash developers here but they're not optimistic when it comes mod-compatibility.

We always try to fix incompatibilities. In particular, this crash has been fixed in [this](https://modrinth.com/mod/radium/version/0.12.1+git.915d28d) radium release.
And it's not related to Bclib...
