### ISSUE TITLE
Axe mines as slow as hand when using Variant Crafting Table and BetterNether

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#361]
### Mod Name

Variant Crafting Table

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/more-crafting-tables-for-forge

### Describe the bug

Very small issue, and odd I might say, but when using these two mods, when using an axe it is as slow as punching with a hand on ANY wood. Wooden planks, wood log, ect

### Steps to reproduce

Download the mods, 
Play the game
Mine a tree or any wood plank  with an axe, notice its slow

### Logs

n/a

**Comment by Su5eD** [comment]
This is an issue with the More Crafting Tables mod, which adds a **required** `mctb:blossom_crafting_table` tag entry to `forge:workbench` that doesn't actually exist. Better nether then adds this workbench tag to `minecraft:mineable/axe`.
```
- #minecraft:mineable/axe
  - #forge:workbench              <- added by betternether
    - mctb:blossom_crafting_table <- nonexistent block
```
When the tag loader fails to locate `blossom_crafting_table`, it triggers a domino effect which stops both `forge:workbench` and `minecraft:mineable/axe` from loading. You can easily recreate this without connector by adding the `forge:workbench` tag to `minecraft:mineable/axe` via a datapack. [Here's](https://github.com/Sinytra/Connector/files/12837267/testdatapack.zip) the one I used for testing (might require game restart to take effect).
