### ISSUE TITLE
AmbientSounds crash at laucher load screen

### ISSUE THREAD

**Issue by llAlexiussll** [Sinytra/Connector#362]
### Mod Name

AmbientSounds

### Mod Homepage

https://modrinth.com/mod/ambientsounds/versions

### Describe the bug

Minecraft dont even open

### Steps to reproduce

1.Download the Ambient Sounds v5.2.21
2.Download Creative Core 2.11.1
3.Try to run Minecraft
...

### Logs
https://gist.github.com/llAlexiussll/ecbd790152df519647040bc125d662e6

### Additional context
I think the issue must be Creative Core mod because i try to use other mod with that and i get the same problem

_No response_

**Comment by Su5eD** [comment]
Please provide your debug.log

**Comment by llAlexiussll** [comment]
done i provide you my .Log

**Comment by llAlexiussll** [comment]
i find the problem my bad im sorry

**Comment by llAlexiussll** [comment]
thanks for your attetion
