### ISSUE TITLE
Grind Enchanment not working

### ISSUE THREAD

**Issue by llAlexiussll** [Sinytra/Connector#363]
### Describe the bug

Grind enchanment do not get loaded as mod

### Steps to reproduce

1.Download Grind Encahnment
2.Download TaxFreelevels 
3.Run Minecraft
4.Create a World
5.Try to use the mod

### Additional context

I do a report about this mod about a week i said it not open minecraft back then now if i put that mod in my folder minecraft open but the mod is not been loaded is like i never put thaht mod in my folder like is gone

https://github.com/Sinytra/Connector/assets/141466172/7f5b6a03-8cd2-4f42-bf7d-b74abf9e102d

**Comment by Su5eD** [comment]
Works fine for me. Do you any other mods installed?

**Comment by rainysux** [comment]
Works for me as well both client and server, definitely mod incompat

**Comment by llAlexiussll** [comment]
Yeah it works to me now so not worry

**Comment by llAlexiussll** [comment]
thank you anyway
