### ISSUE TITLE
 Terrestria and Traverse Incompatibility with Terrablender(Forge) Regions Unexplored(Forge) and Biomes O Plenty(Forge)


### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#364]
Crash log here:

![crash-2023-10-07_12.47.50-client.txt](https://github.com/Sinytra/Connector/files/12838822/crash-2023-10-07_12.47.50-client.txt)

**Comment by Su5eD** [comment]
> -Xbootclasspath/a:/data/user/0/com.tungsten.fcl/app_runtime

As I have previously said, android launchers are NOT supported. Please use a desktop launcher, such as the official one, or prism.

**Comment by RoomAlex68** [comment]
But can you try to at least reproduce this?

Because I don't have a PC or a Laptop

Sinytra connector and Forgified Fabric API work on FoldCraftLauncher and PojavLauncher

**Comment by enzogfaria** [comment]
I just had the same problem and found the solution. Replace regions unexplored and terrablender with the fabric versions, DO NOT use the forge versions, this worked for me

**Comment by Su5eD** [comment]
Terrablender forge will work is you install connector extras

**Comment by enzogfaria** [comment]
the problem doesn't seem to be with Terrablender but with RegionsUnexplored
