### ISSUE TITLE
Cardinal Component Incompatibility

### ISSUE THREAD

**Issue by zeid0ne** [Sinytra/Connector#365]
### Mod Name

Cardinal component

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api

### Describe the bug

Still have a crash in last versions of everything 

### Steps to reproduce

1. Install cardinal component api
2. Launch minecraft

i can provide a .zip of my instance if needed

### Logs

https://pastebin.com/0HVZ2xPg

**Comment by Su5eD** [comment]
Fixed in 1a47e049297b3f62d3963123ab2700ca12e93fbc, will be available in the next release.

See also: #136
