### ISSUE TITLE
Replay mod Footage doesn't show Epic Fights mod animations

### ISSUE THREAD

**Issue by SelimGOZ** [Sinytra/Connector#366]
### Describe the bug

Epic Fights mod animations dont show up on replay mod footage

### Steps to reproduce

1. Mods works and runs great
2. I record a little vid of me using epic fights mod using replay mod
3. I check the footage and the mods animations don't work in there but the sound does
...

### Additional context

In the modpack I have Epic Fight Mod, Forgfied Fabric API, Fabric API, Rubidium, Sinytra Connector, and Replay Mod and no recourse pack

**Comment by WitherTM** [comment]
could you try with embeddium instead of Rubidium?

**Comment by SelimGOZ** [comment]
i did and it doesn't work still

**Comment by Molonalte** [comment]
Is this working or not yet fixed?
keep it up guys! and stay safe!

**Comment by SelimGOZ** [comment]
It won't be able to be fixed because im guessing its a replay mod issue and not forge + fabric mod issue

**Comment by Wanderer70** [comment]
> It won't be able to be fixed because im guessing its a replay mod issue and not forge + fabric mod issue

Hey, I am using Embeddium alongside Replay Mod and there is a gui overlay in the recordings. Does the same thing happen to you as well?

**Comment by notalexyt** [comment]
If you use Epic Fight, just die and respawn with combat mode activated, and then animations will work.
Well, they won't work too good (walking animation issues) but attacks work good. At least in my case

**Comment by Su5eD** [comment]
Merging into #556 to better keep track of issues related to ReplayMod.
