### ISSUE TITLE
unknown crash

### ISSUE THREAD

**Issue by mateus3c** [Sinytra/Connector#368]
### Describe the bug

the log files doesnt seem to give any irelevant nfo about this crash.. 

### Steps to reproduce

1. Launch game
2. Crashes before load
[latest.log](https://github.com/Sinytra/Connector/files/12842436/latest.log)
[console.log](https://github.com/Sinytra/Connector/files/12842440/console.log)

**Comment by mateus3c** [comment]
so are not getting compat with blueprint? ;-;

**Comment by rainysux** [comment]
he fixed it, thats why it says "completed"

**Comment by mateus3c** [comment]
> he fixed it, thats why it says "completed"

but the fix wasnt released yet, right?
