### ISSUE TITLE
Better end biome ClassCastException

### ISSUE THREAD

**Issue by WillIFAS** [Sinytra/Connector#37]
### Describe the bug

When i try to go to the end island for the biomes it crashes and there is no grass or foliage, better nether some biomes and most grass/moss blocks wont spawn in

### Steps to reproduce

1.
2.
3.
...

### Logs
The game crashed whilst feature placement
Error: java.lang.ClassCastException: class org.betterx.bclib.api.v2.levelgen.biomes.BCLBiome cannot be cast to class org.betterx.betterend.world.biome.cave.EndCaveBiome (org.betterx.bclib.api.v2.levelgen.biomes.BCLBiome is in module bclib@3.0.13 of loader 'TRANSFORMER' @28ee882c; org.betterx.betterend.world.biome.cave.EndCaveBiome is in module betterend@4.0.10 of loader 'TRANSFORMER' @28ee882c)
_No response_

### Additional context

I don’t know if this is happening for everyone but i hope there is a fix for this

**Comment by Cixon** [comment]
sad

**Comment by pablothegreat** [comment]
Same Issues as described, attached error log
[crash-2023-08-24_12.56.11-server.txt](https://github.com/Sinytra/Connector/files/12429154/crash-2023-08-24_12.56.11-server.txt)

**Comment by Cixon** [comment]
![IMG_8366](https://github.com/Sinytra/Connector/assets/69068153/ad8893d8-a8be-47dc-8437-c9ffc21ec53d)
