### ISSUE TITLE
Unofficial 1.20.1 port of ExtraSounds for Fabric causing crash on start-up

### ISSUE THREAD

**Issue by mrdialphone** [Sinytra/Connector#370]
### Mod Name

Lonefelidae16's UNOFFICIAL 1.20.1 port of ExtraSounds for Fabric

### Mod Homepage

https://github.com/lonefelidae16/extra-sounds

### Describe the bug

 ExtraSounds port crashing Minecraft on start-up

### Steps to reproduce

1. Put all three mods (Sinytra Connector, Forgified Fabric API, Lonefelidae16's ExtraSounds 1.20.1 port) into the mods folder, using 47.1.3 version of forge and 1.20.1 version of Minecraft.
2. Start up Minecraft as usual, with the three mods in the mods folder.
3. Wait for Minecraft to begin loading, then the crash occurs. 
...

### Logs

https://pastebin.com/aMPNWH0t

### Additional context

Hello, I wasn't sure if I could create an issue with this mod because it's an unofficial port but I love this mod and I'm sure others do as well so I decided to open up an issue. I attempted using the ExtraSounds 1.20.1 port by Lonefelidae16 in forge 47.1.3 (with version mc 1.20.1 of course) as told in the description of the Sinytra Connector, and I used the most up-to-date files for both Sinytra Connector and Forgified Fabric API. The crash occurs during the loading process. I tested with just the three mods in the mods folder, (Sinytra Connector, Forgified Fabric API, and ExtraSounds port) I also reinstalled Minecraft in case something in my saves/config could have been causing the issue, however the crash still happens. I also tested using Fabric normally with just ExtraSounds and the port appears to work fine in Fabric, the crash only appears when using the Sinytra Connector and Forgified Fabric API. (AKA using forge)

**Comment by Su5eD** [comment]
Try using Connector [beta 18](https://modrinth.com/mod/connector/version/1.0.0-beta.18+1.20.1) from Modrinth. The CurseForge release is still awaiting manual approval.
