### ISSUE TITLE
Log Spam and Crashing upon Respawn

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#371]
### Describe the bug

Game is crashing when trying to respawn, which I believe is linked to the fabric rendering api, and immersive portals (maybe?) though the issue perists with dimension stacking disabled, and shaders turned off?

### Steps to reproduce

dying then trying to respawn causes a massive lag spike and almost always leads to a game crash.

### Logs

https://gist.github.com/Its-Just-Luci/f6153eed59914fb02c34d0627ad91e62

**Comment by Su5eD** [comment]
Can you please upload a crash report?

**Comment by Its-Just-Luci** [comment]
[crash-2023-10-10_16.00.28-server.txt](https://github.com/Sinytra/Connector/files/12872717/crash-2023-10-10_16.00.28-server.txt)
[crash-2023-10-10_15.58.23-server.txt](https://github.com/Sinytra/Connector/files/12872718/crash-2023-10-10_15.58.23-server.txt)
[crash-2023-10-10_17.59.30-client.txt](https://github.com/Sinytra/Connector/files/12872719/crash-2023-10-10_17.59.30-client.txt)

There's a couple from last night, when that log was taken

**Comment by Its-Just-Luci** [comment]
curiously, switching to Embeddium from Rubiddium causes the crash to stop, however it also causes terrain to not load at all, shaders or no shaders, so IDK if it's a fix as much as it is a different issue, but I'll also add the log for this one as well

![2023-10-11_12 04 01](https://github.com/Sinytra/Connector/assets/57868183/a5964769-4764-4359-87af-12cf7e50282f)
[latest.log](https://github.com/Sinytra/Connector/files/12872735/latest.log)
[debug.log](https://github.com/Sinytra/Connector/files/12872736/debug.log)

**Comment by Its-Just-Luci** [comment]
[crash-2023-10-11_12.16.19-client.txt](https://github.com/Sinytra/Connector/files/12872816/crash-2023-10-11_12.16.19-client.txt)

Here's my first crash report with Embeddium, upon digging down (maybe entering the other dimension stacked underneath the overworld?) the game crashes

**Comment by Su5eD** [comment]
Which mods are needed to reproduce this issue? Ideally in a clean instance without anything else installed
