### ISSUE TITLE
Despite my efforts to sort through my mod list, Minecraft keeps crashing

### ISSUE THREAD

**Issue by DorkClassic** [Sinytra/Connector#372]
### Describe the bug

Minecraft keeps crashing with an Error Log 1 before it opens. I have tried to sort through the error logs myself but its still not working

### Steps to reproduce

1. Open up Minecraft on Curseforge
2. Click Play
Then, Minecraft crashes with an Error Log 1 
...

### Logs

https://pastebin.com/ujSLmJw6

**Comment by Su5eD** [comment]
The log does not contain mentions of a crash. Please provide a crash report

**Comment by rainysux** [comment]
it says something about optifine if youre using optifine, dont use it, use embeddium/rubidium + oculus

**Comment by Su5eD** [comment]
> OptiFine ZIP file URL: union:/C:/Users/jonat/curseforge/minecraft/Instances/Testing%20OMGGGG/mods/OptiFine_1.20.1_HD_U_I5.jar%23216!/

Optifine if not supported
