### ISSUE TITLE
Sophisticated backpacks tank upgrade bug

### ISSUE THREAD

**Issue by llAlexiussll** [Sinytra/Connector#374]
### Describe the bug

liquid gets bug using tank upgrade

### Steps to reproduce

1.
2.
3.
...

### Logs
https://gist.github.com/llAlexiussll/c51fbe036000c1e58b98bcb3d6f0778c

_No response_

### Additional context

This bug happens after i  change forge and connector version i was using connector beta 5 if i remember but the game was crashing when i click any block but anyways so i change  connector version to the last version and everything was good with the liquid textures like water, lava, exp before the change but after that the textures get glitch i ask to the owner of the mod but he said is not a problem from his mod so i want to know if this bug is caused by connector mod
![2023-10-11_23 32 51](https://github.com/Sinytra/Connector/assets/141466172/d5f8fd50-57ae-47fc-a56a-21794bab4d13)

**Comment by Su5eD** [comment]
Works on Connector beta 19 and FFAPI 0.90.0+1.9.25+1.20.1
