### ISSUE TITLE
Recent Build Beta 19 OWOLIB/Minecells Doesnt Work

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#375]
### Mod Name

Owolib/Minecells

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/owo-lib/files?version=1.20.1

### Describe the bug

Crashes on startup, Exit Code 1, It crashes with owo by itself however with minecells it will also crash due to it depending on it, however there are somethings in the log about minecells

### Steps to reproduce

Start the game with connector,ffapi,extras and owo/minecells or just owo
Crash
 Debug log: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/world/level/levelgen/feature/OreFeature::m_225171_(Lnet/minecraft/world/level/WorldGenLevel;Lnet/minecraft/util/RandomSource;Lnet/minecraft/world/level/levelgen/feature/configurations/OreConfiguration;DDDDDDIIIII)Z has incompatible changes at opcode 682 in callback owo.mixins.json:Copenhagen from mod (unknown)->@Inject::malding(Lnet/minecraft/world/level/WorldGenLevel;Lnet/minecraft/util/RandomSource;Lnet/minecraft/world/level/levelgen/feature/configurations/OreConfiguration;DDDDDDIIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ILjava/util/BitSet;Lnet/minecraft/core/BlockPos$MutableBlockPos;I[DLnet/minecraft/world/level/chunk/BulkSectionAccess;IDDDDIIIIIIIDIDILnet/minecraft/world/level/chunk/LevelChunkSection;IIILnet/minecraft/world/level/block/state/BlockState;Ljava/util/Iterator;Lnet/minecraft/world/level/levelgen/feature/configurations/OreConfiguration$TargetBlockState;)V.
 Expected: [I, Ljava/util/BitSet;, Lnet/minecraft/core/BlockPos$MutableBlockPos;, I, [D, Lnet/minecraft/world/level/chunk/BulkSectionAccess;, I, D, D, D, D, I, I, I, I, I, I, I, D, I, D, I, Lnet/minecraft/world/level/chunk/LevelChunkSection;, I, I, I, Lnet/minecraft/world/level/block/state/BlockState;, Ljava/util/Iterator;, Lnet/minecraft/world/level/levelgen/feature/configurations/OreConfiguration$TargetBlockState;]

### Logs

https://pastebin.com/EjuZfwxZ

**Comment by mateus3c** [comment]
what? the latest release is beta 18, there isnt any beta 19 yet

**Comment by rainysux** [comment]
"Soon to be 19" its a maven build

**Comment by mateus3c** [comment]
> "Soon to be 19" its a maven build

how did you make that?

**Comment by zeid0ne** [comment]
I am not sure if it's the best but this is how i do :

- clone the repo 
- run gradlew.bat
- use the following command ".\gradlew build --no-daemon"
- the mod generated is Connector\build\libs\Connector-XXXXX-full.jar

**Comment by rainysux** [comment]
the easiest way i can explain is join the discord, go to github updates section, then look for the latest "build success on master" and it should show a maven build tbat downloadable. You dont have to build it yourself, just unzip the file and it should give you the jar

**Comment by mateus3c** [comment]
> the easiest way i can explain is join the discord, go to github updates section, then look for the latest "build success on master" and it should show a maven build that is downloadable. You dont have to build it yourself, just unzip the file and it should give you the jar

thank you! whats the discord server link?

**Comment by Su5eD** [comment]
You can find it in the readme, join [here](https://discord.gg/mamk7z3TKZ)
