### ISSUE TITLE
Cloth config fabric no longer recognized

### ISSUE THREAD

**Issue by gitguette** [Sinytra/Connector#376]
### Describe the bug

I have been using the fabric version of cloth config, as the forge version doesn't seem to work with fabric mods. However, after updating connector and forgified fabric api to their latest versions, mods were suddenly complaining about missing cloth config api.

### Steps to reproduce

1. Use connector beta 18, forgified fabric api version 0.8.9.
2. Update to beta 19 and ffapi version 0.9
3. Cloth config api no longer working

**Comment by Su5eD** [comment]
Please describe the issue, "Cloth config api no longer working" is not enough to reproduce, test, or fix the issue

**Comment by rainysux** [comment]
The forge cloth should work it has an auto detection of some sort to do clothconfig 2. When I played on Beta 19, it worked even with cloth config fabric and forge mods. You should show either what mods you used.

**Comment by gitguette** [comment]
> Please describe the issue, "Cloth config api no longer working" is not enough to reproduce, test, or fix the issue

get the following error:
Missing or unsupported mandatory dependencies:
	Mod ID: 'cloth_config', Requested by: 'bettercombat', Expected range: '[11.0.0,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'blur', Expected range: '*', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'invmove', Expected range: '[11,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'inventorio', Expected range: '[11,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'simplyswords', Expected range: '[11.1.106,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'combatroll', Expected range: '[11,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'betterf3', Expected range: '[11.0.0,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'artifacts', Expected range: '[11.0.99,)', Actual version: '[MISSING]'

**Comment by Su5eD** [comment]
> as the forge version doesn't seem to work with fabric mods

What do you mean by this? What's broken?

**Comment by SuperStefan97** [comment]
I have found two incompatibilities so far discussed in the Discord. The first one is related to Marium's Soulslike Weaponry, as only using geckolib fabric, connector, connector extras, ffapi alongside Soulslike weaponry makes the game crash with an error type 1 message
[latest.log](https://github.com/Sinytra/Connector/files/12908911/latest.log)

**Comment by SuperStefan97** [comment]
Hi! Thanks for doing this for the mod community. I found two mod incompatibilities. 
The first one is regarding Parzi's Star Wars mod alongside Goblin Trade (forge version), I also had installed Framework which is a dependency for Goblin Traders and Ragna Goblin Traders, an addon for Goblin traders alongside all connector-related mods on their latest builds. Here is the crash:
[crash-2023-10-15_01.51.28-client.txt](https://github.com/Sinytra/Connector/files/12908951/crash-2023-10-15_01.51.28-client.txt)
It was discussed in the discord, and it seems to do with a "libzoomers" mod, which wasn't installed by me and must be a built-in library

**Comment by SuperStefan97** [comment]
The second one it's with Marium's Soulslike Weaponry. When using it by it's own, it works, but alongside other gecko-using mods, it crashes. 
[crash-2023-10-15_02.05.35-client.txt](https://github.com/Sinytra/Connector/files/12908968/crash-2023-10-15_02.05.35-client.txt)
Thank you for checking this and working on this magnum project.
