### ISSUE TITLE
[1.20.1] Connector 19 Crash

### ISSUE THREAD

**Issue by HaizUber** [Sinytra/Connector#379]
### Describe the bug

crashes on startup process exited with code 2, attached is latest.log

### Steps to reproduce

1.Install Connector 19 and Connector Extras 1.4.0
2.Crash
3.
...

### Logs

https://gist.github.com/HaizUber/fa3742a0bc949620eb65f260b1bcaa0c

### Additional context

can provide more info like modlist and other stuff related with the log itself when needed, no crash-report is generated

**Comment by rainysux** [comment]
its exordium

**Comment by Su5eD** [comment]
Use the [Forge version](https://modrinth.com/mod/exordium/version/1.2.1-1.20.1) of exordium, which is compatible
