### ISSUE TITLE
Gecko Fabric not rendering Forge Gecko Mod (Epic Samurai in this case)

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#380]
### Describe the bug

Gecko Fabric not rendering Forge Gecko Mods in server

### Steps to reproduce
crash report
https://pastebin.com/H1G7AxRs
Looks like epic samurais but could be multiple

### Additional context
latest log
(https://pastebin.com/Vy8cMiQv)

**Comment by rainysux** [comment]
could be because of cosmetic armor, i have epic samurais helmet on me which says in the log

**Comment by rainysux** [comment]
Can confirm its when putting on a samurai jade helmet

**Comment by Su5eD** [comment]
Geckolib has ongoing issues regarding cross-platform compat, which are being tracked in #231. Closing this in favor of that issue.
