### ISSUE TITLE
Connector crashes servers when trying to start

### ISSUE THREAD

**Issue by minimuppen** [Sinytra/Connector#382]
### Describe the bug

When starting a server with Sinytra Connector installed it crashes

### Steps to reproduce

1. Get a server
2. Put Sinytra Connector in it with Forgified fabric api
3. Complete

### Logs

https://mclo.gs/sSv6CiI

### Additional context

I am using a custom modpack that i made myself for this which also may be causing issues. If the steps to reproduce do not work then just ask me to give you the modpack and i will.

**Comment by FrozenDragon0** [comment]
Did you manage to figure out how to fix this? Or is this still an issue?
