### ISSUE TITLE
models don't load with connecter enabled

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#385]
### Describe the bug

models don't load with connecter enabled

### Steps to reproduce

1. load my modpack
2.start game and models don't load
3.
...
 

### Additional context

[latest.log](https://github.com/Sinytra/Connector/files/12920677/latest.log)
logs are here

**Comment by rainysux** [comment]
its Ducklib

**Comment by rainysux** [comment]
https://www.curseforge.com/minecraft/mc-mods/duclib adds entity models and animations that are unlike java models

**Comment by Thunderrock424242** [comment]
i don't have a mod called duclib

**Comment by rainysux** [comment]
"Mixin config duclib.mixin.json does not specify "minVersion" property"

**Comment by Thunderrock424242** [comment]
is that the issue tho?

**Comment by rainysux** [comment]
its a guess, with the context of models not rendering and that being the first error, its just a hunch, however I am not 100% sure. You should do a debug log

**Comment by rainysux** [comment]
theres also alot of supplementaries, moonlight in it, or doggy talents

**Comment by Thunderrock424242** [comment]
i have been using them before and no problom happens its only when i enable this mod

**Comment by rainysux** [comment]
it'd be helpful for the dev to know which mod is causing the issue. All these mods I have said are guesses so you can determine which one is the one conflicting it. Which is why you should do your part in trying get it to solved.

**Comment by Thunderrock424242** [comment]
It started happening after this update

**Comment by Thunderrock424242** [comment]
The new update

**Comment by Su5eD** [comment]
Which mods exactly are required to reproduce this issue?

**Comment by Thunderrock424242** [comment]
so i am using a big modpack so i will just send you the link to the file since i can't send it here casue its big

**Comment by Thunderrock424242** [comment]
https://legacy.curseforge.com/minecraft/modpacks/wilderness-odyssey/files/4809326 this is it

**Comment by Thunderrock424242** [comment]
That link may not work give me a sec

**Comment by Su5eD** [comment]
Please use binary search or otherwise track down the exact mod(s) causing the issue

**Comment by Su5eD** [comment]
Closing as cannot reproduce
