### ISSUE TITLE
Frostiful is incompatible with beta 19

### ISSUE THREAD

**Issue by Nokunami** [Sinytra/Connector#386]
### Mod Name

Frostiful

### Mod Homepage

https://modrinth.com/mod/frostiful

### Describe the bug

Crashes during launch.

### Steps to reproduce

1. have connector and forgified fabric api, frsotiful and thermoo
2. launch game
3. crash
...

### Logs

https://mclo.gs/V1B4zWo

### Additional context

all mods are up to date at the time of writing this issue.

**Comment by Su5eD** [comment]
Fixed in bd1dc3e3a3c5c87a923fd22eb1d3e51b93be13e1

**Comment by RoomAlex68** [comment]
Crashes on connector beta 21

**Comment by RoomAlex68** [comment]
Crashed on connector beta 22
