### ISSUE TITLE
Valkyrien Skies crashes

### ISSUE THREAD

**Issue by enzogfaria** [Sinytra/Connector#389]
### Mod Name

Valkyrien Skies

### Mod Homepage

https://modrinth.com/mod/valkyrien-skies

### Describe the bug

game crashes when starting

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/rHPNYRV

### Additional context

crashes in forge and fabric version

**Comment by Su5eD** [comment]
This looks like an issue between valkyrien skies and embeddium. Does it also occur without connector installed?

**Comment by enzogfaria** [comment]
oh, this is the problem, from what I tested it only works with rubium 0.6.5, thx

**Comment by cmy2008** [comment]
> oh, this is the problem, from what I tested it only works with rubium 0.6.5, thx哦，这就是问题所在，根据我的测试，它仅适用于 rubium 0.6.5，thx

How did you make it work? I installed the rubidium 0.6.5 in Minecraft 1.20.1, but it didn't work, same crash errors.  Is my Valkyrien Skies mod too new? I'm using 2.13 version, tell me more, thanks!
