### ISSUE TITLE
Crash with Rubidium 0.6.5

### ISSUE THREAD

**Issue by dddse2** [Sinytra/Connector#39]
### Mod Name

Rubidium

### Mod Homepage

https://modrinth.com/mod/rubidium/

### Describe the bug

Crashes when loading game

### Steps to reproduce

1.install Rubidium 0.6.5
2.Open the game
3.Crash
...

### Logs

https://pastebin.com/iscnCmP0

### Additional context

Forge Version 47.1.3
Mods:
Connector-1.0.0-beta.4+1.20.1-full
fabric-api-0.86.1+1.8.1+1.20.1
rubidium-0.6.5
Details:
There's no crash report be created in the crash, and the latest version of rubidium did not crash like this.

**Comment by Fiz-Victor** [comment]
is there any hs_err_pid_xxxx.log generated in the minecraft folder?

**Comment by Wudji** [comment]
However, the game runs flawlessly with Rubidium 0.7.0a...

**Comment by dddse2** [comment]
> is there any hs_err_pid_xxxx.log generated in the minecraft folder?

no, the game always crash in the "Scanning mod candidates" progress
there's no more logs can be found

**Comment by dddse2** [comment]
> However, the game runs flawlessly with Rubidium 0.7.0a...

sadly, 0.7.0a has many compatibility issues with some mods like create
that's why I choose the old one

**Comment by Su5eD** [comment]
I've investigated this and found out Rubidium 0.6.5 contains a conflicting package from fabric loader, which causes a split package error at runtime.

> Rubidium 0.6.5 crashes due to a package conflict, where rubidium includes classes from fabric loader without relocating them. It looks like they're only using the version util classes though, so I'm not sure what prevented them from shadowing properly. We cannot relocate our classes, as they are expected to be available by dependents.

- Sinytra/ForgifiedFabricAPI#22

Unfortunately, as a result, the Forgified Fabric API (and Connector) are incompatible with Rubidium 0.6.5. If newer versions of it cause compatibility issues with mods, they should be reported to the authors so they can be fixed properly. It is the best way forward.

**Comment by parka27** [comment]
rubbidion have so many problems of compabiltyes with the most part of the mods its better embeddium the mod fails with oculus (iris) but the most part of the mods can load with embeddium I'm sorry if I wrote wrong, my level of English is like that of an anemone.
