### ISSUE TITLE
Fabric Automessage 1.0.0

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#392]
### Mod Name

Fabric Automessage 1.0.0

### Mod Homepage

https://modrinth.com/mod/fabric-automessage/version/1.0.0

### Describe the bug

don't correctly work

### Steps to reproduce

1.Install mod
2. Create a message for output in the config and do /automessage reload on the server, all commands work, but the mod does not output the message

### Logs

https://mclo.gs/Du8eQr0

**Comment by DonorKrovi** [comment]
https://mclo.gs/87vPo9N
Run with only this mod

**Comment by Su5eD** [comment]
Hmm, how much RAM have you allocated to minecraft? Could be either too low or too high.

**Comment by DonorKrovi** [comment]
> Hmm, how much RAM have you allocated to minecraft? Could be either too low or too high.

![image](https://github.com/Sinytra/Connector/assets/60231586/1772ce12-42f3-40a1-b3fc-bd02f968d7e9)

**Comment by DonorKrovi** [comment]
How much do you recommend using?

**Comment by DonorKrovi** [comment]
![image](https://github.com/Sinytra/Connector/assets/60231586/9097c451-ffe9-4d19-b9da-97a197cf1f46)

**Comment by Su5eD** [comment]
Can you try something lower like `-Xmx4G` instead?

**Comment by Su5eD** [comment]
Okay, could you try this on your pc locally, and see if it still times out? I wonder if it's related to hosting/virtualization in any way, since transformation runs on multiple software threads.

**Comment by DonorKrovi** [comment]
https://mclo.gs/oqdnk1G

**Comment by DonorKrovi** [comment]
No C2ME

https://mclo.gs/plvBZZC

**Comment by DonorKrovi** [comment]
> Seems like you're using an outdated version of connector (beta 8). I recommend updating to the latest version, which is currently beta 20

https://mclo.gs/QvUm0AY

I don't understand how I managed to install such an old version

But the problem is urgent, there are messages, but they are not sent to the chat
![image](https://github.com/Sinytra/Connector/assets/60231586/b503a149-41fb-4557-bd5e-d155c03013c2)
