### ISSUE TITLE
better fabric console

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#393]
### Mod Name

better-fabric-console-mc1.20.1-1.1.6

### Mod Homepage

https://modrinth.com/mod/better-fabric-console

### Describe the bug

Crash server for startup

### Steps to reproduce

1.install and start server

### Logs

https://mclo.gs/cKctljL

**Comment by Su5eD** [comment]
Unfortunately, this cannot be fixed on our end. The mod relies on replacing the `SysOut` appender of the log4j config, which is called `Console` on Forge instead. Even if we tried to alias it, it would still be difficult to determine where / how it was replaced.
