### ISSUE TITLE
Map Rendering issue, Forge Supplementaries and Fabric Better End/Nether

### ISSUE THREAD

**Issue by marpet6137** [Sinytra/Connector#394]
### Describe the bug

The game crashes upon viewing a map/treasure map

### Steps to reproduce

1. install Forge version of Supplementaries and its required library
2. Install Fabric version of Better End & Better Nether and their respective required dependencies
3. Go in-game, grab a map from creative menu or grab any treasure map and view it.
4.
java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 128
	at net.mehvahdjukaar.supplementaries.common.misc.ColoredMapHandler$ColorData.getEntry(ColoredMapHandler.java:145) ~[supplementaries-1.20-2.6.13.jar%23178!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.supplementaries.common.misc.ColoredMapHandler$ColorData.m_8055_(ColoredMapHandler.java:353) ~[supplementaries-1.20-2.6.13.jar%23178!/:?] {re:mixin,re:classloading}

### Logs

https://pastebin.com/7y9NRc99

### Additional context

Better End/Nether works as they should in the context that they add and make drastic overhaul to the dimensions and Supplementaries work and all their respective gadgets, however, they do not seem to like the map rendering at all.

**Comment by Su5eD** [comment]
Good news, this was a bug in supplementaries that has now been [fixed](https://github.com/MehVahdJukaar/Supplementaries/commit/73d497b51566e1889b0e3f63868a1aa6813bcc30#diff-1af2731c469b8ae1dbebb3d9312eb7c05b80dd5837702cd047e26a8f99220806R147-R149) in versions 2.6.14 and newer. I tested this with 2.6.16 and it no longer crashes.
