### ISSUE TITLE
HuskHomes

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#395]
### Mod Name

HuskHomes

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/huskhomes

### Describe the bug

Server crash for launch

### Steps to reproduce

1.put mod and start server

### Logs

https://mcpaste.io/04dccd632b811a37

**Comment by Su5eD** [comment]
Tested to work on beta 20 (dev), will be fixed in the next release
