### ISSUE TITLE
Connected Glass Incompat with new FFAPI

### ISSUE THREAD

**Issue by SuperStefan97** [Sinytra/Connector#397]
### Mod Name

Connected Glass

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/connected-glass

### Describe the bug

The mod used to work with Forgified Fabric API 25... with the new 26 version crashes

### Steps to reproduce

1.Install Connected Glass for Forge
2. Install the new FFAPI version 26 instead of 25
3. Startup
4. Crash
...

### Logs

https://pastebin.com/hs9SisjS

### Additional context

It works fine with 25 version of FF Api, I even entered the same crashed world with that version (after erasing 26 version) and doesn't crash anymore

**Comment by SuperStefan97** [comment]
![2023-10-19_20 41 08](https://github.com/Sinytra/Connector/assets/96614259/71c371fb-5525-4b19-984b-31f3abe467c8)
![2023-10-19_20 41 16](https://github.com/Sinytra/Connector/assets/96614259/67d7c608-ffde-4c7a-90ea-2601b9270991)
It also makes some block textures get weird when getting away from them, I thought it was on Alex's Caves side, but downgrading the FFAPI to version 25 solved that problem too

**Comment by Su5eD** [comment]
I cannot reproduce this. Does it occur with only connected glass installed?

**Comment by SuperStefan97** [comment]
Sorry for my late response, and yes, it happens with that mod only, downgrading to FFAPI 25 solves it without any issue

**Comment by Su5eD** [comment]
Did you have a sodium equivalent installed when you tested this? Rubidium or embeddium?

**Comment by SuperStefan97** [comment]
Nop, I don't use them because I have seen they break a lot of mods. I have seen there's trouble with other mods that have connected textures for blocks, maybe that has to be? With Connected Glass the glass blocks render as a big wall of transparent glass of the selected color (like how the glass looks with optifine installed)

**Comment by Su5eD** [comment]
Can you please post a crash log from an instance where only the necessary mods are installed? It might help track down mixins

**Comment by SuperStefan97** [comment]
Hi! Sorry for my late answer, the game doesn't even make a crash log with only FFAPI, Sinytra, Extras, Connected Glass and SuperMartinLib (the dependency of connected glass) here is the .latest tho 
[latest.log](https://github.com/Sinytra/Connector/files/13197096/latest.log)

**Comment by Su5eD** [comment]
I've tried creating a [Prism Launcher](https://prismlauncher.org) instance with the exact same mods from above, but it still didn't crash. Can you importing my instance and see if you get the same results?

[Connected Glass Test.zip](https://github.com/Sinytra/Connector/files/13204545/Connected.Glass.Test.zip)

**Comment by SuperStefan97** [comment]
Sure, do I install it the same way I would install a mod?

**Comment by Su5eD** [comment]
You need to install prism launcher and import the instance zip

**Comment by Su5eD** [comment]
Any updates on this? Sadly, I'm still unable to reproduce the issue

**Comment by SuperStefan97** [comment]
Hi! Sorry, yesterday night I was trying the newest build of all your connector mods, and now the issue is gone. Thanks for all your work, it might had to do with connected textures
