### ISSUE TITLE
Minecraft errors each time when trying to open with the 2 mods only

### ISSUE THREAD

**Issue by KnotZero** [Sinytra/Connector#398]
### Describe the bug

Tried several times to start minecraft with only the connector and forgified fabric but i get this error each time

### Steps to reproduce

1) Basically putting both mods in and playing but getting this error
[222.txt](https://github.com/Sinytra/Connector/files/13056417/222.txt)

NOTES: no other mod is installed just those 2, version is also 47.1.30
![image](https://github.com/Sinytra/Connector/assets/144356897/d4316138-c95e-4116-965a-12b90269b5df)
![image](https://github.com/Sinytra/Connector/assets/144356897/c415bebe-aa3d-42d6-993b-b3e0d7e64a8c)

**Comment by Su5eD** [comment]
Use Forge version 47.1.3, not 47.1.30
