### ISSUE TITLE
FrozenLib (Ex Wilder Wild) Incompatibility

### ISSUE THREAD

**Issue by murao-kun** [Sinytra/Connector#40]
### Mod Name

Wilder Wild

### Mod Homepage

https://modrinth.com/mod/wilder-wild

### Describe the bug

Crash on start up.

### Logs

https://pastebin.com/pg7rRWPw

**Comment by murao-kun** [comment]
Updated crash report.
https://mclo.gs/paljg7R

**Comment by Nekkok** [comment]
Still an issue with Forgified Fabric API 0.89.0+1.9.21+1.20.1 + Connector 1.0.0-beta.17+1.20.1: https://mclo.gs/JgmnBvg

This is my first time posting about your work, so I want to thank you for your dedication <3 I hope I can see someday WW working on Forge, it's best Fabric mod hands down

**Comment by mateus3c** [comment]
I can confirm it still is an issue with the newest version of Forgified Fabric Api + Connector + Connector Extras

**Comment by Treetrain1** [comment]
This may help for a potential fix
Wilder Wild embeds the mod FrozenLib, which is actually what's incompatible.
FrozenLib's `AxeItem` mixin targets `Optional.isPresent()` in the `onUse()` method

In fabric, it targets here
![image](https://github.com/Sinytra/Connector/assets/39657565/4ecfddf8-5516-4008-ba5a-0d16226f4391)

Forge adds more `Optional.isPresent()` checks before that point, so the mixin target is changed to the one's added by forge. This is what causes the error.
![image](https://github.com/Sinytra/Connector/assets/39657565/dbac60d0-5dab-4172-bff0-2f96e31402a0)

**Comment by mateus3c** [comment]
@Su5eD check this out, its a fix! :D

**Comment by Treetrain1** [comment]
Fixed in beta 21, this can be closed

using frozenlib, wilderwild, configurable everything, or simple copper pipes should no longer cause a crash

**Comment by mateus3c** [comment]
unfortunately it still causes crashes..
[latest.log](https://github.com/Sinytra/Connector/files/13091051/latest.log)

**Comment by enzogfaria** [comment]
you have to remove ww dependencies

**Comment by Treetrain1** [comment]
> unfortunately it still causes crashes.. [latest.log](https://github.com/Sinytra/Connector/files/13091051/latest.log)

use 2.1.10
until ffapi updates to 0.90.4

**Comment by enzogfaria** [comment]
I removed the dependency and it didn't crash, is there a problem?

**Comment by Treetrain1** [comment]
> I removed the dependency and it didn't crash, is there a problem?

yes, wilder wild 2.1.11 requires fapi 0.90.4 but ffapi is only at 0.90.0
use wilder wild 2.1.10

**Comment by mateus3c** [comment]
I have also just changed the fabric api version on the manifest to the one used by the forgified fabric api and it works perfectly
