### ISSUE TITLE
Bobby does not seem to render over 32 chunks, regardless of settings?

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#400]
### Describe the bug

When set to 2048 chunks, bobby seems to hit a limit at around 32 chunks

### Steps to reproduce

Install bobby, and test higher-than 32 chunk render distances next to 32.

### Additional context

No crash log available as game runs fine with bobby installed and configured, it just does not appear to be _doing_ anything https://modrinth.com/mod/bobby/versions using bobby 5.0.1 on 1.20.1

**Comment by Its-Just-Luci** [comment]
https://gist.github.com/Its-Just-Luci/6be03c557d942c189db74fbb0c0fe512 here's my logs, though as stated, there's no crash or even major error, the mod just doesn't do anything which is quite confusing

**Comment by Its-Just-Luci** [comment]
bumping as it's been about a week

**Comment by Su5eD** [comment]
Have you been able to reproduce this with only Bobby installed? Your log also mentions other mods that might be interfering

**Comment by kakashi1464** [comment]
i think better to use this port https://www.curseforge.com/minecraft/mc-mods/bobby-reforged

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

Additionally, I recommend using the official Forge port as suggested above.
