### ISSUE TITLE
Crashing on startup with Backslot

### ISSUE THREAD

**Issue by jorassicoso** [Sinytra/Connector#401]
### Mod Name

Backslot

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/backslot

### Describe the bug

when installing backslot the game crashes on startup

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/9gSp7Vc

**Comment by Su5eD** [comment]
The mod depends on amecsapi, which conflicts with Forge's keybind modifier system. I'll see if it's possible to create a bridged version in Connector Extras.

**Comment by Su5eD** [comment]
Fixed in Connector Extras [1.6.0](https://modrinth.com/mod/connector-extras/version/1.6.0+1.20.1), which now bundles a Forge port of Amecs API
