### ISSUE TITLE
REI & Fabric Language Kotlin Crash

### ISSUE THREAD

**Issue by uthw** [Sinytra/Connector#402]
### Mod Name

REI and Fabric Language Kotlin

### Mod Homepage

https://modrinth.com/mod/rei https://modrinth.com/mod/fabric-language-kotlin

### Describe the bug

The game crashes shortly after being launched with exit code 1. No crash report is made and there are no errors in the log

### Steps to reproduce

1. Add Fabric Language Kotlin, REI, and their dependencies
2. Launch the game

![image](https://github.com/Sinytra/Connector/assets/73855194/3f0aa1a2-ed40-417d-a490-0752450a7971)

### Logs

https://gist.github.com/uthw/7b08949806a607914a75ecd44a1111b6

### Additional context

Both mods work fine on their own

**Comment by Su5eD** [comment]
Please upload your debug.log or a crash report

**Comment by uthw** [comment]
REI + Fabric Language Kotlin work with Connector beta 20 but crash on beta 21

[latest.log](https://gist.github.com/uthw/90580391d4f33e8bf07ba8d93fb65bb7)
[debug.log](https://gist.github.com/uthw/5dc151cdd36b6d8685fd4400cdfa1e05)

Mod list is mostly the same as the initial report except for the versions of Connector, REI, and FFAPI. Changing the versions of the latter two to match the initial report still results in a crash

![Screenshot 2023-10-24 144226](https://github.com/Sinytra/Connector/assets/73855194/c804df18-f1f3-4a72-b818-e31a2bda7f4a)

**Comment by Su5eD** [comment]
Should be good to go now
