### ISSUE TITLE
Dawn Api/Promenade causes alexs caves generation to not work 

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#403]
### Describe the bug

causes alexs caves generation to not work, unable to find through /locate, maps or anything

### Steps to reproduce

Dawn Api alone is able to do this, which is required for promenade. Having the three causes this issue

**Comment by rainysux** [comment]
https://github.com/AlexModGuy/AlexsCaves/issues/210 Exact same issue, thats caused from other mods as well in my modpack as well.

**Comment by Su5eD** [comment]
Promenade embeds Biolith, which leads to the same issue as #396.
