### ISSUE TITLE
Console spam on server for each player joining  : Query ID 200 was received but no query has been associated in net.minecraft.network.Connection@7476c70b!

### ISSUE THREAD

**Issue by litjohn50** [Sinytra/Connector#405]
### Describe the bug

Console gets spammed and locks up a bit as players join

### Steps to reproduce

1. Run connector on a server (with mods is recommended)
2. Connect to the server.
3. Spam gets worse per player joining as there are more mods in the modpack

### Logs

https://gist.github.com/litjohn50/e5f10fe3e7e6369aa169fa55a505ff28

### Additional context

Full server Debug.log if you want it

https://gist.github.com/litjohn50/5789e674ad423e0067f3c3a024d729a9

Connector-1.0.0-beta.19+1.20.1-full.jar
ConnectorExtras-1.4.1+1.20.1.jar
fabric-api-0.90.0+1.9.25+1.20.1.jar
Forge:47.1.3

**Comment by Su5eD** [comment]
> with mods is recommended

Please track down the exact mods causing the issue

**Comment by Su5eD** [comment]
Patched in FFAPI
