### ISSUE TITLE
Voice Chat Interaction Incompatibility 

### ISSUE THREAD

**Issue by Skel200** [Sinytra/Connector#406]
### Mod Name

Voice Chat Interaction

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/voice-chat-interaction

### Describe the bug

mod does not load. the game launches but the mod doesn't load.

### Steps to reproduce

1. download mod
2. put it in mods folder with simple voice chat forge
3. see it fail
...

### Logs

https://gist.github.com/Skel200/91320315ed683316ab9d959174a38f5a

### Additional context

im using voice chat forge.

**Comment by Su5eD** [comment]
The integration mod requires using the fabric version of Simple Voice Chat to run. I've added a patch that fixes hud rendering for it, so everything works fine now with Simple Voice Chat (Fabric) and Voice Chat Interaction installed. If other issues show up with the fabric version of the mod, I'll consider adding a bridge to Connector Extras, but it's not required now
