### ISSUE TITLE
(shaders) shadowcopm error 

### ISSUE THREAD

**Issue by kekis1234** [Sinytra/Connector#408]
### Describe the bug

Light now working properly

### Steps to reproduce

Torches and other sources of light not having any light 

### Additional context

![изображение_2023-10-22_024914890](https://github.com/Sinytra/Connector/assets/148545221/feaea45f-69c1-4621-9d82-8784de795947)
![image](https://github.com/Sinytra/Connector/assets/148545221/1e2f7f35-5421-4767-abea-66522c387e52)
![image](https://github.com/Sinytra/Connector/assets/148545221/65e42e4b-4888-4c23-a9ac-918cc80c8290)

**Comment by Su5eD** [comment]
Duplicate of #409
