### ISSUE TITLE
(shaders) shadowcopm error 

### ISSUE THREAD

**Issue by kekis1234** [Sinytra/Connector#409]
### Describe the bug

Light now working properly,Torches and other sources of light not having any light 

### Steps to reproduce

Torches and other sources of light not having any light 

### Additional context

![изображение_2023-10-22_024914890](https://github.com/Sinytra/Connector/assets/148545221/feaea45f-69c1-4621-9d82-8784de795947)
![image](https://github.com/Sinytra/Connector/assets/148545221/1e2f7f35-5421-4767-abea-66522c387e52)
![image](https://github.com/Sinytra/Connector/assets/148545221/65e42e4b-4888-4c23-a9ac-918cc80c8290)

**Comment by Su5eD** [comment]
Please list the mods you're using

**Comment by kekis1234** [comment]
alex caves only

**Comment by Su5eD** [comment]
Does alex's caves provide shaders?

**Comment by kekis1234** [comment]
i dont think so, there only specific light in biomes like green or yellow,but on screenshots i was in default cave 
![image](https://github.com/Sinytra/Connector/assets/148545221/6085b133-1178-472a-9535-138ad17d79de)

**Comment by kekis1234** [comment]
is that counts as shader?

**Comment by Su5eD** [comment]
Do you have a shaders mod installed alongside alex's caves? Please list all mods you have installed, and please upload your logs as well, thanks.

**Comment by kekis1234** [comment]
![image](https://github.com/Sinytra/Connector/assets/148545221/6af9b734-7792-4d86-bee7-eaab9b51a6d4)
[latest.log](https://github.com/Sinytra/Connector/files/13064152/latest.log)
btw sky is full dark 
![image](https://github.com/Sinytra/Connector/assets/148545221/2860e213-6b9a-4d2f-9925-0d2190cecb11)

**Comment by rainysux** [comment]
alex caves has shaders complications

**Comment by rainysux** [comment]
also dont use optifine

**Comment by Su5eD** [comment]
Sorry, optifine is not compatible with FFAPI / Connector, or pretty much any other mod, as explained in #111. I recommend using Embeddium + Oculus instead.

**Comment by kekis1234** [comment]
i need to download Embeddium and oculus together?

**Comment by rainysux** [comment]
Yes
