### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by Jericho569** [Sinytra/Connector#410]
### Describe the bug

I've downloaded only the connector and forgified fabric, at their latest versions, and while the game starts fine when it's just those two, it crashes as soon as I try to have a Fabric mod active. Am I missing something or doing something wrong? I thought I just needed to drop them into the mod folder and the connector would make them work. Just for reference the only Fabric mods I have installed are Better Nether, Better End, Better FPS, Mythic Metals, and Immersive Portals. I've cycled through activating and deactivating each, and none work by themselves or together.

The game starts fine with Sintyra Connector and Forgified Fabric API, but as soon as there's an active fabric mod in my mod folder, it crashes on startup.

### Steps to reproduce

1.
2.
3.
...

**Comment by Su5eD** [comment]
Please upload your debug.log and a crash report
