### ISSUE TITLE
Incompat with Alex's Caves

### ISSUE THREAD

**Issue by MrCubicYT** [Sinytra/Connector#411]
### Mod Name

Alex's Caves

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/alexs-caves

### Describe the bug

Minecraft crashes on launch

### Steps to reproduce

1. Boot Minecraft with mods: Alex's Caves, Citadel (Dependency), Sinytra and Forgeified
2. It Crashes

### Logs

https://pastebin.com/24535mdR

**Comment by rainysux** [comment]
you need forge 1.47.1.3
