### ISSUE TITLE
[1.20.1] Sheets loaded to early crash?

### ISSUE THREAD

**Issue by HaizUber** [Sinytra/Connector#412]
### Describe the bug

Some other mod loaded the Sheets class to early, causing modded banner patterns and sherds to be invalid. Refusing to proceed further

### Steps to reproduce

1.Install Supplementaries 2.6.15, Connector 19, Forgified 0.90.0+1.9.26
2.Crash on joining world
...

### Logs

https://gist.github.com/HaizUber/bbd24169de5de21f35b54d83302d3579

### Additional context

It could be other mod than Supplementaries crashing this, modlist is in log
Tested that with Supplementaries 2.6.13 works fine

**Comment by rainysux** [comment]
this is due to Alexs Caves primordial pots. Its already a known issue https://gist.github.com/HaizUber/8217ccb3f39297286d2d122617859569
