### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by lordi-erez** [Sinytra/Connector#413]
### Describe the bug

it crashes on startup

### Steps to reproduce

1.
2.
3.
...

### Logs

https://paste.ee/p/sj85e

**Comment by Su5eD** [comment]
> net.minecraftforge.fml.ModLoadingException: Mod §eimmersiveengineering requires forge 47.1.54 or above
Currently, forge is 47.1.3

Immersive engineering requires a later version of forge than the one we support.
