### ISSUE TITLE
Incompatibility with Continuity

### ISSUE THREAD

**Issue by litjohn50** [Sinytra/Connector#414]
### Describe the bug

Rendering bugged causing a lot of mod issues.

### Steps to reproduce

1. Update to the newest FFAPI 
fabric-api-0.90.0+1.9.27+1.20.1.jar
2. launch mod pack I was running https://www.curseforge.com/minecraft/modpacks/towncraft/files/4809175
3. Load singleplayer world
4.  Examine rendering being bugged
...

### Logs

https://gist.github.com/litjohn50/9aca13bc1c6af0b0f364375d15bd70ca

### Additional context

Forge- 47.1.3
Fabric Mods:  (updated modlist)
continuity-3.0.0-beta.3+1.20.1.jar
chiselforge-1.6.0.jar

Mods
Connector-1.0.0-beta.19+1.20.1-full.jar
fabric-api-0.90.0+1.9.27+1.20.1.jar

Mods affected: 
domum_ornamentum-1.20-1.0.142-BETA-universal.jar
Croptopia-1.20.1-FORGE-2.3.2.jar
twilightforest-1.20.1-4.3.1860-universal.jar
productivebees-1.20.1-12.2.4.jar

and many others

Issue does not appear in fabric-api-0.90.0+1.9.26+1.20.1.jar

Rendering issue
![image](https://github.com/matthewperiut/Chisel-Reborn/assets/28884916/92fc68fd-4a3f-418f-9548-1507ca01c097)
![image](https://github.com/matthewperiut/Chisel-Reborn/assets/28884916/bf1ad31e-d867-41ce-b109-1daa69a73672)
![image](https://github.com/matthewperiut/Chisel-Reborn/assets/28884916/5ae168c4-f4bf-4efe-90d2-a919f9107031)
![image](https://github.com/matthewperiut/Chisel-Reborn/assets/28884916/28c8e593-27b8-4be0-99cf-ffd8d570bb34)
![image](https://github.com/Sinytra/Connector/assets/28884916/ac55fa44-f956-4e47-902e-4e4388427cf6)

**Comment by rainysux** [comment]
do you have any mods that use fabric

**Comment by litjohn50** [comment]
I have 

TechReborn-5.8.7.jar
chiselforge-1.6.0.jar <-chisel reborn

**Comment by litjohn50** [comment]
Hmm seems to be an incompatibility. With continuity-3.0.0-beta.3+1.20.1.jar
https://www.curseforge.com/minecraft/mc-mods/continuity

That was auto downloaded when I installed Chisel Reborn

**Comment by StormDragon-64** [comment]
This issue has been fixed as of testing with Continuity 3.0 beta 4 and Connector beta 20.

**Comment by litjohn50** [comment]
This does appear accurate and seems fixed.
