### ISSUE TITLE
Alex's Mobs Crash Due to Non-unique Mixin

### ISSUE THREAD

**Issue by mrdrewlego** [Sinytra/Connector#417]
### Mod Name

Alex's Mobs / Citadel

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

### Describe the bug

Attempting to load Alex's Mobs will crash on launch due to non-unique mixin between Alex's Mobs and Citadel.

### Steps to reproduce

1. Using Connector Beta 20, Citadel 2.4.5, and Alex Mobs 1.22.6
2. Launch the game and game will crash upon load attempt.
3. Does affect other mods that use citadel as a dependency with similar crash log between the mod and citadel.

### Logs

https://paste.gg/p/anonymous/a5cd71f4be5d4458a753350d0088f8ca

**Comment by No1129** [comment]
i get this with cloud storage and other older citadel mods

**Comment by wsxiya** [comment]
”Connector Beta 20“Crashes numerous mods

**Comment by Su5eD** [comment]
> ”Connector Beta 20“Crashes numerous mods

Which ones?

**Comment by wsxiya** [comment]
> > “连接器测试版 20”崩溃了许多模组
> 
> 哪些？
“zoomify”  “Alex's Mobs”  “L_Ender 's Cataclysm”其他未测试

**Comment by melontini** [comment]
In case of Alex's Mobs, the mod [re-specifies Citadel's mixin configs](https://github.com/AlexModGuy/AlexsMobs/blob/c466c07ad10e7f906293b39f0d56e39b75099e51/build.gradle#L128-L131). Which was added in [this commit](https://github.com/AlexModGuy/AlexsMobs/commit/7d9bdfff942cd76f8d2b77df48674bf9988913f3) related to NeoForge.

**Comment by melontini** [comment]
IG this can be fixed by checking if the config exists in the modfile.

```java
                    if (Files.exists(modFile.getFile().findResource(config))) {
                        ModFileInfo prev = configToModMap.putIfAbsent(config, modFile);
                        if (prev != null)
                            throw new RuntimeException(String.format("Non-unique Mixin config name %s used by the mods %s and %s", config, prev.moduleName(), modFile.moduleName()));
                    }
```

**Comment by melontini** [comment]
Btw, FabricUtil still doesn't work, even in Beta 20. So handlers don't get their prefix and config blame still says `(unknown)`

**Comment by Su5eD** [comment]
It's fixed now. I set it to log an error on duplicate mixin configs without crashing, as this functionality is not required to run the game. I don't know why Alex's caves lists citadel's mixin config despite not including it, but that should be fixed on their side.
