### ISSUE TITLE
Incompatibility with Continuity and Chisel Reborn, Connected Textures

### ISSUE THREAD

**Issue by litjohn50** [Sinytra/Connector#422]
### Mod Name

Continuity, Chisel Reborn

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/continuity/files?page=1&pageSize=20 / https://www.bing.com/ck/a?!&&p=7b6808183da042c4JmltdHM9MTY5NzkzMjgwMCZpZ3VpZD0xNDgxY2ZmOS00MGJlLTZlY2EtMGNlNy1kZGQ3NDFmZTZmNTkmaW5zaWQ9NTIwMg&ptn=3&hsh=3&fclid=1481cff9-40be-6eca-0ce7-ddd741fe6f59&psq=chisel+reborn&u=a1aHR0cHM6Ly93d3cuY3Vyc2Vmb3JnZS5jb20vbWluZWNyYWZ0L21jLW1vZHMvY2hpc2VsLXJlYm9ybg&ntb=1

### Describe the bug

Textures do not connect at all as if continuity is supposed to make it.

### Steps to reproduce

1.To View load one version with the "Fabric only test" mods mentioned below 
2. Place Chisel reborn wool whatever color you pick. It will connect
3. Now swap over to a forge profile with connector (mods listed below again in "Forge Test"
4. Place the same wool down and notice that it doesn't connect
...

### Logs

N/A

### Additional context

I have to add to this. As another incompatibility to continuity.
Mods used

Fabric only test
chisel-1.6+1.20.1+templates2-inside.jar
continuity-3.0.0-beta.4+1.20.1.jar
fabric-api-0.90.0+1.20.1.jar <- Fabric API

![image](https://github.com/Sinytra/Connector/assets/28884916/cb0127fc-b2cf-4572-85c4-77f68f1450b2)

Forge test
continuity-3.0.0-beta.3+1.20.1.jar (same mod as above just reposting to avoid confusion)
chiselforge-1.6.0.jar
Connector-1.0.0-beta.20+1.20.1-full.jar
fabric-api-0.90.0+1.9.27+1.20.1.jar <- FFAPI
Forge 47.1.3

![image](https://github.com/Sinytra/Connector/assets/28884916/ab1bd1bb-2279-44bd-8402-d04e2468a110)

**Comment by Su5eD** [comment]
I've tried to reproduce this using the mods you listed, but everything seems to work fine.  
Mod list:
- Connector-1.0.0-beta.20 1.20.1-full
- fabric-api-0.90.0 1.9.27 1.20.1
- chiselforge-1.6.0

Mods extracted by chisel forge:
- chisel-1.6 1.20.1
- templates-2.1.1 1.20.1
- continuity-3.0.0-beta.3 1.20.1

![image](https://github.com/Sinytra/Connector/assets/51261569/29fc98cb-709e-4751-a642-dcd5aa6a418d)

**Comment by litjohn50** [comment]
Sorry for the late response. But was busy with some life events. However, I must have missed some mods that I used that I didn't think would actually effect anything.

Issue still persists 
![image](https://github.com/Sinytra/Connector/assets/28884916/6c40b8ed-e086-4501-86ff-d949addc8787)


Here is the Mod List 
![image](https://github.com/Sinytra/Connector/assets/28884916/58b993ce-4492-4132-94e5-5f7790cd718e)


Forge: 47.1.3
chiselforge-1.6.0.jar
ConnectorExtras-1.5.0+1.20.1.jar
continuity-3.0.0-beta.4+1.20.1.jar
embeddium-0.2.5+mc1.20.1.jar
fabric-api-0.90.4+1.9.30+1.20.1.jar
oculus-mc1.20.1-1.6.9.jar
Connector-1.0.0-beta.22+1.20.1-full.jar

**Comment by litjohn50** [comment]
Tried without oculus issue still persists

**Comment by kakashi1464** [comment]
try again but with https://modrinth.com/mod/lazurite

**Comment by litjohn50** [comment]
removing embeddium fixes the issue.

**Comment by kakashi1464** [comment]
> try again but with https://modrinth.com/mod/lazurite

.

**Comment by litjohn50** [comment]
Yes works with that
we just posted our message the same time XD

**Comment by kakashi1464** [comment]
if everything work then close the issue

**Comment by litjohn50** [comment]
its already closed?

**Comment by kakashi1464** [comment]
ah, sorry didn't see that
