### ISSUE TITLE
Update Mod = crash server

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#424]
### Describe the bug

I'm update Connector - and now my server is down at all

### Steps to reproduce

Idk

I tried many versions and it was in vain to delete the one I had, because now I don't know what it was originally

### Logs

https://mclo.gs/iqL35hm

**Comment by Su5eD** [comment]
> java.lang.RuntimeException: Timed out waiting for jar remap

Duplicate of #275
