### ISSUE TITLE
Wilder Wild mixin incompatibility

### ISSUE THREAD

**Issue by Treetrain1** [Sinytra/Connector#428]
### Describe the bug

The use of ModifyArgs in Wilder Wild's LiquidBlockRendererMixin isn't transformed correctly.

### Steps to reproduce

1. Launch the game?

### Logs

https://gist.github.com/Treetrain1/9c1ed3ab35283d2dfc23cf46549dfc99

### Additional context

Originally discussed in #377 

The game doesn't crash with later versions of Wilder Wild, however the issue still remains.

Wilder Wild source for reference
(Has since changed, appending `require = 0`)
```java
@ModifyArgs(method = "tesselate", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/renderer/block/LiquidBlockRenderer;vertex(Lcom/mojang/blaze3d/vertex/VertexConsumer;DDDFFFFFI)V", ordinal = 8))
	private void wilderWild$sideTextureBottom1(Args args) {
		if (this.wilderWild$isWater) {
			this.wilderWild$u0 = this.waterOverlay.getU0();
			this.wilderWild$u1 = this.waterOverlay.getU1();
			this.wilderWild$v0 = this.waterOverlay.getV0();
			this.wilderWild$v1 = this.waterOverlay.getV1();
			args.set(7, this.wilderWild$u0);
			args.set(8, this.wilderWild$v1);
		}
	}
```

**Comment by RoomAlex68** [comment]
Crashes in Connector Beta 28

**Comment by Su5eD** [comment]
Beta 28 is outdated, please update to beta 29

**Comment by RoomAlex68** [comment]
Rubidium and Embeddium Crash on Connector beta 29
