### ISSUE TITLE
Ordered Player List 0.1.2

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#429]
### Mod Name

Ordered Player List 0.1.2

### Mod Homepage

https://modrinth.com/mod/ordered-player-list/version/0.1.2+1.20.1

### Describe the bug

Prefixes Doesn't point to the server

### Steps to reproduce

![image](https://github.com/Sinytra/Connector/assets/60231586/25450863-c3ab-4e6d-983c-9d3e9bddbe3c)

We'll need player 2 as well as luckyperms, I'm using Forge LuckyPerms, we'll prefix the player

![image](https://github.com/Sinytra/Connector/assets/60231586/985f484f-e7be-4b56-b324-a4084ad7456e)

In the configs I have this
![image](https://github.com/Sinytra/Connector/assets/60231586/7ed2000c-7bca-4709-a8c6-083013dec7fc)

### Logs

https://mclo.gs/NL2uTwK

### Additional context

.connector
40 minutes ago
AchievementOptimizer-1.20.1-1.0.2.jar
8.89 KiB
about 3 hours ago
advancedchat-1.3-1.20.1.jar
515.35 KiB
about 3 hours ago
AI-Improvements-1.20-0.5.2.jar
28.86 KiB
about 3 hours ago
alexscaves-1.0.4.jar
71.81 MiB
about 3 hours ago
alexsmobs-1.22.6.jar
24.53 MiB
about 3 hours ago
alternate_current-mc1.20-1.7.0.jar
35.84 KiB
about 3 hours ago
anti-xray-1.3.1-Forge-1.20.1.jar
104.63 KiB
about 3 hours ago
apexcore-1.20.1-10.0.0.jar
543.23 KiB
about 3 hours ago
aquamirae-6.API15.jar
16.52 MiB
about 3 hours ago
architectury-9.1.12-forge.jar
554.28 KiB
about 3 hours ago
athena-forge-1.20.1-3.1.1.jar
89.66 KiB
about 3 hours ago
AttributeFix-Forge-1.20.1-21.0.2.jar
18.96 KiB
about 3 hours ago
balm-forge-1.20.1-7.1.4.jar
331.78 KiB
about 3 hours ago
Bountiful-6.0.3+1.20.1-forge.jar
493.14 KiB
about 3 hours ago
c2me-fabric-mc1.20.1-0.2.0+alpha.11.0.jar
1.24 MiB
about 2 hours ago
cardinal-components-api-5.2.2.jar
216.7 KiB
about 3 hours ago
chipped-forge-1.20.1-3.0.1.jar
13.97 MiB
about 3 hours ago
chunksending-1.20.1-2.6.jar
10.92 KiB
about 3 hours ago
chunkumulator-1.0.3+MC1.20.1.jar
22 KiB
about 3 hours ago
citadel-2.4.5-1.20.1.jar
2.93 MiB
about 3 hours ago
cloth-config-11.1.106-forge.jar
1.11 MiB
about 3 hours ago
cluttered-2.1-1.20.1.jar
5.66 MiB
about 3 hours ago
collective-1.20.1-6.66.jar
603.87 KiB
about 3 hours ago
common-economy-api-1.1.1.jar
16.74 KiB
about 3 hours ago
Companion-1.20.1-forge-5.0.1.jar
32.08 KiB
about 3 hours ago
Connector-1.0.0-beta.21+1.20.1+dev-gb0e0d44-full.jar
3.88 MiB
about 5 hours ago
cristellib-1.1.3-forge.jar
421.53 KiB
about 3 hours ago
ctov-3.3.5b.jar
4.67 MiB
about 3 hours ago
cupboard-1.20.1-2.1.jar
20.96 KiB
about 3 hours ago
curios-forge-5.3.5+1.20.1.jar
297.74 KiB
about 3 hours ago
dimension-detector-1.2.0.jar
46.8 KiB
about 3 hours ago
does_potato_tick-1.20.1-3.6.3.jar
12.74 KiB
about 1 hour ago
DungeonsArise-1.20.1-2.1.57-release.jar
8.17 MiB
about 1 hour ago
easy_npc_1.20.1-1.8.0.jar
633.6 KiB
about 1 hour ago
eidolon_repraised-1.20.1-0.3.5.8.jar
2.81 MiB
about 1 hour ago
EightsEconomyP-1.20-FABRIC-1.1.2.jar
54.81 KiB
about 3 hours ago
endrem_forge-5.2.3-R-1.20.X.jar
861.96 KiB
about 1 hour ago
Epic-Knights.jar
2.29 MiB
about 1 hour ago
EpicFight-20.5.15.jar
5.37 MiB
about 1 hour ago
essential_commands-0.33.2-mc1.20.jar
1.17 MiB
about 1 hour ago
everycomp-1.20-2.6.8.jar
1.86 MiB
about 2 hours ago
fabric-api-0.90.0+1.9.28+1.20.1.jar
2.63 MiB
about 3 hours ago
fabric-auctionhouse-1.0.1+1.20.1.jar
12.95 MiB
41 minutes ago
fantasyfurniture-1.20.1-9.0.0.jar
3.05 MiB
about 2 hours ago
FarmersDelight-1.20.1-1.2.3.jar
2.76 MiB
about 2 hours ago
Fastload-Reforged-mc1.20.1-3.4.0.jar
65.42 KiB
about 2 hours ago
ferritecore-6.0.1-forge.jar
120.15 KiB
about 2 hours ago
geckolib-forge-1.20.1-4.2.3.jar
1.11 MiB
about 3 hours ago
iammusicplayer-forge-mc1.20-3.22.0-alpha.2.jar
9.46 MiB
about 1 hour ago
iceandfire-2.1.13-1.20.1+build.2.1.13-alpha-4.jar
20.53 MiB
about 1 hour ago
immersive_melodies-0.1.0+1.20.1-forge.jar
2.31 MiB
about 2 hours ago
immersive_paintings-0.6.7+1.20.1-forge.jar
4.62 MiB
about 1 hour ago
ItemBlocker-1.20.1-1.0.1.jar
31.39 KiB
about 2 hours ago
Jade-1.20.1-forge-11.5.1.jar
500.36 KiB
about 2 hours ago
JadeAddons-1.20.1-forge-5.2.0.jar
56.92 KiB
about 2 hours ago
jei-1.20.1-forge-15.2.0.27.jar
1.06 MiB
about 2 hours ago
Kambrik-6.1.1+1.20.1-forge.jar
317.92 KiB
about 3 hours ago
kotlinforforge-4.5.0-all.jar
7.25 MiB
about 3 hours ago
L_Enders_Cataclysm-1.39+-1.20.1.jar
30.98 MiB
about 1 hour ago
libertyvillagers-2.0.0+forge+1.20.1.jar
279.35 KiB
about 2 hours ago
Log-Begone-neoforge-1.20.1-1.0.9.jar
57.17 KiB
about 3 hours ago
logprot-1.20.1-3.1.jar
11.8 KiB
about 3 hours ago
lootr-1.20-0.7.30.73.jar
268.68 KiB
about 3 hours ago
LuckPerms-Fabric-PlaceholderAPI-Hook.jar
98.31 KiB
about 3 hours ago
LuckPerms-Forge-5.4.104.jar
1.33 MiB
about 3 hours ago
majrusz-library-1.20.1-5.1.2.jar
387.64 KiB
about 3 hours ago
majruszs-difficulty-1.20.1-1.8.1.jar
748.31 KiB
about 3 hours ago
Masik'sPuzzleDungeon-forge-1.20.1-v1.1.1.jar
717.39 KiB
about 3 hours ago
MaxHealthFix-Forge-1.20.1-12.0.2.jar
8.73 KiB
about 3 hours ago
mcw-paths-1.0.3forge-mc1.20.1.jar
318.88 KiB
about 3 hours ago
memoryleakfix-forge-1.17+-1.1.2.jar
154.97 KiB
about 3 hours ago
modernfix-forge-5.8.1+mc1.20.1.jar
633.74 KiB
about 2 hours ago
moonlight-1.20-2.8.50-forge.jar
1.05 MiB
about 3 hours ago
mvs-4.1-1.20-forge.jar
1.27 MiB
about 2 hours ago
neruina-1.2.6-forge+1.18.2-1.20.1.jar
294.2 KiB
about 2 hours ago
nethersdelight-1.20.1-4.0.jar
338.69 KiB
about 2 hours ago
Nyctophobia_1.6_(FORGE)_for_1.20+.jar
271.61 KiB
about 2 hours ago
obscure_api-15.jar
485.48 KiB
about 3 hours ago
observable-4.4.0.jar
461.83 KiB
about 2 hours ago
open-parties-and-claims-forge-1.20.1-0.20.1.jar
1.16 MiB
about 2 hours ago
orderedplayerlist-0.1.2+1.20.1.jar
244.03 KiB
about 3 hours ago
otyacraftengine-forge-mc1.20-3.7.0-alpha.2.jar
640.58 KiB
about 2 hours ago
PassiveSkillTree-1.20.1-BETA-0.5.8.jar
1.33 MiB
about 2 hours ago
polymer-bundled-0.5.17+1.20.1.jar
1.39 MiB
about 2 hours ago
ProfessionLock-1.20-1.0.1.jar
22.6 KiB
about 2 hours ago
recipeessentials-1.20.1-3.0.jar
42.84 KiB
about 2 hours ago
recruits-1.20.1-1.10.8.jar
1.15 MiB
about 2 hours ago
RegionsUnexploredForge-0.5.3+1.20.1.jar
5.43 MiB
about 2 hours ago
repurposed_structures-7.1.7+1.20.1-forge.jar
8.18 MiB
about 2 hours ago
resourcefullib-forge-1.20.1-2.1.11.jar
362.96 KiB
about 3 hours ago
servercore-forge-1.3.7+1.20.1.jar
1.14 MiB
about 2 hours ago
smoothchunk-1.20.1-3.1.jar
12.02 KiB
about 2 hours ago
soul_like_armors_reworked_1.20.1_(v42.0).jar
2 MiB
about 3 hours ago
spark-1.10.42-forge.jar
2.84 MiB
about 3 hours ago
starlight-1.1.2+forge.1cda73c.jar
107.99 KiB
about 3 hours ago
starterkit-1.20.1-5.2.jar
60.4 KiB
about 3 hours ago
structureessentials-1.20.1-3.0.jar
27.72 KiB
about 3 hours ago
styled-chat-2.2.3+1.20.1.jar
382.54 KiB
about 3 hours ago
styledplayerlist-3.1.1+1.20.1.jar
245.77 KiB
about 3 hours ago
supplementaries-1.20-2.6.13.jar
14.04 MiB
about 3 hours ago
TaxCastlePillager+M.1.20.1+ForM.1.0.0.jar
452.12 KiB
about 3 hours ago
TerraBlender-forge-1.20.1-3.0.0.169.jar
102.9 KiB
about 3 hours ago
The_Graveyard_2.6.2_(FORGE)_for_1.20+.jar
12.92 MiB
about 3 hours ago
Towns-and-Towers-1.11.1-Fabric+Forge.jar
2.54 MiB
about 3 hours ago
VillagersPlus_3.0_(FORGE)_for_1.20.1.jar
352.93 KiB
about 3 hours ago
waystones-forge-1.20-14.0.2.jar
440.03 KiB
about 3 hours ago
WorldPreGenerator-1.20.1-4.0.0.jar
1.09 MiB
about 3 hours ago
worldspecificviewdistance-0.2.1+1.20.jar

_No response_

**Comment by DonorKrovi** [comment]
![image](https://github.com/Sinytra/Connector/assets/60231586/a11b5ef6-b846-4689-8849-d7e35bb86c9f)
In theory, it should look like this

**Comment by Su5eD** [comment]
How exactly am I supposed to add a prefix to players? I've tried this out on Fabric but couldn't figure it out.

**Comment by DonorKrovi** [comment]
> How exactly am I supposed to add a prefix to players? I've tried this out on Fabric but couldn't figure it out.

Contact me on discord, I will give you a ready-made RP.

Discord: xioniox

**Comment by Su5eD** [comment]
Can you send it in Sinytra's discord server? I think that'd be the best way to do it. GitHub allows file uploads, too. There's a link to it in the repo's README.

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
