### ISSUE TITLE
Simply Swords Fabric doesn’t work with connector.

### ISSUE THREAD

**Issue by Xeno123456789** [Sinytra/Connector#430]
### Mod Name

Simply Swords

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/simply-swords/files?page=1&pageSize=20

### Describe the bug

Game crashes when you place the nessicary dependence’s and the mod in your mods folder along with connector.

### Steps to reproduce

1. Install Connector and Connector Extras
2. Put the fabric version of simply swords and it’s dependiences in the mods folder
3. Run the game
...

### Logs

https://pastebin.com/61xWjtbb

### Additional context

Although there is a forge version, the fabric version has compat with many mods working with connector like Mariums Soulslike Weaponry and Mythic Metals. The forge mod lacks this comparability.

**Comment by Su5eD** [comment]
Works for me using Connector Beta 21 and Connector Extras 1.4.1+1.20.1. Can you please upload your debug.log?

**Comment by Xeno123456789** [comment]
> Works for me using Connector Beta 21 and Connector Extras 1.4.1+1.20.1. Can you please upload your debug.log?

Havent tried with Connector Beta 21 as it messes with some of the other mods I use with connector. I've been using FFAPI 26,  Connector 19, and Latest version of extras. So far, I have no issues.

**Comment by itzinxta** [comment]
> Works for me using Connector Beta 21 and Connector Extras 1.4.1+1.20.1. Can you please upload your debug.log?

It crashes for me, too. Must have something to do with having the Optional Fabric Compat mods with it, Mods like, https://www.curseforge.com/minecraft/mc-mods/mythicmetals have Compat with the Fabric Version of Simply Swords.

**Comment by Su5eD** [comment]
> **MODS USED:**
> 
> * Connector-1.0.0-beta.21+1.20.1-full
> * fabric-api-0.90.4+1.9.28+1.20.1
> * ConnectorExtras-1.4.1+1.20.1
> * simplyswords-fabric-1.51.5-1.20.1
> * architectury-9.1.12-fabric
> * cloth-config-11.1.106-fabric

Ah, I see what I've done differently. Use the Forge version of Architectury instead of the Fabric one, and everything will work fine.

@itzinxta can you please upload your crash report?

**Comment by itzinxta** [comment]
> > **MODS USED:**
> > 
> > * Connector-1.0.0-beta.21+1.20.1-full
> > * fabric-api-0.90.4+1.9.28+1.20.1
> > * ConnectorExtras-1.4.1+1.20.1
> > * simplyswords-fabric-1.51.5-1.20.1
> > * architectury-9.1.12-fabric
> > * cloth-config-11.1.106-fabric
> 
> Ah, I see what I've done differently. Use the Forge version of Architectury instead of the Fabric one, and everything will work fine.
> 
> @itzinxta can you please upload your crash report?

will do. https://pastebin.com/4XQPGDK9

**Comment by Su5eD** [comment]
That looks like mythic metals compat is crashing due to being initialized too early. I recommend [hiding](https://github.com/Sinytra/Connector#hiding-forge-mods-presence) its presence from fabric mods to prevent this crash. It is also favorable to use the native forge version of Simply Swords, as that is guaranteed to work.

I've tested simply swords to work on connector beta 24 with connector extras installed as well.
