### ISSUE TITLE
Error: java.lang.IncompatibleClassChangeError: class dev.su5ed.sinytra.connector.mod.compat.fieldtypes.RedirectingIdMapper overrides final method net.minecraft.core.IdMapper.m_7942_(I)Ljava/lang/Object;

### ISSUE THREAD

**Issue by miroozl** [Sinytra/Connector#433]
### Describe the bug

Game crashes witout mods, only witch connector and api

### Steps to reproduce

1. Install Sinnytra Connector version 21 with Forgified Fabric API version 28 on forge 1.20.1 47.1.30
2. Get: The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class dev.su5ed.sinytra.connector.mod.compat.fieldtypes.RedirectingIdMapper overrides final method net.minecraft.core.IdMapper.m_7942_(I)Ljava/lang/Object;

### Logs

https://gist.github.com/miroozl/a723e6d28b6aa022d7e729b7ff4c14d9

**Comment by Tursiops-G** [comment]
You need to use Forge version 47.1.3 (dot Three)
NOT 47.1.30 (dotThirty).
