### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by neostasis** [Sinytra/Connector#435]
### Describe the bug

Each time I try to run minecraft with the 47.1.3 forge client, it never makes it past the mod loading section. I originally had 47.1.30 downloaded on accident, but after reinstalling my client I got this error message instead. I am trying to run better end, and i have the extra dependencies installed besides the fabric api, because im using the forgified version. I tried looking around to see of this had been an issue for anyone else, but it looked like a quick fix by changing the client version.

### Steps to reproduce

1. forge 47.1.3 client
2. better-end-2.1.6.jar
cave_dweller-1.20.1-1.6.4
Connector-1.0.0-beta.21+1.20.1-full
ConnectorExtras-1.4.1+1.20.1
fabric-api-0.90.0+1.9.28+1.20.1
FarmersDelight-1.20.1-1.2.3
geckolib-forge-1.20.1-4.2.3
bclib-3.0.13

all in mods folder
3. open minecraft launcher
4. run 47.1.3 client
5. watch it load until it gets to the mods section
6. crash
...

### Logs

<script src="https://gist.github.com/neostasis/0c314e857388aa0a4e07b12a8c3742b4.js"></script>

**Comment by Xeno123456789** [comment]
Try FFAPI 26, instead of 28. Better end works with connector, as I'm currently using it.

**Comment by Su5eD** [comment]
Please upload your debug.log

**Comment by neostasis** [comment]
https://gist.github.com/neostasis/0c314e857388aa0a4e07b12a8c3742b4

This should be the correct link I think

**Comment by Su5eD** [comment]
That is still the same crash log. The log I asked for can be found at `config/debug.log`

**Comment by neostasis** [comment]
I just found out i had the wrong version of better end downloaded after looking at the debug log, i think this should fix it. Here's the log anyways, though
[debug.log](https://github.com/Sinytra/Connector/files/13170800/debug.log)
