### ISSUE TITLE
Twilight Forest and Andromeda Incompatiibility

### ISSUE THREAD

**Issue by iludmik** [Sinytra/Connector#436]
### Mod Name

Andromeda

### Mod Homepage

https://andromeda-wiki.pages.dev/

### Describe the bug

Crashes. Cant boot up the game.

### Steps to reproduce

1. Just start the game with both Andromeda and Twilight Forest
2.
3.
...

### Logs

https://mclo.gs/vRmPsdq

**Comment by RoomAlex68** [comment]
Twilight Forest works fine for me

**Comment by RoomAlex68** [comment]
No
