### ISSUE TITLE
Game isn't able to run

### ISSUE THREAD

**Issue by AlmightyFIshy** [Sinytra/Connector#438]
### Describe the bug

Game crashes before loading is finished

### Steps to reproduce

1. Install the mod
2. Put into your mod folder
3. Open the game
4. Game doesn't load
...

### Logs

https://pastebin.com/jPyuWQaH

**Comment by Su5eD** [comment]
Duplicate of #398. Use Forge 47.1.3 (not 47.1.30) as instructed in the README.
