### ISSUE TITLE
Game crashes when loading the mods

### ISSUE THREAD

**Issue by genzoz** [Sinytra/Connector#439]
### Describe the bug

Game crashes when I try to launch the game, despite not having any mods besides the connector and the fabric api

### Steps to reproduce

1.Add the connector and forgefied fabric api into the mods folder
2.Launch game
3.Wait
4.Crash

### Logs

https://pastebin.com/VQckUKZJ

### Additional context

Literally no other mods, the mod files are:
-.connector folder, that is empty
-Connector-1.0.0-beta.21+1.20.1-full.jar
-fabric-api-0.90.0+1.9.28+1.20.1.jar
and the forge version I am using is 1.20.1-forge-47.2.0

**Comment by Su5eD** [comment]
Use Forge version 47.1.3 as instructed in the README. FFAPI is currently not compatible with newer forge versions.

**Comment by genzoz** [comment]
Thanks, it works now. Btw, the mod seems to be incompatible with the fabric mod "Icarus"

**Comment by RoomAlex68** [comment]
Did you had trinkets installed?
