### ISSUE TITLE
MC Dungeons Weapon HeldItemRenderMixin 

### ISSUE THREAD

**Issue by Kinami37** [Sinytra/Connector#440]
### Mod Name

MC Dungeons Weapons

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mcdw

### Describe the bug

Crash on startup/launch

### Steps to reproduce

1. install mc dungeons weapons
2. install sinytra connector
3. launch

tbf i assume its an issue with another mod im using, i just dont know what/which, since i saw someone on discord have no issues using Connector v19

I tried both v19 and v20, still crashed. Might be related to Forge CIT, idk.

### Logs

https://pastebin.com/qTDbtdRm

**Comment by Kinami37** [comment]
thats the error the launcher gives me, not the log, removing Forge CIT gives me the error inside the game and the log, which is this https://imgur.com/pGI75OV

**Comment by Su5eD** [comment]
Hm, I feel like I've patched this before. Can you try using beta 21 or the current [dev build](https://github.com/Sinytra/Connector/actions/runs/6642602211)?

**Comment by Kinami37** [comment]
i am using beta 21, and i tried the current dev build too, same thing happens, same error :/ ( i assume i use the -full.jar and not the -sources.jar?)

**Comment by Kinami37** [comment]
ok randomly works now, no idea why it crashed 30m ago
