### ISSUE TITLE
Error with Citadel and Alex's Caves "Non-unique Mixin config name citadel.mixins.json"

### ISSUE THREAD

**Issue by ComputerUser55** [Sinytra/Connector#442]
### Mod Name

Citadel & Alex's Caves

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/citadel

### Describe the bug

When starting up the game with Citadel & Sinytra, the crash happens after a few seconds.

### Steps to reproduce

1. Just install Citadel and/or Alex's Caves alongside Sinytra...
2. If you add Fabric API, it doesn't produce a Crash Report.

### Logs

https://gist.github.com/ComputerUser55/3167c0d1a1de25314b92a8e46c00d9d9

### Additional context

I haven't tested it much, but I'm sure they worked like, 2 days ago at least. From the reports and the logs, it looks like it has something to do with the 'Citadel' config they use. I'm not great at reading crash reports, so take it as you will.

**Comment by Kinami37** [comment]
citadel and alex caves works for me without issues

**Comment by ComputerUser55** [comment]
Yeah uhh, all I had to do was use the newest version, whoops.
Sorry.
