### ISSUE TITLE
There is a problem with Continuity connecting blocks with transparent textures.

### ISSUE THREAD

**Issue by Primia** [Sinytra/Connector#445]
### Describe the bug

 there seems to be a problem with the connection of transparent textures.

### Steps to reproduce

mod list：
Connector 1.0.0-beta.21+1.20.1
ConnectorExtras 1.5.0+1.20.1
[1.20.1] Forgified Fabric API 0.90.4+1.9.29+1.20.1
indium-1.0.27+mc1.20.1.jar (disabled sodium depend)
embeddium-0.2.2+mc1.20.1
continuity-3.0.0-beta.4+1.20.1
Yuushya Townscape 2.1.1 [Forge] https://modrinth.com/mod/yuushya-townscape/version/udzin5Sj

problem blocks:
yuushya:oak_windows_0
yuushya:average_pink_blooming_leaves
Or any block with transparent material.

resource pack(Contains the mod block resource and the vanilla block resource):
https://www.curseforge.com/minecraft/texture-packs/yuushya-16x
The situation:
![image](https://github.com/Sinytra/Connector/assets/87895370/a88da81f-b68a-4114-b826-0a29fd38dfb0)
This is how it should be（Continuity with fabric only ）:
![image](https://github.com/Sinytra/Connector/assets/87895370/444533a8-1345-4d90-84da-df4380394a6a)

### Additional context

Thank you for your hard work, which has given me hope for CTM on forge.  If this issue can be resolved, then there will be a major breakthrough for CTM on forge!

**Comment by Su5eD** [comment]
Does this occur without embeddium (and indium) installed?

**Comment by Primia** [comment]
> Does this occur without embeddium (and indium) installed?

without embeddium (and indium) ,CTM dont work.
![image](https://github.com/Sinytra/Connector/assets/87895370/d4011c07-0e6e-42d4-a876-670a1fa7e541)
without embeddium,install indium,CTM dont work and have visual error.
![image](https://github.com/Sinytra/Connector/assets/87895370/6a4e6145-b376-4ec3-ab26-3a434f987b13)

**Comment by Su5eD** [comment]
Just tried out in a new instance and the textures can connect correctly.  
Used mods:
- architectury-9.1.12-forge
- Connector-1.0.0-beta.21
- ConnectorExtras-1.5.0 1.20.1
- continuity-3.0.0-beta.3 1.20.1
- fabric-api-0.90.4 1.9.29 1.20.1
- yuushya-1.20.1-forge-2.1.1

![image](https://github.com/Sinytra/Connector/assets/51261569/def97493-9cd9-4aaf-b0a4-40aba949a625)

**Comment by Su5eD** [comment]
This can now be fixed by installing [Lazurite](https://github.com/Su5eD/Lazurite) alongside Embeddium, which provides FRAPI support for Continuity. Could you try and verify that it works for you?

**Comment by RoomAlex68** [comment]
Does Lazurite work with Rubidium?

**Comment by kakashi1464** [comment]
> Does Lazurite work with Rubidium?

nah
