### ISSUE TITLE
 Continuity no longer works with embeddium.

### ISSUE THREAD

**Issue by Primia** [Sinytra/Connector#446]
### Describe the bug

When embeddium is enabled, Continuity no longer works.

### Steps to reproduce

mod list：
Connector 1.0.0-beta.21+1.20.1
ConnectorExtras 1.5.0+1.20.1
[1.20.1] Forgified Fabric API 0.90.4+1.9.29+1.20.1
embeddium-0.2.2+mc1.20.1
continuity-3.0.0-beta.4+1.20.1
Yuushya Townscape 2.1.1 [Forge] https://modrinth.com/mod/yuushya-townscape/version/udzin5Sj
The situation:
https://user-images.githubusercontent.com/87895370/278744907-d4011c07-0e6e-42d4-a876-670a1fa7e541.png

This is how it should be:
https://user-images.githubusercontent.com/87895370/278743251-444533a8-1345-4d90-84da-df4380394a6a.png

**Comment by Su5eD** [comment]
Same issue as #445
