### ISSUE TITLE
Villager Names (Fabric) is incompatible with Guard Villagers

### ISSUE THREAD

**Issue by uthw** [Sinytra/Connector#449]
### Describe the bug

Villager Names (fabric) can be loaded with Connector but isn't playable with Guard Villagers

### Steps to reproduce

1. Add Connector, FFAPI, Guard Villagers (Forge), and Villager Names
2. The game loads, but creating a world crashes when the progress reaches 100%

### Logs

[Crash Report](https://gist.github.com/uthw/dc8146094863acec56ddd6c560255d6f) [latest.log](https://gist.github.com/uthw/5c2996cea7c22406ec04b66bb3c04afd) [debug.log](https://gist.github.com/uthw/c7d10369775849b5cca885f83d341766)

### Additional context

I'm using Connector beta 22 (Connector-1.0.0-beta.22+1.20.1+dev-g40e1feb-full.jar) with the most recent Forgified Fabric API

I also had Connector Extras enabled but seems to crash either way

I tried this with the Fabric version of Guard Villagers too but I got a crash saying the mod loading failed (also happens without Villager Names). Idk if that matters.

[Fabric Crash Report](https://gist.github.com/uthw/a05ded555746150dc084967c304f5d62)
[Fabric latest.log](https://gist.github.com/uthw/459e2c1a49addf55207b146d0edc1921)
[Fabric debug.log](https://gist.github.com/uthw/4617bb2d8e28498665cc6afd8b7058c0)

**Comment by zeid0ne** [comment]
Why you dont use th forge version ? https://www.curseforge.com/minecraft/mc-mods/villager-names

**Comment by Su5eD** [comment]
That's a different mod

**Comment by Su5eD** [comment]
I've added an option that allows you to disable the broken integration to make the two mods work together. This approach uses a config file called `connector.json`, inside which you can define mod IDs that will be hidden from Fabric mods. Making the Fabric mod think Guard Villagers is not installed, it won't enable its integration with it.

Here's my config file I used to test out this solution:
```json
{
  "hiddenMods": [
    "guardvillagers"
  ]
}
```
