### ISSUE TITLE
crash with forge 47.1.0 also another issue in comments

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#45]
### Describe the bug

i looked at the latest log and i think it wants me to update my forge. can you make it work on all forge versions?

### Steps to reproduce

1. launch minecraft forge 47.1.0
2. it should crash with exit code 1
3.
...

### Logs

https://mclo.gs/ocUwlPe

**Comment by Thunderrock424242** [comment]
adding on to the issue i went to 47.1.3 and it so far worked but then crashed. i checked and no mods should be incompatible so i hope you can find the issue.
[latest.log](https://github.com/Sinytra/Connector/files/12328614/latest.log)

**Comment by Su5eD** [comment]
Forge 47.1.3 is required to run Connector or the Forgified Fabric API, as it is explained here:
- https://github.com/Sinytra/Connector/discussions/42

As for the other crash, the latest.log doesn't contain any information about errors or crashes. Please paste your debug.log or a crash report instead, and list the mods you're using.
