### ISSUE TITLE
steelsheepmod error

### ISSUE THREAD

**Issue by ExtremePantherr** [Sinytra/Connector#451]
### Mod Name

SteelSheepMod 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/steel-sheep

### Describe the bug

steelwoolmc is giving an error in the launch folder

### Steps to reproduce

Was trying to add origin++ to Prominence II and the game would just crash before it loads, I went to the curse forge discord and one of the Community Champions told me that Steelwoolmc, is erroring and that I should report it here

### Logs

https://gist.github.com/ExtremePantherr/7f72beca86594dc221f96c3d50b23b97

### Additional context

I also don't see how or why this mod is giving an error when its not even on the mod list for the modpack I am trying to play

**Comment by RoomAlex68** [comment]
This also happens with a mod called: nether sheep

**Comment by Su5eD** [comment]
The cause of this error is that one of your installed mods includes Reach Entity Attributes, which conflicts with Forge. For this, Connector Extras includes a Forge ports of REA that is compatible with both Forge and Pehkui. Install the latest version from [here](https://legacy.curseforge.com/minecraft/mc-mods/connector-extras/files) and it should no longer crash.
