### ISSUE TITLE
When using connector, many mods do not load

### ISSUE THREAD

**Issue by taggerdoxyll** [Sinytra/Connector#452]
### Describe the bug

Game crashes when loading existing and new worlds

### Steps to reproduce

1. Start up game with personal modpack (all dependencies added)
2. All mods loads on main menu
3. Crashes when attempting to load new or existing world
...

### Logs

https://pastebin.com/ybMBLttG

### Additional context

When I do not use Connector and Connector Extras and use ForgeConfig API instead, all Forge mods work but no Fabric mods.
When I use both Connector mods and ForgeConfig API it cannot even load in the main menu.

A link showing all mods incompatible when using Connector and Extras.
This is just to make help make the examining process smoother.
Although I have found replacements for some, I just do not understand why would a shops mod that does not use any dependencies fails to load. 

I am new to this mod so there is a chance I may have done something that should not have been done while using Connector and mods combined. 

![image](https://github.com/Sinytra/Connector/assets/123182409/68f1d2d3-3239-463c-a57f-7c08e825485b)

**Comment by Su5eD** [comment]
I don't know what "mods do not load" means, but it looks like one of your mods is including an outdated version of Polymer. Download the latest version [here](https://modrinth.com/mod/polymer/version/0.5.18+1.20.1), which is compatible with Connector.
