### ISSUE TITLE
it literally just crashes

### ISSUE THREAD

**Issue by SafeOfArsenal** [Sinytra/Connector#456]
### Describe the bug

it just crashes with only sinytra, forgified fabric, and connector extras

### Steps to reproduce

1.
2.
3.
...
you literally just run it

### Logs

---- Minecraft Crash Report ---- // Surprise! Haha. Well, this is awkward.  Time: 2023-10-29 17:18:19 Description: Initializing game  java.lang.IncompatibleClassChangeError: class dev.su5ed.sinytra.connector.mod.compat.fieldtypes.RedirectingIdMapper overrides final method net.minecraft.core.IdMapper.m_7942_(I)Ljava/lang/Object; 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {} 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {} 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:485) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod (unknown),pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:182) ~[forge-47.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {} 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {} 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:485) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod (unknown),pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A} -- Initialization -- Details: 	Modules:  		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation 		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		ColorAdapterClient.dll:Microsoft Color Adapter Client:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.3570:Microsoft Corporation 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.3570:Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		DEVOBJ.dll:Device Information Set DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		GDI32.dll:GDI Client DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		GLU32.dll:OpenGL Utility Library DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		MMDevApi.dll:MMDevice API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		MSCTF.dll:MSCTF Server DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		MpOav.dll:IOfficeAntiVirus Module:4.18.23090.2008 (b0d7cf273f4b179b8031bda447c0e07aca8eb8b4):Microsoft Corporation 		NLAapi.dll:Network Location Awareness 2:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		OWClient.dll:Overlay:2.2.234.6:Overwolf LTD 		OWExplorer.dll:Overlay:2.2.234.3:Overwolf LTD 		OWUtils.dll:Overlay:2.2.234.3:Overwolf LTD 		OpenAL.dll:Main implementation library:1.21.1: 		POWRPROF.dll:Power Profile Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		PROPSYS.dll:Microsoft Property System:7.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		PSAPI.DLL:Process Status Helper:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		SETUPAPI.dll:Windows Setup API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		SHELL32.dll:Windows Shell Common Dll:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		UMPDC.dll 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		WINHTTP.dll:Windows HTTP Services:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		WINNSI.DLL:Network Store Information RPC interface:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		WINSTA.dll:Winstation Library:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		amsi.dll:Anti-Malware Scan Interface:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		cfgmgr32.dll:Configuration Manager DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation 		combase.dll:Microsoft COM for Windows:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		cryptbase.dll:Base cryptographic API DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		cryptnet.dll:Crypto Network Related API:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		dinput8.dll:Microsoft DirectInput:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		drvstore.dll:Driver Store API:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		dxcore.dll:DXCore:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		gdi32full.dll:GDI Client DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW 		gpapi.dll:Group Policy Client API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		icm32.dll:Microsoft Color Management Module (CMM):10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		imagehlp.dll:Windows NT Image Helper:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		inputhost.dll:InputHost:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft 		jemalloc.dll 		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jna11692919976527753936.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA) 		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft 		kernel.appcore.dll:AppModel API Host:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		lwjgl.dll 		lwjgl_opengl.dll 		lwjgl_stb.dll 		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		msasn1.dll:ASN.1 Runtime APIs:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		mscms.dll:Microsoft Color Matching System DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		ntdll.dll:NT Layer DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		ntmarta.dll:Windows NT MARTA provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.3758:NVIDIA Corporation 		nvspcap64.dll:NVIDIA Game Proxy:3.27.0.112:NVIDIA Corporation 		ole32.dll:Microsoft OLE for Windows:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		opengl32.dll:OpenGL Client DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		perfproc.dll:Windows System Process Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		profapi.dll:User Profile Basic API:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		uxtheme.dll:Microsoft UxTheme Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		win32u.dll:Win32u:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		wintypes.dll:Windows Base Types DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3570 (WinBuild.160101.0800):Microsoft Corporation 		xinput1_4.dll:Microsoft Common Controller API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft Stacktrace: 	at net.minecraft.client.main.Main.main(Main.java:182) ~[forge-47.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 328287880 bytes (313 MiB) / 671088640 bytes (640 MiB) up to 12582912000 bytes (12000 MiB) 	CPUs: 12 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz 	Identifier: Intel64 Family 6 Model 165 Stepping 3 	Microarchitecture: unknown 	Frequency (GHz): 2.90 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x21c4 	Graphics card #0 versionInfo: DriverVersion=31.0.15.3758 	Memory slot #0 capacity (MB): 32768.00 	Memory slot #0 clockSpeed (GHz): 2.67 	Memory slot #0 type: DDR4 	Virtual memory max (MB): 37492.50 	Virtual memory used (MB): 21524.46 	Swap memory total (MB): 4864.00 	Swap memory used (MB): 142.64 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12000m -Xms256m 	Launched Version: forge-47.2.0 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.58, NVIDIA Corporation 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

**Comment by kakashi1464** [comment]
Try forge 47.1.3

**Comment by SafeOfArsenal** [comment]
do toy know why is so behind on forge versions

**Comment by Xplodin** [comment]
> do toy know why is so behind on forge versions

forge brokey thats why

**Comment by Su5eD** [comment]
See #42
