### ISSUE TITLE
bclib mods (better nether & end) work in singleplayer but crash mp server

### ISSUE THREAD

**Issue by animatedosprey** [Sinytra/Connector#457]
### Describe the bug

see log below

### Steps to reproduce

1.install mods
2.start server
3.crash
...

### Logs

https://gist.github.com/animatedosprey/e59f7de3925e2f26c3e8426863566e1e

### Additional context

posting this in the hopes that someone can help me figure out an easy fix to get these mods working on my server.  They work great in singleplayer, the server crashes with only bclib (no better nether or better end) but blames the other two mods if they are enabled as well.

**Comment by Aerioos** [comment]
Running into similar issue here
https://github.com/Sinytra/Connector/issues/458

**Comment by animatedosprey** [comment]
> Running into similar issue here #458

I don't know how or why but I feel like a kid on Christmas - I downloaded the new version of Forgified Fabric API that released today and put it on the server.  It launches and the above mods work now!  
The only downside is that endrem seems to crash the client when opening the inventory, but I am assuming this is related only to the better end mod and will have to do some further testing. 

Anyways, try updating forgified fabric api for nature's spirit, I have a feeling you might get similar results since it was the same bug :)

**Comment by animatedosprey** [comment]
Updating to the latest (or 10/30/2023) release of Forgified Fabric API seems to fix this bug.

**Comment by Aerioos** [comment]
Still running into the same issue unfortunately! Glad it fixed for you though. :)

**Comment by Thspooks** [comment]
having same issue

**Comment by Su5eD** [comment]
> having same issue

This is not sufficient information needed to diagnose the issue. Please provide logs, mods installed and steps to reproduce, as described in the issue template. Also, verify which specific mods are required to reproduce the issue.

**Comment by Thspooks** [comment]
Ill do that on new post, but honestly ive never seen a github dev replying so fast

**Comment by Thspooks** [comment]
> Getting the same issue here. Blaming Better Nether on the server: [debug.log](https://github.com/Sinytra/Connector/files/14192448/debug.log)
> 
> @Su5eD Shall I create a new issue?

It is not connector issue. It is all BetteNether/end and BcLib fault. Some time ago there were unofficial fixes, but it seems they got deleted from github.

**Comment by aking4125** [comment]
> > Getting the same issue here. Blaming Better Nether on the server: [debug.log](https://github.com/Sinytra/Connector/files/14192448/debug.log)
> > @Su5eD Shall I create a new issue?
> 
> It is not connector issue. It is all BetteNether/end and BcLib fault. Some time ago there were unofficial fixes, but it seems they got deleted from github.

Ah yes. I see now.

Turns out the fix was applied for BetterNether, BetterEnd, and BCLib on their Git Hub (Branch 1.20) but wasn't released yet. Had to build them manually. Seems to work now.

**Comment by Cataraxts** [comment]
> > > Getting the same issue here. Blaming Better Nether on the server: [debug.log](https://github.com/Sinytra/Connector/files/14192448/debug.log)
> > > [@Su5eD](https://github.com/Su5eD) Shall I create a new issue?
> > 
> > 
> > It is not connector issue. It is all BetteNether/end and BcLib fault. Some time ago there were unofficial fixes, but it seems they got deleted from github.
> 
> Ah yes. I see now.
> 
> Turns out the fix was applied for BetterNether, BetterEnd, and BCLib on their Git Hub (Branch 1.20) but wasn't released yet. Had to build them manually. Seems to work now.


Hey!! Would it be possible to send me those built jars? I got the first two on 1.20 branch building fine but the third one (BetterEnd specifically) refuses to build.
