### ISSUE TITLE
Mythic Metals and Alloy Forgery

### ISSUE THREAD

**Issue by OliverMatt2023** [Sinytra/Connector#46]
### Mod Name

Mythic Metals and Alloy Forgery

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mythicmetals

### Describe the bug

Crashes with exit code 1 with the crash being OwOSentinel

### Steps to reproduce

1. Load in the forge version FORGE 47.1.3
2. Get owolib, Alloy Forgery, and Mythic Metals
3. Wait till it loads then it crashes with exit code 1
...

### Logs

https://pastebin.com/QXcPn8sk

**Comment by Su5eD** [comment]
The mod uses the `reach-entity-attributes` library which I found to be in conflict with Forge's entity attribute modifiers. I'll try to find a way around it

**Comment by OliverMatt2023** [comment]
Thanks, It's one of my favorite ore, armor, weapon, and tool mods because it's inspired by Terraria(Well, some of the items at least). And the main dev of the mod won't make a forge port sadly...

**Comment by OliverMatt2023** [comment]
This mod that you made is the closest thing to get Mythic Metals to a forge port.

**Comment by OliverMatt2023** [comment]
It still crashes with the new Connecter update.

**Comment by Su5eD** [comment]
Yes, I haven't looked into it yet. I'll let you know once I do 👍 .

**Comment by Abbie5** [comment]
new crash caused by additional entity attributes
https://0x0.st/HOuN.txt
