### ISSUE TITLE
Some Mods require mod menu (in fabric if you dont install mod menu nothing happens)

### ISSUE THREAD

**Issue by NotRabug50** [Sinytra/Connector#461]
### Describe the bug

It says a mod menu is required and if I install a mod menu it doesn't let me play, the game doesn't open.

### Steps to reproduce

1.I installed wakes and better clouds
2.I opened the game

### Logs

[latest.log](https://github.com/Sinytra/Connector/files/13204946/latest.log)

**Comment by Su5eD** [comment]
> Missing language kotlinforforge version [4.1,) wanted by Adorn-5.0.0+1.20.1-forge.jar  
Missing language kotlinforforge version [1,) wanted by Resourcify (1.20-1.20.1-forge)-1.2.1.jar  
Missing or unsupported mandatory dependencies:  
>&nbsp;&nbsp;&nbsp;&nbsp;Mod ID: 'searchables', Requested by: 'controlling', Expected range: '[1.0,)', Actual version: '[MISSING]'
>&nbsp;&nbsp;&nbsp;&nbsp;Mod ID: 'architectury', Requested by: 'roughlyenoughitems', Expected range: '[8,)', Actual version: '[MISSING]'

This doesn't seem to be related to modmenu at all

**Comment by NotRabug50** [comment]
> > Missing language kotlinforforge version [4.1,) wanted by Adorn-5.0.0+1.20.1-forge.jar
> > Missing language kotlinforforge version [1,) wanted by Resourcify (1.20-1.20.1-forge)-1.2.1.jar
> > Missing or unsupported mandatory dependencies:
> >     Mod ID: 'searchables', Requested by: 'controlling', Expected range: '[1.0,)', Actual version: '[MISSING]'
> >     Mod ID: 'architectury', Requested by: 'roughlyenoughitems', Expected range: '[8,)', Actual version: '[MISSING]'
> 
> This doesn't seem to be related to modmenu at all

idk why it says it required mod menu

**Comment by Su5eD** [comment]
Where does it say that?

**Comment by NotRabug50** [comment]
> [15:14:39] [WARN] [FabricLoader/Resolution]: Warnings were found!
 - §eMod 'Better Clouds' (betterclouds)§r 1.3.10+1.20.1 recommends any version of §6modmenu§r, which is missing!
	 - You should install any version of §6modmenu§r for the optimal experience.
 - §eMod 'Wakes' (wakes)§r 0.2.0 recommends any version of §6modmenu§r, which is missing!
	 - You should install any version of §6modmenu§r for the optimal experience.

**Comment by embeddedt** [comment]
That's a recommendation not a hard requirement.

**Comment by Su5eD** [comment]
that's just a recommendation, not a hard requirement. The actual cause of the crash is what I've posted above

**Comment by NotRabug50** [comment]
> that's just a recommendation, not a hard requirement. The actual cause of the crash is what I've posted above

oh ok

**Comment by RoomAlex68** [comment]
Yeah this was happening with controlify

**Comment by uthw** [comment]
This also happens with [Chat Patches](https://www.curseforge.com/minecraft/mc-mods/chatpatches)

[latest.log](https://gist.github.com/uthw/c68fdb71fc3258d880a03bb147a63e55) [debug.log](https://gist.github.com/uthw/c3f46487e5425831f0ab2aaefa5b4238)

![Screenshot 2023-11-04 161410](https://github.com/Sinytra/Connector/assets/73855194/5df75895-1203-467c-b9a9-16c596f1f694)

**Comment by Su5eD** [comment]
You can use a [dependency override](https://fabricmc.net/wiki/tutorial:dependency_overrides) to remove it, though I think it might be more convenient to provide a "fake" modmenu mod. Not sure if that could break anything.

**Comment by Su5eD** [comment]
Connector Extras 1.5.1 now includes a dummy ModMenu mod to overcome this issue
