### ISSUE TITLE
Not compatible with MC Dungeons Weapons MOD.

### ISSUE THREAD

**Issue by nanachijiang** [Sinytra/Connector#462]
### Mod Name

MC Dungeons Weapons

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mcdw

### Describe the bug

When equipped with MC Dungeons Weapons (fabric version), the game crashes on startup.

### Steps to reproduce

1.I installed Sinytra Connector, Connector Extras, and Forgified Fabric API for my brand new forge 47.1.3 client and then successfully started minecraft and tested the world. The process was smooth and error-free.

2.After that I quit the game and added the MC Dungeons Weapons mod and its pre-mod: Cloth config (fabric version). Then tried to launch the game again, at which point the game crashed.

3.The game startup screen displays loading bootstrap resources for a while, displays loading mods for a moment, and then crashes.

This is a crash screen recording.
https://github.com/Sinytra/Connector/assets/149419724/68170cd5-fdaf-41ea-8470-894c2ae694c8

This is the crash log automatically generated by the HMCL launcher.
[minecraft-exported-crash-info-2023-10-30T20-04-39.zip](https://github.com/Sinytra/Connector/files/13208392/minecraft-exported-crash-info-2023-10-30T20-04-39.zip)

### Logs

---- Minecraft Crash Report ---- // Why did you do that?  Time: 2023-10-30 20:04:23 Description: Initializing game  java.lang.IncompatibleClassChangeError: class dev.su5ed.sinytra.connector.mod.compat.fieldtypes.RedirectingIdMapper overrides final method net.minecraft.core.IdMapper.m_7942_(I)Ljava/lang/Object; 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {} 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:485) ~[client-1.20.1-20230612.114412-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod (unknown),pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {} 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:485) ~[client-1.20.1-20230612.114412-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.connectorextras_geckolib_fabric_compat.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectorextras_architectury_bridge.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:mixins.connectorextras_modmenu_bridge.json:MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod (unknown),pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod (unknown),pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod (unknown),pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A} -- Initialization -- Details: 	Modules:  		ADVAPI32.dll:高级 Windows 32 基本 API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		COMCTL32.dll:用户体验控件库:6.10 (WinBuild.160101.0800):Microsoft Corporation 		CRYPT32.dll:加密 API32:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTBASE.DLL:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.2506:Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		DEVOBJ.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		DNSAPI.dll:DNS 客户端 API DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		GDI32.dll:GDI Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		GLU32.dll:OpenGL 实用工具库 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		IPHLPAPI.DLL:IP 帮助程序 API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		KERNEL32.DLL:Windows NT 基本 API 客户端 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		KERNELBASE.dll:Windows NT 基本 API 客户端 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		MMDevApi.dll:MMDevice API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		MSCTF.dll:MSCTF 服务器 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		MessageBus.dll:NVIDIA Message Bus::NVIDIA Corporation 		MpOav.dll:IOfficeAntiVirus Module:4.18.23090.2008 (b0d7cf273f4b179b8031bda447c0e07aca8eb8b4):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		OpenAL.dll:Main implementation library:1.21.1: 		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		RPCRT4.dll:远程过程调用运行时:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		SETUPAPI.dll:Windows 安装程序 API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		SHCORE.dll:SHCORE:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		SHELL32.dll:Windows Shell 公用 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		USER32.dll:多用户 Windows 用户 API 客户端 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		USERENV.dll:Userenv:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		WINHTTP.dll:Windows HTTP 服务:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		WINMM.dll:MCI API DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		WINSTA.dll:Winstation Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		WS2_32.dll:Windows Socket 2.0 32 位 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		apphelp.dll:应用程序兼容性客户端库:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		bcrypt.dll:Windows 加密基元库:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation 		combase.dll:用于 Windows 的 Microsoft COM:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		cryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		d3d11.dll:Direct3D 11 Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		dcomp.dll:Microsoft DirectComposition Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc.DLL:DHCP 客户端服务:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc6.DLL:DHCPv6 客户端:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		dinput8.dll:Microsoft DirectInput:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		drvstore.dll:Driver Store API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		dwmapi.dll:Microsoft 桌面窗口管理器 API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		dxcore.dll:DXCore:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		dxgi.dll:DirectX Graphics Infrastructure:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		fwpuclnt.dll:FWP/IPsec 用户模式 API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		gdi32full.dll:GDI Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW 		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		igc64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:26.20.100.7985:Intel Corporation 		igd10iumd64.dll:User Mode Driver for Intel(R) Graphics Technology:26.20.100.7985:Intel Corporation 		igdgmm64.dll:User Mode Driver for Intel(R) Graphics Technology:26.20.100.7985:Intel Corporation 		imagehlp.dll:Windows NT Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		inputhost.dll:InputHost:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		java.exe:OpenJDK Platform binary:17.0.1.0:Microsoft 		jemalloc.dll 		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		jna2833657382866466341.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA) 		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft 		kernel.appcore.dll:AppModel API Host:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		lwjgl.dll 		lwjgl_opengl.dll 		lwjgl_stb.dll 		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		mdnsNSP.dll:Bonjour Namespace Provider:3,0,0,10:Apple Inc. 		msasn1.dll:ASN.1 Runtime APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		mscms.dll:Microsoft 颜色匹配系统 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		mswsock.dll:Microsoft Windows Sockets 2.0 服务提供程序:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		napinsp.dll:电子邮件命名填充提供程序:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		ncrypt.dll:Windows NCrypt 路由器:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		ntdll.dll:NT 层 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		ntmarta.dll:Windows NT MARTA 提供程序:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		nvapi64.dll:NVIDIA NVAPI Library, Version 537.58 :31.0.15.3758:NVIDIA Corporation 		nvldumdx.dll:NVIDIA Driver Loader, Version 537.58 :31.0.15.3758:NVIDIA Corporation 		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.3758:NVIDIA Corporation 		nvspcap64.dll:NVIDIA Game Proxy:3.27.0.112:NVIDIA Corporation 		nvwgf2umx.dll:NVIDIA D3D10 Driver, Version 537.58 :31.0.15.3758:NVIDIA Corporation 		ole32.dll:用于 Windows 的 Microsoft OLE:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		opengl32.dll:OpenGL Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		pdh.dll:Windows 性能数据助手 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		perfos.dll:Windows 系统性能对象 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		perfproc.dll:Windows 系统进程性能对象 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		pnrpnsp.dll:PNRP 命名空间提供程序:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		powrprof.dll:电源配置文件帮助程序 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		profapi.dll:User Profile Basic API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		shlwapi.dll:外壳简易实用工具库:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		uxtheme.dll:Microsoft UxTheme 库:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation 		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft 		win32u.dll:Win32u:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		wintypes.dll:Windows 基本类型 DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		wldp.dll:Windows 锁定策略:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		xinput1_4.dll:Microsoft 公共控制器 API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft Stacktrace: 	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 17.0.1, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 496258416 bytes (473 MiB) / 1476395008 bytes (1408 MiB) up to 6375342080 bytes (6080 MiB) 	CPUs: 16 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz 	Identifier: Intel64 Family 6 Model 165 Stepping 2 	Microarchitecture: unknown 	Frequency (GHz): 2.30 	Number of physical packages: 1 	Number of physical CPUs: 8 	Number of logical CPUs: 16 	Graphics card #0 name: NVIDIA GeForce RTX 2070 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x1f14 	Graphics card #0 versionInfo: DriverVersion=31.0.15.3758 	Graphics card #1 name: Intel(R) UHD Graphics 	Graphics card #1 vendor: Intel Corporation (0x8086) 	Graphics card #1 VRAM (MB): 1024.00 	Graphics card #1 deviceId: 0x9bc4 	Graphics card #1 versionInfo: DriverVersion=26.20.100.7985 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 32552.21 	Virtual memory used (MB): 14023.22 	Swap memory total (MB): 16384.00 	Swap memory used (MB): 341.02 	JVM Flags: 11 total; -Xmx6072m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump 	Launched Version: 1.20.1 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.58, NVIDIA Corporation 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	CPU: 16x Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.1.3.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.1.3.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.1.3.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.1.3.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.1.3.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		forge-1.20.1-47.1.3-universal.jar                 |Forge                         |forge                         |47.1.3              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

### Additional context

I tested another mod by the same author: MC Dungeons Armors (fabric), which also calls the same cloth config (fabric) as MC Dungeons Weapons (fabric). But unlike MC Dungeons Weapons, which are incompatible, MC Dungeons Armors can be played normally.

At the same time, I don't use any other mods except the few mentioned above.

Optifine is not installed on the client either.

Mods list
![1698689671163](https://github.com/Sinytra/Connector/assets/149419724/e9011e4a-70c1-4094-9f3b-6c4708c7fb95)

**Comment by Su5eD** [comment]
This a bug in adapter that has been fixed in the current dev version, and will be available with the next Connector release.

**Comment by nanachijiang** [comment]
Thanks so much

**Comment by RoomAlex68** [comment]
Crashes on Connector 22 and Minecraft Dungeons Armor also crashes

**Comment by rainysux** [comment]
@RoomAlex68 it works, you need clumps fabric and cloth forge
