### ISSUE TITLE
Mod Menu incompatibility

### ISSUE THREAD

**Issue by DoritosSpR** [Sinytra/Connector#464]
### Mod Name

Mod Menu

### Mod Homepage

https://modrinth.com/mod/modmenu

### Describe the bug

Mod Menu is not compatible with connector

### Steps to reproduce

[Mod Menu](https://modrinth.com/mod/modmenu) compatibility when?

### Logs

https://mclo.gs/QjBXEiF

**Comment by Su5eD** [comment]
Mod Menu support is not planned as it directly conflicts with Forge's mod list screen. If you want an enhanced mod list, I recommend using [Catalogue](https://www.curseforge.com/minecraft/mc-mods/catalogue) instead.
