### ISSUE TITLE
KubeJS platform compatibility

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#468]
### Mod Name

Modern Industrialization

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

### Describe the bug

crash on start

### Steps to reproduce

1. download latest connector + extras + forgified fabric api
2. download MI
3. crash on boot
...

### Logs

https://gist.github.com/Xplodin/865fecb2bb24f30f2d065cd51297cfec

### Additional context

it just doesnt work due to some entry point I think

**Comment by Su5eD** [comment]
Do you have kubejs installed?

**Comment by RoomAlex68** [comment]
Works for me

**Comment by Xplodin** [comment]
> Do you have kubejs installed?

yes

**Comment by FeiNaVRgo** [comment]
So, is there any solution to this problem?

**Comment by Su5eD** [comment]
Fixed in Connector Extras [1.8.0](https://modrinth.com/mod/connector-extras/version/1.8.0+1.20.1).
