### ISSUE TITLE
Fabric Seasons: ```java.lang.NullPointerException: Cannot invoke "net.minecraft.server.packs.repository.Pack.m_10446_()" because "p_143903_" is null```

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#47]
### Mod Name

Fabric Seasons

### Mod Homepage

https://modrinth.com/mod/fabric-seasons

### Describe the bug

Crash

### Steps to reproduce

Launch the game.

### Logs

https://mclo.gs/XC7EBLR

**Comment by Su5eD** [comment]
This was caused by a bug in the Forgified Fabric API that prevented the generation of default pack.mcmeta files. It is now fixed in version `0.86.1+1.8.3+1.20.1`.

**Comment by jupiter-august** [comment]
I'm experiencing this error myself. Could that be the reason?
