### ISSUE TITLE
crash with modpack

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#471]
### Describe the bug

crashes when i launch my modpack

### Steps to reproduce

1. load my modpack 
2. hit play then it crashes a couple seconds later
3.
...

### Additional context

[debug.log](https://github.com/Sinytra/Connector/files/13243534/debug.log)
[latest.log](https://github.com/Sinytra/Connector/files/13243535/latest.log)
here are the logs

**Comment by Su5eD** [comment]
> forge-47.2.0

Use forge 47.1.3

**Comment by Thunderrock424242** [comment]
> > forge-47.2.0
> 
> Use forge 47.1.3

are you ever gonna update the mod to a newer forge?
