### ISSUE TITLE
Polymer Exception ticking world

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#473]
### Describe the bug

https://github.com/Patbox/polymer/issues/93

### Steps to reproduce

1. Unfortunately I don't know

### Logs

https://mclo.gs/NfVjysW

**Comment by DonorKrovi** [comment]
I'm find problem!

Mod Alex CAVES 1.0.6
Video: https://youtu.be/uFpmau0Kq00
Log: https://mclo.gs/SiPUXJN

**Comment by DonorKrovi** [comment]
Just in case, I'll write to their repository

**Comment by Su5eD** [comment]
Seems to be an issue with AC/ModernFix/RecipeEssentials as described in https://github.com/AlexModGuy/AlexsCaves/issues/53
