### ISSUE TITLE
Better End Does Not Work on Latest Version 1.20.1

### ISSUE THREAD

**Issue by greztrez** [Sinytra/Connector#474]
### Mod Name

BetterEnd

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/betterend

### Describe the bug

Crash Upon Installing the Needed Dependencies/Mods

### Steps to reproduce

1. Open Minecraft Launcher
2. Start Game
3. Crash midway through
...
[crash-2023-11-03_21.14.14-client.txt](https://github.com/Sinytra/Connector/files/13255796/crash-2023-11-03_21.14.14-client.txt)

### Logs

crash report is attached

**Comment by uthw** [comment]
Try using forge 47.1.3

**Comment by Su5eD** [comment]
Connector requires Forge 47.1.3, see #42

**Comment by greztrez** [comment]
> Connector requires Forge 47.1.3, see #42

yeah, im new to github so correct me if this is wrong etiquette, but the issue is still not fixed when installing forge version 47.1.3

here is the crash report
[crash-2023-11-04_08.26.21-client.txt](https://github.com/Sinytra/Connector/files/13257028/crash-2023-11-04_08.26.21-client.txt)

**Comment by Su5eD** [comment]
Does this happen with only better end installed?

**Comment by greztrez** [comment]
> Does this happen with only better end installed?

yes, this is my first trying the connector-forgified fabric thing and i am only testing it with better end installed. all compatible fabric mods on the list also do not appear to work

**Comment by Kinami37** [comment]
you need bclib because betterend requires it  (if you havent)

betterend / betternether work great for me

**Comment by rainysux** [comment]
youre using 1.47.30, its not the same as 1.47.3

**Comment by Su5eD** [comment]
Confirmed to work on beta 23 with Forge 47.1.3, better end and bclib

**Comment by Liink56** [comment]
I have exactly the same problem, but I have BCLIB installed in the correct version, and my forge version is 47.3.5 (newer so it should work I guess)

in the logs it clearly states that Sinytra Connector is present, but BCLIB and BetterEnd say Fabric is needed, I don't understand what else to do, can you guide me?
