### ISSUE TITLE
Minecraft crash with the latest version of connector but not on the old version

### ISSUE THREAD

**Issue by Thedarklord0002** [Sinytra/Connector#475]
### Describe the bug

crash

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/OFT3Uwq

### Additional context

It works with version 21, https://mclo.gs/aNYPHr5

**Comment by Su5eD** [comment]
Please provide information about your installed mods. The log doesn't show any errors

**Comment by Thedarklord0002** [comment]
https://paste.atlauncher.com/view/e035e02a-7ace-4427-a0ea-802aafdb92bf. Does this help?

**Comment by Thedarklord0002** [comment]
Also i got another issue but it is on beta 21 and on server.(client is function but not server) Here is the log https://mclo.gs/2cpWbru

**Comment by RoomAlex68** [comment]
Yeah it happened to me on Connector Beta 23 on client

**Comment by Reshy** [comment]
Getting something similar on startup:

[06Nov2023 14:15:05.779] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'fabric_api', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_block_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_loot_api_v2', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_item_group_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_screen_handler_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_models_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_mining_level_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_resource_conditions_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_convention_tags_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_biome_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_content_registries_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_game_rule_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_rendering_data_attachment_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_screen_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_particles_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_blockrenderlayer_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_object_builder_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_entity_events_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_events_interaction_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_data_generation_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_recipe_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_api_base', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_renderer_indigo', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_message_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_command_api_v2', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_model_loading_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_lifecycle_events_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_client_tags_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_registry_sync_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_rendering_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_rendering_fluids_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_item_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_sound_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_command_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_transfer_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_transitive_access_wideners_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_dimensions_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_block_view_api_v2', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_resource_loader_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_renderer_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_api_lookup_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_key_binding_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'
	Mod ID: 'forge', Requested by: 'fabric_networking_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'

**Comment by rainysux** [comment]
> Getting something similar on startup:
> 
> [06Nov2023 14:15:05.779] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies: Mod ID: 'forge', Requested by: 'fabric_api', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_block_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_loot_api_v2', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_item_group_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_screen_handler_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_models_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_mining_level_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_resource_conditions_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_convention_tags_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_biome_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_content_registries_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_game_rule_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_rendering_data_attachment_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_screen_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_particles_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_blockrenderlayer_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_object_builder_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_entity_events_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_events_interaction_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_data_generation_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_recipe_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_api_base', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_renderer_indigo', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_message_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_command_api_v2', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_model_loading_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_lifecycle_events_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_client_tags_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_registry_sync_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_rendering_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_rendering_fluids_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_item_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_sound_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_command_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_transfer_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_transitive_access_wideners_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_dimensions_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_block_view_api_v2', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_resource_loader_v0', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_renderer_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_api_lookup_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_key_binding_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30' Mod ID: 'forge', Requested by: 'fabric_networking_api_v1', Expected range: '[47.1.3,47.1.3]', Actual version: '47.1.30'

You’re not using 1.47.1.3 version of forge. youre using .30 completely different

**Comment by Reshy** [comment]
Correct, though even on the correct version it still crashes.

log:  https://pastebin.com/22c7zQqR

**Comment by rainysux** [comment]
that doesnt have a crash in it

**Comment by Reshy** [comment]
> that doesnt have a crash in it

Exactly, no clue what's happening there.  Nothing in the log or debug output, no crash log.

**Comment by Reshy** [comment]
> that doesnt have a crash in it

Exactly, no clue what's causing it.  Could be related to https://github.com/Sinytra/Connector/issues/480 though.

**Comment by rainysux** [comment]
bewitchment doesnt work

**Comment by kakashi1464** [comment]
Forge 47.1.30 != Forge 47.1.3
