### ISSUE TITLE
crashed on beta 21 using hybrid aquatic

### ISSUE THREAD

**Issue by Thedarklord0002** [Sinytra/Connector#476]
### Describe the bug

An issue i have on server, it is fuctioning on client, 

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/2cpWbru

**Comment by RoomAlex68** [comment]
My game crashed on connector beta 23

**Comment by Su5eD** [comment]
Confirmed to work on Connector beta 23
