### ISSUE TITLE
Better end & nether crush my server

### ISSUE THREAD

**Issue by VanityWater** [Sinytra/Connector#477]
### Describe the bug

These 2 mods work in singleplayer, but crushed when starting the server.

### Steps to reproduce

1.Install 2 mods.
2.Start server.
3.Server crushed.
...

### Logs

https://pastebin.com/507VkWEE

### Additional context

I'm using Connector Beta 22, ConnectorExtras 1.5.0 and FFAPI 0.90.4+1.9.30+1.20.1.

**Comment by Su5eD** [comment]
According to the provided reproduction steps, only better end and better nether are required to reproduce the issue. However, the log shows that additional mods such as soulslikeweaponry are present. Please verify this issue is reproducible with ONLY the listed mods installed.
> at net.soulsweaponry.SoulsWeaponry.onInitialize(SoulsWeaponry.java:52) ~[soulslike-weaponry-0.9.9.7-1.20-fabric_mapped_srg_1.20.1.jar%231141!/:?]

**Comment by VanityWater** [comment]
The newest test shows the server won't crush if there's only betterend and betternether, and when I added the rest mods except those 2 mods, soulslikeweaponry also crushed the server for the same reason. BUT when I replaced connector 22 with 23, the server didn't crush anymore even if I continue to use connector 22. It's strange. I will close the issue.
