### ISSUE TITLE
Issue starting the game with forge 47.1.3

### ISSUE THREAD

**Issue by MsVella** [Sinytra/Connector#479]
### Describe the bug

The game crashes when the mods are installed as directed.

### Steps to reproduce

1. Install:
![image](https://github.com/Sinytra/Connector/assets/88259742/ec382c58-f93e-413a-a728-d330d0d7833d)
2. Start Game
3. Crash:
[latest.log](https://github.com/Sinytra/Connector/files/13257602/latest.log)
![image](https://github.com/Sinytra/Connector/assets/88259742/4791faf2-d99c-43a6-82b7-1d71bc69e6f1)
...

### Additional context

I'm genuinely unsure what's going on here??

**Comment by uthw** [comment]
You have forge version 47.1.30 and not 47.1.3. You can change the forge version in your instance's settings
