### ISSUE TITLE
crash with modpack

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#48]
### Describe the bug

whenever i use this mod with my pack it crashes i will give a downlaod to it becasue if i list all the mods it will take for ever

### Steps to reproduce

1. start my pack
2. then it crashes
3.
...

### Logs

https://mclo.gs/xONRUpo             https://mclo.gs/lp4PFaR

### Additional context

https://legacy.curseforge.com/minecraft/modpacks/wilderness-odyssey/files/all this has all the mods i use since it would take me a while to list them

**Comment by Su5eD** [comment]
None of the logs you've provided contain any errors or crashes. Please retry using the latest versions of Connector and Forgified Fabric API, then paste a crash report and/or your debug.log
