### ISSUE TITLE
REI Forge Crash

### ISSUE THREAD

**Issue by itzinxta** [Sinytra/Connector#481]
### Mod Name

Roughly Enough Items (Forge) Geckolib (Fabric) too.

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-forge https://www.curseforge.com/minecraft/mc-mods/geckolib

### Describe the bug

REI will crash while loading a Fabric Geckolib mod.

### Steps to reproduce

1. Load the World [ with REI Forge, Mod that requires Geckolib Fabric ]
2. go into the Fabric Geckolib item section in REI
3. Crash
...

### Logs

https://pastebin.com/PsTLGd0Z

### Additional context

I'm also using Connector Extras. this crash won't happen if you don't load the Fabric Geckolib mods item page in REI.

**Comment by DoritosSpR** [comment]
use geckolib forge, it also loads fabric mods if you use connector extras

**Comment by itzinxta** [comment]
this might be an issue on https://www.curseforge.com/minecraft/mc-mods/enderman-overhaul 's side, other mods seem to work fine.

**Comment by itzinxta** [comment]
> this might be an issue on https://www.curseforge.com/minecraft/mc-mods/enderman-overhaul 's side, other mods seem to work fine.

yea, it is.
