### ISSUE TITLE
Loading Both forge and fabric version of "Kotlin Language" crashes after beta 21

### ISSUE THREAD

**Issue by A00826925** [Sinytra/Connector#482]
### Mod Name

Fabric Language Kotlin

### Mod Homepage

https://modrinth.com/mod/fabric-language-kotlin/changelog

### Describe the bug

In beta 21, im able to load both fabric and forge versions of the api, however from beta 22 onwards, the game crashs with an architechtury error

### Steps to reproduce

1. Install, probably, the following mods:
2. Connector beta 22+, Forgified Api, Kotlin forge, Kotlin fabric, Architectury, cobblemon (maybe optional)
3. Run the game
4.
...

### Logs

https://mclo.gs/1oXgfK3

### Additional context

i know running both version might be dumb, but its required by some fabric mods

**Comment by Su5eD** [comment]
Same issue as #475, will be fixed in the next update. Running both is completely correct btw, each language providers/adapters must be provided for both platforms respectively

**Comment by FullMetalMaster** [comment]
lit cant wait ti see it working lol
