### ISSUE TITLE
MCDW crashes again with Beta 23

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#485]
### Describe the bug

Crashes on start up

### Steps to reproduce

Before this connector update 
 it didnt crash, looks like the same problem that was fixed in Beta 21 I believe.
https://github.com/Sinytra/Connector/actions/runs/6618635008
This is the build you sent to fix it at the time

### Logs

https://pastebin.com/hLUDVFMq

**Comment by RoomAlex68** [comment]
This also happened with Minecraft Dungeons Armor

**Comment by wsxiya** [comment]
"mcdw, mcda" conflicts with Clumps in "beta22"

**Comment by rainysux** [comment]
> "mcdw, mcda" conflicts with Clumps in "beta22"

you need clumps fabric
