### ISSUE TITLE
ClientCommands Incompatability

### ISSUE THREAD

**Issue by thundercreeper10** [Sinytra/Connector#487]
### Mod Name

ClientCommands

### Mod Homepage

https://modrinth.com/mod/client-commands

### Describe the bug

Crash on launch

### Steps to reproduce

1.Use the Sinytra connector with the Forgified API
2.Add Client Commands
3.Crash!
...

### Logs

https://mclo.gs/POrTVm3

**Comment by Su5eD** [comment]
Duplicate of #441
