### ISSUE TITLE
Minecraft Crashing

### ISSUE THREAD

**Issue by Cedgtech** [Sinytra/Connector#49]
### Mod Name

Presence Footsteps

### Mod Homepage

https://modrinth.com/mod/presence-footsteps

### Describe the bug

Crashes

### Steps to reproduce

1.Install the Mods
2.Open Minecraft
3.See
...

### Logs

https://gist.github.com/Cedgtech/53df68393ffd62fd30d34014060ffe37

### Additional context

PresenceFootsteps-1.9.0.jar
Forge Version: 47.1.44
Connector-1.0.0-beta.4+1.20.1-full.jar
fabric-api-0.86.1+1.8.1+1.20.1.jar

**Comment by Su5eD** [comment]
Connector and the Forgified Fabric API require Forge `47.1.3` and aren't compatible with never versions as explained here:
- #42 

Please change your Forge version to `47.1.3` and try again with Connector beta 5

**Comment by Cedgtech** [comment]
I did with the new Beta and Forge version 47.1.3 and still the same issue.

**Comment by Su5eD** [comment]
Okay can you please upload your `debug.log`? The gist you provided does not contain any errors or crashes

**Comment by Su5eD** [comment]
Try removing OptiFine

**Comment by Cedgtech** [comment]
It still crashes

**Comment by Su5eD** [comment]
Then please remove any other mods besides the ones you listed, as I noticed the provided list of mods does not actually match the ones you're running. It might be an entirely different mod causing the incomatibility.

**Comment by Cedgtech** [comment]
Okay its working without the other mods thx
