### ISSUE TITLE
Arcadian Dream crash

### ISSUE THREAD

**Issue by ReisenUdonge** [Sinytra/Connector#490]
### Mod Name

Arcadian Dream

### Mod Homepage

https://github.com/Maxmani/arcadian-dream

### Describe the bug

Crashes while loading mod, 

### Steps to reproduce

Run with Arcadian Dream added.

### Logs

https://pastebin.com/uT5AREwg

### Additional context

mods:
Arcadian Dream
Connector + Connector Extras
Fabric Api
ForgifiedFabric Api
Geckolib (forge) (tried both fabric and forge versions)
owo-lib
Pekhui (fabric) (tried both fabric and forge versions)
trinkets

**Comment by unilock** [comment]
I forked Arcadian Dream to fix the issue: https://github.com/unilock/arcadian-dream/commit/beba8a26392096dbe3a1ca211630a646bd52bb7c

I believe only the LVT mismatch in `net/minecraft/block/FireBlock` between vanilla and Forge is what's actually relevant.  
(I didn't make a PR, as I considered my fix for that - applying a different mixin based on the detected platform - to be somewhat hacky.)

**Comment by ReisenUdonge** [comment]
Thank you! Maxmani told me yesterday that someone forked his mod to fix the compatibility issue, I have yet to try it out though

**Comment by ReisenUdonge** [comment]
It works!

**Comment by ReisenUdonge** [comment]
On second thought, no it doesn't; minecraft loads now, but Arcadian Dream simply isn't seen? like its just not there

**Comment by ReisenUdonge** [comment]
I tried out the fix, but minecraft still crashes. https://pastebin.com/BbTTMkyW

**Comment by unilock** [comment]
Try using the Forge version of Pehkui? I have the following mod set working:

- Arcadian Dream (fork): `arcadiandream-1.20.1-0.1.0.jar`
- Sinytra Connector: `Connector-1.0.0-beta.23+1.20.1.jar`
- Connector Extras: `ConnectorExtras-1.5.1+1.20.1.jar`
- Forgified Fabric API: `fabric-api-0.90.7+1.9.30+1.20.1.jar`
- GeckoLib (Fabric): `geckolib-fabric-1.20.1-4.2.4.jar`
- owo-lib: `owo-lib-0.11.2+1.20.jar`
- Pehkui (Forge): `Pehkui-3.7.11+1.20.1-forge.jar`
- Trinkets: `trinkets-3.7.1.jar`

Notably, I was originally not able to get (my fork of) Arcadian Dream working alongside Connector Extras, but that seems to have been fixed :)

**Comment by ReisenUdonge** [comment]
yup, works now!
