### ISSUE TITLE
Immersive Portals custom Portals

### ISSUE THREAD

**Issue by Charismara** [Sinytra/Connector#491]
### Mod Name

Immersive Portals

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod

### Describe the bug

It is not possible to load custom portals using datapacks for Immersive Portals.

### Steps to reproduce

1. Install the example datapack below
2. Join your world
3. Take a look into the logs of your game
4. Be sad because the `Loaded Custom Portal Gen` message doesn't appear which mean that no datapack has been loaded

### Additional context

Example Datapack download: https://cdn.discordapp.com/attachments/1170734895971176458/1170735472125956116/blutmondtweaks.zip?ex=655a1f5f&is=6547aa5f&hm=1243364ff9c88af3ff6821abdf22b6db98ec4f51167d69b4f2b66c14e8aeb6ec&

**Comment by Su5eD** [comment]
Seems like forge is prefixing the datapack registry with the modid, so it ends up looking for data under `data/blutmondtweaks/imptl/custom_portal_generation`, which is the wrong path. I'll see if I can find a sensible way of knowing when to omit the prefix, as some custom fabric registries require it, too.
