### ISSUE TITLE
Vanadium incompatibility

### ISSUE THREAD

**Issue by kakashi1464** [Sinytra/Connector#492]
### Mod Name

Vanadium

### Mod Homepage

https://modrinth.com/mod/vanadium

### Describe the bug

minecraft crashing at the launch

### Steps to reproduce

1.Add embeddium 0.2.7, lazurite 1.0.1, vanadium to the mods folder
2.Launch minecraft

### Logs

https://mclo.gs/ocvjAVv - latest log
https://mclo.gs/JqcWRjD - debug log

**Comment by kakashi1464** [comment]
No crash report

**Comment by kakashi1464** [comment]
Ok

**Comment by kakashi1464** [comment]
It's still happening  with embeddium 0.2.9

**Comment by kakashi1464** [comment]
still happening with latest embeddium beta

**Comment by Su5eD** [comment]
How is the issue related to embeddium? From what I can see in the log, it is solely a mixin conflict between Vanadium and Forge.

**Comment by kakashi1464** [comment]
idk, it never hurts to just check again, in case something has changed
