### ISSUE TITLE
Archers is incompatible

### ISSUE THREAD

**Issue by vivagabe** [Sinytra/Connector#494]
### Mod Name

Archers (RPG Series)

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/archers

### Describe the bug

Minecraft crashes before it finishes loading.

### Steps to reproduce

The game crashes before it finishes loading up. I have only the required mods to run Archers installed. Archers dev said he doesnt believe it is compatible.

### Logs

https://gist.github.com/vivagabe/5d2778d1d81f71d17d723a59c9885b2a

**Comment by vivagabe** [comment]
This has been fixed in the latest release of Archers!

**Comment by Su5eD** [comment]
Thanks!
