### ISSUE TITLE
Mekanism logistical transporter crash

### ISSUE THREAD

**Issue by MidnightTale** [Sinytra/Connector#497]
### Mod Name

Modern Industrialization

### Mod Homepage

https://modrinth.com/mod/modern-industrialization

### Describe the bug

When use mode pull or push with logistical transporter to Modern Industrialization block will crash

### Steps to reproduce

1.place macerator
2.put steam bucket in macerator and main sort put oak log
3.connet macerator to chest using logistical transporter and
4.use configuretor on logistical transporter at macerator side to use to pull mode
5.should crash

### Logs

https://pastebin.com/NLQmSPGp

**Comment by Su5eD** [comment]
Fixed in 0.90.7+1.9.31+1.20.1
