### ISSUE TITLE
Reflections library does not work on Connector

### ISSUE THREAD

**Issue by embeddedt** [Sinytra/Connector#500]
### Describe the bug

Fabric mods using the Reflections library do not work on Connector due to some issue with UnionFS

### Steps to reproduce

1. Compile https://github.com/embeddedt/reflectionstestmod and add it to an instance with Connector (I used 1.0.0-beta.24+1.20.1).
2. Attempt to launch the game.
3. Note the error that appears in the log.
4. Run the mod on Fabric, and notice that there is no error.

### Additional context

On Fabric, the test mod works correctly, and prints a message stating it found the `TestModule` class.

On Connector, Reflections throws [an exception in the log](https://gist.github.com/embeddedt/67a715f4168a6d6f4f6abfba4d47c294), and does not find the `TestModule` class.

**Comment by LLKawi** [comment]
so #36 again?

**Comment by embeddedt** [comment]
I didn't see that issue. I will see if the workaround suggested works.
