### ISSUE TITLE
Show me what you got mod doesn't render items in chat

### ISSUE THREAD

**Issue by DoritosSpR** [Sinytra/Connector#502]
### Describe the bug

When i try to use SMWYG with connector, doesn't render items in the chat

### Steps to reproduce

1.- Start Minecraft with connector, FFAP, connector extras and [SMWYG](https://modrinth.com/mod/show-me-what-you-got).
2.-Enter a new world
3.-CTRL + T an item in the inventory.

https://github.com/Sinytra/Connector/assets/122171434/f0af8303-000a-438b-8bec-4ea58914f0ac

### Additional context

sa

**Comment by Su5eD** [comment]
Fixed in FFAPI 0.90.7+1.9.32+1.20.1
