### ISSUE TITLE
Changing Respackopts settings for resource packs doesn't change anything.

### ISSUE THREAD

**Issue by StormDragon-64** [Sinytra/Connector#503]
### Mod Name

Respackopts

### Mod Homepage

https://modrinth.com/mod/respackopts

### Describe the bug

When using Connector with Respackopts (and LibJF) along with a Respackopts compatible resource pack (eg. [Stellar Tweaks](https://modrinth.com/resourcepack/stellar-tweaks)) then Resourcepackopts will load, and the configuration button and menu for the resource pack works. After changing a setting and clicking done however, resources are reloaded but everything stays the same.

### Steps to reproduce

1. Install Connector, Connector Extras, FFAPI, Respackopts, LibJF, and Stellar Tweaks. (All of the latest versions, obviously)
2. Launch the game.
3. Enable Stellar Tweaks in the resource pack selection screen.
4. It works as expected, applying all of its texture changes.
5. Now, go back to the resource pack selection screen and click the configuration button next to Stellar Tweaks.
6. Click as many buttons as you want in the configuration screen, including the everything button in the misc. tab.
7. Click Done.
8. Observe than nothing has changed, and everything still acts like it was at the default settings.

### Logs

https://mclo.gs/tFUvCuV

### Additional context

This also could possibly be an issue with LibJF, not Respackopts.

**Comment by StormDragon-64** [comment]
Oops, accidentally uploaded the wrong log where I was using Stellar Tweaks 2.4. [Here's the log when using Stellar Tweaks 2.5](https://mclo.gs/e0Q41N2), even though it probably doesn't make much of a difference.

**Comment by Su5eD** [comment]
It looks like the mod's resource pack filters rely on raw ASM transformation, which is difficult to do on fabric and requires various workarounds to get working. Connector supports Fabric ASM out of the box, although the mod seems to be using its own library, [libjf-unsafe-v0](https://git.frohnmeyer-wds.de/JfMods/LibJF/src/branch/master/libjf-unsafe-v0). This comes into a [conflict](https://git.frohnmeyer-wds.de/JfMods/LibJF/src/commit/ef6c58e93dad61ed693bc7dfd3fd00637b367eed/libjf-unsafe-v0/src/main/java/io/gitlab/jfronny/libjf/unsafe/MixinPlugin.java#L21) with forge's classloading mechanism when trying to reflect into the classloader.
