### ISSUE TITLE
MacOS Input Fixes is Incompatible

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Sinytra/Connector#505]
### Mod Name

MacOS Input Fixes

### Mod Homepage

https://modrinth.com/mod/macos-input-fixes

### Describe the bug

Crashes on startup 

### Steps to reproduce

1. Download necessary mods
2. Start the game
3. Crashes

### Logs

https://mclo.gs/LcQdb2W

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/JqJjacx crashes when I go to the settings in the mod

Options > Controls > Mouse settings

**Comment by Aces-and-Jacks** [comment]
However the mod itself works now. thank you

**Comment by unilock** [comment]
@Aces-and-Jacks My PR to MacOS Input Fixes should fix that issue: https://github.com/hamarb123/MCMacOSInputFixes/pull/31
