### ISSUE TITLE
Game crashes when you start a new world. Possible incompatibility between Promenade and Organics.

### ISSUE THREAD

**Issue by DarkXFast** [Sinytra/Connector#506]
### Mod Name

Organics/Promenade

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/organics | https://modrinth.com/mod/promenade/versions

### Describe the bug

Game crashes when you start a new world.

### Steps to reproduce

1. Install Fabric API, Sinytra Connector, Connector Extras, dawn, Promenade and Organics.
2. Launch the game and start a new world.
3. Game crashes

### Logs

https://gist.github.com/DarkXFast/10e126a312eedcbe5f780955ed822dbe

**Comment by Su5eD** [comment]
Looks to be the same cause as #472, see that issue for a detailed explanation. I've taken a look at Organics' code, and they happen to be replacing the biome source completely, which is not a good approach to adding new biomes. Unfortunately, the mod is closed source and doesn't have any github repo / issue tracker, so I can't submit a fix either.
