### ISSUE TITLE
Mini Placeholders LuckPerms Expansion Fabric 1.4.1

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#507]
### Mod Name

Mini Placeholders LuckPerms Expansion Fabric 1.4.1

### Mod Homepage

https://modrinth.com/plugin/luckperms-expansion/version/1.4.1

### Describe the bug

Crash server to launch

### Steps to reproduce

1. Install Mini Placeholders LuckPerms Expansion Fabric 1.4.1
2. Install MiniPlaceholders-Fabric-2.2.23 https://modrinth.com/plugin/miniplaceholders/version/XFqlqnMW
3. Start server

### Logs

https://mclo.gs/KUqmLQ6

**Comment by Su5eD** [comment]
The version of MiniPlaceholders-Fabric you linked is listed to be made for minecraft 1.20.2 rather than 1.20.1. Have you tried using version [2.2.1](https://modrinth.com/plugin/miniplaceholders/version/bKlpE4fA) instead?

I tested it on the current dev build and everything works fine

**Comment by DonorKrovi** [comment]
> Member

Well, I was sure I downloaded the 1 20 1 version, but it seems to have screwed up, everything works, sorry.
