### ISSUE TITLE
Connector-1.0.0-beta.24+1.20.1 still doesnt work with Cobbreeding cobblemon add on mod

### ISSUE THREAD

**Issue by FullMetalMaster** [Sinytra/Connector#510]
### Mod Name

Cobbreeding

### Mod Homepage

https://modrinth.com/mod/cobbreeding/versions

### Describe the bug

exit Code Zero crash on Startup

### Steps to reproduce

1. cobblemon forge add on mods the mod and question load and crash kotlinforforge as well 
[latest.log](https://github.com/Sinytra/Connector/files/13329840/latest.log)

### Logs

uploaded it

**Comment by Su5eD** [comment]
Both Cobblemon and Cobbreeding work fine for me on beta 24

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
