### ISSUE TITLE
Networking Issues with Immersive Portals

### ISSUE THREAD

**Issue by Charismara** [Sinytra/Connector#513]
### Describe the bug

Walking though a portal causes player on a Server to not being able to run commands and sometimes kick them out of the server

### Steps to reproduce

1. Create a Server
2. Open a Nether Portal
2. Run a Command (which should work just fine)
3. Walk though the portal
4. Run the Command again (which does nothing at all)
5. Kill a mob and the Server will kick you with an "internal server error"

### Logs

Not sure but i think those messages are related: https://mclo.gs/QRU1SP1

### Additional context

As far as i know this only happends on Servers

**Comment by Su5eD** [comment]
Your log also mentions mods like bloodmagic or clumps. Have you tried reproducing this issue with only immersive portals installed?

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
