### ISSUE TITLE
360 mods crashes the game, but 359 mods doesnt

### ISSUE THREAD

**Issue by TechSupportRed** [Sinytra/Connector#514]
### Describe the bug

It crashes as soon as 360 mods is added, at 359 it doesn't crash.

### Steps to reproduce

1. Sinytra Connector 
2. Add 360 mods
3. Crashes on startup due to fabric-screen-api for me
...

### Logs

https://gist.github.com/TechSupportRed/26577c9d96438f55fc8073a3661c2093

### Additional context

It crashes instantly when 360 mods is added, but 359 mods is perfectly fine. It seems to point to sinytra connector due to these fabric api references in it.

**Comment by SettingDust** [comment]
Seems fancymenu

**Comment by TechSupportRed** [comment]
Removed fancymenu and another mod started causing issues

**Comment by TechSupportRed** [comment]
An error always occurs when I hit 360 mods, I tried installing any random mod and crashes still occur

**Comment by SettingDust** [comment]
> An error always occurs when I hit 360 mods, I tried installing any random mod and crashes still occur. At 359 mods every mod works perfectly fine. FancyMenu isn't the error as when I removed it another mod starts to bug out.

Show the another one. Need look into

**Comment by TechSupportRed** [comment]
Removed Essential and error is still occuring

https://gist.github.com/TechSupportRed/41c8c4e45b86cf2ba9d4a054d95d6625

**Comment by SettingDust** [comment]
> Removed Essential and error is still occuring

FancyMenu. 

> Show the another one. Need look into

**Comment by TechSupportRed** [comment]
Yeah, fancymenu seems to not like sinytra connector too much after 360 mods. Immediately crashed with 360 mods with fancymenu installed, and without installed it worked perfectly fine.

**Comment by TechSupportRed** [comment]
**With FancyMenu**
https://gist.github.com/TechSupportRed/54b4a5660ff01c3486a41cf4e09a9a9e

**Without FancyMenu**
https://gist.github.com/TechSupportRed/b6b86f6e2eea43b377068dae5429ce3c

**Comment by SettingDust** [comment]
> **With FancyMenu** [gist.github.com/TechSupportRed/54b4a5660ff01c3486a41cf4e09a9a9e](https://gist.github.com/TechSupportRed/54b4a5660ff01c3486a41cf4e09a9a9e)
> 
> **Without FancyMenu** [gist.github.com/TechSupportRed/b6b86f6e2eea43b377068dae5429ce3c](https://gist.github.com/TechSupportRed/b6b86f6e2eea43b377068dae5429ce3c)

Just fancymenu crashing. Can you test the minimal replicable mod?

**Comment by TechSupportRed** [comment]
> Just fancymenu crashing. Can you test the minimal replicable mod?
Can you send me a link to it, I don't know this mod. I can't locate it on google either

**Comment by SettingDust** [comment]
> Can you send me a link to it, I don't know this mod. I can't locate it on google either

Ooops. Sry for poor Eng. I mean find out the minimal reproducible mod set

**Comment by TechSupportRed** [comment]
What does minimal reproducible mean? Sorry I don't understand what it means

**Comment by SettingDust** [comment]
> What does minimal reproducible mean? Sorry I don't understand what it means

With least mod that can reproduce the crash

**Comment by TechSupportRed** [comment]
The least amount of mods that can reproduce this crash from what I noticed is 358 and above. 357 works perfectly fine, 359 crashes heavily, and 360 mods goes through the entire loading menu and then crashes.

**Comment by SettingDust** [comment]
> The least amount of mods that can reproduce this crash from what I noticed is 358 and above. 357 works perfectly fine, 359 crashes heavily, and 360 mods goes through the entire loading menu and then crashes.

Isn't a conflicting instead of mod count? That's unusual

**Comment by TechSupportRed** [comment]
It's not a conflicting mod, any mod that goes above 357 just immediately crashes the game.

**Comment by Xplodin** [comment]
> It's not a conflicting mod, any mod that goes above 357 just immediately crashes the game.

yes it is because I have 440 mods with connector and it does NOT crash

**Comment by SettingDust** [comment]
> yes it is because I have 440 mods with connector and it does NOT crash

FancyMenu?

**Comment by TechSupportRed** [comment]
> yes it is because I have 440 mods with connector and it does NOT crash

I think its just fancymenu and sinytra connector being incompatible after a point, even some assets in fancymenu just show the error texture.

**Comment by TechSupportRed** [comment]
It's fixed now! Thank you.

Should I leave this open till the ffapi is updated on curseforge/modrinth?

**Comment by Su5eD** [comment]
Released FFAPI [0.90.7+1.10.1+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.90.7+1.10.1+1.20.1) containing the fix.
