### ISSUE TITLE
Dashloader mod bug

### ISSUE THREAD

**Issue by DoritosSpR** [Sinytra/Connector#515]
### Describe the bug

When i use dashloader with connector it shows this

### Steps to reproduce

![Captura de pantalla 2023-11-18 192134](https://github.com/Sinytra/Connector/assets/122171434/30d6e999-c6aa-44a0-8bd5-9e73704aeafc)

**Comment by StormDragon-64** [comment]
How did you even get it to run? It still crashes for me.

**Comment by coco875** [comment]
dashloader have conflict with modernFix and give less optimisation then modernfix so use modernfix instead who are compatible with connector
