### ISSUE TITLE
Mythic Metals/Alloy Forgery Doesnt Work on Beta 25

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#516]
### Describe the bug

Crashes on start up

### Steps to reproduce

Connector-1.0.0-beta.25+1.20.1.jar

alloy-forgery-2.0.22+1.20.jar

cloth-config-11.1.106-forge.jar

ConnectorExtras-1.6.1+1.20.1.jar

fabric-api-0.90.7+1.9.32+1.20.1.jar

mythicmetals-0.18.2+1.20.jar

owo-lib-0.11.2+1.20.jar

### Logs

https://pastebin.com/UJeQ2gQw

**Comment by SettingDust** [comment]
The log seems not relate to the issue. Need double check or debug log

**Comment by RoomAlex68** [comment]
Crashed on connector beta 33
