### ISSUE TITLE
"mcdw", "mcda" and "AdventureZ" can cause crashes on startup

### ISSUE THREAD

**Issue by wsxiya** [Sinytra/Connector#517]
### Describe the bug

"mcdw", "mcda" and "AdventureZ" can cause crashes on startup

### Steps to reproduce

1.There is no problem adding AdventureZ into the game
2.Add "mcdw" "mcda"
3.Game crashes on launch
...

**Comment by wsxiya** [comment]
fabric-api-0.90.7+1.9.33+1.20.1.jar
Connector-1.0.0-beta.25+1.20.1.jar
ConnectorExtras-1.6.1+1.20.1.jar
cloth-config-11.1.106-fabric.jar
mcdw-8.1.0.jar
voidz-1.0.10.jar
adventurez-1.4.19.jar

**Comment by rainysux** [comment]
you need clumps fabric

**Comment by wsxiya** [comment]
> 你需要团块面料

I did not add the "clumps" mod

**Comment by rainysux** [comment]
well download it https://modrinth.com/mod/clumps/version/5q2RWTZ9 mcda needs it

**Comment by wsxiya** [comment]
> 好吧[，https://modrinth.com/mod/clumps/version/5q2RWTZ9](https://modrinth.com/mod/clumps/version/5q2RWTZ9) MCDA需要它，织物版本

The game still crashes on startup，Crash when "AdventureZ" is present with "mcda" or "madw"

**Comment by nanachijiang** [comment]
I have the same problem.

To be precise, the "mcdw" mod caused the crash. 
I have test mcda and i found it has no problem.

with Connector 1.0.0-beta.25, 
Forgified Fabric API 0.90.7+1.10.0, 
ConnectorExtras 1.6.1.

**Comment by wsxiya** [comment]
> 我有同样的问题。
> 
> 准确地说，“mcdw”mod 导致了崩溃。我测试了mcda，发现它没有问题。
> 
> 连接器 1.0.0-beta.25、Forgified Fabric API 0.90.7+1.10.0、ConnectorExtras 1.6.1。
Yes, I just tested it again, "mcdw" will make the game crash

**Comment by nanachijiang** [comment]
> well download it https://modrinth.com/mod/clumps/version/5q2RWTZ9 mcda needs it, fabric version

Sorry, this is useless. The Clumps affact the XP orbs only, which means it has nothing to do with mcdw. mcdw is mainly focuse on weapons. Maybe you mistake mcdw for another mod. 

mcdw = minecraft dungeon weapon

**Comment by Su5eD** [comment]
Please provide a log, I can't reproduce this with only adventurez and mcdw installed

**Comment by nanachijiang** [comment]
[minecraft-exported-crash-info-2023-11-22T22-04-14.zip](https://github.com/Sinytra/Connector/files/13443967/minecraft-exported-crash-info-2023-11-22T22-04-14.zip)
