### ISSUE TITLE
Nvidium incompatability

### ISSUE THREAD

**Issue by Matthew-MBG** [Sinytra/Connector#518]
### Mod Name

Nvidium

### Mod Homepage

https://github.com/MCRcortex/nvidium

### Describe the bug

The game does not open due to relying on Sodium.

### Steps to reproduce

1. Open the game
2. Don't profit

### Logs

https://pastebin.com/raw/HfUjXuNs

**Comment by Wanderer70** [comment]
Maaan, having Nvidium on Forge too would be so cool tho!

**Comment by MCRcortex** [comment]
@Matthew-MBG you need to upload the full log, this is just the tail end of the crash, however iirc it was something to do with the shader loader not looking in the nvidium jar for the shader

**Comment by Su5eD** [comment]
The issue came down to Nvidium not being able to load a shader, which later resulted in the game crashing. I've submitted a fix for this to embeddium which allows it to load shaders from other mods as well, restoring the original sodium behavior.

**Comment by MCRcortex** [comment]
thank you! Much appreciated for the effort and (hopefully) fix

**Comment by hiimrickross** [comment]
> @Wanderer70, they do in fact work (I edited a file to make it look for Oculus rather than Iris), but "working" means Revidium (new name) disables itself. Do remember, this is simply just me modifying like 4 files to get the requirements working, and I am no developer.

wait so.... if you use nvidium with sinytra via your adjustments, it works - but if you use shaders like complimentaryreimagined, nvidium will disable itself ? just wondering since i added your first file "Thanks for the fix! This now works!" post, and i got into my world just fine. Going to try the latest commit #12 where its labelled revidium now... And then without it for performance comparison.

**Comment by Matthew-MBG-Alt** [comment]
Just an update for Revidium:

The project has served its purpose, and a more talented developer has continued the same idea under the name acedium. Revidium is now abandoned.

**Comment by Wanderer70** [comment]
NVIDIUM can actually work with Connector now. All you have to do is make two config files in the Minecraft config folder:

**connector.json :**

{
"version": 1,
"hiddenMods": [],
"globalModAliases": {
"cloth_config": "cloth-config2",
"playeranimator": "player-animator",
"embeddium": ["sodium"]
}
}



**fabric_loader_dependencies.json :**

{
"version": 1,
"overrides":{
"nvidium":{
"-depends":{
"sodium": "IGNORED"
},
"+depends":{
"sodium": "*"
}
}
}
}

**Comment by walkthestars** [comment]
> NVIDIUM can actually work with Connector now. Make sure you are using Embeddium as a replacement to Sodium. All you have to do is make two config files in the Minecraft config folder:
> 
> **connector.json :**
> 
> { "version": 1, "hiddenMods": [], "globalModAliases": { "cloth_config": "cloth-config2", "playeranimator": "player-animator", "embeddium": ["sodium"] } }
> 
> **fabric_loader_dependencies.json :**
> 
> { "version": 1, "overrides":{ "nvidium":{ "-depends":{ "sodium": "IGNORED" }, "+depends":{ "sodium": "*" } } } }

does this still work? anything that would need to be updated?

**Comment by VOLKOUL** [comment]
No afaik.
