### ISSUE TITLE
[FAQ] FFAPI recent Forge version support. (Crash)

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#519]
### Describe the bug

FFAPI 0.90.7+1.10.0+1.20.1 claims to have added compatibility with Forge 47.2.+

### Steps to reproduce

1. Install Connector, Extras, FFAPI
2. Launch game on Forge 47.2.6
3. Crash

### Logs

[main/ERROR]: Missing or unsupported mandatory dependencies: 	Mod ID: 'forge', Requested by: 'rootsclassic', Expected range: '[47,47.1.3]', Actual version: '47.2.6'

### Additional context

I suppose Connector itself (or extras) has to receive an update and Curseforge might as well have it under review atm. I am just reporting this in case it is an actual unintended crash. Sorry in advance.

**Comment by Su5eD** [comment]
> Requested by: 'rootsclassic'

The mod `rootsclassic` is not compatible with forge newer than 47.1.3.

**Comment by Wanderer70** [comment]
Ooooh sorry I must be blind...
Bruh...
