### ISSUE TITLE
Game crashes with Modern Industrialization

### ISSUE THREAD

**Issue by TheFieryFalcon** [Sinytra/Connector#522]
### Mod Name

Modern Industrialization

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

### Describe the bug

Game crashes when loading

### Logs

https://pastebin.com/Gw6J9mCZ

**Comment by Su5eD** [comment]
Duplicate of #468, you can find a temporary workaround [here](https://github.com/Sinytra/Connector/issues/468#issuecomment-1819356927)
