### ISSUE TITLE
BCLib + BetterEnd - Connection Lost

### ISSUE THREAD

**Issue by tamanor** [Sinytra/Connector#527]
### Describe the bug

Minecraft 1.20.1
Forge 47.2.1

trying to join my server with BCLib + BetterEnd results in the following 

Connection Lost - Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: ReaderIndex(13) + length(8) exceeds WriterIndex(14): PooledUnsafeDirectByteBuf(ridx: 13, widx 14, cap: 14)

### Steps to reproduce

1.Start Client
2.Try to join my server
3.Connection lost 
...

### Logs
[Error Log Modrith.txt](https://github.com/Sinytra/Connector/files/13444119/Error.Log.Modrith.txt)

### Additional context
This seems to only happen from the server side, and joing a single player world seems to be working perfectly fine, there did not seem to be much going on in the logs before, but just tried and i can see alot of "[worlds_together]" errors getting spammed this time.

**Comment by Xplodin** [comment]
I wonder if my server issue is because of this as well...
no logs or errors pointing to any mods but I get disconnected 
![image](https://github.com/Sinytra/Connector/assets/13007677/8df09725-1287-4b75-8e51-0107a15ab7a2)

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
