### ISSUE TITLE
Enter world failed with Marium's Soulslike Weaponry mod

### ISSUE THREAD

**Issue by nanachijiang** [Sinytra/Connector#528]
### Mod Name

Marium's Soulslike Weaponry

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry

### Describe the bug

Game crashed when enter the world

### Logs

	World Generation: Stable 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge' 	Launched Version: 1.20.1 	Sinytra Connector: 1.0.0-beta.25+1.20.1 		SINYTRA CONNECTOR IS PRESENT! 		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker. 		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues. 		Installed Fabric mods: 		| ================================================== | ============================== | ============================== | ==================== | 		| soulslike-weaponry-1.0.1-1.20-fabric_mapped_srg_1. | Marium's Soulslike Weaponry    | soulsweapons                   | 1.0.1-1.20-fabric    | 		| geckolib-fabric-1.20.1-4.2.4_mapped_srg_1.20.1.jar | GeckoLib 4                     | geckolib                       | 4.2.4                | 		| geckolib-fabric-1.20.1-4.2.4$mclib-20_mapped_srg_1 | mclib                          | com_eliotlash_mclib_mclib      | 20                   | 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.2.6.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.2.6.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.2.6.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.2.6.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.2.6.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		fabric-transfer-api-v1-3.3.2+51502a0077.jar       |Fabric Transfer API (v1)      |fabric_transfer_api_v1        |3.3.2+51502a0077    |DONE      |Manifest: NOSIGNATURE 		fabric-dimensions-v1-2.1.53+8005d10d77.jar        |Fabric Dimensions API (v1)    |fabric_dimensions_v1          |2.1.53+8005d10d77   |DONE      |Manifest: NOSIGNATURE 		soulslike-weaponry-1.0.1-1.20-fabric_mapped_srg_1.|Marium's Soulslike Weaponry   |soulsweapons                  |1.0.1-1.20-fabric   |DONE      |Manifest: NOSIGNATURE 		fabric-renderer-api-v1-3.2.0+19c2527c77.jar       |Fabric Renderer API (v1)      |fabric_renderer_api_v1        |3.2.0+19c2527c77    |DONE      |Manifest: NOSIGNATURE 		geckolib-fabric-1.20.1-4.2.4_mapped_srg_1.20.1.jar|GeckoLib 4                    |geckolib                      |4.2.4               |DONE      |Manifest: NOSIGNATURE 		geckolib-fabric-1.20.1-4.2.4$mclib-20_mapped_srg_1|mclib                         |com_eliotlash_mclib_mclib     |20                  |DONE      |Manifest: NOSIGNATURE 		fabric-model-loading-api-v1-1.0.2+142e25ab77.jar  |Fabric Model Loading API (v1) |fabric_model_loading_api_v1   |1.0.2+142e25ab77    |DONE      |Manifest: NOSIGNATURE 		fabric-item-api-v1-2.1.27+2272fc7f77.jar          |Fabric Item API (v1)          |fabric_item_api_v1            |2.1.27+2272fc7f77   |DONE      |Manifest: NOSIGNATURE 		fabric-rendering-fluids-v1-3.0.27+4ac5e37a77.jar  |Fabric Rendering Fluids (v1)  |fabric_rendering_fluids_v1    |3.0.27+4ac5e37a77   |DONE      |Manifest: NOSIGNATURE 		fabric-screen-handler-api-v1-1.3.29+561530ec77.jar|Fabric Screen Handler API (v1)|fabric_screen_handler_api_v1  |1.3.29+561530ec77   |DONE      |Manifest: NOSIGNATURE 		fabric-resource-loader-v0-0.11.9+142e25ab77.jar   |Fabric Resource Loader (v0)   |fabric_resource_loader_v0     |0.11.9+142e25ab77   |DONE      |Manifest: NOSIGNATURE 		fabric-models-v0-0.4.1+7c3892a477.jar             |Fabric Models (v0)            |fabric_models_v0              |0.4.1+7c3892a477    |DONE      |Manifest: NOSIGNATURE 		fabric-rendering-v1-3.0.7+1c0ea72177.jar          |Fabric Rendering (v1)         |fabric_rendering_v1           |3.0.7+1c0ea72177    |DONE      |Manifest: NOSIGNATURE 		fabric-renderer-indigo-1.5.0+67f9824077.jar       |Fabric Renderer - Indigo      |fabric_renderer_indigo        |1.5.0+67f9824077    |DONE      |Manifest: NOSIGNATURE 		fabric-convention-tags-v1-1.5.4+fa3d1c0177.jar    |Fabric Convention Tags        |fabric_convention_tags_v1     |1.5.4+fa3d1c0177    |DONE      |Manifest: NOSIGNATURE 		fabric-mining-level-api-v1-2.1.49+561530ec77.jar  |Fabric Mining Level API (v1)  |fabric_mining_level_api_v1    |2.1.49+561530ec77   |DONE      |Manifest: NOSIGNATURE 		fabric-command-api-v1-1.2.33+f71b366f77.jar       |Fabric Command API (v1)       |fabric_command_api_v1         |1.2.33+f71b366f77   |DONE      |Manifest: NOSIGNATURE 		fabric-command-api-v2-2.2.12+561530ec77.jar       |Fabric Command API (v2)       |fabric_command_api_v2         |2.2.12+561530ec77   |DONE      |Manifest: NOSIGNATURE 		fabric-block-view-api-v2-1.0.0+0767707077.jar     |Fabric BlockView API (v2)     |fabric_block_view_api_v2      |1.0.0+0767707077    |DONE      |Manifest: NOSIGNATURE 		rei-bridge-1.6.1+1.20.1.jar                       |Connector Extras REI Bridge   |connectorextras_rei_bridge    |1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		geckolib-fabric-compat-1.6.1+1.20.1.jar           |Connector Extras Geckolib-Fabr|connectorextras_geckolib_fabri|1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		continuity-compat-1.6.1+1.20.1.jar                |Connector Extras Continuity Co|connectorextras_continuity_com|1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		fabric-screen-api-v1-2.0.7+45a670a577.jar         |Fabric Screen API (v1)        |fabric_screen_api_v1          |2.0.7+45a670a577    |DONE      |Manifest: NOSIGNATURE 		energy-bridge-1.6.1+1.20.1.jar                    |Connector Extras Energy Bridge|connectorextras_energy_bridge |1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		fabric-particles-v1-1.1.1+78e1ecb877.jar          |Fabric Particles (v1)         |fabric_particles_v1           |1.1.1+78e1ecb877    |DONE      |Manifest: NOSIGNATURE 		forge-1.20.1-47.2.6-universal.jar                 |Forge                         |forge                         |47.2.6              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 		fabric-api-0.90.7+1.10.1+1.20.1.jar               |Forgified Fabric API          |fabric_api                    |0.90.7+1.10.1+1.20.1|DONE      |Manifest: NOSIGNATURE 		modmenu-bridge-1.6.1+1.20.1.jar                   |Connector Extras ModMenu Bridg|connectorextras_modmenu_bridge|1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		fabric-content-registries-v0-4.0.10+a670df1e77.jar|Fabric Content Registries (v0)|fabric_content_registries_v0  |4.0.10+a670df1e77   |DONE      |Manifest: NOSIGNATURE 		terrablender-bridge-1.6.1+1.20.1.jar              |Connector Extras Terrablender |connectorextras_terrablender_b|1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		fabric-transitive-access-wideners-v1-4.3.0+1880499|Fabric Transitive Access Widen|fabric_transitive_access_widen|4.3.0+1880499877    |DONE      |Manifest: NOSIGNATURE 		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		fabric-game-rule-api-v1-1.0.39+461110ab77.jar     |Fabric Game Rule API (v1)     |fabric_game_rule_api_v1       |1.0.39+461110ab77   |DONE      |Manifest: NOSIGNATURE 		fabric-api-base-0.4.30+ef105b4977.jar             |Fabric API Base               |fabric_api_base               |0.4.30+ef105b4977   |DONE      |Manifest: NOSIGNATURE 		fabric-api-lookup-api-v1-1.6.35+67f9824077.jar    |Fabric API Lookup API (v1)    |fabric_api_lookup_api_v1      |1.6.35+67f9824077   |DONE      |Manifest: NOSIGNATURE 		fabric-blockrenderlayer-v1-1.1.40+1d0da21e77.jar  |Fabric BlockRenderLayer Regist|fabric_blockrenderlayer_v1    |1.1.40+1d0da21e77   |DONE      |Manifest: NOSIGNATURE 		amecsapi-1.5.3+mc1.20-pre1.jar                    |Amecs API                     |amecsapi                      |1.5.3+mc1.20-pre1   |DONE      |Manifest: NOSIGNATURE 		fabric-block-api-v1-1.0.10+0e6cb7f777.jar         |Fabric Block API (v1)         |fabric_block_api_v1           |1.0.10+0e6cb7f777   |DONE      |Manifest: NOSIGNATURE 		reach-entity-attributes-2.4.0.jar                 |Reach Entity Attributes       |reach_entity_attributes       |2.4.0               |DONE      |Manifest: NOSIGNATURE 		fabric-resource-conditions-api-v1-2.3.6+369cb3a477|Fabric Resource Conditions API|fabric_resource_conditions_api|2.3.6+369cb3a477    |DONE      |Manifest: NOSIGNATURE 		architectury-bridge-1.6.1+1.20.1.jar              |Connector Extras Architectury |connectorextras_architectury_b|1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		fabric-item-group-api-v1-4.0.11+9801bf5177.jar    |Fabric Item Group API (v1)    |fabric_item_group_api_v1      |4.0.11+9801bf5177   |DONE      |Manifest: NOSIGNATURE 		Connector-1.0.0-beta.25+1.20.1-mod.jar            |Connector                     |connectormod                  |1.0.0-beta.25+1.20.1|DONE      |Manifest: NOSIGNATURE 		fabric-biome-api-v1-13.0.12+dd0389a577.jar        |Fabric Biome API (v1)         |fabric_biome_api_v1           |13.0.12+dd0389a577  |DONE      |Manifest: NOSIGNATURE 		fabric-entity-events-v1-1.5.22+b909fbe377.jar     |Fabric Entity Events (v1)     |fabric_entity_events_v1       |1.5.22+b909fbe377   |DONE      |Manifest: NOSIGNATURE 		fabric-registry-sync-v0-2.3.2+1c0ea72177.jar      |Fabric Registry Sync (v0)     |fabric_registry_sync_v0       |2.3.2+1c0ea72177    |DONE      |Manifest: NOSIGNATURE 		fabric-recipe-api-v1-1.0.20+514a076577.jar        |Fabric Recipe API (v1)        |fabric_recipe_api_v1          |1.0.20+514a076577   |DONE      |Manifest: NOSIGNATURE 		fabric-object-builder-api-v1-11.1.2+2174fc8477.jar|Fabric Object Builder API (v1)|fabric_object_builder_api_v1  |11.1.2+2174fc8477   |DONE      |Manifest: NOSIGNATURE 		fabric-loot-api-v2-1.2.0+eb28f93e77.jar           |Fabric Loot API (v2)          |fabric_loot_api_v2            |1.2.0+eb28f93e77    |DONE      |Manifest: NOSIGNATURE 		ConnectorExtras-1.6.1+1.20.1.jar                  |Connector Extras              |connectorextras               |1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		fabric-rendering-data-attachment-v1-0.3.36+a6081af|Fabric Rendering Data Attachme|fabric_rendering_data_attachme|0.3.36+a6081afc77   |DONE      |Manifest: NOSIGNATURE 		fabric-networking-api-v1-1.3.10+503a202477.jar    |Fabric Networking API (v1)    |fabric_networking_api_v1      |1.3.10+503a202477   |DONE      |Manifest: NOSIGNATURE 		fabric-sound-api-v1-1.0.12+4f23bd8477.jar         |Fabric Sound API (v1)         |fabric_sound_api_v1           |1.0.12+4f23bd8477   |DONE      |Manifest: NOSIGNATURE 		fabric-message-api-v1-5.1.8+52cc178c77.jar        |Fabric Message API (v1)       |fabric_message_api_v1         |5.1.8+52cc178c77    |DONE      |Manifest: NOSIGNATURE 		emi-bridge-1.6.1+1.20.1.jar                       |Connector Extras EMI Bridge   |connectorextras_emi_bridge    |1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE 		fabric-lifecycle-events-v1-2.2.21+afab492177.jar  |Fabric Lifecycle Events (v1)  |fabric_lifecycle_events_v1    |2.2.21+afab492177   |DONE      |Manifest: NOSIGNATURE 		fabric-data-generation-api-v1-12.3.2+369cb3a477.ja|Fabric Data Generation API (v1|fabric_data_generation_api_v1 |12.3.2+369cb3a477   |DONE      |Manifest: NOSIGNATURE 		fabric-events-interaction-v0-0.6.1+25d9948677.jar |Fabric Events Interaction (v0)|fabric_events_interaction_v0  |0.6.1+25d9948677    |DONE      |Manifest: NOSIGNATURE 		fabric-key-binding-api-v1-1.0.36+561530ec77.jar   |Fabric Key Binding API (v1)   |fabric_key_binding_api_v1     |1.0.36+561530ec77   |DONE      |Manifest: NOSIGNATURE 		fabric-client-tags-api-v1-1.1.1+5d6761b877.jar    |Fabric Client Tags            |fabric_client_tags_api_v1     |1.1.1+5d6761b877    |DONE      |Manifest: NOSIGNATURE 	Crash Report UUID: f434aa9f-5264-4927-ad8d-0ad1e696a0bc 	FML: 47.2 	Forge: net.minecraftforge:47.2.6 #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\86151\Desktop\游戏\MC\互联测试\.minecraft\crash-reports\crash-2023-11-22_22.29.23-server.txt 2023-11-22 22:29:23,753 Server thread WARN Error parsing URI C:\Users\86151\Desktop\游戏\MC\互联测试\.minecraft\versions\1.20.1\log4j2.xml 2023-11-22 22:29:23,791 Server thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger

### Additional context

I'm using forge 47.2.6
Mod list here, without the two mods I crossed out in red.
![image](https://github.com/Sinytra/Connector/assets/149419724/0da0c335-16fd-47d7-bf89-5790d1a58c6d)

Full log documents here
[minecraft-exported-crash-info-2023-11-22T22-29-28.zip](https://github.com/Sinytra/Connector/files/13444143/minecraft-exported-crash-info-2023-11-22T22-29-28.zip)

**Comment by TechSupportRed** [comment]
Is 47.2+ supported with Connector now? I thought it was just forgified fabric api

**Comment by RoomAlex68** [comment]
You sure?? Marium’s Soulslike Weaponery works for me on Forgified Fabric API on 47.2.6 and Connector Beta 25

**Comment by nanachijiang** [comment]
> You sure?? Marium’s Soulslike Weaponery works for me on Forgified Fabric API on 47.2.6 and Connector Beta 25

Did u tried to creat and enter a world? My game crashed at that moment

**Comment by nanachijiang** [comment]
> You sure?? Marium’s Soulslike Weaponery works for me on Forgified Fabric API on 47.2.6 and Connector Beta 25

Would u mind to tell me ur java's version?

**Comment by itzinxta** [comment]
downgrade soulslike weaponry below ver 1.0.0.

**Comment by RoomAlex68** [comment]
> > You sure?? Marium’s Soulslike Weaponery works for me on Forgified Fabric API on 47.2.6 and Connector Beta 25
> 
> Would u mind to tell me ur java's version? 

My Java Version was 1.20.1 Forge 47.2.6

**Comment by RoomAlex68** [comment]
> > You sure?? Marium’s Soulslike Weaponery works for me on Forgified Fabric API on 47.2.6 and Connector Beta 25
> 
> Did u tried to creat and enter a world? My game crashed at that moment

Yes and It didn't crash for me

**Comment by RoomAlex68** [comment]
Geckolib Fabric works with Marium’s Soulslike Weaponery and yes I need the Forge version of Geckolib to run Iron Spells and spellbooks because Geckolib Forge and Fabric are not compatible together. Marium’s Soulslike Weaponery new update crashes the game.

**Comment by mariumbacchus** [comment]
I've just released the version 1.0.2 that fixes the mixin confliction, so it will now work with connector.

**Comment by nanachijiang** [comment]
> I've just released the version 1.0.2 that fixes the mixin confliction, so it will now work with connector.

Godness!  thanks u soooooo much sir!

**Comment by RoomAlex68** [comment]
Marium’sSoulslikeWeaponery 1.0.2 crashes on Connector beta 29

**Comment by mariumbacchus** [comment]
Worked fine for me when using the recommended forge version and geckolib fabric... did it say anything specific in the crash log?

**Comment by Aylel** [comment]
I confirm to my great misfortune, the mod is incompatible :(

**Comment by RoomAlex68** [comment]
What do you mean. It works for me on Connector Beta 36.

**Comment by RoomAlex68** [comment]
Am using Marium’s Soulslike Weaponery 1.02

**Comment by Aylel** [comment]
Yes so the latest version 1.20.1...It's weird for me, it's impossible to make it work...:(

**Comment by Aylel** [comment]
Have you installed a mod in addition to connector and Marium’s Soulslike Weaponery?

**Comment by RoomAlex68** [comment]
Connector beta 36
Forgified Fabric API: 0.91.0+1.10.8+1.20.1
Forge 4.7.13
Geckolib-fabric-1.20.1-4.4.2

**Comment by Aylel** [comment]
And do you use other forge mods with this?

**Comment by RoomAlex68** [comment]
Nope

**Comment by Aylel** [comment]
Maybe that's the difference, our server has around 300 mods :/

**Comment by RoomAlex68** [comment]
Am running the mods on client that's why

**Comment by Su5eD** [comment]
Confirmed to work on Forge 47.1.3 using the following mods:
- Connector-1.0.0-beta.36+1.20.1
- fabric-api-0.92.0+1.11.1+1.20.1
- geckolib-fabric-1.20.1-4.4.2
- soulslike-weaponry-1.0.2-1.20-fabric
