### ISSUE TITLE
More Banner Features is incompatible

### ISSUE THREAD

**Issue by Liamgrayskull** [Sinytra/Connector#536]
### Mod Name

Nature's Spirit

### Mod Homepage

https://modrinth.com/mod/natures-spirit

### Describe the bug

A crash on startup

### Steps to reproduce

1.Update Nature's Spirit, Forgified Fabric API and Sinytra Connector
2.Run on latest available 1.20.1 forge version 
3.Crash upon startup
...

### Logs

https://gist.github.com/Liamgrayskull/9d038052aea0ff418da5afa1704b794d

### Additional context

In the modpack Inquisitive https://modrinth.com/modpack/inquisitive

**Comment by Su5eD** [comment]
This looks like an issue with morebannerfeatures rather than Nature's Spirit
