### ISSUE TITLE
fabric outdated? - Paladins & Priests

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#538]
### Mod Name

Paladins & Priests

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/paladins-and-priests/files/4873387

### Describe the bug

failed start up.

### Steps to reproduce

![Screenshot (1)](https://github.com/Sinytra/Connector/assets/69068153/2e3bbff3-60c5-45eb-9753-c64c0d6bc726)

### Logs

https://gist.github.com/Cixon/649610cc30c6247bfb641ed8cf41747f

**Comment by Su5eD** [comment]
I tested this and it works just fine. Have you installed the Forgified Fabric API?
