### ISSUE TITLE
Simple armor Hud compat

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#542]
### Mod Name

Simple armor Hud

### Mod Homepage

https://github.com/LegoRaft/simple-armor-hud

### Describe the bug

Crash at startup

### Steps to reproduce

--

### Logs

https://mclo.gs/NxOB0Pv

**Comment by Su5eD** [comment]
Seems to work fine on Forge 47.1.3. Can you use that version instead?

**Comment by Lolothepro** [comment]
yeap (should I leave the bug report open or not?)
