### ISSUE TITLE
AdditionZ seems to be incompatible with connector

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#543]
### Mod Name

AdditionZ

### Mod Homepage

https://modrinth.com/mod/additionz

### Describe the bug

Game crashing before main menu

### Logs

https://gist.github.com/Its-Just-Luci/25d69f64040dea549e412c277a93a112

**Comment by RoomAlex68** [comment]
It also crashes with Dehydration mod and Environment Mod

**Comment by RoomAlex68** [comment]
Crashes on beta 28
