### ISSUE TITLE
Crash During Launch [1.20.1]

### ISSUE THREAD

**Issue by lanwoodall423** [Sinytra/Connector#547]
### Describe the bug

Crash during launch.

### Steps to reproduce

1. Install Sinytra and Forgified API with my modset
2. Launch
3.
...

### Logs

https://pastebin.com/nLnDD4e1

### Additional context

I'm using a modset with only Forge mods so I guess one or more are incompatible.

Forge 47.2.6 with Sinytra Beta 26, Forgified Fabric API 0.90.7+1.10.2+1.20.1, Connector Extras 1.7

**Comment by lanwoodall423** [comment]
https://pastebin.com/uYpiAdNf

For me Beta 25 gives (I think) the exact same log except for an earlier crash if Shield Overhaul (Forge) is installed. The attached log is after it is removed with Beta 25.

**Comment by melontini** [comment]
Wanted to add that random mixin failures also happens with Andromeda/Dark Matter. Looks like remapping broke in 26.

Fields are no longer properly remapped: in 25: `field_40859` is `f_243839_` and in 26: `field_40859` is `field_40859`

**Comment by dnelson22** [comment]
Remove Connector Extras. That should fix your issue.

**Comment by lanwoodall423** [comment]
> Remove Connector Extras. That should fix your issue.

https://pastebin.com/nx7vX8LY

Removing Connector Extras results in the shield overhaul crash. Removing shield overhaul as well results in (I think) the same original crash. Attached

**Comment by lanwoodall423** [comment]
![image](https://github.com/Sinytra/Connector/assets/31048810/ebc9966e-19f6-4f85-8bdb-7b030efee3d9)

This is the final error in the log. I'll provide any additional info or test if needed.

**Comment by lanwoodall423** [comment]
[latest.log](https://github.com/Sinytra/Connector/files/13479292/latest.log)
Same issue in Beta 27. (Connector Extras disabled still)

**Comment by lanwoodall423** [comment]
Forge 47.2.6
Sinytra Beta 27
Forgified Fabric API 0.90.7
The Pure Suffering 1.6.0.1R
[crash-2023-11-27_18.04.40-fml.txt](https://github.com/Sinytra/Connector/files/13481480/crash-2023-11-27_18.04.40-fml.txt)
[latest.log](https://github.com/Sinytra/Connector/files/13481477/latest.log)

Forge 47.2.6
Sinytra Beta 27
Forgified Fabric API 0.90.7
Architectury 9.1.12
Truly Modular API 1.0.6
Truly Modular Archery 1.1
Truly Modular Armory 1.0
Truly Modular Arsenal 1.0
[crash-2023-11-27_18.07.48-client.txt](https://github.com/Sinytra/Connector/files/13481498/crash-2023-11-27_18.07.48-client.txt)
[latest.log](https://github.com/Sinytra/Connector/files/13481493/latest.log)

**Comment by dnelson22** [comment]
Downgrade to version 47.1.3

**Comment by lanwoodall423** [comment]
> Downgrade to version 47.1.3
Still crashes with only ffapi, sinytra and one of the two on 47.1.3

Truly Modular
[crash-2023-11-28_09.37.44-client.txt](https://github.com/Sinytra/Connector/files/13489337/crash-2023-11-28_09.37.44-client.txt)
[latest.log](https://github.com/Sinytra/Connector/files/13489338/latest.log)


The Pure Suffering Mod
[crash-2023-11-28_09.39.23-fml.txt](https://github.com/Sinytra/Connector/files/13489359/crash-2023-11-28_09.39.23-fml.txt)
[latest.log](https://github.com/Sinytra/Connector/files/13489364/latest.log)

**Comment by dnelson22** [comment]
Remove the mod Miapi

**Comment by dnelson22** [comment]
And any mods that require that API

**Comment by lanwoodall423** [comment]
The crash was caused by missing Caelus API. So Truly Modular works with only its prereqs, Sinyta/ffapi. There is some incompatibility with it though with other mods in the mix. I sent detail in a new issue specifically regarding Truly Modular series. I have a modset that works with sinytra/ffapi but breaks when Truly Modular is added. If sinytra/ffapi is removed  Truly Modular works.

**Comment by dnelson22** [comment]
ok then do it alright. That should fix your isues.
