### ISSUE TITLE
Crash with beta.26 & beta.27

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#548]
### Describe the bug

Crash on startup

### Steps to reproduce

1. Install Connector, FFAPI, Extras
2. Launch game
3. Crash

### Logs

[main/ERROR]: Non-unique Mixin config name mixinextras.init.mixins.json used by the mods com_github_llamalad7_mixinextras and mixinextras

### Additional context

The line above is the only error in the log. It appears to be a Connector issue, rather than an incompatible mod, as with beta.25 everything works perfectly well.

**Comment by dnelson22** [comment]
What mods are you using?

**Comment by Wanderer70** [comment]
Uno momento

**Comment by Wanderer70** [comment]
If you need anything else, I'll be waiting. I don't really know what else I can do, as checking THAT amount of mods by hand is like entering hell.

**Comment by Wanderer70** [comment]
But as I said, with beta.25 everything is fine

**Comment by Su5eD** [comment]
Try using beta 27

**Comment by dnelson22** [comment]
Remove optifine and iris shaders.

**Comment by dnelson22** [comment]
Remove the replay mod.

**Comment by RoomAlex68** [comment]
Replay mod works for me on Connector Beta 27

**Comment by Wanderer70** [comment]
I haven't tried it without Replay Mod yet. I believe the assumption of it being the problematic mod came from another issue.

**Comment by Wanderer70** [comment]
Whatever this was, it is now fixed in beta.29! Thank you!
Closing issue.
