### ISSUE TITLE
Identity mod crashes the game Forge 1.20.1

### ISSUE THREAD

**Issue by dnelson22** [Sinytra/Connector#549]
### Mod Name

Identity

### Mod Homepage

curseforge.com/minecraft/mc-mods/identity

### Describe the bug

It crashes the game while loading.

### Steps to reproduce

1. Click play in Minecraft Launcher.
2. Red Mojang loading screen appears
3. The game crashes.
...

### Logs

https://hastebin.com/share/ixaxaropem.vbnet

### Additional context

Please help!

**Comment by Su5eD** [comment]
> [26Nov2023 14:03:02.561] [main/WARN] [mixin/]: `@Redirect` conflict. Skipping identity.mixins.json:LivingEntityMixin from mod identity->`@Redirect`::cancelAirIncrement(Lnet/minecraft/world/entity/LivingEntity;I)V with priority 1000, already redirected by exotelcraft.mixins.json:entity.LivingEntityMixin from mod exotelcraft->`@Redirect`::baseTickAir(Lnet/minecraft/world/entity/LivingEntity;I)V with priority 1000

This is a conflict between the Identity and Exotelcraft mods. I've tried installing both in a Forge instance without Connector installed and the game crashed with the exact same error. I recommend reporting this issue to the mods' authors.
