### ISSUE TITLE
Truly Modular - Crash on Launch

### ISSUE THREAD

**Issue by lanwoodall423** [Sinytra/Connector#554]
### UPDATE - READ FIRST COMMENT

Truly Modular Mods

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modular-item-api

### Describe the bug

Crash on launch

### Steps to reproduce

1. Install the triad
2. Install all Truly Modular mods
3. Launch
...

### Logs

https://github.com/Sinytra/Connector/files/13481498/crash-2023-11-27_18.07.48-client.txt

### Additional context

Forge 47.2.6
Sinytra Beta 27
Forgified Fabric API 0.90.7
Architectury 9.1.12
Truly Modular API 1.0.6
Truly Modular Archery 1.1
Truly Modular Armory 1.0
Truly Modular Arsenal 1.0
[crash-2023-11-27_18.07.48-client.txt](https://github.com/Sinytra/Connector/files/13481498/crash-2023-11-27_18.07.48-client.txt)
[latest.log](https://github.com/Sinytra/Connector/files/13481493/latest.log)

**Comment by lanwoodall423** [comment]
I see now curseforge doesn't automatically download the Caelus API requirement for Truly Modular which caused this crash. 

I do however have a modset that works with sinytra/ffapi but breaks when Truly Modular is added. If sinytra/ffapi is removed, Truly Modular works with it fine. It may be a multiple mod incompatibility but I can't spend any more time troubleshooting. Maybe someone else is willing to or can understand the log below which is the modset + Sinyta/ffapi + Truly Modular series on Forge 47.2.6

[latest.log](https://github.com/Sinytra/Connector/files/13489703/latest.log)
[crash-2023-11-27_18.59.14-client.txt](https://github.com/Sinytra/Connector/files/13489709/crash-2023-11-27_18.59.14-client.txt)

**Comment by Su5eD** [comment]
Looks like a mixin conflict in FFAPI, I'll push a fix
