### ISSUE TITLE
Crash on Create World

### ISSUE THREAD

**Issue by lanwoodall423** [Sinytra/Connector#555]
### Describe the bug

Crash on Create World

### Steps to reproduce

1. Install triad
2. Install other mods
3. Click Create World or Enter World

...

### Logs

https://github.com/Sinytra/Connector/files/13482176/latest.log

### Additional context

[latest.log](https://github.com/Sinytra/Connector/files/13482176/latest.log)
[crash-2023-11-27_18.59.14-client.txt](https://github.com/Sinytra/Connector/files/13482185/crash-2023-11-27_18.59.14-client.txt)

Forge 47.2.6
Sinytra Beta 27
Forgified Fabric API 0.90.7

A lot of other mods.

**Comment by Su5eD** [comment]
> Install other mods

Please determine the exact mods required to reproduce the issue (such as using binary search).

**Comment by lanwoodall423** [comment]
This was fixed by the latest ffapi update
