### ISSUE TITLE
Nvidium/Revidium causes a crash when joining a world

### ISSUE THREAD

**Issue by tomasz-brak** [Sinytra/Connector#558]
### Mod Name

Nvidium + Embedium, changed requirements 

### Mod Homepage

https://github.com/Matthew-MBG/Revidium/actions/runs/7008694371

### Describe the bug

minecraft crashes 

### Steps to reproduce

1. Install Embedium
2. Install [modified version of Nvidium -> Revidium](https://github.com/Matthew-MBG/Revidium/actions/runs/7008694371)
3. Launch the game
4. Open a new world
5. The game crashes

### Logs

https://mclo.gs/uOwPCLA

### Additional context

Forge: `47.2.8`
### mod list
* Connector-1.0.0-beta.27 1.20.1
* ConnectorExtras-1.7.0 1.20.1
* embeddium-0.2.10 mc1.20.1
* fabric-api-0.90.7 1.10.2 1.20.1
* nvidium-0.2.4-beta

**Comment by Su5eD** [comment]
Embeddium's latest release as of now doesn't support loading shaders from other mods as described [here](https://github.com/Sinytra/Connector/issues/518#issuecomment-1826146743). A fix for this is scheduled for the next embeddium version.

See #518 for more details.
