### ISSUE TITLE
 I know you said you won't support pojav launcher..

### ISSUE THREAD

**Issue by Kisamerr** [Sinytra/Connector#559]
### Describe the bug

No bug

### Steps to reproduce

1..
2.
3.
...

### Additional context

I know you said you don't support pirate launcher and unofficial Minecraft launcher... But pojav is legal according to Microsoft.. all of pojav user need to buy an original copy of Minecraft so they can play ... It still don't support crack player... So I'm hoping you could consider to try making this mod compatible with pojav ... Thanks for your time .. I'm waiting for your reply

**Comment by Su5eD** [comment]
There are no plans to provide support for non-standard launchers as they are unpredictable in terms of code changes. Anything that runs on PC Minecraft Java Edition should in theory be compatible with other launchers as well. If that's not the case, changes might be required to the launcher or the mod, depending on the cause of the issue.

All of Sinytra's projects are open source and free, allowing anyone to add support for tools that fit their needs should they want to.

**Comment by Kisamerr** [comment]
So if I want to change some coding and make it work with pojav where should I start?

**Comment by Kisamerr** [comment]
Srsly?

**Comment by Kisamerr** [comment]
> Just to let you that sinytra connector works on pojavlauncher

Srsly?

**Comment by Kisamerr** [comment]
> Did you not have Forgified Fabric API installed?

I did but idk why it keep crashing.. I've downloaded synitra connector, connector extra, forgified fabric api

**Comment by RoomAlex68** [comment]
What 1.20.1 Forge version are you using?
