### ISSUE TITLE
Rubidium doesn't work with Continuity

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#56]
### Describe the bug

Rubidium doesn't work with Continuity

### Steps to reproduce

Install Continuity, Rubidium and enable connected glass

### Screenshot

Continuity+Rubidium:
![2023-08-15_11 14 09](https://github.com/Sinytra/Connector/assets/68275908/d8e7acbb-2621-41df-bfe4-eed4f405064a)
Continuity:
![2023-08-15_11 13 19](https://github.com/Sinytra/Connector/assets/68275908/8e0f5618-6252-40d6-bea7-6532d79fffcf)

**Comment by Lolothepro** [comment]
compat or bug??

**Comment by Su5eD** [comment]
According to its modrinth page, Continuity will only work with Sodium if Indium is also installed. I think this applies to Rubidium as well. You would likely need to install a Rubidium version of Indium to make it work, which I don't believe exists.

**Comment by Lolothepro** [comment]
https://github.com/Asek3/Reforgium
This exists, but the thing is, it's Fabric API + Indium.

**Comment by Su5eD** [comment]
A fix for running Indium will be included in the next update. However, as explained in the linked issue, we can't guarantee compatibility with other mods that rely on rendering when using third-party optimization mods. For that, I'll refer to the Forge [port](https://github.com/Asek3/Reforgium) of Indium, in case it ever gets updated for 1.20.

**Comment by Lolothepro** [comment]
Note: https://github.com/CaffeineMC/sodium-fabric/pull/1851
