### ISSUE TITLE
Problem upon startup of Minecraft

### ISSUE THREAD

**Issue by ExtremeDiscomfort** [Sinytra/Connector#560]
### Describe the bug

It just crashes whenever I start up the game

### Steps to reproduce

Unfortunately, I don't know how to replicate this, or even if it's an incompatibility, so I'm putting it on what I feel like it is.
[launcher_log.txt](https://github.com/Sinytra/Connector/files/13493627/launcher_log.txt)

**Comment by ExtremeDiscomfort** [comment]
What mod is it incompatible with?

**Comment by Su5eD** [comment]
The crash comes from Eldritch End

**Comment by nvb-uy** [comment]
> The crash comes from Eldritch End

I don't understand why the boat mixin injection is failing? Another mod redirecting the method probably? EE works fine in the 3 modpacks it's in, Better MC 1.20, Medieval MC 1.20 and Prominence II, all of those are forge modpacks using connector to load EE, so I don't think the incompaibility is between connector and eldritch end

**Comment by Su5eD** [comment]
@ExtremeDiscomfort could you please upload your debug.log? It should tell us more about which mixins modified the class prior to EE

**Comment by nvb-uy** [comment]
This is the mixin btw

https://github.com/nvb-uy/Eldritch_End/blob/1.20.1/src/main/java/elocindev/eldritch_end/mixin/boat/BoatTypeMixin.java

**Comment by ExtremeDiscomfort** [comment]
> @ExtremeDiscomfort could you please upload your debug.log? It should tell us more about which mixins modified the class prior to EE

Unfortunately, since I'm still new to this, I don't know how to do that. Do you mean like, the log itself?

**Comment by ExtremeDiscomfort** [comment]
I figured out the issue, I was sending the launcher log, not the modpack log.
[latest.log](https://github.com/Sinytra/Connector/files/13494148/latest.log)

**Comment by ExtremeDiscomfort** [comment]
Problem has been figured out, turns out it had nothing to do with either of these mods. Apologies for wasting your time.
