### ISSUE TITLE
Crashes with Cerbon's Better Becaons if BeaconsForAll isn't installed.

### ISSUE THREAD

**Issue by PlayfulPiano** [Sinytra/Connector#561]
### Mod Name

Cerbon's Better Beacons

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/cerbons-better-beacons-forge

### Describe the bug

The game crashes if you attempt to run connector with CBB unless you also have BFA installed.

### Steps to reproduce

1. Try running Connector with Cerbon's Better Beacons.
2. Crashes

...

### Logs

https://mclo.gs/UpC1Zo9

### Additional context

https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/issues/4

This was reported separately by someone else, but I can also confirm to reproduce the issue independently.

**Comment by Su5eD** [comment]
Seems like the Fabric mixin fork shipped by Connector is a bit more strict about resolving indy refrences in mixins

**Comment by PlayfulPiano** [comment]
I attempted to run the latest beta (v28) with and without BFA installed, and instead it caused a startup crash for me:
[crash-2023-12-02_15.02.20-client.txt](https://github.com/Sinytra/Connector/files/13537256/crash-2023-12-02_15.02.20-client.txt)
Crash doesn't occur when I switch back with v27. Also doesn't occur if I have IPN removed (that's a false mod suspect)
[crash-2023-12-02_14.38.08-client.txt](https://github.com/Sinytra/Connector/files/13537257/crash-2023-12-02_14.38.08-client.txt)

**Comment by PlayfulPiano** [comment]
beta 29 fixed this crash issue!
