### ISSUE TITLE
Startup crash when `.connector` folder isn't generated yet

### ISSUE THREAD

**Issue by mosharky** [Sinytra/Connector#563]
### Describe the bug

Can't nail it down to a specific set of mods, but the game crashes before fully generating the patched jars inside of the `.connector` folder for the first time. Once generated, the game launches without a crash.

### Steps to reproduce

- Tested on Forge 47.2.8 and 47.1.3
- Stops happening after disabling [Sonance](https://modrinth.com/mod/sonance) and [MRU](https://modrinth.com/mod/mru)
- Cannot reproduce outside of [my modpack](https://gist.github.com/mosharky/9d5010607ec35d163220a5db80b80bcb)
    - so it's definitely some sort of incompatibility rather than an issue with Sonance/MRU

1. Enable Sonance + MRU in my modpack
2. Ensure .connector folder hasn't generated
3. Launch the game and crash
4. Launch the game again and you won't crash until you reset the `.connector` folder

### Logs

[prism launcher log](https://mclo.gs/fcHZN04), because latest.log isn't showing this for some reason

### Additional context

I could export the modpack for you because I don't have the time to find what set of mods are involved until a day or two from now, but Sonance/MRU are definitely a part of it I think

**Comment by Liamgrayskull** [comment]
I don't have MRU in this modpack, but Sonance is in https://modrinth.com/modpack/inquisitive
and this same error occurs

**Comment by mosharky** [comment]
Sonance requires MRU though

**Comment by Liamgrayskull** [comment]
Oh, that's my bad then, it is in there, just slipped my mind

**Comment by Su5eD** [comment]
https://modrinth.com/mod/sonance leads to a 404 page

**Comment by Liamgrayskull** [comment]
Went through a rebrand, new link is https://modrinth.com/mod/sound
