### ISSUE TITLE
CameraOverhaul crashes on startup.

### ISSUE THREAD

**Issue by PlayfulPiano** [Sinytra/Connector#565]
### Mod Name

Camera Overhaul

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/cameraoverhaul

### Describe the bug

Crashes on startup.

### Steps to reproduce

1. Attempt to run Camera Overhaul
2. Crash

### Logs

https://gist.github.com/PlayfulPiano/88c5df8df545ecee616fa8bc9ee2e482

### Additional context

I do have an override file in use, which I believe should make the mod work on forge.
override below:
[fabric_loader_dependencies.json](https://github.com/Sinytra/Connector/files/13506172/fabric_loader_dependencies.json)

**Comment by Su5eD** [comment]
> Attempt to run Camera Overhaul

You listed camera overhaul as the only mod that needs to be run, but your log shows over 400 mods installed. Does this crash also occur with only Camera Overhaul installed?

**Comment by PlayfulPiano** [comment]
Can confirm it does crash on world creation with a minimized mod list:
[crash-2023-12-02_14.58.44-client.txt](https://github.com/Sinytra/Connector/files/13537245/crash-2023-12-02_14.58.44-client.txt)

**Comment by PlayfulPiano** [comment]
Can confirm it still crashes as of beta 29.

**Comment by PlayfulPiano** [comment]
Can confirm that v30 fixed this issue and the mod works fine with no issues!

**Comment by dwoopder** [comment]
> Can confirm that v30 fixed the crash and the mod works fine with no issues!

Hey I have this exact problem, what do you mean by v30? I've downloaded the mod for 1.21 and it doesnt seem to work, how'd you fix it?

**Comment by PlayfulPiano** [comment]
> > Can confirm that v30 fixed the crash and the mod works fine with no issues!
> 
> Hey I have this exact problem, what do you mean by v30? I've downloaded the mod for 1.21 and it doesnt seem to work, how'd you fix it?

note the date this issue was made. this was referring to v30 of the mod back when it was for 1.20.1
