### ISSUE TITLE
Crash on startup with Beta 28 (Beta 27 doesn't crash)

### ISSUE THREAD

**Issue by TechSupportRed** [Sinytra/Connector#574]
### Describe the bug

As soon as I launch the game, I immediately crash on Beta 28, but beta 27 works perfectly fine

### Steps to reproduce

1. Install Beta 28
2. Install mods in additional context
3. Crash on startup
...

### Logs

https://gist.github.com/TechSupportRed/8a0282d6a45da3ad37e8c7dc4e31cbf3

### Additional context

Modpack is running forge 47.1.3 with Adoptium Java and my launch arguements are:
`-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseVectorCmov -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:AllocatePrefetchStyle=3`

All mods that ar e installed:
	- achiopt 1.0.2
	- ad_astra 1.15.5
	- ad_astra_giselle_addon 5.8
	- ad_astra_proxima_plus 0.1.7
	- adaptive_performance_tweaks_core 10.2.0
	- adaptive_performance_tweaks_gamerules 10.0.0
	- adaptive_performance_tweaks_items 10.0.0
	- adaptive_performance_tweaks_player 10.0.0
	- adaptive_performance_tweaks_spawn 10.2.0
	- additional_lights 2.1.7
	- adorn 5.0.0+1.20.1
	- advanced_runtime_resource_pack 0.6.7
	- ae2 15.0.15
	- ae2wtlib 15.1.5-forge
	- aeroblender 1.20.1-1.0.1-neoforge
	- aether 1.20.1-1.0.0-beta.1.4-neoforge
	- aether_redux 1.20.1
	- aiimprovements 0.5.2
	- alexscaves 1.0.8
	- amecsapi 1.5.3+mc1.20-pre1
	- another_furniture 1.20.1-3.0.1
	- apexcore 10.0.0
	- appmek 1.4.2
	- aquaculture 2.5.1
	- aquamirae 6.API15
	- architectury 9.1.12
	- artifacts 9.2.0
	- athena 3.1.1
	- attributefix 21.0.4
	- balm 7.1.4
	- beautify 2.0.2
	- bedrockify 1.9.1mc1.20
	- bedrockwaters 1.7.71.20.1
	- bellsandwhistles 0.4.3-1.20.x
	- betterbeds 1.3.0
	- betterf3 1.0
	- betterfpsdist 1.20.1-4.1
	- bettermodsbutton 8.0.2
	- biggerreactors 0.6.0-beta.10.4
	- blue_endless_jankson 1.2.3
	- blue_skies 1.3.29
	- boatbreakfix 1.0.2
	- bobberdetector 0.1.9.1.20.1
	- botarium 2.2.1
	- canary 0.2.7
	- carrotconfig 1.0.31.20.1
	- cataclysm 1.0
	- catalogue 1.8.0
	- cfm 7.0.0-pre36
	- chipped 3.0.1
	- christmasfestivity 1.20.1-1.6.2-forge
	- citadel 2.4.9
	- citresewn 1.20.1-5
	- clienttweaks 11.1.0
	- cloth_config 11.1.106
	- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- commonality 7.0.0
	- connectivity 1.20.1-4.8
	- connectorextras 1.7.0+1.20.1
	- connectorextras_architectury_bridge 1.7.0+1.20.1
	- connectorextras_continuity_compat 1.7.0+1.20.1
	- connectorextras_emi_bridge 1.7.0+1.20.1
	- connectorextras_energy_bridge 1.7.0+1.20.1
	- connectorextras_geckolib_fabric_compat 1.7.0+1.20.1
	- connectorextras_modmenu_bridge 1.7.0+1.20.1
	- connectorextras_rei_bridge 1.7.0+1.20.1
	- connectorextras_terrablender_bridge 1.7.0+1.20.1
	- connectormod 1.0.0-beta.28+1.20.1
	- consolesounds 1.2.0
	- continuity 3.0.0-beta.41.20.1
	- controllable 0.20.3
	- controlling 12.0.1
	- cookingforblockheads 16.0.1
	- corpse 1.20.1-1.0.9
	- cosmeticarmorreworked 1.20.1-v1a
	- create 0.5.1.f
	- create_confectionery 1.1.0
	- create_crush_everything 1.0.2
	- create_dragon_lib 1.3.3
	- create_enchantment_industry 1.2.7.g
	- create_mechanical_extruder 1.20.1-1.5.7.e-22
	- create_new_age 1.0.1b
	- create_power_loader 1.2.2-mc1.20.1
	- create_things_and_misc 1.0.0
	- createaddition 1.20.1-1.2.0b
	- createarmory 0.5
	- createbb 3.1.1
	- createcasing 1.20.1-1.5.0-ht2
	- createchromaticreturn 1.0.0
	- createdieselgenerators 1.20.1-1.2e
	- creategbd 1.2.9.1b-1.20.1
	- createsifter 1.20.1-1.8.1.e-22
	- createsweetsandtreets 1.0.0
	- cuisinedelight 1.1.11
	- culllessleaves 1.20.1-1.0.5
	- cumulus_menus 1.20.1-1.0.0-beta.1-neoforge
	- cupboard 1.20.1-2.1
	- curios 5.4.5+1.20.1
	- davebuildingmod 5.0
	- decorative_blocks 4.0.2
	- deep_aether 1.20.1-1.0.12
	- deeperdarker 1.2.1
	- diagonalblocks 8.0.3
	- diagonalfences 8.1.2
	- diagonalwindows 8.1.3
	- distinguishedpotions 8.0.2
	- drinkbeer 1.0.4
	- easyanvils 8.0.1
	- easymagic 8.0.1
	- embeddium 0.2.10+mc1.20.1
	- embeddiumplus 1.0.1
	- emotecraft 2.2.7-b.build.50
	- endrem 5.2.3-R-1.20.1
	- enhancedblockentities 0.91.20
	- entity_model_features 1.1.0
	- entity_texture_features 4.6.1
	- entityculling 1.6.2
	- epherolib 0.1.2
	- exdeorum 1.9
	- expandability 9.0.0
	- fabric_api 0.90.7+1.10.3+1.20.1
	- fabric_api_base 0.4.30+ef105b4977
	- fabric_api_lookup_api_v1 1.6.35+67f9824077
	- fabric_biome_api_v1 13.0.12+dd0389a577
	- fabric_block_api_v1 1.0.10+0e6cb7f777
	- fabric_block_view_api_v2 1.0.0+0767707077
	- fabric_blockrenderlayer_v1 1.1.40+1d0da21e77
	- fabric_client_tags_api_v1 1.1.1+5d6761b877
	- fabric_command_api_v1 1.2.33+f71b366f77
	- fabric_command_api_v2 2.2.12+561530ec77
	- fabric_content_registries_v0 4.0.10+a670df1e77
	- fabric_convention_tags_v1 1.5.4+fa3d1c0177
	- fabric_data_generation_api_v1 12.3.2+369cb3a477
	- fabric_dimensions_v1 2.1.53+8005d10d77
	- fabric_entity_events_v1 1.5.22+b909fbe377
	- fabric_events_interaction_v0 0.6.1+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.39+461110ab77
	- fabric_item_api_v1 2.1.27+2272fc7f77
	- fabric_item_group_api_v1 4.0.11+9801bf5177
	- fabric_key_binding_api_v1 1.0.36+561530ec77
	- fabric_lifecycle_events_v1 2.2.21+afab492177
	- fabric_loot_api_v2 1.2.0+eb28f93e77
	- fabric_message_api_v1 5.1.8+52cc178c77
	- fabric_mining_level_api_v1 2.1.49+561530ec77
	- fabric_model_loading_api_v1 1.0.2+142e25ab77
	- fabric_models_v0 0.4.1+7c3892a477
	- fabric_networking_api_v1 1.3.10+503a202477
	- fabric_object_builder_api_v1 11.1.2+2174fc8477
	- fabric_particles_v1 1.1.1+78e1ecb877
	- fabric_recipe_api_v1 1.0.20+514a076577
	- fabric_registry_sync_v0 2.3.2+1c0ea72177
	- fabric_renderer_api_v1 3.2.0+1d29b44577
	- fabric_renderer_indigo 1.5.0+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.36+a6081afc77
	- fabric_rendering_fluids_v1 3.0.27+4ac5e37a77
	- fabric_rendering_v1 3.0.7+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.6+369cb3a477
	- fabric_resource_loader_v0 0.11.9+142e25ab77
	- fabric_screen_api_v1 2.0.7+45a670a577
	- fabric_screen_handler_api_v1 1.3.29+561530ec77
	- fabric_sound_api_v1 1.0.12+4f23bd8477
	- fabric_transfer_api_v1 3.3.2+51502a0077
	- fabric_transitive_access_wideners_v1 4.3.0+1880499877
	- fancymenu 2.14.9
	- fantasyfurniture 9.0.0
	- farmersdelight 1.20.1-1.2.3
	- faster_entity_animations 1.6
	- fastipping 1.0.0
	- fastitems 1.0.0
	- fastload 3.4.0
	- fastpaintings 1.20-1.2.3
	- fastrandom 1.4.2
	- ferritecore 6.0.1
	- festive_delight 1.0.0
	- feytweaks 1.20-1.2.7
	- fishofthieves 3.0.2
	- flib 0.0.11
	- fluxnetworks 7.2.0.14
	- flywheel 0.6.10-7
	- forge 47.1.3
	- forgeconfigapiport 8.0.0
	- forgeconfigscreens 8.0.2
	- framedblocks 9.1.6
	- framework 0.6.16
	- fusion 1.1.0b
	- garnished 1.3-hotfix-2+1.20.1
	- geckolib 4.2.4
	- goldenagecombat 8.0.0
	- gpumemleakfix 1.20.1-1.8
	- handcrafted 3.0.5
	- helditemtooltips 8.0.0
	- iammusicplayer 3.22.0-alpha.2
	- immediatelyfast 1.2.7+1.20.2
	- immersive_aircraft 0.6.2+1.20.1
	- immersive_armors 1.6.1+1.20.1
	- immersive_paintings 0.6.7+1.20.1
	- interiors 0.5.2
	- jade 11.6.3
	- jadeaddons 5.2.1
	- jankson 6.0.0j1.2.3
	- jei 15.2.0.27
	- kiwi 11.1.1
	- konkrete 1.6.1
	- koremods 1.0.0
	- kotlinforforge 4.7.0
	- krypton 0.2.3
	- l2library 2.4.14
	- lazurite 1.0.1+mc1.20.1
	- lazy_language_loader 0.3.3
	- libgui 8.1.01.20.1
	- libninepatch 1.2.0
	- loadmyresources 1.0.4
	- lost_aether_content 1.2.2
	- lucent 1.5.4
	- maidensmerrymaking 1.0.0
	- manyideas_christmas 1.0.0
	- manyideas_core 1.4.2
	- manyideas_doors 1.2.3
	- mcef 2.1.4-1.20.1
	- mcwbridges 2.1.1
	- mcwfences 1.0.7
	- mcwlights 1.0.6
	- mcwroofs 2.2.4b
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.0
	- mekanism 10.4.5
	- mekanismgenerators 10.4.5
	- memoryleakfix 1.1.2
	- mgbuttons 2.2.1build.1853ad23a8
	- mgbuttons_1_20_1 2.2.1build.1853ad23a8
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.9
	- mixinsquared 0.1.1
	- modelfix 1.14
	- modernfix 5.9.3+mc1.20.1
	- modmenu 7.2.2
	- molten_vents 2.0.5
	- moonlight 1.20-2.8.67
	- mousetweaks 2.25
	- mutil 6.1.1
	- myserveriscompatible 1.0
	- naturalist 4.0.3
	- nerb 0.3
	- nightconfigfixes 8.0.0
	- nitrogen_internals 1.20.1-0.1.3-neoforge
	- novacore 1.0.0
	- obscure_api 15
	- oldpotions 0.0NONE
	- otyacraftengine 3.7.0-alpha.2
	- packetfixer 1.2.1
	- panorama_screens 1.0+forge+mc1.20
	- paperdoll 1.1.1
	- patchouli 1.20.1-81-FORGE
	- phosphophyllite 0.7.0-alpha
	- pizzacraft 7.0.7
	- playeranimator 1.0.2-rc1+1.20
	- ppfluids 2.0.1
	- prettypipes 1.15.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.9
	- quartz 0.2.0-alpha
	- radiantgear 2.1.2+1.20.1
	- railways 1.5.3+forge-mc1.20.1
	- reach_entity_attributes 2.4.0
	- rechiseled 1.1.5c
	- rechiseledcreate 1.0.1
	- recipeessentials 1.20.1-3.2
	- recipes_lib 2.0.1
	- redirector 1.20.1-4.4.0
	- reeses_sodium_options 1.0.4
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.18
	- rrls 3.2.0-1.20.1-forge
	- rubidium 0.7.1
	- saturn 0.0.7
	- searchables 1.0.2
	- sereneseasonfix 1.20.1-1.0.8
	- sereneseasons 9.0.0.46
	- shulkerboxtooltip 4.0.4+1.20.1
	- sit 1.3.3
	- sliceanddice 3.2.0
	- smallships 2.0.0-a2.3.3
	- smoothboot 0.0.3
	- snowrealmagic 9.0.2
	- snowyspirit 1.20-2.2.6
	- solarpanels 1.5.8
	- sophisticatedbackpacks 3.19.1.962
	- sophisticatedcore 0.5.108.504
	- sophisticatedstorage 0.8.58.644
	- spelunkers_charm 1.0.0
	- spruceui 5.0.01.20
	- structure_gel 2.15.1
	- stylisheffects 8.0.0
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.15
	- supplementaries 1.20-2.7.4
	- sushigocrafting 0.4.3
	- swplanets 1.1.0
	- tact 1.0.5
	- terrablender 3.0.0.169
	- tetra 6.1.0
	- tetracelium 1.0.1
	- textrues_embeddium_options 0.1.3+mc1.20.1
	- tiltbreak 1.20.1-1.4FE
	- titanium 3.8.23
	- twilightforest 4.3.1893
	- undergarden 0.8.9
	- venus 0.0.1
	- visualworkbench 8.0.0
	- voidscape 1.20.1-1.5.310
	- webdisplays 2.0.1-1.20.1
	- wi_zoom 1.5-MC1.20.1-Forge
	- world_host 0.4.6
	- xaerominimapfair 23.8.2
	- yet_another_config_lib_v3 3.2.1+1.20

**Comment by TechSupportRed** [comment]
Logs:
https://gist.github.com/TechSupportRed/8a0282d6a45da3ad37e8c7dc4e31cbf3

Debug log:
https://gist.github.com/TechSupportRed/1581b40496bb46e23d6018bdce689d4f

**Comment by Su5eD** [comment]
Unfortuantely, neither of the two logs contain the crash stacktrace or expection. Please upload your crash report or launcher log.

**Comment by TechSupportRed** [comment]
Fixed in Beta 29, I believe it was related to #572 and #571 as I had both of those mods installed.
