### ISSUE TITLE
Crash with Embeddium

### ISSUE THREAD

**Issue by Loopdream123** [Sinytra/Connector#579]
### Mod Name

Embeddium

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/embeddium

### Describe the bug

Crash with Embeddium

### Steps to reproduce

1.Install connector and Embeddium
2.Launch the game

### Logs

https://pastebin.com/2xcrVSF9

**Comment by Su5eD** [comment]
Unfortunately I'm unable to reproduce this. Do you have any additional mods installed?

![image](https://github.com/Sinytra/Connector/assets/51261569/1a65cd9a-defa-4852-8e31-51b788da2868)

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
