### ISSUE TITLE
Kotlin for Forge is incompatible with OptiGUI

### ISSUE THREAD

**Issue by Loopdream123** [Sinytra/Connector#580]
### Mod Name

Kotlin for Forge and OptiGUI

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge   https://www.curseforge.com/minecraft/mc-mods/optigui

### Describe the bug

Kotlin for Forge is incompatible with OptiGUI

### Logs

Can't upload to pastebin due to potentially questionable content 

### Additional context

[crash-2023-12-04_01.11.40-client.txt](https://github.com/Sinytra/Connector/files/13539659/crash-2023-12-04_01.11.40-client.txt)

**Comment by Su5eD** [comment]
Kotlin for Forge is a FML language provider and does not work with Fabric mods. You need to use [Fabric Language Kotlin](https://modrinth.com/mod/fabric-language-kotlin) instead.
