### ISSUE TITLE
my game stops responding at loading bootstrap resources

### ISSUE THREAD

**Issue by jojofenin99** [Sinytra/Connector#581]
### Describe the bug

the game stops responding

### Steps to reproduce

i tried to add the rpg series mods and this happens now

### Logs

https://gist.github.com/jojofenin99/af105e67222a84c9b0d02a444cf8cd23

**Comment by jojofenin99** [comment]
![image_2023-12-03_160345536](https://github.com/Sinytra/Connector/assets/103892815/fd1a31b9-e91e-4e01-990d-a1cc13fffaa0)
here is a screenshot

**Comment by jojofenin99** [comment]
![image_2023-12-03_160436982](https://github.com/Sinytra/Connector/assets/103892815/1119aaa3-b4dc-42f5-aba9-2f0803765c4f)
these are the mods i tried to add, it worked fine before with just eldritch and and some other client side mods

**Comment by Su5eD** [comment]
> - mod 'Archers (RPG Series)' (archers) 1.0.6+1.20.1 requires any version of projectile_damage, which is missing!

You are missing the projectile damage mod, which is required by Archers

**Comment by jojofenin99** [comment]
should i get the forge or fabric version of it

**Comment by jojofenin99** [comment]
it still is still just loading when I tried the forge and fabric versions

**Comment by jojofenin99** [comment]
is there a way i can reopen the issue?

**Comment by jojofenin99** [comment]
[latest.log](https://github.com/Sinytra/Connector/files/13541895/latest.log)
here's the log i got after switching from beta.28 to beta.27

**Comment by Su5eD** [comment]
The log does not contain traces of the crash. Please upload your crash report or launcher log

**Comment by Su5eD** [comment]
Appears to be the same issue as #571, sorry for the inconveniece. A fix is coming in the next Connector release

**Comment by jojofenin99** [comment]
the bug is still present in newest version of connector
