### ISSUE TITLE
Exit on startup with Beta.28

### ISSUE THREAD

**Issue by dipilo** [Sinytra/Connector#583]
### Describe the bug

Exits with Exit Code 2 on Startup with Sinytra Connector version Beta.28 (haven't tried other versions)

### Steps to reproduce

1. Have my modpack
2. Add Sinytra Connector Beta.28
3. Launch
...

### Logs

https://mclo.gs/9MPS5Vi

**Comment by Su5eD** [comment]
Same issue as #571
