### ISSUE TITLE
Figura crashes with FFAPI and Connector

### ISSUE THREAD

**Issue by Nokunami** [Sinytra/Connector#584]
### Mod Name

Figura

### Mod Homepage

https://modrinth.com/mod/figura

### Describe the bug

Crashes when loading/ creating a new world

### Steps to reproduce

1. install Figura and Connector and FFAPI
2. load or create a world
3. crash
...

### Logs

https://mclo.gs/7pZgbN7

### Additional context

Figura loads on beta 27 but crashes when wearing any armor while having custom avatar selected: [log](https://mclo.gs/Fk8gdm2)
crashes when loading/ creating a new world on beta 28

**Comment by Su5eD** [comment]
Same issue as https://github.com/Sinytra/Connector/issues/571
