### ISSUE TITLE
Replay Mod not compatible with Connector anymore. Crashes with Connector betas 26 - 29

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#589]
### Mod Name

Replay Mod

### Mod Homepage

https://www.replaymod.com/download/

### Describe the bug

Crash on startup when Replay Mod is installed.

### Steps to reproduce

1. Install Connector, Extras, FFAPI and Replay Mod
2. Launch game
3. Crash

(using Forge 47.2.17)

### Logs

Log: https://mclo.gs/vtR4xPo Crash Report: https://mclo.gs/PwnZgBI

### Additional context

You probably already knew about this. All the previous crashes I reported, except for the one caused by Replay Mod, were fixed in beta.29 (yay! thanks). You were right to determine it as part of the problem. I made a fresh installation with just Connector, Extras, FFAPI and Replay Mod, so that the log is clean :D

**Comment by Liamgrayskull** [comment]
Can confirm same issue is happening on my end and through this post's as well: https://github.com/Sinytra/Connector/issues/556

**Comment by VladisCrafter** [comment]
Still not fixed, even in beta 31 :(

**Comment by RoomAlex68** [comment]
Replay Mod is incompatible with connector beta 34. The is issue has been a hot topic.

**Comment by coco875** [comment]
a lot of people when they come for connector they try replay mod but like said before he will fix issue in the order they want

**Comment by RoomAlex68** [comment]
Yeah

**Comment by kakashi1464** [comment]
![image](https://github.com/Sinytra/Connector/assets/126709049/6e53127d-b9fc-4954-9657-3d30f16e2557)
With the latest dev version I can open the inventory while viewing a record

**Comment by VladisCrafter** [comment]
@Matyrobbrt Well it kinda **is** the problem, because after opening the inventory, there's no way to close it without relaunching the game, afaIk. This isn't a thing in the original mod on Fabric, I guess. However, if you know other ways to get rid of this - please reply, I would also be grateful.

**Comment by VladisCrafter** [comment]
Also, that flying head (you can see it in the inventory) also appears if you manage to leave 1st person perspective.

**Comment by Matyrobbrt** [comment]
> @Matyrobbrt Well it kinda **is** the problem, because after opening the inventory, there's no way to close it without relaunching the game, afaIk. This isn't a thing in the original mod on Fabric, I guess. However, if you know other ways to get rid of this - please reply, I would also be grateful.

Does escape not work?

**Comment by VladisCrafter** [comment]
@Matyrobbrt of course it doesn't, otherwise I wouldn't care about it that much :)

**Comment by Wanderer70** [comment]
There is also an addon to Replay Mod that I find to be very useful. It's called [Replay Fps](https://modrinth.com/mod/replay-fps) and allows you to correctly record in first person. It would be nice for that addon to work on Connector as well.

**Comment by vinnyg0621** [comment]
for me just the replay viewer worlds do not open
