### ISSUE TITLE
2 mods on different platforms requiring geckolib

### ISSUE THREAD

**Issue by DaPuffer** [Sinytra/Connector#590]
### Describe the bug

There are 2 mods in my mod list that require Geckolib. Immersive portal gun and Create:teleporters. Immersive portalgun requires a fabric ver. of geckolib,and create:teleporters requires a froge version. The game won't launch if i use the forge version. And if i use the fabric version,when i go to the create:teleporters tab,the game crashes.

### Steps to reproduce

1.Install Create,Create:teleporters, immersive portals,immersive portalgun,synitra connector and geckolib.
2.Run the game
3. Join a world.
4. Open the Create:teleporters creative tab
5. Enjoy the crash

### Logs

[crash-2023-12-07_23.08.40-client.txt](https://github.com/Sinytra/Connector/files/13602994/crash-2023-12-07_23.08.40-client.txt)

**Comment by kakashi1464** [comment]
Use GeckoLib fabric with Connector  Extras?

**Comment by Su5eD** [comment]
Please refer to #231
