### ISSUE TITLE
Crash on Startup with Apotheosis

### ISSUE THREAD

**Issue by SlayDigger** [Sinytra/Connector#594]
### Mod Name

Apotheosis

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/apotheosis

### Describe the bug

Crashes on Startup with Apotheosis & Connector installed.

### Steps to reproduce

1. Install Apotheosis & Apothic Attributes alongside Connector 
2. Launch Game...
3. & Check Logs

### Logs

https://gist.github.com/SlayDigger/a6760179716c6ccf878f7a9aa060b564

### Additional context

I've also tried launching the game with Zenith (Separately of course) and was also met with a crash. No crash report was created in either instance

**Comment by Su5eD** [comment]
You've got a lot more mods installed other than Apotheosis, making the issue hard to diagnose. This is outlined in the issue template as well:

> Before reporting, please ensure that:
> - You are using the latest available version of Connector and its dependencies
> - You've installed a minimal set of mods required to reproduce the issue.
Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
If you're unsure which mods might be at fault, try using [binary search](https://www.reddit.com/r/feedthebeast/comments/evpy6r/tips_for_modpack_authors_how_to_find_misbehaving/) - removing half of installed mods
repeatedly until the faulty mod is found.

I tried installing Apotheosis without any other Forge mods, and it appears to work fine.
![image](https://github.com/Sinytra/Connector/assets/51261569/2ef7c495-37b2-4a51-9d98-3868934a6968)

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
