### ISSUE TITLE
Crash with justhammers

### ISSUE THREAD

**Issue by Craxell** [Sinytra/Connector#595]
### Mod Name

justhammers-fabric-2.0.1+mc1.20.1

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/justhammers

### Describe the bug

I use a forge client to load the connector and Forgified Fabric API + justhammers fabric, but only loading the mod does the client crash

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/zHTqcnxL

**Comment by Su5eD** [comment]
Try using the Forge version of justhammers. If it doesn't work, try installing Connector Extras.

**Comment by Su5eD** [comment]
Tested to work using the [Forge build](https://www.curseforge.com/minecraft/mc-mods/justhammers/files/4864303) of the mod.

![image](https://github.com/Sinytra/Connector/assets/51261569/6335b7d1-c71d-417d-9601-aac01c51be35)
