### ISSUE TITLE
Incompatible with AutoSlabs and Full Slabs

### ISSUE THREAD

**Issue by mimi-min** [Sinytra/Connector#598]
### Mod Name

AutoSlabs

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/autoslabs/

### Describe the bug

"Error loading mods" "Forge (forge) has failed to load correctly" screen

### Steps to reproduce

1. Install Connector, FFAPI, and AutoSlabs or Full Slabs/Cloth Config
2. Launch Minecraft 
3. Wait for it to load
4. Get error screen

![image](https://github.com/Sinytra/Connector/assets/29613956/f91c5e64-502a-4d9c-bf63-8a55be99bedf)

### Logs

https://pastebin.com/AfmUSTrN

### Additional context

Both AutoSlabs and Full Slabs give the same result. I'm trying to find a Forge alternative but haven't been successful so far.

**Comment by unilock** [comment]
IIRC [Templates 2](https://modrinth.com/mod/templates-2), a similar mod, works decently with Sinytra Connector.

You could also try [Additional Placements](https://www.curseforge.com/minecraft/mc-mods/additional-placements), which runs natively on Forge.

**Comment by mimi-min** [comment]
> IIRC [Templates 2](https://modrinth.com/mod/templates-2), a similar mod, works decently with Sinytra Connector.
> 
> You could also try [Additional Placements](https://www.curseforge.com/minecraft/mc-mods/additional-placements), which runs natively on Forge.

Unfortunately, Templates 2 isn't really what I'm looking for, and Additional Placements just straight up doesn't work (it has some incompatibility with some other mod that I haven't been able to find yet); it also can't and won't support double slabs, according to the author.
 
Thank you for the suggestions though, I'm sure someone else could make use of them! Additional Placements in particular looks nice, even if it's not exactly what I want; if only it would just work properly.
