### ISSUE TITLE
Bclib causing server crash on startup, while it works on singleplayer

### ISSUE THREAD

**Issue by Thspooks** [Sinytra/Connector#601]
### Describe the bug

Crash upon startup

### Steps to reproduce

1. Installed forge on server 
2. Started it
3. and then it died
...

### Logs

https://pastebin.com/nUAYiL78

### Additional context

Forge version 47.2.16
Without bclib and betternether (since BN requires bclib) it boots up just fine 
ill provide more info if i missed something

**Comment by Su5eD** [comment]
I tried running the latest versions of BCLib and BetterNether on a **Fabric server**, but it crashes with the same error.

https://mclo.gs/xmYGc7R

> Minecraft 1.20.1 with Fabric Loader 0.15.1
> fabric-api 0.91.0+1.20.1

**Comment by Thspooks** [comment]
Ah so its their fault, thats honestly kind of relief its not the connector fault. Ill try downgrading those. Thank you

**Comment by Thspooks** [comment]
but i still find it weird no one had this issue.... ive checked BN github and couldnt find anything related

**Comment by Thspooks** [comment]
Ive tried every version now for 1.20.1 now. None of them works.

**Comment by Thspooks** [comment]
I stubled upon a github issue and found this. 
https://github.com/xg787/BCLib-0.15-unoffical-hotfix 
This works perfectly. It seems they didnt fixed the issue for 4 versions of bc lib....
