### ISSUE TITLE
Error transforming jar (Pehkui)

### ISSUE THREAD

**Issue by Somber-Fox** [Sinytra/Connector#603]
### Mod Name

Pehkui (forge and fabric)

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/pehkui

### Describe the bug

When I open the game, shows an error "[Connector] Error transforming jar (directory)\Pehkui-3.7.8+1.14-1.20.1.jar"

### Steps to reproduce

1.Installed Bewitchment and its dependencies (trinkets, patchouli and pehkui) in a forge installations contaning Sinytra Connect
2. If I install the fabric version of Pehkui, it shows "[Connector] Error transforming jar (directory)\Pehkui-3.7.8+1.14-1.20.1.jar"
3. If I install the forge version, I have a exit code 1.

### Logs

https://discord.com/channels/1141048834177388746/1141048835146260513/1184473560559923200

**Comment by Su5eD** [comment]
Use the Forge version of Pehkui. Bewitchment is nonetheless incompatible as reported in #172
