### ISSUE TITLE
Crash when upgrading from connector 27 to connector 29

### ISSUE THREAD

**Issue by zrebarchak** [Sinytra/Connector#604]
### Describe the bug

minecraft crashes on startup using a previously working set of mods

### Steps to reproduce

1. n/a - large modpack
2.
3.
...

### Logs

https://api.paste.ee/p/bl6tY

### Additional context

mods:
![image](https://github.com/Sinytra/Connector/assets/71507946/9a7418b0-9567-4403-9338-3431238bdbaa)
datapacks: aquaculture fishing real compat, true ending

**Comment by Su5eD** [comment]
Plead read the issue template more carefully.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

Looking at the logs, `java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/block/FeastBlock` could mean you've installed Farmer's Delight for one loader and addons for another.

**Comment by zrebarchak** [comment]
farmers delight and all addons are forge except fabric-seasons-delight, which works on 27
