### ISSUE TITLE
Betternether/Betterend crashing on mod loading with other mods

### ISSUE THREAD

**Issue by frangnosquest** [Sinytra/Connector#608]
### Mod Name

Betternether/Betterend, Absolute ULTRACRAFT

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betternether ; https://www.curseforge.com/minecraft/mc-mods/betterend ; https://www.curseforge.com/minecraft/mc-mods/absolute-ultracraft

### Describe the bug

Game crashes on mod loading, if it's the first time loading the mods together the resource pack loading animation will play before declaring a resource pack loading failure and crashing, following attempts to load the game will result in just a mod loading error before crashing

### Steps to reproduce

1. Install Betternether, Betterend or both along with BClib
2. Install Absolute ULTRACRAFT along with either the forge or fabric version of azurelib (shared logs use the forge version)
3. Attempt to launch Minecraft

### Logs

https://pastebin.com/e3VMg8qg ; https://pastebin.com/NBU74ULg

### Additional context

Left the title as generic as possible because i'm not sure if this potentially applies to other mods, the game managed to launch successfully once, but i was not able to replicate it so far. sharing two logs just in case since as i said before the game crashes in a slightly different way if you remove and reinstall one of the conflicting mods.

**Comment by FullMetalMaster** [comment]
having this issue on severs past beta 27
