### ISSUE TITLE
Pekhui 1.20.1

### ISSUE THREAD

**Issue by Haonn** [Sinytra/Connector#614]
### Mod Name

Pehkui-3.7.7+1.20.1

### Mod Homepage

https://modrinth.com/mod/pehkui/versions

### Describe the bug

I tried a lot of different versions of Pekhui both for forge and Fabric but for some versions it crashes with an exit code of 1 or it isn't detected to play along bewitchment.

### Steps to reproduce

1.Install Forge
2.Add connector, connector extra, forgified fabric
3. Add bewitchment and other dependencies 
4. Try to add Pehkui for forge or fabric and see the results

### Logs

https://gist.github.com/Haonn/1291330df9b0f850a613ff8ecc028de1

**Comment by Su5eD** [comment]
Is there any specific reason you're using the fabric version of Pehkui over the forge one? Have you tried it prior to using the fabric version?

**Comment by Haonn** [comment]
I've tried both the forge version and the fabric one of Pehkui and got different issues, I even tried the source code of Pehkui and with the source code the game launches but Pehkui isn't detected by bewitchment.

**Comment by Su5eD** [comment]
Just tested the Forge [version](https://modrinth.com/mod/pehkui/version/3.7.12+1.20.1-forge) of pehkui to run smoothly alongside Connector beta 31. The issue lies in bewitchment, which has been reported as incompatible in #172.
