### ISSUE TITLE
Unable to disable fog in Better End & Better Nether. (and possibly other modded dimentions)

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#616]
### Describe the bug

It's not possible to disable fog in Better End and Better Nether. I am using Embeddium along with Rubidium Extra (NOT Extras)

### Steps to reproduce

1. Install Connector, Extras, FFAPI
2. Install Embeddium & Rubidium Extra
3. Launch game and try to disable fog. (Changing fog modify type from default to mod compat will do nothing)

### Additional context

Here are the reports I made: 
Embeddium: https://github.com/embeddedt/embeddium/issues/102
Rubidium Extra: https://github.com/dima-dencep/rubidium-extra/issues/63
I consider this to be quite a significant issue, because being unable to disable fog makes a lot of mods incompatible. Playing with Distant Horizons for example is basically impossible, as real chunks are fully covered in fog or straight up disappear because of chunk fog culling.

**Comment by FullMetalMaster** [comment]
not having this issue but the latest versions past beta 27 dont load better nether and and it's libraries at all in servers

**Comment by Wanderer70** [comment]
What? Better Nether and Better End work perfectly fine for me with beta 29.

**Comment by FullMetalMaster** [comment]
crashes every time i try to load it in a server same with version beta 31

**Comment by Wanderer70** [comment]
Try singleplayer

**Comment by Su5eD** [comment]
Are you sure this is caused by Connector and not Rubidium Extra? The linked issue hints that the fog setting doesn't go well with other mods

**Comment by Su5eD** [comment]
I was able to get the fog setting working after changing the client config of bclib. To do this, open `<minecraft>/config/bclib/client.json`, then set `customFogRendering` and `netherThickFog` to `false` like so:

> ```json
>"rendering": {
>    "customFogRendering [default: true]": false,
>    "netherThickFog [default: true]": false,
>    "FogDensity [default: 1.0]": 1.0
>  }
>```

**Comment by Wanderer70** [comment]
Thank you! You're a life saver! I honestly had no clue what was the problem, as I have checked the config files for Better End and Better Nether multiple times, but missed Bclib somehow... bruh. Anyway, thanks!

There is another potential fog issue with Nostalgic Tweaks and Connector by the way. I don't yet know whether it is caused by Connector itself or any mods that run using Connector, but changing fog type to that of pre 1.6.4 will break the rendering of said fog, making it flicker. Might post a report about this soon.
