### ISSUE TITLE
Open a chest with Enhanced Block Entities crashes Minecraft

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#62]
### Mod Name

Enhanced Block Entities

### Mod Homepage

https://github.com/FoundationGames/EnhancedBlockEntities

### Describe the bug

Open a chest with Enhanced Block Entities crashes the game

### Steps to reproduce

Open a chest with Enhanced Block Entities crashes Minecraft

### Logs

https://mclo.gs/INtwVli

**Comment by Su5eD** [comment]
Fixed in FFAPI `0.87.0+1.9.2+1.20.1`
