### ISSUE TITLE
Beta 30 breaks owo lib

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#620]
### Mod Name

owo lib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/owo-lib/files?page=1&pageSize=20

### Describe the bug

RecipeManagerMixin Error transforming jar

### Steps to reproduce

Install mod. Launch minecraft.

### Logs

Log https://gist.github.com/Tomat777/74aba4ac71ccad4887e1a98459662c1e

### Additional context

Debug https://gist.github.com/Tomat777/34085cf783cf47ffd6a123dbc7879818
![image](https://github.com/Sinytra/Connector/assets/146892171/e8b9e0b7-4263-4946-8d34-17c95ff70762)
![image](https://github.com/Sinytra/Connector/assets/146892171/4387a758-8bc1-4d4f-84aa-7d9583372238)
Beta 29 works fine

**Comment by Su5eD** [comment]
Same error as #619
