### ISSUE TITLE
Beta 30 breaks betterx mods

### ISSUE THREAD

**Issue by m3t4f1v3** [Sinytra/Connector#623]
### Describe the bug

BetterX mods (as forked by https://github.com/xg787 to run on fabric 0.15) do not work on the latest connector version on the server side

### Steps to reproduce

1. Install connector beta 30
2. Install BCLIB, BetterEnd and/or BetterNether mods
3. Run server

### Logs

https://gist.githubusercontent.com/m3t4f1v3/9a6ef395ce2ebb856cd3ffc5dac81909/raw/a1e82a2c4a052829a632e733e1146cf9ef7cba43/txt

### Additional context

downgrading to beta 29 fixes the issue

**Comment by Su5eD** [comment]
I tried installing the mods you listed, but everything works fine for me

**Comment by Wanderer70** [comment]
He run a server world. Maybe that has to do something with it.

**Comment by Su5eD** [comment]
Yes, I tested this on a server as well
