### ISSUE TITLE
beta 31 crashed server

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#626]
### Describe the bug

beta 31 crashed server

### Steps to reproduce

having this problem on server start up, when i use beta31 version of this mod, i seems cannot boots up my server, it doesn't happens when i use beta27 it don't happens, can you please check on that?

### Logs

https://pastebin.com/meYCTyZ2

**Comment by Su5eD** [comment]
> Caused by: java.lang.NoSuchFieldError: CLENT_CONFIG

Duplicate of #601
