### ISSUE TITLE
with version beta 31 it crashed 

### ISSUE THREAD

**Issue by jojofenin99** [Sinytra/Connector#628]
### Describe the bug

my game crashes on load

### Steps to reproduce

get the latest version of sinytra connector with connector extras  and load the fabric mods yet another config, you were slain, and eldritch end, and then it crashes

### Logs

https://gist.github.com/jojofenin99/08391ffba19bf713f3b0896820cbb71a

**Comment by jojofenin99** [comment]
sorry i forgot the normal log here it is: [https://gist.github.com/jojofenin99/d1c5881da60d858f2addda56a84ad4ed](https://gist.github.com/jojofenin99/d1c5881da60d858f2addda56a84ad4ed)

**Comment by SuperStefan97** [comment]
Hi! Sorry to jump in, version 31 works for me with Useless Reptile, tho, I'm using the forge version of gecko and yet another config lib in case it throws a light

**Comment by Su5eD** [comment]
This is and issue with cataclysmtweaks, which you haven't listed in your description.

Plead read the issue template more carefully.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
