### ISSUE TITLE
EMI Loot crashes when creating a new world

### ISSUE THREAD

**Issue by Nokunami** [Sinytra/Connector#632]
### Describe the bug

Crashed on Preparing for World Creation

### Steps to reproduce

1. FFAPI, Connecter, Connector Extras and EMI + EMI Loot
2. Create new world
3. crash
...

### Logs

https://mclo.gs/BvhxHwH

### Additional context

ran perfectly fine on beta 27, 28, and 29 but beta 30 and 31 broke.

**Comment by latuh** [comment]
Can reproduce on 1.20.1, Forge 47.1.3
