### ISSUE TITLE
Bosses of Mass Destruction incompatibility 

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#64]
Launch the game with Sinytra Connector and Forgified Fabric API installed and crashes after that

**Comment by RoomAlex68** [comment]
It's a beta I get it and not all fabric mods are compatible yet

**Comment by RoomAlex68** [comment]
Mod Link here: 
https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction

**Comment by Su5eD** [comment]
The mod itself run fine when I only use select cardinal components modules. Looks like there is an issue with one of CC-block's mixins. But it should be easily fixable.

**Comment by RoomAlex68** [comment]
Which cardinal components modules do you use?

**Comment by RoomAlex68** [comment]
Or how do you fix it?

**Comment by coco875** [comment]
I think it compile it and editing the code of cardinal components to make a some of fix to try.

**Comment by botttttttttttttt** [comment]
IT WORKED
