### ISSUE TITLE
Incompat with DucLib/Recrafted Creatures

### ISSUE THREAD

**Issue by SuperStefan97** [Sinytra/Connector#641]
### Mod Name

Duc Lib or Recrafted Creatures

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/recrafted-creatures

### Describe the bug

Crash on start up

### Steps to reproduce

1. Add recrafted creatures and duc lib (1.3.2 and 1.1.2 for 1.20.1)
2. Add Connector beta 31, ffapi 0.90.7 and connector extras 1.8.0
3. Crash
...

### Logs

https://pastebin.com/NgJUSRkq

### Additional context

The modders from Recrafted Creatures and DucLib are also checking out if needed.

**Comment by SuperStefan97** [comment]
Hi! Not sure if you got time to check this? (Commenting so it's not forgotten)

**Comment by Su5eD** [comment]
Fixed in FFAPI 0.92.0+1.11.2+1.20.1

**Comment by SuperStefan97** [comment]
Thanks for checking and solving this!
