### ISSUE TITLE
ItemSwapper compatibility

### ISSUE THREAD

**Issue by Su5eD** [Sinytra/Connector#642]
### Mod Name

ItemSwapper

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/itemswapper

### Describe the bug

Dynamic LVT patch broke

### Logs

https://mclo.gs/BPC4eHO

### Additional context

Tested by @VladisCrafter. I'm opening an issue so that I don't forget to fix this, seems like an easy bug

**Comment by VladisCrafter** [comment]
Thanks for fixing it! I'm really glad I could help :D
