### ISSUE TITLE
Mythic Metals looking for a mixin that doesnt exists [Server]

### ISSUE THREAD

**Issue by Thspooks** [Sinytra/Connector#645]
### Describe the bug

Crashes server on startup, mythic metals is looking for a mixin that doesnt exists in forge

### Steps to reproduce

1. Install Magma Mantained 1.20.1, Mythic Metals, Alloy forgery,Connector+Extras, Rei
2. Start up the server
3. it crashes
...

### Logs

https://pastebin.com/uE5A99zJ

### Additional context

Im linking github for it in case if its incompability but idk
https://github.com/magmamaintained/Magma-1.20.1
If i missed something please do let me know

**Comment by Tomat777** [comment]
Custom server api is not supported so u need to test issue non server and if its occurs report to magma dev

**Comment by Thspooks** [comment]
I already did, and they told us to report it to you

**Comment by Tomat777** [comment]
then nothing u can do about it

**Comment by Tomat777** [comment]
but u really need to try single player and if it occurs then connector dev will fix it eventually

**Comment by Thspooks** [comment]
Single player it works, but not serverside

**Comment by Tomat777** [comment]
then its magma fault

**Comment by Thspooks** [comment]
But it wouldnt be the first time mod doesnt works only server side. Same issue had bclib recently

**Comment by Thspooks** [comment]
singleplayer bc lib was fine, but on server it was crashing no matter what server jar u use

**Comment by Tomat777** [comment]
and connector didnt do anything with that it was fixed by some github repository that fixed bclib issue

**Comment by Thspooks** [comment]
Yep, but im giving only example

**Comment by Tomat777** [comment]
Well u can try testing on forge server and if it occurs then report it othervise its 100% magma issue and should be managed on their side

**Comment by TonimatasDEV** [comment]
@Tomat777 @Su5eD Same problem on pure Forge server

**Comment by TonimatasDEV** [comment]
**Logs:** https://pastebin.com/UMfYHrcz
