### ISSUE TITLE
Mythic Metals looking for a mixin that doesnt exists [Pure server forge]

### ISSUE THREAD

**Issue by Thspooks** [Sinytra/Connector#646]
### Describe the bug

Crash on startup due to mixins 

### Steps to reproduce

1.Install Server jar, Mythic Metals, Alloy forgery,Connector+Extras, Rei
2.Start it up
3. it crashes
...

### Logs

https://pastebin.com/UMfYHrcz

### Additional context

It do crashes on pure forge too. Included Logs from pure forge.

**Comment by Thspooks** [comment]
https://pastebin.com/CWaVAqWD  Log with pure forge with rei

**Comment by Su5eD** [comment]
> [17:59:40] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
        Mod ID: 'cloth_config', Requested by: 'roughlyenoughitems', Expected range: '[10.0,)', Actual version: '[MISSING]'
        Mod ID: 'architectury', Requested by: 'roughlyenoughitems', Expected range: '[8,)', Actual version: '[MISSING]'

For the other issue, install Connector Extras
