### ISSUE TITLE
Audioplayer Mod Compatibility

### ISSUE THREAD

**Issue by ItoKyoshiro** [Sinytra/Connector#647]
### Describe the bug

When you Push a Custom Disc (Autoplay Mod) into a Jukebox from a Hopper/Dropper, it doesn't sound (from what I could see, it works for the redstone, timings and everything customizable with the disc, except the sound xD). It works if a Player insert the Custom Disc though (right click on Jukebox), It doesn't affect Vanilla Discs

### Steps to reproduce

1.Push a Custom Disc (Autoplay Mod) into a Jukebox (Hopper/Dropper)
2.Get sad ;(

### Additional context

**MODS:**
audioplayer-1.20.1-1.8.5
Connector-1.0.0-beta.32+1.20.1
fabric-api-0.90.7+1.10.3+1.20.1
voicechat-fabric-1.20.1-2.4.32

**Comment by ItoKyoshiro** [comment]
As an update, the timings for the Discs are based on the Vanilla version and not the updated times by the Audioplayer Mod.
I tested it using a Custom Disc (00:30) using Mellohi (01:36) as it's base, and when pushed onto the Jukebox it went silent for 01:36 (powering the Hopper below with Redstone and signal of 7) and then extracted the Disc and played it (with the Custom Music for 00:30). For the remaining 01:06 it went silent and kept providing redstone (like a second Mellohi)

**Comment by Su5eD** [comment]
Please provide a link to the mod as explained in the Mod Incompatibility issue template

**Comment by ItoKyoshiro** [comment]
oh, my bad (didn't realize used the template for Bug instead of Mod Incompatibility :s!)

**Mod Homepage:**
https://modrinth.com/mod/audioplayer

**Comment by Liamgrayskull** [comment]
I've found that this issue occurs for me (audioplayer being run serverside exclusively) in none of the custom music registering

**Comment by ItoKyoshiro** [comment]
with the last version of Forgified Fabric API (fabric-api-0.91.0+1.10.4+1.20.1.jar) this seems to have resolved (not sure exactly what was changed, but this issue was resolved since now the Custom Disc works as intended)

**MODS:**
audioplayer-1.20.1-1.8.5
Connector-1.0.0-beta.32+1.20.1
fabric-api-0.90.7+1.10.3+1.20.1
voicechat-fabric-1.20.1-2.4.32

**Comment by Su5eD** [comment]
Ah, good to hear. Seems to have been fixed by https://github.com/Sinytra/ForgifiedFabricAPI/pull/88
