### ISSUE TITLE
SkinShuffle mod Incompatibility

### ISSUE THREAD

**Issue by blammie** [Sinytra/Connector#649]
### Mod Name

SkinShuffle

### Mod Homepage

https://modrinth.com/mod/skinshuffle/versions

### Describe the bug

Immediate crash after loading into the main menu

### Steps to reproduce

1. Install SkinShuffle
2. Launch Game
3. Load in
4. Main menu crash
...

### Logs

https://gist.github.com/blammie/bc09b1b5ff78596fd521744b227c4507

### Additional context

(I want this mod to get fixed, because of how it offers more features)

**Comment by Su5eD** [comment]
Fixed in Connector Extras [1.9.2+1.20.1](https://modrinth.com/mod/connector-extras/version/1.9.2+1.20.1).
