### ISSUE TITLE
 I decided to try it with two test mods better-mcdonalds and Worthy-Food

### ISSUE THREAD

**Issue by SALATIKsMORKOVKOY** [Sinytra/Connector#651]
### Describe the bug

Picked up _JAVA_OPTIONS:  2023-12-26 18:47:55,412 main WARN Advanced terminal features are not available in this environment [18:47:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, SALATIKsMORKOVKO, --version, 1.20.1-forge-47.1.3, --gameDir, D:\Minecraft\game, --assetsDir, D:\Minecraft\game\assets, --assetIndex, 5, --uuid, 6fa52a55d6f233d3882429ebf27ab356, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, legacy, --versionType, release, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 47.1.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412] [18:47:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Windows 10 arch amd64 version 10.0 Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: invalid header field (line 6) 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:122) 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70) 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66) 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58) 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50) 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:76) 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:65) 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:48) 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:38) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125) 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:87) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) Caused by: java.io.IOException: invalid header field (line 6) 	at java.base/java.util.jar.Attributes.read(Attributes.java:406) 	at java.base/java.util.jar.Manifest.read(Manifest.java:290) 	at java.base/java.util.jar.Manifest.read(Manifest.java:281) 	at java.base/java.util.jar.JarInputStream.checkManifest(JarInputStream.java:94) 	at java.base/java.util.jar.JarInputStream.<init>(JarInputStream.java:85) 	at java.base/java.util.jar.JarInputStream.<init>(JarInputStream.java:61) 	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:98) 	... 34 more

### Steps to reproduce

1.
2.
3.
...

**Comment by SALATIKsMORKOVKOY** [comment]
why it s closed?

**Comment by kakashi1464** [comment]
Please follow the mod incompatibility template
