### ISSUE TITLE
Modern Industrialization Registry Crash

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#654]
### Mod Name

Modern Industrialization

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

### Describe the bug

crash upon loading menu

### Steps to reproduce

1. Download MI + connector + connector extras + a bunch of other mods
2. get crashed scrub
3.ez gg
...

### Logs

https://gist.github.com/Xplodin/5eefcc90a75c86e8e074797ba5723c9c

### Additional context

Problem goes away if I remove MI
Seems it could be related to the recent kubejs support they introduced

**Comment by Su5eD** [comment]
> a bunch of other mods

Plead read the issue template more carefully.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by unilock** [comment]
Future readers: if you're lucky enough to have come across this issue by finding OP's crash log through Google, then it turns out this issue is a dupe of #404 (at least for me).
