### ISSUE TITLE
Unseen World mod incompatibility

### ISSUE THREAD

**Issue by SashaKYotoz** [Sinytra/Connector#655]
### Mod Name

Unseen World

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/unseen_world

### Describe the bug

If Fabric mods are added to folder with Unseen World, it crashes with title "No model for layer unseen_world:model_beacon_of_weapons", but that isn't issue in Unseen World

### Steps to reproduce

1.Download Unseen World + Sinytra + Fabric mods
2.Try to run Minecraft

### Logs

https://gist.github.com/SashaKYotoz/1a8cde5e0f8e73924c370baad311fa29

### Additional context

From my side as developer of Unseen World i would say - IllegalArgumentException catches in try() catch{}, but if Fabric mods with Sinytra are downloaded it forces error anyway

**Comment by Su5eD** [comment]
Please specifiy "Fabric mods"

**Comment by SashaKYotoz** [comment]
ReplayMod and Nox: Renoxed <-mods that i've tested with
