### ISSUE TITLE
QuickMäth has no effect on Minecraft's client side

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#657]
### Describe the bug

[QuickMäth](https://modrinth.com/mod/quickmath) has no effect on Minecraft's client side

### Steps to reproduce

1. Run QuickMäth in a Fabric environment, see what behavior is broken on the client side
2. Do the same with Forge

### Additional context

link: https://modrinth.com/mod/quickmath

**Comment by Su5eD** [comment]
Please provide a link to the mod as explained in the Mod Incompatibility template

**Comment by Su5eD** [comment]
> see what behavior is broken on the client side

Please provide exact reproduction steps

**Comment by Lolothepro** [comment]
> > see what behavior is broken on the client side
> 
> Please provide exact reproduction steps

I don't know what reproduction method I can give you.?

**Comment by Matyrobbrt** [comment]
The mod's purpose is to quite literally *break* Minecraft. We are not going to invest time fixing mods that are intended to break the game right now.
