### ISSUE TITLE
Continuity's Emmisive textures not working

### ISSUE THREAD

**Issue by Blaize63** [Sinytra/Connector#658]
### Describe the bug

Continuity's connected textures work after installing Embedium and Lazurite, however, the emmisive textures do not work

### Steps to reproduce

1. Install Embeddium and Lazurite
2. Install Sinytra connector and Forgified Fabric
3. Install Continuity
4. Install any Resource pack that adds Emmisive Textures and apply it
5. Realize that the Emmisive textures aren't Emmisive and therefor, aren't working
...

### Additional context

How it's supposed to look(Optifine):
![pack1](https://github.com/Sinytra/Connector/assets/79714522/3bd8653c-428e-41f0-9840-d4b88375da25)

How it looks(Continuity):
![image](https://github.com/Sinytra/Connector/assets/79714522/85342fc8-acfb-4e3e-ba64-6103c03a8fbe)

**Comment by kakashi1464** [comment]
Use  https://modrinth.com/mod/moremcmeta-emissive ?

**Comment by Blaize63** [comment]
> Use https://modrinth.com/mod/moremcmeta-emissive ?
![Screenshot_20231228-195958_Chrome](https://github.com/Sinytra/Connector/assets/79714522/36d0bef6-d129-49ce-95eb-97a8552a204d)
It doesn't say here that items are supported. Only blocks, block and entities, entities and liquids 

![Screenshot_20231228-200210_Chrome](https://github.com/Sinytra/Connector/assets/79714522/94befc0d-8cc5-4d51-a056-cd8c8189c70c)
Continuity in the other hand does provide emmisive textures for item models, but they're not working

Not only that, I can't even test if it does add emmisive item model support and just didn't say it on it's page cause my Minecraft crashed when I added the mod to it
![image](https://github.com/Sinytra/Connector/assets/79714522/eef17e1c-2d70-492b-aca0-4bc0aca50643)
Crash report:
[crash-2023-12-28_20.12.29-client.txt](https://github.com/Sinytra/Connector/files/13788612/crash-2023-12-28_20.12.29-client.txt)

**Comment by Tomat777** [comment]
its compatible use forge version of moremcmeta emissive

**Comment by Blaize63** [comment]
Nvm it works and it's not crashing anymore
![image](https://github.com/Sinytra/Connector/assets/79714522/9f197f22-f644-46d8-8256-1d62eb89825e)
Thanks

**Comment by Blaize63** [comment]
Nvm it works and it's not crashing anymore
![image](https://github.com/Sinytra/Connector/assets/79714522/5d2e1fdf-47c2-47b2-817c-9dbb413672f6)
THANKS
