### ISSUE TITLE
Nox renoxed still doenst work

### ISSUE THREAD

**Issue by Kevenpvp** [Sinytra/Connector#659]
### Mod Name

Nox: Renoxed

### Mod Homepage

https://modrinth.com/mod/nox-renoxed

### Describe the bug

Stil crash on start up

### Steps to reproduce

1. Download nox renoxed and it api https://modrinth.com/mod/midnightlib
2. Play
3. See the crash
...

### Logs

https://gist.github.com/Kevenpvp/dd0f14e698c6e4928f17269c955c8620

### Additional context

Crash

**Comment by Su5eD** [comment]
> nox-2.7.0+1.20.2

1.20.2 mods can't be played on Minecraft 1.20.1
