### ISSUE TITLE
MC Dungeons mods issue

### ISSUE THREAD

**Issue by glea94** [Sinytra/Connector#662]
### Mod Name

MC Dungeons

### Mod Homepage

https://www.curseforge.com/members/chronos_sacaria/projects

### Describe the bug

net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcdw'!

### Steps to reproduce

1.Install MC Dungeons Weapons
2.Launch the game
3.crash to error log
...

### Logs

https://pastebin.com/ND9aT7iJ

### Additional context

if i delete mcdw mod, it will do with the next MC dungeons mod (artefects, enchants, etc)

**Comment by Su5eD** [comment]
MCDW's Clumps integration breaks when Clumps for Forge is installed. To mitigate this, you use the [hidden mods](https://github.com/Sinytra/Connector?tab=readme-ov-file#hiding-forge-mods-presence) config to disable the crashing compat code.

**Comment by xllifi** [comment]
> MCDW's Clumps integration breaks when Clumps for Forge is installed. To mitigate this, you use the [hidden mods](https://github.com/Sinytra/Connector?tab=readme-ov-file#hiding-forge-mods-presence) config to disable the crashing compat code.

Outdated link. New: https://sinytra.org/docs/connector/configuration#hiding-forge-mods-presence
