### ISSUE TITLE
Crash with ULTRACRAFT

### ISSUE THREAD

**Issue by Kevenpvp** [Sinytra/Connector#664]
### Mod Name

ULTRACRAFT

### Mod Homepage

https://modrinth.com/mod/absolute-ultracraft/version/1.20.1-2.0.4

### Describe the bug

It crash on start

### Steps to reproduce

1. Dowload ultracraft
2. Play
3. See crash
...
 

### Logs

https://gist.github.com/Kevenpvp/5ca4177e2b40a4b7c75b1106593c0285

### Additional context

Crash

**Comment by Su5eD** [comment]
Confirmed to work on beta 32 and Forge 47.2.19

![2024-01-13_10 58 18](https://github.com/Sinytra/Connector/assets/51261569/0c80d55c-364c-4869-aeb0-da77b773488c)
