### ISSUE TITLE
Embeddium + Immersive Portals = Block rendering issues

### ISSUE THREAD

**Issue by Charismara** [Sinytra/Connector#665]
### Mod Name

Embeddium

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/embeddium

### Describe the bug

Blocks won't get rendered when Embeddium and Immersive Portals are installed with Sinytra Connector

### Steps to reproduce

1. Install Embeddium 0.2.16 (1.20.1)
2. Install Immersive Portals 3.3.3 (1.20.1)
3. Create a world
<img width="434" alt="image" src="https://github.com/Sinytra/Connector/assets/14293974/ae07766b-be03-43fe-baa1-4d8a7a3b816b">

### Logs

none

**Comment by glea94** [comment]
I tried immersive portal but my error log is about CIT resewn. The mod seems to be problematic.

**Comment by Xplodin** [comment]
Definitely embeddium + immersive portals. I had the same issue

**Comment by Su5eD** [comment]
Immersive portals comes with sodium compat, but in order for it to activate, the `sodium` modid must be present. You can achieve this in 2 steps.

First, create an alias using connector's global alias config file.  
`connector_global_mod_aliases.json`
```json
{
  "version": 1,
  "aliases": {
    "embeddium": "sodium"
  }
}
```

Next, remove the `breaks` dependency constraint from immersive portals, as embeddium and sodium don't follow the same versioning.
`fabric_loader_dependencies.json`
```json
{
  "version": 1,
  "overrides": {
    "immersive_portals": {
      "-breaks": {
        "sodium": "BYE"
      }
    }
  }
}
```

Last step, enjoy the game :)

![2024-01-13_12 58 36](https://github.com/Sinytra/Connector/assets/51261569/0390f910-dfed-4cf4-9a1a-b8d324f99936)

**Comment by hiimrickross** [comment]
> Immersive portals comes with sodium compat, but in order for it to activate, the `sodium` modid must be present. You can achieve this in 2 steps.

> Next, remove the `breaks` dependency constraint from immersive portals, as embeddium and sodium don't follow the same versioning. `fabric_loader_dependencies.json`
> 
> ```json
> {
>   "version": 1,
>   "overrides": {
>     "immersive_portals": {
>       "-breaks": {
>         "sodium": "BYE"
>       }
>     }
>   }
> }
> ```
> 
> Last step, enjoy the game :)

Where do i do this second step? I don't see the fabric_loader_dependencies.json anywhere. i tried opening immersive portals jar and don't see it there either. is it a config file generated after attempting to run immersive portals once?

**Comment by Xplodin** [comment]
> > Immersive portals comes with sodium compat, but in order for it to activate, the `sodium` modid must be present. You can achieve this in 2 steps.
> 
> > Next, remove the `breaks` dependency constraint from immersive portals, as embeddium and sodium don't follow the same versioning. `fabric_loader_dependencies.json`
> > ```json
> > {
> >   "version": 1,
> >   "overrides": {
> >     "immersive_portals": {
> >       "-breaks": {
> >         "sodium": "BYE"
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Last step, enjoy the game :)
> 
> Where do i do this second step? I don't see the fabric_loader_dependencies.json anywhere. i tried opening immersive portals jar and don't see it there either. is it a config file generated after attempting to run immersive portals once?

you have to make the file

**Comment by jpeaglesandkatz** [comment]
Might actually help mentioning where these json's should be placed.. In the .connector folder.. Under config?

**Comment by Arkner421** [comment]
> `fabric_loader_dependencies.json`

where is that file should be?

**Comment by phaon1** [comment]
> > `fabric_loader_dependencies.json`
> 
> where is that file should be?

inside the config folder

**Comment by Skel200** [comment]
Can this be used to make oculus compatible?

**Comment by tonypraf** [comment]
Hello, I've done everything as described here as far as I'm aware and I have no mods other than iPortal, embeddium and the connector installed, it still doesn't work for me when I launch a world, is there a possible reason as to why?

**Comment by kakashi1464** [comment]
> Hello, I've done everything as described here as far as I'm aware and I have no mods other than iPortal, embeddium and the connector installed, it still doesn't work for me when I launch a world, is there a possible reason as to why?

Embeddium version?

**Comment by tonypraf** [comment]
> > Hello, I've done everything as described here as far as I'm aware and I have no mods other than iPortal, embeddium and the connector installed, it still doesn't work for me when I launch a world, is there a possible reason as to why?
> 
> Embeddium version?

0.3.0

**Comment by Trojankill** [comment]
Su5eD I did the same thing, downloaded the same versions of the embeddium mod and immersive portal, but it doesn't work

**Comment by Tapacywka** [comment]
IP isn't compatible with Embeddium 0.3.x & Oculus >1.6.9.

**Comment by iTrooz** [comment]
Thank you Su5eD, I confirm your fix works !
One thing to note: my connector config file was `connector.json` not `connector_global_mod_aliases.json`

I was able to make it work with Embeddium 0.2.10 as well as Embeddium 0.3.24

Is there a chance Sinytra connector can make theses changes the default ? I imagine adding a new entry to the global mod aliases wouldn't be hard, but idk about removing the IP dependency on sodium. Maybe IP should add explicit support for Embeddium ?

My setup:
OS: Linux
Mod loader: Forge 47.3.0
Minecraft: 1.20.1
LWJGL: 3.3.3
Immersive Portals: 3.3.9
Embeddium: 0.2.10/0.3.24
Sinytra connector: 1.0.0-beta.44

**Comment by OverwatchReaper** [comment]
please tell the class with more details i'm trying to read this to fix the bug that supposidly has been said 2 time but all i am getting is uprupt diappointment when i read this as its the only real place i have found a related problem... i'm using this as a basis for the forge version being the only non crashing or complaining mod wanting oculus or something when i love my embedium more as my portals are acting funny with them not rendering from a distance but upclose they look fine the nether portal being the same way

**Comment by OverwatchReaper** [comment]
![Image](https://github.com/user-attachments/assets/2d78f4f3-d4bc-4fd7-80e8-052479f8d59d)
from far away

![Image](https://github.com/user-attachments/assets/753fb80c-b31c-4f4b-8aa9-e254dc11d893)
upclose
