### ISSUE TITLE
crashes with Isometric Renders /isorender area

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#666]
### Mod Name

Isometricrenders [fabric]

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/isometric-renders

### Describe the bug

Crashed when running /isorender area after selection

### Steps to reproduce

1.  Install connector, connector extras + dependencies
2. install isometric renders + dependencies 
3. use keybind for isometric renders and select a simple area then run /isorender area
4. crash immediately 
...

### Logs

https://gist.github.com/Xplodin/b6065857972e5d4147faec995f8799c9

### Additional context

Emojiful 4.2.0
isometric-renders-0.4.6+1.20.2 (1.20.1 is listed as 1.20.2) 
custom fabric dependency config:
"isometric-renders": {
		"depends": {
			"fabricloader": ">=0.14.21",
			"fabric": ">=0.85.0",
			"worldmesher": ">=0.3.0",
			"minecraft": ">=1.20.1",
			"owo": ">=0.11.2"
		}
	}

connector 32 extras 1.8.0 fabric 0.91.0

EDIT: isometric renders just doesnt work with renderarea command. wasnt emojiful

**Comment by Su5eD** [comment]
The mod version you're running was made for minecraft 1.20.2 and is not compatible with 1.20.1. I've tested your use case on fabric and got an identical crash.
