### ISSUE TITLE
Crash when starting the server

### ISSUE THREAD

**Issue by BaryGG** [Sinytra/Connector#667]
### Describe the bug

I have noticed that on the client side the versions are compatible, however when installing it on the server side it simply crashes, even when the server is blank without any mod.

### Steps to reproduce

1. Install Connector-1.0.0-beta.32+1.20.1.jar, ConnectorExtras-1.8.0+1.20.1.jar, fabric-api-0.91.0+1.10.4+1.20.1.jar.
2. Launch server Mohist - Minecraft version:1.20.1 - Forge version: 47.2.17
3. Crashes instantly
...

### Logs

https://mclo.gs/AlvSUA1

### Additional context

Thanks to whom it may concern

**Comment by Tomat777** [comment]
Custom server apis is noot supported by connector, however u can try using MagmaMaintained which should work

**Comment by BaryGG** [comment]
Perfect, I'm going to try it, thank you very much for your support.
