### ISSUE TITLE
Spice of Fabric Crashing with Apple Skin

### ISSUE THREAD

**Issue by mxnmnm** [Sinytra/Connector#669]
### Mod Name

Spice of Fabric

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/spice-of-fabric

### Describe the bug

I tried to enter into the world but I crash

### Steps to reproduce

1. Try to make new world with apple skin (forge) and spice of fabric installed (sinytra beta 32)
2. Enter new world
3. Crash

### Logs

https://gist.github.com/mxnmnm/8d82e7805de04f3c1b6faa7d4d0d6f2f

**Comment by Su5eD** [comment]
AppleSkin's code differs between modloaders, and therefore the Forge version can't be used along with Fabric mods that use it. I recommend looking for config options to disable the integration, or [hiding](https://github.com/Sinytra/Connector?tab=readme-ov-file#hiding-forge-mods-presence) appleskin from Spice of Fabric.

**Comment by mxnmnm** [comment]
Hmmmm will there be a way in the future to enable the integration?

**Comment by mxnmnm** [comment]
or maybe appleskin fabric? (that one crashed before even entering the main menu lol)

**Comment by Tomat777** [comment]
U have spice of life for forge why would u need fabric one?

**Comment by mxnmnm** [comment]
Is there a spice of life for forge 1.20.1 that has diminishing returns and doesn't just give bonus effects/hearts?

**Comment by Tomat777** [comment]
Well appearently there is not

**Comment by DevLucasTavares** [comment]
@mxnmnm 
Hey same problem here, did u solve that?

**Comment by mxnmnm** [comment]
I used another mod instead, you can also use spice of fabric at the same time if you want vanilla cakes to register for diminishing returns but both don't work on modded cakes. 

https://www.curseforge.com/minecraft/mc-mods/hanger-system-overhaul

Personally I ended up just using hanger system over haul and this: https://www.curseforge.com/minecraft/mc-mods/nutritional-balance

Both of these combined makes it to where you have to have a lot of variety even if you find foods that would be cheaty with only one or the other.

**Comment by DevLucasTavares** [comment]
Thanks! Appreciate so much! Why did you choose nutritional balance and not diet?

**Comment by mxnmnm** [comment]
Because nutritional balance forces you to balance things more than diet because overeating a specific kind of food group will also cause negative consequences.

**Comment by mxnmnm** [comment]
I can't remember if I did or not, probably worth just looking at just in-case because it has been a while. I remember they had an interesting mechanic where some foods when eaten didn't push the new food counter as eaten so older foods you had eaten previously would require you to eat other "healthier" foods. I know I removed all of the foods from that list but beyond that I can't remember.

**Comment by DevLucasTavares** [comment]
Oh that helps a lot, thanks bro

**Comment by Mark-The-Lark** [comment]
For those who need same functionality I created https://modrinth.com/mod/spice-of-overhaul, which works on forge/neoforge and compatible with appleskin
