### ISSUE TITLE
Mythic Metals crash

### ISSUE THREAD

**Issue by DummSlayrr69420** [Sinytra/Connector#673]
### Mod Name

Mythic Metals

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mythicmetals

### Minecraft version

1.20.1

### Describe the bug

Crashing upon startup

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/DummSlayrr69420/7f9286baf39125ee2dd390001b0dd58b

### Additional context

Loaded with nothing but Sinytra and Forgified Fabric API, as well as the mod itself (Mythic Metals) and it's dependencies (OWOlib and Alloy Forgery)

**Comment by DummSlayrr69420** [comment]
I had to redo the debug log, because I think I messed it up
https://gist.github.com/DummSlayrr69420/370a41edde85353578f28150d37f384a

Also, latest.log
https://gist.github.com/DummSlayrr69420/83e6ca136f465baa44c9e8c651852dfb

**Comment by Su5eD** [comment]
You need to install Connector Extras, which includes a compatible port of Reach Entity Attributes, a library used by the mod.
