### ISSUE TITLE
More Axoltl Incompatibility

### ISSUE THREAD

**Issue by mxnmnm** [Sinytra/Connector#674]
### Mod Name

More Axolotls

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/more-axolotls

### Minecraft version

1.20.1

### Describe the bug

The mod is not compatible and does not work.

### Logs

https://gist.github.com/mxnmnm/a2b62b0befa502b82b1986ab00a96a2a

**Comment by Su5eD** [comment]
I was able to fix the mixin conflict, however, another issue still remains. Mavapi provides a fabric and forge mod in one jar, which means the forge mod always takes priority. There is no way to only load the fabric mod without modifying the jar, which I'll look into next.

**Comment by melontini** [comment]
I feel that this is entirely MavAPI's fault for poorly abstracting common code. There is no reasonable way to fix this without hardcoding or one more config, and such shouldn't be fixed in Connector.
