### ISSUE TITLE
Axiom, crash when trying to open context menu

### ISSUE THREAD

**Issue by Aendar** [Sinytra/Connector#675]
### Mod Name

Axiom

### Mod Homepage

https://modrinth.com/mod/axiom

### Minecraft version

1.20.1

### Describe the bug

The editor menu works pretty well. But trying to call the creative context menu by pressing alt throws you out of the game.

### Steps to reproduce

1. Enter the world
2. Press left alt (default key)
3. Crash

### Logs

https://mclo.gs/52FktWh

**Comment by Su5eD** [comment]
This looks like a conflict between Axiom and FancyMenu. Try removing FancyMenu to see if the crash persists.

**Comment by VladisCrafter** [comment]
Note that Axiom does work itself tho, tested successfully ☑️

**Comment by Aendar** [comment]
> This looks like a conflict between Axiom and FancyMenu. Try removing FancyMenu to see if the crash persists.

Yes, the crashes are completely gone tyvm!
