### ISSUE TITLE
Crash when loading Simply Swords with Mythic Metals

### ISSUE THREAD

**Issue by PvtFudgepants** [Sinytra/Connector#678]
### Mod Name

Simply Swords

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/simply-swords

### Minecraft version

1.20.1

### Describe the bug

Crashes when loading Simply Swords with Mythic Metals

### Steps to reproduce

1. Enable both Simply Swords and Mythic Metals. Simply Swords has compatibility to add swords using the ore from that mod.
2. Game crashes when you try to load.

### Logs

https://pastebin.com/15y4Wd5R

**Comment by Su5eD** [comment]
The Forge version of Simply Swords runs fine with beta 32. For mod integration compatibility, see the [FAQ](https://github.com/Sinytra/Connector/discussions/689).
