### ISSUE TITLE
Game Crashing with Modern Industrialization on forge 47.1.3 with forgified and sinytra

### ISSUE THREAD

**Issue by ZeroNyte** [Sinytra/Connector#680]
### Mod Name

ModernIndustrialization

### Mod Homepage

https://modrinth.com/mod/modern-industrialization

### Minecraft version

1.20.1

### Describe the bug

crashes with unknown reason

### Steps to reproduce

made a fairly small modpack via modrinth with froge 47.1.3 and mods:
-AE2
-Mekanism
-Industrial Foregoing
-Geckolib
-Distant Horizons
-Terralith-TerraBlender
-Mystical Agriculture
-Jade
-JourneyMap
-Thermal series
-Waystones

### Logs

https://gist.github.com/ZeroNyte/e3efa90a1427e392664f1aea79191f4f

### Additional context

.

**Comment by Su5eD** [comment]
https://gist.github.com/ZeroNyte/e3efa90a1427e392664f1aea79191f4f#file-gistfile1-txt-L325

> net.minecraftforge.fml.loading.EarlyLoadingException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install cloth-config, any version.
More details:
	 - mod 'Modern Industrialization' (modern_industrialization) 1.8.0 requires any version of cloth-config, which is missing!

**Comment by ZeroNyte** [comment]
added the cloth-config and still crashes

**Comment by ZeroNyte** [comment]
well.. doesn't crash when starting anymore, now it doesn't display menu text but squares and crashes when trying to join or make a world.
