### ISSUE TITLE
Mod Compatibility Thread

### ISSUE THREAD

**Issue by markygnlg** [Sinytra/Connector#682]
### Compatibility statuses

- ✅Compatible - This mods is tested and verified to be compatible with Connector
- ⚠️Functional - This mod loads with Connector, but might contain bugs
- ❌Incompatible - This mod is not compatible with Connector

# Status list

| 📦 Mod Name | 🔗 Link | ❓ Status | 🗒️ Notes |
|:------:|:------:|:------:|:------:|e 
 MC1.20.1
 F47.2.0
 Connector-1.0.0-beta.27+1.20.1_[FABRICmodLoader].jar
 fabric-api-0.90.7+1.10.3+1.20.1_[FABRICmodLoader].jar

fastquit-3.0.0+1.20.jar
 - ✅Compatible - This mods is tested and verified to be compatible with Connector

nohotbarlooping-1.1.1-1.20.1.jar
 - ✅Compatible - This mods is tested and verified to be compatible with Connector

better-end-4.0.10.jar (REQUIRES "bclib": "3.0.x" {TESTED: bclib-3.0.13.JAR} )
 - ⚠️Functional - This mod loads with Connector, but might contain bugs

blockofsky-fabric-1.20.1-0.3.0.jar (REQUIRES architectury {TESTED with both Fabric & Forge} )
 - ❌Incompatible - This mod is not compatible with Connector

**Comment by markygnlg** [comment]
TESTED BOTH "architectury-9.1.12-fabric.jar" & "architectury-9.1.12-forge.jar"

**Comment by markygnlg** [comment]
gray-goo-fabric-1.0.3+mc1.20.1.jar
 - ⚠️Functional - This mod loads with Connector, but might contain bugs

**Comment by VladisCrafter** [comment]
move it to #12 (and fix formatting pls)
