### ISSUE TITLE
Crash with Hamsters Plus Mod

### ISSUE THREAD

**Issue by SuperStefan97** [Sinytra/Connector#685]
### Mod Name

Hamsters Plus

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/hamsters-plus

### Minecraft version

1.20.1

### Describe the bug

Crash on start up

### Steps to reproduce

1. Use NeoForge modloader version 47.1.81 (has no problem with other fabric mods using connector, I'm for example using Better Nether/End and Useless Reptile)
2. Install Connector Beta 32, Extras 1.9.0 and Forgified Fabric Api 0.91.0+1.10.4
3. Install Hamsters Plus 1.0.2
4. Install Geckolib Neo version 4.3.1 (also, Neo version Gecko works fine with other dependencies like Useless Reptile)
5. Crash
...

### Logs

https://gist.github.com/SuperStefan97/0c2411af330e398e688efed2c2393d35

### Additional context

First of all Merry Christmas and Happy New Year. I also posted another issue about Recrafted Creatures around Christmas, I know you are busy, but could you give a check too when you got any time? Thanks for your time with this awesome mod

**Comment by RoomAlex68** [comment]
You will need to use Geckolib Fabric for Hamsters Plus

**Comment by SuperStefan97** [comment]
Thanks! Sadly, Fabric Gecko doesn't seems to work with Forge/Neo-gecko dependent mods. Oddly enough, Useless Reptile which is a Fabric mod that also needs Gecko, works nice with Neo gecko

**Comment by SuperStefan97** [comment]
I understand, so there is no way to use Forge/Neo Gecko dependent mods alongside Fabric dependent mods?

**Comment by RoomAlex68** [comment]
Most Geckolib Forge,Neo Gecko mods work with Geckolib Fabric. But at the moment we will have to wait till Geckolib inplants a mulitloader system. So for right now we cannot use Geckolib Forge, NeoForge alongside with Geckolib Fabric. There is a fork of Geckolib called "Azurelib" which has a mulitloader system.

**Comment by SuperStefan97** [comment]
I see, will mods need to replace it dependency to Gecko, or would it work only by replacing Gecko with Azure on my side?

**Comment by RoomAlex68** [comment]
No, Geckolib mods do not use Azurelib dependencies.

**Comment by Su5eD** [comment]
Same issue as #231, see that report for more information on the current state of geckolib on connector.
