### ISSUE TITLE
Sinytra Connector + Psychodelicraft fabric mod 1.20.1 not working

### ISSUE THREAD

**Issue by RadostinDinov** [Sinytra/Connector#687]
### Mod Name

Psychodelicraft

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/psychedelicraft

### Minecraft version

1.20.1

### Describe the bug

I am using forge 47.1.3  Sinytra's connector + forge api and the other mod is psychodelicraft. No other mods used.

### Steps to reproduce

1. Install Sinytra's plugins
2. Install Psychodelicraft
3. Run
4. Error is displayed

### Logs

https://pastebin.com/FWsTmdrB

### Additional context

There is a ticket in Discord too named: Sinytra Connector + Psychodelicraft fabric mod 1.20.1 not working

**Comment by Su5eD** [comment]
Confirmed to run fine on Forge 47.1.3 and Connector beta 32
