### ISSUE TITLE
Holographic Renders area rendering is broken with connector mod only

### ISSUE THREAD

**Issue by Mysticpasta1** [Sinytra/Connector#688]
### Mod Name

Holographic Renders

### Mod Homepage

https://github.com/Mysticpasta1/holographic-renders

### Minecraft version

1.20.1

### Describe the bug

area rendering isn't culling correctly in the mod

### Steps to reproduce

1. load connector mod and holographic renders together
2. take a 3x3x3 area render of the ground and put it in a projector 
3 do same on fabric only
4 profit

### Logs

no logs due to it is a logic error in the code somewhere

### Additional context

https://github.com/Mysticpasta1/holographic-renders
https://github.com/Mysticpasta1/worldmesher

https://cdn.discordapp.com/attachments/1141048835146260513/1193492827280244847/image.png?ex=65ace9d0&is=659a74d0&hm=119baca001008147e42e335b0b9f3c2c9272f02931d9e1d1f12156c8d08f16ac&
on left is fabric only, on right is forge with connector mod

https://github.com/Mysticpasta1/worldmesher/blob/1.20/src/main/java/io/wispforest/worldmesher/renderers/WorldMesherBlockModelRenderer.java

**Comment by Mysticpasta1** [comment]
I'm the creator of the mod if there is anyway I can fix it on my end let me know

**Comment by VladisCrafter** [comment]
There are overall some visual bugs with every type of holograms with Connector. For example, my skin becomes semi-transparent when a working renderer is in camera's FOV. I can open a separate issue about this, if anyone wants.

**Comment by Mysticpasta1** [comment]
can you post them all here

**Comment by Mysticpasta1** [comment]
fixed in this build finally https://www.curseforge.com/minecraft/mc-mods/holographic-renderers/files/5162694
