### ISSUE TITLE
Wurst Client has easily fixable crash

### ISSUE THREAD

**Issue by some16** [Sinytra/Connector#693]
### Mod Name

Wurst7

### Mod Homepage

https://github.com/Wurst-Imperium/Wurst7/

### Minecraft version

1.20.1

### Describe the bug

When attempting to use [Wurst](https://github.com/Wurst-Imperium/Wurst7/) with Connector, one gets the error 
 > org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector setVelocityFromFluid(Lnet/minecraft/world/entity/Entity;Lnet/minecraft/world/phys/Vec3;)V in wurst.mixins.json:EntityMixin from mod wurst failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json   
 
 The ```setVelocityFromFluid``` function does not appear to be used anywhere in Wurst's code, and when I removed it from Wurst it builds and runs successfully.
 
 It is unclear to me if this is technically a bug with Wurst, and I should put this bug report there, or this is an issue with Connector.

### Steps to reproduce

1. Install [Wurst Client](https://www.wurstclient.net/updates/wurst-7-39-1/?mc=1.20.1#downloads), [Connector](https://modrinth.com/mod/connector/version/1.0.0-beta.32+1.20.1), and [Forgified](https://modrinth.com/mod/forgified-fabric-api/version/0.91.0+1.10.4+1.20.1) (I've linked the specific versions I used)
2. Launch Minecraft

### Logs

https://gist.github.com/some16/24c186d291de597c920d7e0af7c42576

**Comment by Su5eD** [comment]
Hacked clients are not supported.
