### ISSUE TITLE
Immersive Portals shouldn't be incompatible with Sleep Tight

### ISSUE THREAD

**Issue by AntonyCilleros** [Sinytra/Connector#694]
### Mod Name

Immersive Portals

### Mod Homepage

https://modrinth.com/mod/immersiveportals

### Minecraft version

1.20.1

### Describe the bug

Can't change gamemode or break blocks in the nether.

### Steps to reproduce

1. Install the latest version of Immersive Portals (fabric) and Sleep Tight (forge).
2. Start a world and go to the nether.
3. Try changing gamemode and try breaking blocks.

### Logs

https://pastebin.com/jxxVUssn

### Additional context

Immersive Portals is normally compatible with Sleep Tight on fabric, but it is not when using sinytra.
With Sleep Tight, I can't change my gamemode after entering the nether unless I disconnect and load the world again but then if I go back to the Overworld I have the same problem again and I need to leave and reload my world again. 
Sometimes I can't even destroy block after switching from these two dimensions but I can't reproduce this error consistently.

imo it's an issue coming from sinytra and Immersive Portals because I have another problem with immersive portals and sinytra and I think these two issues are somehow related #695

**Comment by MehVahdJukaar** [comment]
This is related to capabilities assigned via AttachCapabilitiesEvent somehow being null

**Comment by Su5eD** [comment]
Seems to be the same issue as #564, moving tracking to there
