### ISSUE TITLE
Immersive Portals shouldn't be incompatible with PlayerRevive and Hardcore Revival

### ISSUE THREAD

**Issue by AntonyCilleros** [Sinytra/Connector#695]
### Mod Name

Immersive Portals

### Mod Homepage

https://modrinth.com/mod/immersiveportals

### Minecraft version

1.20.1

### Describe the bug

When I enter the nether, I can't die even after returning to the overworld.

### Steps to reproduce

1. Install latest version of immersive portals and PlayerRevive or Hardcore Revival.
2. Start a world and go to the nether.
3. kys

### Logs

https://pastebin.com/9jXEqU5J

### Additional context

Immersive Portals is normally compatible with PlayerRevive and Hardcore Revival on fabric, but it is not when using sinytra.

imo it's an issue coming from sinytra and Immersive Portals because I have another problem with immersive portals and sinytra and I think these two issues are somehow related ( #694 )

**Comment by Su5eD** [comment]
Seems to be the same issue as #564, moving tracking to there
