### ISSUE TITLE
ItemSwapper resource pack error with REI (Forge) or JEI

### ISSUE THREAD

**Issue by MrFastZombie** [Sinytra/Connector#696]
### Mod Name

ItemSwapper

### Mod Homepage

https://modrinth.com/plugin/itemswapper

### Minecraft version

1.20.1

### Describe the bug

When ItemSwapper is installed with REI or JEI it will not be able to detect its own resource pack and will show a "No compatible resource pack for ItemSwapper is enabled!" error upon opening it.

### Steps to reproduce

1. Install ItemSwapper (Fabric)
2. Install either REI or JEI (Forge)
3. Ensure that the ItemSwapper resource pack is loaded (usually is by default)
4. Try to use ItemSwapper with block included on the default palletes (i.e. cobble)

### Logs

https://mclo.gs/0RwtvxT

### Additional context

My debug.log is attached. There isn't a crash, but just in case it provides any useful information.

REI can be found at https://modrinth.com/mod/rei
JEI can be found at https://modrinth.com/mod/jei

**Comment by Su5eD** [comment]
I've tested this out with both REI and JEI, but I was unable to reproduce the issue.
| JEI | REI |
|--------|--------|
| ![2024-01-13_10 46 15](https://github.com/Sinytra/Connector/assets/51261569/2fe44034-4abd-4e86-bb59-0d90924bd726) | ![2024-01-13_10 48 40](https://github.com/Sinytra/Connector/assets/51261569/2a099478-2c03-4477-9ea4-1ad0fbce76b6) |

Also, your log shows you have a lot more mods installed than you've listed. Plead read the issue template more carefully.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by MrFastZombie** [comment]
My bad. I disabled the rest of the mods and found that this issue only occurs if ModernFix is also installed. I checked if this issue occurs when ModernFix is used with REI and ItemSwapper on Fabric and the issue does not occur there.

Debug.log with Connector, ItemSwapper, REI, dependencies, and ModernFix: https://mclo.gs/y474rhg

**Comment by Su5eD** [comment]
After investigating the issue, I found out ModernFix contains a feature that allows mods to replace the vanilla creative search tree. This only triggers when a valid provider is installed, which happens to be JEI in our case. ItemSwapper detects installed resourcepacks via a resource reloader, which is injected by a [mixin](https://github.com/tr7zw/ItemSwapper/blob/0b18d97c99921b70a84a6267677e1a888163db30/Shared/src/main/java/dev/tr7zw/itemswapper/mixin/MinecraftMixin.java#L43C23-L43C40). However, [ModernFix cancels](https://github.com/embeddedt/ModernFix/blob/1.20/common/src/main/java/org/embeddedt/modernfix/common/mixin/perf/blast_search_trees/MinecraftMixin.java#L35) ItemSwapper's injector after replacing the search tree, leading to the issue.

As a workaround, you can simply disable this ModernFix feature in the `modernfix-mixins.properties` config file by adding `mixin.perf.blast_search_trees=false`. However, for a proper fix I recommend ItemSwapper to lower the priority of its mixin to ensure it always comes before ModernFix.
