### ISSUE TITLE
optifine crashed with connector

### ISSUE THREAD

**Issue by ThePowerFox** [Sinytra/Connector#697]
### Mod Name

Optifine

### Mod Homepage

https://optifine.net/home

### Minecraft version

1.20.1

### Describe the bug

no matter with optifne version i have it still crashes

### Steps to reproduce

1.install optifine
2.install connector
3.launch game
...

### Logs

<script src="https://gist.github.com/ThePowerFox/e96c1d64b7c6c489b96f9db27c728dce.js"></script>

**Comment by Su5eD** [comment]
OptiFine is not supported, please see the [FAQ](https://github.com/Sinytra/Connector/discussions/689)
