### ISSUE TITLE
Bedrockify Incompatibility

### ISSUE THREAD

**Issue by Starexify** [Sinytra/Connector#700]
### Mod Name

Bedrockify

### Mod Homepage

https://modrinth.com/mod/bedrockify

### Minecraft version

1.20.1

### Describe the bug

Bedrockify crashes at startup

### Steps to reproduce

1. Install Bedrockify
2. Run Minecraft
3. Crash

### Logs

https://pastebin.com/HUX3Sinh

### Additional context

I don't really know if bedrockify does that or it's another mod. 
Edit: I tried with bedrockify, connector, forgified api, connector extras,  lazurite, and embeddium das all

**Comment by coco875** [comment]
to be sure reduce create a new instance with only connector and bedrockify and it's better to have the crash log or the debug log if you want on the server we can help analysis your crash.

**Comment by Su5eD** [comment]
Tested to work fine on Forge 47.1.3 and Connector beta 32
