### ISSUE TITLE
All Fabric mods fail to load with cryptic errors if there is an invalid/corrupted Forge mod

### ISSUE THREAD

**Issue by Fuyukai** [Sinytra/Connector#701]
### Minecraft version

1.20.1

### Describe the bug

All Fabric mods fail to load with cryptic errors if there is an invalid/corrupted Forge mod

### Steps to reproduce

1. Add a mod with broken metadata (e.g. ``mkdir META-INF; echo "[invalid]" > META-INF/mods.toml; zip testmod.zip -r META-INF``)
2. Add any Fabric mod to the instance
3. Observe inability to find ``fabric-api`` despite Forgified Fabric API being installed.

### Logs

https://gist.github.com/Fuyukai/f9bd7c60f1a86374495e36ddad94697c

### Additional context

Crash does not happen if ``testmod.jar`` is disabled, or the Fabric mods are disabled (Forge gives the appropriate warning about an invalid mod). The actual Fabric mod in this case doesn't matter; I picked the first I could find on Modrinth with no forge version or other dependencies; I've had it explode in an instance full of them.

For a less contrived example that actually happens in the wild, [Oculus mc1.20.1-1.6.13a](https://modrinth.com/mod/oculus/version/1.20.1-1.6.13a) triggers this bug due to having invalid metadata.

**Comment by Lolothepro** [comment]
probably a NeoForge bug
