### ISSUE TITLE
Incompatible with sodium 0.5.2

### ISSUE THREAD

**Issue by kakashi1464** [Sinytra/Connector#71]
### Mod Name

Sodium

### Mod Homepage

https://modrinth.com/mod/sodium

### Describe the bug

Crashes with Sodium 0.5.2

### Steps to reproduce

1.Add FFAPI with Connector and Sodium
2.Run Minecraft

### Logs

https://mclo.gs/HagiuqH - crash report
https://mclo.gs/vufpfsi - latest log
https://mclo.gs/NWxA45f - debug log

**Comment by Lolothepro** [comment]
Note: Even if you fix this crash, Sodium will never work properly with Forge via Sinytra.

**Comment by Fox2Code** [comment]
There are sodium ports for Forge, making those ports be able to work as a sodium substitute on sintra would work better.

**Comment by Su5eD** [comment]
I've taken a look at the conflicting mixins and unfortunately I don't see any good way to make them work. Sodium redirects window creation to its own method, which is also [completely overwritten](https://github.com/MinecraftForge/MinecraftForge/blob/ab70bde1d648125acee073a93a25d4b8f08985c9/patches/minecraft/com/mojang/blaze3d/platform/Window.java.patch#L7-L9) by forge to enable their Early Loading Screen.

As others have said, you wouldn't get too far running sodium with other mods anyway. I recommend using Forge ports instead - [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) for Sodium and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) for Iris.

**Comment by Gamemassa** [comment]
Damn, I was hoping this might be a thing. ATE48's Xray mod works with Iris on Fabric but not with Oculus on Forge (or not properly anyway).

And inb4 anyone complains about "cheating", I only use Xray in my single-player world for construction purposes. Big pain in the butt having to tear out an entire wall to figure out which redstone device wasn't connected properly.

**Comment by parka27** [comment]
rubbidion have so many problems of compabiltyes with the most part of the mods its better embeddium the mod fails with oculus (iris) but the most part of the mods can load with embeddium I'm sorry if I wrote wrong, my level of English is like that of an anemone.

**Comment by RoomAlex68** [comment]
I hope this is resolved when neoforge releases

**Comment by TouseefX** [comment]
i also need sodium cuz i have issuse with the forge one fabric will only works

**Comment by coco875** [comment]
just a small precision sodium can never be compatible with forge/neoforge so instead use embeddium who make parity with sodium and fix conflict between
