### ISSUE TITLE
Hybrid Aquatic crash while transforming

### ISSUE THREAD

**Issue by Groupix05** [Sinytra/Connector#721]
### Mod Name

Hybrid Aquatic

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic

### Minecraft version

1.20.1

### Describe the bug

Hybrid Aquatic on Sinytra Connector Crash the game.
Only the first launch on client, but always on server. 
 §e[Connector]§r Error transforming jar /home/********/multicraft/servers/server253166/mods/hybrid-aquatic-1.1.0.jar §cjava.util.concurrent.ExecutionException§7: java.lang.RuntimeException: Failed to execute task dev/hybridlabs/aquatic/mixin/FishingBobberEntityMixin.class§r

### Steps to reproduce

I use a modpack called ColoCraft - modern Adventures ver2.3.3 here: https://www.curseforge.com/minecraft/modpacks/colocraft-modern-adventures/files/5034792
It uses :
Forge 47.2.19
ConnectorExtras-1.9.2+1.20.1
fabric-api-0.91.0+1.10.5+1.20.1
geckolib-forge-1.20.1-4.4
hybrid-aquatic-1.1.0
Connector-1.0.0-beta.32+1.20.1
fabric-language-kotlin-1.10.17+kotlin.1.9.22
And a lot of mods

I'm the creator of this modpack. Putting the converted version of Hybrid Aquatic fix the client crash, but not the server, but I cant put it in my modpack due to Curseforge.

### Logs

Logs are in Additional context for simplicity

### Additional context

Every Other Fabric mods works perfectly, like BetterEnd, BetterNether, Interactic, AdventureZ, Wizards, Runes, Paladins & Priests, Jewelry, Archers, Gazebos.
Only Hybrid aquatics crash the game.
If you launch your client 2 times, everything works
I was thinking its due to ESSENTIAL, but removing it does nothing, I still have the same crash.

Client :
1st launch: 
logs: https://mclo.gs/Ma2mdfp
No crash log, just error code: 1
I added 2 line in the crash log, with this time : 13:42:07 ; because they were on the minecraft game output but not the log.
Now there is a .connector folder with hybrid-aquatic_mapped.jar & hybrid-aquatic_mapped.jar.input and some others mods

2nd launch:
logs : https://mclo.gs/K5pYey0
Everything works perfectly, no crash, and hybrid aquatic works as normal.

Server:
1st launch: 
logs : https://mclo.gs/caap4xv
debug : https://mclo.gs/d4c6lqK
Crash log : https://mclo.gs/cJv3bYp
Created .connector folder with hybrid-aquatic_mapped.jar & hybrid-aquatic_mapped.jar.input and some others mods

2nd launch: 
logs : https://mclo.gs/e6Xb4oc
debug : https://mclo.gs/FyI8cD6
Crash log : https://mclo.gs/t1IFjrY

**Comment by Groupix05** [comment]
I tried with only Hybrid aquatics and some others but im unable to reproduce this crash. I will send the problematic mod once I manage to found with what mod this crash happend .

**Comment by Su5eD** [comment]
Confirmed to work on Connector Beta 34

![2024-01-25_19 22 33](https://github.com/Sinytra/Connector/assets/51261569/bc115f26-0533-4135-8f23-26d96f72a183)
