### ISSUE TITLE
Modern Beta crash on startup (exit code: 1)

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#724]
### Mod Name

ModernBeta

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-beta

### Minecraft version

1.20.1

### Describe the bug

Crash for no reason with exit code 1

### Steps to reproduce

1. put the mod in the mods folder
2. launch the game
3. it will not let me play with the mod, and it will crash with exit code: 1
...

### Logs

https://gist.github.com/vinnyg0621/8e08e44821d80f85173e949b2e2f362f

**Comment by Su5eD** [comment]
Please read the log, you're missing a dependency.
> net.minecraftforge.fml.loading.EarlyLoadingException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Install cloth-config2, any version.
Unmet dependency listing:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Mod 'Modern Beta Fabric' (modern_beta) 6.4.1+1.20 requires any version of cloth-config2, which is missing!

**Comment by vinnyg0621** [comment]
I thought I had that mod already in the mods folder 🤔

**Comment by vinnyg0621** [comment]
wait never mind, I just started the game and it loaded with it! 😁
