### ISSUE TITLE
Crash upon entering BetterEnd biones.

### ISSUE THREAD

**Issue by ItzLucaGER** [Sinytra/Connector#725]
### Mod Name

BetterEnd

### Mod Homepage

https://modrinth.com/mod/betterend

### Minecraft version

1.20.1

### Describe the bug

Server starts to lag and then crashes after entering a BetterEnd biome

### Steps to reproduce

1. Enter End (works fine)
2. Use gateway
3. Find BetterEnd biome
4. Starts to lag
5. Server crashes
...

### Logs

https://gist.github.com/ItzLucaGER/65a20c3410eddf18f80a2bb0cfef5ff5

**Comment by Matyrobbrt** [comment]
This is not a Connector issue, you have run out of memory. You should give Minecraft more memory.

**Comment by ItzLucaGER** [comment]
The server crashed every time upon entering the BetterEnd biome, after removing ModernFix it worked just fine
