### ISSUE TITLE
Crash in world with modern beta world type every time I'm in it

### ISSUE THREAD

**Issue by vinnyg0621** [Sinytra/Connector#729]
### Mod Name

ModernBeta

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-beta

### Minecraft version

1.20.1

### Describe the bug

Exception while adding particle

### Steps to reproduce

1. create a new world type with modern beta
2. after a couple seconds, the game will freeze
3. the game saves and exits
4. it happend two times to me
...

### Logs

https://gist.github.com/vinnyg0621/de7a491f30463bf2b0c1cb8976d0fda0

### Additional context

so I created this new world, and then I looked around, and then the game suddenly froze for no reason. but then , the world exited and saved and the game crashed with exit code: -1.

**Comment by Su5eD** [comment]
You're using an outdated version of Connector. Please update to the latest version, and Modern beta will work fine.
