### ISSUE TITLE
Industrial Revolution incompatibility

### ISSUE THREAD

**Issue by Abbie5** [Sinytra/Connector#73]
### Mod Name

Industrial Revolution

### Mod Homepage

https://modrinth.com/mod/industrial-revolution

### Describe the bug

Crash upon loading world

### Steps to reproduce

1. install connector, ffapi, fabric language kotlin, industrial revolution
2. load into world
3. crash

### Logs

https://mclo.gs/X06gb8N

**Comment by Su5eD** [comment]
Should be fixed now. Can you try using this [dev build](https://github.com/Sinytra/Connector/suites/15284086863/artifacts/872844114) and FFAPI `0.87.0+1.9.4+1.20.1` ?

**Comment by Abbie5** [comment]
yup that fixes the issue, thanks

**Comment by tiandan6666** [comment]
> 现在应该修复了。您可以尝试使用此[开发版本](https://github.com/Sinytra/Connector/suites/15284086863/artifacts/872844114)和 FFAPI`0.87.0+1.9.4+1.20.1`吗？

When using rubidium, the block cannot be rendered, and the GUI crashes when opening.
FPS will be very low without rubidium, this must be compatible
This version of Forge does not support optifine
