### ISSUE TITLE
Replay mod crashes minecraft

### ISSUE THREAD

**Issue by braydenl1321** [Sinytra/Connector#733]
### Mod Name

replaymod-1.20.1-2.6.14.jar

### Mod Homepage

https://modrinth.com/mod/replaymod/version/1.20.1-2.6.14

### Minecraft version

1.20.1

### Describe the bug

It crashes the game

### Steps to reproduce

1.I started Minecraft.
2.I waited for the loading screen to finish.
3.The game crashed.
...

### Logs

https://pastebin.com/MaFhsTep

**Comment by Su5eD** [comment]
Duplicate of #589
