### ISSUE TITLE
Its not a problem but i need for according to how it looks

### ISSUE THREAD

**Issue by RedneTwo** [Sinytra/Connector#736]
### Minecraft version

1.20.1

Could you add the config file to disable in mods list the all mods from Sinytra? They just didn't appear in the mod list.

**Comment by Su5eD** [comment]
FML displays all loaded mods regardless of their origin, and it doesn't have any ways of disabling mods from showing up. Could you please elaborate why this is desired?

**Comment by Tapacywka** [comment]
> FML displays all loaded mods regardless of their origin, and it doesn't have any ways of disabling mods from showing up. Could you please elaborate why this is desired?

Perhaps this means that the in-game menu with a list of modifications is initially filled with dozens of different tweaks from the connector, among which it is difficult to search for “real” modifications that you installed after installing the connector. Most likely the person is asking for an option, something like “hide libraries” in the fabric version of ModMenu.

**Comment by Su5eD** [comment]
Unfortunately, this is imposed by Forge's modlist, which doesn't come with such features. Connector adds a regular FML mod to the game, which is necessary to apply certain compat code.
