### ISSUE TITLE
crash on startup 

### ISSUE THREAD

**Issue by seijakijinn** [Sinytra/Connector#737]
### Mod Name

yosbr (?)

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/yosbr

### Minecraft version

1.20.1

### Describe the bug

game crashes on startup

### Steps to reproduce

1. drop mods into mods folder
2. launch game
3. game gives error or crashes

### Logs

https://gist.github.com/seijakijinn/f4f246ab8fe9a411142e4ecbd01fb42b

**Comment by Matyrobbrt** [comment]
>>> [04:00:01] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'lmft', Expected range: '[47.2.6,)', Actual version: '47.1.3'
	Mod ID: 'forge', Requested by: 'bettercombat', Expected range: '[47.2,)', Actual version: '47.1.3'

**Comment by seijakijinn** [comment]
[latest.log](https://github.com/Sinytra/Connector/files/14000694/latest.log)
[crash-2024-01-21_04.30.54-fml.txt](https://github.com/Sinytra/Connector/files/14000695/crash-2024-01-21_04.30.54-fml.txt)

**Comment by Tomat777** [comment]
1.Issue template says this:
You've installed a minimal set of mods required to reproduce the issue.
Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
If you're unsure which mods might be at fault, try using [binary search](https://www.reddit.com/r/feedthebeast/comments/evpy6r/tips_for_modpack_authors_how_to_find_misbehaving/) - removing half of installed mods
repeatedly until the faulty mod is found.
2. You can try to delete sodium and indium and use forge ports which is embeddium and lazurite.
