### ISSUE TITLE
crash on startup 

### ISSUE THREAD

**Issue by seijakijinn** [Sinytra/Connector#738]
### Mod Name

yosbr (?)

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/yosbr

### Minecraft version

1.20.1

### Describe the bug

game crashes on startup

### Steps to reproduce

1. drop mods into mods folder
2. launch game
3. game gives error or crashes

### Logs

https://gist.github.com/seijakijinn/f4f246ab8fe9a411142e4ecbd01fb42b https://gist.github.com/AvaloriaSinytra/ff717b492e92e2b3785dd140e1869003

### Additional context

receiving the same error before and after deleting yosbr from the mods folder

**Comment by Su5eD** [comment]
Duplicate of #737
