### ISSUE TITLE
Wakes mod rendering issues

### ISSUE THREAD

**Issue by GermanArtur** [Sinytra/Connector#740]
### Mod Name

Wakes

### Mod Homepage

https://modrinth.com/mod/wakes

### Minecraft version

1.20.1

### Describe the bug

Boat model overlaps the "wake simulation"

### Steps to reproduce

1. Get in the boat
2. Start moving
3. Spot the visual bug
...

### Logs

https://mclo.gs/TgcS6mK

### Additional context

Connector-1.0.0-beta.33+1.20.1.jar
ConnectorExtras-1.9.2+1.20.1.jar
fabric-api-0.91.0+1.10.8+1.20.1.jar
wakes-0.2.3.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar

**Comment by Learwin** [comment]
This seems to be a bug in wakes. 
https://github.com/Goby56/wakes/issues/46
I downgraded to wakes-0.2.2 which did not have that issue.
