### ISSUE TITLE
Crash with sculk horde forge mod

### ISSUE THREAD

**Issue by frangnosquest** [Sinytra/Connector#741]
### Mod Name

Sculk Horde

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sculk-horde

### Minecraft version

1.20.1

### Describe the bug

Game crashes when attempting to use the sculk sweeper's right-click ability

### Steps to reproduce

1. Install sinytra connector and forgified fabric api
2. Install sculk horde and geckolib forge/neoforge
3. Join a world, give yourself the sculk sweeper sword and spawn a sculk monster from the mod
4. attempt to right-click with the sword in hand and said mob nearby

### Logs

https://pastebin.com/pR7vVjqp

**Comment by Su5eD** [comment]
This is a bug in the sculk mod and also occurs without connector installed
