### ISSUE TITLE
Latest Connector [33] crashes my modpack, while 29 did not.

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#749]
### Minecraft version

1.20.1

### Describe the bug

The modpack will no longer load, logs attached

### Steps to reproduce

download pack : https://modrinth.com/modpack/minecraft-findev/versions then attempt to update to Connector-33, and the game will not make it past the initial loading/startup screen

### Logs

https://gist.github.com/Its-Just-Luci/e2d58db5691da24504b9af2604e57907

**Comment by Matyrobbrt** [comment]
> [21Jan2024 22:35:24.021] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'cloth_config', Requested by: 'brb', Expected range: '[9,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'dynmus', Expected range: '[9.0.94,)', Actual version: '[MISSING]'

You have missing dependencies.

**Comment by Its-Just-Luci** [comment]
> You have missing dependencies.

I've had those errors for months, I will resubmit the log without them if that will make you feel better.

**Comment by Its-Just-Luci** [comment]
Additionally, and I cannot stress this enough, the pack worked with connector 29, and does not with 33, I have not changed _literally anything else in the installation whatsoever_, However I will resubmit the same error as a new issue as soon as I am home.

**Comment by Matyrobbrt** [comment]
> > You have missing dependencies.
> 
> I've had those errors for months, I will resubmit the log without them if that will make you feel better.

Missing dependencies will lead to Forge (and Connector) not loading certain features (or not fully doing so). A missing dependency *can* be the sole cause of even a mixin error.

**Comment by Its-Just-Luci** [comment]
> > > You have missing dependencies.
> > 
> > 
> > I've had those errors for months, I will resubmit the log without them if that will make you feel better.
> 
> Missing dependencies will lead to Forge (and Connector) not loading certain features (or not fully doing so). A missing dependency _can_ be the sole cause of even a mixin error.

Cool, but it isn't.

https://gist.github.com/Its-Just-Luci/4aad6d8f480cfb12837cb0a4ebf21442
