### ISSUE TITLE
Reposts #748

### ISSUE THREAD

**Issue by charliez0** [Sinytra/Connector#751]
### Mod Name

Advanced Reborn

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/advancedreborn

### Minecraft version

1.20.1

### Describe the bug

cannot start the game

### Logs

https://gist.github.com/charliez0/872502e1400eb474a1147bba46e808ae

**Comment by Matyrobbrt** [comment]
MCPitanLib, a dependency of Advanced Reborn requires Arhitectury.

**Comment by charliez0** [comment]
added, problem still exists.
https://gist.github.com/charliez0/58c9a824f9db00033acdae7c6c5d804d

**Comment by charliez0** [comment]
@Su5eD

**Comment by Su5eD** [comment]
Confirmed to work on Beta 40 using the Fabric version of MCPitanLib
