### ISSUE TITLE
OmniHoppers Oxidizing Copper Hopper crash

### ISSUE THREAD

**Issue by water-mizuu** [Sinytra/Connector#754]
### Mod Name

Omni Hoppers

### Mod Homepage

https://modrinth.com/mod/omnihopper

### Minecraft version

1.20.1

### Describe the bug

The mod actually works mostly fine, but the game crashes when placing a fluid hopper which is made of copper. This only applies to the hopper that can be oxidized.  

### Steps to reproduce

1. Install the mod.
2. Try to place a fluid hopper named "Flopper" in game (not waxed).

### Logs

https://gist.github.com/water-mizuu/ac9b4609e236b8e839113c5e5a870394

### Additional context

I did not post the entire log, because it's very long and because I have a large mod pack. However, I believe that I have posted the relevant details regarding this crash. Note, the waxed hoppers do not crash, so I have reason to believe this is related to the `Oxidizable` interface which seems like it's from fabric? I do not indulge in coding mods, so I apologize if this is wrong.

**Comment by Matyrobbrt** [comment]
> Before reporting, please ensure that:
- You've installed a minimal set of mods required to reproduce the issue.
Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
If you're unsure which mods might be at fault, try using [binary search](https://www.reddit.com/r/feedthebeast/comments/evpy6r/tips_for_modpack_authors_how_to_find_misbehaving/) - removing half of installed mods
repeatedly until the faulty mod is found.

I am unable to reproduce this with must omnihoppers, it would seem to be an incompatibility between omnihoppers and create.

**Comment by water-mizuu** [comment]
My bad, it seems that it also crashes with other copper blocks, which means that Omni-hoppers is not the problem. Thank you!

**Comment by water-mizuu** [comment]
It seems I have fixed the problem. It turns out, the breakage is caused by the combination of Create, Additional Placements, and Omni Hoppers.
