### ISSUE TITLE
Startup crash with Unicopia

### ISSUE THREAD

**Issue by AzrielMud** [Sinytra/Connector#757]
### Mod Name

Unicopia

### Mod Homepage

https://github.com/Sollace/Unicopia

### Minecraft version

1.20.1

### Describe the bug

The game just crashes when Unicopia is installed and game doesn't create crash-report.

### Steps to reproduce

1. Install Connector, FFAPI, Unicopia
2. Launch game
3. Crash

### Logs

latest.log - https://pastebin.com/2VUT2iMq
debug.log - https://pastebin.com/Mha1MZK2

### Additional context
(Forge 47.1.3, Connector beta 36)
_No response_

**Comment by coco875** [comment]
Add the crash-log also

**Comment by AzrielMud** [comment]
> and game doesn't create crash-report.

crash-report isn't created

**Comment by coco875** [comment]
Ok I just skip some information
