### ISSUE TITLE
Disconnects from world (internal server) with Nether Depths installed

### ISSUE THREAD

**Issue by Nokunami** [Sinytra/Connector#759]
### Mod Name

Nether Depths

### Mod Homepage

https://modrinth.com/mod/nether-depths-mod

### Minecraft version

1.20.1

### Describe the bug

Disconnects the player after a few minutes.

### Steps to reproduce

1. Connector + FFAPI and Nether Depths
2. Launch game and create/ load a world
3. After a minute just disconnect
...

### Logs

https://mclo.gs/gJiVTW8

### Additional context

This doesn't happen on fabric.

**Comment by Su5eD** [comment]
Tested this out and it runs fine on Beta 44. Here's my log for reference https://mclo.gs/YRe77yL
