### ISSUE TITLE
dynamic surroundings underwater crash

### ISSUE THREAD

**Issue by dasdwavbc** [Sinytra/Connector#761]
### Mod Name

dynamic surroundings

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-fabric-edition

### Minecraft version

1.20.1

### Describe the bug

break underwater block proceeds world crash

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/dasdwavbc/84538e1be444263f8a36f2eaec9e9b05

**Comment by dasdwavbc** [comment]
only appears when particles  is set "minimal"

**Comment by OreCruncher** [comment]
I believe this is a Dynamic Surroundings issue. I made a code tweak fin 0.3.0 which hopefully will hit CurseForge once someone wakes up and hits some buttons. Or you can get from Modrinth because their elves are on automatic. :)

**Comment by liangmoe** [comment]
some of the Dynamic Surroundings feature are not working from the newest version via connector: bow pulling sound, steam columns effect... cant track other not working feature properly cause i just know a few of then
![image](https://github.com/Sinytra/Connector/assets/135343248/8c27d560-4155-484b-91db-db6956289f6d)

**Comment by OreCruncher** [comment]
@liangmoe Open up an issue in my GitHub repo. I don't think this is Connector related.
