### ISSUE TITLE
Zenith (unofficial fabric port of the Apotheosis) crash on startup

### ISSUE THREAD

**Issue by YShadowMY** [Sinytra/Connector#764]
### Mod Name

Zenith

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/zenith

### Minecraft version

1.20.1

### Describe the bug

crash on start

### Steps to reproduce

1. install connector, connectorExtras, FFAPI, zenith, zenith attributes (https://www.curseforge.com/minecraft/mc-mods/zenith-attributes), fakerlib (https://www.curseforge.com/minecraft/mc-mods/fakerlib), patchouli fabric (https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
2. launch game
3. crash 1 (no crash log)

### Logs

https://gist.github.com/YShadowMY/ecd1c2499d146b78b4eb49998469c3dd

**Comment by Matyrobbrt** [comment]
Apotheosis is a Forge mod, please use the Forge version. We do not provide support for (unofficial ports) from Forge to Fabric because a Forge version exists already and time is better spent working on fixing incompatibilities with actual Fabric mods.

**Comment by RoomAlex68** [comment]
Uh, actually the Forge version will crash when AdventureZ is present.

**Comment by YShadowMY** [comment]
thats the reazon why i posted, to see if it work with it

**Comment by RoomAlex68** [comment]
Yeah because what if someone wants to make modpack with Forge and Fabric mods but AdventureZ is not compatible with Apotheosis Forge. But the unofficial port for Fabric is compatible with AdventureZ.

**Comment by RoomAlex68** [comment]
https://github.com/Sinytra/Connector/issues/610
