### ISSUE TITLE
Bewitchment crash

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#765]
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment/files/all?page=1&pageSize=20

### Minecraft version

1.20.1

### Describe the bug

Game doesnt start

### Steps to reproduce

Install mod and dependencies and launch the game

### Logs

dev.log: https://gist.github.com/Tomat777/d1ca8a6c4c302b4185443212827200b5 

### Additional context

latest.log: https://gist.github.com/Tomat777/5d30ea02e1ea120dc723947a45600e54

**Comment by Su5eD** [comment]
Bewitchment works perfectly fine for me with the following mods on Forge 47.1.3. Make sure you are using the Forge version of Pehkui.

![image](https://github.com/Sinytra/Connector/assets/51261569/956ee660-999c-49e9-aa36-11a0b29c120d)

**Comment by EndangeredNayla** [comment]
Currently getting 

```Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method bewitchment$voodooDrownEffect(Lnet/minecraftforge/fluids/FluidType;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Z in bewitchment.mixins.json:poppet.LivingEntityMixin from mod bewitchment failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bewitchment-refmap.json```
