### ISSUE TITLE
Pehkui crash Beta 34

### ISSUE THREAD

**Issue by Learwin** [Sinytra/Connector#766]
### Mod Name

pehkui

### Mod Homepage

https://modrinth.com/mod/pehkui/version/3.7.12+1.14.4-1.20.4

### Minecraft version

1.20.1

### Describe the bug

The game crashes

### Steps to reproduce
Install these mods and try to boot the game.

Connector beta34
fabric-api-0.91.0+1.10.4+1.20.1
Pehkui-3.7.12+1.14.4-1.20.4

### Logs
debug.log
https://gist.github.com/Learwin/bf98d512f470897ae8905042f57446be

latest.log
https://gist.github.com/Learwin/79d1a19ac55586ca229a1f233985ea4b

console.log
https://gist.github.com/Learwin/9d5f9ae9faf90ab36f209dc65931fd66

**Comment by Su5eD** [comment]
Use the Forge version of Pehkui
