### ISSUE TITLE
Crash with BedrockIfy

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#767]
### Mod Name

BedrockIfy

### Mod Homepage

https://modrinth.com/mod/bedrockify

### Minecraft version

1.20.1

### Describe the bug

Crash

### Steps to reproduce

1. Launch Sinytra with BedrockIfy
2. Crash

### Logs

https://mclo.gs/f1gNWjz

**Comment by Matyrobbrt** [comment]
I am unable to reproduce this.

**Comment by murao-kun** [comment]
Just tested and got same result. https://mclo.gs/Ow79Nrs

**Comment by Its-Just-Luci** [comment]
also got the same results, crazy because bedrockify _works_ on connector 29 at the very least

**Comment by Its-Just-Luci** [comment]
updating to 1.9.1 seems to have fixed the issue on my end... @murao-kun @Lolothepro pinging y'all since y'all had the same issue.

**Comment by Su5eD** [comment]
Confirmed to work on Connector beta 35 and Forge 47.1.3. Note that newer Forge versions are not targeted by adapter patches and may cause issues.
