### ISSUE TITLE
TerraFirmaCraft open inventory crash - fabric-item-group-api

### ISSUE THREAD

**Issue by Akoto090** [Sinytra/Connector#768]
### Mod Name

TerraFirmaCraft

### Mod Homepage

https://github.com/TerraFirmaCraft/TerraFirmaCraft

### Minecraft version

1.20.1

### Describe the bug

Open the inventory with clicking "e" in a singleplayer world crashes with a error message. the game

### Steps to reproduce

1. Install [TerraFirmaCraft](https://www.curseforge.com/minecraft/mc-mods/terrafirmacraft/files/5044308)
2. Install [Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/files/5057104)
4. Create a world
3. Open the Inventory in a singleplayer world

### Logs

https://gist.github.com/Akoto090/b0dfdadef4ded32cbef82612af472273

### Additional context

I also tried it on forge, same crash report
If you are trying to use Neoforge, change the dependencies in the mods.toml in TerraFirmaCraft
Version range must be: versionRange = "[47.1.3,47.1.6),[47.1.96],[47.2.6,)"
If you are to busy use [this](https://workupload.com/file/HzhwBtyVkUG) TFC build

**Comment by Su5eD** [comment]
I tested this on both Forge 47.1.3 and NeoForge 47.1.96 but couldn't reproduce the issue. Does it occur constantly?

**Comment by Akoto090** [comment]
Sorry, I think it was a user error.
I renamed the forgiefied fabric api from "jar" to "disabled" one time and I think this corrupted the jar for some reason, also after I renamed it again, that it crashed while opening the inv (for some reason)
I now installed a new forgiefied fabric api on a new profile and it works.
Im so sorry if I wasted your time, I tried everything before and really thought it was just an error

**Comment by Akoto090** [comment]
False report, im sorry
