### ISSUE TITLE
Crash with bewitchment 

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#769]
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Minecraft version

1.20.1

### Describe the bug

Crash when going into survival mode.

### Steps to reproduce

Install mod
Go in survival mod(or create new survival world)

### Logs

https://gist.github.com/Tomat777/a132760a181994addcd000d925dda30b

**Comment by YShadowMY** [comment]
note: only crashes on forge 47.1.6 and newer

**Comment by Tomat777** [comment]
> note: only crashes on forge 47.1.6 and newer

no this issue not related to crashes on newer forge

**Comment by Su5eD** [comment]
Duplicate of #765

**Comment by Tomat777** [comment]
Its about different bug, or its like the same cause?
