### ISSUE TITLE
Modern Industrialization crash

### ISSUE THREAD

**Issue by Abbie5** [Sinytra/Connector#77]
### Mod Name

Modern Industrialization

### Mod Homepage

https://modrinth.com/mod/modern-industrialization

### Describe the bug

crash upon startup

### Logs

https://0x0.st/HL0d.txt

### Additional context

Modern Industrialization 1.7.0-beta
Cloth Config 11.1.106
Connector 1.0.0-beta.7+1.20.1 (error also occurs on beta.6)
FFAPI 0.87.0+1.9.4+1.20.1

**Comment by ArrowAced** [comment]
Was going to report this exact issue but for the Blåhaj mod

**Comment by Su5eD** [comment]
Fixed the version crashes, as well as a fluid render handler issue that crashed MI.

However, MI might still contain some bugs from upstream that occur on fabric. For example, I got a crash when attempting to attach a pump onto a fluid pipe. Reported that to MI, too.
