### ISSUE TITLE
Connector *34* causes my modpack to crash, while Connector 29 did not

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#772]
### Minecraft version

1.20.1

### Describe the bug

The same as the last issue I made, except slightly more annoyed

### Steps to reproduce

1. Install Connector, that's it :)

### Logs

https://gist.github.com/Its-Just-Luci/4aad6d8f480cfb12837cb0a4ebf21442

### Additional context

No missing dependencies are present in the log file this time.

**Comment by Su5eD** [comment]
Plead read the issue template more carefully.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by Its-Just-Luci** [comment]
awesome, will do expect another issue report imminently.
