### ISSUE TITLE
Crash with owo lib

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#779]
### Mod Name

owo-lib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/owo-lib/files/all?page=1&pageSize=20&version=1.20.1

### Minecraft version

1.20.1

### Describe the bug

Start up crash

### Steps to reproduce

1.Install mods
2.Launch minecraft

### Logs

https://gist.github.com/Tomat777/0d8a743a1660b3e53c3386e1019ebf7d

### Additional context

Beta 34 worked fine. Crashes on both 47.2.20 and 47.1.3.

**Comment by GreatKingKeenan** [comment]
Having similar crash. Also, posted in the support channel on Discord. Here is my log:
[latest.log](https://github.com/Sinytra/Connector/files/14074233/latest.log)

**Comment by Liamgrayskull** [comment]
Crash replicatable here as well

**Comment by VladisCrafter** [comment]
Confirmed crash, same error as provided here.

**Comment by Whitebrim** [comment]
+

**Comment by kakashi1464** [comment]
s∞n
