### ISSUE TITLE
Spectrum startup crash due to Reach Entity Attributes

### ISSUE THREAD

**Issue by soleilan** [Sinytra/Connector#780]
### Mod Name

Spectrum

### Mod Homepage

https://modrinth.com/mod/spectrum

### Minecraft version

1.20.1

### Describe the bug

Game crashes on startup

### Steps to reproduce

1. Run with Connector + Spectrum
2. Crash
3. Cry
...

### Logs

https://mclo.gs/Jj3kRgz

### Additional context

Adding Connector Extras fixes the startup crash.

**Comment by soleilan** [comment]
https://github.com/DaFuqs/Spectrum/issues/329

**Comment by Matyrobbrt** [comment]
Please install Connector Extras. Additionally, please do **not** report issues to Fabric mod authors when using Connector, it's not their job to ensure compatibility with Forge.
