### ISSUE TITLE
ULTRACRAFT + Connecter extras Crash

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#784]
### Mod Name

ULTRACRAFT

### Mod Homepage

https://modrinth.com/mod/absolute-ultracraft

### Minecraft version

1.20.1

### Describe the bug

crash on startup

### Steps to reproduce

1.download mod
2.start game
3.crashes
...

### Logs

https://gist.github.com/xg787/6416cfa853d7c8ee5543540adfc13af6

### Additional context

using beta 35 + extras

**Comment by Su5eD** [comment]
Fixed in https://github.com/Sinytra/ConnectorExtras/commit/5b22b019f3027067e8f0771ba7f7cf542b659296
