### ISSUE TITLE
Modern Industrialization error loading

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#79]
### Mod Name

Modern Industrialization

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

### Describe the bug

show a error at the start

### Steps to reproduce

1. Run the game
2. Wait
3. See

### Logs

https://pastebin.com/N3C6PsN6

### Additional context

![image](https://github.com/Sinytra/Connector/assets/59367621/36242c0a-d307-4466-b8c2-f569b8cbd061)

**Comment by Su5eD** [comment]
This has been reported and resolved in issue #77. The fix will be available in the next release.
