### ISSUE TITLE
Seedcracker X and clientcommands

### ISSUE THREAD

**Issue by ValbombCZ** [Sinytra/Connector#792]
### Mod Name

Seedcracker X and clientcommands

### Mod Homepage

https://github.com/19MisterX98/SeedcrackerX?tab=readme-ov-file   https://modrinth.com/mod/client-commands/version/2.8.5

### Minecraft version

1.20.1

### Describe the bug

Crash on start up/bootstrap

### Steps to reproduce

**1.** Add Seedcracker X and/or clientcommands 2.8.5
**2.** Start with Connector 1.0.0-beta.35+1.20.1 and ffapi 0.91.0+1.10.8+1.20.1
**3.** Crash

### Logs

https://mclo.gs/DhDCDEs

### Additional context

Fabric API needed for clientcommands.

**Comment by Su5eD** [comment]
Duplicate of #441
