### ISSUE TITLE
Tinkerer's Smithing: Forge replaces ingots with tags in recipes, but not in repair ingredients.

### ISSUE THREAD

**Issue by sisby-folk** [Sinytra/Connector#793]
### Mod Name

Tinkerer's Smithing

### Mod Homepage

https://modrinth.com/mod/tinkerers-smithing

### Minecraft version

1.20.1

### Describe the bug

Tinkerer's Smithing is missing recipes on 2.6+ due to forge ingot tag replacement

### Steps to reproduce

1. Launch tinkerer's smithing 2.6.6 with connector beta 35 and forgified fabric api 0.91.0+1.10.8
2. Observed logged number of units costs created recipes is lower than on fabric, as some weren't found.

### Logs

https://mclo.gs/UED9ZnL (deliberate debug output to show the discrepancies)

### Additional context

Tinkerer's Smithing relies on matching repair ingredients from tool and armor materials to the ingredients in crafting recipes in order to determine the "cost" of a piece of equipment (e.g. a pickaxe costing "3" repair material).

Forge replaces, for example, `{"item":"minecraft:gold_ingot"}` with `{"tag":"forge:ingots/gold"}` in crafting recipes, but doesn't do the same thing for tool/armor material ingredients. 

This creates an unfixable mismatch for tinkerer's smithing - which runs before tags are actually loaded, and therefore can't access the contents of the forge tags to confirm they match the repair ingredient - it just serializes ingredients to json to match them instead.

A possible workaround would be to just keep a big hardcoded lookup table for common tag replacements, but I figured we'd file it.

tracked here: https://github.com/sisby-folk/tinkerers-smithing/issues/31

**Comment by sisby-folk** [comment]
Worked around using the aforementioned lookup table for now, so, low prio, but worth noting anyway.

**Comment by Su5eD** [comment]
From what I understand, changing the material repair ingredients to use forge tags should eliminate the issue as the serialized JSON would be the same, right? My only concern with that approach is compatibility with Forge mods that might get affected by it.

**Comment by sisby-folk** [comment]
Changing the material repair ingredients to use forge tags should eliminate the issue, and I personally think it makes logical consistency sense for forge or neo to do so (why allow stuff in the iron ingots tag to craft a pickaxe, but not to repair one?), but whether it makes sense for connector to do so I'm less certain.

**Comment by Su5eD** [comment]
I recommend proposing this to NeoForge, given they're the ones replacing vanilla tag usages. I'd rather not make a behavioral change in Connector as it could lead to unintended side effects.
