### ISSUE TITLE
Andromeda broke with beta 35+

### ISSUE THREAD

**Issue by melontini** [Sinytra/Connector#794]
### Mod Name

Andromeda

### Mod Homepage

https://github.com/melontini/andromeda

### Minecraft version

1.20.1

### Describe the bug

Crash due to Adapter patches not applying (?)

### Steps to reproduce

1. Launch the game with `items.infinite_totem` or `world.quick_fire` enabled in Andromeda's config
2. Mixin can't locate injection targets.

### Logs

`items.infinite_totem`: https://mclo.gs/RG6Xon1

### Additional context

Confirmed with this build https://github.com/Sinytra/Connector/actions/runs/7716373181

**Comment by melontini** [comment]
Doesn't look like beta 36 fixed the issue.

**Comment by melontini** [comment]
Seems like 1.8.0 is broken on all Connector versions.

**Comment by melontini** [comment]
It's not "seems". Some time ago, connector stopped piping every class to the mixin transformer, and since Andromeda generates its mixin configs at runtime, no patches are applied. 😛

**Comment by melontini** [comment]
> so thats why my modpack was crashing after updating connector... glad this is being checked

This should only affect modpacks with Andromeda (all 3 of them), but even then, Andromeda will disable the module if some mixin fails to apply. This also only affects `world/quick_fire` and `items/infinite_totem`.

If you're trying to run AM without those modules, then the issue is in something else.

**Comment by Su5eD** [comment]
You're right, I just piped everything through the mixin patch transformer and Andromeda worked again, lol. Sorry about this stupid issue, fixing it right now.
