### ISSUE TITLE
Connector is unable to handle refmapless mixins

### ISSUE THREAD

**Issue by melontini** [Sinytra/Connector#795]
### Minecraft version

1.20.1

### Describe the bug

Same as title.

### Steps to reproduce

I'm honestly not sure what to put here. 

### Additional context

Loom 1.5 introduced support for Tiny Remapper's Mixin extension, which remaps mixin classes in-place instead of using a refmap. It looks like Connector only remaps hard targets like `@Shadow`. 

> I wonder how in-place remapping will affect load times.

**Comment by Matyrobbrt** [comment]
Considering that the refmap contained FQN and was much easier to remap, this will be... interesting.

**Comment by melontini** [comment]
What about using Tiny Remapper directly? It works in the NeoForge → Fabric direction, although it requires the game jar to be remapped to source mappings.

**Comment by Su5eD** [comment]
What mod / class can be used to test this?

**Comment by melontini** [comment]
I've built a version of Andromeda a bit ago https://github.com/melontini/andromeda/actions/runs/7722779071

**Comment by sakurawald** [comment]
> What mod / class can be used to test this?

How about this example ?
https://github.com/Sinytra/Connector/issues/1439
