### ISSUE TITLE
Revidium incompatability

### ISSUE THREAD

**Issue by nekohacker591** [Sinytra/Connector#798]
### Mod Name

Revidium

### Mod Homepage

https://github.com/TavstalDev/Revidium

### Minecraft version

1.20.1

### Describe the bug

fatal crash via noref mixin error

### Steps to reproduce

1. build the mod
2. drop it in the mods folder
3. start the game
4. crash

### Logs

https://paste.ubuntu.com/p/bwX8r2wqFR/

### Additional context

build command used was "bash gradlew build"

**Comment by Xplodin** [comment]
normal nvidium works with connector. I added it to my modpack and it worked well

**Comment by Su5eD** [comment]
What is the difference between this and Nvidium? If you're looking for a Forge port, try out [ascendium](https://github.com/ferriarnus/acedium).
