### ISSUE TITLE
Mod IDs that are java keywords cause crashes on mod resolution.

### ISSUE THREAD

**Issue by mineblock11** [Sinytra/Connector#80]
### Describe the bug

If a mod's ID is exactly the same as a java keyword, eg: `break` or `continue` or `public` - the game crashes. An example of this is the Continue Button mod, https://modrinth.com/mod/continue.

### Steps to reproduce

1. Install the Continue Button mod, https://modrinth.com/mod/continue, which has the mod ID of `continue`.
2. This is a java keyword, so it crashes.

### Logs

N/A

### Additional context

Potential workaround, either check if the mod id is a java keyword and modify it, or add support for mod IDs that are java keywords.

For reference, all the keywords:

abstract
continue
for
new
switch
assert
default
goto
package
synchronized
boolean
do
if
private
this
break
double
implements
protected
throw
byte
else
import
public
throws
case
enum
instanceof
return
transient
catch
extends
int
short
try
char
final
interface
static
void
class
finally
long
strictfp
volatile
const
float
native
super
while

**Comment by Su5eD** [comment]
Fixed in a5ce10729d25b50b1810759f04617bb116e8400d
