### ISSUE TITLE
Crash with Voidscape And Sintra Connector

### ISSUE THREAD

**Issue by morgatronday1234** [Sinytra/Connector#800]
### Mod Name

voidscape

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/voidscape

### Minecraft version

1.20.1

### Describe the bug

Running void scape with sintra crash's

### Steps to reproduce

1.install Sintra Connector
2.install Forgified Fabric API
3.install Voidscape
4.run instant
5.crash

### Logs

https://gist.githubusercontent.com/morgatronday1234/213731d901df2c05e25a92e977aaa177/raw/6f5f05a9a486a6d7b19f334e5075888da57a830c/gistfile1.txt

**Comment by Su5eD** [comment]
Connector is not compatible with Minecraft 1.20.2.
