### ISSUE TITLE
Crash with Trinkets, Simply Skills

### ISSUE THREAD

**Issue by nthxny** [Sinytra/Connector#802]
### Mod Name

Trinkets

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/trinkets/files/all?page=1&pageSize=20&version=1.20.1

### Minecraft version

1.20.1

### Describe the bug

Fails to find reference to trinkets, crash immediately

### Steps to reproduce

no idea, but I was trying to install Simply Skills and its dependencies, and it dont work

### Logs

https://gist.github.com/nthxny/995f65a9f8d5f4fe8600e95baf555299

**Comment by Su5eD** [comment]
Plead read the issue template more carefully.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
