### ISSUE TITLE
Crashed with cardinal-components

### ISSUE THREAD

**Issue by liangmoe** [Sinytra/Connector#803]
### Mod Name

cardinal-components

### Mod Homepage

https://modrinth.com/mod/cardinal-components-api

### Minecraft version

1.20.1

### Describe the bug

included the cardinal-components, crashed

### Steps to reproduce

Game will succelly boot, but after entering a existing world, the game crashed immediately

### Logs

latestlog: https://mclo.gs/pR7Ci39

### Additional context

also crash report: https://mclo.gs/kkyeDb3

**Comment by liangmoe** [comment]
Issue also occured in beta.35, but beta.34 runs fine

**Comment by RoomAlex68** [comment]
It also happens when creating a new world

**Comment by RoomAlex68** [comment]
The mod still crashes on Connecter Beta 37

**Comment by liangmoe** [comment]
mine runs fine, maybe send your log?

**Comment by RoomAlex68** [comment]
It crashed when I was running Bosses of Mass Destruction for Fabric. Since the mod requires the Dependency "Cardinals Component"

**Comment by RoomAlex68** [comment]
It crashed when I was running Bosses of Mass Destruction for Fabric. Since the mod requires the Dependency "Cardinals Component"
