### ISSUE TITLE
Eden Ring Reforked crash on server

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#804]
### Mod Name

Eden Ring Reforked

### Mod Homepage

https://modrinth.com/mod/eden-ring-reforked/version/0.6.5-1.20.1

### Minecraft version

1.20.1

### Describe the bug

Eden Ring Reforked crashed server

### Steps to reproduce

having this problem on server start up, when i use this mod, i seems cannot boots up my server, can you please check on that?

### Logs

https://pastebin.com/GFfMH4yq

**Comment by Su5eD** [comment]
This also occurs on a regular Fabric server. Please report the issue to the mod's author.

>```
>java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'edenring'!
>        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
>        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
>        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
>        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
>        at net.minecraft.server.Main.main(Main.java:112)
>        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
>        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
>        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
>        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
>Caused by: java.lang.NoSuchFieldError: CLIENT_CONFIG
>        at paulevs.edenring.config.Configs.<clinit>(Configs.java:20)
>        at paulevs.edenring.registries.EdenItems.<clinit>(EdenItems.java:13)
>        at paulevs.edenring.registries.EdenBlocks.<clinit>(EdenBlocks.java:48)
>        at paulevs.edenring.EdenRing.onInitialize(EdenRing.java:49)
>        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
>        ... 6 more
>```

**Comment by RoomAlex68** [comment]
Eden Ring Beta 7 incompatible with connector beta 36

**Comment by Poopooracoocoo** [comment]
@RoomAlex68 Are you able to reproduce this with Eden Ring Reforked 0.6.13? Or with 0.7.0- beta.4?

**Comment by RoomAlex68** [comment]
Just Eden Ring Reforked Beta 7

**Comment by Poopooracoocoo** [comment]
Are you sure it's the same crash as this and that you don't see the issue on Fabric?

**Comment by RoomAlex68** [comment]
I had to downgrade to Eden Ring Reforked 0.6.13 to use the mod on Connector Beta 36

**Comment by RoomAlex68** [comment]
Eden Ring Reforked 0.7.0 crashes on Connector Beta 36 when trying to create a new world
