### ISSUE TITLE
Chunks fade in crash on world loading with latest embeddium and oculus

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#805]
### Mod Name

Chunks fade in

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/chunks-fade-in

### Minecraft version

1.20.1

### Describe the bug

Chunks fade in crash on world loading with latest embeddium and oculus

### Steps to reproduce

Install mods 
Load world

### Logs

https://gist.github.com/Tomat777/6f0f179a06daf88902c7edfb098506d7
crash: https://gist.github.com/Tomat777/8c664a11f9053b1f142fd0eb75dc0a85

### Additional context

I am not sure whos causing this issue but on fabric CFI works fine with Sodium 0.5.8 and iris 1.6.5 and embeddium 0.31 and oculus 1.65 should be their forge counterpart

**Comment by Its-Just-Luci** [comment]
Ditto

**Comment by kakashi1464** [comment]
In chunks fade in edit fabric.mod.json
Remove sodium in dependencies

**Comment by Su5eD** [comment]
This is a conflict between Chunks fade in and Oculus, which tries to apply its Iris mixins. I tried to disable this integration using Connector's hidden mods config, but Chunks fade in uses [reflection](https://github.com/kerudion/chunksfadein/blob/63a71b0242de46137995a076e36cbe071e38f884/src/main/java/com/koteinik/chunksfadein/ChunkFadeInMixinConfig.java#L19) to determine whether Iris is present, so Connector's config has no effect on it.

Sorry, this is out of our control. Your best bet in this case is disabling Oculus.
