### ISSUE TITLE
Voidscape Startup Crash

### ISSUE THREAD

**Issue by ChapperNi** [Sinytra/Connector#812]
### Mod Name

Voidscape

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/voidscape

### Minecraft version

1.20.1

### Describe the bug

Starting with connector and Voidscape crashes

### Steps to reproduce

1. Have voidscape and connector installed
2. Crash on startup

### Logs

https://gist.github.com/ChapperNi/28b5f94877349c631cca86246222624f

**Comment by Xplodin** [comment]
been using voidscape on beta 33 pretty well
