### ISSUE TITLE
connected textures don't work

### ISSUE THREAD

**Issue by T3rryScary357** [Sinytra/Connector#814]
### Mod Name

Sinytra Connector

### Mod Homepage

https://github.com/Sinytra/Connector

### Minecraft version

1.20.1

### Describe the bug

textures are not connecting

### Steps to reproduce

1.instal forge 47.2.20
2.Chisel Reborn-1.6
3.Oculus-mc1.20-1.6.4 and Rubid
<img width="1133" alt="image" src="https://github.com/Sinytra/Connector/assets/158995981/92094b93-cf71-4d31-a55a-7ba165d6b27b">
ium-0.6.5

### Logs

no crash

**Comment by Su5eD** [comment]
Please replace rubidium with [Embeddium](https://modrinth.com/mod/embeddium), then install [Lazurite](https://modrinth.com/mod/lazurite). Connected textures will work as expected.

![2024-02-07_09 46 41](https://github.com/Sinytra/Connector/assets/51261569/37fd714f-661f-480f-b660-fec55cdd955e)

**Comment by T3rryScary357** [comment]
> Please replace rubidium with [Embeddium](https://modrinth.com/mod/embeddium), then install [Lazurite](https://modrinth.com/mod/lazurite). Connected textures will work as expected.
> 
> ![2024-02-07_09 46 41](https://private-user-images.githubusercontent.com/51261569/302915575-37fd714f-661f-480f-b660-fec55cdd955e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjA0MTcsIm5iZiI6MTcwNzQyMDExNywicGF0aCI6Ii81MTI2MTU2OS8zMDI5MTU1NzUtMzdmZDcxNGYtNjYxZi00ODBmLWI2NjAtZmVjNTVjZGQ5NTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE5MjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjA3NzY3NzBmZmY5YWFjNTExNjExMjQ1ZTVhMzUzZTViYjAwZTY2ZTE2N2I5NjE2ZThjNmZkNWYxZjU5OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8B6Nnrc4OS8dKwLOTlZii-Jv0uEV4tDCwoiDEPU0-ro)

Thank you, you help a lot. I was able to get it to work with your help. However I did encounter a crash with the up to date mods. Maybe because of the version of forge (47.2.20) I was using or perhaps the java version (17.0.8). Regardless it's working with slightly older version of Oculus, Embeddium and Lazurite.
