### ISSUE TITLE
Missing capability for UUID after using Immersive portals mod nether portal - kick from the server 

### ISSUE THREAD

**Issue by luk4k0** [Sinytra/Connector#816]
### Mod Name

Immersive Portals (Luckperms?) 

### Mod Homepage

https://modrinth.com/mod/immersiveportals 

### Minecraft version

1.20.1

### Describe the bug

After I use nether portal for once with Immersive Portals mod, any command, or typing into the chat causes kick from the server with error missing capability for my UUID. After reconnection it works again until I use the portal again. When I delete Luckperms from the server, the problem stops. Server log doesn't show much, it is in the end of the log:

### Steps to reproduce

Reproduction Steps:

Connect to the server.
Type anything in the chat - works fine.
Go through the nether portal (Immersive portals) to the nether (or vice-versa)
Again type anything in the chat ---> kicked out of the server

Actually, when I type a command, /tp , /spawn etc. it does nothing and its like ignored, like a ping lag, when I type message into to the chat, it kicks me out..

### Logs

https://gist.github.com/luk4k0/7cd3dd57dfbc45ac1ef9b6eeb6f42e49

### Additional context

Potentially, this issue is somehow related to: https://github.com/Sinytra/Connector/issues/564 since I also experienced that the issue with Curios and Immersive portals. (for now it seems switching from Curios to Trinkets could potentially solve the problem) 

I have also reported the issue on Luckperms and Immersive portals github.

Thank you.

**Comment by Su5eD** [comment]
Merging this into #564 as they indeed appear to be the same issue related to switching dimensions and networking.
