### ISSUE TITLE
suggestion support quilt since its like frabric too.

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#817]
### Minecraft version

1.20.1

### Describe the bug

support quilt theres no other place to make a suggestiomn

### Steps to reproduce

1.
2.
3.
...
idk

**Comment by RoomAlex68** [comment]
https://github.com/Sinytra/Connector/discussions/119

**Comment by RoomAlex68** [comment]
It could be possible on 1.20.4 since Sinytra Connector is porting to NeoForge 1.20.4 and beyond. So they could make a QSL Forgified API for NeoForge 1.20.4 as a beta. But hey it's there choice.
