### ISSUE TITLE
Redstone Wires/Libmultipart incompatible

### ISSUE THREAD

**Issue by Fuyukai** [Sinytra/Connector#818]
### Mod Name

Redstone Wires

### Mod Homepage

https://modrinth.com/mod/wiredredstone

### Minecraft version

1.20.1

### Describe the bug

Crashes upon launch with Mixin failure to ClientPlayerInteractionManager#breakBlock.

### Logs

Crash log: https://gist.github.com/Fuyukai/84bfb41d982bb71bfbf98fd8f515f0dd
Debug log: https://gist.github.com/Fuyukai/f963b331871da6ad5bc2ea620ce609f1

**Comment by Su5eD** [comment]
Confirmed to work on Connector beta 40
