### ISSUE TITLE
[BUG] Weird rendering bug occurred using ForgeCIT

### ISSUE THREAD

**Issue by Ryuushen** [Sinytra/Connector#820]
### Minecraft version

1.20.1

### Describe the bug

Forge CIT breaks textures / CIT Resewn doesn't do anything

### Steps to reproduce

1. Install Forge CIT in any mod pack with connect and it will break texture when there are more than 240 Mods installed.
2. Install Resewn CIT in the same mod pack and disable ForgeCIT, now the texture is normal but CIT doesn't work
...

### Additional context

Very weird issue, I have 2 modpacks that I tested with this. 
1st modpack, 240 mods, with Forge CIT, **ANYTHING** after 240 mods will break the textures.
-> This is to test the limitation of numbers of mods before the texture breaks
![Forge CIT](https://github.com/Sinytra/Connector/assets/24853902/050fc119-d071-4739-8e08-543cd12c68e5)

2st modpack, 305 mods, with CIT Resewn, works perfectly but CIT Resewn will not render item as it supposed to be. And the moment I swapped CIT Resewn for Forge CIT resewn it will break the texture like the images. Using [nongko-3d-weapons](https://www.curseforge.com/minecraft/texture-packs/nongko-3d-weapons)
-> Main modpack that I want to use
![CIT Resewn](https://github.com/Sinytra/Connector/assets/24853902/57e6de57-94ad-4ee7-abc9-21fed4bdde80)

**Comment by Su5eD** [comment]
What are the exact mods required to reproduce this?

**Comment by RoomAlex68** [comment]
Include a crash log

**Comment by Ryuushen** [comment]
> What are the exact mods required to reproduce this?

Here is mod list: https://mclo.gs/elbyUlx
If you want a mod pack I can send the curseforge zipfile



> Include a crash log

It's not crashing, it loads fine.
It's just the texture is broken when used Forge CIT and CIT Resewn (Fabric) doesn't do anything.

**Comment by RoomAlex68** [comment]
Then you can send the latest Log

**Comment by Ryuushen** [comment]
> Then you can send the latest Log
Sure
This log is for when everything works fine (240 Mods)
[with forge cit 240 mods.log](https://github.com/Sinytra/Connector/files/14217500/with.forge.cit.240.mods.log)

This log is for when the texture broke after installing 1 extra mod
[with forge cit 241 mods.log](https://github.com/Sinytra/Connector/files/14217501/with.forge.cit.241.mods.log)

**Comment by UltimatChamp** [comment]
Yup, also facing the same issue.
I'm pretty sure that CIT worked before, perfectly, with a previous Connector release.

**Comment by Ryuushen** [comment]
> Yup, also facing the same issue. I'm pretty sure that CIT worked before, perfectly, with a previous Connector release.

From what i do to fix it is that certain resources pack is incompatible (For my case it's Ghoulcraft and Mizunos). If you have modernfix then turn on Dynamic Resources and remove Better Archeology if you have that

**Comment by UltimatChamp** [comment]
> From what i do to fix it is that certain resources pack is incompatible (For my case it's Ghoulcraft and Mizunos). If you have modernfix then turn on Dynamic Resources and remove Better Archeology if you have that

I don't think it fixes CIT Resewn, though🤔.

**Comment by Ryuushen** [comment]
> > From what i do to fix it is that certain resources pack is incompatible (For my case it's Ghoulcraft and Mizunos). If you have modernfix then turn on Dynamic Resources and remove Better Archeology if you have that
> 
> I don't think it fixes CIT Resewn, though🤔.
> 
> EDIT: Hmm.. Works only with ForgeCIT... Thanks, though💖!

yeah nah CIT Resewn just doesn't work at all in general for me

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
