### ISSUE TITLE
Clientside particle mod works correctly in singleplayer, but breaks when connected to a server.

### ISSUE THREAD

**Issue by Billnotic** [Sinytra/Connector#821]
### Mod Name

Wakes

### Mod Homepage

https://modrinth.com/mod/wakes

### Minecraft version

1.20.1

### Describe the bug

When in singleplayer, the wakes (not splashes or other particles) generate correctly. However, when connected to a server (mod is clientside and is not on the server, however the issue occurs regardless of if it is in the server modlist or not) creating a wake (by moving along water, mobs and other entities can create wakes too) will crash the game.

### Steps to reproduce

1. Install Sinytra and Wakes mod 0.2.2 (occurs in 0.2.3 as well, but 0.2.3 has a rendering bug)
2. Create a server with necessary mods.
3. Join server and move along the surface of water to generate a wake.
...

### Logs

https://pastebin.com/R87q0ScY

### Additional context

The server never crashes because of this. The crash is entirely clientside, and can be fixed by disabling the wake generation portion of this mod.

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

I've tested wakes on a local server with all mods only installed on the client side, and it worked perfectly fine.

![2024-02-10_18 55 11](https://github.com/Sinytra/Connector/assets/51261569/b2d52e51-f6c7-4908-ad1b-c09be597cdf5)
