### ISSUE TITLE
net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'client' due to errors, provided by 'betterend'!

### ISSUE THREAD

**Issue by prrhic** [Sinytra/Connector#823]
### Mod Name

BetterEnd 1.20.1

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1

### Describe the bug

I have BetterEnd fabric 1.20.1 mod installed and it keep crashing, I couldn't figure out what's the problem

### Steps to reproduce

1. Installs BetterEnd
2. Launches
3. Crashes

### Logs

crash log: https://pastebin.com/RHXwicW0
debug log: https://gist.github.com/prrhic/135fa62aaeffcc960058f38173941466

### Additional context

Couldn't figure out what causes the crash myself

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by prrhic** [comment]
> Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.
> 
> > Before reporting, please ensure that:
> > 
> > * You've installed a **minimal set of mods** required to reproduce the issue.
> >   Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
> >   Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
> >   If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
> >   repeatedly until the faulty mod is found.

nvm i found the solution. Turns out it was the oculus mod, it happens when i update the oculus mod the latest version
