### ISSUE TITLE
Fabric farmers delight crash (only Fabric FD is installed on the instance)

### ISSUE THREAD

**Issue by mateus3c** [Sinytra/Connector#827]
### Mod Name

Farmer's Delight

### Mod Homepage

https://modrinth.com/mod/farmers-delight-fabric

### Minecraft version

1.20.1

### Describe the bug

crashes before the mojang loading screen

### Steps to reproduce

1. Add connector, connector extras, ffapi and lazurite
2. Add Fabric Farmer's Delight
3. Click to play
4. Game crashes

### Logs

https://github.com/Sinytra/Connector/files/14229550/latest.log

### Additional context

I'm using the latest version of all the mods installed.

[latest.log](https://github.com/Sinytra/Connector/files/14229550/latest.log)
[latest - console.log](https://github.com/Sinytra/Connector/files/14229551/latest.-.console.log)

**Comment by mpustovoi** [comment]
Why would you need the Fabric version of Farmer's Delight?
This issue is more likely to be marked as invalid, since the recommendations indicate to use the original Forge version of any mod if it exists.

**Comment by RoomAlex68** [comment]
There are Farmer's Delight Fabric addons that are on 1.20 and they are not compatible with the Forge Farmer's Delight

**Comment by RoomAlex68** [comment]
https://github.com/Sinytra/Connector/issues/96
