### ISSUE TITLE
Crash due to the connector mod apparently

### ISSUE THREAD

**Issue by YunaDreamFR** [Sinytra/Connector#828]
### Mod Name

Connector

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

### Minecraft version

1.20.1

### Describe the bug

I crash without having no idea why

### Steps to reproduce

1.
2.
3.
...

### Logs

---- Minecraft Crash Report ---- // Who set us up the TNT?  Time: 2024-02-10 18:33:29 Description: Initializing game  org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {} 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {} 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading} 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:847) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:mixin,re:classloading,pl:mixin:APP:fpsreducer.json:RenderSystemMixin from mod fpsreducer,pl:mixin:APP:sodium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium,pl:mixin:A} 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:438) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.2.20.jar:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {} Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method setAdditionalWindowHints(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in sodium.mixins.json:core.WindowMixin from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	... 32 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {} 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {} 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:classloading} 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:847) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:mixin,re:classloading,pl:mixin:APP:fpsreducer.json:RenderSystemMixin from mod fpsreducer,pl:mixin:APP:sodium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium,pl:mixin:A} 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:438) ~[client-1.20.1-20230612.114412-srg.jar%23306!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} -- Initialization -- Details: 	Modules:  		ADVAPI32.dll:API avancées Windows 32:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		COMCTL32.dll:Bibliothèque de contrôles de l’expérience utilisateur:6.10 (WinBuild.160101.0800):Microsoft Corporation 		CRYPT32.dll:Crypto API32:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.3930:Microsoft Corporation 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.3636:Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		DEVOBJ.dll:Device Information Set DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		DNSAPI.dll:DNS DLL de l’API Client:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		GDI32.dll:GDI Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		GLU32.dll:DLL bibliothèque des utilitaires OpenGL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		IPHLPAPI.DLL:API de l’application d’assistance IP:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		KERNEL32.DLL:DLL du client API BASE Windows NT:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		KERNELBASE.dll:DLL du client API BASE Windows NT:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		MSASN1.dll:ASN.1 Runtime APIs:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		MSCTF.dll:DLL de MSCTF Server:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		MpOav.dll:IOfficeAntiVirus Module:4.18.23110.3 (9ebb3643d539a6fc4659898b1df3124d5da4c0a9):Microsoft Corporation 		NLAapi.dll:Network Location Awareness 2:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		Ole32.dll:Microsoft OLE pour Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		POWRPROF.dll:DLL d’assistance du profil d’alimentation:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		PROPSYS.dll:Système de propriétés Microsoft:7.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		RPCRT4.dll:Runtime d’appel de procédure distante:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		SETUPAPI.dll:Installation de L’API Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		SHCORE.dll:SHCORE:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		SHELL32.dll:DLL commune du shell Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		UMPDC.dll 		USER32.dll:DLL client de l’API uilisateur de Windows multi-utilisateurs:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		USERENV.dll:Userenv:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		WINHTTP.dll:Services HTTP Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		WINMM.dll:DLL API MCI:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.19041.3930 (WinBuild.160101.0800):Microsoft Corporation 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		Wldp.dll:Stratégie de verrouillage Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		amdihk64.dll:Radeon Settings: Host Service:2,00,00,1788:Advanced Micro Devices, Inc. 		amsi.dll:Anti-Malware Scan Interface:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		atig6pxx.dll:atiglpxx.dll:8.14.01.6564:Advanced Micro Devices, Inc.  		atio6axx.dll:AMD OpenGL Driver:23.08.230531_53c0013:Advanced Micro Devices, Inc 		bcrypt.dll:Bibliothèque de primitives de chiffrement Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		cfgmgr32.dll:Configuration Manager DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation 		combase.dll:Microsoft COM pour Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc.DLL:Service client DHCP:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc6.DLL:Client DHCPv6:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		dinput8.dll:Microsoft DirectInput:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		dwmapi.dll:API du Gestionnaire de fenêtres du Bureau Microsoft:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		fwpuclnt.dll:API en mode utilisateur FWP/IPsec:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		gdi32full.dll:GDI Client DLL:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation 		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW 		inputhost.dll:InputHost:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft 		jemalloc.dll 		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jna12473089280915068290.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA) 		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft 		kernel.appcore.dll:AppModel API Host:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation 		lwjgl.dll 		lwjgl_opengl.dll 		lwjgl_stb.dll 		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		mdnsNSP.dll:Bonjour Namespace Provider:3,0,0,10:Apple Inc. 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		mswsock.dll:Fournisseur de service Sockets 2.0 de Microsoft Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		napinsp.dll:Fournisseur Shim d’affectation de noms de messagerie:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		ncrypt.dll:Routeur Windows NCrypt:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		ntdll.dll:DLL Couche NT:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		ntmarta.dll:Fournisseur MARTA Windows NT:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		opengl32.dll:OpenGL Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		pdh.dll:DLL d’application d’assistance Windows pour les données de performance:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		perfos.dll:DLL d’objets Performances système Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		perfproc.dll:DLL d’objets Performances de processus système Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		pnrpnsp.dll:Fournisseur d’espace de noms PNRP:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		profapi.dll:User Profile Basic API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		shlwapi.dll:Bibliothèque d’utilitaires légers du Shell:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		uxtheme.dll:Bibliothèque de thèmes Ux Microsoft:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		win32u.dll:Win32u:10.0.19041.3930 (WinBuild.160101.0800):Microsoft Corporation 		windows.storage.dll:API de stockage Microsoft WinRT:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		wintypes.dll:DLL de types de base Windows:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation 		xinput1_4.dll:API du contrôleur commun Microsoft:10.0.19041.3691 (WinBuild.160101.0800):Microsoft Corporation 		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft Stacktrace: 	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.2.20.jar:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 597294328 bytes (569 MiB) / 1275068416 bytes (1216 MiB) up to 6442450944 bytes (6144 MiB) 	CPUs: 12 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 5 PRO 4650U with Radeon Graphics 	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1 	Microarchitecture: unknown 	Frequency (GHz): 2.10 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: AMD Radeon(TM) Graphics 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002) 	Graphics card #0 VRAM (MB): 2048.00 	Graphics card #0 deviceId: 0x1636 	Graphics card #0 versionInfo: DriverVersion=31.0.21024.5005 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 22392.41 	Virtual memory used (MB): 17926.84 	Swap memory total (MB): 8192.00 	Swap memory used (MB): 504.43 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Launched Version: 1.20.1-forge-47.2.20 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: Unknown 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	CPU: <unknown> 	Sinytra Connector: 1.0.0-beta.29+1.20.1 		SINYTRA CONNECTOR IS PRESENT! 		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker. 		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues. 		Installed Fabric mods: 		| ================================================== | ============================== | ============================== | ==================== | 		| FpsReducer2-fabric-1.20-2.5_mapped_srg_1.20.1.jar  | FPS Reducer                    | fpsreducer                     | 1.20-2.5             | 		| logical_zoom-0.0.20_mapped_srg_1.20.1.jar          | Logical Zoom                   | logical_zoom                   | 0.0.20               | 		| puffish_skills-0.11.2-1.20-fabric_mapped_srg_1.20. | Pufferfish's Skills            | puffish_skills                 | 0.11.2               | 		| fusion-1.0.6-fabric-mc1.20_mapped_srg_1.20.1.jar   | Fusion                         | fusion                         | 1.0.6                | 		| sodium-fabric-mc1.20.1-0.5.3_mapped_srg_1.20.1.jar | Sodium                         | sodium                         | 0.5.3                | 		| entityculling-fabric-1.6.2-mc1.20.1_mapped_srg_1.2 | EntityCulling-Fabric           | entityculling                  | 1.6.2-mc1.20.1       | 		| indium-1.0.27+mc1.20.1_mapped_srg_1.20.1.jar       | Indium                         | indium                         | 1.0.27mc1.20.1       |

### Additional context

The game simply keep crashing with Connector I don't know why (Either Connector Either forgified Fabric but it look like its more connector the reason)

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin

**Comment by YunaDreamFR** [comment]
Of course I have mod since connector mod is made for putting forge and fabric mod together. Plus at the end of the log it's clearly said "SINYTRA CONNECTOR IS PRESENT! Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker. Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues. Installed Fabric mods: | ================================================== | ============================== | ============================== | ==================== | | FpsReducer2-fabric-1.20-2.5_mapped_srg_1.20.1.jar | FPS Reducer | fpsreducer | 1.20-2.5 | | logical_zoom-0.0.20_mapped_srg_1.20.1.jar | Logical Zoom | logical_zoom | 0.0.20 | | puffish_skills-0.11.2-1.20-fabric_mapped_srg_1.20. | Pufferfish's Skills | puffish_skills | 0.11.2 | | fusion-1.0.6-fabric-mc1.20_mapped_srg_1.20.1.jar | Fusion | fusion | 1.0.6 | | sodium-fabric-mc1.20.1-0.5.3_mapped_srg_1.20.1.jar | Sodium | sodium | 0.5.3 | | entityculling-fabric-1.6.2-mc1.20.1_mapped_srg_1.2 | EntityCulling-Fabric | entityculling | 1.6.2-mc1.20.1 | | indium-1.0.27+mc1.20.1_mapped_srg_1.20.1.jar | Indium | indium | 1.0.27mc1.20.1 |"

AND the fabric mod right HERE is optimization mod (except pufferfish's skill but it result the same if its the forge version anyways.)

**Comment by RoomAlex68** [comment]
Sodium and Indium are not supported. There are Forge ports of them.
Embeddium and Lazurite so is use them instead
