### ISSUE TITLE
Incompatible with ImmediatelyFast mod

### ISSUE THREAD

**Issue by kakashi1464** [Sinytra/Connector#83]
### Mod Name

ImmediatelyFast

### Mod Homepage

https://modrinth.com/mod/immediatelyfast

### Describe the bug

Crashes with ImmediatelyFast

### Steps to reproduce

1.Add ImmediatelyFast with Connector and FFAPI
2.Run Minecraft

### Logs

https://mclo.gs/KdT2dW7 - latest log
https://mclo.gs/vcVO4mN - debug log

### Additional context

Crashes with no crash-report

**Comment by Su5eD** [comment]
ImmediatelyFast has just released an official [Forge port](https://modrinth.com/mod/immediatelyfast/version/1.2.0+1.20.1) which works on Connector. This eliminates the need to run the fabric version, thus resolving the issue.
