### ISSUE TITLE
TieredZ Fabric mod crash

### ISSUE THREAD

**Issue by pietrascoelho** [Sinytra/Connector#830]
### Mod Name

TieredZ

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/tieredz

### Minecraft version

1.20.1

### Describe the bug

Crash during earlyload of Minecraft

### Steps to reproduce

1. Install all dependencies: AuthTag, ClothConfig (no matter forge or fabric), LibZ
2. Install TieredZ
3. Boot the title
4. Notice that the Minecraft crashes
...

### Logs

https://pastebin.com/PRpMk1LL

### Additional context

All depedency mods without TieredZ are working fine.

Forge "version" is not the same, though can't be used as replacament.

**Comment by pietrascoelho** [comment]
logs with fabric ClothConfig:
https://pastebin.com/Qm9mh24h

**Comment by RoomAlex68** [comment]
There is a Forge Port of it

**Comment by pietrascoelho** [comment]
> https://www.curseforge.com/minecraft/mc-mods/tiered-forge

This mod is significantly different. I mentioned it in the description

**Comment by Sazuzaki** [comment]
Can confirm. The forge port also crashes with curios and lacks reforging, so having this fixed would be great.
