### ISSUE TITLE
xaeros mini map crash

### ISSUE THREAD

**Issue by nekohacker591** [Sinytra/Connector#831]
### Mod Name

Xeraros worldmap

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map

### Minecraft version

1.20.1

### Describe the bug

crashs as a null pointer

### Steps to reproduce

1. add the conenctors mod xaeros world map and minimap
2. install connector mod
3. add any fabric mod doesnt matter what
...

### Logs

https://pastebin.com/raw/ChCQUy3L

### Additional context

this bug happens when ever i had a fabric mod doesn't matter what mod it is the forge mod Xaeros minimap will make conenctor crash with the same error every time 

this is for the forge version not teh fabric version

**Comment by Su5eD** [comment]
The mod works fine on my end alongside Techreborn, so it's hard to conclude "any fabric mod doesnt matter what" will cause this crash.

![2024-02-22_17 50 06](https://github.com/Sinytra/Connector/assets/51261569/f3269f7f-d92f-4638-bd77-dc083762c933)

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
