### ISSUE TITLE
Corrupted Create blocks' behavior on Replay recordings 

### ISSUE THREAD

**Issue by VladisCrafter** [Sinytra/Connector#833]
### Mod Name

Create, Replay mod, Create add-ons

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/create, https://www.curseforge.com/minecraft/mc-mods/replay-mod-fabric-and-forge

### Minecraft version

1.20.1

### Describe the bug

When adding certain add-ons to the game and recording a replay, on watching it Create's blocks are corruptedly replaced by other random block(states)

### Steps to reproduce

Record with Replay mod only - everything fine.
Record with one extra add-on - _cursed things_.

### Logs

In "Additional context"

### Additional context

Create only: ![2024-02-13_22 10 21](https://github.com/Sinytra/Connector/assets/122053125/cadbdb57-066a-45ce-9258-4ac267f73a9a) [logs](https://mclo.gs/UPhp2gK);
Create and [Copycats+](https://github.com/copycats-plus/copycats): 
![2024-02-13_22 08 26](https://github.com/Sinytra/Connector/assets/122053125/47125eea-fed2-4acf-b4e0-f6a3b334158c) [logs](https://mclo.gs/F4A4fKC);
Create and [Design n Decor](https://github.com/DrMango14/Create-Design-n-Decor): ![2024-02-13_22 06 25](https://github.com/Sinytra/Connector/assets/122053125/0cb6be7b-bcf9-4f29-845b-79b67fcd23bf) [logs](https://mclo.gs/V06dT78);
Create and [Steam'n'Rails](https://github.com/Layers-of-Railways/Railway): ![2024-02-13_22 04 16](https://github.com/Sinytra/Connector/assets/122053125/0f199bc4-8c75-4c35-90f9-012b8de84d4e) [logs](https://mclo.gs/i59namP).

**Comment by VladisCrafter** [comment]
Those goofy random replacements are mostly random and do not depend on the add-on itself, I guess...

**Comment by VladisCrafter** [comment]
The reason **might actually be** me entering the world with updated mods list, which somehow corrupts the NBT data of every non-vanilla(ish?) block. I'll try to record a world with constant modlist and see the results soon...

**Comment by VladisCrafter** [comment]
# The problem was solved!
## Due to some testing, of course.
The biggest thanks goes to `@mxnmnm`*, because THIS was his (their) comment on my issue in Sinytra's Discord server:

![image](https://github.com/Sinytra/Connector/assets/122053125/db211ced-22ad-411b-b43a-aee5dd902bf0)

Well, test if this is true was a brilliant idea.

`Created a fresh world with many of add-ons metioned in my issue. Recorded - everything fine! Added another, tiny add-on - shlt happened.`

`Created another fresh world with this "naughty" add-on included - EVERYTHING IS STILL FINE!`
### Meaning that all Replay mod needs in oreder to record properly is just a constant modlist for the world!

*Discord username used. Lmk if you know his (their) GitHub username, I'll replace it with the right one!

**Comment by VladisCrafter** [comment]
Also note, that **only the mods that add new blocks/items**  are actually causing the corruption.
You can add client-side mods safely :D

**Comment by TheHaskBit** [comment]
it turns out that you can delete the "FML" parameter in level.dat and the replay mod will show the replays correctly. personally, it helped me and didn't break the world (I'm not sure exactly, make a backup)

**Comment by VladisCrafter** [comment]
If only you told me it 7 months ago, @TheHaskBit... 😅
