### ISSUE TITLE
Incompatible with MidnightControls

### ISSUE THREAD

**Issue by Jo4p** [Sinytra/Connector#834]
### Mod Name

MidnightControls

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/midnightcontrols

### Minecraft version

1.20.1

### Describe the bug

the game does not load with midnight controls

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/Jo4p/4d8aea9bbf94629d47eed8a4a8c91ea3

### Additional context

![145561454](https://github.com/Sinytra/Connector/assets/144541136/3b351388-daa4-4536-b0b5-330242766572)

**Comment by Su5eD** [comment]
Confirmed to work on Forge 47.1.3 and Connector beta 37.

![image](https://github.com/Sinytra/Connector/assets/51261569/31cc9ef3-b9aa-4a39-8cf2-1db2f35b0273)
