### ISSUE TITLE
Incompatible with "Tale of Kingdoms: A new Conquest"

### ISSUE THREAD

**Issue by UGamer** [Sinytra/Connector#835]
### Mod Name

Tale of Kingdoms: A new Conquest

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/tale-of-kingdoms-a-new-conquest

### Minecraft version

1.20.1

### Describe the bug

Can't get to title screen with Tale of Kingdoms installed

### Steps to reproduce

1. Fresh install of Minecraft, Forge 4.7.1.3 (4.7.2.20 doesn't work either), Connector beta 36, latest version of Forgified Fabric API, and latest Connector extras (doesn't work with or without).
2. Install owo-lib (dependency) and Tale of Kingdoms.
3. Start game, crash report is given.

### Logs

https://mclo.gs/so4qN7k

### Additional context

owo-lib was also problematic recently it seems, but that has been fixed. You're able to load in just fine with JUST owo-lib. Tale of Kingdoms is the problem.

**Comment by Su5eD** [comment]
Got the same error on Fabric using Fabric loader 0.15.3 and FAPI 0.90.4+1.20.1.

See https://github.com/SamB440/Tale-of-Kingdoms/issues/154
