### ISSUE TITLE
Game crashes with Cloth Config Api

### ISSUE THREAD

**Issue by NyanLinHtet5** [Sinytra/Connector#837]
### Mod Name

Cloth Config Api

### Mod Homepage

https://modrinth.com/mod/cloth-config/version/11.1.118+fabric

### Minecraft version

1.20.1

### Describe the bug

[Note : I'm on PojavLauncher] I've recently downloaded a file called "Remarkably Optimized" that helps you reduce lag for low end devices and since my phone doesn't work well for computer games, I downloaded it, but the game crashes when I join servers.

### Steps to reproduce

1. Use Cloth Config Api
2. Run the game
3. Join any servers
4. Crashes 
5. (Only happens to me me for some reason)

**Comment by coco875** [comment]
use the forge version of cloth config api it will work with fabric mod

**Comment by Su5eD** [comment]
Custom server APIs (such as Mohist, Magma, Arclight) are not supported. This also applies to launchers for mobile platforms (Pojav, FoldCraft) and pirated launchers.

Such platforms provide unpredictable environments in which mods might not function as expected, and therefore we can't provide support for them. Ensuring mod compatibility is the platform's duty, just like Connector tries its best to achieve parity when running Fabric mods on Forge.

This is explained in our [FAQ](https://github.com/Sinytra/Connector/discussions/689).
