### ISSUE TITLE
Crash upon game open with BMC4 Modpack

### ISSUE THREAD

**Issue by Nximus** [Sinytra/Connector#838]
### Mod Name

ffapi

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

### Minecraft version

1.20.1

### Describe the bug

Game crashes

### Steps to reproduce

1. Download BMC4 Modpack
2. Launch Game
3. Crash
...

### Logs

https://paste.atlauncher.com/view/2a4c5b4b-4278-40dd-9813-885f382e9c28

### Additional context

Reinstalled java, updated java jre, uninstalled and reinstalled modpack, system restarted multiple times, and even changed forge versions to no avail. I spoke with modpack developers and they said they believe FFAPI to be the issue causing the crash according to the above crash logs.

**Comment by coco875** [comment]
Reduce the number of mods to isolate with what he make the conflict (it look like to be with eldritch_end not sure)

**Comment by Nximus** [comment]
We fixed the issue! It seems that the ~ in the nickname of her c drive was causing a problem. She switched to her e drive and it opens no problem now
