### ISSUE TITLE
Opening creative inventory with Controlify still crashes the game

### ISSUE THREAD

**Issue by OKHI233** [Sinytra/Connector#839]
### Mod Name

Controlfiy

### Mod Homepage

https://modrinth.com/mod/controlify

### Minecraft version

1.20.1

### Describe the bug

Basically a clone of #720: opening creative inventory with Controlify installed still crashes the game, although the log output seems different.

### Steps to reproduce

1. Install Controlify and YACL. 
2. Load a Minecraft world. 
3. Make sure you're in creative mode. 
4. Open your inventory. 
5. Game crash. 

### Logs

https://gist.github.com/OKHI233/d36347b07383fd9bc3c233b72e7585db

**Comment by Su5eD** [comment]
Fixed in FFAPI 0.92.0+1.11.3+1.20.1. I've tested modded tabs as well and everything appears to run fine.
