### ISSUE TITLE
Game crashes on opening

### ISSUE THREAD

**Issue by Beta123456** [Sinytra/Connector#840]
### Minecraft version

1.20.1

### Describe the bug

My game crashes during the forge loading after it says transforming fabrri jars with a  exit code of one 

### Steps to reproduce

1.install this forge modpack
![ad](https://github.com/Sinytra/Connector/assets/160263282/1a783a82-d5f4-4a16-ada0-d47315433a9c)
2.open game
3.wait a few seconds
4. crash

### Logs

crash exit code:1

### Additional context

i'm using more than one beta mod so that might be the problem

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin

**Comment by Beta123456** [comment]
ok thank you for your time anyway

**Comment by Beta123456** [comment]
but it started happening only after i put immersive portals in so it might be incompatible
