### ISSUE TITLE
Raknetify Incompat 

### ISSUE THREAD

**Issue by Liamgrayskull** [Sinytra/Connector#841]
### Mod Name

rakenetify

### Mod Homepage

https://modrinth.com/plugin/raknetify

### Minecraft version

1.20.1

### Describe the bug

Startup Crash with minimal modlist

### Steps to reproduce

1.Load latest versions of Sinytra Connector, Forgified Fabric API and https://modrinth.com/plugin/raknetify/version/0.1.0+alpha.5.114 on forge 47.2.17
2. Start the game
3. Crash on startup with listed error
...
https://gist.github.com/Liamgrayskull/6bf2174659890011bfdb1ab5532153f8
(latest.log)

### Logs

https://gist.github.com/Liamgrayskull/1f46c36425159e1092167b5b4fd446b8

**Comment by kakashi1464** [comment]
Try with forge 47.1.3

**Comment by liangmoe** [comment]
> Try with forge 47.1.3

lates.log from new instance with forge 47.1.3: https://mclo.gs/AnqTX9r
