### ISSUE TITLE
ULTRACRAFT server crash (again why)

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#842]
### Mod Name

ULTRACRAFT

### Mod Homepage

https://modrinth.com/mod/absolute-ultracraft

### Minecraft version

1.20.1

### Describe the bug

crash on startup

### Steps to reproduce

1.add mod to server
2.crash

### Logs

https://gist.github.com/xg787/625bac179c3ab8786d2729910a0e26af

### Additional context

tested with beta 36 + extras 1.9.3

**Comment by Su5eD** [comment]
Fixed in FFAPI [0.92.0+1.11.1+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.92.0+1.11.1+1.20.1).
