### ISSUE TITLE
Elytra Aeronautics crashes with a mixin erroro

### ISSUE THREAD

**Issue by Dakedres** [Sinytra/Connector#843]
### Mod Name

Elytra Aeronautics

### Mod Homepage

https://modrinth.com/mod/elytra-aeronautics

### Minecraft version

1.20.1

### Describe the bug

The game crashes during startup with Elytra Aeronautics

### Steps to reproduce

1. Install Elytra Aeronautics, Forgified Fabric API, and Sinytra Connectors
2. Launch the game

### Logs

https://mclo.gs/erL03hc

**Comment by Su5eD** [comment]
Confirmed to work on Forge 47.1.3

**Comment by Dakedres** [comment]
joy and peace and love on planet earth
