### ISSUE TITLE
Random Crashing with big modpack?

### ISSUE THREAD

**Issue by BoardAnims** [Sinytra/Connector#847]
### Mod Name

Unknown

### Mod Homepage

Unknown

### Minecraft version

1.20.1

### Describe the bug

Game has a chance of crashing at random?

### Logs

https://gist.github.com/BoardAnims/cefcb301d2f626fab3d8cac928b0e66d

### Additional context

Sorry for asking here, but im not sure where else to ask for help in a large custom modpack.

This connector has been working quite great for me besides a few unrelated lag problems. The main problem Im having is the game randomly crashing. It doesnt seem to be triggered by anything in particular, it sort of just happens while play-testing. I can re-enter the world and continue playing without many errors. 
Asking here if it's possible the sinytra connector is responsible for any of these crashes. Please read crash-reports if possible, thank you.

**Comment by Su5eD** [comment]
I've read the stacktrace in the crash report, but it doesn't point to any particular mod. Try removing Connector and all Fabric mods, which should eliminate the possibility of Connector being involved.

**Comment by BoardAnims** [comment]
> I've read the stacktrace in the crash report, but it doesn't point to any particular mod. Try removing Connector and all Fabric mods, which should eliminate the possibility of Connector being involved.

I'll try this in a new world, thanks.

Do you know what the error is for when forge tries to load a fabric mod? Since finding all fabric mods is a little hard, especially if one is a library.

Also if there's a way to binary search only content mods and not library/dependencies?
