### ISSUE TITLE
Error transforming jar (lithium)

### ISSUE THREAD

**Issue by Barerock** [Sinytra/Connector#848]
### Mod Name

Lithium

### Mod Homepage

https://modrinth.com/mod/lithium

### Minecraft version

1.20.1

### Describe the bug

Error loading mod displays error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to execute task me/ jellysquid/mods/lithium/mixin/ai/raid/RaidMixin.class

### Steps to reproduce

1. install Connector and Forgified Fabric API
2. install lithium
3. error

### Logs

Crash log: https://pastebin.com/dgEfUfY0

**Comment by weegeeluigi** [comment]
Use Embeddium and it's companion mods for now.  Sodium is about to go multiloader starting with 0.6 so Embeddium is only a holdover.

**Comment by Lolothepro** [comment]
but... [lithium](https://modrinth.com/mod/lithium) is not Sodium... it's radium (https://modrinth.com/mod/radium)

**Comment by weegeeluigi** [comment]
No one said it is.  I recommended to use the forge ports until the multiloader conversions are done.

**Comment by Lolothepro** [comment]
> No one said it is. I recommended to use the forge ports until the multiloader conversions are done.

this person reported that **Lithium** is not compatible
You have recommended a **Sodium port** (Embeddium)
Lithium is not Sodium

**Comment by weegeeluigi** [comment]
> Use Embeddium and **it's companion mods for now**. Sodium is about to go multiloader starting with 0.6 so Embeddium is only a holdover.
