### ISSUE TITLE
Error transforming jar (lithium)

### ISSUE THREAD

**Issue by Barerock** [Sinytra/Connector#849]
### Mod Name

Lithium

### Mod Homepage

https://modrinth.com/mod/lithium

### Minecraft version

1.20.1

### Describe the bug

Error loading mod displays error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to execute task me/ jellysquid/mods/lithium/mixin/ai/raid/RaidMixin.class

### Steps to reproduce

1. install Connector and Forgified Fabric API
2. install lithium
3. error

### Logs

Crash log: https://pastebin.com/dgEfUfY0 latest.log: https://pastebin.com/9xHtU3UM

### Additional context

Many other mods, but I was using lithium and all of these other mods + rayon without seeing this error; however, I removed rayon due to its new incompatibility with sodium 0.5.+, which is most likely why only now am I seeing this error. I looked through other issues and the descriptions of the Connector, API, and extras page to see if there was a compatibility note anywhere but couldn't find one. Apologies if this was supposed to be an obvious thing that would happen.

**Comment by kakashi1464** [comment]
Use radium instead of lithium

**Comment by Barerock** [comment]
> Use radium instead of lithium

Shouldn't matter, no?

**Comment by Barerock** [comment]
It flat out crashes with sodium so I guess that's that. Very unfortunate, considering rubidium and magnesium are total messes with next to no compatibility for some rather nice things.

**Comment by coco875** [comment]
use embeddium for the sodium port

**Comment by coco875** [comment]
and heavy mod of optimisation will not be supported since they change a lot of thing in game and can conflict a lot with forge so use forge port instead

**Comment by Barerock** [comment]
> use embeddium for the sodium port

This is the info I found by looking up sodium instead. What is the best set of extras mods? There's at least 8

**Comment by coco875** [comment]
of what I see extra don't optimise more, it's just to add useful thing to control if you want to discuss about mod of optimisation we can go the discord of connector instead of using the issue

**Comment by Barerock** [comment]
I think I've got it handled. Reeling from this massive addition to the platform and also the neoforge situation. Been away from modding since Axiom came out, so like... a small time. Thanks for the help, dude!

**Comment by coco875** [comment]
no problem, it's true the situation of modding now are complex I hope it will be more simplified in 1.21
