### ISSUE TITLE
Missing layer definitions crash with Spectrum

### ISSUE THREAD

**Issue by Dogboy-Cole** [Sinytra/Connector#854]
### Mod Name

Spectrum

### Mod Homepage

https://modrinth.com/mod/spectrum

### Minecraft version

1.20.1

### Describe the bug

Loading fails on start up 

### Steps to reproduce

1.
2.
3.
...

### Logs

Crash log: https://gist.github.com/Dogboy-Cole/3f298c3856df918f6210511097ff7a26 ||  Mod list: https://gist.github.com/Dogboy-Cole/b9b4c518d50e530dbbd8cbde265dcafa

### Additional context

Upon loading the instance the game crashes with the following error:

"The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Missing layer definitions: [spectrum:preservation_turret_head#main, spectrum:monstrosity_head#main, spectrum:kindling#main, spectrum:monstrosity#main, spectrum:warden_head#main, spectrum:lizard#horns, spectrum:eraser#body, spectrum:kindling_head#main, spectrum:egg_laying_wooly_pig#wool, spectrum:lizard#frills, spectrum:egg_laying_wooly_pig#main, spectrum:egg_laying_wooly_pig_head#main, spectrum:kindling_armor#main, spectrum:kindling_cough#main, spectrum:eraser_head#body, spectrum:kindling_saddle#main, spectrum:bedrock_armor#main, spectrum:bedrock_armor#feet, spectrum:lizard_head#main, spectrum:lizard#main, spectrum:preservation_turret#main, spectrum:egg_laying_wooly_pig#hat]"

The instance actually loaded once before this, but every subsequent attempt to load it has resulted in this error.

**Comment by Su5eD** [comment]
I've tested spectrum on the latest version of connector using Forge 47.1.3, and it runs fine even after multiple reboots.

![image](https://github.com/Sinytra/Connector/assets/51261569/3492ffe2-375a-4422-ade9-6ce3dfd2b1c3)

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
