### ISSUE TITLE
Bewitchment crash

### ISSUE THREAD

**Issue by SmArtKar** [Sinytra/Connector#855]
### Mod Name

Bewitchment

### Mod Homepage

https://modrinth.com/mod/bewitchment

### Minecraft version

1.20.1

### Describe the bug

Game crashes with Bewitchment. Same as #765 again, this issue supposedly was fixed in beta 35 but still occurs. Gist links to latest_stdout.log because latest.log doesn't have mixin conflict info

### Logs

https://gist.github.com/SmArtKar/03caaa6a125d2ab53ce325c20a551468

**Comment by SmArtKar** [comment]
Fixed by using forge 47.1.3/neoforge 47.1.5

**Comment by SoftySylph** [comment]
Working initially when used on forge 47.1.3
But crashes upon being turned into a vampire due to the same or a similar mixin, heres a crash log.
[crash-2024-02-25_14.39.15-client.txt](https://github.com/Sinytra/Connector/files/14397575/crash-2024-02-25_14.39.15-client.txt)
mods used:
![image](https://github.com/Sinytra/Connector/assets/92411169/4f966bbf-e475-4de5-9036-6abf2bb157fc)

**Comment by KultidGames** [comment]
> Working initially when used on forge 47.1.3 But crashes upon being turned into a vampire due to the same or a similar mixin, heres a crash log. [crash-2024-02-25_14.39.15-client.txt](https://github.com/Sinytra/Connector/files/14397575/crash-2024-02-25_14.39.15-client.txt) mods used: ![image](https://private-user-images.githubusercontent.com/92411169/307617818-4f966bbf-e475-4de5-9036-6abf2bb157fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDMwMjAsIm5iZiI6MTcxNzM0MjcyMCwicGF0aCI6Ii85MjQxMTE2OS8zMDc2MTc4MTgtNGY5NjZiYmYtZTQ3NS00ZGU1LTkwMzYtNmFiZjJiYjE1N2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE1Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Yjk3ZmU1M2Y3N2UxMTZhMzExNjUyOGIxZDUyMGM4NTFmY2U2MjBlZDllNmRhNDkzOGNjNmEzNjhhYzVmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gb-qZNdZgg0tcC8uaMSSTIeEQSo3cmGw-vMI_fpPInc)
> 
> Edit: all newest versions, besides maybe pehkui, but that doesn't come into play here. soft locks the world since you're stuck in the gui change, also only on the client since its related to gui. testing is possible using these commands: /curse add bewitchment:susceptibility /time set night /give @s minecraft:totem_of_undying /give @s bewitchment:vampire_spawn_egg (I think that's the id)
> 
> then in survival hold the totem, spawn the vampire and let it kill you, should instantly crash.
> 
> Edit 2: Would be nice to have on the newest forge version too though.

Unable to replicate in Forge 47.1.3— interestingly, I'm unable to even load Bewitchment in that version. 

However, you are able to to load Betwichment in NeoForge 47.1.5.
Can confirm issue is still extant, both using a totem of undying and death protection poppet, as well as using /transformation set [player] vampirism when in survival mode.

**Comment by NoalSimon** [comment]
I'm getting same issue with being unable to load bewitchment in newest edition in any forge version. something they did with voodoo dolls drowning effect being unable to be injected with mixin and failing on launch.

**Comment by Cyph3rous** [comment]
trying recently now, and can confirm still will not get passed launch
