### ISSUE TITLE
Incompatible with Desolation

### ISSUE THREAD

**Issue by cal1407** [Sinytra/Connector#856]
### Mod Name

Desolation

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/desolation

### Minecraft version

1.20.1

### Describe the bug

Game crash on startup with Desolation installed.

### Steps to reproduce

1. Install Forgified Fabric API, Connector and Connector Extras
2. Install Trinkets
3. Install Desolation
4. Launch the game
...

### Logs

https://pastebin.com/1mDaDVVa

### Additional context

Crash Report: https://pastebin.com/R6x1SbSR

**Comment by Su5eD** [comment]
You'll need to use the Fabric version of Geckolib to make Desolation work. However, there might be incompatibility issues related to it if you're also running Forge mods that require Geckolib, as explained in #231.

**Comment by cal1407** [comment]
I do have the forge version of Geckolib installed. Does this mean that I can't run both fabric and forge version together?

**Comment by RoomAlex68** [comment]
Unfortunately no, Geckolib Forge and Fabric are incompatible with each other due to both not having a multiloader system inside both mods.
