### ISSUE TITLE
Infinite save loading with Cinderscapes installed (as well as Terrestria and Traverse)

### ISSUE THREAD

**Issue by cal1407** [Sinytra/Connector#857]
### Mod Name

Cinderscapes

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/cinderscapes

### Minecraft version

1.20.1

### Describe the bug

The game would initially load just fine, but it would freeze when I try to create or load a save, occurring before the loading box appears.

### Steps to reproduce

1. Install Forgified Fabric API, Connector and Connector Extra
2. Install Cinderscapes (and/or Terrestria and Traverse)
3. Launch Minecraft
4. Create/load a save
...

### Logs

https://pastebin.com/0tfZ40U3

### Additional context

When I try to force close the game, no crash logs were generated. However, this message appear instead: https://imgur.com/a/LLJhphK

I'm certain that there's nothing wrong with the memory allocation, since I can open the game just fine without this mod installed.

**Comment by Su5eD** [comment]
This appears to be the same issue as #472, where a mod replaced instances of `MultiNoiseBiomeSource`, erasing biolith's data. I've tested both Cinderscapes and Terrestria, and they run just fine. Additionally, your log lists mod that are not mentioned in the issue, therefore it's hard to determine the culprit.

This is outlined in the issue template:

> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by cal1407** [comment]
Found the issue. It seems that this happens when I have Dungeons Content installed together along with the aforementioned mods.
