### ISSUE TITLE
bedrockify can't load

### ISSUE THREAD

**Issue by FTLasteroid** [Sinytra/Connector#858]
### Mod Name

bedrockify

### Mod Homepage

https://modrinth.com/mod/bedrockify

### Minecraft version

1.20.1

### Describe the bug

PCL2 launcher said inject that mod failed, I use beta 36 and use forge 47.2.20, then i find another issue said use beta 35 and forge 47.1.30 will be fine, but  still crash. 

### Steps to reproduce

1. Install connector and bedrockify 
2. Launch 
3. Load a little time then crash 
4. Here is my mod list 
<img width="525" alt="{A91EA995-B6E8-439f-A540-DC6DD79374C6}" src="https://github.com/Sinytra/Connector/assets/136573272/7bceda41-5b81-4dc2-9bb9-2ca2e0f38a61">
I try to locate problem so I close other mod to prevent other mod's influence 

### Logs

https://paste.ubuntu.com/p/FHnw92NCxW/

### Additional context

I use PCL2 launcher

**Comment by Su5eD** [comment]
Use Forge 47.1.3 as explained in the documentation.
