### ISSUE TITLE
Lukas' Weapon Leveling damage buff doesn't work

### ISSUE THREAD

**Issue by NotCodly** [Sinytra/Connector#863]
### Minecraft version

1.20.1

### Describe the bug

When the weapon levelled up it supposed to add 0.1 damage for every level the weapon has but in reality the weapon damage still the same.

### Steps to reproduce

1.Join a Singleplayer World
2.Hold any weapon
3./itemlevel set @s 100 level

### Logs

https://gist.github.com/NotCodly/038973a4db7f1e0fdce5e6c5c14aa492

### Additional context

This is with the latest version 1.0.0-beta.36+1.20.1 and connector extras version 1.9.3+1.20.1
![bug 1](https://github.com/Sinytra/Connector/assets/109955276/76816498-ec9d-4cd7-818f-92fc61ee37ac)

This is without the connector mod and only Lukas' Weapon Leveling
![bug 3](https://github.com/Sinytra/Connector/assets/109955276/1d09239b-46ab-45b9-b6fc-22f482f1c7e4)

**Comment by Su5eD** [comment]
Fixed in beta 37
