### ISSUE TITLE
Bewitchment and Besmirchment crash when using transformations

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#864]
### Mod Name

Bewitchment and Besmirchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment Besmirchment - https://www.curseforge.com/minecraft/mc-mods/besmirchment-2

### Minecraft version

1.20.1

### Describe the bug

Game crashes when transforming into some creatures(and u cant rejoin world)

### Steps to reproduce

1.Install bewitchhment and besmirchment(besmirchment isnt mandatory just have the same issue)
2.create survival mode world 
3.use command /transformation set @player besmirchment:werepyre and/or /transformation set @player bewitchment:vampyre
...

### Logs

https://gist.github.com/Tomat777/7eb0f950438f6bd6c1eb361cedbdb4a0

**Comment by Joki2904** [comment]
I can confirm I have the exact same problem. Could it possible to add compatibility for this mod a well as for newest versions of Forge?

**Comment by Joki2904** [comment]
Little update: it seems to be an mixin failure due to an incompatibility with Entity Step Attributes. Or at least that's what happens in Forge 47.2.0. I think we would be very grateful if it could be fixed.

**Comment by Joki2904** [comment]
I can confirm the same issue is happening to me. Everything is fine until you become a vampire.
