### ISSUE TITLE
Beta.37 crashes game on startup (Exit Code: 1)

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#865]
### Minecraft version

1.20.1

### Describe the bug

Beta.37 crashes game on startup (Exit Code: 1)

### Logs

https://mclo.gs/sBfASiu

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
