### ISSUE TITLE
Replay Mod crashes when splitting a long recording

### ISSUE THREAD

**Issue by SubayAdamm** [Sinytra/Connector#866]
### Minecraft version

1.20.1

### Describe the bug

A recording I took (approximately 1.30 hours long) crashes the game when trying to split in the main menu

### Steps to reproduce

1. Record a long replay recording
2. Try to split it or cut it
3. Crash report, original recording is gone

### Logs

https://pastebin.com/rJAaM5Kw

### Additional context

I've posted the issue on the Replay Mod's github page, but they stated that I should post it here.

**Comment by Su5eD** [comment]
Merging into #556 to better keep track of issues related to ReplayMod.
