### ISSUE TITLE
Crash when both Show Me Your Skin! and Blue Skies are installed

### ISSUE THREAD

**Issue by TheLastRar** [Sinytra/Connector#867]
### Mod Name

Show Me Your Skin!

### Mod Homepage

https://modrinth.com/mod/show-me-your-skin

### Minecraft version

1.20.1

### Describe the bug

Crash when Show Me Your Skin! and Blue Skies are installed

### Steps to reproduce

Install [Blue Skies](https://modrinth.com/mod/blue-skies) (A forge only mod) and Show Me Your Skin!
Try to launch Minecraft
Game crashes

### Logs

https://mclo.gs/1xGzGUg

### Additional context

Connector is currently the only way I'm aware of to have both mods running together, so it's not possible for me to easily determine whether Connector is causing the issue, or if this is just an incompatibility between the two mods.

**Comment by BTrn778** [comment]
I have both mods installed in my modpack having the same issue did you find a solution?

**Comment by TheLastRar** [comment]
It was fixed beta 38 iirc
It's been a while since I've used those mods (or played mc actually)
Has it regressed? if so you may need to open a new issue
