### ISSUE TITLE
Crash after loading for a couple seconds - just got the mod.

### ISSUE THREAD

**Issue by VAitwo** [Sinytra/Connector#868]
### Minecraft version

1.20.1

### Describe the bug

I put the forgified api thing in, and after that, it's just doesn't work. I don't know what mod is causing this.

### Steps to reproduce

1. these mods 
![image](https://github.com/Sinytra/Connector/assets/161784710/d29898a9-42eb-44bc-b8d0-71cef78a4f3d)
2. open it up
3. it crashes

### Logs

[crash-2024-02-29_18.26.16-fml.txt](https://github.com/Sinytra/Connector/files/14455195/crash-2024-02-29_18.26.16-fml.txt)

### Additional context

Hope this isn't too many mods

**Comment by Jadan1213** [comment]
you have doubles of mods and some are incorrect versions to start.

Remove then mc1.20 0.4.10 of sodium.
Remove cloth config 11.1.118
Remove fabirc api 0.91.1 for 1.20.2
I don't think you can use optifine with sodium..

**Comment by Jadan1213** [comment]
i see two copies that are different sizes of fabric api 0.92.0, you should remove fabric api and use forgified fabric instead

**Comment by VAitwo** [comment]
Thanks homie

**Comment by Jadan1213** [comment]
let me know if it loads. i'll help you figure it out =)

**Comment by VAitwo** [comment]
> you have doubles of mods and some are incorrect versions to start.
> 
> Remove the mc1.20 0.4.10 of sodium. Remove cloth config 11.1.118 Remove fabirc api 0.91.1 for 1.20.2 I don't think you can use optifine with sodium..

could you clarify which I should just remove altogether and which ones i just need a different version of?

**Comment by Jadan1213** [comment]
Those were the ones to remove. 

Delete
fabric-api-0.9.1+1.20.2
fabric-api-0.92.0+1.20.1.jar
Optifine_1.20.1_HD_U_I6.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar

**Comment by VAitwo** [comment]
> Those were the ones to remove.
> 
> Delete fabric-api-0.9.1+1.20.2 fabric-api-0.92.0+1.20.1.jar Optifine_1.20.1_HD_U_I6.jar sodium-fabric-mc1.20-0.4.10+build.27.jar

gotcha

**Comment by Jadan1213** [comment]
remove those and try to load the game. let me know what happens

**Comment by Jadan1213** [comment]
if you get a crash log, post it here for me

**Comment by VAitwo** [comment]
> remove those and try to load the game. let me know what happens

I decided to forego the shaders and just work with the gameplay mods, but now Modern Beta is yelling at me. 
![image](https://github.com/Sinytra/Connector/assets/161784710/1ca85c7e-95f3-4fb5-a51d-151c6e98b6c6)

**Comment by Jadan1213** [comment]
post the full crash log

**Comment by VAitwo** [comment]
[crash-2024-02-29_19.42.36-client.txt](https://github.com/Sinytra/Connector/files/14455439/crash-2024-02-29_19.42.36-client.txt)

**Comment by Jadan1213** [comment]
your modern beta jar is for 1.20 not 1.20.1 it looks like
get the correct version and try again

**Comment by Jadan1213** [comment]
unless it's compatible with both. i don't know what modern beta is. sorry

**Comment by VAitwo** [comment]
> unless it's compatible with both. i don't know what modern beta is. sorry
it's compatible with both. Modern Beta is a world generation thingy, that makes it so that minecraft kinda makes the terrain exactly the same as it was in the beta version. so if you typed 404 as the seed, you get the exact same sinkhole cave as you would in the beta version. Maybe try it yourself?

**Comment by VAitwo** [comment]
it'd be cool if i could keep it but if i gotta delete it for things to work, that's fine

**Comment by Jadan1213** [comment]
i use terralith and tectonic for my overworld generation. give me a few. i'm gonna make an install with your mods and see what happens

**Comment by Jadan1213** [comment]
i noticed another duplicate.

cloth-config-11.1.118-fabric.jar 
cloth-config-12.0.119-fabric.jar.

delete the older version

**Comment by Jadan1213** [comment]
i noticed most of your mods are fabric, why not just use fabric? do you need forge for a specific reason?

**Comment by VAitwo** [comment]
i probably should've checked to see if the connector worked with fabric too

**Comment by VAitwo** [comment]
or rather. the lack of the regular fabric api

**Comment by Jadan1213** [comment]
ok so i'm confused now. You're running fabric 1.20.1?

if so, you don't need sinytra connector. It's meant for forge in order to run fabric mods on Forge isntalls

**Comment by VAitwo** [comment]
there was a couple mods out here where I was like "I can't believe these aren't in Fabric" and I found the mod and I'm like "oh ok so I can use Better Stacks with Fabric with Sinytra Connector."

**Comment by Jadan1213** [comment]
Unfortunately it doesn't work in reverse. You'd need to run a Forge install in order to use sinytra. Sinytra makes fabric mods work on forge only. Not the other way around.

**Comment by VAitwo** [comment]
see that's what i thought, so I stuck with forge

**Comment by Jadan1213** [comment]
Then you shouldn't be using the fabric loader.

**Comment by VAitwo** [comment]
I wasn't using it, I was using forge

**Comment by VAitwo** [comment]
![image](https://github.com/Sinytra/Connector/assets/161784710/639f15d9-df30-4605-8202-83f80b2fbf61)
see

**Comment by Jadan1213** [comment]
oh ok, i misunderstood from the screenshot then.

**Comment by VAitwo** [comment]
I deleted the old cloth-config

**Comment by VAitwo** [comment]
same thing still happens with Modern Beta. It happens after it says "gathering CONSTRUCT" when forge is loading in the beginning if that helps at all

**Comment by VAitwo** [comment]
if there isn't a fix for Modern Beta, I might just try out Terralith.

**Comment by Jadan1213** [comment]
i'm trying to recreate your install but i dont know what reindev or esm are

**Comment by VAitwo** [comment]
Reindev is something I only use on MultiMC, it doesn't work on Minecraft Launcher.

**Comment by Jadan1213** [comment]
ok it loads without using sodium/indium. which i thought would be the case. Use the forge equivilents

Embeddium (sodium equivilent)
Embeddium Extra
Lazurite (indium equivilent)

if you want shader support, you can install Oculus, no promises it will work good.

I also installed the forge version of Ambient sounds since it's available on forge.

**Comment by Jadan1213** [comment]
![image](https://github.com/Sinytra/Connector/assets/68805162/74911925-a05a-467f-9efc-33c4d3514119)

**Comment by VAitwo** [comment]
Yeah, they're sodium and indium are in a different folder

**Comment by Jadan1213** [comment]
according to your image, it's in your mods folder.

**Comment by VAitwo** [comment]
oh yeah i said i put away the shaders

**Comment by VAitwo** [comment]
I guess I didn't clarify that I moved them elsewhere

**Comment by Jadan1213** [comment]
with these mods
![image](https://github.com/Sinytra/Connector/assets/68805162/2c1d05d7-08f4-4b0c-8877-6dd9fbd112c2)
i'm able to load into the game.

i also have forge 47.2.17
You're on 47.2.0, you can try updating it if it doesnt work

**Comment by VAitwo** [comment]
oh ok hold on

**Comment by VAitwo** [comment]
lemme just upgrade real quick and see if it works

**Comment by VAitwo** [comment]
OH SHIT IT WORKS

**Comment by VAitwo** [comment]
so I got the Forge version of Ambient Sounds, and it mysteriously works now

**Comment by VAitwo** [comment]
so there aren't any problems anymore, sorry it took so long to figure out what was going on

**Comment by Jadan1213** [comment]
all good, glad it's working for you now.
