### ISSUE TITLE
Sky Lands and some Fabric mods

### ISSUE THREAD

**Issue by XeXeking99** [Sinytra/Connector#871]
### Mod Name

Sky Lands

### Mod Homepage

https://modrinth.com/mod/sky-lands

### Minecraft version

1.20.1

### Describe the bug

After starting up my game and trying to load a single player world, the game freezes before generating the new world.

### Steps to reproduce

1. Launch the game
2. Create a New World
3. As it's preparing the world, it freezes.
4. When you click on the game, it says the game is not responding and gives you the option to close the game or wait for it to respond.
5. When you close the game out, and error message saying: This crash may be resolved by allocating additional memory.

...
![2024-02-29](https://github.com/Sinytra/Connector/assets/57610726/afe54a32-b1b0-4e1c-bb66-7a6cce8159b7)

### Logs

https://gist.githubusercontent.com/XeXeking99/23485f8b68ef6772c16637bc045d9a26/raw/d1b0dfb570be1bf7489490ea3dd555b18be2c2d7/latest.log5d9a26

### Additional context

I've tested and figured out which mods are conflicting with it.

Terrestria-6.0.13
TerraBlender-fabric-1.20.1-3.0.1.4
Cinderscapes-4.0.9
Remove_Base_Origins_1.20+_Fabric

**Comment by Su5eD** [comment]
Same issue as #857
