### ISSUE TITLE
EntityJs incompability

### ISSUE THREAD

**Issue by DragonMaster14545** [Sinytra/Connector#879]
### Mod Name

EntityJs

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/entityjs 

### Minecraft version

1.20.1

### Describe the bug

You can't access server side values in places you normally can

### Steps to reproduce

[kubejs.zip](https://github.com/Sinytra/Connector/files/14473568/kubejs.zip)
Install kubejs, entityJs and connector, together with all their dependencies
You don't even need to have any fabric mod
Put the folder from the zip into your .minecraft folder
Start the game
Spawn a kubejs:npc1
It basicly just is a blue cube, that jumps from time to time
If you uninstall connector and spawn another npc1, you will see that it basicly never jumps
This is the code that creates the entity:
```js
StartupEvents.registry('entity_type', event => {
    event.create('npc1', 'entityjs:animal')
    .eggItem(item => {
        item.backgroundColor(0x0000FF)
        item.highlightColor(0x0099FF)
    })
    .onInteract(ctx => {
        if(ctx.hand == 'MAIN_HAND') {
            if(!ctx.entity.getLevel().isClientSide()) return InteractionResult.PASS
            Client.player.sendData('rpg_npc_interaction', {entity:ctx.entity.stringUuid,level:ctx.entity.level.dimension.toString()})
        }
        return InteractionResult.PASS
    })
    .isPersistenceRequired(true)
    .isImmobile(entity => {
        return true
    })
    .isInvulnerableTo(ctx => {
        if(ctx.damageSource.type().msgId() != 'genericKill') {
            return true
        } else {
            return false
        }
    })
    .isPushable(false)
    .addAnimationController('idleAnimation', 5, e => {
        e.addTriggerableAnimation('idle', 'idleing', 'play_once')
        return true
    })
    .tick(entity => {
        if (entity.age % 100 != 0) return
        if (Math.random() <= 0.99) return
        entity.triggerAnimation('idleAnimation', 'idleing')
    })
})
```
We mainly care about the tick methode here. As you can see I test if the age of the entity is devidable by 100 with 0 left. (The % operator returns the number that is left when dividing by a number) If not I return. Then I have a random factor, to only provide a verry small chance. If both of those don't return, I trigger the animation, in this case a little jump.
If everything works fine, this should basicly never trigger, because every 100 ticks there is a 1/100 chance. 
So now to the problem: entity.age only exists on the server. But if sinytra connector is installed, it can't access the server for some reason. So it returns 0. 0/100 has 0 left, so the first check always succeeds. This is why it jumps pretty often with connector installed

### Logs

https://gist.github.com/DragonMaster14545/2bf7dda10a040a13e9b7400cc337f47b

### Additional context

Also I see this warning appear a lot in the log:
[03Mar2024 16:08:09.886] [Server thread/WARN] [net.minecraft.world.entity.ai.attributes.AttributeMap/]: Ignoring unknown attribute 'reach-entity-attributes:reach'

I already talked to the creator of entityJs, he said this is not on his side
It would be awesome if this could be fixed, because I love playing my pack with axiom
Thanks a lot in advance

**Comment by DragonMaster14545** [comment]
Update on this, I just noticed this is a way bigger problem Im pretty sure
```js
EntityJSEvents.addGoalSelectors('kubejs:npc1', e => {
    e.customGoal(
        'move_to_persistent_data_position',
        1,
        mob => { 
            return true
        },
        mob => {
            return true
        },
        true,
        mob => {
                if(mob.persistentData.targetX && mob.persistentData.targetY && mob.persistentData.targetZ) {
                    mob.getNavigation().moveTo(mob.persistentData.targetX,mob.persistentData.targetY,mob.persistentData.targetZ, 1.0);
                }
        },
        mob => {
            mob.getNavigation().stop();
        },
        true, 
        mob => {
                if(mob.persistentData.targetX && mob.persistentData.targetY && mob.persistentData.targetZ) {
                    mob.getNavigation().moveTo(mob.persistentData.targetX,mob.persistentData.targetY,mob.persistentData.targetZ, 1.0);
                }
        }
    );
})```This is a custom entity goal with entityJs, if the entity has persistent data (That is only on the server) it should move to  a specific position. But it seams like the persistent data is always empty here. This is also fixed when disabeling connector. This code is run on the server though, not on the client

**Comment by Su5eD** [comment]
I was able to trace this down to a bizarre scenario where changing the access level of `AgeableMob#age` to public triggers this issue. Connector applies a global access widener to all package-private and protected fields to prevent issues with package-level access between changing mappings.

https://github.com/Sinytra/Connector/blob/e40dcef57cf88ddb36bbcfdb43f4a341e1eea465/src/main/java/dev/su5ed/sinytra/connector/service/ConnectorPreLaunchPlugin.java#L44-L53

What makes things interesting, though, is that I was also able to trigger this with an ordinary access transformer file.

```ini
public net.minecraft.world.entity.AgeableMob age # age
```

As I was investigating this, I found out the `AgeableMob#age` field's value doesn't match the value returned by `entity.age` in the script, which seems to point to `Entity#tickCount` instead.

It turned out to be an [alias](https://github.com/KubeJS-Mods/KubeJS/blob/caa37aa85d82ef749c2b1cdaeb9ea6df51029362/common/src/main/java/dev/latvian/mods/kubejs/core/mixin/common/EntityMixin.java#L74-L76) set by kubejs. Normally, the protected field is hidden from outside access and doesn't get in the way of the aliased `tickCount` field. However, after being set to `public`, it now takes priority, hiding the value of `tickCount` (`age`).

**Comment by DragonMaster14545** [comment]
So, is this something that you can fix?

**Comment by DragonMaster14545** [comment]
Also, that doesn't explain why the server script code doesn't work

**Comment by Su5eD** [comment]
I tried running the server script, but it doesn't move the entity regardless of connector/FFAPI being installed.

**Comment by DragonMaster14545** [comment]
You have to set in its persistent data where it should move to. Thats thw hole purpose of that code

**Comment by DragonMaster14545** [comment]
With /kubejs persistent_data entity *your entity* merge {targetX:0, targetY:64, targetZ:0}
Just replace those coordinates with some near you. Also note, that this only works on the custom npc1 entity

**Comment by Su5eD** [comment]
I've tried that now, but the entity still doesn't move. The script also seems to be loaded correctly according to the server logs.

**Comment by DragonMaster14545** [comment]
Try just console.logging the persistent data, with connector it will always be {}

**Comment by DragonMaster14545** [comment]
For me the moving works fine, but Ive changed the code quite a bit since then

**Comment by Su5eD** [comment]
Forks fine for me both with and without connector

**Comment by DragonMaster14545** [comment]
Thats weird

**Comment by DragonMaster14545** [comment]
Im not at my computer right now so I cant test it

**Comment by Su5eD** [comment]
At which point does the persistent data become empty? Is it on world reload, game reload or immediately after setting it?

Don't feel rushed, I can get back to this anytime later.

**Comment by DragonMaster14545** [comment]
The persistent data is there, the entityJs methode just doesn't seem to have acces to it. For the rest of my scripts its perfectly fine

**Comment by DragonMaster14545** [comment]
So, I just tested it and it worked fine as well. Weird, sorry for annoying you with that then.

**Comment by Su5eD** [comment]
I talked to Lat about this on [discord](https://discord.com/channels/166630061217153024/418125698486632448/1223403525158080522). Unfortunately, there is no way to get around the alias and directly access the field in KubeJS at the moment, sorry. Globally widening fields' access is necessary to prevent package-level conflicts usually doesn't have any side effects. Given that this can also be reproduced without Connector, I'll delegate it to the KubeJS devs to fix.

**Comment by DragonMaster14545** [comment]
Thanks for trying thought
