### ISSUE TITLE
crash with C2ME

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#88]
### Mod Name

C2ME

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/c2me-fabric

### Describe the bug

crash at start

### Steps to reproduce

1. start
2. wait a little
3. see
...

### Logs

https://pastebin.com/RAAvGS3Q

### Additional context

It's not a normal crash and it look like it's C2ME with make something wrong

**Comment by Cixon** [comment]
It doesn’t work out of box. Requires changes to config in order to work.

**Comment by Cixon** [comment]
> what I need to change ?

read the last 7-8 lines of your debug.log after your game crashes. it’ll tell you what mixin is failing. after that, go into c2me.toml and change values from “default” to false

**Comment by Cixon** [comment]
OH one last thing - C2MEs results varies system to system. I have a AMD cpu, and my friend has Intel. We both used the same config in my [modpack](https://legacy.curseforge.com/minecraft/modpacks/ult/files/4728948). Creating a world for me; no issues but, my friend's client crashed when they tried to create theirs. It's odd and not entirely Sinytra's fault. The mod C2ME is still in it's experimental stages, I would recommend shelving it for now or use [Fastload](https://www.curseforge.com/minecraft/mc-mods/fastload) mod

**Comment by coco875** [comment]
ok

**Comment by MichelJonkman** [comment]
[Getting this crash](https://mclo.gs/Yd6jIED) with:

- c2me-fabric-mc1.20.1-0.2.0+alpha.11.5
- Connector-1.0.0-beta.41+1.20.1
- fabric-api-0.92.0+1.11.5+1.20.1

Config:
- noTickViewDistance off
- threadedWorldGen on, without this the mod isn't actually very useful

**Comment by MrCubicYT** [comment]
made an issue in the c2me repository a while back https://github.com/RelativityMC/C2ME-fabric/issues/257

**Comment by MichelJonkman** [comment]
I tried adding compatibility but I got very little support in the Sinytra Connector Discord so I'm still stuck

**Comment by BlackCube4** [comment]
Is there any plan to make this work? I really rely on that mod
