### ISSUE TITLE
Wakes and Explosive Enhancement

### ISSUE THREAD

**Issue by AlexGuy117** [Sinytra/Connector#881]
Tried to run it with Wakes and Explosive Enhancement from 1.20.1, placing all 3 inside a multiplayer modpack for CurseForge required to play on a server and got this error.

"The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "xaero.map.events.Events.handleRenderTick(boolean)" because "xaero.map.WorldMap.events" is null"

**Comment by Su5eD** [comment]
Please follow the mod compatibility issue template as explained in the README

**Comment by AlexGuy117** [comment]
What README exactly?

**Comment by coco875** [comment]
https://github.com/Sinytra/Connector/blob/master/README.md

**Comment by AlexGuy117** [comment]
Did all 3 steps in the Usage Guide. Didn't work.
