### ISSUE TITLE
Incompatible with Wakeful and Explosive Enhancement

### ISSUE THREAD

**Issue by AlexGuy117** [Sinytra/Connector#882]
### Mod Name

Wakes, Explosive Enhancements

### Mod Homepage

CurseForge, Modrinth

### Minecraft version

1.20.1

### Describe the bug

Crash to launcher with an error code of 1 shortly after the start of mod loading.

### Steps to reproduce

1. Install Sinytra Connector together with Forgified Fabric API and Yet AnotherConfigLib alongside Wakes and Explosive Enhancements into the mod folder containing 100+ mods for a CurseForge modpack required to join a multiplayer server.
2. Launch the CurseForge instance of Minecraft and start playing.
3. Get crash shortly after the red-colored Forge Mod Loader title screen appears as it attempts to load. Uninstalling all 5 of the mods mentioned in "1." removed the problem and the game started normally again.

### Logs

[latest.log](https://github.com/Sinytra/Connector/files/14482182/latest.log)

### Additional context

No additional context at this time.

**Comment by coco875** [comment]
![image](https://github.com/Sinytra/Connector/assets/59367621/889acea2-527c-4ffb-a432-13f73129580a)
100 mods forge are not the minimal set of mods

**Comment by coco875** [comment]
Optifine are not compatible connector since he are closed source

**Comment by AlexGuy117** [comment]
It's not compatible with Optifine at all? Weird. How did i not know this?
Is there some sort of alternative i could try out? I really want to use some blessed mods like even Effective from Quilt for example.

**Comment by coco875** [comment]
> It's not compatible with Optifine at all? Weird. How did i not know this?
> 
> Is there some sort of alternative i could try out? I really want to use some blessed mods like even Effective from Quilt for example.

Hmm maybe he don't mention this on his curseforge page. Alternative you can use is embeddium, oculus if want shader and other mod for his custom ressources pack format

**Comment by coco875** [comment]
Effective say he don't want to be on forge or quilt so you can't run it

**Comment by kakashi1464** [comment]
> Effective say he don't want to be on forge or fabric so you can't run it

https://github.com/hlysine/Effective-Forge-

**Comment by coco875** [comment]
> > Effective say he don't want to be on forge or fabric so you can't run it
> 
> 
> 
> https://github.com/hlysine/Effective-Forge-

Yeah but you need to know how build a java mod

**Comment by AlexGuy117** [comment]
But also alternative to Sinytra Connnector as in? Are there any?

**Comment by coco875** [comment]
But optifine give less performance then mod of optimization with even less compatibility so i recommend you to use mod of optimization instead of optifine

**Comment by kakashi1464** [comment]
> It's not compatible with Optifine at all? Weird. How did i not know this? Is there some sort of alternative i could try out? I really want to use some blessed mods like even Effective from Quilt for example.

What quilt mods do you want to use?

**Comment by AlexGuy117** [comment]
Effective as an example. I wanted to have it for a while now. I remember seeing some other great Quilt mods like this out there.

**Comment by coco875** [comment]
> Effective as an example. I wanted to have it for a while now. I remember seeing some other great Quilt mods like this out there.
> 
> 

By memory there is not a lot of quilt mod with a majority being very similar to other forge/fabric mod and he give a link to have effective on forge. But it's a little hs since its a issue for bug if you want we can continue on discord

**Comment by AlexGuy117** [comment]
> > Effective say he don't want to be on forge or fabric so you can't run it
> 
> https://github.com/hlysine/Effective-Forge-

With the Effective mod, do i put the ZIP in the mods folder/

**Comment by coco875** [comment]
let's continue on discord instead on an issue who don't report correcly the incompat

**Comment by RoomAlex68** [comment]
Another mod that's on quilt mod loader is called: Plants vs Zombies Cubed. It's currently on 1.19 at the moment.
