### ISSUE TITLE
Bewitchment Vampire Error

### ISSUE THREAD

**Issue by adfgdsgf** [Sinytra/Connector#884]
### Mod Name

bewitchment

### Mod Homepage

https://modrinth.com/mod/bewitchment

### Minecraft version

1.20.1

### Describe the bug

Collapse when transforming into a vampire

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/adfgdsgf/de25ba17ffc4e191e4cb50d531cbc093

**Comment by Su5eD** [comment]
Duplicate of #864, will be fixed in the next release

**Comment by adfgdsgf** [comment]
thank！
&nbsp;


白开水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月5日(星期二) 晚上10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sinytra/Connector] Bewitchment Vampire Error (Issue #884)





 
与#864重复，将在下一版本中修复
 
—
直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了该主题。消息 ID：<Sinytra/Connector/issues/884/1978896057 @ github 。com&gt;
