### ISSUE TITLE
Crash using Ultracraft and Iron's Spell and Spellbooks

### ISSUE THREAD

**Issue by vred1** [Sinytra/Connector#885]
### Mod Name

Iron's Spell and Spellbooks

Ultracraft

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

https://www.curseforge.com/minecraft/mc-mods/absolute-ultracraft/

### Minecraft version

1.20.1

### Describe the bug

Crash, probably caused by mixin conflict

### Steps to reproduce

1. Download Connector
2. Download [Ultracraft](https://www.curseforge.com/minecraft/mc-mods/absolute-ultracraft)
3. Download [Iron's Spells 'n Spellbooks](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
4. Launch game
5. Crash while loading bootstrap resources
![image](https://github.com/Sinytra/Connector/assets/162346502/8a40c683-519c-4fd0-971a-1655c20adb6c)

...

### Logs

https://mclo.gs/OhVFNUS

### Additional context

List of mods:
![image](https://github.com/Sinytra/Connector/assets/162346502/6a9ecd6c-43bc-47a2-b581-ffe131267162)

**Comment by Su5eD** [comment]
> [05mar2024 17:07:34.478] [Client Shutdown Thread/WARN] [mixin/]: `@Redirect` conflict. Skipping mixins.irons_spellbooks.json:LocalPlayerMixin from mod irons_spellbooks->`@Redirect`::addSlowdownCondition(Lnet/minecraft/client/player/LocalPlayer;)Z with priority 1000, already redirected by ultracraft.mixins.json:client.ClientPlayerEntityMixin from mod ultracraft->`@Redirect`::redirectIsUsingItem(Lnet/minecraft/client/player/LocalPlayer;)Z with priority 1000

This is a conflict between the two mods and should be reported to their respective authors.
