### ISSUE TITLE
Enchancement Crash Persisting

### ISSUE THREAD

**Issue by twohundredangels** [Sinytra/Connector#886]
### Mod Name

Enchancement

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/enchancement

### Minecraft version

1.20.1

### Describe the bug

Game crashes when trying to load into enchancement; looks to be a mixin issue.

### Steps to reproduce

1. Load necessary mods.
2. Load up game.
3. Crash

### Logs

https://mclo.gs/ZFoyh6E

### Additional context

Does not occur with enchancement 1.20.1-8; but if on a heavier modpack, will crash regardless with a log of 'https://mclo.gs/b0bHylT'

**Comment by Matyrobbrt** [comment]
Please downgrade to Forge `47.1.3` as it is the only Forge version we support.
