### ISSUE TITLE
Random crash when exploring with the crash log mentioning Better Nether

### ISSUE THREAD

**Issue by cal1407** [Sinytra/Connector#887]
### Mod Name

Better Nether

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betternether

### Minecraft version

1.20.1

### Describe the bug

Game crash randomly when exploring the world. Reloading the save would cause the game to crash at the same exact spot.

### Steps to reproduce

1. Launch the game
2. Create a new save
3. Explore around the world a bit
...

### Logs

https://pastebin.com/B23MZ3cw

### Additional context

Crash Log: https://pastebin.com/kBY9hEgL

**Comment by BrokenSynapse** [comment]
I had an issue like this, though it wasn't better nether causing the issue directly, every time I would have any sort of issue, the crash log would just spit out that better nether was causing it. I believe for me it ended up being Konkrete and a mod that depended on it, ElytraTrims (Fabric), that one just seemed broken as I couldn't get it to launch on standard fabric either, and better combat.
