### ISSUE TITLE
Modpack work with older version but not with newer version (many errors)

### ISSUE THREAD

**Issue by mateus3c** [Sinytra/Connector#888]
### Mod Name

unsure

### Mod Homepage

unsure

### Minecraft version

1.20.1

### Describe the bug

many errors occur when using the most up-to-date version of connector and connector extras (those errors do not occur with older versions)

### Steps to reproduce

Versions that work fine:
- Connector-1.0.0-beta.36+1.20.1
- ConnectorExtras-1.9.2+1.20.1

[old_ver - CONSOLE.log](https://github.com/Sinytra/Connector/files/14511296/old_ver.-.CONSOLE.log)
[old_ver.log](https://github.com/Sinytra/Connector/files/14511292/old_ver.log)

Versions that crash:
- Connector 1.0.0-beta.37+1.20.1
- ConnectorExtras 1.10.0+1.20.1
[new_ver - CONSOLE.log](https://github.com/Sinytra/Connector/files/14511294/new_ver.-.CONSOLE.log)
[new_ver.log](https://github.com/Sinytra/Connector/files/14511295/new_ver.log)

Nothing was changed besides the Connector and ConnectoreExtras versions. I'm aware of the changes made on the config files, so that wasn't the cause of the crash.

### Logs

.

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
