### ISSUE TITLE
Nvidium doesn't seem to work anymore.

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#889]
### Mod Name

Nvidium

### Mod Homepage

https://modrinth.com/mod/nvidium

### Minecraft version

1.20.1

### Describe the bug

I thought it was somehow related to Embeddium, so I made a report and explained everything there: https://github.com/embeddedt/embeddium/issues/227
I am using the latest versions of everything.

**Comment by Su5eD** [comment]
I've tried running Nvidium on Connector beta 37 with the latest Embeddium version and it works completely fine. Make sure your configuration is correct, as the global mod alias config has been merged into `connector.json` with beta 37. You can find my configuration below, hope it helps.

`connector.json`
```json
{
  "version": 1,
  "hiddenMods": [],
  "globalModAliases": {
    "embeddium": "sodium"
  }
}
```

`fabric_loader_dependencies.json`
```json
{
  "version": 1,
  "overrides": {
    "nvidium": {
      "-depends": {
        "sodium": "ignored"
      }
    }
  }
}
```

**Comment by Wanderer70** [comment]
Thank you! Yes, I had to update the config format. Sorry, hadn't noticed that it got changed!
