### ISSUE TITLE
AdventureZ don't dectect cloth forge version

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#89]
### Describe the bug

AdventureZ don't dectect cloth forge version but other mod who use it detect it

### Steps to reproduce

1. Have conector, ffapi, cloth forge and advenureZ
2. run
3. and see the warn
...

### Additional context

![image](https://github.com/Sinytra/Connector/assets/59367621/18f5b794-50dc-483a-8c91-e35b27281e77)

**Comment by Su5eD** [comment]
AdventureZ declares a dependency on modid `cloth-config2`, which is not provided by cloth config on forge. You'll need to use a dependency override to replace the dependency with `cloth_config` instead. This is explained in #67.
