### ISSUE TITLE
Spectrum server crash on Forge 47.2.20

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#892]
### Mod Name

Spectrum

### Mod Homepage

spectrum - Minecraft Mods - CurseForge

### Minecraft version

1.20.1

### Describe the bug

https://www.curseforge.com/minecraft/mc-mods/spectrum

### Logs

https://gist.githubusercontent.com/EndangeredNayla/7e5a543b3f5b7e13aaf0e88f00a8f7f0/raw/d181cff826e0728229051a28858221154dab3865/gistfile1.txt

**Comment by unilock** [comment]
It's recommended that Sinytra Connector be run on Forge 47.1.3 specifically:

> When reporting bugs, please make sure you are using the latest release of Connector and Forgified Fabric API, as well as **Forge 47.1.3** on Minecraft 1.20.1

I, personally, have not had any issues with Spectrum on that Forge version (after most Connector-related issues were fixed on Spectrum's side some weeks ago).

**Comment by Su5eD** [comment]
Confirmed to work on Forge 47.1.3
