### ISSUE TITLE
[suggestion] make a mod like this but instead of fabric on forge, it's forge on fabric (1.20.1)

### ISSUE THREAD

**Issue by randomultrakillplayer** [Sinytra/Connector#894]
i wanted to play gun mods on fabric, but because of 90% of the gun mods being on forge, i need a connector and patchwork are outdated for a long long time

**Comment by RoomAlex68** [comment]
However, due fabric being a lightweight mod loader and forge being a heavyweight mod loader. It will be much more difficult to get Forge on Fabric.

**Comment by randomultrakillplayer** [comment]
ok
