### ISSUE TITLE
DungeonZ : crash with mouseClicked event handler.

### ISSUE THREAD

**Issue by Yldales** [Sinytra/Connector#896]
### Mod Name

DungeonZ

### Mod Homepage

* https://modrinth.com/mod/dungeonz
* https://github.com/Globox1997/DungeonZ

### Minecraft version

1.20.1

### Describe the bug

Minecraft crash after trying to create a new singleplayer world.

### Steps to reproduce

1. Launch the game.
2. Create a new singleplayer world.

### Logs

https://gist.github.com/Yldales/659c96048e3ae70e39de243d766b8306

### Additional context

- Tested with the latest version of Connector (beta.37) and latest nightly (beta.38-dev-g5f7c70b).
- Tested with a minimal set of mods (Connector and its dependencies, DungeonZ and its dependencies).

**Comment by Sazuzaki** [comment]
Can confirm. This also happens when loading any datapack from a global loader mod like Openloader or Global Packs.

**Comment by captainharrie** [comment]
Also happening for me with the fabric versions of any of YUNG's "better [xyz]" mods, log attached just in case it provides more insight:
[crash-2024-03-22_04.12.08-client.txt](https://github.com/Sinytra/Connector/files/14717222/crash-2024-03-22_04.12.08-client.txt)

**Comment by Sazuzaki** [comment]
My issue regarding Openloader randomly fixed itself, not sure what happened.
