### ISSUE TITLE
Linkart crash on start

### ISSUE THREAD

**Issue by HawKDesigns** [Sinytra/Connector#898]
### Mod Name

Linkart

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/linkart-updated

### Minecraft version

1.20.1

### Describe the bug

It crashes on startup no matter if a its a clean install or with other mods

### Steps to reproduce

1.Install all dependencies 
2.Press Play Minecraft
3.Crash

### Logs

just says Error 1

**Comment by melontini** [comment]
Mixin crash https://gist.github.com/melontini/2ba1d6c5010f9abd747e054f9fffdf6c
