### ISSUE TITLE
connector incompatible with alternate current

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#90]
### Mod Name

alternate current

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/alternate-current

### Describe the bug

crash at the startup

### Steps to reproduce

1. have ffapi, connector, atlernate current
2. run the game
3. and he crash

### Logs

https://pastebin.com/1EPcT4c1

### Additional context

![image](https://github.com/Sinytra/Connector/assets/59367621/9c0aef38-844b-45c5-ad4c-104ff4672f48)

**Comment by Su5eD** [comment]
Alternate Current provides an invalid forge modid (`alternate-current`). This is an issue with the mod itself, as it happens without connector, too. See https://github.com/SpaceWalkerRS/alternate-current/issues/30
