### ISSUE TITLE
EPIC GAME with RPG PALADIN WIZARD AND ARCHER 

### ISSUE THREAD

**Issue by Aladire** [Sinytra/Connector#900]
### Mod Name

Epic Game

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft version

1.20.1

### Describe the bug

Texture not compatible 

### Steps to reproduce

![image](https://github.com/Sinytra/Connector/assets/149100987/9ee5e0fa-10d2-44aa-9b83-6f4ea541f1d0)

Who is probleme ! 

### Logs

Texture not compatble

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
