### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by a3sthos** [Sinytra/Connector#901]
### Mod Name

Connector

### Mod Homepage

.

### Minecraft version

1.20.1

### Describe the bug

I can't open modded minecraft server

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/a3sthos/575325eb5352b72ec39461750b38c785#file-gistfile1-txt

### Additional context

dynamiclightsreforged-1.20.1_v1.6.0.jar           
fabric-renderer-api-v1-3.2.1+1d29b44577.jar      
geckolib-forge-1.20.1-4.4.2.jar                   
Player-Animator-Mod-Forge-1.20.1.jar              
botarium-forge-1.20.1-2.3.3.jar                 
fabric-item-api-v1-2.1.28+2272fc7f77.jar        
firstperson-forge-2.3.4-mc1.20.1.jar          
fabric-rendering-fluids-v1-3.0.28+4ac5e37a77.jar 
naturalist-forge-4.0.3-1.20.1.jar               
fabric-models-v0-0.4.2+7c3892a477.jar           
dynamiclights-1.20.1.2.jar                  
immersive_aircraft-0.7.4+1.20.1-forge.jar      
IronJetpacks-1.20.1-7.0.3.jar                  
fabric-convention-tags-v1-1.5.5+fa3d1c0177.jar  
Controlling-forge-1.20.1-12.0.2.jar          
Prism-1.20.1-forge-1.0.5.jar                   
Placebo-1.20.1-8.6.1.jar                       
modernfix-forge-5.14.0+mc1.20.1.jar             
fabric-command-api-v1-1.2.34+f71b366f77.jar    
lootintegrations-1.20.1-3.4.jar            
fabric-block-view-api-v2-1.0.1+0767707077.jar   
fabric-command-api-v2-2.2.13+561530ec77.jar       
fabric-data-attachment-api-v1-1.0.0+30ef839e77.jar
mixinextras-forge-0.2.0-beta.8.jar      
Bookshelf-Forge-1.20.1-20.1.9.jar  
AchievementOptimizer-1.20.1-1.0.1.jar     
Apotheosis-1.20.1-7.3.1.jar             
mcw-doors-1.1.0forge-mc1.20.1.jar     
cave_dweller-1.20.1-1.7.0.jar        	
PickUpNotifier-v8.0.0-1.20.1-Forge.jar    
fabric-screen-api-v1-2.0.8+45a670a577.jar   
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar   
JustEnoughResources-1.20.1-1.4.0.247.jar   
cloth-config-11.1.118-forge.jar       
soundphysics-forge-1.20.1-1.1.2.jar    
fabric-api-0.92.0+1.11.3+1.20.1.jar       
dummmmmmy-1.20-1.8.14.jar             
fabric-content-registries-v0-4.0.11+a670df1e77.jar
twilightforest-1.20.1-4.3.2145-universal.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar   
embeddium-0.3.7+mc1.20.1.jar           
industrial-foregoing-1.20.1-3.5.15.jar   
handcrafted-forge-1.20.1-3.0.6.jar     
fabric-game-rule-api-v1-1.0.40+683d4da877.jar    
fabric-api-lookup-api-v1-1.6.36+67f9824077.jar
mcw-fences-1.1.1-mc1.20.1forge.jar 
Botania-1.20.1-443-FORGE.jar           
resourcefulconfig-forge-1.20.1-2.1.2.jar   
pamhc2foodextended-1.20-1.0.0.jar          
curios-forge-5.7.0+1.20.1.jar                   
Patchouli-1.20.1-84-FORGE.jar                  
oculus-mc1.20.1-1.6.15a.jar               
Searchables-forge-1.20.1-1.0.2.jar          
ApothicAttributes-1.20.1-1.2.1.jar         
elevatorid-1.20.1-1.8.15.jar 
Connector-1.0.0-beta.37+1.20.1-mod.jar         
tombstone-1.20.1-8.6.3.jar  
fabric-entity-events-v1-1.6.0+6274ab9d77.jar      
resourcefullib-forge-1.20.1-2.1.23.jar     
architectury-9.2.14-forge.jar              
Panorama-Creator-Mod-Forge-1.20.1.jar      
fabric-loot-api-v2-1.2.1+eb28f93e77.jar     	
mcw-furniture-3.2.2-mc1.20.1forge.jar       
cupboard-1.20.1-2.5.jar                     
ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar   
dynamic-fps-3.4.2+minecraft-1.20.4-forge.jar  
fabric-rendering-data-attachment-v1-0.3.37+a6081af
fabric-networking-api-v1-1.3.11+503a202477.jar  
Towns-and-Towers-1.12-Fabric+Forge.jar
Vein-Mining-Mod-Forge-1.20.1.jar
EnchantingInfuser-v8.0.2-1.20.1-Forge.jar 
fabric-lifecycle-events-v1-2.2.22+afab492177.jar
fabric-key-binding-api-v1-1.0.37+561530ec77.jar
fabric-client-tags-api-v1-1.1.2+5d6761b877.jar
fabric-transfer-api-v1-3.3.4+b00938ec77.jar
fabric-dimensions-v1-2.1.54+8005d10d77.jar
chiselforge-1.6.0.jar	
Fastload-Reforged-mc1.20.1-3.4.0.jar  
Cucumber-1.20.1-7.0.7.jar              
pamhc2trees-1.20-1.0.2.jar  
fabric-model-loading-api-v1-1.0.3+6274ab9d77.jar
fabric-screen-handler-api-v1-1.3.30+561530ec77.jar
fabric-resource-loader-v0-0.11.10+cefbb70477.jar
fabric-rendering-v1-3.0.8+1c0ea72177.jar  
fabric-renderer-indigo-1.5.1+67f9824077.jar    
Clumps-forge-1.20.1-12.0.0.3.jar              
fabric-mining-level-api-v1-2.1.50+561530ec77.jar  
LibX-1.20.1-5.0.12.jar                 
starlight-1.1.2+forge.1cda73c.jar          
memoryleakfix-forge-1.17+-1.1.5.jar    
ars_nouveau-1.20.1-4.9.0-all.jar       
mythicmounts-20.1-7.4.2-forge.jar 
fabric-particles-v1-1.1.2+78e1ecb877.jar         
puzzlesaccessapi-forge-8.0.7.jar          	
rubidium_extras-1.20.1_v1.4.3.jar             
DungeonsAriseSevenSeas-1.20.x-1.0.2-forge.jar  
forge-1.20.1-47.2.20-universal.jar   
fabric-transitive-access-wideners-v1-4.3.1+1880499
Tarot-Cards-Mod-Forge-1.20.1.jar      
ironchest-1.20.1-14.4.4.jar               
infernalmobs-1.20.1.1.jar        
MythicBotany-1.20.1-4.0.3.jar              
DungeonsArise-1.20.1-2.1.56.1-beta.jar   
client-1.20.1-20230612.114412-srg.jar   
cofh_core-1.20.1-11.0.0.51.jar          
thermal_core-1.20.1-11.0.2.18.jar
thermal_integration-1.20.1-11.0.0.23.jar 
redstone_arsenal-1.20.1-8.0.0.22.jar      
thermal_innovation-1.20.1-11.0.0.21.jar  
thermal_foundation-1.20.1-11.0.2.64.jar  
thermal_expansion-1.20.1-11.0.0.27.jar 
thermal_dynamics-1.20.1-11.0.0.21.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.14.jar 
TerraBlender-forge-1.20.1-3.0.1.4.jar   
BiomesOPlenty-1.20.1-18.0.0.598.jar               
moonlight-1.20-2.11.0-forge.jar              
fabric-api-base-0.4.31+ef105b4977.jar      
Mouse-Tweaks-Mod-Forge-1.20.1.jar     
Better-Combat-Mod-Forge-1.20.1.jar 
titanium-1.20.1-3.8.25.jar
ImmersiveEngineering-1.20.1-10.0.0-169.jar     
fabric-blockrenderlayer-v1-1.1.41+1d0da21e77.jar
Jade-1.20.1-forge-11.7.1.jar           
pamhc2crops-1.20-1.0.3.jar                    
CullLessLeaves-Reforged-1.20.1-1.0.5.jar  
CreativeCore_FORGE_v2.11.24_mc1.20.1.jar   
spectrelib-forge-0.13.14+1.20.1.jar  
fabric-block-api-v1-1.0.11+0e6cb7f777.jar    
fabric-resource-conditions-api-v1-2.3.8+9ad825cd77
cavedust-2.0.0.jar                   
EnderIO-1.20.1-6.0.24-alpha.jar
betterfpsdist-1.20.1-4.3.jar                 
notenoughanimations-forge-1.7.1-mc1.20.1.jar
Iceberg-1.20.1-forge-1.1.18.jar
flywheel-forge-1.20.1-0.6.10-7.jar
create-1.20.1-0.5.1.f.jar
ars_creo-1.20.1-4.0.1.jar 
reliquary-1.20.1-2.0.36.1199.jar 
LegendaryTooltips-1.20.1-forge-1.4.5.jar
pamhc2foodcore-1.20-1.0.0.jar 
fabric-item-group-api-v1-4.0.12+c9161c2d77.jar
thermal_cultivation-1.20.1-11.0.0.22.jar     
Fast-Workbench-Mod-Forge-1.20.1.jar               
polymorph-forge-0.49.2+1.20.1.jar                
almostunified-forge-1.20.1-0.8.1.jar              
jei-1.20.1-forge-15.2.0.27.jar                 
appliedenergistics2-forge-15.0.21.jar             
ae2wtlib-15.2.2-forge.jar                      
entityculling-forge-1.6.2-mc1.20.jar          
fabric-biome-api-v1-13.0.13+dd0389a577.jar       
XaeroPlus-2.0+forge-1.20.1-WM1.37.8-MM23.9.7.jar  
XaerosWorldMap_1.37.8_Forge_1.20.jar         
Xaeros_Minimap_23.9.7_Forge_1.20.jar     
fancymenu_forge_3.1.2_MC_1.20.1.jar            
fabric-registry-sync-v0-2.3.3+1c0ea72177.jar    
appleskin-forge-mc1.20.1-2.5.1.jar              
fabric-recipe-api-v1-1.0.21+514a076577.jar     
ferritecore-6.0.1-forge.jar                      
fabric-object-builder-api-v1-11.1.3+2174fc8477.jar
PuzzlesLib-v8.1.17-1.20.1-Forge.jar              
Corail-Backpack-1.20.1-175.jar                  
fabric-sound-api-v1-1.0.13+4f23bd8477.jar         
fabric-message-api-v1-5.1.9+52cc178c77.jar        
fabric-data-generation-api-v1-12.3.4+369cb3a477.ja
fabric-events-interaction-v0-0.6.2+0d0bd5a777.jar 
createaddition-1.20.1-1.2.3.jar                 
cristellib-1.1.5-forge.jar                   
ad_astra-forge-1.20.1-1.15.18.jar

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
