### ISSUE TITLE
Qu Enchantments Mod & critical errors 

### ISSUE THREAD

**Issue by ilove-sinytraconnector-mod** [Sinytra/Connector#903]
### Mod Name

Qu Enchantments 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/qu-enchantments/files/4670172

### Minecraft version

1.20.1

### Describe the bug

The bug is caused by critical errors which make JEI and Forge mods load incorrectly. 

### Steps to reproduce

1. Put Qu enchantments mod into mod folder with sinytra connector and forgified api
2. Loads a bit 
3. Goes into minecraft title screen showing that "JEI and Forge has failed to load correctly."

### Logs

https://pastebin.com/BXtaW4Md

**Comment by Su5eD** [comment]
Please provide your debug log as indicated in the issue template

**Comment by ilove-sinytraconnector-mod** [comment]
Put all of this and the debug log into a paste site?

**Comment by ilove-sinytraconnector-mod** [comment]
My bad, just fixed it
