### ISSUE TITLE
Dedicated server stop working with beta.39+bclib

### ISSUE THREAD

**Issue by liangmoe** [Sinytra/Connector#904]
### Mod Name

Bclib

### Mod Homepage

https://modrinth.com/mod/bclib

### Minecraft version

1.20.1

### Describe the bug

Dedicated server stop working with beta.39+bclib

### Steps to reproduce

1.update connector from beta.37 to beta.39
2.install forge server and bclib with connector
3.server freeze
...

### Logs

debug log: https://mclo.gs/JxVObeG

**Comment by ionutsoran** [comment]
Can confirm this. I am in the exact same situation also got crashed with betterend and betternether mods

**Comment by heipiao233** [comment]
Sinytra Connector loads some client-only mods on dedicated server. I don't think #908 (2bc9aee) fixes this properly.
