### ISSUE TITLE
[1.20.1] Connector beta38+39 crashes when updated.

### ISSUE THREAD

**Issue by Starexify** [Sinytra/Connector#909]
### Minecraft version

1.20.1

### Describe the bug

The last 2 versions of Connector crash

### Steps to reproduce

1. Install Connector with some fabric mods and forge mods and crash.
2.
3.
...

### Logs

https://pastebin.com/BhHc4XcB

### Additional context

I am not sure what mod does that really.

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
