### ISSUE TITLE
Medieval Weapons Crash

### ISSUE THREAD

**Issue by Megaboy809** [Sinytra/Connector#914]
### Mod Name

Medieval Weapons

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/medievalweapons

### Minecraft version

1.20.1

### Describe the bug

The game crashes and says that it couldn't initialize client because of errors provided by Medieval Weapons

### Steps to reproduce

1.Start Game with medieval weapons
2.Wait until it crashes
3.There you go!

### Logs

Not Available

### Additional context

I only have sinytra connector and forgified fabric with the mod

**Comment by Su5eD** [comment]
Confirmed to work on Forge 47.1.3 and Connector Beta 39
