### ISSUE TITLE
Starting from beta.37, ETF and EMF will be incompatible and crash during startup phase

### ISSUE THREAD

**Issue by Qee1y** [Sinytra/Connector#915]
### Mod Name

etf and emf

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric/files/all?page=1&pageSize=20

### Minecraft version

1.20.1

### Describe the bug

1

### Steps to reproduce

[2024-03-18-6.log](https://github.com/Sinytra/Connector/files/14639013/2024-03-18-6.log)

### Logs

1

### Additional context

1

**Comment by Su5eD** [comment]
The linked mod, [ETF](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric/download/5079833), works fine for me. Please provide further details.

**Comment by Qee1y** [comment]
Strangely, I have never experienced any breakdown again. Prior to this, I upgraded 36beta to 37 or higher and crashed during the startup phase, deleting ETF, EMF, and connector configuration files. I have not experienced any crashes since then.
