### ISSUE TITLE
boss of mass destruction need fabric version of kotlin

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#92]
### Describe the bug

he require fabric kotlin and don't work with forge kotlin

### Steps to reproduce

1. have boss of mass destruction and it's dependence, ffapi, connector
2. run
3. see
...

### Logs

https://pastebin.com/JzGwFKnd

**Comment by Su5eD** [comment]
This is expected behavior; forge and fabric language providers are not interchangeable. You need to use Fabric Language Kotlin, which is compatible with Connector

**Comment by coco875** [comment]
oh ok I think it's the same like other lib
