### ISSUE TITLE
The Dawn Era - Crash on Server after World Load

### ISSUE THREAD

**Issue by Oliviafrostpaw** [Sinytra/Connector#920]
### Mod Name

The Dawn Era

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/the-dawn-era

### Minecraft version

1.20.1

### Describe the bug

Once the world loads on the server, it creates a fatal error between dawnera and MiximNaturalSpawner

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/Oliviafrostpaw/d488a246a5a0443b21057baaee33824a

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by MhaWay** [comment]
this happens also when the down era is the only one mod
