### ISSUE TITLE
Crash on using replaymod and immersive portal mod

### ISSUE THREAD

**Issue by R3NxX** [Sinytra/Connector#922]
### Mod Name

Replay Mod

### Mod Homepage

https://www.replaymod.com/

### Minecraft version

1.20.1

### Describe the bug

I use Sinytra Connector mod to play replay mod and immersive portal mod in forge. I dont know why it crash, pls help me, thanks

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/R3NxX/9dcce7504ddc99a8357f66e9b48a653e

**Comment by RoomAlex68** [comment]
Replay Mod works on Connector Beta 39

**Comment by RoomAlex68** [comment]
Is it just Immersive Portals that isn't working on Connector beta 39?

**Comment by R3NxX** [comment]
I will try it, Thanks
