### ISSUE TITLE
Mods (Forge and Fabric) that depend on versions of Geckolib above 4.2.2 do not work (Using Fabric Geckolib and Connector Extras)

### ISSUE THREAD

**Issue by MCCrafter247** [Sinytra/Connector#923]
### Mod Name

Enderman Overhaul, Forge version of Bosses of Mass Destruction

### Mod Homepage

https://modrinth.com/mod/enderman-overhaul https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction-forge

### Minecraft version

1.20.1

### Describe the bug

When you load any mod that relies on a newer version of Geckolib than 4.2.2, the game fails to load and crashes, even when I have a newer Geckolib fabric version installed (I have 4.4.4 in my mods folder, and that loads fine on its own.)

### Steps to reproduce

1. Have Connector and Connector Extras (and their dependencies), a version of Geckolib newer than 4.2.2 fabric, and any mod that requires a newer version of Geckolib than 4.2.2, regardless of that mod's loader. (Examples I've tried are both the forge and fabric versions of Enderman Overhaul, and the forge port of bosses of mass destruction).
2. Try to load the game as you would normally. The load after the typical .connector folder generation crash, which normally works, crashes and complains that there is version 4.2.2 of Geckolib, when the version in the mods folder is actually much newer.

### Logs

https://pastebin.com/cc0N4Tcj

### Additional context

When you load the newer version of Geckolib on its own, it runs just fine, however, the mod list indicates that it is version 4.2.2. I'm not sure why this is. I don't know whether this is simply a version label that needs updated, or if this is some deeper issue. Presumably this is a connector extras issue, though, I cannot say for sure since I don't know nor understand the code for either mod.

This is with the current latest versions of forgified fabric api, connector, and connector extras. This issue actually persisted for a while in many earlier versions. My crash log is with a modpack I was trying to make, but this issue seems to persist regardless of what mods do or don't go with it. Also, even having Geckolib fabric 4.2.3 in the mods folder still gives the issue, and all versions in between 4.2.3 and 4.4.4 that I've tested.
![image](https://github.com/Sinytra/Connector/assets/108512960/66172220-f945-497c-9e14-22f8004d4654)

**Comment by RoomAlex68** [comment]
Which Geckolib are you using?

**Comment by Su5eD** [comment]
Please provide an exact list of mods required to reproduce the issue as well as their versions. I've installed BOMD with the following dependencies and my game runs just fine.

![image](https://github.com/Sinytra/Connector/assets/51261569/40e0911f-266b-4268-8709-58c2de2f20fe)

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
