### ISSUE TITLE
Tiered Z crash when reforging

### ISSUE THREAD

**Issue by pietrascoelho** [Sinytra/Connector#927]
### Mod Name

TieredZ

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/tieredz

### Minecraft version

1.20.1

### Describe the bug

Crash when opening Reforging tab on Anvil (on beta 39)

### Steps to reproduce

1. Install all dependencies: AutoTag, ClothConfig (Fabric), LibZ
2. Install TieredZ
3. Boot the title
4. Use anvil
5. Open reforging tab
6. Notice that title crashes

### Logs

https://paste.atlauncher.com/view/a4ca698a-9697-460b-a34e-55d3e20462be

### Additional context

Forge "version" is not the same, though can't be used as replacament.
Tested on Connector-1.0.0-beta.39+1.20.1

**Comment by Su5eD** [comment]
This is a known issue with TieredZ - you're using an outdated version of libz. See https://github.com/Globox1997/tiered/issues/97

**Comment by pietrascoelho** [comment]
@Su5eD TY!!! Sorry for bothering
