### ISSUE TITLE
crash when launching

### ISSUE THREAD

**Issue by kittenvr** [Sinytra/Connector#929]
### Mod Name

i dont know 

### Mod Homepage

https://mclo.gs/JWl8LrL

### Minecraft version

1.20.1

### Describe the bug

when launching i crash

### Steps to reproduce

1 use same mods as me 
launch game

### Logs
https://mclo.gs/JWl8LrL

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
