### ISSUE TITLE
crash with Brewin' And Chewin'

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#93]
### Mod Name

Brewin' And Chewin'

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin-fabric

### Describe the bug

crash at start

### Steps to reproduce

1. install connector, ffapi, Brewin' And Chewin', forge version of famer delight
2. Run
3. See

### Logs

https://pastebin.com/BeHQ4GuU

**Comment by Abbie5** [comment]
the forge and fabric versions of farmer's delight don't have the same api's, or even the same base package, so fabric farmer's delight addons don't work on the forge version of farmer's delight

**Comment by Abbie5** [comment]
there's a forge version of brewin' and chewin' you can use instead https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin

**Comment by coco875** [comment]
so how to solve this because this mean if I have an addon on fabric and one on forge I need to have also two time farmer delight the forge and the fabric version and i guess make every item in double or crash

**Comment by coco875** [comment]
> there's a forge version of brewin' and chewin' you can use instead https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin

oh i don't see it
