### ISSUE TITLE
Faster random + particle core + spectrum mixin issue

### ISSUE THREAD

**Issue by ghost** [Sinytra/Connector#933]
### Mod Name

Faster random

### Mod Homepage

https://modrinth.com/mod/faster-random/version/3.0.2

### Minecraft version

1.20.1

### Describe the bug

Start up crash when particle core and fater random is present

### Steps to reproduce

Install mods 
![image](https://github.com/Sinytra/Connector/assets/146892171/09d90acf-988d-4e91-9341-b9e59b60000a)
Launche the game

### Logs

https://gist.github.com/Tomat777/0332e95d7ba919c6815f2ec4120d1f03

### Additional context

Doesnt happen on fabric.

**Comment by unilock** [comment]
I've had this happen to me in a Quilt modpack, completely separate from Sinytra Connector. I took it to mean something was wrong with Faster Random, but I was never able to figure out what, so I just removed it...
