### ISSUE TITLE
It will crash if you change the mod settings.

### ISSUE THREAD

**Issue by YKITV7I7T7T** [Sinytra/Connector#934]
### Minecraft version

1.20.1

### Describe the bug

I changed the settings of the midnightcontrols mod and it crashed when I started the game again.

### Steps to reproduce

1.The first step is to install midnightcontrols and start the game
2.Go to Key Binds and there will be a game joystick icon next to it. Click on it and change a setting called Virtual Mouse.
3.Then restart the game and it will crash
...

**Comment by YKITV7I7T7T** [comment]
I use google translate and if something looks weird that's why

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
