### ISSUE TITLE
[1.20.1 FORGE] BCLIB 3.0.14 Server crash with Sinytra Connector 1.0.0b 40+

### ISSUE THREAD

**Issue by UmbrellaDevelopment** [Sinytra/Connector#936]
### Mod Name

BCLIB

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bclib/files/4971470

### Minecraft version

1.20.1

### Describe the bug

Server don't launch and crash with fatal error in early loading

### Steps to reproduce

1. Install my modpack containing Sinytra Connector 1.0.0 beta 40+ (1.20.1), BCLib 3.0.14 (1.20.1), BetterEnd 4.0.11 (1.20.1) and Fabric API 0.92.0 1.11.3 (1.20.1)
2. Put it on a server with forge 47.2.0 or 47.2.21
3. The server will crash
...

### Logs

https://pastebin.com/VCFiFbGd

### Additional context

When I disable the following mods it works perfectly. It works in client side and I had no crash while testing. I tried with only these mods and nothing else, it crashes with the same error.

I'm open for detailing the issue

**Comment by Su5eD** [comment]
I might have an idea of what's going on. Did you copy your entire mods folder from a client to the server after the .connector folder was generated? Connector only strips sided code when transforming jars, therefore running the client and then copying the output jars to a server will leave client-only code in them.

**Comment by Su5eD** [comment]
This should be solvable by caching the side as part of the input files, which will prompt jars to be transformed again when accidentally moved between a client and server.

**Comment by UmbrellaDevelopment** [comment]
Yep I done this, this should be the issue then, I'll try deleting the .connector and let your code generate this folder again, thanks !

**Comment by UmbrellaDevelopment** [comment]
Update : it fixed the issue, thank you for your fast answer and courtesy !
