### ISSUE TITLE
REI crash

### ISSUE THREAD

**Issue by erialsan** [Sinytra/Connector#937]
### Minecraft version

1.20.1

### Describe the bug

crash REI

### Steps to reproduce

1 click REI recipe "crafting" 
2 crash game
3 cant start game

### Logs

https://mclo.gs/kAQQ9v4

### Additional context

REI? TechReborn? Mekanism? RefinedStorage? Immersive engineering?

**Comment by Su5eD** [comment]
Hi, thanks for reporting this. Upon looking at the log, it seems like this crash is coming from Ad Astra interacting with REI. Please forward the issue to them.

> java.lang.ClassCastException: class `me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay` cannot be cast to class `earth.terrarium.adastra.common.compat.rei.displays.CompressingDisplay` (me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay is in module rei_plugin_compatibilities@12.0.93 of loader 'TRANSFORMER' @5737d116; earth.terrarium.adastra.common.compat.rei.displays.CompressingDisplay is in module ad_astra@1.15.18 of loader 'TRANSFORMER' @5737d116)
