### ISSUE TITLE
Immersive Portals (Fabric) crashes with Valkyrien Skies (Forge)

### ISSUE THREAD

**Issue by Byllfighter** [Sinytra/Connector#938]
### Mod Name

Immersive Portals

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod

### Minecraft version

1.20.1

### Describe the bug

Minecraft crashes on loading

### Steps to reproduce

1. Launch Minecraft

### Logs

https://gist.github.com/Byllfighter/c5f425b1bc088f34102c1d1a9db2b918

### Additional context

Mod list:
- Connector-1.0.0-beta.40+1.20.1.jar
- ConnectorExtras-1.10.0+1.20.1.jar
- create-1.20.1-0.5.1.f.jar
- fabric-api-0.92.0+1.11.3+1.20.1.jar
- immersive-portals-3.3.9-mc1.20.1-fabric.jar
- kotlinforforge-4.10.0-all.jar
- valkyrienskies-120-2.1.3-beta.1.jar

**Comment by Su5eD** [comment]
> `@At("INVOKE")` on net/minecraftforge/common/extensions/IForgePlayer::wrapDistanceInHandleBlockBreakAction with priority 1000 cannot inject into net/minecraftforge/common/extensions/IForgePlayer::canReach(Lnet/minecraft/core/BlockPos;D)Z merged by org.valkyrienskies.mod.forge.mixin.feature.forge_interact.MixinIForgePlayer with priority 1000

This is unfortunately a direct conflict between Immersive Portals and Valkyrien Skies. I've tried changing the priority of extracted mixin, but the injectors would still clash. As such, it cannot be fixed on Connector's side, sorry.
