### ISSUE TITLE
CameraOverhaul Incompatible past v36

### ISSUE THREAD

**Issue by nolanmaster99** [Sinytra/Connector#942]
### Mod Name

CameraOverhaul

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/cameraoverhaul

### Minecraft version

1.20.1

### Describe the bug

The game opens and says I need cloth-config v4.8.3 (which doesn't exist). Only happens in connector versions past v36

### Steps to reproduce

1. Install CameraOverhaul + Connector v37+
2. Run Minecraft
3.
...

### Logs

https://gist.github.com/nolanmaster99/cbad8423803314d0ff71427a31a4281b

**Comment by Su5eD** [comment]
> [14:21:22] [Render thread/FATAL]: Error during pre-loading phase
>net.minecraftforge.fml.ModLoadingException: Some of your mods are incompatible with the game or each other!
>A potential solution has been determined, this may resolve your problem:
>   - Install §6cloth-config2§r, version 4.8.3 or later.
>More details:
>   - §Emod Camera Overhaul (cameraoverhaul)§r 1.4.0-fabric-universal requires version 4.8.3 or later of §6cloth-config2§r, which is >missing!

Do you have cloth config installed? If so, you might also be missing a mod alias. Try deleting your `config/connector.json` file, which will prompt regenerating the default values.

**Comment by nolanmaster99** [comment]
I deleted the connector.json file and it works now, thank you so much for the help
