### ISSUE TITLE
The Explosion FX from the "Explosion Enhancement" mod isn`t visible on Aternos Server

### ISSUE THREAD

**Issue by Ford3l** [Sinytra/Connector#947]
### Mod Name

"Explosion Enhancement"

### Mod Homepage

https://modrinth.com/mod/explosive-enhancement/version/1.1.0-1.20.x

### Minecraft version

1.20.1

### Describe the bug

I don`t see explosion FX from the "Explosion Enhancement" mod on Aternos server(I see FX in singleplayer). I Already wrote to the author of the "Explosion Enhancement" and he say: "Are your particle settings set to "all"? (Found in Options > Video Settings > Particles for vanilla. Also found in Options > Video Settings > Quality > Particles for Sodium", i use Embeddium(my particle setting set to "all") and i decided to write to you, in case there is a problem on your part

### Steps to reproduce

1.
2.
3.
...

### Logs

In "Addirional context"

### Additional context

[latest.log](https://github.com/Sinytra/Connector/files/14793915/latest.log)

**Comment by Su5eD** [comment]
I've tried installing the mod on a server and all particles were displayed correctly, even when embeddium was installed on both sides. The log also mentions more mods installed than just the one you listed.

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
