### ISSUE TITLE
Cannot run Immersive Portals

### ISSUE THREAD

**Issue by Gladosator** [Sinytra/Connector#952]
### Discussed in https://github.com/Sinytra/Connector/discussions/12
I tried every version of Immersive Portals and yet every one of them either failed at launch or when generating / preloading a Minecraft world
<div type='discussions-op-text'>

<sup>Originally posted by **Su5eD** August  8, 2023</sup>
# Mod Compatibility

A maintained list of known mods and compatibility state in regards to Connector.

### Help us test!

We welcome any help. If you have tested or experienced issues with a mod and would like let us know, just comment on this post and we'll look into listing the mod. Thanks!

### Compatibility statuses

- ✅Compatible - This mods is tested and verified to be compatible with Connector
- ⚠️Functional - This mod loads with Connector, but might contain bugs
- ❌Incompatible - This mod is not compatible with Connector

# Status list

| 📦 Mod Name | 🔗 Link | ❓ Status | 🗒️ Notes |
|:------:|:------:|:------:|:------:|
| LambDynamicLights | [Modrinth](https://modrinth.com/mod/lambdynamiclights) | ✅ |  |
| Tech Reborn | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/techreborn) | ✅ |  |
| Terrestria | [Modrinth](https://modrinth.com/mod/terrestria) | ✅ |  |
| Traverse | [Modrinth](https://modrinth.com/mod/traverse) | ✅ |  |
| Immersive Portals | [Modrinth](https://modrinth.com/mod/immersiveportals) | ✅ |  |
| amecs api | [GitHub](https://github.com/Siphalor/amecs-api) | ❌ | Conflicting mixins with Forge's keybind API |
| Forge Config API Port | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric) | ❌ | Provides modified versions of Forge config classes | 
| Reach Entity Attributes | [GitHub](https://github.com/JamiesWhiteShirt/reach-entity-attributes) | ❌ | Conflicts with Forge attribute modifiers |
| Sodium | [Modrinth](https://modrinth.com/mod/sodium) | ❌ | Conflicts with Forge's Early Loading Screen |
| FREX | [Modrinth](https://modrinth.com/mod/frex) | ❌ | Conflicts with Forge's rendering pipeline |
| Indium | [Modrinth](https://modrinth.com/mod/indium) | ❌ | Conflicts with Forge's rendering pipeline |</div>

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
