### ISSUE TITLE
Latest Everycompat crash

### ISSUE THREAD

**Issue by Ryuushen** [Sinytra/Connector#954]
### Mod Name

Everycompat

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/every-compat

### Minecraft version

1.20.1

### Describe the bug

Crash with latest Everycompat update

### Steps to reproduce

1.
2.
3.
...

### Logs

https://mclo.gs/X54rJwM

**Comment by Su5eD** [comment]
I've downloaded everycompat and it runs fine on its own. You log mentions you have a lot of other mods installed, so it's hard to determine the real cause of the crash.

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
