### ISSUE TITLE
[1.20.1] Craftify crash with Connector

### ISSUE THREAD

**Issue by Starexify** [Sinytra/Connector#959]
### Mod Name

Craftify

### Mod Homepage

https://modrinth.com/mod/craftify

### Minecraft version

1.20.1

### Describe the bug

When I try to load Craftify with Connector. They crash

### Steps to reproduce

1. Install Craftify alongside Fabric Language Kotlin(dependency) and Connector
2. Try to run them and startup crash without crashlog

### Logs

https://gist.github.com/Starexify/e726a19a1cdd4197b76c9dc14cb2f202

### Additional context

Doesn't matter if this gets fixed. I just hope for more compatibility

**Comment by Su5eD** [comment]
> Caused by: java.lang.LayerInstantiationException: Class loader (instance of): 'TRANSFORMER' @3e2772a9 tried to define prohibited package name: java.tech.thatgravyboat.craftify.mixin
	at java.base/java.lang.ModuleLayer.defineModules(ModuleLayer.java:673)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:81)

Unfortunately, I'm afraid this cannot be fixed on our side. The mod includes classes in a package that begins with `java.`, which is prohibited by the JVM. It works fine on Fabric as they don't use the module system, but Forge does.

That said, it **can** be worked around, but it takes a bit of effort. I recommend forwarding this to the mod devs, as all of these are non-technical changes and are easy to fix without having any side effect on the mod whatsoever.

1. Remove the `java` folder in the jar's root. There are two Minecraft mixins in the jar so I assume this is a duplicate
2. Open each of the nested jars under `META-INF/jars`. Inside each of them, open the `META-INF/MANIFEST.MF` file and change the value of `FMLModType` from `LIBRARY` to `GAMELIBRARY`, which will allow it to access the necessary classes it needs to function.

Make sure the changes are saved to the jar after closing the manifest file (I used WinRar to edit the mod in my case). With this, you should be good to go. I tested the mod with Spotify and it worked as expected.
