### ISSUE TITLE
[1.20.1] The Backrooms Crash Startup

### ISSUE THREAD

**Issue by Starexify** [Sinytra/Connector#960]
### Mod Name

The Backrooms

### Mod Homepage

https://modrinth.com/mod/backrooms

### Minecraft version

1.20.1

### Describe the bug

I try to launch The Backrooms with Connector and it crashes at startup.

### Steps to reproduce

1. Install The Backrooms and Gecko Lib(Dependency) and Connector.
2. Try to launch the game and Crash.

### Logs

https://gist.github.com/Starexify/bfd68c21b88740b81aebae986cebdfe7

### Additional context

Crash Log: https://gist.github.com/Starexify/f8b344c600a4941106a82fde6114a5b3

I opened once an Issue based on this. But I just wanted to see if something changed since it crashes at startup now. It may be the mod at fault. But I just want to make sure. Because reporting compatibility is important.

**Comment by melontini** [comment]
The mod also doesn't work on Fabric due to them using Quilt's `access_widener` key. (Should be `accessWidener`)

**Comment by Su5eD** [comment]
Ah, I should've tested it myself.. thanks a lot. In that case, I'll revert this change and let the mod authors fix the issue on their end.
