### ISSUE TITLE
Feature Placement Crash

### ISSUE THREAD

**Issue by BrandonTheGod06** [Sinytra/Connector#962]
### Mod Name

Sinytra Connector

### Mod Homepage

https://modrinth.com/mod/connector

### Minecraft version

1.20.1

### Describe the bug

Start up a server and walk around for around 5 mins until I reach a certain chunk then crash

### Steps to reproduce

1. Walk around world
2. Crash

### Logs

https://mclo.gs/SQ9l8Y7

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
