### ISSUE TITLE
[1.20.1] [Requires Investigation] Unable to generate Wesley's Roguelike Dungeons using ModernBeta's worldtype

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#964]
### Mod Name

Wesley's Roguelike Dungeons

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/wrd

https://www.curseforge.com/minecraft/mc-mods/modern-beta

### Minecraft version

1.20.1

### Describe the bug

WRD's is not able to naturally generate in ModernBeta's biomes.

### Steps to reproduce

1. Install required mods (Wrd & ModernBeta)
2. Locate wesleys-roguelike-dungeons-config.toml
3. Change false value to true -> CFAllowNaturalDungeons = true
4. Attempt to locate dungeons around the world
/-/-/-/-/-/-/-/-/-/-/-/-/-/

A few things to note, I attempted to make a datapack that'll support the generation in ModernBeta's unique biomes but this did not work either. Reached out to original author as well but to no avail.

![image](https://github.com/Sinytra/Connector/assets/69068153/cf2c8e79-a4ee-4baf-892f-dcfe91c13b42)

### Logs

n/a

**Comment by Cixon** [comment]
Tested using the following:

Connector-1.0.0-beta.40+1.20.1
fabric-api-0.92.0+1.11.3+1.20.1

Neoforge 47.1.99

**Comment by Su5eD** [comment]
Duplicate of #690
