### ISSUE TITLE
All the Textures in Jei Becoming Error

### ISSUE THREAD

**Issue by BerkinBatu** [Sinytra/Connector#965]
### Mod Name

Industrial Revolution,  Mekanism

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/industrial-revolution

### Minecraft version

1.20.1

### Describe the bug

Once a specific item from Mekanism is seen while using it with Industrial Revolution the textures become error

### Steps to reproduce

1.Get Industrial Revolution , Mekanism and Jei
2.Go to a world and open inventory
3.Search "Creative Tank" or "@Mekanism Creative Tank" the texture fails to load and every single texture in jei becomes Error till game restart.
...

### Logs

https://gist.github.com/BerkinBatu/d1f71e1f9b404397651000b3e76212ac

### Additional context

This is my first time making an Issue like this so sorry for any thing that is missing.

**Comment by sisby-folk** [comment]
blueprint is installed and this is asset related, so this might be #919

**Comment by BerkinBatu** [comment]
It could be that but when I remove blueprint while having Industrial Revolution it still turns them into errors

**Comment by Chickn-man** [comment]
Happening for me without blueprint installed, crashes when trying to render the Creative tank in the creative inventory, error shows up in JEI

Crash report after looking up "tank" in creative inventory: https://dl.hlep.site/crash-2024-04-28_17.49.44-client.txt

**Comment by Su5eD** [comment]
![image](https://github.com/user-attachments/assets/9b641a39-faff-4158-b1ac-2de6f7670a36)

Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
