### ISSUE TITLE
Apotheosis with Zephyr and Jewels(RPG Series) Crash on Startup

### ISSUE THREAD

**Issue by Ozbobo** [Sinytra/Connector#969]
### Mod Name

Zephyr

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/zephyr

### Minecraft version

1.20.1

### Describe the bug

Game crashes when launches.

### Steps to reproduce

1.Download Apotheosis with Zephyr and Jewels(RPG Series)
2. You'll also need to add the following in globalModAliases in the connector.json config:
"apotheosis": "zenith"
3. Launch Minecraft
...

### Logs

https://gist.github.com/Ozbobo/a5ae9662f5be5f3a63caa33c53bdb144

### Additional context

I am unaware if this is a Connector issue or a Zephyr and RPG Series issue. The Zephyr mod and Jewels(RPG Series) mods worked perfectly fine when on fabric modloader. When launching on Forge separately with connector Zephyr(with Apotheosis) and Jewels(RPG Series) work fine and cause no issues. Apotheosis and Jewels(RPG Series) also launch perfectly fine.  Zephyr(with Apotheosis)  with the other mods from the RPG Series also launch fine on forge it is just Zephyr(with Apotheosis)  and Jewels(RPG Series) giving an issue. I even Isolated the mods to make sure:
![Mods1](https://github.com/Sinytra/Connector/assets/166033943/354e3e14-47ea-460c-9ddb-a77f0bc1253a)
![Mods2](https://github.com/Sinytra/Connector/assets/166033943/c44585d0-c747-4c5a-925f-8f80a9e8773c)

**Comment by muon-rw** [comment]
The issue seems to be with https://github.com/muon-rw/Zephyr/blob/master/src/main/java/dev/muon/zephyr/mixin/JewelryAttributeMixin.java which is necessary on Fabric for Jewelry to be able to use Attributeslib’s attributes. 

I can look into this a bit more on my end later if needed.

**Comment by muon-rw** [comment]
This specific mixin has been removed, FYI

However, I still have to do [this](https://github.com/muon-rw/Zephyr/blob/master/src/main/java/dev/muon/zephyr/mixin/AttributesMixin.java) to get other mods' attributes to be readable by Jewelry/Spell Engine. 

I'm disabling this if Forge is detected as I imagine it will crash for the same reason, but players on Forge won't be able to add AttributesLib attributes to SpellEngine/Jewelry item configs.

For reference, Apotheosis:
https://github.com/Shadows-of-Fire/Apothic-Attributes/blob/1.20/src/main/java/dev/shadowsoffire/attributeslib/api/ALObjects.java

Zenith:
https://github.com/TheWinABagel/ZenithAttributes/blob/master/src/main/java/dev/shadowsoffire/attributeslib/api/ALObjects.java

**Comment by Su5eD** [comment]
Unfortunately, this cannot be fixed on our end. The crash is a result of Zephyr trying to initialize attributeslib too early, which would work with its Fabric version, but not the Forge one. I'd recommend trying Zephir if none of your other mods require Apotheosis, which should work.
