### ISSUE TITLE
When using the oculus mod and the immersive portal, it crashes from minecraft when shaders are turned on

### ISSUE THREAD

**Issue by Trojankill** [Sinytra/Connector#970]
### Mod Name

oculus

### Mod Homepage

https://modrinth.com/mod/oculus/version/1.20.1-1.6.15a

### Minecraft version

1.20.1

### Describe the bug

I turn on the shaders and enter the world and minecraft crashes

### Steps to reproduce

1.Enable any shaders in the oculus mod
2.Enter any world
3.And wait for the crash of Minecraft
...

### Logs

https://gist.github.com/Trojankill/faf5885ae493b51ba9784f8c89c1629a

### Additional context

Versions mods
oculus 1.6.15a
immersive portal 3.3.3
embeddium 0.3.12
embeddium++ 1.2.4

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
