### ISSUE TITLE
Controlify (v1.6.0) stopped working after updating the Connector to the latest beta.41 from Github Actions

### ISSUE THREAD

**Issue by Tapacywka** [Sinytra/Connector#971]
### Mod Name

Controlify

### Mod Homepage

https://modrinth.com/mod/controlify

### Minecraft version

1.20.1

### Describe the bug

Controlify (v1.6.0) stopped working after updating the Connector to the latest beta.41 from Github Actions

### Steps to reproduce

1. Install Connector, Connector Extras, Forgified Fabric API, Controlify (v1.6.0) and YetAnotherConfigLib (the library to make it work).
2. Attempt to start the client.

### Logs

https://mclo.gs/Ubhi4by (latest.log), https://mclo.gs/IN4nR4d (debug).

### Additional context

Additional crashlog screenshots, which are only displayed in the launcher.
I can't find them in latest or debug, and crash-report is not generated.

![image](https://github.com/Sinytra/Connector/assets/71761232/db484fcd-168f-4142-b49b-04c80f52766b)
![image](https://github.com/Sinytra/Connector/assets/71761232/a4f0a8cd-653c-4ff3-b7b8-1fac36199547)
![image](https://github.com/Sinytra/Connector/assets/71761232/d0148b4c-d32b-4de9-81d3-9fb360aa0b35)

**Comment by Tapacywka** [comment]
https://github.com/Sinytra/Connector/actions/runs/8499984206 - the latest build of beta.41, on which it is still running.
https://github.com/Sinytra/Connector/actions/runs/8544702564 - starting with this beta, it stops working.

**Comment by Su5eD** [comment]
I tested Controlify versions 1.6.0 and 1.7.0, both appears to work fine.

![image](https://github.com/Sinytra/Connector/assets/51261569/19ff5dfd-dbf5-429b-8641-ba21f107d397)

**Comment by Tapacywka** [comment]
> I tested Controlify versions 1.6.0 and 1.7.0, both appears to work fine.
> 
> ![image](https://private-user-images.githubusercontent.com/51261569/319758927-19ff5dfd-dbf5-429b-8641-ba21f107d397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjE5NzIsIm5iZiI6MTcxMjI2MTY3MiwicGF0aCI6Ii81MTI2MTU2OS8zMTk3NTg5MjctMTlmZjVkZmQtZGJmNS00MjliLTg2NDEtYmEyMWYxMDdkMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDIwMTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MDE4ZTIyOWNkMTczMDYxZDgyMjRjN2MzY2I0YzJlMGI5YjUzY2Q0YWFkYzVlMDMyNWM2MzdjYmVjM2NjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DfqHTjnhudz6m6Jp3kYL5__rgyQfvxJrJZwSXadBAdE)

You checked on the penultimate build of beta.41 version, i.e. this one:
![image](https://github.com/Sinytra/Connector/assets/71761232/26446a44-57bc-4de7-bf97-7133c6e5557d)

**Comment by Tapacywka** [comment]
I'm talking about this build:
![image](https://github.com/Sinytra/Connector/assets/71761232/008a6da1-ff2f-4f32-885b-34b24dd8199c)

**Comment by Su5eD** [comment]
Yes I used build 590, you can check that the git hash in the jar version matches

**Comment by Tapacywka** [comment]
> Yes I used build 590, you can check that the git hash in the jar version matches

Oh, I apologize, mistake on my part.
Then that's weird. I'll check again.

**Comment by Tapacywka** [comment]
I'm back with news: Controlify starts crashing the client with the latest build beta.41 if the BadOptimizations mod is present.
Controlify + BadOptimizations works fine with the penultimate build beta.41.

![image](https://github.com/Sinytra/Connector/assets/71761232/d400a853-64a4-4ade-bf78-f979e4a57d4c)

**Comment by Tapacywka** [comment]
I apologize for the lengthy amount of time this has taken. But this is a minimal list of what is needed to reproduce the crash.

**Comment by Tapacywka** [comment]
Controlify is not working again after updating its version to 2.0.0-beta.7 for MC 1.20.1.
The latest working version is 2.0.0-beta.5 for MC 1.20.1 (there is no beta.6 for 1.20.1).
Should I downgrade to a working version or can you see if you can fix the current one?

**Comment by Tapacywka** [comment]
Well, I come bearing sad news. It seems that the mod hasn't worked all this time, although it started up and even detected our controller. Mod version 1.6.0 partially allows us to play through the controller, but the visual GUI (controller buttons) are not shown on the screen, only the Y button that opens chat. That said, after a while (or after certain actions) the game just crashes. I've never been able to find a pattern to freely reproduce this. Since version 2.0.0-beta.1 - the mod still detects the controller and connects to it. The mod settings are accessible through the in-game GUI. But as soon as we enter the world (with the controller connected) - the game crashes. And since version 2.0.0-beta.7 - the game stopped running with it at all. I decided to replace Controlify with Controllable, which officially supports Forge and has exactly the same functionality, but a little different visual design. So in my case the problem is solved. I think it will take a lot of time (and probably nerves) to get this mod to work. So you can close this thread as "not planned" to avoid wasting your time on it.

**Comment by Su5eD** [comment]
Interesting. I just tested 2.0.0 beta 10 on the latest Connector dev build and it runs fine.

**Comment by Tapacywka** [comment]
> Interesting. I just tested 2.0.0 beta 10 on the latest Connector dev build and it runs fine.

Maybe Xander fixed the launch, I haven't looked anymore to the mod since I posted about this error. Have you checked to see if the game crashes when you plug in the controller? If there's no way to test that, I can try it on my ROG Ally.

**Comment by Tapacywka** [comment]
https://mclo.gs/nJz6M1Q
I can start the game, but I can't access mod settings, can't choose my controller. It's just stuck on mods list.

**Comment by Su5eD** [comment]
Does this happen with only controlify installed?

**Comment by Tapacywka** [comment]
> Does this happen with only controlify installed?

Yeah https://mclo.gs/KqAd9X5

**Comment by Tapacywka** [comment]
> What's the crash log? Try using 47.1.3, it could help

Sorry, I was busy yesterday. There is no crash report, because the crash doesn't happen, but the menu just hangs. I assume that the settings menu is rendered in the background, but you can't see it because after opening the settings menu, the menu with the list of mods doesn't disappear. And, yes, exactly the same problem with 47.1.3 Forge.

**Comment by Su5eD** [comment]
That's quite odd. I tested it with a Dualshock 4 controller on Forge 47.1.3 and the Connector nighly dev build. Booted into the menu and was able to play in a world / interact with the creative menu and other inventories as expected.

Here's my mod list for reference.

![image](https://github.com/Sinytra/Connector/assets/51261569/ac49322a-03c2-428e-8aeb-937a84e688e6)

**Comment by Su5eD** [comment]
![2024-06-05_15 41 08](https://github.com/Sinytra/Connector/assets/51261569/6291eeff-5d87-4c32-94e4-e9490641a74b)

**Comment by Tapacywka** [comment]
Oh sh1t, latest dev build? And I'm testing with beta.43 from Modrinth.... I'll check now on the latest dev version, sorry!

**Comment by Tapacywka** [comment]
This situation is kind of unrealistic because nothing has changed for me at all. Here I press settings and that's it, the menu hangs, only the Esc button works, which takes me back to the main game menu. Forge 47.1.3, I will leave the list of mods on the screenshot below. I will also leave a link to latest.log, since there is still no crash-report. https://mclo.gs/vAm8XHq
![image](https://github.com/Sinytra/Connector/assets/71761232/da3b0f8e-0704-489a-9abb-0323d0da21bd)
![image](https://github.com/Sinytra/Connector/assets/71761232/4d7fee9f-f927-435d-ab8c-6ff766360bcc)

**Comment by Tapacywka** [comment]
It turns out that it is the use of the ROG Ally and its built-in controller that is the problem? But before that (Controlify-v2.0.0.0-beta.5, for example) I was able to open settings normally, the controller was displayed, I could download libraries for it, I could customize buttons, etc., but when I entered the world, it crashed.

**Comment by Su5eD** [comment]
> So the problem is with using ROG Ally and its built-in controller?

Dunno. Can you try running the mod on a PC?

**Comment by Tapacywka** [comment]
> > So the problem is with using ROG Ally and its built-in controller?
> 
> Dunno. Can you try running the mod on a PC?

Unfortunately, no. I don't own a PC or a laptop now. This is the reason why I bought the ROG Ally. I will ask someone I know to test the mod on my modpack, and if it doesn't work - on a clean instance with Connector only.

**Comment by Tapacywka** [comment]
https://mclo.gs/pITfsZK - latest.log.
https://mclo.gs/9UANzmy - debug.log.
It's not mine anymore, it's an acquaintance's. He also can't run Controlify on pure Forge 47.1.3 with dependencies. And while I have an AMD processor with integrated graphics on my ROG Ally, he has Intel + NVidia hardware on his PC. So it's not the hardware that's the problem. I have no idea how you managed to get it to work.

**Comment by Tapacywka** [comment]
Ooh, new information. Regarding 3.4.4 YACL he is right, the mod is broken. Regarding the fact that you can generate a config on 1.6.0 and then run 2.0.0-beta.10 - theoretically it will give the same result as 2.0.0-beta.5; you will be able to download libraries, go to the controller settings menu, but the crash during the game will not go anywhere.

**Comment by cmy2008** [comment]
> Ooh, new information. Regarding 3.4.4 YACL he is right, the mod is broken. Regarding the fact that you can generate a config on 1.6.0 and then run 2.0.0-beta.10 - theoretically it will give the same result as 2.0.0-beta.5; you will be able to download libraries, go to the controller settings menu, but the crash during the game will not go anywhere.

okay, i just replace yacl from forge to fabric, then it works! I can use settings without crash.

**Comment by EchoEllet** [comment]
**(Off-topic for Sinytra Connector project)**

For users who want to use Controlify in Forge 1.20.1, consider [Controlify: Forgified](https://modrinth.com/mod/controlify-forgified), an unofficial backport.

Controlify already supports NeoForge 1.21.1+, so it's recommended to move to NeoForge (more future-proof).
