### ISSUE TITLE
Blueprint Crashes with playerAnimator Mod Animations

### ISSUE THREAD

**Issue by SirChamomile** [Sinytra/Connector#972]
### Mod Name

Blueprint Mod Library

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/blueprint

### Minecraft version

1.20.1

### Describe the bug

Spell Engine mods and Blueprint (Team Abnormals Mod Library) are incompatible via Sinytra due to animations.

### Steps to reproduce

1. Install the mods - Spell Engine with an RPG series mod and dependants, and the Blueprint API mod.
2. Hold any item with an animation that leverages the mod playerAnimator. It crashes the game.
3. In a new world, with the forge version of BetterCombat installed, hold any item with a new animation. It crashes the game.
...

### Logs

https://gist.github.com/SirChamomile/4154bbbab225efafcdcb8e0ec7306c85

**Comment by Su5eD** [comment]
Fixed in Forgified Fabric API [0.92.0+1.11.5+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.92.0+1.11.5+1.20.1).
