### ISSUE TITLE
Modern Industrialization Steam Mining drill not working

### ISSUE THREAD

**Issue by SmugSw2** [Sinytra/Connector#973]
### Minecraft version

1.20.1

### Describe the bug

Modern Industrialization steam mining drill can't mine blocks

### Steps to reproduce

1. give yourself a  steam mining drill
2. go into survival 
3. try to drill blocks after giving the drill water and coal

( sometimes , the drill WILL mine, but after that it goes back to not working )

current list of enabled mods
![image](https://github.com/Sinytra/Connector/assets/96033110/cb8ec949-ca1b-49ad-853f-a4a424b07668)
**(shows I am currently on nightly build but this also happens from the version on curseforge)**

**Comment by Su5eD** [comment]
Fixed in Forgified Fabric API [0.92.0+1.11.4+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.92.0+1.11.4+1.20.1).
