### ISSUE TITLE
When using the oculus mod and the immersive portal, it crashes from minecraft when shaders are turned on

### ISSUE THREAD

**Issue by Trojankill** [Sinytra/Connector#974]
### Mod Name

oculus

### Mod Homepage

https://modrinth.com/mod/oculus/version/1.20.1-1.6.15a

### Minecraft version

1.20.1

### Describe the bug

I turn on the shaders and enter the world and minecraft crashes

### Steps to reproduce

1.Enable any shaders in the oculus mod
2.Enter any world
3.And wait for the crash of Minecraft
...

### Logs

https://gist.github.com/Trojankill/172f28cb79e88304cbd10003698afa24

### Additional context

Versions mods
oculus 1.6.15a
immersive portal 3.3.3
embeddium 0.3.12

The previous post became invalid due to the large number of mods, but in this post I launched oculus and immersive portal separately from other mods, and again the error appeared

**Comment by liangmoe** [comment]
For 1.20.1, you can use embeddium-0.2.18, oculua-1.6.9 and immersive portal 3.3.9, they works fine with this combination
