### ISSUE TITLE
BetterEnd crashes

### ISSUE THREAD

**Issue by heyoux** [Sinytra/Connector#975]
### Mod Name

BetterEnd

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betterend

### Minecraft version

1.20.1

### Describe the bug

Crashes

### Steps to reproduce

1. Go to the end
2. Go to the other end islands.
3. Walk for a few minutes then the game will crash.
...

### Logs

https://gist.github.com/heyoux/6f675fc99ad5ee2d265beb5132010063

### Additional context

Crash report: https://gist.github.com/heyoux/d312ff7be0dfa08dc6a4cfc7e2e8df28

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.
