### ISSUE TITLE
[1.20.1][Beta-40] owolib incompatible

### ISSUE THREAD

**Issue by Terra-B-Welch** [Sinytra/Connector#976]
### Mod Name

owolib

### Mod Homepage

https://modrinth.com/mod/owo-lib

### Minecraft version

1.20.1

### Describe the bug

Sinytra connector does not launch, with owolib whatsoever, this occurs regardless if the extras are installed or not.

### Steps to reproduce

1.Load up a modded instance with only forge 47.1.3, forgified fabric api, sinytra connector and owolib, extras is optional.
2.Crash with a read only file error!

### Logs

https://mclo.gs/sDbiOKq

### Additional context

I wasn't going to bother reporting this at first, but then I tested my issue on a fresh multimc instance with the correct version of forge and only the necessary mods(being forgified fabric api, sinytra connector and owolib) installed and replicated the same thing, so I knew it wasn't my modpack being jank.

**Comment by Xplodin** [comment]
This is definitely user error, as I run owolib and many more mods without issues.

Check your drive for anything that is preventing read and write access

**Comment by Terra-B-Welch** [comment]
I am going to state that I am playing on Linux, I do not know if that may cause an issue.
Specifically I have to run modded 1.20.1 through Wine in order to not have a chunk locking issue, I'm not certain if either running on linux or using wine may cause some form of read-only problem.

**Comment by Terra-B-Welch** [comment]
What folder? The mods folder?

**Comment by Terra-B-Welch** [comment]
> Try adjusting the folder's permissions to make sure it's writable, as write perms are necessary for connector's transfomer to save processed jars.

No seriously what folder's permissions do I gotta change cause I tried changing all the folders and files in multimc to read and write and the same issue occurs.

**Comment by Terra-B-Welch** [comment]
Thanks for nothing I guess :s

**Comment by Terra-B-Welch** [comment]
I figured out it's the wine layer I'm using to run my 1.20.1 modpack without the internal server hang issue...
so guess I'm figuring out how to set up read and write perms through wine.
