### ISSUE TITLE
[1.20.1] Connector crash with Early Loading Screen

### ISSUE THREAD

**Issue by Starexify** [Sinytra/Connector#986]
### Mod Name

Early Loading Screen

### Mod Homepage

https://modrinth.com/mod/early-loading-screen

### Minecraft version

1.20.1

### Describe the bug

I tried running this fabric mod and the game crashed on startup. (I mean logic)

### Steps to reproduce

1. Install Early Loading Screen alongside Connector

### Logs

[crash-2024-04-07_11.01.58-client.txt](https://github.com/Sinytra/Connector/files/14896517/crash-2024-04-07_11.01.58-client.txt)
[latest.log](https://github.com/Sinytra/Connector/files/14896518/latest.log)

### Additional context

Just made this for more compatibility no need for a fix to this mod👍

**Comment by Su5eD** [comment]
Support for this mod is not plannes as it clashes with Forge's own early loading screen.
