### ISSUE TITLE
EnvironmentInterface annotation is ignored?

### ISSUE THREAD

**Issue by unilock** [Sinytra/Connector#991]
### Minecraft version

1.20.1

### Describe the bug

It appears that the `@EnvironmentInterface` annotation is ignored; the interface(s) specified in the annotation are still loaded regardless of the side specified, which most commonly leads to crashes on a dedicated server.

### Steps to reproduce

1. Install Forge, Connector, Forgified Fabric API, and a mod that uses `@EnvironmentInterface` to only load certain classes on the client (in my case, [Yttr](https://github.com/unilock/Yttr) + [Lib39](https://github.com/unilock/Lib39)) on a client
2. Start the game; it works fine
3. Set up a dedicated server with the same environment
4. Start the game; it crashes during startup due to client-side classes being loaded on the server

### Logs

debug.log from server: https://gist.github.com/unilock/de839d56129571dc7dee06afcee521f8

### Additional context

Here's an example of `@EnvironmentInterface` usage in Yttr: https://github.com/unilock/Yttr/blob/5ca213d9c3f8d295763a50e3ab1454229ead5eb6/src/main/java/com/unascribed/yttr/content/block/decor/ContinuousPlatformBlock.java#L47

Also, in the above log, I had to use Connector beta 40 instead of beta 41 as the latter wouldn't load Yttr's JiJ'd dependencies for some reason...!?

**Comment by Su5eD** [comment]
I tried running a locally built version of the provided Lib39 fork, but I'm getting an error when running it in my Connector dev env.

> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on lib39-phantom.mixins.json:connectormod.present.MixinEntity from mod lib39_phantom->`@Inject`::lib39Phantom$forgetMutableForFluid(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! CallbackInfoReturnable is required! [INJECT Applicator Phase -> lib39-phantom.mixins.json:connectormod.present.MixinEntity from mod lib39_phantom -> Apply Injections ->  -> Inject -> lib39-phantom.mixins.json:connectormod.present.MixinEntity from mod lib39_phantom->`@Inject`::lib39Phantom$forgetMutableForFluid(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]

**Comment by Su5eD** [comment]
> Also, in the above log, I had to use Connector beta 40 instead of beta 41 as the latter wouldn't load Yttr's JiJ'd dependencies for some reason...!?

I've encountered this as well, it turned out to be a regression introduced by #926. It'll be fixed in the next update

**Comment by unilock** [comment]
> I tried running a locally built version of the provided Lib39 fork, but I'm getting an error when running it in my Connector dev env.

This is the `@Inject` it's having trouble with:
<img width="649" alt="image" src="https://github.com/Sinytra/Connector/assets/11802133/302ded7d-969b-47d4-b352-19c70fe958eb">

...but that method returns `void` (on Forge 47.1.3), so I'm not sure what the problem is? Does it want `CallbackInfoReturnable<Void>` or something??

<img width="624" alt="image" src="https://github.com/Sinytra/Connector/assets/11802133/f0a8baa1-5016-4885-a787-0da03338a7e7">

It, of course, works fine on my end...

Anyway, thanks for the fixes!
