### ISSUE TITLE
Enderman Overhaul crashes (both forge and fabric versions)

### ISSUE THREAD

**Issue by MCCrafter247** [Sinytra/Connector#996]
### Mod Name

Enderman Overhaul

### Mod Homepage

https://modrinth.com/mod/enderman-overhaul

### Minecraft version

1.20.1

### Describe the bug

Enderman Overhaul does not seem to work with Connector and the ConnectorExtras-compatible Geckolib. This is the case for both forge and fabric versions of the mod.

### Steps to reproduce

1. Install the latest versions of Connector, ConnectorExtras, Forgified Fabric API, Enderman Overhaul (Either forge or fabric version), Resourcefullib (I used the forge version), Resourcefulconfig (I used the forge version), and Geckolib (I used the fabric version for ConnectorExtras compat)
 
2. Run the game. In the case of the fabric version of Enderman Overhaul, it should crash on startup.

3. (If running the forge version) Try to view the corrupted shield in any menu. Searching the creative menu is what I tried. With the forge version, it should crash when the corrupted shield item is rendered (Regardless of whether it's in the world, your inventory, the creative menu, etc.)

### Logs

Crash with fabric version: https://pastebin.com/YsSwpnDi  Crash with Forge Version: https://pastebin.com/0drbG0Kw

### Additional context

All mods are up to date as of this post (for 1.20.1). 
Resourcefullib and Resourcefulconfig are dependencies for Enderman Overhaul, along with Geckolib. In both tests, I've used the forge version of Resourcefulconfig and Resourcefullib, not the fabric ones. I do not know if the fabric versions would change anything.
Both tests run on forge 47.1.3
Here are the exact files and versions I used, so that you have everything you need to properly recreate this.

Fabric version of Enderman Overhaul:

Connector-1.0.0-beta.41+1.20.1
ConnectorExtras-1.10.0+1.20.1
endermanoverhaul-fabric-1.20.1-1.0.4
fabric-api-0.92.0+1.11.5+1.20.1
geckolib-fabric-1.20.1-4.4.4
resourcefulconfig-forge-1.20.1-2.1.2
resourcefullib-forge-1.20.1-2.1.23

Forge version of Enderman Overhaul:

Connector-1.0.0-beta.41+1.20.1
ConnectorExtras-1.10.0+1.20.1
endermanoverhaul-forge-1.20.1-1.0.4
fabric-api-0.92.0+1.11.5+1.20.1
geckolib-fabric-1.20.1-4.4.4
resourcefulconfig-forge-1.20.1-2.1.2
resourcefullib-forge-1.20.1-2.1.23

As each version has a different issue, I've provided the logs for each respective crash.
I wasn't sure whether I needed to make two separate issue reports for the different versions or not. I hope this suffices!
I made sure to be as thorough as possible, but if I missed anything, let me know if you need any more information.

**Comment by Groupix05** [comment]
works well for me with Forge Geckolib, and I can still use Forge Geckolib for Fabric mods

**Comment by RoomAlex68** [comment]
Well, not all fabric mods that require Geckolib Fabric work with Geckolib Forge

**Comment by MCCrafter247** [comment]
> works well for me with Forge Geckolib, and I can still use Forge Geckolib for Fabric mods

I'm making a modpack that relies on the ConnectorExtras compat for Geckolib, meaning I have to use the fabric one in that instance. It's still an issue if it's incompatible with that.

**Comment by MCCrafter247** [comment]
> Well, not all fabric mods that require Geckolib Fabric work with Geckolib Forge

I did not use the forge Geckolib. I used the fabric one, since I need to do that to make many mods work through the ConnectorExtras Geckolib compat.

**Comment by MCCrafter247** [comment]
> Well, not all fabric mods that require Geckolib Fabric work with Geckolib Forge

Yeah. More or less this.

**Comment by Su5eD** [comment]
Works fine using the Forge version of Geckolib. For geckolib compat, please see #231
