### ISSUE TITLE
Some of Alex's Caves and Cataclysm models not appearing

### ISSUE THREAD

**Issue by Wo0f27** [Sinytra/Connector#999]
### Mod Name

L_ender's Cataclysm

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/lendercataclysm

### Minecraft version

1.20.1

### Describe the bug

Some models from certain mods are invisible

### Steps to reproduce

1.
2.
3.
...

### Logs

None

### Additional context

I was using the connector to use Marium's Soulslike mod(requires geckolib for fabric so i was using that) alongside L_ender's cataclysm. It doesnt crash but it makes some models from the cataclysm mod to not appear, also tried it with Alex's caves and some models are also invisible.  It doesnt crash but items are invisible. I'm using the beta41 of the connector

Mods that could have caused it:
geckolib-fabric-1.20.1-4.4.4
soulslike-weaponry-1.1.3-1.20-fabric
L_Enders_Cataclysm-1.90 -1.20.1

**Comment by RoomAlex68** [comment]
You need to install connector extras

**Comment by Wo0f27** [comment]
> You need to install connector extras

It worked now, thank you
